### ISSUE TITLE
Eas Build failed installing pod in iOS

### ISSUE THREAD

**Issue by p4bl1t0** [expo/eas-cli#1001]
### Build/Submit details page URL

https://expo.dev/accounts/pablo_botta/projects/ema/builds/09c4a9d5-1b89-4f3a-9852-4419c6196a31

### Summary

Trying to build for iOS the build failed installing pods. Android builds works. "expo build:ios" also works.

### Managed or bare?

Managed

### Environment

➜  ema-app git:(master) ✗ npx expo-env-info
npx: instaló 1 en 2.646s

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 26, 27, 28, 29, 30, 31
        Build Tools: 26.0.1, 28.0.3, 29.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Google Play Intel x86 Atom, android-30 | ARM 64 v8a, android-30 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.18 => 0.16.18 
      expo: ^41.0.0 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
      react-native-web: ^0.14.13 => 0.14.13 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Error output

Installing react-native-webview (11.2.3)
[!] The following Swift pods cannot yet be integrated as static libraries:
The Swift pod `AndesUI` depends upon `PureLayout`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
The Swift pod `MercadoPagoSDK` depends upon `MLUI`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
[stderr] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `0A6E9DDD2BDD44DC99AE3B8D` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
pod exited with non-zero code: 1

### Reproducible demo or steps to reproduce from a blank project

Not yet

**Comment by wkozyra95** [comment]
It looks like issue with `blackbox-vision-react-native-mercadopago-px` 

based on https://github.com/BlackBoxVision/react-native-mercadopago-px/issues/45 it's not supported out-of-the-box in the managed workflow. you need to wait for them to support it or implement config plugins yourself

It works on android, because android does not require any manual step during installation https://react-native-mercadopago-px.blackbox-vision.tech/docs/intro/
