### ISSUE TITLE
How to change the icon of my iOS app for the Expo + EAS

### ISSUE THREAD

**Issue by RengeRenge** [expo/eas-cli#1006]
### Build/Submit details page URL

https://expo.dev/accounts/renge/builds/988c3299-6322-4bec-a400-e59e74e3831e

### Summary

I only have one picture (1024x1024), which is specified by the app.json (./icon.png), but Expo does not perform the task of setting icon.

### Managed or bare?

Bare

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.2.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.4 - /usr/local/bin/npm
      Watchman: 2021.08.02.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 21, 23, 25, 26, 27, 28, 30
        Build Tools: 26.0.2, 27.0.3, 29.0.2, 30.0.2
        System Images: android-21 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.3 => 0.66.3 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.3.0
    Expo Workflow: bare

### app.json
{
  "name": "AwesomeProject",
  "displayName": "AwesomeProject",
  "expo": {
    "name": "YOUHA",
    **"icon": "./icon.png",**
    "version": "1.0.0",
    "slug": "your-app-slug",
    "ios": {
      "bundleIdentifier": "xj.reactjs.native.example.AwesomeProject",
      "buildNumber": "1.0.0"
    },
    "android": {
      "package": "com.yourcompany.yourappname",
      "versionCode": 1
    }
  }
}

### eas.json
{
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  },
  "cli": {
    "version": ">= 0.47.0"
  }
}

### other
Xcode project has only one Images.xcassets, there is only one empty AppIcon image set

**Comment by wkozyra95** [comment]
For a bare project, you need to follow platform specific instructions this is not expo or even react-antive specific

I recommend to google for a better tutorial, but In short
- for iOS you need to add images to AppIcon image set (you need to generate different resolutions of that icon)
- for Android you need to add appropriate assets in res directory

You can run `expo prebuild`  to apply values from app.json, but depending on why you are using bare project and what changes you made it might not work or override your changes

**Comment by adwidianjaya** [comment]
Hello, I encountered similar issue. Do iOS icon will be applied only for bare project, or do we have solution for managed workflow? Since build output (using eas) didn't reflect what I specify in icon field under app.json.

**Comment by wkozyra95** [comment]
> Do iOS icon will be applied only for bare project, or do we have solution for managed workflow?

The other way around, values in app.json are applied only in a managed workflow. For bare projects, you need to configure it in the native code.
