### ISSUE TITLE
EAS Build failing to find database after successful build but Expo Build works fine

### ISSUE THREAD

**Issue by staghouse** [expo/eas-cli#1008]
### Test Repo

https://github.com/staghouse/expo-sqlite-starter

### Summary

I have a project that uses `expo-sqlite`, the implementation follows the steps in the documentation and my local dev environemnt and Expo Build CLI works fine to find this database (and subsequently makes my app work fine) however, when using EAS Build, I can log an error at that step to get the database and am met with an error (below). This happens only during EAS CLI Build, including building for simulator but not Expo CLI Build.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.22.10 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.3.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Service that creates the database:

```js
export default class DatabaseService extends ComponentService {
  instance = null;
  dbName: string = 'AllPrintings.sqlite';
  sqlDir: string = FileSystem.documentDirectory + 'SQLite';

  /**
   * Asynchronously create a folder and download local database to it
   * for the SQLite package to perform operations on.
   *
   * @param setErrorViewState State setter for ErrorView
   */
  async getDatabase(setErrorViewState: (value: string) => {}): Promise<SQLite.WebSQLDatabase | void> {
    try {
      if (!(await FileSystem.getInfoAsync(this.sqlDir)).exists) {
        await FileSystem.makeDirectoryAsync(this.sqlDir);
      }

      await FileSystem.downloadAsync(
        Asset.fromModule(require('../assets/database/AllPrintings.sqlite')).uri,
        this.sqlDir + '/' + this.dbName
      );

      return SQLite.openDatabase(this.dbName);
    } catch (err: any) {
      setErrorViewState('DatabaseService: ' + err.toString());
    }
  }
}
```

File structure:

<img width="232" alt="Screen Shot 2022-03-09 at 9 20 03 PM" src="https://user-images.githubusercontent.com/1939508/157575484-46a99f87-5f21-4ef9-9247-88e03b8193c9.png">

Error (Generated from my app from the catch block):

![Screen Shot 2022-03-08 at 1 23 54 PM](https://user-images.githubusercontent.com/1939508/157575542-8816364d-4e55-4a6d-9a51-5f1a0f9a96b9.jpg)

**Comment by wkozyra95** [comment]
check out this troubleshooting guide https://docs.expo.dev/build-reference/troubleshooting/

It looks like there is some reference to your local path, which of course does not exists on eas builder. Also, remember that ifiles that are gitignored will not be uploaded to eas builder

**Comment by staghouse** [comment]
@wkozyra95 So just the clarify, my database is not git ignored because its rather small. I did a couple things in that guide that I had not seen before:

1. `expo run:ios --configuration Release`
Output: 
```
⚠️  Pods/boost-for-react-native: iOS@8.0 deployment version mismatch, expected >= 9.0 <= 14.4.99
⚠️  Pods/HMSegmentedControl: iOS@7.0 deployment version mismatch, expected >= 9.0 <= 14.4.99
```

2. `eas login`, then `eas build --local`, then select `ios`
Output:
```
[INSTALL_DEPENDENCIES] [4/4] Building fresh packages...
[INSTALL_DEPENDENCIES] $ husky install
[INSTALL_DEPENDENCIES] fatal: not a git repository (or any of the parent directories): .git
[INSTALL_DEPENDENCIES] Done in 12.54s.
[READ_APP_CONFIG] Using app configuration:
[READ_APP_CONFIG] **Omitted**
[PREPARE_CREDENTIALS] Preparing credentials
[PREPARE_CREDENTIALS] Creating keychain
[PREPARE_CREDENTIALS] Preparing credentials for target **omitted**
[PREPARE_CREDENTIALS] Getting distribution certificate fingerprint
[PREPARE_CREDENTIALS] Writing distribution certificate to /var/folders/ph/6rhgg4f138s68wrbhvbq6csh0000gn/T/683ecaa8-3765-46a7-ad53-189c4239e18f.p12
[PREPARE_CREDENTIALS] Importing distribution certificate into the keychain
[PREPARE_CREDENTIALS] Initializing provisioning profile
[PREPARE_CREDENTIALS] Validating whether distribution certificate has been imported successfully
[PREPARE_CREDENTIALS] Destroying keychain - /var/folders/ph/6rhgg4f138s68wrbhvbq6csh0000gn/T/turtle-v2-1dd0a512-4431-4593-9d5e-fcb388661714.keychain
[PREPARE_CREDENTIALS] 
Error: Distribution certificate with fingerprint **omitted** hasn't been imported successfully
    at Keychain.ensureCertificateImported (/Users/lakae002/.npm/_npx/23134/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/ios/credentials/keychain.js:54:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async IosCredentialsManager.prepareTargetCredentials (/Users/lakae002/.npm/_npx/23134/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/ios/credentials/manager.js:96:13)
    at async IosCredentialsManager.prepare (/Users/lakae002/.npm/_npx/23134/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/ios/credentials/manager.js:54:41)
    at async /Users/lakae002/.npm/_npx/23134/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/ios.js:25:20
    at async BuildContext.runBuildPhase (/Users/lakae002/.npm/_npx/23134/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/context.js:48:28)
    at async Object.iosBuilder (/Users/lakae002/.npm/_npx/23134/lib/node_modules/eas-cli-local-build-plugin/node_modules/@expo/build-tools/dist/builders/ios.js:24:29)
    at async Object.buildIosAsync (/Users/lakae002/.npm/_npx/23134/lib/node_modules/eas-cli-local-build-plugin/dist/ios.js:45:27)
    at async Object.buildAsync (/Users/lakae002/.npm/_npx/23134/lib/node_modules/eas-cli-local-build-plugin/dist/build.js:28:32)
    at async main (/Users/lakae002/.npm/_npx/23134/lib/node_modules/eas-cli-local-build-plugin/dist/main.js:16:9)

Build failed
Distribution certificate with fingerprint **omitted** hasn't been imported successfully
    Error: npx exited with non-zero code: 1
```

**Comment by gregfenton** [comment]
I notice in the error text from your app that the path includes `......./assets/assets/database/......`.  Is that the correct directory?

It might be helpful if you could post a super-simple repo via GitHub so that to reproduce the issue it is a simple matter of:

1. Clone the repo
2. Run the command XXX 
3. See the error by doing YYY

**Comment by staghouse** [comment]
I'll see about making a public MVE but the "assets/assets" is certainly weird but that error only occurs for EAS Build, not Dev mode or Expo Build

**Comment by staghouse** [comment]
Well thats the weird part, Expo CLI Build finds that file just fine, ive never had a problem before EAS Build.

Heres my implementation (ive changed a few naming conventions of the database file so the error still applies just with a different database name):

**Base Service:**
```js
export default class ComponentService {
  // Needs to be overridden to avoid conflicts on extension
  static instance: any = null;

  /**
   * Gets a single instance of the service across components
   */
  static getService(): any {
    if (this.instance === null) {
      this.instance = new this();
    }

    return this.instance;
  }

  /**
   * Wipes out instance
   */
  static resetInstance() {
    this.instance = null;
  }
}
```

**Database Service extending ComponentService**
```js
import * as FileSystem from 'expo-file-system';
import * as SQLite from 'expo-sqlite';
import { Asset } from 'expo-asset';
import ComponentService from './ComponentService';

export default class DatabaseService extends ComponentService {
  instance = null;
  dbName: string = 'db.db';
  sqlDir: string = FileSystem.documentDirectory + 'SQLite';

  /**
   * Asynchronously create a folder and download local database to it
   * for the SQLite package to perform operations on.
   *
   * @param setErrorViewState State setter for ErrorView
   */
  async getDatabase(setErrorViewState: (value: string) => {}): Promise<SQLite.WebSQLDatabase | void> {
    try {
      if (!(await FileSystem.getInfoAsync(this.sqlDir)).exists) {
        await FileSystem.makeDirectoryAsync(this.sqlDir);
      }

      await FileSystem.downloadAsync(
        Asset.fromModule(require('../assets/database/db.db')).uri,
        this.sqlDir + '/' + this.dbName
      );

      return SQLite.openDatabase(this.dbName);
    } catch (err: any) {
      setErrorViewState('DatabaseService: ' + err.toString());
    }
  }
}
```

**Usage**
```js
import DatabaseService from '../services/DatabaseService';

const databaseService = DatabaseService.getService();

databaseService.getDatabase(/*setErrorViewState, basically just a setter for various states so render the error seen above*/)
```

**metro.config.js**

```js
const { getDefaultConfig } = require('expo/metro-config');

const defaultConfig = getDefaultConfig(__dirname);

defaultConfig.resolver.assetExts.push('db');

module.exports = defaultConfig;
```

**app.config.js**
```
export default {
  expo: {
    ...
    assetBundlePatterns: [
      "assets/images/*",
      "assets/database/*"
    ],
    ...
  }
};
```

**Comment by wkozyra95** [comment]
I didn't notice that the error refers to the path in the simulator filesystem, so probably the path is fine that it refers to your user

It probably worked in `expo build` because `Asset.fromModule(require('../assets/database/db.db')).uri,` referred to the asset hosted on expo cdn, try using https://docs.expo.dev/versions/latest/sdk/filesystem/#filesystemcopyasyncoptions instead of `downloadAsync`

**Comment by staghouse** [comment]
@wkozyra95 No luck on that, I tried a few different options all met with errors locally.

```js
await FileSystem.copyAsync({
  from: FileSystem.documentDirectory + 'assets/database/db.db',
  to: FileSystem.documentDirectory + 'SQLite/db.db',
});
 ```
 
![Screen Shot 2022-03-17 at 8 11 19 AM](https://user-images.githubusercontent.com/1939508/158806103-8729fb7c-2aa4-40fb-89b5-1c475e40b0ab.jpg)

```js
await FileSystem.moveAsync({
  from: FileSystem.documentDirectory + 'assets/database/db.db',
  to: FileSystem.documentDirectory + 'SQLite/db.db',
});
```

![Screen Shot 2022-03-17 at 8 14 30 AM](https://user-images.githubusercontent.com/1939508/158806583-c78831cd-d152-48e6-a923-26b89bb5bcf0.jpg)

Ive always tried a few variations including the following, all met with similiar errors:

```js
await FileSystem.copyAsync({
  from: FileSystem.documentDirectory + 'assets/database/db.db',
  to: FileSystem.documentDirectory + 'SQLite',
});
```
```js
await FileSystem.copyAsync({
  from: FileSystem.documentDirectory + 'assets/database/db.db',
  to: FileSystem.documentDirectory + 'SQLite/',
});
```

**Comment by staghouse** [comment]
Here is a test repo to reproduce the issue (it uses downloadAsync since that was my initial problem).

**Comment by staghouse** [comment]
I've found the "EAS Build" way to resolve this issue. I use `expo-asset`'s `useAssets` hook to bundle up the database so that it can properly be referenced:

```js
import React, { useEffect } from 'react';
import { useAssets } from 'expo-asset';
import * as FileSystem from 'expo-file-system';
import * as SQLite from 'expo-sqlite';

export default () => {
  const databaseName = 'db.db';
  const sqlDir = FileSystem.documentDirectory + 'SQLite';

  const [assets, assetsError] = useAssets([require('../assets/database/db.db')]);

  useEffect(() => {
    const getDatabase = async (databaseAsset) => {
      try {
        if (!(await FileSystem.getInfoAsync(sqlDir)).exists) {
          await FileSystem.makeDirectoryAsync(sqlDir);
        }
  
        await FileSystem.copyAsync({
          from: databaseAsset.localUri,
          to: sqlDir + '/' + databaseName,
        });
  
        return SQLite.openDatabase(databaseName);
      } catch (err) { /* Handle error */ }
    };

    if (assets && assets[0] && !assetsError) {
      const databaseAsset = assets[0];

      getDatabase(databaseAsset).then(database => {
        // Use the database
      }).catch(err => { /* Handle error */ });
    }
  }, [assets]);

  return ( /* Whatever your app looks like */ );
}
```

Since bundled assets are read only we have to use `copyAsync` to move the database over the the proper SQLite directory location and reference the `localUri` of the database asset. This is a little bit free-hand since my implementation uses services to use FileSystem and SQLite but this is the general idea to get the asset bundled and referenced properly.

**Comment by Cleymi** [comment]
Hola, tenía un problema parecido y revisando `tsconfig.json`  en los módulos de `expo-sqlite,` observé que necesitaba la dependencia de `expo-module-scripts`.
mi problema se solucionó instalando esa dependencia,  no sé si sea tu caso, pero deberías intentarlo.


![imagen_2022-08-03_140610278](https://user-images.githubusercontent.com/45864853/182689171-a629b73f-2a88-4cc8-bdc7-3f0d5768b523.png)

**Comment by winterOmii** [comment]
According to your method, I solved my problem, thank you!

Others can try to solve the CDN download problem by excluding DB files from the optimization.

"assetBundlePatterns": [
      "assets/images/*"
    ],
