### ISSUE TITLE
AssertionError: AndroidManifest.xml is missing the required MainApplication element

### ISSUE THREAD

**Issue by thespacemanatee** [expo/eas-cli#1019]
### Summary

Updated to `eas-cli@0.48.0` and ran `eas update:configure` and got `AssertionError: AndroidManifest.xml is missing the required MainApplication element`. `eas build` is also causing the same error.

### Managed or bare?

Bare

### Environment

```
expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.1.4 - ~/.npm-global/bin/npm
      Watchman: 2022.02.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: Chipmunk 2021.2.1 Beta 4 Chipmunk 2021.2.1 Beta 4
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.66.4 => 0.66.4 
    npmGlobalPackages:
      eas-cli: 0.38.3
      expo-cli: 4.13.0
    Expo Workflow: bare
```

### Error output

```
Configured app.json for EAS Update
    AssertionError: AndroidManifest.xml is missing the required MainApplication element
    Code: ERR_ASSERTION
```

### Reproducible demo or steps to reproduce from a blank project

Just update to latest `eas-cli@0.48.0` and run `eas update:configure` or `eas build`

**Comment by thespacemanatee** [comment]
Update: newest `eas-cli@0.48.0` seems to have broken my `Supporting/Expo.plist`, every time I do `eas build` it adds some new lines which are causing `Expo.plist` to be malformed.

**Comment by TomasSestak** [comment]
same here

**Comment by dogfootruler-kr** [comment]
I had the same issue, after rolling back to `eas-cli@0.47.0` it worked fine.
FYI: I am using the dynamic configuration with app.config.js and it seems like this is the reason but I'm not sure.

**Comment by MaltesBytes** [comment]
Does anyone have a solution?

**Comment by TomasSestak** [comment]
i also rolled back

**Comment by thespacemanatee** [comment]
Hi, this is still happening and seems like many people are facing this issue.

**Comment by Akhr0** [comment]
Hi, any news about it ?

**Comment by wkozyra95** [comment]
> ### Reproducible demo or steps to reproduce from a blank project
> Just update to latest eas-cli@0.48.0 and run eas update:configure

Those steps do not reproduce the issue, please provide a reproducible example

**Comment by thespacemanatee** [comment]
@wkozyra95 We did not manage to reproduce it with a clean setup but it is not working for many of us since `0.48.0`. Would it not be sufficient to look at the changes introduced by `0.48.0` since `0.47.0`? This is blocking us from updating to even `0.49.0`. Is this issue going to be ignored because we are unable to produce a repro?

**Comment by TomasSestak** [comment]
maybe related to flavours?

**Comment by wkozyra95** [comment]
@thespacemanatee without any way to reproduce that or even basic information about the structure of your project I don't see what we can do. The error happens because either 
- AndroidManifest.xml has sth unusual
- you have multiple AndroidManifest.xml and the wrong one is picked up

**Comment by thespacemanatee** [comment]
@wkozyra95 There is nothing special about the structure of my project. We barely touch any native code and if we do it is to install Reanimated 2. We did not create any extra `AndroidManifest.xml` and the only edits were done to it are by other expo libraries like `expo-splash-screen` and `expo-update`. Something must have been broken in `0.48.0`, or at least a breaking change was not documented. Here is my `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.cams.cams_app">
  <uses-permission android:name="android.permission.INTERNET"/>
  <application android:name=".MainApplication" android:allowBackup="false" android:icon="@mipmap/ic_launcher" android:label="@string/app_name" android:roundIcon="@mipmap/ic_launcher_round" android:theme="@style/AppTheme">
    <meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="https://u.expo.dev/xxxx-xxxx-xxxx-xxxx"/>
    <meta-data android:name="expo.modules.updates.ENABLED" android:value="true"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="ALWAYS"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS" android:value="0"/>
    <meta-data android:name="expo.modules.updates.EXPO_RUNTIME_VERSION" android:value="1.0.0"/>
    <activity android:name=".MainActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:exported="true" android:launchMode="singleTask" android:screenOrientation="sensorPortrait" android:theme="@style/Theme.App.SplashScreen" android:windowSoftInputMode="adjustPan">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="cams-app"/>
      </intent-filter>
      <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:host="camsapp.page.link" android:scheme="https"/>
      </intent-filter>
      <intent-filter>
        <action android:name="android.nfc.action.NDEF_DISCOVERED"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="cams-app"/>
      </intent-filter>
      <intent-filter android:label="filter_medication">
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:host="medication" android:scheme="cams-app"/>
      </intent-filter>
    </activity>
  </application>
</manifest>
```

**Comment by txvnt** [comment]
This is also happening for us. We do have flavours set up if that helps.

**Comment by wkozyra95** [comment]
> Something must have been broken in 0.48.0, or at least a breaking change was not documented

There was no breaking change, before 0.48.0 `update:configure` did not modify your native files(you had to do it on your own) and now it does. Also, it technically does not break anything because this is the last step of configuring so it should behave the same as the older version but the command exits with an error

> We did not manage to reproduce it with a clean setup

The simplest way to reproduce it is just to copy your repo, replace your js code with minimal app.json and remove any sensitive information and keys.

**Comment by thespacemanatee** [comment]
> > Something must have been broken in 0.48.0, or at least a breaking change was not documented
> 
> There was no breaking change, before 0.48.0 `update:configure` did not modify your native files(you had to do it on your own) and now it does. Also, it technically does not break anything because this is the last step of configuring so it should behave the same as the older version but the command exits with an error
> 
> > We did not manage to reproduce it with a clean setup
> 
> The simplest way to reproduce it is just to copy your repo, replace your js code with minimal app.json and remove any sensitive information and keys.

We get the exact same error with just `eas build`. We are also using multiple flavours on Android. Will try to create a repro later but since there are many reports something is clearly not well documented.

**Comment by thespacemanatee** [comment]
@wkozyra95 Found the root cause of the problem for you, it is due to updating `@expo/config-plugins` from `4.0.16` to `4.0.18`. Not sure what changed here as I cannot find the repository for `@expo/config-plugins` but it stopped working for some of us, presumably projects with multiple flavours since that's been mentioned quite a few times. I already did the investigation work so I hope that you guys would take this issue more seriously.

![Screenshot 2022-04-10 at 9 18 52 PM](https://user-images.githubusercontent.com/6837599/162620100-cb3dc067-d209-4335-92c3-7a9324c780dd.png)

**Comment by wkozyra95** [comment]
> Found the root cause of the problem for you, it is due to updating

As I already explained in a previous comment, it's not a regression, because the native code was not configured in previous versions of eas-cli.

> I already did the investigation work so I hope that you guys would take this issue more seriously.

We are not able (and probably never will) handle all cases for a bare project because the number of different ways to configure your project, automatic configuration is a best-effort approach that assumes similarity to the ejected project, we are willing to add support for cases do not work currently when possible, but we need a way to reproduce it. We are providing tooling that automates a lot of stuff, but for bare projects, developers are ultimately responsible for native code/configuration, if you don't want to deal with stuff like that, I recommend looking into managed workflow, with config plugins support most of the use cases can be migrated to managed.

Also, error message is quite clear, "AndroidManifest.xml is missing the required MainApplication element", given that it worked for me when I copied your manifest, I'm assuming that manifest you provided is in a different location. `eas-cli` assumes it's under `android/app/src/main/AndroidManifest.xml`

> let me know if you still need a repro and provide me a way to send it to you privately

you can invite me to the private repo if it's not sth that you are comfortable sharing publicly

**Comment by wkozyra95** [comment]
> Again, the problem still occurs when we use eas build NOT eas update:configure.

The issue is about `update:configure`, you did not mention anywhere here that android build does not work for you.

> I'm not sure why the finger is constantly being pointed in our direction when we have not touched or moved any native code from where it originally was.

Other than "There is nothing special about the structure of my project" which is very vague statement in itself you did not mention that, plus if the issues were not related to your changes, it would also happen in managed projects, which as far as I'm aware is not happening.

> Not to be rude or anything but see for yourself in the repro I provided.

I ran `update:configure` and both ios and android builds and everything works, both AndroidManifext.xml and Expo.plist file were updated correctly.

- were you able to reproduce the issue on the repo you provide or is it just stripped version of your repo?
- try creating new clone of the repo and build from there(macos filesystem is not  case sensitive, but git is, sometimes it's causing issues that are not reproducible outside because changes are not visible in git)

**Comment by thespacemanatee** [comment]
@wkozyra95  Refer to my following comments. Will be updating issue to reflect that as well, sorry if it wasn't clear but this is affecting ALL eas commands on Android.

> Update: newest `eas-cli@0.48.0` seems to have broken my `Supporting/Expo.plist`, every time I do `eas build` it adds some new lines which are causing `Expo.plist` to be malformed.

> We get the exact same error with just eas build. We are also using multiple flavours on Android. Will try to create a repro later but since there are many reports something is clearly not well documented.

As for your comment:

> were you able to reproduce the issue on the repo you provide or is it just stripped version of your repo?

Yes, I was able to reproduce this issue on my repro. What I did was I cloned my project in a different folder and removed all the javascript files and obfuscated some potentially sensitive stuff, and then ran `eas build --profile preview -p android` and got the same error. I will try your second suggestion but in the mean time, do you have any other suggestions? I've looked into the git history of `eas-cli` and the `@expo/config-plugins` is quite suspect. I don't think this issue has anything to do with `before 0.48.0 update:configure did not modify your native files` like you mentioned. Thanks!
