### ISSUE TITLE
can't build internal distribution profile due to icloud error 

### ISSUE THREAD

**Issue by louisholley** [expo/eas-cli#1022]
### Build/Submit details page URL

https://expo.dev/accounts/sanctuary/projects/migrate-app-dev/builds/30a8c8b4-e3d9-44a4-b579-c7b5f7507165

### Summary

when running `eas build` with a profile that has `"distribution": "internal"` I'm getting the following error:

```
Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key "iCloudContainerEnvironment": expected one of {Development, Production}, but no value was provided" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key "iCloudContainerEnvironment": expected one of {Development, Production}, but no value was provided}
```

I came across [this](https://github.com/expo/eas-cli/issues/693) issue which seems to suggest that the issue is fixed but it's still happening for me.

running `expo config --type introspect` shows that the required entitlement is undefined:

<img width="479" alt="image" src="https://user-images.githubusercontent.com/4563781/158571376-342552bb-351b-41ff-b742-9d6f3c08fb11.png">

can anyone offer any advice?

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.3 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.5.2 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ^44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.48.1
      expo-cli: 5.2.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Set up a managed expo app with `expo-document-picker` and `ios.usesIcloudStorage: true` in the config and try to build a profile with `"distribution": "internal"`

**Comment by louisholley** [comment]
@wkozyra95 i'm using `DocumentPicker.getDocumentAsync()` so not sure how to specify that prop, any advice?

**Comment by wkozyra95** [comment]
that value goes in your app.json in the same place where `appleTeamId`

**Comment by louisholley** [comment]
@wkozyra95 tried that and it still didn't work, same error as before

**Comment by wkozyra95** [comment]
> using the latest version of document picker

I just checked your build logs you are using `10.1.0` and latest is `10.1.3`

**Comment by louisholley** [comment]
@wkozyra95 wild...i could have sworn i updated it. thanks so much!!
