### ISSUE TITLE
If root folder is called react-native, build fails with : While resolving module `react-native/Libraries/Core/Devtools/getDevServer`, the Haste package `react-native` was found. 

### ISSUE THREAD

**Issue by sebastienlabine** [expo/eas-cli#1025]
### Summary

If the root folder for the eas-build is called react-native, the build fails with "While resolving module `react-native/Libraries/Core/Devtools/getDevServer`, the Haste package `react-native` was found"

### Managed or bare?

managed

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.5.5 - ~\Documents\Github\smartbills\packages\mobile\node_modules\.bin\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30
        Build Tools: 30.0.3
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    npmPackages:
      @expo/metro-config: ^0.3.12 => 0.3.12
      expo: ^44.0.0 => 44.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Error output

While resolving module `react-native/Libraries/Core/Devtools/getDevServer`, the Haste package `react-native` was found.

### Reproducible demo or steps to reproduce from a blank project

- expo init
- name project react-native
- try to build with eas-build with "distribution": "internal",

**Comment by wkozyra95** [comment]
If your package is called react-native and you have react-native in dependencies it's broken by definition, if you run `expo init react-native` expo-cli will not allow you to create a project like that.

**Comment by sebastienlabine** [comment]
didn't knew that! I renamed the folder that's why. Hope this thread could be usefull for some people, because it works well in dev but failed on the build step.
