### ISSUE TITLE
eas build -p ios messes up apple app identifier

### ISSUE THREAD

**Issue by ibrag474** [expo/eas-cli#1030]
### Summary

Eas build -p ios warns that provisioning profile is no longer valid and asks if you want to reuse the original profile and you can answer yes or no, but it will update/generate provisioning profile anyway and it results in settings change in your app's identifier at developer.apple.com. EAS should not mess around with this settings, I cannot build and upload my app to app store because of this issue, I have to use old expo build:ios.

### Managed or bare?

Managed

### Environment

 expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.13 Linux Mint 20.3 (Una)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      npm: 8.4.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    IDEs:
      Android Studio: AI-211.7628.21.2111.8092744
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: ~0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: managed

### Error output

✔ Fetched Apple provisioning profiles
Provisioning profile (id: Y8J48D83ML) is no longer valid
✔ Fetched Apple provisioning profiles
✔ Provisioning Profile - ID: Y8J48D83ML
    Name: *[expo] com.app.app AppStore 2022-03-24T22:47:34.269Z
    Expiry: Sun Feb 26 2023 
  Would you like to reuse the original profile? … yes
✔ Fetched Apple provisioning profiles
✔ Updated provisioning profile (5VN7SZYV8L) with distribution certificate (TW8T4ZUN8G)

### Reproducible demo or steps to reproduce from a blank project

1. Set up app identifier at developer.apple.com;
2. Run eas build -p ios;
3. Go to developer.apple.com and see that your identifier settings was changed by eas build.

**Comment by wkozyra95** [comment]
I'm not sure what you mean by changing identifiers? The only thing besides generating credentials that cli is doing is to synchronize capabilities in appstore for your app id with entitlements configured in app.json (or dependencies that support it).

You can disable that behavior with env `EXPO_NO_CAPABILITY_SYNC=1`
https://docs.expo.dev/build-reference/ios-capabilities/

**Comment by ibrag474** [comment]
Yes, that was my problem. I used usesIcloudServices, fact that it works in bare workflow only remained unnoticed by me until now. I added:

> "entitlements": {
>         "com.apple.developer.icloud-services": ["CloudKit"],
>         "com.apple.developer.icloud-container-environment": "Production",
>         "com.apple.developer.icloud-container-identifiers": ["iCloud.com.app.app"] 
>  } 

and now it works as expected. But it's still warns that `Provisioning_ profile (id: LZZB55VR9Y) is no longer valid` all the time and asks if I want to reuse the original profile. Is it normal?

**Comment by wkozyra95** [comment]
> But it's still warns that Provisioning_ profile (id: LZZB55VR9Y) is no longer valid all the time and asks if I want to reuse the original profile. Is it normal?

does it still happen if you answer no when it asks you to reuse the existing profile?

**Comment by ibrag474** [comment]
> > But it's still warns that Provisioning_ profile (id: LZZB55VR9Y) is no longer valid all the time and asks if I want to reuse the original profile. Is it normal?
> 
> does it still happen if you answer no when it asks you to reuse the existing profile?

If I reply no, it asks if I want to generate new provisioning profile, y -> generates new profile, n -> asks for manualy generated profile. No matter what I answer the warning persists

**Comment by wkozyra95** [comment]
It shouldn't be happening, but as far as I remember those icloud entitlements are not fully supported, so it looks like every time you run build it's updating app id which requires you to update profile. If you just snwear no when asked to login to apple it should work

@EvanBacon Just to make sure, is this expected behavior?
If I add those icloud sentiments like @ibrag474 above app id is updated every time, I'm getting
```
✔ Synced capabilities: Enabled: iCloud
✔ Synced capability identifiers: Linked: iCloud.com.app.app
```

**Comment by seba9999** [comment]
Any news on that one ? 
Seems that it's linked to iCloud use.

I'm using expo [DocumentPicker](https://docs.expo.dev/versions/latest/sdk/document-picker/).

- I've got ``"usesicloudstorage": true`` in my `app.json`
- I also have this configured in my app identifier : 
![image](https://user-images.githubusercontent.com/14869447/162447718-544cb356-8a7c-44b9-920c-d9c57ac40bd2.png)

 --> And in the pop-up (Oppened by clicking "Edit") With ``iCloud.<your_bundle_identifier>`` as mentionned in the doc :
 
![image](https://user-images.githubusercontent.com/14869447/162447956-59429aa8-a396-4710-91b3-c510b25035e7.png)


But still facing that provisionning profile invalidation 😢

**Comment by seba9999** [comment]
@ibrag474 Why did you close this ? 🤔

**Comment by kelley-sharp** [comment]
@seba9999 @wkozyra95, a new post for this issue can be found at https://github.com/expo/eas-cli/issues/1073. You will have until 4/25 before https://github.com/expo/eas-cli/issues/1030 is deleted. Sorry for the inconvenience!
