### ISSUE TITLE
EAS build's icon with a slight offset.

### ISSUE THREAD

**Issue by JorensM** [expo/eas-cli#1031]
### Summary

Hello, so I made an app and decided to build it using EAS. Everything is fine, except one thing that irks me is that the app's icon has a slight offset.

As you can see in the following screenshot, the icon has a slight offset to the right.

![Screenshot_20220325-112938_One UI Home](https://user-images.githubusercontent.com/17122123/160094570-144226d9-2b24-4475-96f4-d004c3295bca.jpg)

And this is the image file that I'm using when building the app. It's perfectly centered.

![adaptive-icon1](https://user-images.githubusercontent.com/17122123/160094650-7abff69a-ebe8-4a9c-81c9-865fe2ea36e1.png)

### Managed or bare?

Bare

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30, 31
        Build Tools: 30.0.2, 30.0.3
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

You can try building my app from [https://github.com/JorensM/crypto-notifier](https://github.com/JorensM/crypto-notifier) and see if the same problem occurs. It's a small build.

**Comment by wkozyra95** [comment]
> It's perfectly centered.

The meaning of what center means is not that obvious, but the center of the icon on the screenshot and center of the file you provided seems to be the same
