### ISSUE TITLE
Detection of managed workflow for iOS platform doesn't play well with local packages

### ISSUE THREAD

**Issue by lacasseio** [expo/eas-cli#1033]
### Summary

We have a managed Expo project that have a local native package. We use the custom dev-client feature to build the client on Android which works fine. Our local native package gets compiled in the dev-client and everything works on Android. However, on iOS, the workflow detection logic is broken for that particular case. Trying to build on the command line I get the following error:
```
    Error: We did not find any schemes in the Xcode project, make sure that at least one scheme is marked as "shared" in Xcode, and that it's listed in the output of "xcodebuild -list" command
```

I dug around the code base and narrow it down to `resolveWorkflowAsync`, particularly at [this line](https://github.com/expo/eas-cli/blob/ad2d8e80f007da47886e50540e1ebbc37a555f2d/packages/eas-cli/src/project/workflow.ts#L17). The detection uses `IOSConfig ` from `@expo/config-plugins` which calls the [`getPBXProjectPath`](https://github.com/expo/expo-cli/blob/main/packages/config-plugins/src/ios/Paths.ts#L189). Instead of detecting the bare/managed workflow by checking `ios` folder from the project root path, it list all PBX projects which includes our local native package located in the `packages` folder off the project root. The [ignore paths are static](https://github.com/expo/expo-cli/blob/main/packages/config-plugins/src/ios/Paths.ts#L8) preventing any customization.

Instead of having multiple different, unequal, detection algorithm for managed/bare workflow, why not give the option in the `eas.json` file to specify the workflow type? Alternatively, the detection algorithm should not rely on finding all possible PBX projects but instead look at the conventional location, i.e. `ios`/`android`, for the bare workflow.

The current solution is to patch the eas-cli project to remove this bug.

### Managed or bare?

managed with custom dev-client

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
      Watchman: 2022.02.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 26, 28, 29
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.1.1 4.1.1
      Xcode: 13.2/13C90 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.3.0 => 8.3.0 
      expo: 41.0.1 => 41.0.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.5.0 => 16.5.0 
      react-native: 0.63.4 => 0.63.4 
      react-navigation: 4.0.10 => 4.0.10 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 4.12.1
    Expo Workflow: managed

### Error output

Error: We did not find any schemes in the Xcode project, make sure that at least one scheme is marked as "shared" in Xcode, and that it's listed in the output of "xcodebuild -list" command

### Reproducible demo or steps to reproduce from a blank project

The explanation above should be enough to figure out the problem.

**Comment by lacasseio** [comment]
To add a bit more to this problem, patching `eas-cli` to properly detect a managed workflow is only part of the solution. During `expo prebuild`, `expo-cli` uses `@expo/config-plugins` package which crashes the patching step because the native package located in `packages` is queried for an "application" which only contains a "library" as it's a react-native native module. The unfortunate solution was to use the luckily ignored base path `vendor` instead of `packages`. This is not a good solution but a workaround to a deeper problem with `expo-cli` and `eas-cli`.

**Comment by wkozyra95** [comment]
I'm not sure if I understand correctly your project structure,  I'm assuming here that the native code/library you are adding is not in the `ios` directory.

If we match those files only in ios directory will this solve your problem?

**Comment by wkozyra95** [comment]
it should be fixed in:
- remote builds
- local builds if you have latest eas-cli
- expo prebuild in latest expo-cli
