### ISSUE TITLE
White screen instead of Splash Screen only after upload to stores

### ISSUE THREAD

**Issue by dlamon1** [expo/eas-cli#1036]
### Summary

Instead of Splash Screen is a white screen, which only happens in production after uploaded to both the Play Store and App Connect. This bug does not appear when building an .apk and installing manually on a mobile device. 

Steps I have taken include: 

Renaming splash screen png file and changing the path in app.json

### Managed or bare?

Managed

### Environment

    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 8.5.4 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
      react-navigation: 4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.48.1
      expo-cli: 5.3.0
    Expo Workflow: managed

### Error output

I am using Sentry, I do not get an error message. 

### Reproducible demo or steps to reproduce from a blank project

I do not know what is appropriate to put here, please advise. 

Thank you for the help, this is a very time consuming bug to work with.

**Comment by dlamon1** [comment]
This is my code 

```
import * as SplashScreen from "expo-splash-screen";

SplashScreen.preventAutoHideAsync();


function App() {
  return (
        <View style={{ width: 300, height: 300, backgroundColor: "yellow" }}>
            <Text style={{ color: "#d8d8d8", fontSize: 36, fontWeight: "bold" }}>
               5
            </Text>
        </View>;
    )
}

export default App;
```

**Comment by dlamon1** [comment]
package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "safe": "expo install react-native-safe-area-context"
  },
  "dependencies": {
    "@aws-amplify/auth": "4.5.0",
    "@react-native-async-storage/async-storage": "1.15.0",
    "@react-native-community/hooks": "2.6.0",
    "@react-native-community/masked-view": "0.1.11",
    "@react-native-community/netinfo": "7.1.3",
    "@react-navigation/bottom-tabs": "6.2.0",
    "@react-navigation/native": "6.0.8",
    "@react-navigation/native-stack": "6.5.0",
    "@react-navigation/stack": "6.1.1",
    "@sentry/integrations": "^6.19.3",
    "@sentry/react-native": "3.3.3",
    "amazon-cognito-identity-js": "5.2.8",
    "aws-amplify": "4.3.18",
    "aws-amplify-react-native": "5.0.3",
    "crypto-js": "3.1.9-1",
    "expo": "44.0.6",
    "expo-app-loading": "1.3.0",
    "expo-application": "4.0.1",
    "expo-constants": "13.0.1",
    "expo-crypto": "10.1.1",
    "expo-device": "4.1.0",
    "expo-linear-gradient": "11.0.3",
    "expo-secure-store": "11.1.0",
    "expo-splash-screen": "0.14.1",
    "expo-status-bar": "1.2.0",
    "expo-updates": "0.11.6",
    "expo-web-browser": "10.1.0",
    "ionicons": "5.5.2",
    "mobx": "6.3.2",
    "mobx-react": "7.2.0",
    "moment": "2.29.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-loader-spinner": "4.0.0",
    "react-native": "0.64.3",
    "react-native-elements": "3.4.2",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-linear-gradient": "2.5.6",
    "react-native-loading-spinner-overlay": "2.0.0",
    "react-native-pager-view": "5.4.9",
    "react-native-reanimated": "2.3.1",
    "react-native-redash": "16.2.3",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "3.10.1",
    "react-native-switch-selector": "2.1.4",
    "react-native-tab-view": "3.1.1",
    "react-native-vector-icons": "9.1.0",
    "react-native-web": "0.17.1",
    "react-navigation": "4.4.4",
    "react-navigation-stack": "2.10.4",
    "react-number-format": "4.6.3",
    "sentry-expo": "^4.0.5",
    "validator": "13.6.0"
  },
  "devDependencies": {
    "@babel/core": "7.17.8",
    "@babel/preset-typescript": "7.1.0"
  },
  "private": true
}

```

**Comment by dlamon1** [comment]
`
{
  "expo": {
    "name": ""**************",",
    "slug": ""**************",",
    "version": "1.1.2",
    "orientation": "portrait",
    "userInterfaceStyle": "dark",
    "icon": "./assets/icon.png",
    "backgroundColor": "#1e1e1e",
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": ""**************",",
            "project": ""**************",",
            "authToken": ""**************","
          }
        }
      ]
    },
    "splash": {
      "image": "./assets/splash2.png",
      "resizeMode": "cover",
      "backgroundColor": "#1e1e1e"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "**************",
      "splash": {
        "resizeMode": "cover"
      }
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#1e1e1e"
      },
      "package": "***********",
      "permissions": [],
      "splash": {
        "resizeMode": "native"
      },
      "userInterfaceStyle": "dark",
      "versionCode": 37
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": ["sentry-expo"]
  }
}

`

**Comment by dlamon1** [comment]
Update, I have created a new project with `expo init` and copied over the old files. I have created a new app in both the Play Store and App Store Connect and uploaded the new bundles from the new project. There is still a white screen instead of the splash screen. Sorry to sound like a grown baby complaining about a free service, but I have now delayed the release of my app for 2 weeks now because of this bug.

**Comment by dlamon1** [comment]
Ok I have removed all of the dependencies, node modules, and .lock file except for the following and still a white screen. 

  ```
"dependencies": {
    "expo": "~44.0.0",
    "expo-app-loading": "1.3.0",
    "expo-splash-screen": "0.14.1",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-loader-spinner": "4.0.0",
    "react-native": "0.64.3",
    "sentry-expo": "^4.0.5"
  },
  "devDependencies": {
    "@babel/core": "7.17.8",
    "@babel/preset-typescript": "7.1.0"
  },
```

**Comment by dlamon1** [comment]
I will pay $300 to whoever can fix this bug.

**Comment by dlamon1** [comment]
Running the app in production mode via expo start throws the following error

Failed to load all assets
```

ABI44_0_0RCTFatal
__37-[ABI44_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start
0x0

```

**Comment by kbrandwijk** [comment]
You can't use a hook outside of a functional component, so the code snippet you shared is probably erroring out.

**Comment by emehmet** [comment]
Hi,
This seems to be due to the npm packages installed on your computer or the difference in the environment variables.

In npm packages, try to remove the ^ and ~ characters at the beginning of the version numbers and make your build process like that.

These characters will try to update to the last updated version of the npm package. 
Chek this url
[https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json](url)

One or more of the packages in npm package.json may have been updated and there may be errors in this update. Or maybe a feature has been deprecated.

Other than that, make sure that the environment variables, cocoapods, nodejs versions are the same as those on your local computer.

**Comment by kbrandwijk** [comment]
Closing as there was no further reply from OP.

**Comment by samih-sghier** [comment]
having the same issue, how did you resolve it OP?

**Comment by diegocuehdz** [comment]
Same issue here, how did you solve it

**Comment by munroAllie** [comment]
Having the exact same issue. Happened after doing a fresh npm install because I got the following complaint. 
```
Some dependencies are incompatible with the installed expo package version:
 - @react-native-async-storage/async-storage - expected version: 1.17.11 - actual version installed: 1.18.1
 - @stripe/stripe-react-native - expected version: 0.23.3 - actual version installed: 0.27.2
 - lottie-react-native - expected version: 5.1.4 - actual version installed: 5.1.6
 - react-native - expected version: 0.71.8 - actual version installed: 0.71.4
```
Even if I revert. to my original packages (which don't have^ or ~) I still get the white screen. I can get text to render down until my stack.navigator component. After that nothing renders but still get console.logs from the components which should render.

**Comment by cseelus** [comment]
Same since upgrading to Expo 49.

**Comment by dilshod1d** [comment]
Same problem who fixed the issue?

**Comment by 0xAskar** [comment]
Has anyone fixed this issue? we had to upgrade our project from expo 47 to 49, and after the splash screen, we get a white screen but with normal logs, as in the startup screen logs are still there. Anyone have any solution?

**Comment by Lurstre99** [comment]
I am experiencing the same issue,  but only on IOS EAS stand-alone build. local builds using `expo run start` works fine. But as the IOS build shows a white screen instead of a splash-screen. On expo 49 and using expo-splash-screen@0.20.5

**Comment by suantony** [comment]
same here, how to fix it ?

**Comment by xcenai** [comment]
This has become such an annoying issue.

**Comment by AlexBThomsen** [comment]
Same issue works fine locally but no the build store version...

**Comment by PowerForward08** [comment]
ran into the same problem, does anybody have the solution?
