### ISSUE TITLE
Could not create task ':app:prepareLintJarForPublish' - It is too late to set storeFilePath

### ISSUE THREAD

**Issue by hkaras19** [expo/eas-cli#1040]
### Summary

My project runs perfectly on local android and iOS emulators. However, upon uploading to eas, the build fails with the error below. With a little research into the eas build process, the error appears to originate from the eas-build.gradle file which is created by eas. See the code snippet below for the section in question. Additionally, the final command run by eas (where the error occurs) is './gradlew :app:bundleRelease,' which I am able to run locally without any errors.

Note: I get the same error running the build on my machine with the --local flag

<img width="634" alt="Screen Shot 2022-03-29 at 8 23 13 AM" src="https://user-images.githubusercontent.com/44104172/160679432-e47003f6-54e4-425c-8d7f-d6cd0b89890d.png">

### Managed or bare?

Bare

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 17.8.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-native: 0.67.2 => 0.67.2 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: bare

### Error output

Welcome to Gradle 7.2!
Here are the highlights of this release:
- Toolchain support for Scala
- More cache hits when Java source files have platform-specific line endings
 - More resilient remote HTTP build cache behavior
For more details see https://docs.gradle.org/7.2/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build

[stderr] FAILURE: Build failed with an exception.
[stderr] * Where:
[stderr] Script '/home/expo/workingdir/build/android/app/eas-build.gradle' line: 32
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':app'.
[stderr] > Could not create task ':app:prepareLintJarForPublish'.
[stderr]    > It is too late to set storeFilePath
[stderr]      It has already been read to configure this project.
[stderr]      Consider either moving this call to be during evaluation,
[stderr]      or using the variant API.
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 1m 14s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

### Reproducible demo or steps to reproduce from a blank project

eas build -p android
eas build -p android --local

**Comment by wkozyra95** [comment]
it should be fixed now for cloud builds, local build will be fixed in the next eas-cli release

**Comment by hkaras19** [comment]
That did it! Thanks for the help.

**Comment by eswarant** [comment]
I got the same issue. Refer error log

A problem occurred configuring project ':app'.
> Could not create task ':app:prepareLintJarForPublish'.
   > It is too late to set storeFilePath
     It has already been read to configure this project.
     Consider either moving this call to be during evaluation,
     or using the variant API.
![image](https://github.com/expo/eas-cli/assets/5981774/0d7ed724-ed4a-46ec-a21a-26fbc4453a00)
