### ISSUE TITLE
eas submit --platform ios fails with `Cannot read property 'attributes' of undefined`

### ISSUE THREAD

**Issue by jvgaeta** [expo/eas-cli#1042]
### Build/Submit details page URL

[Submit Link on Expo](https://expo.dev/accounts/panama-app/projects/panama_prod/submissions)

### Summary

eas submit to ios fails transiently with error `Cannot read property 'attributes' of undefined`. This occurs every other day or so but seems to fix itself if I just wait and try again later. This may actually be a transient issue with the apple, but I'm not sure from the error message.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.13 - /usr/local/bin/npm
      Watchman: 2022.02.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.48.2
      expo-cli: 5.3.0
    Expo Workflow: managed

### Error output

Cannot read property 'attributes' of undefined
    Error: Submission failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Reproducible demo or steps to reproduce from a blank project

eas submit --platform ios --profile production

This issue is transient, so it's not easily reproducible.

submit section of eas.json (retracted company details)

```
  "submit": {
    "production": {
      "ios": {
        "appName": "xxx",
        "companyName": "xxx"
      }
    }
  }
```

**Comment by wkozyra95** [comment]
Can you provide a full stack trace by running eas with `DEBUG=*` ?

Also, you might want to add ascAppId in your submit profile, if I remember correctly with your current setup you are prompted every time for apple credentials.

**Comment by jvgaeta** [comment]
I haven't seen this issue for a few days now. Closing as I just use transporter when submit doesn't work.
