### ISSUE TITLE
EAS update

### ISSUE THREAD

**Issue by billnbell** [expo/eas-cli#1052]
### Summary

Getting error on eas update...

> eas update:configure

💡 The following process will configure your project to run EAS Update. These changes only apply to your local project files and you can safely revert them at any time.
✔ Linked to project @billnbell/theclub (​[https://expo.dev/accounts/billnbell/projects/theclub​](https://expo.dev/accounts/billnbell/projects/theclub%E2%80%8B))
✔ Set updates.url value, to "https://u.expo.dev/fe216081-8e44-46cf-ba34-sskjjkjk" in app.json
✔ Set Android runtimeVersion to ""1.0.0"" in app.json
✔ Set iOS runtimeVersion to ""1.0.0"" in app.json
✔ Configured app.json for EAS Update
    TypeError: Cannot read properties of undefined (reading 'android') 
Getting error
app.json is
{
  "name": "TheClub",
  "displayName": "TheClub",
  "runtimeVersion": "1.0.0",
  "android": {},
  "ios": {},
  "updates": {
    "url": "https://u.expo.dev/fe216081-8e44-46cf-ba34-sdjskdjskdjie2je2"
  }
}

### Managed or bare?

bare

### Environment

normal react-native 0.68

### Error output

see above

### Reproducible demo or steps to reproduce from a blank project

see above

**Comment by kbrandwijk** [comment]
Issue resolved through direct support.

**Comment by daominhsangvn** [comment]
Any solution here? I just got the same issue :(

**Comment by ohheyitskartik** [comment]
facing the same issue here, can anyone mention a solution for this. 
cc @kbrandwijk

**Comment by daominhsangvn** [comment]
@ohheyitskartik  
Revert the `app.json` to original then add the following:
```
{
  ...
  expo: {}
}
```
then re-run the command
