### ISSUE TITLE
Update fails error 1

### ISSUE THREAD

**Issue by billnbell** [expo/eas-cli#1056]
### Build/Submit details page URL

billnbell

### Summary

eas update 
✔ Linked to project @billnbell/theclub (​https://expo.dev/accounts/billnbell/projects/theclub​)
✔ Which branch would you like to publish on? › feature/red - current update: N/A
✔ Please enter an update message. … New
✖ Failed to build bundle!
    Error: /Users/bill/theclub/TheClub/node_modules/expo/bin/cli.js exited with non-zero code: 1

It errors. weird!

### Managed or bare?

bare

### Environment

npx: installed 1 in 0.71s

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.3/bin/yarn
      npm: 6.14.10 - ~/.nvm/versions/node/v12.18.3/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: ^0.68.0 => 0.68.0 
    npmGlobalPackages:
      expo-cli: 5.3.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

/a

**Comment by kbrandwijk** [comment]
Please run `EXPO_DEBUG=1 expo export --experimental-bundle` and share the output.
