### ISSUE TITLE
EAS build local is very slowly

### ISSUE THREAD

**Issue by erichou668** [expo/eas-cli#1062]
### Summary

I use the command “npx eas-cli build --profile preview --platform ios --local --non-interactive” to build iOS ipa, but it is very slowly, it cost 30 minutes. How to save the build time?

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.15.1 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 28, 30, 32
        Build Tools: 29.0.2, 30.0.3, 32.0.0, 32.1.0
        Android NDK: 24.0.8215888
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.2/13C90 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.3.0 => 8.3.0 
      expo: ^42.0.0 => 42.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      eas-cli: 0.50.0
      expo-cli: 5.3.0
    Expo Workflow: managed

### Error output

build is slowly

### Reproducible demo or steps to reproduce from a blank project

execute the command "npx eas-cli build --profile preview --platform ios --local --non-interactive"

**Comment by wkozyra95** [comment]
most cloud builds take about 10-15 minutes if you are using mostly expo packages. If takes longer for you then there might be 2 reasons:
- you are using some heavy libraries that take long time to compile
- your machine or network access is a bottleneck (how long cloud builds take?)

I see you are using SDK 42, I don't remember for sure, but I think most of the expo packages on that sdk were built from sources, where now a lot of those are provided as prebuild binaries, so upgrading to the latest SDK might help

**Comment by bombillazo** [comment]
Hey, this issue was related ot local builds, not cloud server builds. I am also seeing this behavior, my `expo start` and `expo run-<PLATFORM>` commands build and install the app super fast, yet `eas cli build --local` takes 10 times as much time.

**Comment by wkozyra95** [comment]
@bombillazo `expo start` does not build the application just js. `expo run:*` builds in Debug mode which is a bit faster, plus it reusing stuff that was built previously, if you delete android/ios dir and clean xcode cache it would take just as long as local builds.

**Comment by shashankGS10** [comment]
I observed that today, it took me 1 hour 53 mins.
<img width="1107" alt="Screenshot 2022-11-10 at 1 30 11 AM" src="https://user-images.githubusercontent.com/49735860/200929289-cfec6018-3b9b-485f-bb8f-b19e33162e48.png">

It asked me to go for enterprise edition or so, is there anyway to avoid this much latency in the build. To revert back to non expo environment is quite tedious too. Any suggestions?

**Comment by wkozyra95** [comment]
@shashankGS10 There is a limited amount of resources for a free tier, so at peek times of the day there is a queue, it's mostly affects iOS. You can check how long a queue is during the day here https://expo.dev/eas-build-status

You can either:
- Subscribe to a production plan https://expo.dev/pricing
- Build on your own machine with `eas build --local`

**Comment by MkrierPharmanity** [comment]
hello , i have the same issue with android

running a local build take 15 min with a ryzen 3950x 16c/32t oc at 4.5ghz, 64gb ram , nvme ssd and a 1g fiber optic link

anyway i can speed up the build ?

**Comment by boblitex** [comment]
My iOS build takes about 4 minutes on my M2 Pro for local builds, but android takes about 30 minutes, usually gets stuck here: `tput of task ':expo-updates:copyReleaseExpoManifest' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.5.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
[RUN_GRADLEW] > Task :app:validateSigningRelease
[RUN_GRADLEW] > Task :app:mergeReleaseArtProfile
[RUN_GRADLEW] > Task :expo-modules-core:downloadBoost
[RUN_GRADLEW] Download https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
[RUN_GRADLEW] > Task :app:mergeDexRelease
[RUN_GRADLEW] > Task :expo-modules-core:downloadDoubleConversion
[RUN_GRADLEW] Download https://github.com/google/double-conversion/archive/v1.1.6.tar.gz
[RUN_GRADLEW] > Task :app:compileReleaseArtProfile
[RUN_GRADLEW] > Task :expo-modules-core:downloadFolly
[RUN_GRADLEW] Download https://github.com/facebook/folly/archive/v2021.07.22.00.tar.gz
[RUN_GRADLEW] > Task :expo-modules-core:prepareFolly
[RUN_GRADLEW] > Task :expo-modules-core:prepareDoubleConversion`

**Comment by monochrome-yeh** [comment]
@MkrierPharmanity , I found the method to speed up build performance: 
https://reactnative.dev/docs/build-speed

we might try this afterward we could check it's better or not

**Comment by ahmed-hounati** [comment]
@MkrierPharmanity the command in that url is use react... not expo?

**Comment by shashankGS10** [comment]
Let me try. Thanks though it looks I'll get my solution here. ?
🫡

**Comment by janroures** [comment]
hello, any updates on this? ios local builds take like 30 minutes, while android local builds take less than 5. anything we can do to speed up build times?

**Comment by demeralde** [comment]
Why is this issue closed? It hasn't been fixed and no one has provided any decent workarounds. This needs to be fixed.

**Comment by a-eid** [comment]
EAS android build takes almost 50 minutes on github actions, is there anyway to speed it up ?

<img width="1118" alt="Screenshot 2024-12-01 at 1 02 28 AM" src="https://github.com/user-attachments/assets/71a89786-9783-4317-8d2c-db9336b0cfdb">

**Comment by janwirth** [comment]
Use local builds.

**Comment by alisabry22** [comment]
iam still having same issue on android with local build why it takes this long time? I have MacBook Pro m4 pro so I excepted  to be lower than that

**Comment by oniseun** [comment]
I have the same issue on android local build as well. Takes about an hour and then fails :( .
So frustrating

**Comment by Blackfaded** [comment]
Having the same issue. on github action it runs 1h13min. then errors with no space left. ios is running fine in like 20 minutes.
