### ISSUE TITLE
Found multiple *.entitlements. Choose the wrong one.

### ISSUE THREAD

**Issue by mhammerc** [expo/eas-cli#1065]
### Summary

Hello !

I am experimenting migrating from a fully bare react-native to a semi-managed workflow (reproducible expo prebuild). It looks really nice, congrats on the work achieved!

Let's call my app W for the following.

My app "W" have two targets:
- OneSignal(.entitlements)
- W(.entitlements)

When I build using eas build for iOS, I get a warning there is two entitlements files. One for OneSignal, one for W (my app).

But, EAS choose the OneSignal entitlement instead of mine. I guess it's because W comes after OneSignal (alphabetical order).

I use associated domains.

W.entitlements properly have associated domains configured as I set them in app.config.js.

I can not build with EAS because it disable associated domains on my app ID/profiles because it uses OneSignal entitlements which doesn't have it.

If I delete the OneSignal entitlement, it choose the right entitlement and configure my App ID/Profiles properly but I can not build anymore.

### Managed or bare?

bare but reproducible (expo prebuild, then expo run:ios)

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 3.4.1 
    Binaries:
      Node: 16.14.2
      Yarn: 1.22.18
      npm: 8.5.0
    Managers:
      CocoaPods: 1.11.3
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 30, 31
        Build Tools: 30.0.2, 31.0.0
        System Images: android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Bumblebee 2021.1.1 Patch 3 Bumblebee 2021.1.1 Patch 3
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: 44.0.6 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: bare

### Error output

» ios: paths-entitlements: Found multiple *.entitlements file paths, using "ios/OneSignalNotificationServiceExtension/OneSignalNotificationServiceExtension.entitlements". Ignored paths: ["ios/W/W.entitlements"]

### Reproducible demo or steps to reproduce from a blank project

Create a project named W.

Add onesignal.

Perform eas build.

**Comment by mhammerc** [comment]
I searched for settings into app.json to choose which entitlement I want but couldn't find any.

I wrote a patch (`patch-package`) which ignore the first entitlement found (OneSignal) and keep only the second one.

Looks like it works for me (not tested on a real device yet)! But this is only a workaround. If anyone have the same problem, you can use the patch.

Patch filename: `patches/@expo+config-plugins+4.1.0.patch`

```patch
diff --git a/node_modules/@expo/config-plugins/build/ios/Paths.js b/node_modules/@expo/config-plugins/build/ios/Paths.js
index 9630c9e..306bf5b 100644
--- a/node_modules/@expo/config-plugins/build/ios/Paths.js
+++ b/node_modules/@expo/config-plugins/build/ios/Paths.js
@@ -309,7 +309,7 @@ function getAllEntitlementsPaths(projectRoot) {
 
 
 function getEntitlementsPath(projectRoot) {
-  const [using, ...extra] = getAllEntitlementsPaths(projectRoot);
+  const [_, using, ...extra] = getAllEntitlementsPaths(projectRoot);
 
   if (extra.length) {
     warnMultipleFiles({

```

**Comment by mhammerc** [comment]
Here is documentation from OneSignal about this: https://github.com/OneSignal/onesignal-expo-plugin/blob/main/IOS_CREDENTIALS_EAS.md#complex-setup-explanation

**Comment by wkozyra95** [comment]
This is a known problem, we are working on support for target-specific entitlements

**Comment by mhammerc** [comment]
> This is a known problem, we are working on support for target-specific entitlements

Thank you! Great job you're doing on here!

**Comment by mhammerc** [comment]
I confirm it seems to works on my end 👍. Thanks!
