### ISSUE TITLE
Build run in CI hangs on "Waiting for builds to complete"

### ISSUE THREAD

**Issue by nickfla1-mxm** [expo/eas-cli#1067]
### Summary

When executing the build and submit process on CI, the latter hangs until the build has completed, effectively blocking the pipeline until it has finished or it times out, wasting resources and money.

As it's not needed to wait for the build to be completed it could be useful to disable this behaviour on CIs by default or via a 
cli flag.

### Managed or bare?

bare

### Environment

Azure Pipelines

### Reproducible demo or steps to reproduce from a blank project

`eas build --auto-submit --platform all --profile production --non-interactive`

**Comment by dsokal** [comment]
@nickfla1-mxm what EAS CLI are you using?

**Comment by dsokal** [comment]
```
eas build --help
start a build

USAGE
  $ eas build [-p android|ios|all] [--json] [--profile <value>] [--non-interactive] [--local] [--output <value>] [--wait] [--clear-cache] [--auto-submit | --auto-submit-with-profile <vache] [--auto-submit | --auto-submit-with-profile <value>]

FLAGS
  -p, --platform=(android|ios|all)
  --auto-submit                            Submit on build complete using the submit profile with the same name as the build profile
  --auto-submit-with-profile=PROFILE_NAME  Submit on build complete using the submit profile with provided name
  --clear-cache                            Clear cache before the build
  --json                                   Enable JSON output, non-JSON messages will be printed to stderr
  --local                                  Run build locally [experimental]
  --non-interactive                        Run command in non-interactive mode
  --output=<value>                         Output path for local build
  --profile=PROFILE_NAME                   Name of the build profile from eas.json. Defaults to "production" if defined in eas.json.
  --[no-]wait                              Wait for build(s) to complete

DESCRIPTION
  start a build

COMMANDS
  build:cancel     cancel a build
  build:configure  configure the project to support EAS Build
  build:inspect    inspect the state of the project at specific build stages, useful for troubleshooting
  build:list       list all builds for your project
  build:submit     submit app binary to App Store and/or Play Store
  build:view       view a build for your project
```

Change the command to:
`eas build --auto-submit --platform all --profile production --non-interactive --no-wait`

**Comment by ChromeQ** [comment]
Also ran into this, it is a bit silly that non-interactive waits for the build, the default should have been no-wait in my opinion

**Comment by billsbooth** [comment]
If we're using the no-wait flag, is there an easy to notify slack when build is done?

**Comment by pavlos-sqds** [comment]
@billsbooth, you can probably do it with EAS webhooks instead. https://docs.expo.dev/eas/webhooks/
