### ISSUE TITLE
eas-cli@0.51.0 is now available, please upgrade

### ISSUE THREAD

**Issue by dcesca** [expo/eas-cli#1075]
### Summary

I'm running versione 0.48.1 (obtained with: eas -v )

When I try to build with a message appears:
eas-cli@0.51.0 is now available, please upgrade.

I then run npm install -g eas-cli but the new version isn't installed and the old version is still there.
Is there another method to install the latest release?

### Managed or bare?

Bare with plugins

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 29.0.2, 29.0.3
        System Images: android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
    npmPackages:
      expo: ~43.0.0 => 43.0.1
      react: 17.0.1 => 17.0.1
      react-dom: ^17.0.2 => 17.0.2
      react-native: 0.64.3 => 0.64.3
      react-native-web: ^0.17.5 => 0.17.5
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Nothing

**Comment by wkozyra95** [comment]
Most likely you installed eas-cli twice, with yarn and npm, so you are updating one version but using the other one. I recommend using npm for global install, because yarn sometimes resolves dependencies incorrectly.

**Comment by LouisSyfer** [comment]
Same issue, no solution
impossible to upgrade to @3.6.1...

**Comment by XiscoB** [comment]
I'm having the same issue with eas-cli@3.7.2 

Tried to uninstall, do as @wkozyra95 said:
> Most likely you installed eas-cli twice, with yarn and npm, so you are updating one version but using the other one. I recommend using npm for global install, because yarn sometimes resolves dependencies incorrectly.

 But still getting: 
```
 eas-cli@3.7.2 is now available, please upgrade.
Proceeding with outdated version
```

**Comment by carmenchapa** [comment]
I have the same issue. Trying to upgrade to eas-cli@3.7.2 but I'm stuck with:
`eas-cli/3.3.2 darwin-arm64 node-v16.19.0`

**Comment by carmenchapa** [comment]
I'm using mac but [this](https://stackoverflow.com/a/70736825) helped me to completely delete eas, then I could install the latest version
`which eas`
it outputs the dir
then go there and manually delete it
cc: @XiscoB @LouisSyfer

**Comment by LouisSyfer** [comment]
Thanks @carmenchapa ! 

I will try. 

Otherwise I use npx eas-cli, it's a bit longer but very useful (you'll have the latest version anyway)

**Comment by BlessingAdewale** [comment]
> I'm using mac but [this](https://stackoverflow.com/a/70736825) helped me to completely delete eas, then I could install the latest version `which eas` it outputs the dir then go there and manually delete it cc: @XiscoB @LouisSyfer

Please how did you install the latest version

**Comment by BlessingAdewale** [comment]
@carmenchapa After I deleted the eas file which I got through the "which eas" command, I can't install a new one. I get "bash:eas:commandnotfound"

**Comment by nakaamov** [comment]
**I'm getting the same error please help**

eas-cli@5.9.1 is now available.
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.

eas-cli/3.13.3 darwin-arm64 node-v21.4.0

**Comment by LouisSyfer** [comment]
@Lektrion @nakaamov 

Have a look here : https://forums.expo.dev/t/impossible-to-upgrade-eas-cli-version/73019 
And here : https://forums.expo.dev/t/impossible-to-upgrade-eas-cli-continuation-and-end/74541

**Comment by twwspes** [comment]
In my case, that's because of me using nvm to manage diff version of node while have multiple `eas-cli` being installed for diff node. Having uninstall all other versions in other nodes the eas-cli is now pointing to the correct one
