### ISSUE TITLE
EAS Update - ✖ Failed to published updates     CombinedError: [Network] Payload Too Large

### ISSUE THREAD

**Issue by jrwpatterson** [expo/eas-cli#1076]
### Summary

When I'm running EAS upgrade it is saying that the Payload is too large. When looking at the produced Dist folder it is only 16.1MB

### Managed or bare?

Bare

### Environment

 System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      Yarn: 3.2.0 - ~/.nvm/versions/node/v14.19.0/bin/yarn
      npm: 8.7.0 - ~/.nvm/versions/node/v14.19.0/bin/npm
      Watchman: 2022.03.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/josephpatterson/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30, 31, 32
        Build Tools: 29.0.2
        System Images: android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom, android-Tiramisu | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.51.0
      expo-cli: 5.3.1
    Expo Workflow: managed

### Error output

- Building bundle...
✔ Built bundle!
- Uploading assets...
✔ Uploaded assets!
- Publishing...
✖ Failed to published updates
    CombinedError: [Network] Payload Too Large

### Reproducible demo or steps to reproduce from a blank project

This is specific to our project.

**Comment by ide** [comment]
We would need to see the contents of the `dist` folder to see what the issue is. Updates are published to the public internet like a website, so in general the contents shouldn't be sensitive.

**Comment by karanmartian** [comment]
Hi, I am also facing issue of publishing updates. Its timing out on Asset upload. Could you please help urgently?

karan@karan-B550-VISION-D:~/repos/idrlapp$ eas update --auto
✔ Linked to project: xxxxxxxxxxxxxxxxx (not mentioning here)
✔ Created branch: master
✔ Created a channel: master pointed at branch: master.
✔ Built bundle!
✖ Failed to upload assets
    Error: Asset upload timed out. Please try again.

Here's my output of tree:
karan@karan-B550-VISION-D:~/repos/idrlapp$ tree --du -h dist
[ 16M]  dist
├── [7.5M]  assets
│   ├── [1.9K]  004c2bbb035d8d06bb830efc4673c886
│   ├── [5.4K]  014c4b109d7a0da794294db1aba7bae8
│   ├── [ 16K]  01c13e57ce441176c6faa88ef6a1d30e
│   ├── [3.7K]  02ace463d7634337b27f8c1cf1d7b51a
│   ├── [ 167]  02bc1fa7c0313217bde2d65ccbff40c9
│   ├── [2.6K]  0465a4dc9488af2189f38632c30916d9
│   ├── [3.1K]  04ee30a7c806bf2e435c890dedb89372
│   ├── [6.2K]  059bad53d2ed4d25ae92bc16c46df39f
│   ├── [3.8K]  05c7f5280f11d2bc35d5687de56a83b6
│   ├── [2.4K]  07069ee6f592b7d31693f303f5db073c
│   ├── [ 12K]  078d46b4daf3735833398c6f8814276a
│   ├── [ 540]  09a791be0aa03e3b35933c12cbf618f8
│   ├── [167K]  0be9fa8f2863998d1e52c84165976880
│   ├── [ 761]  0ea69b5077e7c4696db85dbcba75b0e1
│   ├── [5.5K]  0f41bf1abaf399c4c0965a9c61ed39a3
│   ├── [7.7K]  0fe266bfbdd45680f6017969cb7b0692
│   ├── [3.6K]  1306dffb89d8921e2b478737c7b9471c
│   ├── [ 13K]  140c53a7643ea949007aa9a282153849
│   ├── [5.3K]  14651cb55bd671c5f7d06a04370522dc
│   ├── [ 370]  152979eaec8c78c59aea0bd2708c62a1
│   ├── [ 25K]  1681f34aaca71b8dfb70756bca331eb2
│   ├── [9.3K]  16bcad632490d7560eae7d74f4162c1e
│   ├── [ 42K]  1896d72b45c24f7a1a6972c5778564e7
│   ├── [5.3K]  199a5a6b9f19646dd66ad8bb1dfe9cfe
│   ├── [ 17K]  1c92e07ac53b53430ce53d64f26ec4d2
│   ├── [ 258]  1cb2f4223eb470435ed99d4566c2ddbf
│   ├── [ 33K]  1f77739ca9ff2188b539c36f30ffa2be
│   ├── [5.8K]  1f800e791c126fa41d3e4b9b790b9bf4
│   ├── [1.9K]  21f3eab731baa5c6c1646ab0a06a8daf
│   ├── [ 494]  21fc2c04a8f670b62658a9726913bbc5
│   ├── [1.9K]  2327736b3ea09c41abfb69be1221f430
│   ├── [2.9K]  2369f935053ab3f254fb8e2bb2598a1d
│   ├── [4.7K]  23aa28b15a963006c370a3951017aaf2
│   ├── [5.3K]  245f4efcc05029630c7e5f8af6a1ae5f
│   ├── [7.0K]  25ca580e34afea803daa94866ab07c7d
│   ├── [ 57K]  26d8c85559d347f4009461dde23a69e5
│   ├── [ 10K]  26df812a9d250efa0723b8d4d35a1bd1
│   ├── [ 11K]  272478b8d531c1ec944da8be48d56b65
│   ├── [ 557]  28d7d912e888fdd70369f4cb6c0a430f
│   ├── [8.6K]  293e93339ac3b97ad7c25b26c38be271
│   ├── [4.5K]  2a0d89683fe6deb67d684934f1648035
│   ├── [ 522]  2a7caec15b44dc21d61ec0418f28d175
│   ├── [ 14K]  2ac94b0f6afd455b71e4d700ba040e2f
│   ├── [ 610]  2b978005eda9d90af267b4df0f90ac0c
│   ├── [ 559]  2bb064ef6a4ff2189a2f95e26fd7dc5f
│   ├── [9.6K]  2c12d78296e387a4a3a1ec58746e3c6f
│   ├── [7.2K]  2e9ebc8c8731a0961259cd7324f5c474
│   ├── [ 889]  2f4e3c34bdc214f95b347d05edb9565c
│   ├── [169K]  2ffc058ddedacfeaa23542026c8108e2
│   ├── [164K]  301fe70f8f0f41c236317504ec05f820
│   ├── [ 13K]  3055dc2befb1e3758da8340bbc0ff217
│   ├── [ 16K]  30b3889e52e520ab75ca2998181ec922
│   ├── [7.2K]  30c25de44a748159bfc5fbd373292fac
│   ├── [ 65K]  31b5ffea3daddc69dd01a1f3d6cf63c5
│   ├── [8.7K]  332964d18933b7e32f0db5a3684b9433
│   ├── [ 807]  3502dd7fb3dc2d242818428cabb8640a
│   ├── [ 207]  35ba0eaec5a4f5ed12ca16fabeae451d
│   ├── [ 134]  376d6a4c7f622917c39feb23671ef71d
│   ├── [ 69K]  3a2ba31570920eeb9b1d217cabe58315
│   ├── [7.0K]  3acccce148ee8bee3fb42136fa16f517
│   ├── [ 12K]  3ae373fa31cc2820113f2669cfc99195
│   ├── [131K]  3b89dd103490708d19a95adcae52210e
│   ├── [2.5K]  3c2780a5891c010c2a018672db469191
│   ├── [ 437]  3c28f6636e2baa5a29ee66beef98e7d7
│   ├── [ 20K]  3ff21d100a4e94ec2d4a42453ec2bde8
│   ├── [303K]  404e4373cba1344d28a4a257152ac8b8
│   ├── [1.2K]  40f3c197e3f2478499f7208ae42a57f5
│   ├── [ 157]  4114588a26828a4839a136dd5cef745d
│   ├── [ 560]  41e4150e6a963160206a65dd389599f5
│   ├── [ 13K]  425f5fd052f712b976dce9d80544f00b
│   ├── [1.3K]  42aab862284d8a08535cac9f1f6a03d9
│   ├── [ 15K]  4536835ca8247ef876a38684c5e44ea0
│   ├── [ 27K]  45ad2f667e09002e6ecaf5f5e212f2da
│   ├── [167K]  465d1affcd03e9c6096f3313a47e0bf5
│   ├── [7.1K]  4995ccb291433f4d5da52e3d1bbda832
│   ├── [ 934]  4b9cf0cc747e3c1abc541befa05b1e37
│   ├── [ 930]  4bdd6aad790c6c8370a06876ec7d31e1
│   ├── [ 134]  4cba04e93ea9d5ba83812b1e4ad284b7
│   ├── [ 442]  4e3a12e2d53fbce4bd9de5c7bc10217f
│   ├── [165K]  4f0b85f5b601a405bdc7b23aad6d2a47
│   ├── [1.4K]  50e36b9542e0572e42c10140cc3bec98
│   ├── [4.0K]  51671417ef20e0bbc32f0a2bc6edfa95
│   ├── [4.9K]  5170c1e6b26829b37daa13519846ca5c
│   ├── [ 913]  5223c8d9b0d08b82a5670fb5f71faf78
│   ├── [2.4K]  52eb6cee832a55271682334e74a0e4a0
│   ├── [3.9K]  532b6d0f28ef025780f863c9fe8e8af7
│   ├── [ 236]  5393073f061156373de9c127b93ca41e
│   ├── [5.2K]  540973dbc55ac4501667cc2eab071f46
│   ├── [ 309]  54bba6ee1b0e7a8b3a527035b34dd49c
│   ├── [6.3K]  563169bc7d0b5395ba2eb45bcebd37c5
│   ├── [ 13K]  57ea1e5cf18f2f23f5a09a43124ce8dd
│   ├── [ 432]  589110596c122152b9c5466e707b58eb
│   ├── [5.9K]  5a9dafd8736c0362f034fdbe4b0de653
│   ├── [7.3K]  5adca3251cb05fb0de17830b5c594d56
│   ├── [ 570]  5ae234d4265da61bf9e5c8cf59bab154
│   ├── [334K]  5b6c7cdfe0acd0fcc93cef7984a08740
│   ├── [ 554]  5de64672d77fb58f53f33b0b39497d42
│   ├── [ 10K]  5df5e43fd221cf6968c30ef53ab38785
│   ├── [ 22K]  5e5280dac769556303806f51414c12ff
│   ├── [ 589]  5ff0b3e684faa102fad43a26d247f1bd
│   ├── [198K]  605ed7926cf39a2ad5ec2d1f9d391d3d
│   ├── [163K]  6090d256d88dcd7f0244eaa4a3eafbba
│   ├── [ 247]  614a881a65c203755de7dc35ab6e2ed6
│   ├── [ 19K]  6174f291286db9ff22966d917bb2a6b0
│   ├── [9.7K]  62926b879ee4f1eea72c62422bef4d7f
│   ├── [2.1K]  62d28a5b80baed5d3b88becee469539e
│   ├── [2.6K]  63041111fe7cbe59f08d6afbc8248ba6
│   ├── [7.9K]  647577908c2b8245e321c23e5f2a01ac
│   ├── [ 26K]  656c5b7473e257c5f681bfcfa04e825c
│   ├── [ 926]  65be686237823bbb23cfd08d0da1dd1a
│   ├── [ 15K]  662cbd22bcf245bf15010a10234b86c4
│   ├── [ 247]  6688c459e497c72ef4601aa02b85cac3
│   ├── [ 18K]  678ffd1c8c3769aff642ed62c16ad897
│   ├── [ 27K]  67bf8f9e91bd1462d48bedbce86d2cfa
│   ├── [5.5K]  67dafd60fda959a1ab5697e6cd4a2791
│   ├── [ 16K]  6827f261416397cc9982ae6ca30ab770
│   ├── [ 12K]  68e641e9af8ec3072bb8f543dcbd93b3
│   ├── [5.0K]  6aade315b0e2c840f3ac8a5b31fa22de
│   ├── [ 451]  6fc8c2ec4abb9057b8fe6e788a3006c3
│   ├── [2.3K]  70b29501d68246924a7b8d05d928b57a
│   ├── [ 10K]  70d9a9f5f0cb76535d4d8bd705d9b684
│   ├── [3.0K]  71177cefe9de7cccf1c134349245a14a
│   ├── [ 22K]  71a02434a19616dc8361b7264ad5e258
│   ├── [4.6K]  71a18b72b90e30b46d5e76ccaa71c995
│   ├── [169K]  7384da64612787e3662872e9d19cbc2d
│   ├── [2.0K]  74a99ffd785563a18bf83f994696b1da
│   ├── [1.7K]  751c75e178df0c1d65563fa5244a6e18
│   ├── [1.9K]  7597a4d1074ae463efdda6d00e3c126e
│   ├── [ 552]  75bfe5f1314af84921bfd16f9e7c244f
│   ├── [ 100]  778ffc9fe8773a878e9c30a6304784de
│   ├── [3.8K]  77e3e1f249feac2f62fd6dab69b0f9dc
│   ├── [ 332]  78bcee18ea28b9b4ba26fb3dd9ca161f
│   ├── [ 10K]  7917e2eec1d87eae6eaa232adec7130f
│   ├── [1.1K]  79c3c3623bdfa681537a4e2c6d65491c
│   ├── [ 17K]  7a592d08f2ebb26f7f220dc8c6e39e98
│   ├── [ 12K]  7bd313de9856c7d31351eb2e371ed9cf
│   ├── [ 172]  7cc2706ac0658a498d96fdb523093cba
│   ├── [ 16K]  7cda8917740563da731082841ab0a14d
│   ├── [ 290]  7d40544b395c5949f4646f5e150fe020
│   ├── [2.1K]  7dd318a3bde58a95980c1d0dc73dd1e2
│   ├── [ 14K]  7f02140df8430d0de9b9faddb06e9762
│   ├── [ 557]  8263b2b2ef5b6ab2b44d3dc289c52522
│   ├── [ 557]  82a714ec1cdd86dbe42274e28b63c865
│   ├── [2.7K]  8543c7aec077337fa492de9020a2e8e9
│   ├── [4.9K]  860c9f4cb536a4544b3ae6142660be8f
│   ├── [ 481]  861bff67e9bd2b8f5b98bbea97526cde
│   ├── [9.0K]  883b0b831d200cce7750d54593f3e60e
│   ├── [ 588]  89ad16c947ab14bf99ed8dad6ed13b41
│   ├── [1.8K]  8a3bd4981c9ad5ecb7f81f7f2c7e11ab
│   ├── [2.0K]  8ab6a4ea826741b465dc61cf9a607e45
│   ├── [3.5K]  8b06661e8682a9a8f5630f15c0aa5319
│   ├── [ 684]  8b69b540b9beaf9b3d9edb897cbbaf99
│   ├── [ 557]  8bdd06f5373c834adf9e1650071c42e3
│   ├── [ 19K]  8c819b2f3d8c6dc7e0637c2441dc6fa2
│   ├── [6.3K]  8cf054ae9bb2790c6ebd77a60584a765
│   ├── [2.1K]  8d384a0089876f070c4df2b0f6aa2e28
│   ├── [225K]  8ef52a15e44481b41e7db3c7eaf9bb83
│   ├── [335K]  8f079b59ff6659b39b41bc2255c968b8
│   ├── [ 14K]  8f52682c02d9c20e292d016f5d64fb1b
│   ├── [6.5K]  9060388cb5b0e4865484a8c24583b24e
│   ├── [5.7K]  90746345242a7b2815c90738b459c681
│   ├── [ 14K]  90ce5a48bca4032c4a43f0d4394b2f43
│   ├── [8.0K]  9142d792e33c1d2964ac2db435c589c6
│   ├── [5.1K]  9370e8ffaade6a692ee4bb26b293a5de
│   ├── [3.6K]  93a054b741caaae1245235894e038d43
│   ├── [5.9K]  950ff9649d293d1b2f423c68134bde75
│   ├── [ 815]  963eee9d6dedd524ff4aa394e4e74405
│   ├── [ 12K]  97ab227bd06e71b718c177f9977a4440
│   ├── [6.8K]  9827265c66200b4c17446d0cab2c0d8a
│   ├── [1.9K]  985edb4ece584a93fa430e61be6dcc6a
│   ├── [6.9K]  99524679f4cab30970ef73ddb06bc5ca
│   ├── [2.6K]  9a420beec0afc41c955998d3ebf9eeba
│   ├── [4.0K]  9a6a802b83424fd7f14776e33314c9ba
│   ├── [1.9K]  9b8ea71a725684d96dbffe0199c33ca6
│   ├── [4.2K]  9bc3ddaee5a12c8eb8467beccd2ed6a5
│   ├── [ 967]  9c13e3a15b1ffe61c7f0b3ddd4390f06
│   ├── [163K]  9ece5b48963bbc96309220952cda38aa
│   ├── [ 343]  9f077e747533059d00c35952bc10c16e
│   ├── [ 23K]  9f44f9c13192ffcd438d66bed57f17b7
│   ├── [ 405]  a132ecc4ba5c1517ff83c0fb321bc7fc
│   ├── [3.7K]  a1483a544ada9b5f060747936e80dd25
│   ├── [ 22K]  a24ca482ca7144ea3491678e6b66aab2
│   ├── [3.6K]  a2e82dba84d48e59bdafba0f3b0e0ba8
│   ├── [2.6K]  a32e34bca6e2146f923ff3c7f4b08dfa
│   ├── [ 13K]  a379858069cfb4b76e7ef0f4a09a2709
│   ├── [6.0K]  a605cedca9b9f2f6e2c7a7c33cf1bfa1
│   ├── [ 14K]  a637d912892ba84e145f04e5e7647f15
│   ├── [ 10K]  a712fac20d79de8c15f69c383455396d
│   ├── [ 55K]  a76d309774d33d9856f650bed4292a23
│   ├── [2.9K]  a7b9dc9de5f8f1fb1afbef917619a5ac
│   ├── [ 31K]  a86ccb7d0e7a7f8719668db9c3e3e0b9
│   ├── [2.4K]  a98ace1d1953a94497e63ec4bf396dbf
│   ├── [4.8K]  a9a67e793e178cb26c8920f7110c9545
│   ├── [2.2K]  a9d3fe60409e2045f51bb1dc75ef145d
│   ├── [7.7K]  aa8aa9017e63d1bbd08479dd96d605ba
│   ├── [ 12K]  aacc435844ead5125b3e78de0cc54981
│   ├── [ 247]  abbd4565f7bcef8dc782a07aeaae4d2d
│   ├── [8.7K]  ae38db7a40627a4a26ecf55b9e253ef5
│   ├── [ 990]  af41a2007953bfbd0732551aba7cbb49
│   ├── [3.2K]  af42f710e4a10ba47c433efcc89f3889
│   ├── [162K]  b06871f281fee6b241d60582ae9369b9
│   ├── [7.9K]  b119e23c320733e4c992dbc0ffc23966
│   ├── [8.9K]  b264ab36e282ff9b16165a1e98dbb7e5
│   ├── [1.2K]  b2800abdab4203ee29f96c3ba14c1a96
│   ├── [165K]  b2d307df606f23cb14e6483039e2b7fa
│   ├── [241K]  b3263095df30cb7db78c613e73f9499a
│   ├── [ 15K]  b33dbf1534fdbc4951e0a266a3cdc36b
│   ├── [4.9K]  b3745e0fb3b7f02db6fd6c67e65e1e69
│   ├── [306K]  b49ae8ab2dbccb02c4d11caaacf09eab
│   ├── [1.9K]  b55ba28d1e0e8a911aa860afaa310320
│   ├── [7.1K]  b5ac3b3ac422b648ccc384b09a9b3e41
│   ├── [1.1M]  b62641afc9ab487008e996a5c5865e56
│   ├── [ 22K]  b8689085163c096af98c5a247fb83114
│   ├── [ 645]  b8a494a4f6a2836ee6eab604d58861be
│   ├── [1.7K]  b8b3bd4b10bc2f2db2f3b80d7395e66d
│   ├── [6.1K]  b8dfff2b5e251df889de64a2c168843a
│   ├── [ 557]  b90e559a19e8a2d3f1b9b978568e4a41
│   ├── [7.5K]  ba5a7dbfa723ab7f3e02300879e761c8
│   ├── [3.9K]  bbfeaa4510b0601e6ce2aa461bf2838f
│   ├── [4.0K]  bcd2c7b257dad9f6c65587bbcbc86064
│   ├── [5.4K]  bdd0b2c4b643b57389b90deabd550346
│   ├── [ 40K]  bde3270a01cb960201ecb628bd3a5623
│   ├── [ 683]  bdf10e77474c1686990fd61cd24a9f68
│   ├── [2.9K]  be239d1a382be893671d62ebdbc28de8
│   ├── [ 523]  bf7cd133ff45958c2991377ba140cdd7
│   ├── [2.4K]  c15ea127d3f546bb13dac2dba8884bc0
│   ├── [ 19K]  c15face77db6dfc87a680fd96ee31cc7
│   ├── [170K]  c470ca2b5b4f4437a3fe71b113a289a2
│   ├── [ 10K]  c63ee1c865cfd4b7037573581c70ae63
│   ├── [2.2K]  c6b9a4306dd4dcb5e16d2d3b24092fbe
│   ├── [9.4K]  c721f18620f6873b6ea936c9fa674cf6
│   ├── [ 134]  c79c3606a1cf168006ad3979763c7e0c
│   ├── [ 11K]  c828c44606e29d01873343461fdb4550
│   ├── [ 17K]  c8caa175bf630a665c7eb311aef4ecc5
│   ├── [2.2K]  c97ee5c0e1f14a26d7a8b637d9e20dfc
│   ├── [169K]  cabdb4a12e5de710afde298809306937
│   ├── [3.9K]  cd84880cd7b49d68a35e8d75ffe22eb8
│   ├── [ 373]  cdd04e13d4ec83ff0cd13ec8dabdc341
│   ├── [ 421]  ce238cf370b78134ea7f695aa4b4c780
│   ├── [ 196]  ced0b93dd85941cee0bf1ee921b3c4a9
│   ├── [ 18K]  d01e1cf888e3dfd53c1c9549ce784b44
│   ├── [ 10K]  d04925e638e235a8a958a433c22c170a
│   ├── [ 14K]  d052e0b27c5b6d0dc6e0d117e4cdeaa5
│   ├── [2.3K]  d0f6d8a4bf9484e16352cc442d60e6b4
│   ├── [ 308]  d1a7c041614c087034e412acda5fb340
│   ├── [2.2K]  d1c56584e4c28820cd4bc48814ffcc2f
│   ├── [ 53K]  d2285965fe34b05465047401b8595dd0
│   ├── [2.2K]  d37fd3e2e31b86b923152bc4ef4d7133
│   ├── [ 10K]  d3827ccb1b68cebce2500a061a67cc62
│   ├── [ 11K]  d41090a03be155adeae3d698e05e7132
│   ├── [ 46K]  d434f10bce063bfe8ab79d31d57e6a5e
│   ├── [1.2K]  d4b60ba28c3a4465188bd48e6714149e
│   ├── [7.6K]  d4d1e9701d7f33fda13898dfaf437c94
│   ├── [ 30K]  d583be7ec8813f27d82ee0f77232aa6b
│   ├── [ 358]  d90a9c4f4d323b44dd4c62b69f1e2c9d
│   ├── [2.7K]  d90b5103897ce3de2bad678e9e815549
│   ├── [3.6K]  d9c1ebf197431fc7c164ea7fa7aab429
│   ├── [3.4K]  da828b5eae7f04bf52dd9fb8912a2126
│   ├── [ 16K]  db226c04d05f6d50aeca1668442a6ea1
│   ├── [ 265]  dc39da53f05ee6a78e70820e6fe57731
│   ├── [ 225]  dd8fe250547c5222b48c2b710cb8417e
│   ├── [2.6K]  dfe060d4881a16c50c9937826a1b2a7c
│   ├── [ 13K]  e0c2b4f59ee723b1979928e682caf85b
│   ├── [ 56K]  e20945d7c929279ef7a6f1db184a4470
│   ├── [ 11K]  e362f359a3f68b188ab67dfef60b8b12
│   ├── [9.0K]  e3b327fdb7a6f26a24212e5e70f9593c
│   ├── [ 35K]  e3cb65103a8be6a903770b620c513e62
│   ├── [ 11K]  e4a75107b2413eda9113052a8eb1daaa
│   ├── [8.3K]  e57c6e576870c25ce1f21b2acf26fe0b
│   ├── [ 879]  e669af77038c06d1026a75ddb410b77b
│   ├── [ 25K]  e6cc1f96ed55f4c5ece03ce3e38aa88b
│   ├── [ 354]  e6d60c230e58fd44a6b9c64459e82afc
│   ├── [5.4K]  e753f7043a5590caed3b8828cd937345
│   ├── [ 12K]  e75d5f2f5744bebde4e8caa45d9923d6
│   ├── [ 29K]  e89638307efb2088ee047b073d64d9f0
│   ├── [ 338]  e993ca5fa1d40611dd0ba63e1bc88578
│   ├── [ 557]  eaaf3d8adb48aae3bbda062e411fa1ab
│   ├── [ 14K]  ebaa3b94ff25d6bd023a8aff36078375
│   ├── [3.5K]  ed440a5581eef2ae755447f365e70b89
│   ├── [2.3K]  eee2148b070931f4ef08b18d00591ee3
│   ├── [ 15K]  ef62f02808d00936e74a17c215b8dedf
│   ├── [ 540]  efabb6631e81deb6d84e23e30036fa65
│   ├── [ 22K]  f0a24c9db9dbae94f19e0501e9171954
│   ├── [2.0K]  f1cef75ed66f89b4625981bdd270f8dc
│   ├── [7.4K]  f1d8671033443c5e13956df45bc61303
│   ├── [2.1K]  f23611e8ae8f17c135bacf7a4076c3d4
│   ├── [1.6K]  f2f57cc63057db97b7c449a09a6ba444
│   ├── [164K]  f36638c2135b71e5a623dca52b611173
│   ├── [8.1K]  f37753b15d534b32e92205ba4fb356ad
│   ├── [1.2K]  f4c717e23ed2b96e1d9f75a8d630057f
│   ├── [ 812]  f5b790e2ac193b3d41015edb3551f9b8
│   ├── [8.6K]  f601041ecc597dc251c3e82409ac91c8
│   ├── [5.5K]  f636c4cdcd30bf9e04768deb06fd738d
│   ├── [8.8K]  f68fa25942b86d982d05b030407781b6
│   ├── [ 557]  f79ef42b8b163c2388af9afdf3fc0323
│   ├── [ 48K]  f7c53c47a66934504fcbc7cc164895a7
│   ├── [ 15K]  f8663b8d0a57ee5a52fdb473d37f98a5
│   ├── [ 247]  f8978f38857226aebe9272b0fae675ad
│   ├── [ 324]  f8edb3942e38e627c5a7286c5bd01a1c
│   ├── [ 451]  f99dd6e4742bbb8cac0f14f1f05369c7
│   ├── [2.1K]  fa4a2d52297929d9488eec5a980d5e76
│   ├── [2.2K]  fb08426e210cdd18af9376a552fdaeae
│   ├── [ 261]  fb41aa1136672c50a5d761660be595eb
│   ├── [ 16K]  fb46025c8904fcd52666cadef23483f9
│   ├── [1.6K]  fbe7f8c9950fe1d354eb55f5c5e283b2
│   ├── [6.7K]  fed487bddd3c6f080aaee06438aeafea
│   └── [4.5K]  ff2487154f636d5cdf36ab200333f842
├── [8.6M]  bundles
│   ├── [4.3M]  android-1ffe84932207995dba8fe338a898b49e.js
│   └── [4.3M]  ios-dc4c4a5281c128a7d004361d253fce83.js
└── [ 38K]  metadata.json

  16M used in 2 directories, 310 files

**Comment by ide** [comment]
@karanmartian The error "Asset upload timed out. Please try again." is unrelated to the one reported in this issue. I tested publishing assets with a small app a moment ago successfully -- try again now.

**Comment by dsokal** [comment]
Closing because of the inactivity.
