### ISSUE TITLE
Looks like fastlane ran into a build/archive error with your project

### ISSUE THREAD

**Issue by alalfakawma** [expo/eas-cli#1080]
### Build/Submit details page URL

https://expo.dev/accounts/alalfakawma/projects/FamCart-Retail/builds/d2f17df3-508a-4852-aa80-bb9c5112a100

### Summary

Build stopped working on April 5th, it was working before Apple released an update for the SDK.

```
Uncaught Exception: -[NSNull path]: unrecognized selector sent to instance 0x7fff8069ceb0
```

This is the error that shows each time, I have removed and created a new distribution certificate to no avail.

### Managed or bare?

Bare

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 5.10 Manjaro Linux
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.12.0 - ~/.nvm/versions/node/v16.12.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.12.0/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.12.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 30, 31
        Build Tools: 29.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs Intel x86 Atom_64, android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: AI-203.7717.56.2031.7583922
    npmPackages:
      expo: ^44.0.0 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.51.0
      expo-cli: 5.3.2
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

EAS JSON -

```json
{
  "cli": {
    "version": ">= 0.41.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
```

The build was queued with:

```bash
eas build --profile preview --platform ios
```

**Comment by wkozyra95** [comment]
As far as I'm aware we did not modify existing images, if sth changed on apple side maybe try using the latest version of the xcode https://docs.expo.dev/build-reference/infrastructure/

> I have removed and created a new distribution certificate to no avail.

Did you also recreate the provisioning profile?

**Comment by alalfakawma** [comment]
> Did you also recreate the provisioning profile?

Yes.

**Update:** Build now works, I didn't change anything, and it just worked. Closing the issue.

**Comment by piscespieces** [comment]
@wkozyra95 how can I recreate the provisioning profile? Having this issue. "Didn't change anything and it just worked" doesn't seem the solution to me

**Comment by brentvatne** [comment]
- run `eas credentials -p ios` in your project directory
- choose the production profile
- sign in to your apple account
- select "Build Credentials: Manage everything needed to build your project" and hit return
- select "All" and then when prompted with " Would you like to reuse the original profile? › (Y/n)" choose "n"
- when prompted with "Generate a new Apple Provisioning Profile? › (Y/n)" choose "y"

**Comment by kalashovkerim** [comment]
I've tried everything but nothing works, are there any updates?

**Comment by NilsBaumgartner1994** [comment]
Still facing also fastlange error: https://expo.dev/accounts/baumgartner-software/projects/rocket-meals-swosy/builds/882f5508-cffc-48d4-9ef9-4dcc51e78d5c

https://github.com/expo/expo/issues/30679
