### ISSUE TITLE
EAS build fails on iOS with multiple schemas

### ISSUE THREAD

**Issue by pzatorski** [expo/eas-cli#1086]
### Summary

After upgrading to the latest `eas-cli`:

> ★ eas-cli@0.52.0 is now available, please upgrade.

The process failed to execute the schema with error:
```
Error: EISDIR: illegal operation on a directory, read
Code: EISDIR
```

### Managed or bare?

Bare workflow

### Environment

```
System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-28 | Polestar 2, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Polestar 2
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.16
      babel-preset-expo: 9.0.2 => 9.0.2
      expo: ^44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: bare
```

### Error output

```
Error: EISDIR: illegal operation on a directory, read
Code: EISDIR
```

### Reproducible demo or steps to reproduce from a blank project

1. Upgrade `eas-cli` to the latest version (0.52.0):
```
npm install -g eas-cli
```
2. Run:
```
eas build --platform ios
```
3. Select schema to use.
The project that I work on uses multiple schemas (Widget App, Watch App). After removing all schemas expect the main one (for the app). The `cli` works fine. However when having multiple schemas then the bug accrues.

The latest stable version for me is `0.49.0`

**Comment by wkozyra95** [comment]
Can you provide a repo with a reproducible example? Mostly I'm interested in pbxproj file and xcscheme files, but having full repo would make it much easier.

Try running a build with  env `DEBUG=*`
Did you specify the scheme in eas.json?

**Comment by dsokal** [comment]
Closing because of the inactivity.
