### ISSUE TITLE
Regression since 0.52

### ISSUE THREAD

**Issue by ScreamZ** [expo/eas-cli#1087]
### Summary

I upgraded from 0.51 to 0.52, looks not related to a specific package

## EAS CLI @ 0.51 ✅
```
➜ eas build --profile development --platform ios --local
★ eas-cli@0.52.0 is now available, please upgrade.
Proceeding with outdated version

✔ Linked to project @xxxxx/xxxxx(​https://expo.dev/accounts/xxxxxx/projects/xxxx​)
✔ Using remote iOS credentials (Expo server)
```

## EAS CLI @ 0.52 ❌
```
➜ eas build --profile development --platform ios --local
✔ Linked to project @xxxx/xxx (​https://expo.dev/accounts/xxxxx/projects/xxxx​)
    TypeError: Cannot read properties of undefined (reading 'withJsEnginePodfileProps')
```

### Managed or bare?

managed

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.volta/tools/image/node/16.14.2/bin/node
      Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
      npm: 8.5.0 - ~/.volta/tools/image/node/16.14.2/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 26, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
        Android NDK: 24.0.8215888
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    Expo Workflow: managed
```

### Error output

```
➜ EXPO_DEBUG=true eas build --profile development --platform ios --local
- Linking to project @xxxxx/xxxx
✔ Linked to project @xxxxx/xxxxx (​https://expo.dev/accounts/xxxxxx/projects/xxxx​)
    TypeError: Cannot read properties of undefined (reading 'withJsEnginePodfileProps')
```

### Reproducible demo or steps to reproduce from a blank project

Just try to build a dev-client for iOS

**Comment by kav** [comment]
Seeing same

**Comment by ScreamZ** [comment]
@wkozyra95 @dsokal It might be important for you to check this.

**Comment by dsokal** [comment]
@ScreamZ @kav thanks for reporting!

I cannot repro the issue. My intuition tells me this could be related to yarn not being able to install packages properly.

Can you check this comment and follow the instructions? https://github.com/expo/eas-cli/issues/790#issuecomment-983053048

**Comment by derekstavis** [comment]
Faced this issue today after upgrading eas-cli to latest using `yarn global add eas-cli@latest`.

I can confirm that removing and re-adding solved the problem.

**Comment by stuckj** [comment]
I don't have eas-cli installed globally. I install it locally and use `npx eas ...` for all the commands. I also ran into this problem, but `yarn remove eas-cli && yarn add eas-cli` fixed it for me too.

So...apparently not a `yarn global` only issue.

Just a datapoint. :)

**Comment by mercpls** [comment]
Interesting issue. Had this happen to me on 6.0.2 after an installation this morning, and switching branches.

Both on SDK45
