### ISSUE TITLE
releaseChannel Not working in Eas build

### ISSUE THREAD

**Issue by keung7252** [expo/eas-cli#1091]
### Summary

releaseChannel Not working in Eas build

### Managed or bare?

Managed

### Environment

{
  "build": {
    "prod": {
      "releaseChannel": "1.1.0"
    },
    "production": {}
  }
}

### Error output

releaseChannel Not working in Eas build

### Reproducible demo or steps to reproduce from a blank project

releaseChannel Not working in Eas build

**Comment by wkozyra95** [comment]
you specified `releaseChannel` in `prod` profile, but build you linked is on `production` profile
