### ISSUE TITLE
Build Failed in Android, IOS can build successfully

### ISSUE THREAD

**Issue by keung7252** [expo/eas-cli#1092]
### Build/Submit details page URL

https://expo.dev/accounts/playmore/projects/MSOwner/builds/8b1e033c-b3d4-4e9d-8ca9-14853ecf196b

### Summary

Build Failed in Android, IOS can build successfully

### Managed or bare?

managed

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.19.1 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.6.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 21, 23, 25, 26, 27, 28, 29, 30, 31
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.2, 31.0.0
        System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz => 0.64.3 
      react-native-web: ^0.17.1 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.4.3
    Expo Workflow: managed

### Error output

[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:mergeReleaseResources'.
[stderr] > Multiple task action failures occurred:
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[stderr]       > Android resource compilation failed
[stderr]         /home/expo/workingdir/build/android/app/build/generated/res/react/release/drawable-mdpi/assets_images_homeimg2.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
[stderr]             
[stderr]         /home/expo/workingdir/build/android/app/build/generated/res/react/release/drawable-mdpi/assets_images_homeimg2.png: AAPT: error: file failed to compile.
[stderr]             
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[stderr]       >
[stderr] Android resource compilation failed
[stderr]         /home/expo/workingdir/build/android/app/build/generated/res/react/release/drawable-mdpi/assets_images_homeimg1.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.
[stderr]             
[stderr]         /home/expo/workingdir/build/android/app/build/generated/res/react/release/drawable-mdpi/assets_images_homeimg1.png: AAPT: error: file failed to compile.
[stderr]             
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 5m 21s

### Reproducible demo or steps to reproduce from a blank project

Build Failed in Android, IOS can build successfully

**Comment by wkozyra95** [comment]
Error is quite clear, file is not a valid png. If you are not sure what this file is you can temporarily eject your app with `expo prebuild` and check that file
`assets_images_homeimg1.png: AAPT: error: failed to read PNG signature: file does not start with PNG signature.`

**Comment by renelimonglobant** [comment]
I had the same error, the error was that there was a corrupted png file that caused the error. With expo build it didn't happen but with eas it did

**Comment by iuliuvisovan** [comment]
Same here only the error was a bit different to yours.

Fix: just drop the mentioned PNG into Photoshop or something and re-export it, fixed the issue on my end.

**Comment by TeodorFredriksson95** [comment]
I'm getting this:

ERROR:/home/expo/workingdir/build/android/app/src/main/res/drawable-mdpi/splashscreen_image.png: AAPT: error: file failed to compile.

I would happily repair it with GIMP or whatever, but I don't have a file called splashscreen_image.png anywhere in my project, or on my desktop for that matter. Any suggestions?

**Comment by Iuryck** [comment]
> I'm getting this:
> 
> ERROR:/home/expo/workingdir/build/android/app/src/main/res/drawable-mdpi/splashscreen_image.png: AAPT: error: file failed to compile.
> 
> I would happily repair it with GIMP or whatever, but I don't have a file called splashscreen_image.png anywhere in my project, or on my desktop for that matter. Any suggestions?

Same, it seems to be something created in the build process, not related to our project

**Comment by amitesh786** [comment]
@keung7252 @TeodorFredriksson95 I encountered a similar issue and managed to resolve it using the following steps:

1. Add the following configuration to **app/build.gradle**, after **defaultConfig**:
`aaptOptions {
        cruncherEnabled = false
        useNewCruncher = false
    }`
2. Remove the build folder by executing: `rm -rf android/app/build`
3. Perform a clean build with the following command: `./gradlew clean && ./gradlew assembleRelease`

This solution worked successfully in my project, and I hope it resolves the issue in yours as well.

**Comment by TeodorFredriksson95** [comment]
> [@keung7252](https://github.com/keung7252) [@TeodorFredriksson95](https://github.com/TeodorFredriksson95) I encountered a similar issue and managed to resolve it using the following steps:
> 
> 1. Add the following configuration to **app/build.gradle**, after **defaultConfig**:
>    `aaptOptions { cruncherEnabled = false useNewCruncher = false }`
> 2. Remove the build folder by executing: `rm -rf android/app/build`
> 3. Perform a clean build with the following command: `./gradlew clean && ./gradlew assembleRelease`
> 
> This solution worked successfully in my project, and I hope it resolves the issue in yours as well.

Its been  a while since i had this issue. Honestly, as dumb as it felt i think i just made a copy of all my images in paint, removed the original ones and replaced them with the copies, and it worked.
