### ISSUE TITLE
EAS BUILD -p ios freezes on blank managed project

### ISSUE THREAD

**Issue by gds3k3** [expo/eas-cli#1093]
### Build/Submit details page URL

build do not reach this page

### Summary

eas build --profile preview -p ios freezes after:

√ Linked to project [@gusds](https://forums.expo.dev/u/gusds)/iostest2 (​https://expo.dev/accounts/gusds/projects/iostest​2)

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.3 environment info:
System:
OS: Windows 10 10.0.16299
Binaries:
Node: 16.14.2 - C:\nodejs\node.EXE
Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
npm: 8.7.0 - C:\nodejs\npm.CMD
npmPackages:
expo: 44.0.2 => 44.0.2
react: 17.0.1 => 17.0.1
react-dom: 17.0.1 => 17.0.1
react-native: 0.64.3 => 0.64.3
react-native-web: 0.17.1 => 0.17.1
Expo Workflow: managed

eas --version
eas-cli/0.52.0 win32-x64 node-v16.14.2  <--50 and 51 also hangs

expo doctor

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with expo-cli on Windows. You may encounter issues using cmd.exe.

:tada: Didn’t find any issues with the project!

### Error output

No error build just hangs

### Reproducible demo or steps to reproduce from a blank project

expo init iostest2
cd iostest2
npx expo-env-info tells it is a bare project and I wanted a managed one so I renamed ios and android folders, npx expo-env-info say it is managed now .
expo start, tested a bit then
eas build:configure and selected All.
eas build --profile preview --platform ios

**Comment by gds3k3** [comment]
Hi.
Narrowed the problem to expo-modules-autolinking/mergeLinkingOptionsAsync/resolveSearchPathsAsync no returning.
It is called from @expo/prebuild-config.

An ugly patch in getManagedApplicationTargetEntitlementsAsync/getPrebuildConfigAsync/getAutolinkedPackagesAsync 
(const searchPaths = [projectRoot];) allowed me to continue but this requires a better understanding.

GdS

**Comment by wkozyra95** [comment]
As far as I'm aware this issue was fixed
