### ISSUE TITLE
Install pods fails with: Unable to add a source

### ISSUE THREAD

**Issue by SebastianRoese** [expo/eas-cli#1099]
### Build/Submit details page URL

https://expo.dev/accounts/s01roese/projects/kyzncode-dareu/builds/e0839120-e503-4c18-96eb-b09db7bcb545

### Summary

EAS build fails while installing pods (see error below). The same project with the same native dependencies was build successfully before (https://expo.dev/accounts/s01roese/projects/kyzncode-dareu/builds/3471d7b2-0610-4a32-a9e4-011283d2714e).

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.6.0 - ~/Documents/dev/dareu-app/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ^44.0.6 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.3
    Expo Workflow: managed

### Error output

Installing pods
Using Expo modules
Auto-linking React Native modules for target `DareU`: RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNReanimated, RNSVG, RNScreens, react-native-animateable-text, react-native-maps, react-native-netinfo, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
[!] Unable to add a source with url `https://cdn.cocoapods.org/` named `trunk`.
You can try adding it manually in `/Users/expo/.cocoapods/repos` or via `pod repo add`.
[stderr] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `24C9841764F04DE99C5DC1DD` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
pod exited with non-zero code: 1

### Reproducible demo or steps to reproduce from a blank project

Since it seems to be a native dependency problem it should be reproducible in a blank project by adding the same dependencies.

Here is the dependency list from our project:
```
"dependencies": {
  "@miblanchard/react-native-slider": "^2.1.0",
  "@react-native-async-storage/async-storage": "~1.15.0",
  "@react-native-community/masked-view": "0.1.11",
  "@react-native-community/netinfo": "7.1.3",
  "@react-navigation/bottom-tabs": "^6.0.9",
  "@react-navigation/native": "^6.0.6",
  "@react-navigation/stack": "^6.0.11",
  "@reduxjs/toolkit": "^1.6.2",
  "@types/color": "^3.0.1",
  "@types/geodesy": "^2.2.3",
  "@zxcvbn-ts/core": "^2.0.1",
  "@zxcvbn-ts/language-common": "^2.0.1",
  "@zxcvbn-ts/language-de": "^2.0.1",
  "@zxcvbn-ts/language-en": "^2.0.1",
  "await-notify": "^1.0.1",
  "d3": "^7.1.1",
  "d3-scale": "^4.0.2",
  "date-fns": "^2.25.0",
  "date-fns-tz": "^1.1.6",
  "deprecated-react-native-prop-types": "^2.2.0",
  "dotenv": "^16.0.0",
  "expo": "^44.0.6",
  "expo-app-loading": "~1.3.0",
  "expo-application": "~4.0.1",
  "expo-dev-client": "~0.8.5",
  "expo-device": "~4.1.0",
  "expo-file-system": "~13.1.4",
  "expo-font": "~10.0.4",
  "expo-image-manipulator": "~10.2.0",
  "expo-image-picker": "~12.0.1",
  "expo-linear-gradient": "~11.0.3",
  "expo-localization": "~12.0.0",
  "expo-location": "~14.0.1",
  "expo-notifications": "~0.14.0",
  "expo-permissions": "~13.1.0",
  "expo-task-manager": "~10.1.0",
  "geodesy": "^2.3.0",
  "i18n-js": "^4.0.0-alpha.14",
  "immer": "^9.0.12",
  "react": "17.0.1",
  "react-dom": "17.0.1",
  "react-native": "0.64.3",
  "react-native-animateable-text": "^0.10.0",
  "react-native-animated-hamburger": "0.0.2",
  "react-native-datepicker": "^1.7.2",
  "react-native-gesture-handler": "~2.1.0",
  "react-native-iphone-x-helper": "^1.3.1",
  "react-native-keyboard-accessory": "^0.1.9",
  "react-native-keyboard-aware-scroll-view": "^0.9.3",
  "react-native-maps": "0.29.4",
  "react-native-modal": "^12.1.0",
  "react-native-reanimated": "~2.3.1",
  "react-native-redash": "^16.2.3",
  "react-native-safe-area-context": "3.3.2",
  "react-native-screens": "~3.10.1",
  "react-native-svg": "12.1.1",
  "react-native-swiper": "^1.5.14",
  "react-native-web": "0.17.1",
  "react-redux": "^7.1.1",
  "redux": "^4.0.4",
  "redux-devtools-extension": "^2.13.8",
  "redux-thunk": "^2.3.0",
  "styled-components": "^5.3.5",
  "url": "^0.11.0",
  "use-async-effect": "^2.2.5",
  "use-immer": "^0.6.0",
  "use-memo-one": "^1.1.1"
}
```

**Comment by PiotrSzlagura** [comment]
Is there anything we as developers in managed workflow can do as a workaround?

**Comment by mlalitthapa** [comment]
Same here, my build failed which was successful about an hour ago.

I think the issue is with CocoaPods CDN rather than the expo server.
https://github.com/CocoaPods/CocoaPods/issues/11355

**Comment by mlalitthapa** [comment]
There is a fix mentioned here https://github.com/CocoaPods/CocoaPods/issues/11355#issuecomment-1123568293. Can we do this with eas-cli?

**Comment by homosape** [comment]
I'm experiencing same issue.

**Comment by wkozyra95** [comment]
> Can we do this with eas-cli?

for bare project you can just add it, for managed you would need to do that with config plugins

example of config plugin that can modify Podfile https://gist.github.com/giautm/402e1732c89548281d6605ef77289476

**Comment by wkozyra95** [comment]
Workaround for managed projects

create file myplugin.js with bellow content
```
const { withDangerousMod, withPlugins } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

async function readFileAsync(path) {
  return fs.promises.readFile(path, "utf8");
}

async function saveFileAsync(path, content) {
  return fs.promises.writeFile(path, content, "utf8");
}

const withDisableCocoapodsCdn = (c) => {
  return withDangerousMod(c, [
    "ios",
    async (config) => {
      const file = path.join(config.modRequest.platformProjectRoot, "Podfile");
      const contents = await readFileAsync(file);
      await saveFileAsync(file, "source 'https://github.com/CocoaPods/Specs.git'\n" + contents);
      return config;
    },
  ]);
};

module.exports = (config) => withPlugins(config, [withDisableCocoapodsCdn]);
```
add in app.json
```
+    "plugins": [
+      ["./myplugin.js"]
+    ]
```

**Comment by PMalaret** [comment]
I'm facing the same issue.
The build worked yesterday.

**Comment by PiotrSzlagura** [comment]
I can confirm that @wkozyra95 's workaround actually fixes it :) Thank you very much! You literally saved my day 🎉

**Comment by wkozyra95** [comment]
The issue was fixed upstream, if you added some mitigation we recommend removing it.
