### ISSUE TITLE
🔥 Unable to build iOS on M1 Macbook (--local flag)

### ISSUE THREAD

**Issue by ScreamZ** [expo/eas-cli#1108]
### Summary

In order to build locally with `--local` flag, Cocoapods need some additional setup to work on M1 Macbook, see https://reactnative.dev/docs/environment-setup#cocoapods and https://github.com/CocoaPods/CocoaPods/issues/10518#issuecomment-798912624.

### Managed or bare?

managed

### Environment

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.volta/tools/image/node/16.14.2/bin/node
      Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
      npm: 8.5.0 - ~/.volta/tools/image/node/16.14.2/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.4 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Get an expo project, and try to run `eas build --local`

**Comment by wkozyra95** [comment]
m1 support will land at a certain point, but we are not actively working on that yet.

if it's just a matter of changing the cocopods command you can do it here https://github.com/expo/eas-build/blob/main/packages/build-tools/src/ios/pod.ts
instruction how to use local clone: https://github.com/expo/eas-build/blob/main/DEVELOPMENT.md
If it's just matter of that small change, we are open to PR

**Comment by ScreamZ** [comment]
I was able to fix the issue when updating pods to the brew version instead of the version from gem

**Comment by antoniomefa** [comment]
@ScreamZ How did you solve it? Are you using Expo? I have this problem with Expo 46.0.9

**Comment by ScreamZ** [comment]
@antoniomefa Use cocoapod from brew instead of gem -> https://formulae.brew.sh/formula/cocoapods
