### ISSUE TITLE
EAS Build with Old Manifest Package Name

### ISSUE THREAD

**Issue by yudijohn** [expo/eas-cli#1110]
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:processReleaseResources'.
[stderr] > A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
[stderr]    > Package 'grwe.android.package' from AndroidManifest.xml is not a valid Java package name as 'package' is a Java keyword.
[stderr] * Try:
[stderr] > Run with --stacktrace option to get the stack trace.
[stderr] > Run with --info or --debug option to get more log output.
[stderr] > Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 12m 44s

I Have published an Android App with that package name, but EAS can't build with that manifest package name.
https://play.google.com/store/apps/details?id=grwe.android.package

**Comment by wkozyra95** [comment]
`grwe.android.package` is a valid applicationId but an invalid package name, expo is using the same value for both. If you want to use it you need to eject it.

**Comment by yudijohn** [comment]
> `grwe.android.package` is a valid applicationId but an invalid package name, expo is using the same value for both. If you want to use it you need to eject it.

so i need to eject the project just to build the app?

**Comment by wkozyra95** [comment]
> so i need to eject the project just to build the app?

Yes, you would need to eject and manually edit native code to change your package name to sth else in native code, but you can keep applicationId set to what you have currently.

Or use sth without `package` in the name
