### ISSUE TITLE
Expo Updates not checking updates neither is it downloading update

### ISSUE THREAD

**Issue by amireds** [expo/eas-cli#1114]
### Build/Submit details page URL

https://expo.dev/accounts/infinitypaul/projects/flickwheel/builds/37a39816-757e-41ef-b4b6-9544725fab38

### Summary

I'm trying to use expo update to update the JS Layer of my app. I'm currently using EAS build and I'm trying to use Expo Updates to check for updates, after pushing the update to the preview channel branch.

On opening the build on my device. I don't seem to be getting the update. I believe the `checkForUpdateAsync` is not working.

Please help!

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.3.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
      Watchman: 2022.02.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 27, 28, 29, 30, 31, 32
        Build Tools: 29.0.2, 30.0.2, 31.0.0, 32.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.52.0
      expo-cli: 5.4.4
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

NA

**Comment by wkozyra95** [comment]
You are using `releaseChannel` that specifies channel for classic build service, but you are publishing using EAS Update.

If you want to use EAS Update you need to specify `channel` in eas.json instead
