### ISSUE TITLE
EAS Build failing at "npm login"

### ISSUE THREAD

**Issue by catchgit** [expo/eas-cli#1120]
### Build/Submit details page URL

https://expo.dev/accounts/catchmedia/projects/Gimening/builds/3a811b07-6475-473b-9f9f-b74a24031c89

### Summary

Every time i submit a build running `eas build`, the build is failing at `npm login`. Not sure why, as I don't have any private repos - either way I have my `NPM_TOKEN` set under Secrets.

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^45.0.4 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Error output

Running "npm install" in the root dir of your repository 
[stderr] npm
[stderr] WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[stderr] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[stderr] npm WARN
[stderr] deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
[stderr] npm
[stderr] WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
[stderr] npm
[stderr] 
[stderr] WARN
[stderr] deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
[stderr] npm
[stderr] WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[stderr] npm
[stderr] 
[stderr] WARN
[stderr] 
[stderr] deprecated
[stderr] uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
[stderr] npm
[stderr] WARN deprecated @react-native-community/masked-view@0.1.11: Repository was moved to @react-native-masked-view/masked-view
[stderr] npm ERR!
[stderr] code E401
[stderr] npm
[stderr] ERR! Incorrect or missing password.
[stderr] npm ERR! If you were trying to login, change your password, create an
[stderr] npm ERR! authentication token or enable two-factor authentication then
[stderr] npm ERR! that means you likely typed your password in incorrectly.
[stderr] npm ERR! Please try again, or recover your password at:
[stderr] npm ERR!     https://www.npmjs.com/forgot
[stderr] npm ERR! 
[stderr] npm ERR! If you were doing some other operation then your saved credentials are
[stderr] npm
[stderr] ERR! probably out of date. To correct this please try logging in again with:
[stderr] npm ERR!     npm login
[stderr] 
[stderr] npm ERR! A complete log of this run can be found in:
[stderr] npm ERR!     /Users/expo/.npm/_logs/2022-05-24T13_58_12_595Z-debug.log
npm exited with non-zero code: 1

### package.json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo-google-fonts/nunito": "^0.1.0",
    "@expo/vector-icons": "^13.0.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.34",
    "@fortawesome/free-brands-svg-icons": "^5.15.2",
    "@fortawesome/pro-light-svg-icons": "^5.15.2",
    "@fortawesome/pro-regular-svg-icons": "^5.15.2",
    "@fortawesome/pro-solid-svg-icons": "^5.15.2",
    "@fortawesome/react-native-fontawesome": "^0.2.6",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/slider": "4.2.1",
    "@react-native-masked-view/masked-view": "0.2.6",
    "@react-navigation/bottom-tabs": "^5.11.7",
    "@react-navigation/drawer": "^5.12.3",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "axios": "^0.21.1",
    "expo": "^45.0.4",
    "expo-asset": "~8.5.0",
    "expo-av": "~11.2.3",
    "expo-blur": "~11.1.0",
    "expo-constants": "^13.1.1",
    "expo-dev-client": "~0.9.6",
    "expo-device": "^4.2.0",
    "expo-font": "^10.1.0",
    "expo-haptics": "~11.2.0",
    "expo-keep-awake": "~10.1.1",
    "expo-linear-gradient": "~11.3.0",
    "expo-linking": "~3.1.0",
    "expo-local-authentication": "~12.2.0",
    "expo-notifications": "^0.15.2",
    "expo-permissions": "~13.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-video-player": "^1.6.1",
    "expo-web-browser": "~10.2.0",
    "lodash": "^4.17.21",
    "lodash.filter": "^4.6.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-confetti": "^0.1.0",
    "react-native-confirmation-code-field": "^6.5.1",
    "react-native-countdown-component": "^2.7.1",
    "react-native-dropdown-picker": "^3.8.3",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-haptic-feedback": "^1.11.0",
    "react-native-keyboard-accessory": "^0.1.14",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-keyboard-spacer": "^0.4.1",
    "react-native-picker-select": "^8.0.4",
    "react-native-progress-circle": "^2.1.0",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-search-filter": "^0.1.5",
    "react-native-simple-animations": "^0.2.3",
    "react-native-size-matters": "^0.3.1",
    "react-native-svg": "^12.3.0",
    "react-native-use-websocket": "^0.2.0",
    "react-native-web": "0.17.7",
    "react-native-webview": "11.18.1",
    "victory-native": "^35.3.1"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "jest-expo": "^45.0.1",
    "typescript": "~4.0.0"
  },
  "private": true
}

**Comment by wkozyra95** [comment]
It looks like you are using font awesome pro, but you don't have npmrc in your project (in "Prepare project" section of the logs eas is creating it for you).

According to https://fontawesome.com/docs/web/setup/packages#alternate-per-project-setup-using-environment-variables
you need to have 
```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
```
in `.npmrc` in your project and pass `FONTAWESOME_NPM_AUTH_TOKEN` env via eas secrets


as for the NPM_TOKEN, if you don't use a private package, why are you passing it?

**Comment by catchgit** [comment]
> It looks like you are using font awesome pro, but you don't have npmrc in your project (in "Prepare project" section of the logs eas is creating it for you).
> 
> According to https://fontawesome.com/docs/web/setup/packages#alternate-per-project-setup-using-environment-variables you need to have
> 
> ```
> @fortawesome:registry=https://npm.fontawesome.com/
> //npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
> ```
> 
> in `.npmrc` in your project and pass `FONTAWESOME_NPM_AUTH_TOKEN` env via eas secrets
> 
> as for the NPM_TOKEN, if you don't use a private package, why are you passing it?

**Comment by catchgit** [comment]
> It looks like you are using font awesome pro, but you don't have npmrc in your project (in "Prepare project" section of the logs eas is creating it for you).
> 
> According to https://fontawesome.com/docs/web/setup/packages#alternate-per-project-setup-using-environment-variables you need to have
> 
> ```
> @fortawesome:registry=https://npm.fontawesome.com/
> //npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
> ```
> 
> in `.npmrc` in your project and pass `FONTAWESOME_NPM_AUTH_TOKEN` env via eas secrets
> 
> as for the NPM_TOKEN, if you don't use a private package, why are you passing it?

That's what I thought, so I have already entered the `FONTAWESOME_NPM_AUTH_TOKEN` under Secrets. It didnt help.

I inserted the `NPM_TOKEN` because the log said it failed at `npm login`.

**Comment by wkozyra95** [comment]
> That's what I thought, so I have already entered the FONTAWESOME_NPM_AUTH_TOKEN under Secrets. It didnt help.

setting env on it's own does not do anything if you don't have correct  npmrc in the project
