### ISSUE TITLE
Getting error related to expo-updates in both ios and esa.

### ISSUE THREAD

**Issue by JoachimKoenigslieb** [expo/eas-cli#1124]
### Build/Submit details page URL

https://expo.dev/accounts/climaider/projects/climaider-app/builds/0727d1d6-60c1-4096-8738-b56411689b3b

### Summary

I'm building as usual my project with eas targeting android and ios. I'm getting an error related to something about expo-updates is my reading of the logs:

› Executing expo-updates Pods/EXUpdates » [CP-User] Generate app.manifest for expo-updates

ios error (https://expo.dev/accounts/climaider/projects/climaider-app/builds/0727d1d6-60c1-4096-8738-b56411689b3b): 

```
❌ Metro encountered an error:
Cannot read properties of undefined (reading 'charAt')
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/expo/Library/Developer/Xcode/DerivedData/Climaider-gkmwhlfhxbavlteubjvpzsbtilex/Build/Intermediates.noindex/ArchiveIntermediates/Climaider/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-46EB2E00027AD0.sh (in target 'EXUpdates' from project 'Pods')
▸ (1 failure)
2022-05-29 08:17:45.925 xcodebuild[4383:12456] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-29 08:17:45.926 xcodebuild[4383:12456] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-29 08:17:45.991 xcodebuild[4383:12456] XType: com.apple.fonts is not accessible.
2022-05-29 08:17:45.991 xcodebuild[4383:12456] XType: XTFontStaticRegistry is enabled.
** ARCHIVE FAILED **
› Executing expo-updates Pods/EXUpdates » [CP-User] Generate app.manifest for expo-updates

❌ Metro encountered an error:
Cannot read properties of undefined (reading 'charAt')
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/expo/Library/Developer/Xcode/DerivedData/Climaider-gkmwhlfhxbavlteubjvpzsbtilex/Build/Intermediates.noindex/ArchiveIntermediates/Climaider/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-46EB2E00027AD0.sh (in target 'EXUpdates' from project 'Pods')
▸ (1 failure)
2022-05-29 08:17:45.925 xcodebuild[4383:12456] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-29 08:17:45.926 xcodebuild[4383:12456] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-29 08:17:45.991 xcodebuild[4383:12456] XType: com.apple.fonts is not accessible.
2022-05-29 08:17:45.991 xcodebuild[4383:12456] XType: XTFontStaticRegistry is enabled.
** ARCHIVE FAILED **
```

Android error (https://expo.dev/accounts/climaider/projects/climaider-app/builds/f8857b54-bef6-43c2-8375-5b3169ef30cf):
```
                    Welcome to Metro!
              Fast - Scalable - Integrated
[stderr] [BABEL] Note: The code generator has deoptimised the styling of /home/expo/workingdir/build/unknown as it exceeds the max of 500KB.
[stderr] [BABEL] Note: The code generator has deoptimised the styling of /home/expo/workingdir/build/unknown as it exceeds the max of 500KB.
[stderr] [BABEL] Note: The code generator has deoptimised the styling of /home/expo/workingdir/build/unknown as it exceeds the max of 500KB.
[stderr] Error: @build-script-error-begin
[stderr] Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. Cannot read properties of undefined (reading 'charAt')
[stderr] @build-script-error-end
[stderr]     at /home/expo/workingdir/build/node_modules/expo-updates/scripts/createManifest.js:43:11
> Task :expo-updates:createReleaseExpoManifest FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
Execution optimizations have been disabled for 6 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
798 actionable tasks: 798 executed
```

I've tried to re-install expo-updates with expo install expo-updates, but no packages are changing. I've recently upgraded to expo sdk 45 and this is the first time installing in the new setup.

Hopefuly someone can give me some hints!

Best wishes Joachim

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
      Yarn: 3.2.1 - ~/.nvm/versions/node/v16.13.2/bin/yarn
      npm: 8.3.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      expo-cli: 5.4.6
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

-

**Comment by wkozyra95** [comment]
Start with fixing issues reported by expo doctor,
Is the `charAt` part of some logic in `app.config.js` ?

I'm not sure if this the reason for the error but, I noticed that you are using yarn berry, it's working on EAS side but SDK does not officially support it. In short, EAS will call yarn install in the correct directories and so on, but it's on you to make sure that the project is configured properly and the libraries you are using support it.

**Comment by JoachimKoenigslieb** [comment]
I tried running expo doctor and it was happy. (It is also part of the build pipeline and ran successfully)

I dont have an app.config.js. Is that an issue? The charAt function is only reference in my own code in some util function generating some database IDs. 

I solved the problem by downgrading to expo SDK 44. I'm still not sure what the issue was.

**Comment by wkozyra95** [comment]
This is an output of expo doctor in the build you linked
```
Running "expo doctor"
- Finding all copies of expo-modules-autolinking
✔ Found all copies of expo-modules-autolinking
[stderr] 
[08:14:21] Expected package expo-modules-autolinking@~0.8.1
[stderr] 
[08:14:21] Found invalid:
[stderr] 
[08:14:21]   expo-modules-autolinking@0.7.1
[stderr] 
[08:14:21]   (for more info, run: npm why expo-modules-autolinking)
- Finding all copies of @expo/config-plugins
✔ Found all copies of @expo/config-plugins
[08:14:23]   All copies of @expo/config-plugins satisfy ^4.1.0
- Finding all copies of @expo/prebuild-config
✔ Found all copies of @expo/prebuild-config
[08:14:25]   All copies of @expo/prebuild-config satisfy ^4.0.0
[08:14:27] 🎉 Didn't find any issues with the project!
```
You have a wrong version of auto-linking package, that package should not be installed directly, so you most likely have a dependency that includes that old version. You can check with `npm why expo-modules-autolinking`  what package is a problem

**Comment by TheRealMikeD** [comment]
I'm getting this same error in my eas build:
`The following build commands failed:
PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/expo/Library/Developer/Xcode/DerivedData/{appname}-hiwtnkmowddhzeasnfxgrxjthlxr/Build/Intermediates.noindex/ArchiveIntermediates/{appname}/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-46EB2E00050DE0.sh (in target 'EXUpdates' from project 'Pods')`

expo-doctor is totally clean. 
Using expo 49.0.0 and expo-updates 0.18.11, which are the latest of each as of this comment.

If I try to build for `developmentClient: true`, it works with no problem.  Production builds fail consistently, though, always with this same error.

**Comment by josephjoberno** [comment]
> I'm getting this same error in my eas build: `The following build commands failed: PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/expo/Library/Developer/Xcode/DerivedData/{appname}-hiwtnkmowddhzeasnfxgrxjthlxr/Build/Intermediates.noindex/ArchiveIntermediates/{appname}/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-46EB2E00050DE0.sh (in target 'EXUpdates' from project 'Pods')`
> 
> expo-doctor is totally clean. Using expo 49.0.0 and expo-updates 0.18.11, which are the latest of each as of this comment.
> 
> If I try to build for `developmentClient: true`, it works with no problem. Production builds fail consistently, though, always with this same error.

i have the same error

**Comment by TheRealMikeD** [comment]
@josephjoberno, what versions of expo and expo-updates are you using?
And can you get a build to work if you set `developmentClient: true` in eas.json?

**Comment by josephjoberno** [comment]
I use expo 49 i can’t build  my apps i will send the log !

**Comment by MarchewkaMatthew** [comment]
@TheRealMikeD @josephjoberno 

Same error for me. I'm using these versions:
```
"expo-updates": "~0.18.11",
"expo": "~49.0.5",
```
and `eas-cli/4.1.2 darwin-x64 node-v16.20.0`.

One thing to add, is that it worked for me for the `preview` profile which is the same as the production (no `"developmentClient": true,` set) but without `"distribution": "store",`

**Comment by TheRealMikeD** [comment]
So, I looked at some other similar error reports out there, and the advice was to look through the XCode log.  That log file is big, but you can save a little time by searching for "`error`" and searching backwards from the end of the file.

In my case, I found an error message telling me that there was an image file being used via a `require()` statement, but the image file could not be found.  Sure enough, that file was listed in my .gitignore file, so it wasn't being uploaded to the eas build server.  I removed the exclusion from .gitignore, ran another build, and it worked as expected.

I'm not suggesting that other people who are seeing this error should check their .gitignore files for image files that are needed, but rather that, even though it's cumbersome to look through, the XCode log is very likely to have the answer to why your build may be failing.  It's a lot more helpful than the cryptic message that fastlane gives us.

**Comment by MarchewkaMatthew** [comment]
@TheRealMikeD Thanks for the info, for me it was a matter of changing the file's permissions in the `/tmp` folder. Have a great weekend!

**Comment by TheRealMikeD** [comment]
@MarchewkaMatthew, glad I could help!

**Comment by 3madurya3** [comment]
> [RUN_FASTLANE] The following build commands failed:
> [RUN_FASTLANE]  PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates
> [PATH]/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-46EB2E00020E00.sh
> (in target 'EXUpdates' from project 'Pods')

@MarchewkaMatthew I am getting the same error with relation to 'EXUpdates'. Did you ever have to change your version of EXUpdates/how did you get rid of this specific error?

**Comment by eduance** [comment]
> So, I looked at some other similar error reports out there, and the advice was to look through the XCode log. That log file is big, but you can save a little time by searching for "`error`" and searching backwards from the end of the file.
> 
> In my case, I found an error message telling me that there was an image file being used via a `require()` statement, but the image file could not be found. Sure enough, that file was listed in my .gitignore file, so it wasn't being uploaded to the eas build server. I removed the exclusion from .gitignore, ran another build, and it worked as expected.
> 
> I'm not suggesting that other people who are seeing this error should check their .gitignore files for image files that are needed, but rather that, even though it's cumbersome to look through, the XCode log is very likely to have the answer to why your build may be failing. It's a lot more helpful than the cryptic message that fastlane gives us.

Absolute legend!

**Comment by arnaudambro** [comment]
I can't read the log file, cause I get `E05E9EE0-E1FA-4EB4-8586-0CA9313D83F0.xcactivitylog is not a valid xcactivitylog file`

how did you read this ?

**Comment by TheRealMikeD** [comment]
@arnaudambro, a quick search turns up this error: [https://github.com/MobileNativeFoundation/XCLogParser/issues/219](https://github.com/MobileNativeFoundation/XCLogParser/issues/219)
It looks like a parsing error that existed in Xcode 16, but was fixed in January, 2025.
Maybe try updating your Xcode and see if that fixes it?
