### ISSUE TITLE
[eas build] Managed project with workflow set to generic in eas.json outputs incorrect error message

### ISSUE THREAD

**Issue by EvanBacon** [expo/eas-cli#114]
In a managed project (no ios or android folder), running the following produces an error message that doesn't seem right.
```
client 𝝠 easd build:create -p ios
✔ Ensuring @bacon/pillar-valley is created on Expo

We've found multiple schemes in your Xcode project: 
You can specify the scheme you want to build at builds.ios.PROFILE_NAME.scheme in eas.json.
```
I'd expect the project to not have any schemes, but here it says it found multiple.

**Comment by brentvatne** [comment]
Important note: the build profile is set to `generic` in this case

**Comment by dsokal** [comment]
I'd say we need to read the project type (generic/managed) from `eas.json` and verify the project really matches that setting. We can do that by checking for the existence of the `android` and `ios` directories.
