### ISSUE TITLE
eas not building my app

### ISSUE THREAD

**Issue by Pancham555** [expo/eas-cli#1140]
### Summary

I have been trying to build my app with eas but it is showing me an error 
Error: EPERM: operation not permitted, scandir 'D:\Config.Msi'
    Code: EPERM

### Managed or bare?

bare but don't have any native code

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD  
      npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD    
    npmPackages:
      expo: ~45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: bare

### Error output
 Error: EPERM: operation not permitted, scandir 'D:\Config.Msi'
    Code: EPERM
_No response_

### Reproducible demo or steps to reproduce from a blank project

1. expo init app (Use bare template)
2. install eas globally 
3. run `eas build:configure` or ` eas build --platform android`

**Comment by wkozyra95** [comment]
any chance you have some yarn.lock or package.json in the root of the drive? Where is your project in relation to `D:\` ?
