### ISSUE TITLE
[iOS] Apple Push Services certificate

### ISSUE THREAD

**Issue by xD3CODER** [expo/eas-cli#1141]
### Summary

I'm trying to configure `eas` to build my iOS application.
I use Onesignal to send push notifications. According to their documentation, I have generated an Apple Push Services certificate.
The `eas credentials` asks if I want to generate an APN key but I want to use the certificate already on my Apple developer account instead.
Is there a way to specify this type of certificate somewhere?
Currently, the build triggered with `eas build -p ios --local --profile development` completes without error but my push notifications don't work.

### Managed or bare?

bare

### Environment

    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.18 - ~/WebstormProjects/app/node_modules/.bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.05.16.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: Chipmunk 2021.2.1 Chipmunk 2021.2.1
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.4 => 45.0.4 
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
    npmGlobalPackages:
      eas-cli: 0.53.0
      expo-cli: 5.4.8
    Expo Workflow: bare

### Error output

no relevent

### Reproducible demo or steps to reproduce from a blank project

- Init bare project
- Follow Onesignal documentation [here](https://documentation.onesignal.com/docs/generate-an-ios-push-certificate)
- Setup EAS credentials
- Build app for iOS

**Comment by wkozyra95** [comment]
Question about push key in eas-cli refers only to notifications that go through expo servers, if you are using onesginal or any other service configuring it does not do anything. 

Push certificate is a server-side credential and it's not used/needed during the build process, you can generate it on apple developer portal, onesignal probably has documentation on how to do that
