### ISSUE TITLE
Standalone app built with EAS tries to connect to metro dev server

### ISSUE THREAD

**Issue by ibrag474** [expo/eas-cli#1142]
### Build/Submit details page URL

(https://expo.dev/accounts/ibrag474/projects/cyqler/builds/f5a86558-b2af-4ad8-aa97-034a329c24c4)

### Summary

I built my app with `eas build -p android --profile production` and it crashes on startup, eas.json is untouched. `adb logcat '*:S' ReactNative:V ReactNativeJS:V` shows that for some reason it tries to connect to metro dev server.

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Linux 5.13 Linux Mint 20.3 (Una)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      npm: 8.12.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    IDEs:
      Android Studio: AI-211.7628.21.2111.8092744
    npmPackages:
      expo: ^44.0.6 => 44.0.6 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: ~0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.53.0
      expo-cli: 5.4.8
    Expo Workflow: managed

### Error output

06-04 01:47:43.442 14908 14952 E ReactNativeJS: TypeError: undefined is not an object (evaluating '(void 0).toString')
06-04 01:47:43.449 14908 14952 I ReactNativeJS: Running "main" with {"rootTag":1}
06-04 01:47:43.451 14908 14952 E ReactNativeJS: Invariant Violation: "main" has not been registered. This can happen if:
06-04 01:47:43.451 14908 14952 E ReactNativeJS: * Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
06-04 01:47:43.451 14908 14952 E ReactNativeJS: * A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

### Reproducible demo or steps to reproduce from a blank project

Run eas build -p android

**Comment by ibrag474** [comment]
I tried this solution https://docs.expo.dev/build-reference/migrating/#custom--main--entry-point-in and still getting same error

**Comment by wkozyra95** [comment]
can you link the build page for the app?

**Comment by wkozyra95** [comment]
It does not look like there is an issue with the building process and I don't see anything that would suggest that app attempts to connect to the development server

It's hard to tell what is your project structure after mixing all of those solutions you listed, but error suggests that bundle is created, but it's invalid so I suggest changing it to the same state as clean expo init app
- create App.tsx file (or ts/js/jsx) and `export default` root of your app
- remove registerComponent
- add `"main": "node_modules/expo/AppEntry.js"` in package.json

**Comment by ibrag474** [comment]
All fix attempts undone, now I am getting the same error that is pasted in my first comment. [Build page](https://expo.dev/accounts/ibrag474/projects/cyqler/builds/19810a3a-33f2-41a3-9b2b-2391071ab8fa)

**Comment by ibrag474** [comment]
Since [this package](https://docs.expo.dev/versions/latest/sdk/amplitude/) is deprecated and does not comply to google play's user data collection policy, I need to move to [@amplitude/react-native](https://github.com/amplitude/Amplitude-ReactNative) until August instead, but I cannot do this because this new package does not work with expo built app's, it works with eas built apps only. Problems begin to stack up, because eas still does not work properly!

**Comment by ibrag474** [comment]
After creating a new project with `expo init`, copy pasting all source to the new project, 12 hours and tenths of builds I figured out that the crash of the on start was cause by `app.json` configuration, specifically `"updates": { "enabled": false }`

**Comment by wkozyra95** [comment]
I agree that the error message should be better, but why did you have expo-updates installed if you set it to false?

**Comment by wkozyra95** [comment]
It sounds like issue is resolved for you (e.g. you can either enable updates or remove expo-updates package)

As for the underlying cause I was not able to reproduce it on the fresh expo init SDK 45 project, so I'm assuming it was fixed at some point
