### ISSUE TITLE
eas build with developmentClient reapeating yarn install

### ISSUE THREAD

**Issue by bombillazo** [expo/eas-cli#1145]
### Summary

When running `eas build -p android --local` on a project with the developmentClient option:

```js
// eas.json
{
...
  "development": {
    "developmentClient":true,
    "android": {
      ...
    }
  }
...
}
```
The command runs the `[INSTALL_DEPENDENCIES]` Runs multiple times. I believe the first time it runs it is for the regular eas build process, and the second time it runs due to the prebuild phase running because it has a dev client. Dev clients typically use the `expo prebuild` to install dependencies (and pods for ios) as well. When running for ios, it can potentially run 3 times due to the `expo doctor` command.

Currently, there is no way to control whether to run or skip yarn dependency installation nor can one skip expo doctor if needed. Due to this the build process can take much longer than necessary.

### Managed or bare?

managed

### Environment

 expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
      Watchman: 2022.05.16.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/usr/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 27, 28, 29, 30, 31, 32
        Build Tools: 30.0.2, 31.0.0, 32.0.0, 32.1.0
        System Images: android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 0.53.0
      expo-cli: 5.4.9
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Create a basic app with a [custom dev client](https://docs.expo.dev/development/getting-started/).
2. Install eas cli.
3. Run `eas build -p android --local`

**Comment by wkozyra95** [comment]
this is intended and works the same for the cloud builds, The first install is necessary so prebuild works, the second install will install any packages that prebuild added to package.json

As far as I'm aware `expo doctor` does not run install on it's own, and this additional time feels like a good tradeoff for detecting issues.

Also running install multiple times, should not have any performance impact , any install call after the initial should be very quick
