### ISSUE TITLE
Error after submitting iOS version

### ISSUE THREAD

**Issue by farrokh** [expo/eas-cli#1146]
Hi,
after updating to 0.53.0, my submissions keep getting rejected. The message I get from connect is:
The build status of xxx (version xxx(1) iOS) has changed to Invalid Binary
I tried to downgrade it but it didn't help. Is anyone else experiencing the same issue?

**Comment by ikeller96** [comment]
I'm getting the same errors as well. Seems like this isn't just happening with expo though. But I still wouldn't rule it out that it could be an issue as I have seen multiple comments in other places that this stems from a third party issue. 

Here are some other threads where people are having the same issues: 

https://github.com/facebook/react-native/issues/33789
https://developer.apple.com/forums/thread/127678

The last link is important as this is an apple forum. Seems like this is stemming from something on Apple's side of things.

**Comment by farrokh** [comment]
Thanks for the update.

**Comment by wkozyra95** [comment]
It was an issue with apple validation, it looks like it's fixed, try resubmitting

https://developer.apple.com/forums/thread/127678?page=6
