### ISSUE TITLE
Credentials setup failing [CombinedError: [GraphQL] Unexpected server error (Expo error ID: undefined)]

### ISSUE THREAD

**Issue by Saad-Bashar** [expo/eas-cli#1151]
### Build/Submit details page URL

https://expo.dev/accounts/shiftcare/projects/shiftcare

### Summary

So I have been trying to submit my iOS app using eas submit. All the credentials are made properly. I can build as well. However when I want to submit it fails in ASC API KEY step. When I select ASC API KEY from the list it throws out this error - CombinedError: [GraphQL] Unexpected server error (Expo error ID: undefined).

Few contexts,
1. My app store connect is still in review process, Is that a problem? I submitted my ID to apple, waiting.
2. We are 2 developers and both of us went through EAS steps. So now we have 2 distribution plus 2 certificates which have been generated by EAS. The other developer can submit the app to iOS without any issue. Am I doing something wrong here? 

### Managed or bare?

Bare

### Environment

 System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2
      react-dom: ^17.0.1 => 17.0.2
      react-native: 0.66.4 => 0.66.4
    npmGlobalPackages:
      eas-cli: 0.53.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Sorry if I am posting in the wrong thread. This might be more of a question rather than a bug with EAS CLI. But with the error message, I am lost what to do. Hence the issue.

**Comment by Saad-Bashar** [comment]
Yes, what happened was, First I created the app myself, then created an organization, transferred the project from my account to the organization, and invited the other dev. The app is the bare react native app so I don't think I have app.json?  

I have added another one of my personal accounts to this organization and from that account, I can build plus submit. As for the original account which created the organization is having the issues. That brings another question, can both of us devs use our own distribution + provision certificates which we created from EAS automatically? 

Here goes my eas.json. I got the error when I run `eas build` or `eas submit`. The command fails with the `error setting up credentials`.

```
{
  "cli": {
    "version": ">= 0.53.1"
  },
  "build": {
    "development": {
      "distribution": "internal",
      "android": {
        "gradleCommand": ":app:assembleDebug"
      },
      "ios": {
        "buildConfiguration": "Debug"
      }
    },
    "preview": {
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      },
      "ios": {
        "simulator": true
      }
    },
    "production": {}
  },
  "submit": {
    "production": {
      "ios": {
        "appleId": "****",
        "ascAppId": "****",
        "appleTeamId": "****"
      }
    }
  }
}

```

**Comment by centerfield77** [comment]
@Saad-Bashar 
I am having the same problem now.
Have you been able to solve this problem?

**Comment by centerfield77** [comment]
I just now solved this problem.
The problem was occurring at the time I ran eas submit and entered the Apple app-specific password.
So instead of entering the Apple app-specific password, I proceeded to create a new API key, which solved this problem.

**Comment by wkozyra95** [comment]
@centerfield77 @stefaandevylder if it started happening in the past 2 hours issue should be resolved already

@Saad-Bashar you had this issue before, so the fix will likely not affect you, please provide full output of the commands you are running 

> The app is the bare react native app so I don't think I have app.json?

You should create app.json even in the bare project to specify `slug` and `owner` of the project, by default your project is using name of your directory as a name of the project, so it's not recommended to use it this way

> That brings another question, can both of us devs use our own distribution + provision certificates which we created from EAS automatically?

yes, if you would both build for that organization then credentials would be shared, but if you don't have the owner field specified in `app.json` then you are building those apps on your personal accounts, not on the organization

**Comment by alexislefebvre** [comment]
I have the same error with an account that worked previously and also an account I created today.

Everything is fine then it fails:

```
✔ Please enter the 6 digit code you received at +33 •• •• •• •• 01: … 123456
✔ Valid code
✔ Logged in and verified
› Team [TEAM] ([ID])
› Provider [TEAM] ([ID])
✔ Bundle identifier registered com.[…]
✔ Synced capabilities: No updates
✔ Synced capability identifiers: No updates
✔ Fetched Apple distribution certificates
Failed to setup credentials.
    CombinedError: [GraphQL] Unexpected server error (Expo error ID: [ID]).
    [GraphQL] Unexpected server error (Expo error ID: undefined).
```

We use `eas-cli:0.24.1` and the SDK 41 because we didn't updated the app yet.

**Comment by wkozyra95** [comment]
@alexislefebvre does it happen on latest cli?

We do not support old cli plus for the last 2 months it should not be possible to build with CLIs older than `0.26.0` plus some other APIs might have been deprecated in a meantime. There was a long deprecation period before we disabled it, but as far as I remember warning showed up only when building.

**Comment by RobCata** [comment]
I have the same problem, yesterday it worked today not, Expo SDK 42, how to solve?

**Comment by Saad-Bashar** [comment]
> @centerfield77 @stefaandevylder if it started happening in the past 2 hours issue should be resolved already
> 
> @Saad-Bashar you had this issue before, so the fix will likely not affect you, please provide full output of the commands you are running
> 
> > The app is the bare react native app so I don't think I have app.json?
> 
> You should create app.json even in the bare project to specify `slug` and `owner` of the project, by default your project is using name of your directory as a name of the project, so it's not recommended to use it this way
> 
> > That brings another question, can both of us devs use our own distribution + provision certificates which we created from EAS automatically?
> 
> yes, if you would both build for that organization then credentials would be shared, but if you don't have the owner field specified in `app.json` then you are building those apps on your personal accounts, not on the organization

I see, so in my case app.json should be like the following? Again thanks for your kind response on this!
```
{
  "name": "appname",
  "displayName": "appdisplayname"
    "expo": {
        "owner": "name of the account",
        "slug": "slug"
    }
}
```

**Comment by alexislefebvre** [comment]
> @alexislefebvre does it happen on latest cli?

Thanks, it worked with `eas-cli@^0.53.0`! We will update our SDK as soon as possible.

**Comment by RobCata** [comment]
Guys now work, i do not know how

**Comment by abury** [comment]
I've had a build running fine for months . After updating my eas cli I've started getting this error.
The logged in user is part of the organization that owns the project, so I'm not sure why this would be happening?

**Comment by JoaoLucas8760** [comment]
in app.json, remove the object  extra on end file, so rebuild
