### ISSUE TITLE
Android - App crashes when trying to connect to debugger on { "developmentClient": true, "distribution": "internal" }

### ISSUE THREAD

**Issue by kuriel-trivu** [expo/eas-cli#1157]
### Build/Submit details page URL

https://expo.dev/accounts/trivudev/projects/smattcom/builds/ad7d2c17-9aeb-480a-9c14-697ddd4e7159

### Summary

App crashes when trying to connect to debugger on { "developmentClient": true, "distribution": "internal" }

Tested on Android.

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000 // <-- (this is actually Windows 11)
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/metro-config: ^0.1.84 => 0.1.84
      expo: ^43.0.0 => 43.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: managed

### Error output

App just crashes and close on trying to connect.

### Reproducible demo or steps to reproduce from a blank project

use the APK in provided project.

**Comment by wkozyra95** [comment]
start with fixing issues reported by the expo doctor, if the issue persist check native logs for any reason for crash/stacktrace

**Comment by kuriel-trivu** [comment]
I was working on that yesterday, i had to update SDK to 45 and follow all the steps to upgrade (including 3rd parts libraries).

The app works (no debug mode), The build is OK (no expo-doctor messages).

**The problem persists on trying to connect to Debugger.**

https://expo.dev/accounts/trivudev/projects/smattcom/builds/30b3f849-3606-4ada-bdb9-1a0ddab10f84

the new environment is:

```
  expo-env-info 1.0.3 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/metro-config: ^0.1.84 => 0.1.84
      expo: ^45.0.0 => 45.0.5
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
    Expo Workflow: managed
```

**Comment by wkozyra95** [comment]
I can see issues reported by expo doctor in your build logs
