### ISSUE TITLE
[ios] Prevent redundant binary upload

### ISSUE THREAD

**Issue by EvanBacon** [expo/eas-cli#116]
We should implement some mechanisms to try and prevent redundant binary uploads:
https://github.com/expo/eas-cli/issues/115#issuecomment-738996478

**Comment by brentvatne** [comment]
we could try to query the app store apis before submitting to see if we've already submitted a build for that version/build number/version code.

as a last resort, we can handle the error message from fastlane and make it more well-formatted and easier to read

**Comment by kbrandwijk** [comment]
Related: https://github.com/expo/eas-cli/issues/892

**Comment by izakfilmalter** [comment]
This is super annoying.

**Comment by dsokal** [comment]
@izakfilmalter FWIW you can use app version management - https://docs.expo.dev/build-reference/app-versions/

**Comment by izakfilmalter** [comment]
Ahh sweet! Will try it out @dsokal.

**Comment by dsokal** [comment]
I'm closing the issue as the new "App version management" feature mostly fixes the issue.
