### ISSUE TITLE
eas submit CombinedError: [GraphQL] Unexpected server error (Expo error ID: undefined).

### ISSUE THREAD

**Issue by PaddyLock** [expo/eas-cli#1165]
### Build/Submit details page URL

https://expo.dev/accounts/patricklock/projects/helios-app-expo

### Summary

When I run the following to submit to ios

eas submit -p ios

I get the following output after successful Scheduled iOS submission

CombinedError: [GraphQL] Unexpected server error (Expo error ID: undefined).

I have been able to submit previously with the same credentials. I can still build fine. Build and submit to android works fine too.

I am on the latest eas-cli

eas-cli/0.53.1 darwin-x64 node-v15.14.0

### Managed or bare?

managed

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
      Watchman: 2021.11.15.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.5.2 - /Users/patricklock/.rvm/rubies/ruby-2.4.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.53.1
      expo-cli: 5.4.9
    Expo Workflow: bare

✔ Found all copies of expo-modules-autolinking
  All copies of expo-modules-autolinking satisfy ~0.8.1
✔ Found all copies of @expo/config-plugins
  All copies of @expo/config-plugins satisfy ^4.1.0
✔ Found all copies of @expo/prebuild-config
  All copies of @expo/prebuild-config satisfy ^4.0.0

🎉 Didn't find any issues with the project!

### Error output

No further error reporting with EXPO_DEBUG=true

just this

CombinedError: [GraphQL] Unexpected server error (Expo error ID: undefined).

### Reproducible demo or steps to reproduce from a blank project

Not possible

**Comment by PaddyLock** [comment]
It did start happening in the last 2 hours, and yes I did get it working with

eas build --platform ios --auto-submit

However I didn't see anything in the eas submit status here - https://status.expo.dev
And the error message was unclear

What was the problem please? and how do I know what to do if it happens again?

**Comment by wkozyra95** [comment]
> What was the problem please? 

just a bug in a code, we rolled it back as soon as we realized that there is an issue, we will update the status page retroactively

> and how do I know what to do if it happens again?

the status page is the best place to check for that

**Comment by PaddyLock** [comment]
Thanks

**Comment by alexislefebvre** [comment]
I have the same error:

```
$ node ./node_modules/eas-cli/bin/run update --platform=ios --branch=preprod --group=preprod
✔ Linked to project @team/project
    CombinedError: [GraphQL] Unexpected server error (Expo error ID: undefined).
```

This is with `update` command but the error is the same as in this issue.

**Comment by alexislefebvre** [comment]
Removing the ` --group=preprod` option fixed the issue. No more strange GraphQL error.

**Comment by cyril94440** [comment]
Same here.

I get this with every command that involves iOS : 

`✔ Created provisioning profile
Failed to set up credentials.
    CombinedError: [GraphQL] Unexpected server error (Expo error ID: undefined).
The terminal process "/bin/zsh '-c', 'npm run build:local:ios'" terminated with exit code: 1.`

Any idea?

Thanks

**Comment by gyl89** [comment]
Same issue with `eas build`

**Comment by cyril94440** [comment]
I removed everything from my account, created a new one and now it is working...
