### ISSUE TITLE
signing issue only when building with eas

### ISSUE THREAD

**Issue by philipheinser** [expo/eas-cli#1172]
### Summary

```
error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team
```

builds locally without problem

### Managed or bare?

bare

### Environment

expo-env-info 1.0.3 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.4.7
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

enable automatic signing in Xcode & set signing cert to apple development

**Comment by wkozyra95** [comment]
> enable automatic signing in Xcode & set signing cert to apple development

I see your previous build finished successfully, is that the only part you changed? Did you modify the signing config only for the main target or also for all extensions?

We are overriding pbpxproj values on eas build to use certs/profiles that were configured by eas-cli, but there might sth in pbxproj that we are not handling. Can you post your pbxproj file or diff of the changes in pbxproj?

**Comment by philipheinser** [comment]
@wkozyra95 Yes to test the only thing I changed is to manually change the sign config for all targets & extensions. The targets we have `app`, `today-extension`, `notification-service`, `watchkitapp`, `watchkitapp-extension`, `imessage`, `widget-extension`. I sorry but im not able to post the pbxproj file here.
