### ISSUE TITLE
Build json output missing submission info

### ISSUE THREAD

**Issue by mccraveiro** [expo/eas-cli#1181]
### Summary

I'm trying to integrate our CI (GitHub Actions) with Slack. The idea is to send a message with the submission URL on every deploy. However, It seems that the json output is missing this information. Is this a bug? It seems to be a bug as the text output has this info. 

This is used to output a JSON:
https://github.com/expo/eas-cli/blob/283f086b258d507b7772129f33eae0eb355fc7c7/packages/eas-cli/src/build/runBuildAndSubmit.ts#L136

And this is only called for text output:
https://github.com/expo/eas-cli/blob/283f086b258d507b7772129f33eae0eb355fc7c7/packages/eas-cli/src/build/runBuildAndSubmit.ts#L130

### Managed or bare?

both

### Environment

Not applicable 

### Reproducible demo or steps to reproduce from a blank project

Run eas build with out submit and json output:

```sh
eas build --non-interactive --auto-submit --no-wait --json --platform ios --profile production
```

We got a bunch of text outputs that contains both the build URL and the submission URL:
```sh
[...]
Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive
✔ Compressed project files 2s (16.5 MB)
✔ Uploaded to EAS 18s

Build details: https://expo.dev/accounts/<account id>/projects/<project id>/builds/<build id>

[...]

✔ Scheduled iOS submission

Submission details: https://expo.dev/accounts/<account id>/projects/<project id>/submissions/<submission id>
```

However, the json output is the following:
```json
[
  {
    "id": "<build id>",
    "status": "IN_QUEUE",
    "platform": "IOS",
    "artifacts": {},
    "initiatingActor": {
      "id": "<account id>",
      "displayName": "<account name>"
    },
    "project": {
      "id": "<project id>",
      "name": "<project name>",
      "slug": "<project slug>",
      "ownerAccount": {
        "id": "<account id>",
        "name": "<account name>"
      }
    },
    "releaseChannel": "default",
    "distribution": "STORE",
    "buildProfile": "production",
    "sdkVersion": "<sdk version>",
    "appVersion": "<app version>",
    "appBuildVersion": "<app build version>",
    "gitCommitHash": "<commit hash>",
    "priority": "HIGH",
    "createdAt": "2022-06-26T01:32:20.118Z",
    "updatedAt": "2022-06-26T01:32:20.118Z"
  }
]
```

Which is missing the submission info.

**Comment by wkozyra95** [comment]
Hi, thanks for reporting it, I added that to our internal issue tracker.

Can you describe why you need that info? Currently, we do not provide any way to check the status of a submission, so if you got that id only thing you could do is to construct URL to the submit page.

**Comment by mccraveiro** [comment]
@wkozyra95 yeap, I'll just use the link to notify our team that a new submission is in progress.

**Comment by mccraveiro** [comment]
Thanks @wkozyra95 ❤️
