### ISSUE TITLE
Build fails on `react-native-navigation`

### ISSUE THREAD

**Issue by tamis-laan** [expo/eas-cli#1185]
### Build/Submit details page URL

https://expo.dev/accounts/projectjoin/projects/projectjoin/builds/b91a2908-eed1-461c-beaa-209834763336

### Summary

Build fails on `react-native-navigation`

```
[stderr] FAILURE: Build completed with 2 failures.

[stderr] 1: Task failed with an exception.

[stderr] -----------

[stderr] * Where:

[stderr] Build file '/home/expo/workingdir/build/node_modules/react-native-navigation/lib/android/app/build.gradle' line: 5

[stderr] * What went wrong:

[stderr] A problem occurred evaluating project ':react-native-navigation'.

[stderr] > Plugin with id 'kotlin-android' not found.

[stderr] * Try:

[stderr] > Run with --stacktrace option to get the stack trace.

[stderr] > Run with --info or --debug option to get more log output.

[stderr] > Run with --scan to get full insights.

[stderr] ==============================================================================

[stderr] 2: Task failed with an exception.

[stderr] -----------

[stderr] * What went wrong:

[stderr] A problem occurred configuring project ':react-native-navigation'.

[stderr] >

[stderr] compileSdkVersion is not specified. Please add it to build.gradle

[stderr] * Try:

[stderr] > Run with --stacktrace option to get the stack trace.

[stderr] > Run with --info or --debug option to get more log output.

[stderr] > Run with --scan to get full insights.

[stderr] ==============================================================================

[stderr] * Get more help at https://help.gradle.org

[stderr] BUILD FAILED in 2m 10s
```

Just started with EAS so not sure if this should be reported here or with `react-native-navigation`

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.4 environment info:
    System:
      OS: Linux 5.18 Arch Linux
      Shell: 3.4.1 - /bin/fish
    Binaries:
      Node: 16.15.1 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 8.5.5 - /usr/bin/npm
    npmPackages:
      @expo/webpack-config: ~0.16.21 => 0.16.25
      expo: ^45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Not possible ATM, build should give enough information for now. Will see what I can do if required.

**Comment by dhapin** [comment]
https://docs.expo.dev/guides/routing-and-navigation/#alternatives

> - [React Native Navigation](https://github.com/wix/react-native-navigation) will not work in Expo managed workflow apps, but if you are using a bare React Native app it may be something you will consider. Similar to `createNativeStackNavigator` from React Navigation, it uses the platform native APIs.

**Comment by tamis-laan** [comment]
> https://docs.expo.dev/guides/routing-and-navigation/#alternatives
> 
> > * [React Native Navigation](https://github.com/wix/react-native-navigation) will not work in Expo managed workflow apps, but if you are using a bare React Native app it may be something you will consider. Similar to `createNativeStackNavigator` from React Navigation, it uses the platform native APIs.

omfg, `react-native-navigation` was a lingering package and it confused me with `react-navigation`.

**Comment by JFranco-Advanced** [comment]
Sorry, how you fix the problem. I have all day trying and i can't

**Comment by sn0wzZz** [comment]
Anything figured it out?

**Comment by JFranco-Advanced** [comment]
Go to package.json and delete react-native-navigation. Thats work for me

**Comment by sn0wzZz** [comment]
It worked I managed to build and install the app but it crashes once I try to launch it. Any ideas?

**Comment by jangandibantingg** [comment]
> Sorry, how you fix the problem. I have all day trying and i can't

do you have solution ?

**Comment by jorgezerpa** [comment]
`npm uninstall react-native-navigation` (the package was not needed in my case, try removing it and run your app, if run you are done)
