### ISSUE TITLE
EAS builds iOS always takes longer than 45 mins

### ISSUE THREAD

**Issue by homosape** [expo/eas-cli#1190]
### Build/Submit details page URL

https://expo.dev/accounts/valasolutions/projects/vala-solutions/builds/43637711-2971-49c1-b94a-e108e5022fbb

### Summary

I've noticed that EAS builds, regardless the size of the app, always takes longer than 45 mins, therefore, hitting a timeout limit for free accounts. 

Basically, it means that free user can't have EAS builds on iOS. I do keep track of expo status at https://status.expo.dev/ which says that it has been resolved but it appears that this issue still persists.

### Managed or bare?

Managed

### Environment

```
  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v14.18.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-S | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.4.12
    Expo Workflow: managed
```

```
✔ Found all copies of expo-modules-autolinking
  All copies of expo-modules-autolinking satisfy ~0.8.1 || ~0.9.0
✔ Found all copies of @expo/config-plugins
  All copies of @expo/config-plugins satisfy ^4.1.0
✔ Found all copies of @expo/prebuild-config
  All copies of @expo/prebuild-config satisfy ^4.0.0
```

### Reproducible demo or steps to reproduce from a blank project

Create a blank project and trigger EAS build on iOS.

**Comment by wkozyra95** [comment]
I only see one build in your account that failed with timeout

>  it has been resolved but it appears that this issue still persists.

Issue was resolved, because it's not affecting most of the builds, we are still getting occasional spikes in build time, but it's relatively rare and short

**Comment by m-sasikaran** [comment]
Hi, I am facing the same issue. Can some one please help me on this. 

https://expo.dev/accounts/msasi/projects/tracker/builds/3fee7da9-f492-40c6-a264-72391e5b5f1a

**Comment by sergeu90** [comment]
Hi. I have some issue 
![image](https://user-images.githubusercontent.com/7217517/228814106-4d179e37-60a9-4fe5-9dbb-89bc46756fca.png)
take 35 minutes and build down after timeout.

**Comment by homosape** [comment]
> Hi, I am facing the same issue. Can some one please help me on this.
> 
> https://expo.dev/accounts/msasi/projects/tracker/builds/3fee7da9-f492-40c6-a264-72391e5b5f1a

Try using M1 workers. You can read more here[](https://blog.expo.dev/m1-workers-on-eas-build-dcaa2c1333ad?gi=bcf582e2342e)

**Comment by m-sasikaran** [comment]
@homosape , no difference, got the same result.

**Comment by GhohanGehlot** [comment]
whats up i am facing same error !!
