### ISSUE TITLE
Passing environment variables to standalone EAS builds

### ISSUE THREAD

**Issue by SashaMihalache** [expo/eas-cli#1198]
### Build/Submit details page URL

https://expo.dev/accounts/room/projects/ondemand/builds/a959df0a-21aa-4468-a49c-b0990ecb4466

### Summary

Hello,

Is there any way to pass the **standalone builds** environment variables instead of having them encoded in the `AppDelegate.m` and `AndroidManifest.xml` files?

Use case example: 
I've added GoogleMaps on both iOS and Android standalone apps to have a normalized UX, but I also have to pass the google maps API key. In order for it to work, I have to set them up in the files mentioned above.

I've been trying the past couple of days to combine the eas build with the `react-native-config` in order to inject in `AppDelegate.m` and `AndroidManifest.xml` the API key coming from an `.env` file. 

Locally it works when running `expo run:ios` & `expo run:android`. (probably because locally I have and `.env` file)

But when I'm running `eas build -p all --profile development` and the builds are sent to the cloud:
-  Android build fails saying there's no `.env` file
- iOS build is successful, but when instantiating the gmaps it simply crashes

Any thoughts on this?

### Managed or bare?

Bare workflow

### Environment

`expo-env-info` output:

expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.3.2 - ~/programming/work/room/room-on-demand/native/node_modules/.bin/npm
      Watchman: 2022.03.14.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /Users/sashamihalache/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 30, 32
        Build Tools: 29.0.2, 30.0.2, 32.0.0, 33.0.0
        System Images: android-30 | Google Play ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~43.0.2 => 43.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.54.1
      expo-cli: 5.4.12
    Expo Workflow: bare

`expo doctor` output
🎉 Didn't find any issues with the project!

### Reproducible demo or steps to reproduce from a blank project

0. on GCP add an API key that has both Maps for Android SDK and Maps for iOS SDK included
1. init expo bare workflow project 
2. create a `.env` file with `GOOGLE_MAPS_API_KEY=xxx`
3. install react-native-config (https://github.com/luggit/react-native-config)
4. install react-native-maps (https://github.com/react-native-maps/react-native-maps)
5. create a simple screen that renders a `<MapView/>` component with `PROVIDER_GOOGLE` passed as a prop

For IOS:
In `AppDelegate.m`:
<img width="923" alt="image" src="https://user-images.githubusercontent.com/7697631/177559587-0c6f94a8-eed5-4817-bc2d-a6850a1fd971.png">

For Android:
In `/android/app/build.gradle`:
<img width="878" alt="image" src="https://user-images.githubusercontent.com/7697631/177560278-3f98065b-808c-4353-8ded-0c6e753def65.png">

In `/app/src/main/AndroidManifest.xml`:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/7697631/177560518-30c9b890-7f56-44f0-b4cc-16638667a67c.png">

Running `expo run:ios` or `expo run:android` should successfully build a standalone app on both simulators and google maps should be loading.

When sending the build to expo.dev via `eas build` as previously mentioned, the android build fails because it can't find the `.env` file and `iOS` will crash when loading it on physical device saying `Google Maps SDK for iOS must be initialized via [GMSServices provideAPIKey:...] prior to use`

**Comment by wkozyra95** [comment]
this doc describes what is uploaded to eas builder https://github.com/expo/fyi/blob/main/eas-build-archive.md

there are multiple approaches for passing that env file to eas build
- you could take file content of that file -> base64 encode it -> add it as EAS Seacret -> write env with that secret to file in eas-build-pre-install hook
- you could commit that file to repo encrypted with git crypt,(by default it should just work, but if you have requireCommit set to true, you will also need to upload your git crypt key using secrets mechanism and unlock them there)
- create .easignore with the same content as .gitignore but do not ignore .env(more about it in the link above), personally I don't recommend that option, but it's probably the easiest
- also consider just committing that file, those values are embedded in the app so anyone that has this app can access them if they want

**Comment by rahmanharoon** [comment]
> this doc describes what is uploaded to eas builder https://github.com/expo/fyi/blob/main/eas-build-archive.md
> 
> there are multiple approaches for passing that env file to eas build
> 
> * you could take content of that file -> base64 encode it -> add it as EAS Seacret -> write env with that secret to file in eas-build-pre-install hook
> * you could commit that file to repo encrypted with git crypt,(by default it should just work, but if you have requireCommit set to true, you will also need to upload your git crypt key using secrets mechanism and unlock them there)
> * create .easignore with the same content as .gitignore but do not ignore .env(more about it in the link above), personally I don't recommend that option, but it's probably the easiest
> * also consider just committing that file, those values are embedded in the app so anyone that has this app can access them if they want

What if i have multiple env files like env.dev, env.stage, env.prod
