### ISSUE TITLE
EAS builds are missing the latest changes on the project.

### ISSUE THREAD

**Issue by davidjtorres** [expo/eas-cli#1200]
### Summary

When running a build with  `eas build -p ios` the bulid generated does not have all the latest changes on the project (all committed). However, running it with `expo build:ios` does. Additionally all EAS builds crash the first time the app is launched. Any ideas  of what could I be doing wrong?  I have also tried  `eas build -p ios --clear-cache` . Same results.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 11.6.5
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.10 - ~/node_modules/.bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7351085
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: ^0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      expo-cli: 5.4.9
      eas-cli:  0.54.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Commit new changes to the project. 
2.  Run `eas build -p ios` 
3. Submit the app to TestFlight and Install
4. App crashes at first launch
6. The app opens on the second attempt but does not reflect any of the new changes.

**Comment by wkozyra95** [comment]
I'm not sure why it would load older code, probably it's a fallback in expo-updates to avoid bricking and app with invalid js, but in your case js from the original build causing the crash, you should look into the error during the crash when the app is opened the first time.
If it works in classic builds then most likely it's not a bug in your js code, but a problem with configuration e.g. you might be using incompatible packages or did not pass some envs to eas correctly

**Comment by davidjtorres** [comment]
**Update**
 I was relying on EAS secrets to handle env variables on the app. I removed all the secrets, and put them in eas.json.
Now the build seems to be working fine.

**Comment by wkozyra95** [comment]
You can see in build logs what secrets are injected.
We did not have any reports of problems with secrets, so if moving values to eas.json helped then the most likely issue is that you set the secrets on the wrong project(e.g. or on a project with the same name but on a different account)

**Comment by zwadzinski** [comment]
Having this exact issue of crashing on first open and changes not going through as well. Any updates on fixes for this?

**Comment by davidjtorres** [comment]
For me it fixed it putting the env variables on the eas.josn file, but I'm experiencing this again now after upgrading to SDK 47.

**Comment by bk-sin** [comment]
having this exact issue, any solution already?

**Comment by davidjtorres** [comment]
My experience tells me that this happens when there is a runtime error in the app, that makes it crash and it falls back to a previous version on next open. In my case this it was the I was having a problem with the latest version of react-native [viewproptypes has been removed from react native](https://stackoverflow.com/a/73135908). It may be something different for you @bk-sin .

**Comment by JakeTheWorld** [comment]
Any resolutions? I also had viewproptype errors that i have since fixed. Now I am having the exact same symptoms altered code seems fine in expo start. but when building with EAS build changes don't seem to make it through. I initially thought it maybe had to do with malformed android sub directories but this isn't the case. Any help would be greatly appreciated

**Comment by edi** [comment]
Hi. I don’t have a crash, never had one, but even after using `eas update —channel production —auto` running `eas build` does not reflect the applied changes.

it does show the proper version after re-opening the app, so it does fetch the update in the background.

so after running eas update, I cannot see the channel being updated in the expo dashboard either, even though I see the update going to the linked branch.

what am I missing?

**Comment by zwadzinski** [comment]
I ended up solving by using Transporter instead of EAS. Still working on Expo and Transporter has actually been more efficient than EAS too

**Comment by arinmodi** [comment]
Also Have same issue, updates are not reflecting in the apk

**Comment by arinmodi** [comment]
@ahan-s, Did you find any solution for this problem, I have exactly same problem

**Comment by ahan-s** [comment]
I had upgraded the expo sdk to version 47
if it does not works then you can delete the project from expo dev and create a new project and link it to your existing project.

**Comment by MichalKrakow** [comment]
Same problem. It's like whatever build you publish eas build sticks to js bundle that it was originaly build with ON FIRST BUILD and then just updates other assets BUT NOT THE JS BUNDLE. So on first run you get old js bundle wchich gets updated later on on second app load. How to fix this?

**Comment by csulit** [comment]
This is happening again..
