### ISSUE TITLE
[eas-cli] Factor in --non-interactive for prompts

### ISSUE THREAD

**Issue by brentvatne** [expo/eas-cli#121]
I think we can in many cases have them just default to returning whatever the default selection is.

eg:

```
eas build --non-interactive
```

-> no platform provided, default to "All" which is the default selection in the prompt

**Comment by wkozyra95** [comment]
- I added few checks before prompts here https://github.com/expo/eas-cli/pull/122 
- I'm not sure if the default value would be a good idea for the build command. Before that param was required so in noninteractive mode it should throw an error
- in expo-cli `--non-interactive` flag was global, currently, we only support it for specific commands, so creating some default handler might not best approach, but on the other hand, we would be sure that users get a meaningful error message when prompt is showing up.
- I would suggest handling this case by case for commands that support this flag

**Comment by EvanBacon** [comment]
agreed that in non interactive (CI) the command should fail if parameters aren't properly defined.
