### ISSUE TITLE
gradleCommand fails when specifying multiple tasks

### ISSUE THREAD

**Issue by alexlukelevy** [expo/eas-cli#1212]
### Summary

If `gradleCommand` contains one than one gradle task, then `eas build` fails.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - ~/Code/hifi/mobile/node_modules/.bin/yarn
      npm: 8.8.0 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 5.4.0

┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (5.5.1).                 │
│   You are currently using expo-cli 5.4.0                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
Some dependencies are incompatible with the installed expo package version:
 - expo-dev-client - expected version: ~1.0.0 - actual version installed: 0.9.6
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo doctor --fix-dependencies,
or install individual packages by running expo install [package-name ...]

### Error output

> [RUN_GRADLEW] FAILURE: Build failed with an exception.
> [RUN_GRADLEW] * What went wrong:
> [RUN_GRADLEW] Project 'assembleDebug ' not found in project ':app'.

### Reproducible demo or steps to reproduce from a blank project

`eas.json`

```json
{
  "cli": {
    "version": ">= 0.52.0"
  },
  "build": {
    "test": {
      "android": {
        "gradleCommand": ":app:assembleDebug :app:assembleAndroidTest"
      }
    }
  }
}

```

`eas build -p android --profile test --local`

If you edit `gradleCommand` to just `:app:assembleDebug` or  `:app:assembleAndroidTest` only then the build works. My understanding is that gradlew can take a list of tasks. My current workaround at the moment it to have multiple build profiles.

**Comment by wkozyra95** [comment]
this is not supported

You have 2 options:
- You can use https://docs.expo.dev/build-reference/how-tos/#eas-build-specific-npm-hooks to run tests after or before build using `eas-build-post-install`/`eas-build-pre-upload-artifacts`. Note that you would need to check OS it runs on to make sure you do not run those test on ios builds
- You could make one task depend on the other and to avoid running that locally it could be based on some env that you could specify in eas.json

> My understanding is that gradlew can take a list of tasks

yes, but whatever you are passing as an gradleCommand is treated as a single shell argument here so it's trying to start task named "assembleDebug :app:assembleAndroidTest", it's probably doing split on `:`  when parsing that is why you have that space 'assembleDebug ' in the error log

We plan to eventually support testing on eas, as a first-class citizen, but it's not sth we have currently on the roadmap

**Comment by alexlukelevy** [comment]
Thanks for your reply. 

> * You could make one task depend on the other and to avoid running that locally it could be based on some env that you could specify in eas.json

I'm not sure how I'd do that with a managed workflow...

> yes, but whatever you are passing as an gradleCommand is treated as a single shell argument here so it's trying to start task named "assembleDebug :app:assembleAndroidTest", it's probably doing split on `:` when parsing that is why you have that space 'assembleDebug ' in the error log

That makes sense why it's not working, but possibly it's not that clear from the docs. It's more of a gradle _task_ than a gradle_command_ then.
 
> We plan to eventually support testing on eas, as a first-class citizen, but it's not sth we have currently on the roadmap

Looking forward to it 😎
