### ISSUE TITLE
when enable autoIncrement for iOS the build fails

### ISSUE THREAD

**Issue by philipheinser** [expo/eas-cli#1218]
### Summary

when enable autoIncrement for iOS the build fails. 

### Managed or bare?

bare

### Environment

expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.yarn/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2022.03.21.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.0, iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.0/14A5270f - /usr/bin/xcodebuild
    npmPackages:
      react: 17.0.2 => 17.0.2 
      react-native: 0.68.1 => 0.68.1 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 5.4.12
    Expo Workflow: bare

### Error output

The CFBundleVersion of an app extension ('16') must match that of its containing parent app ('18').
2282

❌  error: The value of CFBundleVersion in your WatchKit app's Info.plist (16) does not match the value in your companion app's Info.plist (18). These values are required to match.

### Reproducible demo or steps to reproduce from a blank project

create a rn project with iOS app with WatchKit extension and enable autoIncrement in expo

**Comment by wkozyra95** [comment]
Yes, currently autoincrement updates the value of the main target only, we are currently working on a better experience for autoincrement feature that should solve that issue.

**Comment by philipheinser** [comment]
@wkozyra95 sounds great im happy to test as soon as the new feature is online 👍

**Comment by felixlucien** [comment]
So does autoincrement work at all? Docs are not really helping here :(

**Comment by wkozyra95** [comment]
@felixlucien yes it works, what is not clear in the documentation?

https://docs.expo.dev/build-reference/eas-json/#autoincrement

**Comment by felixlucien** [comment]
Hey wkoz, I'm a bit confused by how the autoIncrement parameter interacts with the app.config.js, are there a way we can have the build number autoIncrement while using app.config.js?

**Comment by wkozyra95** [comment]
From the link I sent in my previous comment

> This feature is not intended for use with dynamic configuration (app.config.js). EAS CLI will throw an error if you don't use app.json.

**Comment by wkozyra95** [comment]
the issue should be fixed in latest cli, but the "better experience for autoincrement feature" I mentioned in the first comment will land in the next cli version.
