### ISSUE TITLE
Authentication with Apple Developer Portal failed!

### ISSUE THREAD

**Issue by igorcesarcode** [expo/eas-cli#1220]
### Summary

I'm trying to do my first build on ios with eas.
But I'm having an error when logging in with apple id.

Even putting the code correctly shows an error.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.4 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.0/bin/yarn
      npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
      Watchman: 2022.06.27.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      expo-cli: 5.4.6
    Expo Workflow: managed

VERSION
  eas-cli/0.55.1 darwin-x64 node-v16.15.0

### Error output

Authentication with Apple Developer Portal failed! Error: Error Description not available Code: -20528

### Reproducible demo or steps to reproduce from a blank project

eas build -p ios --profile production

![image](https://user-images.githubusercontent.com/44711552/179866129-d8fe4c84-a7e9-453e-89a2-7eb341b40d47.png)

**Comment by wkozyra95** [comment]
Was that just a transient issue or do you still experiencing that problem? Maybe try logging in to https://developer.apple.com/ and check if there is no policy change you need to accept. Did you try SMS option to validate the account?

**Comment by igorcesarcode** [comment]
@wkozyra95 

1° Yes I am facing this problem and with that I am unable to create the build.

2° Yes, I went to developer.apple.com and confirmed that there were no changes to the terms

3° Yes, I tried both ways without success.

**Comment by izaakrogan** [comment]
@igorcesarcode did you find a solution? I'm facing the same issue

**Comment by igorcesarcode** [comment]
@izaakrogan Yes, I still have this problem, I ended up giving up on launching my app on the apple store, through EAS Build.
 
I migrated the project to react native cli

**Comment by saikrishna6938** [comment]
I got this same issue, I changed my network  and it worked for me.

**Comment by igorcesarcode** [comment]
For those looking for a solution, in the process the company I work for moved to the app center due to the difficulties of several of our devs not being able to connect to apple.

The tool is wonderful, but the small difficulties made it impossible to work with it.

**Comment by dmitryame** [comment]
I'm having this issue today, any resolution from previous failures?

**Comment by Sidibedev** [comment]
also having this issue. +1

**Comment by dmitryame** [comment]
https://stackoverflow.com/questions/75347609/eas-build-ios-failure-authentication-with-apple-developer-portal-failed/75347883#75347883
There are some reports that it started happening for some people. Looks like expo server side issue...

**Comment by kev2010** [comment]
+1 Getting this error over and over:

```
Authentication with Apple Developer Portal failed!
    Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
```

**Comment by Lamonarch87** [comment]
Me too. Same issue after apple account maintenance.

**Comment by Huguet57** [comment]
Same, seems like a mantainance thing

**Comment by neypalma79** [comment]
Hi, is there any solution for this issue? Greetings

**Comment by kristianhristov** [comment]
+1

**Comment by PSodor01** [comment]
+1

**Comment by Lamonarch87** [comment]
#1672 this issue is open. Report there.

**Comment by imarc7** [comment]
Having the same issue

**Comment by addeelnayyer** [comment]
Build worked perfect 4 hours ago. Now it is showing this error:

<img width="901" alt="image" src="https://user-images.githubusercontent.com/96280770/216789437-1287cecd-3bc2-494f-8b0c-0312effb1982.png">

**Comment by BerkeAras** [comment]
_Same issue_

**Comment by fipster-dev** [comment]
+1 Same issue here

**Comment by nickreese** [comment]
Same issue

**Comment by isabellahoch** [comment]
having the same issue!

**Comment by timlangner** [comment]
Same here! I was able to build my app using EAS by selecting "No" for the "Do you want to log in to your Apple account?" question but submitting to the App Store is not possible right with this issue.

**Comment by gharker** [comment]
I'm having the same issue.

**Comment by andreyxdd** [comment]
Hm, guys don't you think that we just need to review and agree with the new agreement in the app store connect?

**Comment by guillaumegaluz** [comment]
> Hm, guys don't you think that we just need to review and agree with the new agreement in the app store connect?

usually those appear as soon as i login but i don't get anything right now. you do?

**Comment by erstefan** [comment]
Same issue here as well.

Checked App Store Connect and there is nothing (new) to agree to.

**Comment by andreyxdd** [comment]
> > Hm, guys don't you think that we just need to review and agree with the new agreement in the app store connect?
> 
> usually those appear as soon as i login but i don't get anything right now. you do?

Yeah, I have "New agreements are now available for you to accept." under the "Agreements" tab. However, I can't press on agree button, because I guess I don't have enough permissions in the project.

**Comment by MrtnvM** [comment]
The same issue

```
✔ Please enter the 6 digit code you received at .....
✔ Valid code
✔ Logged in and verified
Authentication with Apple Developer Portal failed!
    Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
```

**Comment by fipster-dev** [comment]
I've gone through and agreed to the new paid app agreement on AppStore Connect and provided all of the info necessary. Agreement have been approved. Still the same issue though.
```
Authentication with Apple Developer Portal failed!
    Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com 
    Request:developer.apple.com
```

**Comment by lucidprojects** [comment]
same.  agreed to the new agreement and still can't submit.   At least I'm not alone.  🍿

**Comment by dmitryame** [comment]
I've had that agreement lingering for a while, never completed it because it does not apply to my case -- everything was working fine. It's something else. We really need some input from the expo team on this.

**Comment by maybenat** [comment]
+1

**Comment by dtantil1** [comment]
+1

**Comment by vince971** [comment]
+1

**Comment by mikealche** [comment]
Seems like apple changed the CDN and broke this flow for all of us

**Comment by YoelEigner** [comment]
+1

**Comment by dvirben** [comment]
Same error for me:

Authentication with Apple Developer Portal failed!
    Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com

**Comment by yotam-frid** [comment]
Any update from the EAS team?

**Comment by d3v4nt** [comment]
+1

**Comment by shifanpark** [comment]
+1

**Comment by dix1409** [comment]
+1

**Comment by Charfedineee** [comment]
+1 ! it's kinda comforting find out I'm not the only one haha

**Comment by fipster-dev** [comment]
Some work arounds also discussed in this open `eas-cli` issue 

https://github.com/expo/eas-cli/issues/1672

**Comment by ycaptain** [comment]
> 

Worked! Thank you!!

**Comment by ycaptain** [comment]
> Some work arounds also discussed in this open `eas-cli` issue
> 
> #1672
> 
> I can confirm that the hack [here](https://github.com/expo/eas-cli/issues/1672#issuecomment-1417514145) worked for me with `eas build`.
> 
> I've not tried `eas submit` yet though

Worked for me, thank you!

**Comment by Sidibedev** [comment]
I was able to build and submit it by pressing no when asking **Do you want to log in to your Apple account?**

**Comment by clarkology56** [comment]
This worked for me - I chose to not sign into my apple account for the build. Then I downloaded the build from expo and submitted it via transporter to apple app store

**Comment by lucidprojects** [comment]
Also confirmed configuring user and ascAppId in eas.json makes it work as well.  as detailed [here](https://github.com/expo/fyi/blob/main/asc-app-id.md) 

```
"submit": {
    "production": {
      "ios": {
        "appleId": "email@email.com",
        "ascAppId": "[Apple ID]"
      }
    }
  }
```

**Comment by timlangner** [comment]
> Also confirmed configuring appleId and ascAppId in eas.json makes it work as well. as detailed [here](https://github.com/expo/fyi/blob/main/asc-app-id.md)
> 
> ```
> "submit": {
>     "production": {
>       "ios": {
>         "appleId": "email@email.com",
>         "ascAppId": "[Apple ID]"
>       }
>     }
>   }
> ```

This works for me & is a good workaround for now. Don't forget to still select "No" when being asked if you want to log into your apple account.

**Comment by ornakash** [comment]
This is now fixed by the expo team. In order for it to work, all you have to do is update to the latest eas-cli. This should do it:

npm i -g eas-cli
Then build or submit you application to iOS.

eas build --platform ios --auto-submit
Of course you can ignore the --auto-submit.

**Comment by ErnestCodes** [comment]
upgrade the eas-cli. That should solve the problem

**Comment by jeltehomminga** [comment]
would be helpful it was showed in the error that it's needed to upgrade the eas-cli

**Comment by ErionTp** [comment]
My problem was resolved by upgrading eas-cli: `npm install -g eas-cli`

**Comment by VhonaniSpecno** [comment]
> ked for me, thank yo

yup, this is the fix

**Comment by KeaganStevens** [comment]
I have the same problem ,but I get a different error on the latest update.

Authentication with Apple Developer Portal failed!
   Error: Apple Service Error -36607. Unable to sign you in to your Apple ID. Try again later. <a target="_blank" 
   href="https://support.apple.com/kb/HT212522 ">Learn more.<span class="sr-only"> Opens in a new window.</span></a>


After retrying a few times yesterday and today, I logged onto appstore connect on my browser, and was then asked to recover my account. So I went through the process and changed my password. Tried EAS build again and still failed.
I have not tried the hack in [#1672 ](https://github.com/expo/eas-cli/issues/1672#issuecomment-1417514145).

EAS Version: eas-cli/3.6.1 win32-x64 node-v16.9.1

**Comment by MaxAst** [comment]
got the same issue as @KeaganStevens since today: 

```
✖ Logging in...
Authentication with Apple Developer Portal failed!
    Error: Apple Service Error -36607. Unable to sign you in to your Apple ID. Try again later. <a target="_blank" 
    href="https://support.apple.com/kb/HT212522 ">Learn more.<span class="sr-only"> Opens in a new window.</span></a>
```
after getting the error, I do get the Apple ID verification code prompt on my apple devices though, so it might be that the CLI is not able to handle cases where 2fa is required.

**Comment by jan-karnik** [comment]
Got it working by installing the new 3.7.0 version. Now it prompts you for the 2fa code

`eas-cli/3.7.0 darwin-arm64 node-v16.15.0`

**Comment by 67millwood** [comment]
> got the same issue as @KeaganStevens since today:
> 
> ```
> ✖ Logging in...
> Authentication with Apple Developer Portal failed!
>     Error: Apple Service Error -36607. Unable to sign you in to your Apple ID. Try again later. <a target="_blank" 
>     href="https://support.apple.com/kb/HT212522 ">Learn more.<span class="sr-only"> Opens in a new window.</span></a>
> ```
> 
> after getting the error, I do get the Apple ID verification code prompt on my apple devices though, so it might be that the CLI is not able to handle cases where 2fa is required.
> 
> eas-cli/3.6.1 darwin-arm64 node-v18.12.1

also cannot get it to work today.  tried eas-cli 3.5.2....tried 3.7....no dice.  reset keychain...

**Comment by jpatricksweeney** [comment]
I'm getting the same error as @KeaganStevens

**Comment by cdosborn** [comment]
See this issue for updates: https://github.com/expo/eas-cli/issues/1714

**Comment by kenorvick** [comment]
I am working with an old expo project but was able to get everything working using the following to build an ipa:

1. (Not sure if needed but is what I did on the final success) Removed and re-added all files within: /Users/{yourusername}/.app-store/auth/
2. With latest version of eas-cli: `eas credentials`
3. Selected no when asked to log into apple developer account
4. Select `Manage everything needed to build your project`
5. Select `All: Set up all the required credentials to build your project`
6. When prompted to log into apple account, now log in
7.  Generate all new certificates and provisioning profiles
8. Now run `eas build -p ios`

Hope this helps. I went through all previous suggestions before such as changing `ignoreErrors:true` shown above in a previous thread so it could have been a combination

**Comment by patrinoua** [comment]
Running everything @kenorvick suggested resolved the issue for me. 

The cookies were expired and the provisional profile so
`eas credentials` was the magic command to renew them.

Thanks!

**Comment by monkeyK1n9** [comment]
I had the same issue and eas could not even identify my developer team. Deleting the cookie file solved the issue. I was prompt to login again at the build/submit and it worked fine.

**Comment by Karniej** [comment]
![image](https://github.com/expo/eas-cli/assets/24280640/c0c231ba-1992-47f6-b1da-c3ce6c3b1974)
Have anyone had this kind of issue with the newly configured project? I want to use eas and do everything automatically as I did on my previous project.

**Comment by DaatKruby** [comment]
I'm having this issue

**Comment by Amusa-Paulos** [comment]
@DaatKruby I had the same issue and it was because of my node version, if you are using a PC that supports nvm   

first check your node version if it is higher that version 18, downgrade it to version 18 using `nvm use v18.x.x` command and you could also choose a lower version than version 18.x.x

**Comment by GHUApsynet** [comment]
Personally, I was using SSH through a VPN. Instead i went on the Mac and used "eas credentials" there, and it worked.

So i guess turn off your VPN and SSH.

**Comment by dolapo-oluremi** [comment]
> Also confirmed configuring appleId and ascAppId in eas.json makes it work as well. as detailed [here](https://github.com/expo/fyi/blob/main/asc-app-id.md)
> 
> ```
> "submit": {
>     "production": {
>       "ios": {
>         "appleId": "email@email.com",
>         "ascAppId": "[Apple ID]"
>       }
>     }
>   }
> ```

works!

**Comment by Noitidart** [comment]
Thanks @dolapo-oluremi that worked for me too!

**Comment by MarkPopovich** [comment]
Had this problem today. 

After trying many of the options here, it turned out to be due to the fact that I was ssh'ed into my macbook pro via my windows desktop. 

After trying the exact same build command on directly on my macbook, 2FA kicked in and I was able to log in and start the build immediately.

**Comment by michel-reyes** [comment]
After try all the solutions provided here and more, I ended up:
- create anew user profile on my Mac and that works
- I tracked the keys added to my Mac keychain
- I returned to my previous user (the one with the issue)
- Go to Mac keychain app
- search for this terms and delete the entries
   - <key> (private and public key)
   - handoff-own-encryption-key
   - deliver.[your Apple ID here]
- Go to Terminal and continue using that command that fail, should work

**Comment by lewisdonovan** [comment]
Updating eas-cli and restarting my machine worked for me 🤷🏻‍♂️

**Comment by nyitraibence** [comment]
I've changed my node version with nvm and that solved it. Interestingly I changed it backwards from v20.17.0 to v18.20.1 insipred by @paulosabayomi 's comment and now it just worked.

**Comment by da-war** [comment]
Faced in 2025. The reason was location. My client who gave me the account access was from US and I am from the beautiful country Pakistan. 

When you use a different location account this happened. Solved by using US VPN

**Comment by den-ii** [comment]
Also happens if you're not using the latest eas-cli

**Comment by LucaL1fe** [comment]
I was working from Vietnam, connected to a VPN in the US and it works...
