### ISSUE TITLE
Can't find file after eas build with artifactPath

### ISSUE THREAD

**Issue by Heli0os** [expo/eas-cli#1225]
Hi everyone,

I am a beginner with Expo and I am working on a CI/CD project to upgrade our deployment and test flow.
I am currently facing an issue with my generated artifacts from Expo as I would like to store them in my repository after the build succeeded in order to retrieve them later with pipelines.

I use the following command to build my project on Expo for both iOS and Android : 

`eas build --platform all --non-interactive --profile preview`

**Eas.json file description :** 

```
"build": {
    "preview": {
      "android": {
        "buildType": "apk",
        "artifactPath" : "android/build"
      },
      "ios" : {
        "simulator" : true,
        "artifactPath" : "ios/build"
      },
      "distribution": "internal"
    }
  },
```

**Project structure :** 

I have both folders in my project : 
- android/build
- ios/build

**Final issue :** 

My app has been successfully builded on Expo but I can't find my artifact **(app.tar.gz for iOS)** in my /ios/build folder.
Here is the build output : 

```
✔ Build finished

🍎 iOS app:
https://expo.dev/artifacts/eas/***********.tar.gz
```

If anyone has an idea how I can retrieve it correctly, it would help me a lot.
Thanks in advance !

**Comment by Heli0os** [comment]
@wkozyra95 Thanks for the reply ! 

That looks clear now.
Would it be possible to automatise this ? It would help me a lot !

**Comment by wkozyra95** [comment]
Yes, you can run `eas build --json`  pipe that to e.g. `jq` and extract archive URL from that. After you get URL just curl/wget and commit changes

**Comment by Heli0os** [comment]
Thanks a lot ! 
I will take a look to that and test, I might close the issue a bit later if it works.

**Comment by Heli0os** [comment]
I think it worked, I managed to retrieve the output and curl the url but the output of the curl is quite strange.
I have a link to my artifact as a .tar.gz file but when I unzip it, I don't see any .app file. Am I missing something there ?

**Comment by Heli0os** [comment]
I am following the expo EAS build documentation and it says that I should have a tar.gz file after the build. 
I successfully retrieve it and I managed to download it with curl as you recommended in your reply. However, I don't see any .app file as mentioned in the documentation. Am I missing something?

**Comment by dsokal** [comment]
I'm closing the issue because of the inactivity. Let us know if we can help you with anything.
