### ISSUE TITLE
app.config.js output to stdout breaks Gradle build

### ISSUE THREAD

**Issue by nmschulte-aviture** [expo/eas-cli#1226]
### Summary

The `console.log` diagnostic executed from `app.config.js` causes `eas build --profile android` to fail running `gradlew`'s `:app:bundleReleaseJsAndAssets`.

ex: ```console.log(`APP_VARIANT is "${JSON.stringify(process.env.APP_VARIANT)}"`)```

```
> Task :app:bundleReleaseJsAndAssets
APP_VARIANT is "development"
warning: the transform cache was reset.
Error: The resource `/home/expo/workingdir/build/APP_VARIANT is "development"
index.js` was not found.
    at /home/expo/workingdir/build/node_modules/metro/src/IncrementalBundler.js:297:24
    at gotStat (fs.js:1782:21)
    at FSReqCallback.oncomplete (fs.js:168:21)
info Run CLI with --verbose flag for more details.
> Task :app:bundleReleaseJsAndAssets FAILED
```
Using `console.error` (stderr) instead mitigates the issue.

### Managed or bare?

managed

### Environment

N/A

### Reproducible demo or steps to reproduce from a blank project

(see description)

**Comment by dsokal** [comment]
I cannot reproduce the issue using provided steps.

**Comment by danielricecodes** [comment]
I just had this same problem.  commenting out `console.log` lines fixed the issue.

**Comment by eprice122** [comment]
+1

**Comment by AlastairTaft** [comment]
Noting here my EAS builds on Expo in SDK 45 were failing and it was too to do with having a `console.log` in the app.config.js

**Comment by dsokal** [comment]
Can any of you share a reproducible example of the issue?

**Comment by nmschulte-aviture** [comment]
```
npx expo init my-app --template blank
npx eas init
npx build:configure --platform=android
cat <<- EOF > app.config.js
export default ({ config }) => {
  console.log('break\nbreak');
  config.android.package = 'my.app';
  return config;
};
EOF
```
`npx eas build --platform=android` : --
```
Error: The resource `/home/expo/workingdir/build/break

break

index.js` was not found.

    at /home/expo/workingdir/build/node_modules/metro/src/IncrementalBundler.js:297:24

    at gotStat (node:fs:2637:21)

    at FSReqCallback.oncomplete (node:fs:198:21)
```
