### ISSUE TITLE
 App includes SDK com.segment.analytics.android:analytics

### ISSUE THREAD

**Issue by tomgiam** [expo/eas-cli#1229]
### Build/Submit details page URL

https://expo.dev/accounts/tomgiam/projects/andiamo_places/builds/bdb86526-6589-40e5-a124-93c3fbdddbed

### Summary

When creating a new release for Android, google gives the error message "App includes SDK com.segment.analytics.android:analytics".

Note: I was getting this same error with expo build using SDK 44, I upgrades to SDK 45 and still got the error, I upgraded to EAS build and I'm still getting the same error. So, it must have something to do with my project. How can I determine which package is using this SDK?

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.14.0 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28
        Build Tools: 28.0.3
        System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6200805
    npmPackages:
      expo: ~45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (5.5.1).                 │
│   You are currently using expo-cli 5.4.12                               │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with expo-cli on Windows. You may encounter issues using cmd.exe.        

√ Found all copies of expo-modules-autolinking
  All copies of expo-modules-autolinking satisfy ~0.8.1 || ~0.9.0
√ Found all copies of @expo/config-plugins
Expected package @expo/config-plugins@^4.1.0        
Found invalid:
  @expo/config-plugins@4.0.7
  @expo/config-plugins@4.0.7
  @expo/config-plugins@4.0.7
  @expo/config-plugins@4.0.7
  (for more info, run: npm why @expo/config-plugins)
√ Found all copies of @expo/prebuild-config
Expected package @expo/prebuild-config@^4.0.0
Found invalid:
  @expo/prebuild-config@3.0.7
  (for more info, run: npm why @expo/prebuild-config)

### Error output

No errors from eas build. The error is from google play console. "includes SDK com.segment.analytics.android:analytics"

### Reproducible demo or steps to reproduce from a blank project

NA, it's probably specific to my project.

**Comment by tomgiam** [comment]
It appears that google Play store is showing errors from old builds. They stay there until they are dismissed. After dismissing them, the new versions don't have the error.

**Comment by Eliav2** [comment]
I've also has this problem with expo SDK 45, looking the permissions my bundle app uses in the android developer console console is as follow:
```
android.permission.ACCESS_NETWORK_STATE, 
android.permission.INTERNET, 
android.permission.MODIFY_AUDIO_SETTINGS, 
android.permission.READ_APP_BADGE, 
android.permission.READ_EXTERNAL_STORAGE, 
android.permission.RECEIVE_BOOT_COMPLETED, 
android.permission.RECORD_AUDIO, 
android.permission.SYSTEM_ALERT_WINDOW, 
android.permission.VIBRATE, 
android.permission.WAKE_LOCK, 
android.permission.WRITE_EXTERNAL_STORAGE, 
com.anddoes.launcher.permission.UPDATE_COUNT, 
com.google.android.c2dm.permission.RECEIVE, 
com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE, 
com.htc.launcher.permission.READ_SETTINGS, 
com.htc.launcher.permission.UPDATE_SHORTCUT, 
com.huawei.android.launcher.permission.CHANGE_BADGE, 
com.huawei.android.launcher.permission.READ_SETTINGS, 
com.huawei.android.launcher.permission.WRITE_SETTINGS, 
com.majeur.launcher.permission.UPDATE_BADGE, 
com.oppo.launcher.permission.READ_SETTINGS, 
com.oppo.launcher.permission.WRITE_SETTINGS, 
com.sec.android.provider.badge.permission.READ, 
com.sec.android.provider.badge.permission.WRITE, 
com.sonyericsson.home.permission.BROADCAST_BADGE, 
com.sonymobile.home.permission.PROVIDER_INSERT_BADGE, 
me.everything.badger.permission.BADGE_COUNT_READ, 
me.everything.badger.permission.BADGE_COUNT_WRITE
```
non of them is `com.segment.analytics.android:analytics` or even include the words analytics and I still got this error and have no idea what the problem is

someone help?
