### ISSUE TITLE
EAS build failing Pod Install with pnpm

### ISSUE THREAD

**Issue by zaniluca** [expo/eas-cli#1230]
### Build/Submit details page URL

https://expo.dev/accounts/zaniluca/projects/expo-cicd-github-actions/builds/2e382e5e-d0a8-4839-95a8-f2ed1a5c592a

### Summary

When trying to run a remote build on any project using the **pnpm package manager** it fails the Pod Install step with the output pasted below.

I noticed this on a production app where I recently migrated from yarn to pnpm, reverting this change made the build succeed. I tried on a brand new project and it still resulted in the same error when using pnpm as the package manager instead of yarn

### Managed or bare?

Managed

### `npx expo-env-info`
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~45.0.0 => 45.0.6
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed
```
### `expo doctor`
```
🎉 Didn't find any issues with the project!
```

### Error output

```
Installing pods
[stderr] 
node:internal/modules/cjs/loader:936
[stderr] 
  throw err;
[stderr] 
  ^
[stderr] 
[stderr] 
Error: Cannot find module 'expo-modules-autolinking/package.json'
[stderr] 
Require stack:
[stderr] 
- /Users/expo/workingdir/build/ios/[eval]
[stderr] 
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[stderr] 
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
[stderr] 
    at [eval]:1:9
[stderr] 
    at Script.runInThisContext (node:vm:129:12)
[stderr] 
    at Object.runInThisContext (node:vm:305:38)
[stderr] 
    at node:internal/process/execution:75:19
[stderr] 
    at [eval]-wrapper:6:22
[stderr] 
    at evalScript (node:internal/process/execution:74:60)
[stderr] 
    at node:internal/main/eval_string:27:3 {
[stderr] 
  code: 'MODULE_NOT_FOUND',
[stderr] 
  requireStack: [ '/Users/expo/workingdir/build/ios/[eval]' ]
[stderr] 
}
[!] Invalid `Podfile` file: cannot load such file -- ./scripts/ios/autolinking_manager.
 #  from /Users/expo/workingdir/build/ios/Podfile:1
 #  -------------------------------------------
 >  require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
 #  require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
 #  -------------------------------------------
pod exited with non-zero code: 1
```

### Reproducible demo or steps to reproduce from a blank project

This is reproducible by initializing a new expo project, removing the `node_modules` folder and the` yarn.lock` file and running `pnpm install` with `pnpm >= 7.0.0`.

The project I tested it with are these:

Production project: https://github.com/zaniluca/ping-4-gitlab
Bare project with minimum repro: https://github.com/zaniluca/expo-cicd-github-actions

Thanks for your time and great work! If you need more info I'm more than happy to provide them!

**Comment by wkozyra95** [comment]
pnpm is supported on EAS, but not by expo packages in general. If you have a bare project that you can build in android studio/xcode then it will work on eas, but it's on you to configure it in a way that works with expo and react-native module resolution. For managed project situation is very similar, if you run `expo prebuild` and you are able to build that project locally it should also work on EAS.

As far as I'm aware some people were able to configure it for managed workflow, it should be a matter of some options in .npmrc files, but I'm not familiar with the details.

> Bare project with minimum repro:

This is a managed project, bare project would have android and ios directory

Closing as it does not seem to be an eas issue, but if are able to build that locally and not on eas please reopen the issue.

**Comment by zaniluca** [comment]
@wkozyra95 thanks for the reply! By **Bare** I meant "Minimum repro", I understand that it was not clear at first. so if I want to use `expo-*` packages I can't use `pnpm` in my project, am I right?

**Comment by conor909** [comment]
@wkozyra95 so pnpm is not officially supported for expo projects?
