### ISSUE TITLE
Archive failed when building app with expo-updates on sdk 45/46 because of expo-updates

### ISSUE THREAD

**Issue by skjorrface** [expo/eas-cli#1234]
Both for android and ios, when trying to build a store distribution (everything goes fine with development client and internal distributions), I get this archive failed error related to expo-updates: (this is the ios one, android error is similar):

`
[RUN_FASTLANE] ▸ ** ARCHIVE FAILED **                                                                                                            
[RUN_FASTLANE] ▸ The following build commands failed:                                                                                            
[RUN_FASTLANE] ▸        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'expo-dev-menu' from project 'Pods')    
[RUN_FASTLANE] ▸        PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/username/Library/Developer/Xcode/
DerivedData/MyApp-edhvlkqeryypieawhhmnzycwnguh/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Rel
ease-iphoneos/EXUpdates.build/Script-46EB2E00044BD0.sh (in target 'EXUpdates' from project 'Pods')                                               
[RUN_FASTLANE] ▸ (2 failures)                                                                                                                    
[RUN_FASTLANE] › Packaging expo-haptics Pods/ExpoHaptics » libExpoHaptics.a                                                                      
[RUN_FASTLANE] › Executing expo-haptics Pods/ExpoHaptics » Copy generated compatibility header                                                   
[RUN_FASTLANE] › Compiling expo-secure-store Pods/EXSecureStore » EXSecureStore.m                                                                
[RUN_FASTLANE] › Compiling expo-secure-store Pods/EXSecureStore » EXSecureStore-dummy.m                                                          
[RUN_FASTLANE] 2022-07-26 20:19:36.737 xcodebuild[72546:791913] Requested but did not find extension point with identifier Xcode.IDEKit.Extension
SentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore            
[RUN_FASTLANE] 2022-07-26 20:19:36.737 xcodebuild[72546:791913] Requested but did not find extension point with identifier Xcode.IDEKit.Extension
PointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWat
chSupportCore                                                                                                                                    
[RUN_FASTLANE] ** ARCHIVE FAILED **                                                                                                              
[RUN_FASTLANE]                                                                                                                                   
[RUN_FASTLANE]                                                                                                                                   
[RUN_FASTLANE] The following build commands failed:                                                                                              
[RUN_FASTLANE]  CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'expo-dev-menu' from project 'Pods')            
[RUN_FASTLANE]  PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/username/Library/Developer/Xcode/DerivedD
ata/Demov8-edhvlkqeryypieawhhmnzycwnguh/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/IntermediateBuildFilesPath/Pods.build/Release-iph
oneos/EXUpdates.build/Script-46EB2E00044BD0.sh (in target 'EXUpdates' from project 'Pods')
[RUN_FASTLANE] (2 failures)
`

expo doctor doesn't complain about anything and as I already pointed out I'm not having issues at all with development builds. What am I missing/doing wrong here? P.S. I do my builds locally but same result on expo cloud build service.

**Comment by dsokal** [comment]
Please fill out the issue template.

**Comment by skjorrface** [comment]
It turns out I had messed with project dev dependencies/typescript settings. (Setting up a new project solved everything). Thanks for help and sorry for not exposing this issue/question based on the right template. I will read more carefully next time. ☺️

**Comment by dani-z** [comment]
Funny enough, I am having the exact same issue on a quite fresh project. @skjorrface, did you maybe manage to pinpoint what the issue was for you?

**Comment by skjorrface** [comment]
@dani-z If I remember accurately I just messed up my tsconfig.json. I just added something which made the build fail. Reverting to the original one from expo init resolved the issue.
