### ISSUE TITLE
Ios app built on eas cli validation via Transporter to Testflisht

### ISSUE THREAD

**Issue by vladis-c** [expo/eas-cli#1235]
### Summary

Hi! 

I am trying to upload the iOS app to Testflight via Transporter on MacOs. 

I am getting the following errors:
I cannot solve any of them, because there is quite little info on the internet. 

Eas cli 0.55.1 
Expo 45

App run with expo run:ios successfully
Build run with eas build -p ios successfully.

Using expo notificaitons, maybe this is the reason?

Asset validation failed (90081)
This bundle is invalid. Applications built for more than one architecture require an iOS Deployment Target of 3.0 or later. (ID: 7a98bf5a-3db8-43e2-8735-0838ba430f4c)

Asset validation failed (90171)
Invalid Bundle Structure - The binary file 'hammashelppiapp.app/Frameworks/GoogleAppMeasurementOnDeviceConversion.framework/GoogleAppMeasurementOnDeviceConversion' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure. (ID: 51df662f-2a51-4323-b65a-e7e3a09aa6de)

Asset validation failed (90124)
The binary is invalid. The executable 'hammashelppiapp.app/Frameworks/GoogleAppMeasurementOnDeviceConversion.framework/GoogleAppMeasurementOnDeviceConversion' has type 'OBJECT' that is not valid. Only 'EXECUTE' is permitted. (ID: 1aea1aa2-29de-49ca-85d0-45b0a60975b2)

Asset validation failed (90360)
Missing Info.plist value. A value for the key 'MinimumOSVersion' in bundle hammashelppiapp.app/Frameworks/GoogleAppMeasurementOnDeviceConversion.framework is required. (ID: 9ac79685-8c59-4dfd-a0c8-2184c9d572b3)

Asset validation failed (90124)
The binary is invalid. The executable 'hammashelppiapp.app/Frameworks/GoogleAppMeasurementOnDeviceConversion.framework/GoogleAppMeasurementOnDeviceConversion' has type 'OBJECT' that is not valid. Only 'EXECUTE' is permitted. (ID: 47364d2b-16e4-4b6d-aba6-49c82f667b1f)

Asset validation failed (90125)
The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker. (ID: 6b59f71e-2cfa-4f28-9274-8e2ba44e81cc)

Asset validation failed (90125)
The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker. (ID: 449d3ef7-fa98-482e-b665-439f40d3554c)

Asset validation failed (90210)
Missing load commands. The executable at 'hammashelppiapp.app/Frameworks/GoogleAppMeasurementOnDeviceConversion.framework' does not have the necessary load commands. Try rebuilding the app with the latest Xcode version. If you are using third party development tools, contact the provider. (ID: 50257a45-06a7-47bf-83b5-e4f2a8f56255)

Asset validation failed (90635)
Invalid Mach-O Format. The Mach-O in bundle "hammashelppiapp.app/Frameworks/GoogleAppMeasurementOnDeviceConversion.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains arm64(bitcode), while the nested bundle Mach-O contains armv7(machine code) and arm64(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting. (ID: 97823ded-e1f3-4772-90bd-f503af046e57)

Asset validation failed (90208)
Invalid Bundle. The bundle hammashelppiapp.app/Frameworks/GoogleAppMeasurementOnDeviceConversion.framework does not support the minimum OS Version specified in the Info.plist. (ID: 28ca7f23-f7ef-49aa-9225-9334dbdc06ae)

### Managed or bare?

bare

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.5.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~45.0.0 => 45.0.2 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.55.1
      expo-cli: 6.0.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

No code.

**Comment by Lauwed** [comment]
Hello,
I have the same issue, did u resolved it ?

- `eas -v` : `eas-cli/2.8.0 win32-x64 node-v16.13.2`
- Expo : `~47.0.7`
- Dev run is working
- EAS build ios is working

I had a bare workflow but with the migration of Expo SDK 47, nothing was working correctly so I came back to a managed workflow. Android is working perfectly for A to Z, but the submitting of iOS is not working.

Please help, I tried everything and I find nothing. I have a managed workflow, where can I change that ?

```
Starting the submit process
Downloading archive
Preparing artifact
Verifying archive
Creating ascApiJsonKey.json file with ASC credentials
Submitting iOS app to TestFlight...
Submitting the app with fastlane pilot
-------------------
--- Step: pilot ---
-------------------
Creating authorization token for App Store Connect API
Ready to upload new build to TestFlight (App: 1608329485)...
Going to upload updated app to App Store Connect
This might take a few minutes. Please don't interrupt the script.
[altool] 2022-11-29 05:39:06.800 *** Error: Asset validation failed This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: 2f489105-f922-41b7-b124-9632a452420c) (90101)
[altool]  {
[altool]     NSLocalizedDescription = "Asset validation failed";
[altool]     NSLocalizedFailureReason = "This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: 2f489105-f922-41b7-b124-9632a452420c)";
[altool]     "original_server_error" =     {
[altool]         code = "STATE_ERROR.VALIDATION_ERROR.90101";
[altool]         detail = "This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html";
[altool]         id = "2f489105-f922-41b7-b124-9632a452420c";
[altool]         status = 409;
[altool]         title = "Asset validation failed";
[altool]     };
[altool] }
Application Loader output above ^
ERROR: Asset validation failed (90101) This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: 2f489105-f922-41b7-b124-9632a452420c)
Error uploading '/var/folders/h2/gp9wlkv11lg0qj6y2mnqgc_40000gn/T/81764e1b-cd80-4fe2-bbbb-dfa691d55117.ipa'.
Asset validation failed This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: 2f489105-f922-41b7-b124-9632a452420c) (90101)
The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
Could not download/upload from App Store Connect!
[stderr] [!] Error uploading ipa file: 
[stderr]  [Application Loader Error Output]: ERROR: Asset validation failed (90101) This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: 2f489105-f922-41b7-b124-9632a452420c)
[stderr] [Application Loader Error Output]: Error uploading '/var/folders/h2/gp9wlkv11lg0qj6y2mnqgc_40000gn/T/81764e1b-cd80-4fe2-bbbb-dfa691d55117.ipa'.
[stderr] [Application Loader Error Output]: Asset validation failed This bundle does not support one or more of the devices supported by the previous app version. Your app update must continue to support all devices previously supported. You declare supported devices in Xcode with the Targeted Device Family build setting. Refer to QA1623 for additional information: https://developer.apple.com/library/ios/#qa/qa1623/_index.html (ID: 2f489105-f922-41b7-b124-9632a452420c) (90101)
[stderr] [Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
Fastlane pilot failed
fastlane exited with non-zero code: 1
Failed to submit the app
We couldn't figure out what went wrong. See logs to learn more.
```

Going to https://developer.apple.com/library/ios/#qa/qa1623/_index.html doesn'tg help at all

I don't have a reproducible demo bc i don't know how to reproduce this bug and there sensitive information in my app.

Thank you very much...

**Comment by CharlyPoppins** [comment]
@Lauwed don't know if you managed to make it work, maybe your app was handle mobile + tablet and now it's only handling mobile.
You can configure it in app.json or app.config.js
```{
  ios: {
      supportsTablet: true,
    }
}
```

**Comment by Lauwed** [comment]
@CharlyPoppins Thank you for your answer. It was the solution for me ! It's working now. I totally forgot to post it here.
It's weird that they put `supportsTablet` to `false` by default... Well wathever.
