### ISSUE TITLE
Make EAS cli auto terminate once build is submitted

### ISSUE THREAD

**Issue by felixlucien** [expo/eas-cli#1240]
### Summary

When submitting a build in non-interactive mode (cloud build CI / CD), the cli tool stays running until the build is complete, these builds can take a while, so is there a parameter to make the build tool auto exit once the build is submitted? The command the cli runs is:

`eas build --auto-submit --non-interactive`

### Managed or bare?

managed

### Environment

`eas build --auto-submit --non-interactive`

### Error output

No error, my cloud builder just times out and I don't want it to be running for the whole build, only the submission.

### Reproducible demo or steps to reproduce from a blank project

Any applicable expo project submitted using a CI CD service such as cloud build.

**Comment by dsokal** [comment]
Just run the build with `--no-wait`:
`eas build --auto-submit --non-interactive --no-wait`

**Comment by felixlucien** [comment]
Cheers!
