### ISSUE TITLE
IOS build failed CocoaPods could not find compatible versions for pod "hermes-engine"

### ISSUE THREAD

**Issue by alzalabany** [expo/eas-cli#1254]
### Build/Submit details page URL

https://expo.dev/accounts/amana.dev/projects/amanaapp/builds/b949346d-bfab-4a5c-ac3f-109d28045664

### Summary

after updating my local version of cocopods build no longer run on EAS, although it runs fine on local machine and i'm able to create .ipa

### Managed or bare?

bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.3.0 - /usr/local/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 30
        System Images: android-30 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      react: 18.0.0 => 18.0.0 
      react-native: 0.69.3 => 0.69.3 
    npmGlobalPackages:
      expo-cli: 5.0.1
    Expo Workflow: bare

### Error output

Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes/hermes-engine.podspec`
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
[!] CocoaPods could not find compatible versions for pod "hermes-engine":
  In snapshot (Podfile.lock):
    hermes-engine (from `../node_modules/react-native/sdks/hermes/hermes-engine.podspec`)
  In Podfile:
    hermes-engine (from `../node_modules/react-native/sdks/hermes/hermes-engine.podspec`)
It seems like you've changed the version of the dependency `hermes-engine` and it differs from the version stored in `Pods/Local Podspecs`.
You should run `pod update hermes-engine --no-repo-update` to apply changes made locally.
Error: Compatible versions of some pods could not be resolved.
You are seeing this error because either:
  - Versions in the Podfile.lock cached by EAS do not match required values in Podspecs of some of the libraries. To fix that add the "cache.key" field (it can be set to any value) in the build profile in eas.json to invalidate the cache.
  - Some of the pods used in your project depend on different versions of the same pod. Please see logs for more info.

### Reproducible demo or steps to reproduce from a blank project

project created with react-native init. follow eas steps.

it was working fine until i updated my Cocopods version.

**Comment by dsokal** [comment]
Hi, could you please follow the instructions from the error output and let me know whether the error goes away?

**Comment by dsokal** [comment]
Closing because of the inactivity.

**Comment by yolpsoftware** [comment]
@dsokal I'm getting this error in a Managed project, in which I cannot run the suggested command, as there is no `ios` directory.

https://expo.dev/accounts/yolpsoftware/projects/cards/builds/9ad8d882-da00-4123-b7b9-91bdfa35bb0e

**Comment by yolpsoftware** [comment]
Was something changed on the EAS build machines? E.g. an update of Cocoapods?
