### ISSUE TITLE
EAS build error when adding dev dependencies

### ISSUE THREAD

**Issue by MicaelRodrigues** [expo/eas-cli#1263]
### Build/Submit details page URL

https://expo.dev/accounts/micaelrodrigues/projects/bug-eas-cli/builds/9259cd38-ac8b-4366-b9ee-8ab3b2591cb5

### Summary

After upgrading to [expo-sdk-46](https://blog.expo.dev/expo-sdk-46-beta-is-now-available-9dfee4040aa7) i can't run `eas` builds. [Local builds](https://docs.expo.dev/build-reference/troubleshooting/#verify-that-your-project-builds-and-runs) work as expected.

By adding an entry (except `@babel/core`) to `devDependencies` and compiling with `eas` on the cloud or locally (`--local` option) produces the error output bellow.

### Managed or bare?

managed

### Environment info
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /usr/local/bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.15.1 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    Expo Workflow: managed
```

### Doctor
```
🎉 Didn't find any issues with the project!
```

## Android
```
[RUN_GRADLEW] Running './gradlew :app:assembleRelease' in /var/folders/sb/705339xs6kg83h_n36j2d4mh0000gn/T/eas-build-local-nodejs/4adeb1c9-d477-48c8-a1b4-3526bb7f3d37/build/android
[RUN_GRADLEW] FAILURE:
[RUN_GRADLEW] Build failed with an exception.
[RUN_GRADLEW] * Where:
[RUN_GRADLEW] Script '/private/var/folders/sb/705339xs6kg83h_n36j2d4mh0000gn/T/eas-build-local-nodejs/4adeb1c9-d477-48c8-a1b4-3526bb7f3d37/build/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 250
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem occurred evaluating script.
[RUN_GRADLEW] > Calling `[node, /private/var/folders/sb/705339xs6kg83h_n36j2d4mh0000gn/T/eas-build-local-nodejs/4adeb1c9-d477-48c8-a1b4-3526bb7f3d37/build/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
[RUN_GRADLEW] The current character read is 'i' with an int value of 105
[RUN_GRADLEW]   Unable to determine the current character, it is not a string, number, array, or object
[RUN_GRADLEW]   line number 1
[RUN_GRADLEW]   index number 0
[RUN_GRADLEW] info Run CLI with --verbose flag for more details.
[RUN_GRADLEW]   ^. Output: info Run CLI with --verbose flag for more details.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 2s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
```

## IOS
```
[INSTALL_PODS] Installing pods
[INSTALL_PODS] Using Expo modules
[INSTALL_PODS] Auto-generating `.xcode.env.local` with $NODE_BINARY=/Users/micael/.nvm/versions/node/v16.16.0/bin/node
[INSTALL_PODS] error Failed to load configuration of your project.
[INSTALL_PODS] [!] Invalid `Podfile` file: 767: unexpected token at 'info Run CLI with --verbose flag for more details.
[INSTALL_PODS] '.
[INSTALL_PODS] 
[INSTALL_PODS]  #  from /private/var/folders/sb/705339xs6kg83h_n36j2d4mh0000gn/T/eas-build-local-nodejs/d80923fb-2d26-41ee-966f-22e87fad0731/build/ios/Podfile:14
[INSTALL_PODS]  #  -------------------------------------------
[INSTALL_PODS]  #    use_expo_modules!
[INSTALL_PODS]  >    config = use_native_modules!
[INSTALL_PODS]  #  
[INSTALL_PODS]  #  -------------------------------------------
[INSTALL_PODS] 
Error: pod exited with non-zero code: 1
```

## Create app and add a dev dependency (e.g `eas-cli` or `yarn-deduplicate`).
```
npx create-expo-app bug-eas-cli

cd bug-eas-cli

expo-cli upgrade

yarn add -D eas-cli
```

### Add dummy `eas.json` , e.g:

```
{
  "build": {
    "base": {
      "developmentClient": false,
      "env": {
        "NODE_ENV": "production"
      },
      "ios": {
        "cocoapods": "1.11.3"
      }
    },
    "development": {
      "distribution": "internal",
      "env": {
        "NODE_CONFIG_ENV": "dev"
      },
      "extends": "base",
      "releaseChannel": "dev"
    }
  },
  "submit": {
    "production": {}
  }
}
```
## Run eas build

`eas build --profile development --platform android --no-wait --local --clear-cache`

**Comment by MicaelRodrigues** [comment]
@dsokal  This is reproducible version of these two:
- https://github.com/expo/eas-cli/issues/1258
- https://github.com/expo/eas-cli/issues/1259

**Comment by dsokal** [comment]
I cannot repro the issue. I followed your repro steps (except for setting `eas.json` - I used the autogenerated one) and everything works fine for me.

**Comment by dsokal** [comment]
It's because you set `NODE_ENV` to `production`. In that case, dev dependencies are not installed. You can test this locally by removing `node_modules` and running `NODE_ENV=production npm install`.
This is not a bug with EAS Build. Local build work for you because you have dev dependencies installed locally.

We even print this warning in EAS CLI:
<img width="1394" alt="Screenshot 2022-08-11 at 15 30 02" src="https://user-images.githubusercontent.com/5256730/184144730-2b8f5b38-ecf2-475c-a9b0-31f37ec8246e.png">

**Comment by MicaelRodrigues** [comment]
> It's because you set `NODE_ENV` to `production`. In that case, dev dependencies are not installed. You can test this locally by removing `node_modules` and running `NODE_ENV=production npm install`. This is not a bug with EAS Build. Local builds work for you because you have dev dependencies installed locally.
> 
> We even print this warning in EAS CLI: <img alt="Screenshot 2022-08-11 at 15 30 02" width="1394" src="https://user-images.githubusercontent.com/5256730/184144730-2b8f5b38-ecf2-475c-a9b0-31f37ec8246e.png">

That the whole point. I don't want `devDependencies` to be installed in a "production like" build.
- https://expo.dev/accounts/seegno-labs/projects/unimoney/builds/47330489-7fbc-4ca2-9448-a43cbac3c9fd

I was working correctly before this version, so it should keep working on this one...

**Comment by dsokal** [comment]
It's not a bug. Development dependencies are necessary for building your bundle. 
It's like if you wanted to have a project in TypeScript but transpile it without installing `typescript` for transpiling. It's just not possible.

**Comment by MicaelRodrigues** [comment]
> It's not a bug. Development dependencies are necessary for building your bundle. It's like if you wanted to have a project in TypeScript but transpile it without installing `typescript` for transpiling. It's just not possible.

Ok. I understand. So what you're are saying is that in the previous versions of `eas` this was not happening?:
- `NODE_ENV=production npm install` (BTW, typescript was never a `devDependency` for us)
I'm asking because `NODE_ENV": "production"` was always set in our deployment configuration (the "base" on the `eas.json` example) and all eas builds worked fine. Now, i can even have `jest` as a devDependency.

**Comment by ShaneBurkhart** [comment]
i have this same issue. my pervious build works just fine. it has NODE_ENV set to production. 

i went to push a new change today. i'm getting this error. we did install new packages (hence the app store deploy) but non are dev dependencies. why would this not work now? 

if we aren't supposed to set NODE_ENV during build time, then how do we get that into our production app? because the app code uses process.env.NODE_ENV conditionals. there have been no problems with it until now.
