### ISSUE TITLE
eas update - Error: Unable to determine runtime version for android

### ISSUE THREAD

**Issue by dimaportenko** [expo/eas-cli#1266]
I've just created a new project with 
```
npx create-expo-app new-expo-app
```

And trying to share the app with Expo Go with the following instructions https://docs.expo.dev/guides/sharing-preview-releases/
on `eas update` run I'm getting 
```
Error: Unable to determine runtime version for android
```

**Comment by dimaportenko** [comment]
thanks @brentvatne, this is missed step I needed.

**Comment by lasharela** [comment]
I was following this instruction: https://docs.expo.dev/eas-update/github-actions/

and I've got this error:

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/2189316/186547460-4060b59f-1383-4be1-889e-eae849bfd608.png">

**Comment by toutpuissantged** [comment]
> hi there! run `eas update:configure` in your app before running `eas update`
> 
> this is not a very good error message though. also, we should change the command so that it runs `eas update:configure` for you automatically if you haven't. i made a couple tasks to follow up on these usability issues internally

Thanks ! Now it worked perfectly

**Comment by geraldcells18** [comment]
@brentvatne Thanks!
