### ISSUE TITLE
EAS build in monorepo failure (/home/expo/.nvm/test/fast/Unit tests/mocks/project_dirs/nested-both/package.json as JSON: Unexpected end of JSON input)

### ISSUE THREAD

**Issue by joseito-terence** [expo/eas-cli#1276]
### Build/Submit details page URL

https://expo.dev/accounts/joseito.terence/projects/solito-blank/builds/99352195-3373-445a-860d-a7fb11058fd4

### Summary

Created a new starter template using create-solito-app and then tried to build the project with eas build but the build has failed. I'm trying this new approach of creating NextJs and Expo apps with shared code, but I'm unable to build the project.
I have run the follow commands.
```
➜  npx create-solito-app@latest my-solito-app
➜  cd apps/expo 
➜  expo eas build --platform android
```

error message 
`Failed to construct transformer:  Error: Cannot parse /home/expo/.nvm/test/fast/Unit tests/mocks/project_dirs/nested-both/package.json as JSON: Unexpected end of JSON input`

### Managed or bare?

Managed

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
      npm: 8.13.2 - ~/.nvm/versions/node/v16.15.1/bin/npm
    npmGlobalPackages:
      eas-cli: 0.59.0
      expo-cli: 5.5.1
    Expo Workflow: managed
```

```
Running "expo doctor"
- Finding all copies of @unimodules/core
- Finding all copies of @unimodules/react-native-adapter
- Finding all copies of react-native-unimodules
[stderr] [15:32:17] Warning: could not reach `expo.io`.
[stderr] [15:32:17] Warning: could not reach `expo.dev`.
[stderr] [15:32:17] Warning: could not reach `static.expo.dev`.
[stderr] [15:32:17] We couldn't reach some of our domains, this might cause issues on our website or services.
[stderr] [15:32:17] Please check your network configuration and try to access these domains in your browser.
[15:32:18] 🎉 Didn't find any issues with the project!
```

### Error output

[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01

[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01

[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01

[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01

[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01

[stderr] Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01

[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01

[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01

[stderr] Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

> Task :app:bundleReleaseJsAndAssets

warning: the transform cache was reset.

                    Welcome to Metro!

              Fast - Scalable - Integrated

[stderr] Failed to construct transformer:  Error: Cannot parse /home/expo/.nvm/test/fast/Unit tests/mocks/project_dirs/nested-both/package.json as JSON: Unexpected end of JSON input

[stderr]     at Object.worker (/home/expo/workingdir/build/node_modules/jest-haste-map/build/worker.js:146:13)

[stderr]     at HasteMap._processFile (/home/expo/workingdir/build/node_modules/jest-haste-map/build/index.js:724:8)

[stderr]     at HasteMap._buildHasteMap (/home/expo/workingdir/build/node_modules/jest-haste-map/build/index.js:776:28)

[stderr]     at /home/expo/workingdir/build/node_modules/jest-haste-map/build/index.js:426:33

[stderr] error Cannot parse /home/expo/.nvm/test/fast/Unit tests/mocks/project_dirs/nested-both/package.json as JSON: Unexpected end of JSON input.

Error: Cannot parse /home/expo/.nvm/test/fast/Unit tests/mocks/project_dirs/nested-both/package.json as JSON: Unexpected end of JSON input

    at Object.worker (/home/expo/workingdir/build/node_modules/jest-haste-map/build/worker.js:146:13)

    at HasteMap._processFile (/home/expo/workingdir/build/node_modules/jest-haste-map/build/index.js:724:8)

    at HasteMap._buildHasteMap (/home/expo/workingdir/build/node_modules/jest-haste-map/build/index.js:776:28)

    at /home/expo/workingdir/build/node_modules/jest-haste-map/build/index.js:426:33

info Run CLI with --verbose flag for more details.

> Task :app:bundleReleaseJsAndAssets FAILED

[stderr] FAILURE: Build failed with an exception.

[stderr] * What went wrong:

[stderr] Execution failed for task ':app:bundleReleaseJsAndAssets'.

[stderr] > Process 'command 'node'' finished with non-zero exit value 1

[stderr] * Try:

[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

[stderr] * Get more help at https://help.gradle.org

[stderr] BUILD FAILED in 3m 8s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

Use '--warning-mode all' to show the individual deprecation warnings.

See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

1 actionable task: 1 executed

### Reproducible demo or steps to reproduce from a blank project

```
➜  npx create-solito-app@latest my-solito-app
➜  cd my-solito-app/apps/expo 
➜  expo eas build --platform android
```

**Comment by dsokal** [comment]
Following your repo steps - I think you've initialized (using `eas build`) the git repository in `my-solito-app/apps/expo`. As a result, only `apps/expo` directory was uploaded to EAS.

The repo should have been initialized in `my-solito-app`. To fix the bug:
- `cd my-solito-app/apps/expo`
- `rm -rf .git`
- `cd ../..`
- `git init` (+ `git add .` + `git commit -m "Initial commit"`)
- `cd apps/expo`
- `eas build -p android`

On our side, I think we should account for cases where someone has a monorepo without git initialized.

**Comment by joseito-terence** [comment]
@dsokal Thank you for the help.
The steps you provided have resolved the issue.

**Comment by pencilcheck** [comment]
I don't have mono repo setup (separate package.json) still get this issue
