### ISSUE TITLE
Cannot build Android app on Windows "no such directory, lstat 'C:\c\..."

### ISSUE THREAD

**Issue by TTFH** [expo/eas-cli#1284]
### Summary

When trying to build an app for Android on Windows I get the error `no such directory, lstat 'C:\c\..`. which obviously doesn't exist, since there is no 'c' folder inside C:\\  
EAS CLI is trying using the Linux path /c/... on Windows.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 7 6.1.7601
    Binaries:
      Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.0
      expo: latest => 46.0.2
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: ^0.69.4 => 0.69.4
      react-native-web: latest => 0.18.7
    Expo Workflow: managed

× Dependency tree validation for expo-modules-autolinking failed. This validation is only available on Node 16+ / npm 8.
× Dependency tree validation for @expo/config-plugins failed. This validation is only available on Node 16+ / npm 8.
× Dependency tree validation for @expo/prebuild-config failed. This validation is only available on Node 16+ / npm 8.
× Dependency tree validation for @unimodules/core failed. This validation is only available on Node 16+ / npm 8.
× Dependency tree validation for @unimodules/react-native-adapter failed. This validation is only available on Node 16+ / npm 8.
× Dependency tree validation for react-native-unimodules failed. This validation is only available on Node 16+ / npm 8.
🎉 Didn't find any issues with the project!

### Error output

PS E:\ReactNative\app> eas build -p android
✔ Linked to project @ttfh/**** (https://expo.dev/accounts/ttfh/projects/****)
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials **** (default)

Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive
    Error: ENOENT: no such file or directory, lstat 'E:\e\ReactNative\app'
    Code: ENOENT

### Reproducible demo or steps to reproduce from a blank project

Execute `eas build -p android` on Windows

**Comment by TTFH** [comment]
It works on Linux, but I don't want to copy my project to a different computer every time I need to make a new build

**Comment by dsokal** [comment]
It works for me on Windows:
<img width="1217" alt="Screenshot 2022-08-18 at 16 39 50" src="https://user-images.githubusercontent.com/5256730/185422973-223a4d74-6b42-4087-814d-95cc8b0dbe38.png">

Can you please tell me a little more about your setup? Can you share `eas.json`?

**Comment by TTFH** [comment]
eas.json
```json
{
	"cli": {
		"version": ">= 0.60.0"
	},
	"build": {
		"development": {
			"android": {
				"buildType": "apk"
			}
		},
		"preview": {},
		"production": {}
	},
	"submit": {
		"production": {}
	}
}
```
Build command:
`eas build -p android --profile development`

It works fine on Linux, but on Windows it's seems it's not detecting the operative system correctly and appending the drive letter at the beginning of the path.

**Comment by TTFH** [comment]
@dsokal I found the problem.
I'm using eas version: `eas-cli/0.60.0 win32-x64 node-v14.16.1`

The program crash on build.js:110
`const projectTarball = await (0, repository_1.makeProjectTarballAsync)();`
It calls repository.js:80
`await (0, vcs_1.getVcsClient)().makeShallowCopyAsync(shallowClonePath);`
That calls local.js:73
`async function makeShallowCopyAsync(src, dst) {`
In this function src has the value:
src = "\e\ReactNative\app";
instead of:
src = "E:\\ReactNative\\app";
Not sure where the value comes from or why it's wrong
