### ISSUE TITLE
EAS build does not support numeric separators

### ISSUE THREAD

**Issue by alamothe** [expo/eas-cli#1291]
### Build/Submit details page URL

https://expo.dev/accounts/carsync/projects/carsync/builds/98eb4210-7197-495a-88d7-bbfd46f6a929

### Summary

TypeScript 2.7 brought support for numeric separators as outlined in the [Numeric Separators](https://github.com/tc39/proposal-numeric-separator) ECMAScript proposal (Stage 4) in 2018. Within a numeric literal, you can now group digits by putting an underscore as a separator character between them:
```tsx
const worldPopulationIn2017 = 7_600_000_000;
const leastSignificantByteMask = 0b1111_1111;
const papayawhipColorHexCode = 0xff_ef_d5;
```

Weirdly, this is not supported in EAS build in 2022. 

Error is:
```
Error: Unexpected token name «_000», expected punc «,» in file src/main/XYZ.tsx at 319:16
    at minifyCode (/Users/expo/workingdir/build/client-web/node_modules/metro-transform-worker/src/index.js:101:13)
    at transformJS (/Users/expo/workingdir/build/client-web/node_modules/metro-transform-worker/src/index.js:319:28)
    at transformJSWithBabel (/Users/expo/workingdir/build/client-web/node_modules/metro-transform-worker/src/index.js:410:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.transform (/Users/expo/workingdir/build/client-web/node_modules/metro-transform-worker/src/index.js:571:12)
```

We didn't have this problem in managed Expo Go workflow.

### Managed or bare?

Managed

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /opt/homebrew/opt/node@16/bin/node
      Yarn: 3.2.2 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - /opt/homebrew/opt/node@16/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0 
      expo: ^45.0.8 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.5
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

- Start from a TypeScript template
- Use a number literal with a separator e.g. `1_000_000`

**Comment by alamothe** [comment]
Not sure what's happening, I can see that numeric separators are es2021, and our `tsconfig.json` says:
```
    "target": "es2019",
```
but why it's not transpiled?

**Comment by alamothe** [comment]
I was able to fix it with:
```
"plugins": ["@babel/plugin-proposal-numeric-separator"]
```
in `babel.config.js`. However, very weird that this was not necessary so far, we have been developing in Expo for ages and only now switched to EAS.

**Comment by dsokal** [comment]
It doesn't seem to be a problem with EAS Build. EAS Build doesn't have `typescript` preinstalled/preconfigured. The only `typescript` configuration there could be is the one from your project. 
Unfortunately, I have to close the issue because I cannot repro the issue with your repro steps.

**Comment by alamothe** [comment]
@dsokal The issue is not with TypeScript but general with JavaScript numeric separators. But I suppose React Native does not make a promise to support them, even though they work without issues in Expo Go. We only found out about it when we switched to EAS.

**Comment by dsokal** [comment]
I can look into this but only if I have valid repro steps. From the build logs you shared, I see that you're on Node.js 16.13.2.

Numeric separators are supported for that version:
<img width="367" alt="Screenshot 2022-08-23 at 09 42 34" src="https://user-images.githubusercontent.com/5256730/186100761-2e49607d-1a75-4d64-9574-d2a56fe2c833.png">

**Comment by alamothe** [comment]
1.
```
npx create-react-native-app -t with-typescript
expo install expo-dev-client
```

2. Add `const x = 1_000` in `App.tsx`

3. eas build -p ios --profile preview

**Comment by dsokal** [comment]
These are not valid repro steps. There are definitely some missing steps. Sorry to say but I'm 100% sure this is an issue with your configuration. 
EAS Build uses a Node.js version that supports numeric separators. As I said before, EAS Build doesn't have "its own" Typescript installed / preconfigured. That means if the project is not buildable locally then it won't build on EAS Build.
