### ISSUE TITLE
Failed to upload assets: ValidationError: "fileMetadata.web" is not allowed

### ISSUE THREAD

**Issue by camnpr** [expo/eas-cli#1293]
### Summary

development complete, and run is worked.
my update is sucess before.
next:
step one:`eas update:configure`
step two: `eas update`

...
✔ Built bundle!
✖ Failed to upload assets
    ValidationError: "fileMetadata.web" is not allowed
...

Maybe is my network question?

### Managed or bare?

bare

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.17134
    Binaries:
      Node: 14.17.0 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.13 - ~\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.0.0.0 AI-171.4408382
    npmPackages:
      @expo/webpack-config: 0.17.2 => 0.17.2
      expo: ~46.0.8 => 46.0.8
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
      react-native-web: 0.18.7 => 0.18.7
    Expo Workflow: bare

### Error output

...
✔ Built bundle!
✖ Failed to upload assets
    ValidationError: "fileMetadata.web" is not allowed
...

### Reproducible demo or steps to reproduce from a blank project

step one: `eas update:configure`
step two: `eas update`

**Comment by mackenziekira** [comment]
we ran into this recently and resolved it by upgrading the global version of eas cli: `npm install -g eas-cli`
