### ISSUE TITLE
error: emit-module command failed with exit code 1 when building a simulator build.

### ISSUE THREAD

**Issue by a-eid** [expo/eas-cli#1299]
### Build/Submit details page URL

https://expo.dev/accounts/zeal-pay/projects/zeal-brgr/builds/5abb0988-ffa7-4d25-885e-94976cbd181e

### Summary

when building a simulator build `ios.simulator: true` 

I get the following error 

```
[RUN_FASTLANE] › Packaging Pods/CocoaAsyncSocket » libCocoaAsyncSocket.a
[RUN_FASTLANE]
❌  error: emit-module command failed with exit code 1 (use -v to see invocation)


[RUN_FASTLANE]
❌  (../../node_modules/react-native-paymob/ios/Paymob.swift:3:8)

  1 | import Foundation
  2 | import UIKit
> 3 | import AcceptSDK
    |        ^ no such module 'AcceptSDK'
  4 |
  5 | @objc(Paymob)
  6 | class Paymob: RCTEventEmitter, AcceptSDKDelegate {

[RUN_FASTLANE] › Compiling react-native-paymob Pods/react-native-paymob » Paymob.swift
[RUN_FASTLANE]
❌  (../../node_modules/react-native-paymob/ios/Paymob.swift:3:8)

  1 | import Foundation
  2 | import UIKit
> 3 | import AcceptSDK
    |        ^ no such module 'AcceptSDK'
  4 |
  5 | @objc(Paymob)
  6 | class Paymob: RCTEventEmitter, AcceptSDKDelegate {

[RUN_FASTLANE]
❌  error: emit-module command failed with exit code 1 (use -v to see invocation)


[RUN_FASTLANE] › Compiling react-native-paymob Pods/react-native-paymob » Paymob.swift
[RUN_FASTLANE]
❌  (../../node_modules/react-native-paymob/ios/Paymob.swift:3:8)

  1 | import Foundation
  2 | import UIKit
> 3 | import AcceptSDK
    |        ^ no such module 'AcceptSDK'
  4 |
  5 | @objc(Paymob)
  6 | class Paymob: RCTEventEmitter, AcceptSDKDelegate {

[RUN_FASTLANE]
❌  (../../node_modules/react-native-paymob/ios/Paymob.swift:3:8)

  1 | import Foundation
  2 | import UIKit
> 3 | import AcceptSDK
    |        ^ no such module 'AcceptSDK'
  4 |
  5 | @objc(Paymob)
  6 | class Paymob: RCTEventEmitter, AcceptSDKDelegate {

```

this happens only when `ios.simulator: true` I tried to reproduce without it but it worked fine.

### Managed or bare?

both

### Environment

```

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.n/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 8.3.1 - ~/.n/bin/npm
      Watchman: 4.9.0 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 29, 30, 31
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-31 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8092744
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      react-dom: 18.0.0 => 18.0.0
    npmGlobalPackages:
      eas-cli: 1.0.0
      expo-cli: 6.0.5
    Expo Workflow: managed

```

```
🎉 Didn't find any issues with the project!
```

### Error output

```

[RUN_FASTLANE] › Packaging Pods/CocoaAsyncSocket » libCocoaAsyncSocket.a
[RUN_FASTLANE]
❌  error: emit-module command failed with exit code 1 (use -v to see invocation)


[RUN_FASTLANE]
❌  (../../node_modules/react-native-paymob/ios/Paymob.swift:3:8)

  1 | import Foundation
  2 | import UIKit
> 3 | import AcceptSDK
    |        ^ no such module 'AcceptSDK'
  4 |
  5 | @objc(Paymob)
  6 | class Paymob: RCTEventEmitter, AcceptSDKDelegate {

[RUN_FASTLANE] › Compiling react-native-paymob Pods/react-native-paymob » Paymob.swift
[RUN_FASTLANE]
❌  (../../node_modules/react-native-paymob/ios/Paymob.swift:3:8)

  1 | import Foundation
  2 | import UIKit
> 3 | import AcceptSDK
    |        ^ no such module 'AcceptSDK'
  4 |
  5 | @objc(Paymob)
  6 | class Paymob: RCTEventEmitter, AcceptSDKDelegate {

[RUN_FASTLANE]
❌  error: emit-module command failed with exit code 1 (use -v to see invocation)


[RUN_FASTLANE] › Compiling react-native-paymob Pods/react-native-paymob » Paymob.swift
[RUN_FASTLANE]
❌  (../../node_modules/react-native-paymob/ios/Paymob.swift:3:8)

  1 | import Foundation
  2 | import UIKit
> 3 | import AcceptSDK
    |        ^ no such module 'AcceptSDK'
  4 |
  5 | @objc(Paymob)
  6 | class Paymob: RCTEventEmitter, AcceptSDKDelegate {

[RUN_FASTLANE]
❌  (../../node_modules/react-native-paymob/ios/Paymob.swift:3:8)

  1 | import Foundation
  2 | import UIKit
> 3 | import AcceptSDK
    |        ^ no such module 'AcceptSDK'
  4 |
  5 | @objc(Paymob)
  6 | class Paymob: RCTEventEmitter, AcceptSDKDelegate {
  ```

### Reproducible demo or steps to reproduce from a blank project

- start a new expo project 
- install [my custom package](https://github.com/zeal-io/react-native-paymob)
- yarn add `react-native-paymob`
- build a simulator build with eas  locally or remotely.

**Comment by dsokal** [comment]
- Sorry, but it doesn't seem to be a problem with EAS Build. 
- From looking at the logs you provided it seems to be a problem with `react-native-paymob`. Expo doesn't maintain this package.
- If there is a project that you can't build locally, e.g. with Xcode, then it's also not buildable on EAS Build.

**Comment by a-eid** [comment]
@dsokal thanks for the response, it seemed weird because the app builds just fine with xCode, and eas if and only if it's not a simulator build.

**Comment by dsokal** [comment]
Can you try building locally with Xcode but choosing the target to simulator?

**Comment by a-eid** [comment]
![Screen Shot 2022-08-23 at 11 23 50](https://user-images.githubusercontent.com/19273413/186122583-6e19acd1-a62d-4e83-9b65-d51ca3b38eb7.png)

building the app with  xcode on simulator works fine 

steps I took
- expo prebuild -p ios
- cd id; pod install
- xed . 
- change target to `IPhone13` 
- build app 

everything worked just fine

**Comment by a-eid** [comment]
@dsokal it's probably worth noting that I've had issues with building when package like `react-native-blurhash` / `react-native-intercom` are present, removing them solved the issue.

**Comment by a-eid** [comment]
@dsokal I'm wondering if you could provide any insights as to what this issue could be, I've spent a lot of time trying to fix it but am not able to.

cc @tsapeta

**Comment by a-eid** [comment]
`expo run:ios` seem to be working fine as well.

**Comment by a-eid** [comment]
@dsokal @tsapeta is there any way to simulate this command with xCode, I couldn't reproduce the error there.

**Comment by a-eid** [comment]
@dsokal is there a way to build a dev client with xcode after prebuild with expo ?

just trying to reproduce the issue.

**Comment by wkozyra95** [comment]
Hi @a-eid 

I reproduced your issue and it looks like the issue is not related to EAS. When you are building in Xcode by default it's creating debug simulator build, but on EAS default it Release configuration.

When I was building in xcode, simulator build with Debug configuration worked for me, but Release failed with the same error as on EAS. I did not test that yet, but if you set your `buildConfiguration: Debug` in eas.json your simulator build should work the same way as in xcode.

**Comment by wkozyra95** [comment]
>  I did not test that yet, but if you set your buildConfiguration: Debug in eas.json your simulator build should work the same way as in xcode.

It looks like I was wrong, Debug simulator build also fails on EAS, but you can still look into the root cause of why Release simulator builds do not work, it's likely the same problem.

**Comment by a-eid** [comment]
`buildConfiguration: Debug` seems to be failing for me, I'll retry with a fresh expo project.

**Comment by a-eid** [comment]
> but you can still look into the root cause of why Release simulator builds do not work, it's likely the same problem.

will do, thank you @wkozyra95

**Comment by wkozyra95** [comment]
When building for a simulator, the destination is set to `generic/platform=iOS Simulator` which requires building for x86_64 and arm64, but when you build in xcode you are selecting a specific simulator which always is x86_64.

The root cause of the problem is that AcceptCardSDK provides only x86_64 binaries for simulator builds and there is no fallback to build from the source.

**Comment by a-eid** [comment]
@wkozyra95 that clarifies the issue, would be nice if there was an EAS option for that.
