### ISSUE TITLE
EAS Build not using local credentials.json or credentials.config.js

### ISSUE THREAD

**Issue by martin-braun** [expo/eas-cli#1308]
### Summary

On my new project I run `eas build --platform android --local` with this eas.json:

```json
{
  "cli": {
    "version": ">= 1.0.0"
  },
  "build": {
    "android": {
      "credentialsSource": "local"
    },
    "ios": {
      "credentialsSource": "local"
    },
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
```

and this credentials.json:

```json
{
  "android": {
    "keystore": {
      "keystorePath": "signing/androidKeystore.jks",
      "keystorePassword": "p$ssw0rd",
      "keyAlias": "main",
      "keyPassword": "p$ssw0rd"
    }
  },
  "ios": {
    "provisioningProfilePath": "signing/iosProfile.mobileprovision",
    "distributionCertificate": {
      "path": "signing/iosDistribution.p12",
      "password": "p$ssw0rd"
    }
  }
}
```

But the output is: 

```
✔ Using remote Android credentials (Expo server)
```

The project is new and does not exist on Expo.dev.

### Managed or bare?

Bare

### Environment

```
WARNING: expo-cli has not yet been tested against Node.js v18.7.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

Expected package expo-modules-autolinking@~0.10.1
Found invalid:
  expo-modules-autolinking@0.8.1
  (for more info, run: npm why expo-modules-autolinking)
Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@^5.0.1
Found invalid:
  @expo/prebuild-config@4.0.3
  (for more info, run: npm why @expo/prebuild-config)
```

Things I will work on ..

### Reproducible demo or steps to reproduce from a blank project

```sh
npx create-expo-app my-app
cd my-app
npm i eas-cli -D
# now creating eas.json / credentials.json as shown above
mkdir signing
keytool -genkey -keyalg RSA -deststoretype pkcs12 -keysize 4096 -validity 365000 -dname “C=US” -keystore signing/androidKeystore.jks -alias main -storepass 'p$ssw0rd' -keypass 'p$ssw0rd'
npx eas build --platform android --local
```

### Final notes

I would welcome to load the credentials dynamically using a `credentials.config.js`. Is this already possible? It's not documented. Anyways, neither method work.

**Comment by brentvatne** [comment]
we do not support credentials.config.js, you can accomplish this by just writing a script to swap out credentials.json prior to running eas build.

your eas.json configuration won't actually set the local credentials source - you have created build profiles name "ios" and "android" - those are meant to be nested properties under profile names. i can see why you did this though, the docs were incorrect for this, so i have updated the docs in this commit: https://github.com/expo/expo/commit/7a5e1c9fe284393cf31fb8c288d29c34e6829292

see your fixed eas.json below:

```json
{
  "cli": {
    "version": ">= 1.0.0"
  },
  "build": {
    "base": {
      "credentialsSource": "local"
    },
    "development": { 
      "extends": "base",
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "extends": "base",
      "distribution": "internal"
    },
    "production": {
       "extends": "base"
     }
  },
  "submit": {
    "production": {}
  }
}
```

**Comment by martin-braun** [comment]
@brentvatne Thank you, now I get it. Yes, I think the docs are confusing, especially because it involves things like `amazon` and `google` without explaining the whole concept. Or maybe I just missed it.

So in general. `build` can contain predefined profiles (`development`, `production`, `preview`)  and own profiles. I can extend from other profiles using `extends` and I can even further specify different configurations using different platform sub profiles (`android`, `ios`).

It's now printing `✔ Using local Android credentials`. Thank you!
