### ISSUE TITLE
Project with path ':expo-modules-core' could not be found in project ':expo'

### ISSUE THREAD

**Issue by tomlinder** [expo/eas-cli#1311]
### Build/Submit details page URL

https://expo.dev/accounts/francesco9820/projects/dummytestdeploy/builds/992e22e5-86d8-4404-b25a-401356f330f7

### Summary

We are a small team of developers located in Sweden and we are trying to develop a mobile application with Expo. However, we are encountering a problem when we try to deploy the app using the command: “eas build -p android --profile preview", since we get the error:
 
Project with path ':expo-modules-core' could not be found in project ':expo'
 
The thing is that we are able to deploy the app if we use the command "expo build:android -t apk” and we cannot understand reasons behind this. Could you please help us?

### Managed or bare?

Managed

### Environment

Finding all copies of @unimodules/core
- Finding all copies of @unimodules/react-native-adapter
- Finding all copies of react-native-unimodules
[14:17:28] Some dependencies are incompatible with the installed expo package version:
[14:17:28]  - @react-native-async-storage/async-storage - expected version: ~1.15.0 - actual version installed: 1.17.9
[14:17:28]  - expo-constants - expected version: ~13.0.1 - actual version installed: 13.2.4
[14:17:28]  - expo-file-system - expected version: ~13.1.4 - actual version installed: 14.1.0
[14:17:28]  - expo-font - expected version: ~10.0.4 - actual version installed: 10.2.0
[14:17:28]  - expo-image-picker - expected version: ~12.0.1 - actual version installed: 13.3.1
[14:17:28]  - expo-modules-core - expected version: ~0.6.4 - actual version installed: 0.11.4
[14:17:28]  - expo-updates - expected version: ~0.11.7 - actual version installed: 0.14.5
[14:17:28]  - lottie-react-native - expected version: 5.0.1 - actual version installed: 5.1.3
[14:17:28]  - react-native-safe-area-context - expected version: 3.3.2 - actual version installed: 4.3.1
[14:17:28]  - react-native-screens - expected version: ~3.10.1 - actual version installed: 3.15.0
[14:17:28]  - react-native-svg - expected version: 12.1.1 - actual version installed: 12.3.0
[14:17:28] Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo doctor --fix-dependencies,
or install individual packages by running expo install [package-name ...]
[14:17:31] Warning: Invalid version react-native@0.69.4 for expo sdkVersion 44.0.0. Use react-native@0.64.3

### Error output

Project with path ':expo-modules-core' could not be found in project ':expo'

### Reproducible demo or steps to reproduce from a blank project

Gradle code

**Comment by wkozyra95** [comment]
As you can see in the `expo doctor` output you posted you are using incompatible versions of packages. Fix the issue listed there.

To install correct versions of those packages run `expo doctor --fix-dependencies`

**Comment by tomlinder** [comment]
We have run it many times but we are still getting the problems

From: Wojciech Kozyra ***@***.***>
Reply to: expo/eas-cli ***@***.***>
Date: Wednesday, 24 August 2022 at 14:31
To: expo/eas-cli ***@***.***>
Cc: tomlinder ***@***.***>, Author ***@***.***>
Subject: Re: [expo/eas-cli] Project with path ':expo-modules-core' could not be found in project ':expo' (Issue #1311)


As you can see in the expo doctor output you posted you are using incompatible versions of packages. Fix the issue listed there.

To install correct versions of those packages run expo doctor --fix-dependencies

**Comment by wkozyra95** [comment]
> We have run it many times but we are still getting the problems

That sounds unlikely, I'm not saying that `expo doctor --fix-dependencies` will fix all the issues, but you shouldn't get those warnings about incompatible packages.

If you think `expo doctor` does not update your packages correctly, please provide the output of the command and diff of the changes that it made

**Comment by BFMarks** [comment]
+1 to this `Expo doctor` says: 

`🎉 Didn't find any issues with the project!`

Gradle Logs say:
`> Project with path ':expo-modules-core' could not be found in project ':react-native-reanimated'.`

**Comment by danielcunhas** [comment]
I have the same problem in my project after upgrading to RN 0.70
Did anyone manage to solve it?

**Comment by tomlinder** [comment]
Sorry for the answer of before.
First of all thanks for your message, but we run expo doctor –fix-dependencies many times and we are still encountering the problem. Do you have in mind an alternative solution?
Many thanks,

Tom

From: Tom Linder ***@***.***>
Date: Wednesday, 24 August 2022 at 14:39
To: expo/eas-cli ***@***.***>, expo/eas-cli ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [expo/eas-cli] Project with path ':expo-modules-core' could not be found in project ':expo' (Issue #1311)

We have run it many times but we are still getting the problems

From: Wojciech Kozyra ***@***.***>
Reply to: expo/eas-cli ***@***.***>
Date: Wednesday, 24 August 2022 at 14:31
To: expo/eas-cli ***@***.***>
Cc: tomlinder ***@***.***>, Author ***@***.***>
Subject: Re: [expo/eas-cli] Project with path ':expo-modules-core' could not be found in project ':expo' (Issue #1311)


As you can see in the expo doctor output you posted you are using incompatible versions of packages. Fix the issue listed there.

To install correct versions of those packages run expo doctor --fix-dependencies

**Comment by nurikon** [comment]
I also faced the same problem. is there any solution this issue.

**Comment by oliviercperrier** [comment]
Samething here, doctor say everything is good, but i get `Project with path ':expo-modules-core' could not be found in project ':expo'`

**Comment by next6leo** [comment]
bump

**Comment by SiddhiBlackLotus** [comment]
any solution for this issue ?

**Comment by Desintegrator** [comment]
same

**Comment by SunZhiC** [comment]
any workaround for this issue?

**Comment by LuisEB** [comment]
Having this same issue, anyone has manage to solve it?

**Comment by kevilondo** [comment]
> Having this same issue, anyone has manage to solve it?

Have you solved this issue? @LuisEB ??

**Comment by kevilondo** [comment]
> any solution for this issue ?

Have you solved it? @SiddhiBlackLotus @SunZhiC  ?

**Comment by jbar173** [comment]
I'm having the same issue, can't find any solutions for it!

**Comment by amn-max** [comment]
Try `npm uninstall expo`

**Comment by thanhdat2106** [comment]
Project with path ':expo-modules-core' could not be found in project ':expo'.

**Comment by thanhdat2106** [comment]
I am having the same problem with expo sdk46 using eas build

**Comment by 2MO5** [comment]
SDK 47 is as well suffering the same fate!

**Comment by calcooke** [comment]
I'm also having the same issue - "project with path ':expo-modules-core' could not be found in project ':expo'."

**Comment by 2MO5** [comment]
What could be the issue here guys?

A problem with the linking?

**Comment by tolypash** [comment]
Just created a fresh expo module and I get the same issue.

**Comment by rootsquid** [comment]
Same here , also with expo 
doctor & expo doctor --fix-dependencies 
outputs:
🎉 Didn't find any issues with the project!

**Comment by BeatrizLopes97** [comment]
I am also having this issue with expo module: "Unable to resolve module expo". It started after I upgraded to Expo SDK 48.

**Comment by ribeiro240** [comment]
Having the same issue after upgrading to SDK 48. Any updates?

**Comment by 54m1r** [comment]
I'm having the same issue with SDK 48. Does anyone know how to fix this?

**Comment by chrishoermann** [comment]
same here - none of the above mentioned fixes helped

**Comment by ATSudoDev** [comment]
I have the same issue.

**Comment by MohammadKurjieh** [comment]
Any updates on this issue?

**Comment by korg1OOO** [comment]
Same issue here

**Comment by serolgames** [comment]
Hello ! I solved it, add this line in android/settings.gradle : include ':expo-modules-core'

**Comment by IZZAGOLD** [comment]
> Hello ! I solved it, add this line in android/settings.gradle : include ':expo-modules-core'

thx bro

**Comment by ml242** [comment]
> Hello ! I solved it, add this line in android/settings.gradle : include ':expo-modules-core'

Where can I find this file? Ty

**Comment by htmlin** [comment]
I have solved the problem.

Environment info:
pnpm: 9.8.0
expo: 51.0.38

I found that after installing the dependencies with `pnpm i`, the directory `expo-modules-core` was missing under `node_modules/expo/node_modules`. I checked the `node_modules/expo/package.json` file, and it indeed declares `expo-modules-core` as a dependency. So, I copied it into my own package.json:

```json
"expo-modules-core": "1.12.26"
```

Then, I ran pnpm i again, and added these two lines at the end of the `android/settings.gradle` file generated by Expo:

```
include ':expo-modules-core'
project(':expo-modules-core').projectDir = new File(rootProject.projectDir, '../node_modules/expo-modules-core/android')
```

After that, everything worked fine.

**Comment by PranjalBandwal** [comment]
> Hello ! I solved it, add this line in android/settings.gradle : include ':expo-modules-core'

worked for me, but now facing another issue related to expo-modules-cre.


<img width="1695" height="263" alt="Image" src="https://github.com/user-attachments/assets/ba2ef726-5756-4da1-b0a1-4c43ba7de3b5" />
