### ISSUE TITLE
eas device:rename

### ISSUE THREAD

**Issue by ZEAL-MATCH-LTD** [expo/eas-cli#1314]
### Do you understand that any feature requests opened in this repository will be closed?

Yes

Device management is difficult by default let alone when you have 50+ un-named devices. 
At the moment it seems the only way to "name" a device is during `eas device:create` when you are given the option to manually input the devices UDID and then subsequently given the option to name it. 

It would be great if you could rename a device that has been registered via the `url` option during `eas device:create` 

### Proposition
```bash
$ eas device:rename [UDID]
$ Name: _
$ Device renamed ✅
$ # output eas device:view [UDID] here #
```

**Comment by brentvatne** [comment]
created a task for this internally, it's a good idea :)
