### ISSUE TITLE
Generating (or quering) provisioning profile returns wrong result in some cases

### ISSUE THREAD

**Issue by wkozyra95** [expo/eas-cli#132]
Mostly copied from slack and grouped together

Steps I took to verify that issue is contained to appstore api implementation
- I verified that `listProvisioningProfilesAsync` was called with `org.reactjs.native.example.testapp.turt`
- I verified that `createProvisioningProfilesAsync` was called with `org.reactjs.native.example.testapp.turt` , it's called only when you select explicitly to create new profile and after doing that next call to `listProvisioningProfilesAsync`  returns one more profile, if I'm only reusing profile new profile is not added to the list
 - All profiles returned by this method have status set to 'INVALID'
 - it works correctly if i change to some totally random bundleidentifier
 - it does not work if I use similar bundleIdentifier (e.g org.reactjs.native.example.testapp.tu ), but on the other hand there are profiles on this account that should also be matching in the same way but are not returned by listProvisioningProfilesAsync  (e.g. org.reactjs.native.example.testapp.turtaawedawed)

Changes after fix https://github.com/expo/eas-cli/pull/127
- listProvisioningProfilesAsync did not return any results during first build (correct behavior)
- generation of new profile finished with success (correct behavior), but we don't validate stuff returned by apple api, so we don't know if it was correct
- listProvisioningProfilesAsync did not return any results during second build (incorrect behavior) - should return provisioning profile created during first build

@EvanBacon I saw failed build on your account, it was for adhoc builds, but error was the same as I'm getting, so you are probably hitting the same problem.
If it's the same issue you can verify that by running `Ensure all credentials for project are valid` twice, if during second run it will warn you about invalid profile that means you are hitting that case.

**Comment by EvanBacon** [comment]
On main (without this update https://github.com/expo/eas-cli/pull/127), I'm getting the following:

- `eas.json` - default
- Fresh `ios.bundleIdentifier`, `android.package`, and `slug` (reran `expo eject`) (basically it's a new, project)
- Added the following to [`provisioningProfile.ts` at this line](https://github.com/expo/eas-cli/blob/38a0ef8b1ed553419de5e033dbb52f9005e5e9a7/packages/eas-cli/src/credentials/ios/appstore/provisioningProfile.ts#L146) `console.log('listProvisioningProfilesAsync: ', profileType, profiles);`
- `eas build -p ios` 

**First run**

```
listProvisioningProfilesAsync:  IOS_APP_STORE []
```

**Second run**

```
listProvisioningProfilesAsync:  IOS_APP_STORE [
  Profile {
    context: { providerId: 118573547, teamId: 'QQ57RJ5UTD' },
    id: '8P872ZYQ95',
    attributes: {
      profileState: 'INVALID',
      configuration: 'N/A',
      uuid: 'XX-6484-40c8-b1c5-ff4645e11c96',
      platform: 'IOS',
      bundlePlatform: 'IOS',
      createdDate: null,
      profileType: 'IOS_APP_STORE',
      templateName: null,
      name: '*[expo] com.bacon.test.ejbtest10 AppStore 2020-12-08T20:58:33.712Z',
      profileTypeLabel: 'App Store',
      profileContent: 'BIGLONG=',
      platformName: 'iOS',
      responseId: 'XX-4474-476d-9e9c-d1de6c7bbb6b',
      expirationDate: '2021-12-08T20:48:23.000+0000'
    }
  }
]
```

**Comment by wkozyra95** [comment]
Based on this output I'm guessing that you are able to reproduce the problem
- newly created profile is invalid `profileState: 'INVALID',`
- can't see that but I'm guessing that if you decode value that was in place of `BIGLONG=` it might have wrong bundle identifier

On What account did you run those builds? I see only adhoc builds here https://expo.io/accounts/bacon/builds ? Did the second run fail?

I debugged it a bit more and found that in my case `BundleId.findAsync` return multiple results, but current implementation supports only one. I added filter there
```
diff --git a/packages/app-store/src/connect/models/BundleId.ts b/packages/app-store/src/connect/models/BundleId.ts
index 2c85b86..6ae4827 100644
--- a/packages/app-store/src/connect/models/BundleId.ts
+++ b/packages/app-store/src/connect/models/BundleId.ts
@@ -79,9 +79,13 @@ export class BundleId extends ConnectModel<BundleIdProps> {
       identifier: string;
     }
   ): Promise<BundleId | null> {
-    const [bundleId] = await BundleId.getAsync(context, {
+   const r = await BundleId.getAsync(context, {
       query: { filter: { identifier } },
     });
+   console.log(r.filter(bundleId => bundleId.attributes.identifier === identifier));
+   const [bundleId] = r.filter(bundleId => bundleId.attributes.identifier === identifier);
     return bundleId ?? null;
   }
```
after that new profile is still marked as invalid but it contains correct bundle identifier

**Comment by wkozyra95** [comment]
If I'm wrong about the example you gave and that `INVALID` status is unrelated and you are unable to reproduce that issue, then please try using an example I gave in the original post. bundleIdentifier: `org.reactjs.native.example.testapp.turt` on `turtle-dev` apple account. I sent you info on how to access that account on slack

**Comment by dsokal** [comment]
It seems this is not an issue now.
