### ISSUE TITLE
CocoaPods could not find compatible versions for pod "hermes-engine"

### ISSUE THREAD

**Issue by yolpsoftware** [expo/eas-cli#1320]
### Build/Submit details page URL

https://expo.dev/accounts/yolpsoftware/projects/cards/builds/0341216c-01ef-4f73-94f6-945ebdf958d9

### Summary

Since today, my Managed project does not build anymore on EAS build, although it runs fine on my local machine.

The project is managed, so I don't have an `ios` folder and no `Podfile`. Thus I cannot do what the error message suggests.

### Managed or bare?

managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.7.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.15.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.8 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 0.60.0
      expo-cli: 6.0.5
    Expo Workflow: managed

expo doctor
Didn't find any issues with the project!

### Error output

Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes/hermes-engine.podspec`
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
[!] CocoaPods could not find compatible versions for pod "hermes-engine":
  In snapshot (Podfile.lock):
    hermes-engine (from `../node_modules/react-native/sdks/hermes/hermes-engine.podspec`)
  In Podfile:
    hermes-engine (from `../node_modules/react-native/sdks/hermes/hermes-engine.podspec`)
It seems like you've changed the version of the dependency `hermes-engine` and it differs from the version stored in `Pods/Local Podspecs`.
You should run `pod update hermes-engine --no-repo-update` to apply changes made locally.
Error: Compatible versions of some pods could not be resolved.
You are seeing this error because either:
  - Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that add the "cache.key" field (it can be set to any value) in the build profile in eas.json to invalidate the cache.
  - Some of your npm packages have native code that depend on different versions of the same pod. See logs for more information.

### Reproducible demo or steps to reproduce from a blank project

https://expo.dev/accounts/yolpsoftware/projects/cards/builds/4bf47ead-f05b-49b7-a342-2b5f74a496cd

Please see also [here](https://github.com/expo/eas-cli/issues/1254).

**Comment by dsokal** [comment]
Have you by any chance upgraded Expo to a new version?

Follow the instructions from the error message and the error should go away:

> Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that add the "cache.key" field (it can be set to any value) in the build profile in eas.json to invalidate the cache.

eas.json:
```
{
  "build": {
    "production": {
      "cache": {
        "key": "whatever" // <- set this
      }
    }
}
```

**Comment by mariomurrent-softwaresolutions** [comment]
> Have you by any chance upgraded Expo to a new version?
> 
> Follow the instructions from the error message and the error should go away:
> 
> > Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that add the "cache.key" field (it can be set to any value) in the build profile in eas.json to invalidate the cache.
> 
> eas.json:
> 
> ```
> {
>   "build": {
>     "production": {
>       "cache": {
>         "key": "whatever" // <- set this
>       }
>     }
> }
> ```

Awesome, that did the trick in combination with eas-cli and expo upgrade to the newest versions

**Comment by yolpsoftware** [comment]
Thanks @dsokal this did it indeed.

Strange thing is, after I upgraded to Expo 46, one build ran fine. It was a few days later it stopped working.
