### ISSUE TITLE
Invalid prov. profile for internal distribution

### ISSUE THREAD

**Issue by dsokal** [expo/eas-cli#133]
There's an issue with regenerating the provisioning profile when building an app for internal distribution (I haven't verified it's broken for app store builds too). The provisioning profile is generated for a different distribution certificate than the chosen one.

Repo steps:
- use the `turtle-dev` apple id and the `Alicja Warchał` team
- log in to eas-cli as `expo-turtle` (ask me for the password)
- init a new app and add this to app.json:
  ```
    "android": {
      "package": "com.expo.turtle.tutorial.internal.abc"
    },
    "ios": {
      "bundleIdentifier": "com.expo.turtle.tutorial.internal.abc"
    }
  ```
- run `eas build:configure` and complete all steps
- edit `eas-cli/packages/eas-cli/src/build/create.ts`to add `process.exit(1);` on line 20 to not spam turtle with test builds
  <img width="812" alt="Screenshot 2020-12-08 at 19 01 01" src="https://user-images.githubusercontent.com/5256730/101522583-b978c500-3987-11eb-9b63-50129e76b7cc.png">
- go to Apple Dev Portal and revoke the iOS dist cert with the expiry on 2021/12/08 (don't revoke the one with the expiry on 2021/11/09 - it will break turtle v1 smoke tests)
   <img width="1233" alt="Screenshot 2020-12-08 at 19 04 27" src="https://user-images.githubusercontent.com/5256730/101523105-6d7a5000-3988-11eb-8b75-f1e7b719599e.png">
- create eas.json:
   ```
   {
    "builds": {
      "android": {
        "release": {
          "workflow": "generic"
        }
      },
      "ios": {
        "release": {
          "workflow": "generic",
          "distribution": "internal"
        }
      }
    } 
  }
   ```
- run `eas build -p ios` and follow all the steps, EAS CLI will regenerate the profile
- go to [Apple Dev Portal](https://developer.apple.com/account/resources/certificates/list) and see that the new profile was generated for the wrong dist cert (for the one with the expiry on 2020/11/09) - even though a new one was created
  <img width="563" alt="Screenshot 2020-12-08 at 19 10 46" src="https://user-images.githubusercontent.com/5256730/101523596-1923a000-3989-11eb-90c8-5b0ffbd52f67.png">

**Comment by EvanBacon** [comment]
The post request is in line with what you've described, meaning it's not a bug in `apple-utils`'s `Profile.createAsync` method.
```
⠋ Handling Apple ad hoc provisioning profiles
- 201 Created (POST https://developer.apple.com/services-account/v1/profiles)
```

Here is the request (notice [`4L484Q4H26`](https://developer.apple.com/account/resources/certificates/download/4L484Q4H26) is the Nov 09 certificate)
```diff
{
	"data": {
		"attributes": {
			"name": "*[expo] com.expo.turtle.tutorial.internal.abc AdHoc 1607456400273",
			"profileType": "IOS_APP_ADHOC",
			"teamId": "QL76XYH73P"
		},
		"type": "profiles",
		"relationships": {
			"bundleId": {
				"data": {
					"type": "bundleIds",
					"id": "DJD4D2R9FX"
				}
			},
			"certificates": {
				"data": [{
					"type": "certificates",
+					"id": "4L484Q4H26"
				}]
			},
			"devices": {
				"data": [{
					"type": "devices",
					"id": "3XK2WJ89C8"
				}, {
					"type": "devices",
					"id": "8CX2CBVQYJ"
				}, {
					"type": "devices",
					"id": "Z2HPCVR6Q9"
				}]
			}
		}
	}
}
```

**Comment by EvanBacon** [comment]
Can confirm that `getDistributionCertificateAync` works as expected too (get expected (newly generated) certificate with serial number). 
Essentially apple-utils is returning the correct certificate, and it's getting passed the wrong certificate. So nothing seems wrong on the apple-utils side. 

This leaves `createOrReuseAdhocProvisioningProfileAsync` as the most suspect method.

<img width="395" alt="Screen Shot 2020-12-08 at 12 07 19 PM" src="https://user-images.githubusercontent.com/9664363/101535740-f627ca80-394d-11eb-99f0-bf4f3d519ec1.png">

**Comment by dsokal** [comment]
This is still broken for me
