### ISSUE TITLE
Needing to create new dev builds after adding new dependencies

### ISSUE THREAD

**Issue by michaelshum** [expo/eas-cli#1343]
### Summary

When installing multiple packages (`react-native-animated` and `@react-navigation/material-top-tabs`), I've run into errors when using the dev client. This happens both in my development builds as well as preview builds. For these two packages, I've done the following:

```
react-native-reanimated
1. expo install react-native-reanimated
2. Added plugins: ['react-native-reanimated/plugin'] to my babel.config.js
3. expo start --dev-client --clear
4. get error: [TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')](https://stackoverflow.com/questions/63190006/typeerror-null-is-not-an-object-evaluating-reanimatedmodule-default-createno)
```

```
@react-navigation/material-top-tabs
1. yarn add @react-navigation/material-top-tabs react-native-tab-view
2. npx expo install react-native-pager-view
3. expo start --dev-client --clear
4. get error: Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.
```

I saw for material-top-tabs someone else has also run into the same issue (https://github.com/react-navigation/react-navigation/issues/10124).

In both cases, my issue was resolved by uninstalling my current build, creating a new development build, and installing that build. However, my understanding is that with EAS I shouldn't need to create new builds unless I'm updating native code. Is there something I'm missing, or is this EAS missing a link somehow?

### Managed or bare?

managed

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.5.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.18.0 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/user/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
      Android SDK:
        API Levels: 22, 23, 25, 26, 27
        Build Tools: 23.0.1, 25.0.2, 26.0.1, 27.0.1
        System Images: a...gle_apis | Google APIs Intel x86 Atom_64 ...
    IDEs:
      Android Studio: 2.3 AI-162.4069837
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.9
    npmGlobalPackages:
      expo-cli: 6.0.5
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

N/A as the issue is in the development client

**Comment by JamesIde** [comment]
Not sure why the incomplete issue label was added here. Its a valid question, one that I'm also finding annoying. Having to create new development builds each time a package is installed (that doesn't interact with any native code) costs money, which quickly adds up. So if there's a way without having to do this, which @michaelshum is asking, an answer would be appreciated (despite this being over a year old)

**Comment by janwirth** [comment]
I think this is because you are using the simulator build, not expo-go.

**Comment by astronomyf** [comment]
Having the same problem here using the reanimated library (Expo SDK48). 

My understanding is that there shouldn’t be a need to make a new dev build unless the library updates native code. Couldn’t find any mention of this in the library documentation. Am I missing something too?

**Comment by jameszhan02** [comment]
> Having the same problem here using the reanimated library (Expo SDK48).
> 
> My understanding is that there shouldn’t be a need to make a new dev build unless the library updates native code. Couldn’t find any mention of this in the library documentation. Am I missing something too?

I found the similar question here, my guess is expoGo have include some popular libs which include some native code? since most of lib need to do pod install etc. , but when you go for dev-client is only included all minimum changes you made( the libs you install in the project ) while you compile the project.

**Comment by jameszhan02** [comment]
> Not sure why the incomplete issue label was added here. Its a valid question, one that I'm also finding annoying. Having to create new development builds each time a package is installed (that doesn't interact with any native code) costs money, which quickly adds up. So if there's a way without having to do this, which @michaelshum is asking, an answer would be appreciated (despite this being over a year old)

No clue if there is a solution for this problem, however about the eas build adds up your bill, you could add --local flag for android to get apk and install in your device for dev purpose, and for ios you could install your build with xcode. so in both way is not going to make you pay more money on this.

**Comment by paulshaun-kdtk** [comment]
So there still isn't any solution to this?
