### ISSUE TITLE
IOS build failed with latest version of eas-cli

### ISSUE THREAD

**Issue by Profi-web** [expo/eas-cli#1347]
### Summary

after updating npm, expo and eas making the build for IOS it keeps giving me "Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
    CombinedError: [GraphQL] Entity not authorized: AccountEntity[c8c830e2-c703-435f-b893-a4bd4ac91805] (viewer =
    UserViewerContext[56d8550c-32df-454f-b441-6779f25f55d1], action = READ, ruleIndex = -1)" as an output.

### Managed or bare?

Managed

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 2.15.12 - ~\node_modules\.bin\npm.CMD
    IDEs:
      Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    npmPackages:
      expo: ^46.0.0 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: 0.18.9 => 0.18.9
    Expo Workflow: managed

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with expo-cli on Windows. You may encounter issues using cmd.exe.

🎉 Didn't find any issues with the project!

### Reproducible demo or steps to reproduce from a blank project

install latest versions of:
- npm
- expo
- eas

after that make a new expo project and run "eas build --platform ios" for the just made project.

**Comment by dsokal** [comment]
Duplicated issue: https://github.com/expo/eas-cli/issues/1324
