### ISSUE TITLE
[tvOS] eas-cli build doesn't create a proper Provisioning Profile for tvOS

### ISSUE THREAD

**Issue by danychi** [expo/eas-cli#1349]
I was trying to generate a tvOS build using `eas-cli build --platform="ios"` and the process was returning this kind of error:
```
 error: No profile for team 'TEAM' matching '*[expo] bundle.id AppStore 2022-08-25T15:51:50.365Z' found: Xcode couldn't find any provisioning profiles matching 'TEAM/*[expo] bundle.id AppStore 2022-08-25T15:51:50.365Z'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor. (in target 'TARGET-tvOS' from project 'TARGET')
``` 
The reason is that by default eas creates an `App Store` provisioning profile type, while the project needs a `tvOS App Store` provisioning profile type. 

<img width="1063" alt="Screenshot 2022-09-08 at 14 13 56" src="https://user-images.githubusercontent.com/45874461/189119640-fed2d7c3-dfd9-4353-8af7-7986693495a0.png">

So after creating the provisioning profile on https://developer.apple.com/account/resources/profiles/list
and uploading it to https://expo.dev/accounts/TEAM/projects/PROJECT_NAME/credentials then everything works perfectly 👌

**Comment by quinlanj** [comment]
@danychi just to sanity check since tvOS support was added not too long ago:
- what version of `eas-cli` do you have? 
- did you ever run `eas build` for your tvOS project on a cli version earlier than 2.1.0?

**Comment by quinlanj** [comment]
Closing this issue for now. @danychi if you run into the same problem again, please open up another issue and:
- reference this issue
- let us know what version of `eas-cli` you are running
- let us know what changes you've made in your project to build for tvOS (configuration changes, XCode build settings, etc)
