### ISSUE TITLE
Error: EACCES: permission denied, scandir      '/Users/mikechambers/Library/Saved Application      State/com.bitrock.appinstaller.savedState'     Code: EACCES

### ISSUE THREAD

**Issue by mikeRChambers610** [expo/eas-cli#1359]
### Build/Submit details page URL

N/A

### Summary

I upgraded to Expo 45 and now when I go to use eas build -p ios --auto-submit and the CLI throws this error:

Error: EACCES: permission denied, scandir 
    '/Users/mikechambers/Library/Saved Application 
    State/com.bitrock.appinstaller.savedState'
    Code: EACCES

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      npm: 8.19.2 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.1.84 => 0.1.84 
      babel-preset-expo: 8.3.0 => 9.0.2 
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
      react-navigation: 4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

Expected package @expo/config-plugins@^4.1.0
Found invalid:
  @expo/config-plugins@3.1.0
  @expo/config-plugins@5.0.1
  @expo/config-plugins@5.0.1
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@^4.0.0
Found invalid:
  @expo/prebuild-config@5.0.3
  (for more info, run: npm why @expo/prebuild-config)

### Error output
Error: EACCES: permission denied, scandir 
    '/Users/mikechambers/Library/Saved Application 
    State/com.bitrock.appinstaller.savedState'
    Code: EACCES

### Reproducible demo or steps to reproduce from a blank project

Upgrade to Expo 45, reinstall node modules, run eas build -p ios --auto-submit.

**Comment by mikeRChambers610** [comment]
After downloading the zip from github and installing node modules and expo-cli and eas-cli I was still getting this error.

Solution: Create a fresh expo project and then copy my folder inside of the new app. Now I am not having this issue. Thanks again!

**Comment by pong7772** [comment]
Move the project directory: If none of the above solutions work, you can try moving your project directory to a different location that does not have permission issues. For example, you can move your project to a directory within your home directory.

**Comment by pong7772** [comment]
> Move the project directory: If none of the above solutions work, you can try moving your project directory to a different location that does not have permission issues. For example, you can move your project to a directory within your home directory.

i've done this and it work for me

**Comment by gdomenech98** [comment]
> > Move the project directory: If none of the above solutions work, you can try moving your project directory to a different location that does not have permission issues. For example, you can move your project to a directory within your home directory.
> 
> i've done this and it work for me



> Move the project directory: If none of the above solutions work, you can try moving your project directory to a different location that does not have permission issues. For example, you can move your project to a directory within your home directory.

Just "git init" in your expo project folder. This fixed the issue for me. Hope you found this helpful 👯
