### ISSUE TITLE
EAS does not create a push key in apple developer

### ISSUE THREAD

**Issue by ItsCrotix** [expo/eas-cli#1362]
### Summary

When initializing a managed expo project, and publishing it with eas build, when you create a push key, this wil generate, but not show up within the keys of apple developer account.

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30, 31, 32
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-28 | Google APIs Intel x86 Atom_64, android-Tiramisu | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    npmPackages:
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

1. Create a sample project.
2. Configure apple dev login within EAS.
3. run EAS build --platform ios
4. Select generate key

**Comment by wkozyra95** [comment]
Where on the apple developer portal are you checking that? If you are part of multiple teams, make sure you are checking on the correct one.
