### ISSUE TITLE
react-native-maps 'RCTConvert+AirMap.h' file not found on 0.31.3

### ISSUE THREAD

**Issue by borademiral** [expo/eas-cli#1375]
### Build/Submit details page URL

https://expo.dev/accounts/egecavusoglu/projects/Chember/builds/72d0f5c6-65be-41a7-8703-5f43d264821c

### Summary

I upgraded to SDK 46 and thus, upgraded react-native-maps to the recommended version. However, eas build fails on managed workflow at the run fastlane step with the error seen below.

<img width="758" alt="Screen Shot 2022-09-18 at 2 42 48 PM" src="https://user-images.githubusercontent.com/67051670/190929175-a78a2353-6cea-458c-83ee-da8eaa5377a9.png">

### Managed or bare?

Managed

### **npx expo-env-info**

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0
      expo: ^46.0.10 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
    Expo Workflow: managed
    
###   **expo doctor**
🎉 Didn't find any issues with the project!

### Error output

❌  (node_modules/react-native-maps/ios/AirGoogleMaps/AIRGoogleMapPolylineManager.m:17:9)

  15 | #import <React/RCTViewManager.h>
  16 | #import <React/UIView+React.h>
 17 | #import "RCTConvert+AirMap.h"
     |         ^ 'RCTConvert+AirMap.h' file not found
  18 | #import "AIRGoogleMapPolyline.h"
  19 | 
  20 | @interface AIRGoogleMapPolylineManager()
 Compiling react-native-maps Pods/react-native-google-maps » AIRGoogleMapPolyline.m

### Reproducible demo or steps to reproduce from a blank project

Set up a new managed expo project -> npx expo install react-native-maps -> eas build

**Comment by wkozyra95** [comment]
It does not look like it's an issue with EAS. If you think the problem is expo specific please open an issue in https://github.com/expo/expo and if it's not specific to expo you should report it in react-native-maps repo.
