### ISSUE TITLE
EAS iOS build failing at Fastlane XType: unable to make a connection to the font daemon! - XTFontStaticRegistry is enabled as fontd is not available

### ISSUE THREAD

**Issue by oualidmaz** [expo/eas-cli#1378]
### Build/Submit details page URL

https://expo.dev/accounts/waheb/projects/mizen-app/builds/042d353d-efa4-4cd5-bec5-3a7417aeaeab

### Summary

trying to build the app but it fails at Fastlan step with the errors bellow : 

failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}
▸ 2022-09-19 16:24:13.224 xcodebuild[4410:13297] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
▸ 2022-09-19 16:24:13.224 xcodebuild[4410:13297] XType: unable to make a connection to the font daemon!
▸ 2022-09-19 16:24:13.224 xcodebuild[4410:13297] XType: XTFontStaticRegistry is enabled as fontd is not available.

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8309675
    npmPackages:
      babel-preset-expo: ~9.1.0 => 9.1.0
      expo: ^45.0.0 => 45.0.4
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    Expo Workflow: managed

--------- -----------------------

 Found all copies of expo-modules-autolinking
Expected package expo-modules-autolinking@~0.8.1 || ~0.9.0
Found invalid:
  expo-modules-autolinking@0.7.1
  (for more info, run: npm why expo-modules-autolinking)
√ Found all copies of @expo/config-plugins
Expected package @expo/config-plugins@^4.1.0
Found invalid:
  @expo/config-plugins@5.0.1
  @expo/config-plugins@5.0.0
  @expo/config-plugins@5.0.1
  (for more info, run: npm why @expo/config-plugins)
√ Found all copies of @expo/prebuild-config
Expected package @expo/prebuild-config@^4.0.0
Found invalid:
  @expo/prebuild-config@5.0.3
  (for more info, run: npm why @expo/prebuild-config)

Some dependencies are incompatible with the installed expo package version:
 - expo-notifications - expected version: ~0.15.4 - actual version installed: 0.15.2
 - expo-updates - expected version: ~0.13.4 - actual version installed: 0.13.1
 - expo-web-browser - expected version: ~10.2.1 - actual version installed: 10.2.0
 - lottie-react-native - expected version: 5.0.1 - actual version installed: 5.1.3
Your project may not work correctly until you install the correct versions of the packages.

### Error output

 xcodebuild -resolvePackageDependencies -workspace ./Mizen.xcworkspace -scheme Mizen -configuration Release
▸ 2022-09-19 16:24:13.146 xcodebuild[4410:13297] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
▸ 2022-09-19 16:24:13.147 xcodebuild[4410:13297] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
▸ 2022-09-19 16:24:13.224 xcodebuild[4410:13297] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}

### Reproducible demo or steps to reproduce from a blank project

eas build --profile production --platform ios

**Comment by jacobhummel** [comment]
I believe we have the same issue: https://expo.dev/accounts/reveltransit/projects/driver/builds/967dbd1f-223c-4a8c-9c39-e4d2cdd63b96

**Comment by wkozyra95** [comment]
@oualidmaz error output you posted should not cause any issues with the build. No idea what could be the problem, xcode logs just stop without any error. I would suggest starting with fixing incompatible libs that expo doctor reports.

@jacobhummel It looks like there is an issue building flipper. Unless you have a reason to believe this is sth specific to EAS Build, you will probably open an issue in the repo of the config-plugin you are using. Also, you are trying to add flipper to the release build, is this even supported?

**Comment by oualidmaz** [comment]
thanks @wkozyra95 . I fix all incompatible libs that expo doctor reports. However the build still fails 

------  Expo doctor logs : ----------

Running "expo doctor"
- Finding all copies of expo-modules-autolinking
- Finding all copies of @expo/config-plugins
- Finding all copies of @expo/prebuild-config
- Finding all copies of @unimodules/core
- Finding all copies of @unimodules/react-native-adapter
- Finding all copies of react-native-unimodules
[05:27:13] 🎉 Didn't find any issues with the project!

Build url : 
https://expo.dev/accounts/waheb/projects/mizen-app/builds/1a723a20-9be7-45f7-9354-6fbb7bc5f6e8

**Comment by jacobhummel** [comment]
@wkozyra95, thanks for the info. Disabling flipper by setting `"FLIPPER_DISABLE": "1"` fixed my build failure. https://expo.dev/accounts/reveltransit/projects/driver/builds/ed4dd0f0-a188-4b0b-a6c4-482d76874595

@oualidmaz I also noticed that we see the same error you posted on all of our builds, even successful ones. It didn't actually end up determining whether our build fails or passes. Not sure what we can do to resolve that error message, or if it's something with EAS / Apple.

**Comment by oualidmaz** [comment]
For me it was **Hermes engine**. switch back to JSC and now the build works fine.

**Comment by dsokal** [comment]
Are you still seeing this issue?

**Comment by oualidmaz** [comment]
> Are you still seeing this issue?

Not anymore ... after changing the engine to JSC

**Comment by gretzky** [comment]
Still seeing this issue with the hermes engine -- switching it to JSC does fix it, but it would be nice to be able to use hermes.

```
▸ ** ARCHIVE FAILED **

▸ The following build commands failed:

▸ 	PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/expo/Library/Developer/Xcode/DerivedData/GoingPreview-asuaksfjacriknapsbxedpseavrg/Build/Intermediates.noindex/ArchiveIntermediates/GoingPreview/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-46EB2E00028F10.sh (in target 'EXUpdates' from project 'Pods')

▸ (1 failure)

2022-10-12 04:50:04.568 xcodebuild[4737:15129] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore

2022-10-12 04:50:04.569 xcodebuild[4737:15129] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore

2022-10-12 04:50:04.638 xcodebuild[4737:15129] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}

2022-10-12 04:50:04.638 xcodebuild[4737:15129] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts

2022-10-12 04:50:04.638 xcodebuild[4737:15129] XType: unable to make a connection to the font daemon!

2022-10-12 04:50:04.638 xcodebuild[4737:15129] XType: XTFontStaticRegistry is enabled as fontd is not available.

** ARCHIVE FAILED **
```

**Comment by wkozyra95** [comment]
Originally issue was a problematic case because there were no errors, logs were just cut off, we will probably look into that more, but we didn't see any other reports of that happening. 
Building with hermes on iOS seems not to be related to EAS, so I recommend opening an issue in expo/expo repo, unless there is a specific reason to believe it sth EAS related. Closing issue for now.

**Comment by osilkin98** [comment]
I'm currently running into the same exact issue where my `fastlane` job is failing due to being unable to communicate with XType. I don't have an entry defined for `Expo.jsEngine` in my `app.json`.

**Comment by kennethlynne** [comment]
I stopped seeing this issue after changing the folder name of the app (in a monorepo) so it did not longer contain a space... 
"Example App" -> "Example_App". Was fun digging while it lasted.

**Comment by Joshandrews43** [comment]
Experiencing this issue with no spaces in any folder names nor `jsEngine` defined
