### ISSUE TITLE
Wrong MAX_VERSION_CODE for android

### ISSUE THREAD

**Issue by aeife** [expo/eas-cli#1393]
### Summary

Maximum versionCode for android (MAX_VERSION_CODE) is set to 2000000000 but according to official Google Documentation the actual maximum is 2100000000.

### Managed or bare?

both

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 6.14.16 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~9.2.0 => 9.2.0 
      expo: ^46.0.0 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

### Error output

AssertionError: Invalid versionCode 2006081651
    Code: ERR_ASSERTION

### Reproducible demo or steps to reproduce from a blank project

1. set versionCode for android in app.json to 2000000001
2. enable autoIncrement for android to eas.json
3. run eas build

**Comment by aeife** [comment]
You might wonder why it might be important to raise max versionCode here. When we initially started we encoded the current date in version code as we did not know better and it worked fine for iOS. Knowing the limitations at one point we started incrementing it only for android but as you can not lower versionCode we are now stuck with a version code higher than 2000000000 but lower than 2100000000.

**Comment by wkozyra95** [comment]
Will be fixed in the next release.
