### ISSUE TITLE
Setting up EAS local builds

### ISSUE THREAD

**Issue by barndoor101** [expo/eas-cli#1396]
Hi all,

I'm trying to setup EAS to build locally on an Azure pipeline (we're rewriting our app in RN that's currently in NativeScript), but I'm having trouble setting up EAS on Azure, so wondered if anyone could tell me what I'm doing wrong?

I have eas.json setup as:
`
{
    "build": {
      "development": {
        "developmentClient": true,
        "distribution": "internal",
        "credentialsSource": "local"
      },
      "preview": {
        "distribution": "internal",
        "credentialsSource": "local"
      },
      "production": {}
    }
  }
`

credentials.json:

`
{
    "android": {
      "keystore": {
        "keystorePath": "$(androidKeyStore.secureFilePath)",
        "keystorePassword": "$(androidKeyStorePassword)",
        "keyAlias": "tempreupgrade",
        "keyPassword": "$(androidKeyStorePassword)"
      }
    },
    "ios": {
      "provisioningProfilePath": "$(devProvisioningProfile)",
      "distributionCertificate": {
        "path": "$(p12DevFileName)",
        "password": "$(p12DevPassword)"
      }
    }
  }
`

In Azure I'm just doing:
 - script: |
    eas build --profile development --platform all --non-interactive --no-wait
  displayName: Build

But I get the error "Error: Generating a new Keystore is not supported in --non-interactive mode" which indicates the creds ive specified arent being used.

Any help would be much appreciated! Many thanks

**Comment by wkozyra95** [comment]
Are you sure you are using this exact command? It seems that you did not set credentialsSource for the production build profile. Are you sure you ar e building with `--profile development`?

Please provide full cli output
