### ISSUE TITLE
java.io.IoException: Manifest string is not a valid JSONObject or JSONArray: OK

### ISSUE THREAD

**Issue by stephenson080** [expo/eas-cli#1398]
### Build/Submit details page URL

https://expo.dev/accounts/stevepath/projects/blockplot-mobile/builds/dd3ad4bb-eb76-4b5c-98c6-06d96818bd27

### Summary

after running eas build, the build is completed but the standalone app keeps stopping in my device. i ran the codebase with npx expo start --no-dev minify, works perfectly. when i run the standalone app on expo go it shows the error java.io.IoException: Manifest string is not a valid JSONObject or JSONArray: OK

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 8.1 6.3.9600
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.14.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.7042882
    npmPackages:
      expo: ~46.0.9 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: managed

expo doctor output

🎉 Didn't find any issues with the project!

### Reproducible demo or steps to reproduce from a blank project

there is nothing wrong with my codebase. I actually created a new expo without inputting any code and built it with eas build and it is still showing same error

**Comment by bernborgess** [comment]
I am experiencing the same error, when running ```eas build -p android --profile preview``` where preview targets apk on a managed clean app right from tabs template. Apparently no app I try this command is avoiding the issue.

**Comment by stephenson080** [comment]
I actually solved the error

**Comment by stephenson080** [comment]
@bernborgess I don't understand. Is your  android APK not working?

**Comment by BernardoBorgesIjunior** [comment]
> I actually solved the error

What step did you take to solve it? I am having the same problem even on a new app.

**Comment by bernborgess** [comment]
I get this exact error when I try to run the apk. It just crashes on start

**Comment by stephenson080** [comment]
![Screenshot_20221018-213504_1.jpg](https://user-images.githubusercontent.com/65906366/196541416-5ea3464b-8e1c-47ff-b95b-5c6a365e12c8.jpg)

Wrap your app with SafeAreaProvider from react-native-safe-area-view. Call the registerRootComponent method with your App component

**Comment by stephenson080** [comment]
![Screenshot_20221018-213538_1.jpg](https://user-images.githubusercontent.com/65906366/196542347-cf60a4b0-d413-46b6-90dd-39c9862fb264.jpg)

Then change your main script in your package.json file to your root component
