### ISSUE TITLE
EAS build fails when there is a git submodule and requireCommit in eas.json is true

### ISSUE THREAD

**Issue by obayit** [expo/eas-cli#1399]
### Build/Submit details page URL

https://expo.dev/accounts/etherservices/projects/etherservices/builds/dc172b87-123c-45aa-9b71-211b44716fb2

### Summary

I have a project with a git submodule for common code, it is in the `src/common` directory.
When `requireCommit` in `eas.json` is set to `true` the build failed, I tried at least two times. And after setting it to `false` the build succeeded as normal.
I think there is a bug preventing the upload of the git submodule code to eas servers. The error messages says:
```
[stderr] error Unable to resolve module ./src/common/providers/APIErrorProvider from /home/expo/workingdir/build/App.js: 
[stderr] None of these files exist:
[stderr]   * src/common/providers/APIErrorProvider(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
[stderr]   * src/common/providers/APIErrorProvider/index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
[stderr]    8 | // import { StatusBar } from './src/components/status-bar.component';  for some reason this breaks the app
[stderr]    9 | import { Provider } from 'react-redux'
[stderr] > 10 | import APIErrorProvider from './src/common/providers/APIErrorProvider';
[stderr]      |                               ^
[stderr]   11 | import { PersistGate } from 'redux-persist/integration/react';
[stderr]   12 | import configureStore from './src/native-common/storage/configureStore';
[stderr]   13 | import { useFonts, TitilliumWeb_200ExtraLight, TitilliumWeb_300Light, TitilliumWeb_400Regular, TitilliumWeb_700Bold } from '@expo-google-fonts/titillium-web';.

```

The module which it can't resolve is inside the common git submodule.

### Managed or bare?

managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.15.0 - /usr/local/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.5.5 - /usr/local/bin/npm
    npmPackages:
      @expo/webpack-config: ~0.16.21 => 0.16.27 
      expo: ^45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed

Expo doctor:
Warning: could not reach `expo.io`.

We couldn't reach some of our domains, this might cause issues on our website or services.
Please check your network configuration and try to access these domains in your browser.

🎉 Didn't find any issues with the project!

### Reproducible demo or steps to reproduce from a blank project

Create a git submodule inside the source of a new project
use a class/method from that submoudle in the App.js

try to build with this in the `eas.json`:
```
  "cli": {
    "version": ">= 0.50.0",
    "requireCommit": false
  }

```

**Comment by wkozyra95** [comment]
This is expected behavior, submodules should not be included in the bundle, if you want to use submodules you need to initialize submodules on the eas worker.

We are using setup like that to build Expo GO on EAS Build.
https://github.com/expo/expo/blob/main/apps/eas-expo-go/scripts/eas-build-pre-install.sh

If your submodules are in private repos you will also need to setup ssh key
https://docs.expo.dev/build-reference/how-tos/#how-to-use-git-submodules
