### ISSUE TITLE
Android: EAS Build fails due to Internal Server Error

### ISSUE THREAD

**Issue by lkalashov** [expo/eas-cli#1410]
### Build/Submit details page URL

https://expo.dev/accounts/narrativ/projects/howl-native/builds/7788132a-c750-42c9-92de-60438b9c24f0

### Summary

We are deploying our application to Play Store using EAS.
Since 27.09.2022 all builds for Android platform are failing without error. Gradlew process runs as expected but then is interrupted on different steps, and following message is displayed.

![изображение](https://user-images.githubusercontent.com/102518316/192761426-6c5ff0e3-f50b-481c-b40f-9ddd227e0566.png)

Running local build with ```eas build --platform android --local``` works as expected and results into 
```
Build successful
You can find the build artifacts in /Users/.../build-1664297219232.aab
```

### Managed or bare?

Bare

### Environment

```
expo-env-info 1.0.5 environment info:
  System:
   OS: macOS 12.3.1
   Shell: 5.8 - /bin/zsh
  Binaries:
   Node: 14.19.1 - /opt/i386_homebrew/opt/nvm/versions/node/v14.19.1/bin/node
   Yarn: 1.22.18 - /opt/i386_homebrew/bin/yarn
   npm: 6.14.3 - /opt/i386_homebrew/bin/npm
  Managers:
   CocoaPods: 1.11.3 - /opt/i386_homebrew/bin/pod
  SDKs:
   iOS SDK:
    Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
  IDEs:
   Android Studio: 2021.1 AI-211.7628.21.2111.8309675
   Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  npmPackages:
   @expo/metro-config: =0.3.12 => 0.3.12
   expo: =44.0.6 => 44.0.6
   metro: =0.67.0 => 0.67.0
   react: =17.0.2 => 17.0.2
   react-dom: =17.0.2 => 17.0.2
   react-native: =0.64.3 => 0.64.3
   react-native-web: =0.17.7 => 0.17.7
  Expo Workflow: bare
  ```

### Error output

```
Build failed: Internal Server Error.  
Try again later. If the problem persists, report the issue.
```

### Reproducible demo or steps to reproduce from a blank project

```eas build --platform android```

**Comment by wkozyra95** [comment]
From our perspective workers with your builds are just dropping the connection to the service. I suspect the server running on the worker is killed by the OOM killer.

Can you try building with  `--resource-class large` (queue time might be longer there)?
Also in the past, ubuntu 22.04 had some issues with too aggressive memory killer, so you might also try downgrading to ubuntu 20.04. https://docs.expo.dev/build-reference/infrastructure/#image--ubuntu-2004-jdk-11-ndk-r21e--alias--default

**Comment by cyclops23** [comment]
We see the same here - https://expo.dev/accounts/robinator/projects/Friday/builds/b1d8a015-b88f-4f3b-80b9-a76bb0225e70

**Comment by b4lk0n** [comment]
thanks @wkozyra95 - `---resource-large large` solves the issue

**Comment by AyoCodess** [comment]
> thanks @wkozyra95 - `---resource-large large` solves the issue

how do i set this flag in my eas.json?

**Comment by AyoCodess** [comment]
> From our perspective workers with your builds are just dropping the connection to the service. I suspect the server running on the worker is killed by the OOM killer.
> 
> Can you try building with `--resource-class large` (queue time might be longer there)? Also in the past, ubuntu 22.04 had some issues with too aggressive memory killer, so you might also try downgrading to ubuntu 20.04. https://docs.expo.dev/build-reference/infrastructure/#image--ubuntu-2004-jdk-11-ndk-r21e--alias--default

how do i set `--resource-class large` flag in my eas.json?

**Comment by b4lk0n** [comment]
@AyoCodess have you seen https://docs.expo.dev/build-reference/eas-json/?

**Comment by johnrevs** [comment]
the issue is still on, to use large resourceClass you need to go to the paid plan, is this right?
