### ISSUE TITLE
eas update - requires app restart for changes to take effect

### ISSUE THREAD

**Issue by sabarishml** [expo/eas-cli#1412]
### Summary

Noticed EAS update roll outs requires the app to be restarted atleast couple times even for fresh new installs. This doesn't seem to be acceptable. Any recommendations how to resolve this?

### Managed or bare?

Bare

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.5 => 0.69.5 
      react-native-web: ~0.18.7 => 0.18.9 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 0.60.0
      expo-cli: 6.0.2
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Needs a demo project to be prepared and build pushed to test flight or App Store. Otherwise please let me know the best way to reproduce.

**Comment by wkozyra95** [comment]
You can adjust this behavior with
- https://docs.expo.dev/versions/latest/config/app/#checkautomatically (it's by default checking on every start)
- https://docs.expo.dev/versions/latest/config/app/#fallbacktocachetimeout if you set it to a higher value it will wait for update download longer. If value is large enough only one restart will be necessary, but it might be bad experience if user has a slow internet connection.

Alternatively, you can use js API to download updates.
