### ISSUE TITLE
Expo-firebase-core 5.2.0 failure

### ISSUE THREAD

**Issue by iM-GeeKy** [expo/eas-cli#1419]
### Build/Submit details page URL

https://expo.dev/accounts/bluebirding/projects/bluebird-client/builds/44eff806-5c59-4c62-a4d5-ef4694717857

### Summary

As it currently stands, Expo expects `expo-firebase-core` version `~5.2.0`, but when running the command `eas build --profile preview --platform ios --clear-cache` results in an internal failure. However, using the previous expected version of `5.1.1` and running the command results in a success.

Note: Using the expected version of `~5.2.0` via `expo start` works with no issues.

Failing Build: https://expo.dev/accounts/bluebirding/projects/bluebird-client/builds/44eff806-5c59-4c62-a4d5-ef4694717857
Successful Build: https://expo.dev/accounts/bluebirding/projects/bluebird-client/builds/bb2f99d4-2b5e-4b43-b966-7e1626170c01

### Managed or bare?

Managed

### Environment

```expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.13 => 46.0.13 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.9 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.1.0
      expo-cli: 6.0.5
    Expo Workflow: managed
```

```
Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)
```

### Error output

```
[!] The following Swift pods cannot yet be integrated as static libraries:
The Swift pod `FirebaseCoreInternal` depends upon `GoogleUtilities`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

### Reproducible demo or steps to reproduce from a blank project

This should be reproducible via the steps below, but this behavior is currently being exhibiting in a private repository)
1. `npx create-expo-app my-app`
2. `npx expo install expo-firebase-core`
3. `eas build --profile preview --platform ios --clear-cache`

**Comment by wkozyra95** [comment]
You are missing config-plugin https://docs.expo.dev/versions/v46.0.0/sdk/firebase-recaptcha/#additional-configuration-for-ios
