### ISSUE TITLE
Eas build crashes after app install

### ISSUE THREAD

**Issue by cassde** [expo/eas-cli#1422]
### Summary

After the build with eas, the app crashes with `Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types` error. After reading the suggested fix in the react-native community, I've applied it to the native-modules (adding import from the deprecated-react-native-prop-types)  and the app is working fine on the emulator and when I build using enableProguardInReleaseBuilds. The issue is when I build with eas, it runs npm install which overwrites my updates and crashes with this error. How can I build with eas without overwriting my node-module updates?

### Managed or bare?

bare

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.18.3 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    npmPackages:
      expo: ^46.0.0 => 46.0.10
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.5 => 0.69.5
      react-native-web: ~0.18.7 => 0.18.9
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

eas build -p android --profile release
install the app
app crashes immediately

**Comment by wkozyra95** [comment]
You can use https://www.npmjs.com/package/patch-package to automatically patch sth in nodemodules on install
