### ISSUE TITLE
eas build -p ios successfull build when sent to TestFlight it does not reflect change in UI.

### ISSUE THREAD

**Issue by aliexalter** [expo/eas-cli#1429]
### Build/Submit details page URL

https://expo.dev/accounts/aliexalter/projects/amhoops/builds/71759067-5d45-4154-ba3b-c913ee538ebe

### Summary

I have project on github. I am using bare workflow (npx expo run:ios and npx expo prebuild). I commit changes and prebuild the project. The changes are in UI which I can see in simulator when I run expo run:ios command. 
When I build the project using eas build -p ios. It successfully built. After that I submit the built using eas submit -p ios and it as. me for the build I select latest build. It successfully sent it to TestFlight. When I download the latest version of app from TestFlight it gives me old UI of the app my changes were not reflect in the build. Whereas I can see my changes in simulator when running expo run:ios.
Please help me out if I am missing any command or anything.  

### Managed or bare?

Bare

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      Yarn: 1.22.15 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
      Android SDK:
        Android NDK: 22.1.7171670
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.13 => 46.0.15 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.7 
    npmGlobalPackages:
      eas-cli: 2.2.1
      expo-cli: 6.0.5
    Expo Workflow: bare
```
### Expo Doctor
🎉 Didn't find any issues with the project!

### Error output

No errors

### Reproducible demo or steps to reproduce from a blank project

Create new expo managed project. Then run 
`npx expo run:ios`
`npx expo prebuild`
make some changes in app.tsx
change version of ios and buildnumber in app.json
`npx expo run:ios`
`npx expo prebuild`
`eas build -p ios`
`eas submit -p ios`
once build reaches TestFlight download the latest version and compare it with expo run:ios simulator view.

**Comment by aliexalter** [comment]
Now I removed the ios and android folders I am thinking its not getting changes from git it might taking old code from folders. The project turns into managed workflow now and its compiling on expo let see what happen when it reached testFlight.

**Comment by aliexalter** [comment]
Managed also did not work. Changes are not reflect on Android Build either. Should I remove the project from expo account and create a new project I don't know where it's getting the old code.

**Comment by aliexalter** [comment]
This odd.
I have run expo build:ios then run eas build -p ios --clean-cache. it updates the build on android. Now checking on Testflight and I think --clean-cache is the one that is doing it.

**Comment by aliexalter** [comment]
eas build -p ios --clear-cache

**Comment by aliexalter** [comment]
It does not work I run the command again today with some slight changes. The build I got on TestFlight does not reflect changes. There is something with eas build on server which is compiling old code not the latest changes even i commit it on git and push the commits.

**Comment by aliexalter** [comment]
Ok here what I did and its working again but I need explanation of these commands
```
expo build:ios
npx expo prebuild --clean
eas build -p ios --clear-cache
```

**Comment by wkozyra95** [comment]
It's hard to say what is the problem, but I have few observations based on info you provided that might help with debugging.
- ` --clear-cache` is definitely not doing anything here.
- `expo build:ios` is publishing OTA update before building and artifact build using EAS Build might download that update and revert the changes. Try disabling updates on EAS Build or use a different `releaseChannel`.
- Are you sure that you are correctly installing ap from testflight and that the version is changing? e.g. after EAS Submit is finished it takes a few minutes until the app is available in testfllight?
- If you are running prebuild before every build, you should be on managed workflow. (you can add android and ios directories to gitignore, run:ios/run:android still work). EAS Build will run prebuild on the server.
- You can verify with `eas build:inspect` what will be uploaded to EAS.
