### ISSUE TITLE
How to enable `enableSeparateBuildPerCPUArchitecture` flag

### ISSUE THREAD

**Issue by farzin-fs** [expo/eas-cli#1431]
Is it possible to enable the `enableSeparateBuildPerCPUArchitecture` flag on the Android build to have separate APK builds instead of one in a managed expo app?

**Comment by wkozyra95** [comment]
Not currently, you would need to eject or write your own config plugins that modify build.gradle https://docs.expo.dev/guides/config-plugins/

Also if you want to just minimize download size for users you should use aab instead. A separate APK only makes sense if you want to distribute those files outside of stores.
