### ISSUE TITLE
showing old device list, unable to add new devices

### ISSUE THREAD

**Issue by chrisdrackett** [expo/eas-cli#1441]
### Summary

I have some new devices that I want to add to my build. I also have an old device that I want to remove. I did all this on apple's dev site and then I've been trying to do a build with EAS. No matter what I do (revoke all certs, create new certs, etc.) I still get the device list from before I made the changes.

I've even tried to update the profiles after EAS creates them on apple's site, but it just reverts the device list to the incorrect devices when I go to do a build.

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 3.2.0 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

¯\_(ツ)_/¯

**Comment by jcohenho** [comment]
@dsokal I have multiple devices listed on the Apple Developer portal, but when I run `eas device:create` and select the import from Developer Portal option, it says `All your devices registered on Apple Developer Portal are already imported to EAS.`. Any other ideas for how to refresh the list?
