### ISSUE TITLE
EAS Build failing at installing dependencies only on expo.dev

### ISSUE THREAD

**Issue by kdthomas2121** [expo/eas-cli#1446]
### Build/Submit details page URL

https://expo.dev/accounts/kdthomas21/projects/moneynomad/builds/cee7e9eb-a6be-41b4-825a-b78595f95b6b

### Summary

Cannot get iOS builds working on expo.dev, work fine locally and on Android, but can't install dependencies on iOS

`Running "npm install" in the root dir of your repository 
[stderr] npm
[stderr] ERR! code 1
[stderr] npm ERR! path /Users/expo/workingdir/build/node_modules/sqlite3
[stderr] npm ERR!
[stderr] command failed
[stderr] npm ERR! command sh /var/folders/h2/gp9wlkv11lg0qj6y2mnqgc_40000gn/T/install-751592bb.sh
[stderr] npm ERR! ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
[stderr] npm ERR! Failed to execute '/Users/expo/.nvm/versions/node/v16.17.1/bin/node /Users/expo/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/expo/workingdir/build/node_modules/sqlite3/lib/binding/node-v93-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/expo/workingdir/build/node_modules/sqlite3/lib/binding/node-v93-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
[stderr] npm ERR! node-pre-gyp info it worked if it ends with ok
[stderr] npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
[stderr] npm ERR! node-pre-gyp info using node@16.17.1 | darwin | x64
[stderr] npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
[stderr] npm ERR!
[stderr] node-pre-gyp info check checked for "/Users/expo/workingdir/build/node_modules/sqlite3/lib/binding/node-v93-darwin-x64/node_sqlite3.node" (not found)
[stderr] npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-darwin-x64.tar.gz
[stderr] npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-darwin-x64.tar.gz
[stderr] npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-darwin-x64.tar.gz 
[stderr] npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@16.17.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
[stderr] npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v93-darwin-x64.tar.gz 
[stderr] npm ERR! gyp info it worked if it ends with ok
[stderr] npm ERR! gyp info using node-gyp@9.0.0
[stderr] npm ERR! gyp info using node@16.17.1 | darwin | x64
[stderr] npm ERR! gyp info ok 
[stderr] npm ERR! gyp info it worked if it ends with ok
[stderr] npm ERR! gyp info using node-gyp@9.0.0
[stderr] npm ERR! gyp info using node@16.17.1 | darwin | x64
[stderr] npm ERR! gyp info find Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
[stderr] npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.1/node-v16.17.1-headers.tar.gz
[stderr] npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.1/node-v16.17.1-headers.tar.gz
[stderr] npm ERR! gyp http GET https://nodejs.org/download/release/v16.17.1/SHASUMS256.txt
[stderr] npm ERR! gyp http 200 https://nodejs.org/download/release/v16.17.1/SHASUMS256.txt
[stderr] npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
[stderr] npm ERR! gyp info spawn args [
[stderr] npm ERR! gyp info spawn args   '/Users/expo/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
[stderr] npm ERR! gyp info spawn args   'binding.gyp',
[stderr] npm ERR! gyp info spawn args   '-f',
[stderr] npm ERR! gyp info spawn args   'make',
[stderr] npm ERR! gyp info spawn args   '-I',
[stderr] npm ERR! gyp info spawn args   '/Users/expo/workingdir/build/node_modules/sqlite3/build/config.gypi',
[stderr] npm ERR! gyp info spawn args   '-I',
[stderr] npm ERR! gyp info spawn args   '/Users/expo/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
[stderr] npm ERR! gyp info spawn args   '-I',
[stderr] npm ERR! gyp info spawn args   '/Users/expo/Library/Caches/node-gyp/16.17.1/include/node/common.gypi',
[stderr] npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
[stderr] npm ERR! gyp info spawn args   '-Dvisibility=default',
[stderr] npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/expo/Library/Caches/node-gyp/16.17.1',
[stderr] npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/expo/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/node-gyp',
[stderr] npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/expo/Library/Caches/node-gyp/16.17.1/<(target_arch)/node.lib',
[stderr] npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/expo/workingdir/build/node_modules/sqlite3',
[stderr] npm ERR! gyp info spawn args   '-Dnode_engine=v8',
[stderr] npm ERR! gyp info spawn args   '--depth=.',
[stderr] npm ERR! gyp info spawn args   '--no-parallel',
[stderr] npm ERR! gyp info spawn args   '--generator-output',
[stderr] npm ERR! gyp info spawn args   'build',
[stderr] npm ERR! gyp info spawn args   '-Goutput_dir=.'
[stderr] npm ERR! gyp info spawn args ]
[stderr] npm ERR! gyp info ok 
[stderr] npm ERR! gyp info it worked if it ends with ok
[stderr] npm ERR! gyp info using node-gyp@9.0.0
[stderr] npm ERR! gyp info using node@16.17.1 | darwin | x64
[stderr] npm ERR! gyp info spawn make
[stderr] npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
[stderr] npm ERR! /bin/sh: python: command not found
[stderr] npm ERR! make: *** [Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
[stderr] npm ERR! gyp ERR! build error 
[stderr] npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
[stderr] npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/expo/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
[stderr] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
[stderr] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
[stderr] npm ERR! gyp ERR! System Darwin 21.5.0
[stderr] npm ERR! gyp ERR! command "/Users/expo/.nvm/versions/node/v16.17.1/bin/node" "/Users/expo/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/expo/workingdir/build/node_modules/sqlite3/lib/binding/node-v93-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Users/expo/workingdir/build/node_modules/sqlite3/lib/binding/node-v93-darwin-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
[stderr] npm ERR! gyp ERR! cwd /Users/expo/workingdir/build/node_modules/sqlite3
[stderr] npm ERR! gyp ERR! node -v v16.17.1
[stderr] npm ERR! gyp ERR! node-gyp -v v9.0.0
[stderr] npm ERR! gyp ERR! not ok 
[stderr] npm ERR! node-pre-gyp ERR! build error 
[stderr] npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/expo/.nvm/versions/node/v16.17.1/bin/node /Users/expo/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/expo/workingdir/build/node_modules/sqlite3/lib/binding/node-v93-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Users/expo/workingdir/build/node_modules/sqlite3/lib/binding/node-v93-darwin-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
[stderr] npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/expo/workingdir/build/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
[stderr] npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
[stderr] npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
[stderr] npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
[stderr] npm ERR! node-pre-gyp ERR! System Darwin 21.5.0
[stderr] npm ERR! node-pre-gyp ERR! command "/Users/expo/.nvm/versions/node/v16.17.1/bin/node" "/Users/expo/workingdir/build/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
[stderr] npm ERR! node-pre-gyp ERR! cwd /Users/expo/workingdir/build/node_modules/sqlite3
[stderr] npm ERR! node-pre-gyp ERR! node -v v16.17.1
[stderr] npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
[stderr] npm ERR! node-pre-gyp ERR! not ok
[stderr] npm ERR! A complete log of this run can be found in:
[stderr] npm ERR!     /Users/expo/.npm/_logs/2022-10-14T18_59_12_227Z-debug-0.log
npm exited with non-zero code: 1`

Getting the above. Tried deleting package-lock.json, and node_modules, no help

### Managed or bare?

Bare

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/kylethomas/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      expo: ~46.0.9 => 46.0.10 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.3.0
      expo-cli: 6.0.6
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

`{
  "cli": {
    "version": ">= 2.1.0",
    "promptToConfigurePushNotifications": false
  },
  "submit": {
    "production": {
      "android": {
        "serviceAccountKeyPath": "removed",
        "track": "internal",
        "releaseStatus": "draft"
      },
      "ios": {
        "appleId": "removed",
        "appleTeamId": "removed",
        "ascAppId": "removed"
      }
    }
  },
  "build": {
    "apk": {
      "android": {
        "buildType": "apk"
      }
    },
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "autoIncrement": true
    },
    "preview": {
      "distribution": "internal",
      "autoIncrement": true
    },
    "production": {
      "autoIncrement": true,
      "node": "16.17.1"
    }
  }
}
`

**Comment by wkozyra95** [comment]
> [stderr] npm ERR! /bin/sh: python: command not found

macOS removed python2, you can:
- try using an older image(it might break other things)
- figure out how to install python2 on current image
- update package that is failing (maybe they fixed that issue or they provide prebuilds for that platform)
- find a version of the node that this package in current version has prebuilds
