### ISSUE TITLE
Environment variables not updating with EAS Update

### ISSUE THREAD

**Issue by lindanip** [expo/eas-cli#1450]
Hey

We are having issues with updating environment variable, when using eas update.

We have ran:
`API=""  STAGE="" eas udpate --profile pre-development --message ""`

It was only able to change our environment variables once, then it stopped working, we've updated several times and only the text/ui in the app changes but not the environment variables.

And somehow our apollo-graphql initialisation file has different environment variables as compared to our login page, and they both  access env values via `process.env.VALUE.` 

for our environment variables we are using:
`babel-plugin-transform-inline-environment-variables` `^0.4.4`

We are using 
SDK 45
eas cli 0.52.0
node v16.16.0
expo-updates ~0.13.4
react 17.0.2
react native 0.68.2

Please adivse.

**Comment by stovmascript** [comment]
I don't think the `eas update` currently accepts the `--profile` flag. It would be great if it did though. Also, if it could be set up in a similar fashion as build and submit in `eas.json`, with profiles and environment variables, etc.

**Comment by lindanip** [comment]
Oh ye sorry about that, I meant to put `API_URL="" eas --branch pre-development --message ""`

1. Just to add on the query above, we have also tried using Expos way of accessing envs, using:
`Constants.expoConfig.extra.API_URL` 
and it doesn`t work.

When we put console logs on the `app.config.js`, we are able to see our variables, even on expo dashboard log under `Read app config` we are able to see them, 

But the `Constants.expoConfig.extra.API_URL` doesn't work

on the code it says `expoConfig` doesn't exist on the module.

**Comment by lindanip** [comment]
`API="" STAGE="" eas udpate --branch pre-development --message ""`

**Comment by douglowder** [comment]
To work on this, we would need a project that reproduces the issue. It may be that the real problem is in `babel-plugin-transform-inline-environment-variables`, but it is hard to tell without a working repro.
