### ISSUE TITLE
Android bundle id with numbers in

### ISSUE THREAD

**Issue by rennard** [expo/eas-cli#1453]
### Summary

Trying to run `eas build` to build android fails with a bundle id that contains numbers, e.g. com.123.app I'm met with 
"Invalid format of Android applicationId. Only alphanumeric characters, '.' and '_' are allowed, and each '.' must be followed by a letter.
    Error: "android.package" is not defined in your app.config.js and we can't update this file 
    programmatically. Add the value on your own and run this command again."

### Managed or bare?

bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.8.0/bin/yarn
      npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
      Watchman: 2022.05.16.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      expo: ~46.0.9 => 46.0.13 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 1.2.0
      expo-cli: 6.0.6
    Expo Workflow: bare

### Error output

`
eas build
★ eas-cli@2.4.1 is now available.
To upgrade, run npm install -g eas-cli.
Proceeding with outdated version.

Found eas-cli in your project dependencies.
It's recommended to use the "cli.version" field in eas.json to enforce the eas-cli version for your project.
Learn more: https://github.com/expo/eas-cli#enforcing-eas-cli-version-for-your-project

✔ Select platform › Android
Invalid format of Android applicationId. Only alphanumeric characters, '.' and '_' are allowed, and each '.' must be followed by a letter.
    Error: "android.package" is not defined in your app.config.js and we can't update this file 
    programmatically. Add the value on your own and run this command again.`

### Reproducible demo or steps to reproduce from a blank project

init new app, set bundle id to contain numbers and run eas build for android

**Comment by dsokal** [comment]
It's not an issue. Please read the error message "... each '.' must be followed by a letter."
