### ISSUE TITLE
EAS Update to build only either IOS or Android

### ISSUE THREAD

**Issue by davidyang** [expo/eas-cli#1455]
### Do you understand that any feature requests opened in this repository will be closed?

Yes

**Comment by davidyang** [comment]
When I specify `--platform=ios` on eas-cli update it still builds the Android version.  I can build just the IOS platform manually but then when I try `npx eas-cli update --platform=ios --skip-bundler` I get an error like this:

```
✖ Failed to upload assets
    ValidationError: "fileMetadata.android" is required
```

**Comment by pfcodes** [comment]
+1
