### ISSUE TITLE
IOS Builds failing due to StripeApplePay build failing

### ISSUE THREAD

**Issue by Pcummings** [expo/eas-cli#1456]
### Build/Submit details page URL

https://expo.dev/accounts/fairtasting/projects/fairTasting

### Summary

When trying to build my project through EAS using the following command:

```npx eas-cli build --platform ios --non-interactive --wait  --profile production```

This became an issue after upgrading to SDK46 and using the latest version of eas-cli. Previously I have not had any issues building this. When removing @stripe/stripe-react-native from my project it builds just fine.

Looking at the @stripe/stripe-react-native documentation, it is mentioned that you need to run pod install before building, so I tried this with:
```
npx expo prebuild --platform ios 
cd ios
pod install
```
and then build again, this however yielded the same output.

Any help on this would be greatly appreciated.

### Managed or bare?

Managed

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.17.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.1.61 => 0.1.84 
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      expo: ^46.0.0 => 46.0.14 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    Expo Workflow: managed

### Error output

ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPApplePayContext.swift:240:54)

  238 |         let pk_didSelectShippingMethod = #selector(
  239 |             (PKPaymentAuthorizationControllerDelegate.paymentAuthorizationController(
> 240 |                 _:didSelectShippingMethod:handler:)) as pkDidSelectShippingMethodSignature)
      |                                                      ^ '-> ((PKPaymentAuthorizationController, PKShippingMethod, @escaping (PKPaymentRequestShippingMethodUpdate) -> Void) -> Void)?' is not convertible to 'pkDidSelectShippingMethodSignature' (aka 'Optional<((any PKPaymentAuthorizationControllerDelegate) -> (PKPaymentAuthorizationController, PKShippingMethod, @escaping (PKPaymentRequestShippingMethodUpdate) -> ()) -> ())>')
  241 |         let stp_didSelectShippingMethod = #selector(
  242 |             _stpinternal_STPApplePayContextDelegateBase.applePayContext(_:didSelect:handler:))
  243 |         let pk_didSelectShippingContact = #selector(

▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	SwiftCompile normal arm64 Compiling\ Address.swift,\ BillingDetails.swift,\ BillingDetails+ApplePay.swift,\ Blocks.swift,\ CardBrand.swift,\ FraudDetectionData.swift,\ PaymentIntent.swift,\ PaymentIntent+API.swift,\ PaymentIntentParams.swift,\ PaymentMethod.swift,\ PaymentMethod+API.swift,\ PaymentMethodParams.swift,\ PKContact+Stripe.swift,\ PKPayment+Stripe.swift,\ SetupIntent.swift,\ SetupIntent+API.swift,\ SetupIntentParams.swift,\ STPAnalyticsClient+Payments.swift,\ STPAnalyticsClient+PaymentsAPI.swift,\ STPAPIClient+ApplePay.swift,\ STPAPIClient+PaymentsCore.swift,\ STPApplePayContext.swift,\ STPApplePayContext+LegacySupport.swift,\ STPTelemetryClient.swift,\ StripeCore+Import.swift,\ Token.swift,\ Token+API.swift,\ UserDefaults+PaymentsCore.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/Address.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/BillingDetails.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/Extensions/BillingDetails+ApplePay.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/Blocks.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/CardBrand.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Telemetry/FraudDetectionData.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/PaymentIntent.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/PaymentIntent+API.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/PaymentIntentParams.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/PaymentMethod.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/PaymentMethod+API.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/PaymentMethodParams.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/Extensions/PKContact+Stripe.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/Extensions/PKPayment+Stripe.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/SetupIntent.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/SetupIntent+API.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/SetupIntentParams.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Analytics/STPAnalyticsClient+Payments.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Analytics/STPAnalyticsClient+PaymentsAPI.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPAPIClient+ApplePay.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Categories/STPAPIClient+PaymentsCore.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPApplePayContext.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPApplePayContext+LegacySupport.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Telemetry/STPTelemetryClient.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/StripeCore+Import.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Models/Token.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/API/Token+API.swift /Users/expo/workingdir/build/ios/Pods/StripeApplePay/StripeApplePay/StripeApplePay/Source/PaymentsCore/Categories/UserDefaults+PaymentsCore.swift (in target 'StripeApplePay' from project 'Pods')
▸ 	CompileSwift normal arm64 (in target 'StripeApplePay' from project 'Pods')
▸ (2 failures)
** ARCHIVE FAILED **

### Reproducible demo or steps to reproduce from a blank project

Implement the standard functionality of a payment button from stripe react native, and try to build

**Comment by paulsizer** [comment]
I have the same issue as @Pcummings 

Environment

Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 12.6
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 16.14.1 - /usr/local/bin/node
Yarn: 1.22.17 - /usr/local/bin/yarn
npm: 7.24.2 - ~/Apps/coach-rx-mobile/node_modules/.bin/npm
SDKs:
iOS SDK:
Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
IDEs:
Android Studio: 2021.1 AI-211.7628.21.2111.8193401
Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
npmPackages:
expo: ^46.0.0 => 46.0.15
react: 18.0.0 => 18.0.0
react-dom: 18.0.0 => 18.0.0
react-native: 0.69.6 => 0.69.6
react-native-web: ~0.18.7 => 0.18.9
npmGlobalPackages:
eas-cli: 2.4.1
expo-cli: 6.0.6
Expo Workflow: managed

**Comment by Pcummings** [comment]
I upgraded @stripe/stripe-react-native version to 0.19.0 and that worked! It would seem that expo needs to update the dependencies.

**Comment by lifesmile-ae** [comment]
Hi,
I was having the same issue so as you have mentioned I upgraded the  @stripe/stripe-react-native but I am not having 
`The following build commands failed:
	CompileC /Users/expo/Library/Developer/Xcode/DerivedData/lifesmile-epzjiqmuwpqabggewnatjchafarp/Build/Intermediates.noindex/ArchiveIntermediates/lifesmile/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/UMReactNativeAdapter.build/Objects-normal/arm64/UMReactNativeEventEmitter.o /Users/expo/workingdir/build/node_modules/@unimodules/react-native-adapter/ios/UMReactNativeAdapter/Services/UMReactNativeEventEmitter.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'UMReactNativeAdapter' from project 'Pods')`

Is this same stripe issue or another one ??

**Comment by Raraku** [comment]
Currently having this issue. 
Is there any workaround that can be done without updating stripe?

**Comment by andy-ratsirarson** [comment]
I'm having the same issue with 
```
 "@stripe/stripe-identity-react-native": "^0.2.7",
    "@stripe/stripe-react-native": "^0.37.3",
```
