### ISSUE TITLE
EAS CLI Apple Developer Authentication Fails

### ISSUE THREAD

**Issue by lordprana** [expo/eas-cli#1459]
### Summary

I submitted a build via EAS cli with the following command: `eas build --profile internalDevelopment --platform ios`, and was asked for a 2-factor code. I didn't have my 2-factor code handy, so I control+c'd the terminal window. After I had my 2-factor code, I tried logging in again, and after inputting my password, I received the following error from the CLI:

`Authentication with Apple Developer Portal failed!
    Error: getaddrinfo ENOTFOUND
    developer.apple.com
    Code: ENOTFOUND`

I ran the command again with the EXPO_NO_KEYCHAIN=1 env variable, and was asked for my two-factor code. However, after inputting a successful two-factor code, I saw the following output.

`› Saving Apple ID password to the local Keychain
  Learn more
✔ Logged in New session
Authentication with Apple Developer Portal failed!
    Error: getaddrinfo ENOTFOUND
    developer.apple.com
    Code: ENOTFOUND
error Command failed with exit code 1.`

Please let me know what I need to do to fix this, or if Apple's servers are experiencing problems. Thank you.

### Managed or bare?

Bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.18.3 - /usr/local/bin/node
      Yarn: 1.22.17 - /opt/homebrew/bin/yarn
      npm: 8.5.0 - ~/.npm-global/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.2.0
    Expo Workflow: bare

### Error output

`› Log in to your Apple Developer account to continue
✔ Apple ID: … mrazek@ucsb.edu
› Restoring session /Users/matthewgaba/.app-store/auth/mrazek@ucsb.edu/cookie
› Session expired Local session
› Using password for mrazek@ucsb.edu from your local Keychain
  Learn more
✖ Logging in...
Authentication with Apple Developer Portal failed!
    Error: getaddrinfo ENOTFOUND
    idmsa.apple.com
    Code: ENOTFOUND
error Command failed with exit code 1.`

### Reproducible demo or steps to reproduce from a blank project

See summary.

**Comment by dsokal** [comment]
It looks like an intermittent issue with Apple servers. Is this still not working for you? Are you using some kind of proxy?

**Comment by lordprana** [comment]
It's working again now. Thanks!
