### ISSUE TITLE
Unable to build app with eas [expo/node_modules/react-native-reanimated/android/../../react-native/package.json (No such file or directory)]

### ISSUE THREAD

**Issue by joseito-terence** [expo/eas-cli#1471]
### Build/Submit details page URL

https://expo.dev/accounts/joseito.terence/projects/builderror/builds/954a2025-50d8-462c-b046-2ae201f8681c

### Summary

I'm unable to build the app. It throws an error.
It works fine in development mode with Expo Go, no issues there.

I've tried playing around with the version of react-native-reanimated but no luck

basically error looks something like this.
```
A problem occurred evaluating project ':react-native-reanimated'.

[stderr] > /home/expo/workingdir/build/apps/expo/node_modules/react-native-reanimated/android/../../react-native/package.json (No such file or directory)
```

### Managed or bare?

managed

### Environment

```
 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
      npm: 8.13.2 - ~/.nvm/versions/node/v16.15.1/bin/npm
    npmGlobalPackages:
      eas-cli: 0.59.0
      expo-cli: 6.0.6
    Expo Workflow: managed
```

```
Running "expo doctor"
- Finding all copies of @unimodules/core
- Finding all copies of @unimodules/react-native-adapter
- Finding all copies of react-native-unimodules
[14:50:07] 🎉 Didn't find any issues with the project!
```

### Error output

[stderr] FAILURE: Build completed with 2 failures.
[stderr] 1: Task failed with an exception.
[stderr] -----------
[stderr] * Where:
[stderr] Build file '/home/expo/workingdir/build/apps/expo/node_modules/react-native-reanimated/android/build.gradle' line: 7
[stderr] * What went wrong:
[stderr] A problem occurred evaluating project ':react-native-reanimated'.
[stderr] > /home/expo/workingdir/build/apps/expo/node_modules/react-native-reanimated/android/../../react-native/package.json (No such file or directory)
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] 2: Task failed with an exception.
[stderr] -----------
[stderr] * What went wrong:
[stderr] A problem occurred configuring project ':expo'.
[stderr] > compileSdkVersion is not specified. Please add it to build.gradle
[stderr] * Try:
[stderr] Run with -stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] ==============================================================================
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 44s

### Reproducible demo or steps to reproduce from a blank project

1. git clone https://github.com/joseito-terence/build-error-repo.git
or 
1. git clone git@github.com:joseito-terence/build-error-repo.git

2. yarn
3. cd apps/expo
4. eas build -p android

**Comment by dsokal** [comment]
It's not an issue with EAS CLI. 
https://github.com/software-mansion/react-native-reanimated/issues/3711
