### ISSUE TITLE
Command to validate iOS Certificate and Provision Profile

### ISSUE THREAD

**Issue by hieunc229** [expo/eas-cli#1476]
When building the iOS using `eas build -p ios --local`, it took me about 5 mins to get to where it start validating iOS Distribution, Profile Provision with the app identifier.

When I choose to let Expo and xCode manage the certificate automatically, it gets messy and keep throwing Provision profile "*[expo]..." not suitable with the selected Distribution certificate error. Then to validate it, I need to spend another 5 mins to see if it was correct.

After many times, the cert was still incorrect, I ended up remove all the certs and profiles to let expo regenerate them all again. It'd be great to have a command where we can validate it right away

**Comment by alexander-schranz** [comment]
I' also searching for a way to check if my certificates expires.

I have 3 channels, for one I also require to validate if the development distribution is valid or not. Is there any way yet fo rthis?

**Comment by hieunc229** [comment]
Sorry it's been a while, I forgot how to check it. Hope it'll work out for you!
