### ISSUE TITLE
🤖 Android build failed: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.

### ISSUE THREAD

**Issue by CHNsPart** [expo/eas-cli#1496]
### Summary

I was using `expo build:android` but after upgrading to `eas-build` It is showing me this error :

**🤖 Android build failed:
Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.**

### Environment

```
{
  "name": "test-app",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/netinfo": "8.2.0",
    "expo": "~45.0.0",
    "expo-asset": "~8.5.0",
    "expo-av": "~11.2.3",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-system-ui": "~1.2.0",
    "expo-updates": "~0.13.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-video": "git+https://git@github.com/paddy57/react-native-video-android-cache.git",
    "react-native-web": "0.17.7",
    "react-native-webview": "11.18.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "metro": "^0.71.1"
  },
  "private": true
}
```

### Please specify your device/emulator/simulator platform, model and version

ADB TV OS, Expo SDK

### Error output

`Running './gradlew :app:bundleRelease' in /home/expo/workingdir/build/android
Downloading https://services.gradle.org/distributions/gradle-7.3.3-all.zip
10
%.
20
%.
30
%.
40%.
50
%.
60%.
70
%.
80
%.
90%.
100%
Welcome to Gradle 7.3.3!
Here are the highlights of this release:
 - Easily declare new test suites in Java projects
- Support for Java 17
 - Support for Scala 3
For more details see https://docs.gradle.org/7.3.3/release-notes.html
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.3.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
Unable to list file systems to check whether they can be watched. Assuming all file systems can be watched. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)
> Task :react-native-gradle-plugin:compileKotlin
'compileJava' task (current target is 1.8) and 'compileKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (10, 37): 'BaseVariant' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (119, 30): 'BaseVariant' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (135, 26): 'BaseVariant' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (155, 32): 'BaseVariant' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (161, 31): 'BaseVariant' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactExtension.kt: (169, 36): 'BaseVariant' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactPlugin.kt: (100, 48): 'reactRoot: DirectoryProperty' is deprecated. reactRoot was confusing and has been replace with rootto point to your root project and reactNativeDir to point to the folder of the react-native NPM package
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (10, 37): 'ApplicationVariant' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (11, 37): 'BaseVariant' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (12, 37): 'LibraryVariant' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (28, 51): 'BaseVariant' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (131, 12): 'ApplicationVariant' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (132, 12): 'LibraryVariant' is deprecated. Deprecated in Java
w: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt: (252, 14): 'BaseVariant' is deprecated. Deprecated in Java
> Task :react-native-gradle-plugin:compileJava
[stderr] 
Note: /home/expo/workingdir/build/node_modules/react-native-gradle-plugin/src/main/java/com/facebook/react/codegen/generator/SchemaJsonParser.java uses or overrides a deprecated API.
[stderr] 
Note: Recompile with -Xlint:deprecation for details.
> Task :react-native-gradle-plugin:pluginDescriptors
> Task :react-native-gradle-plugin:processResources
> Task :react-native-gradle-plugin:classes
> Task :react-native-gradle-plugin:inspectClassesForKotlinIC
> Task :react-native-gradle-plugin:jar
> Configure project :app
Unable to detect AGP versions for included builds. All projects in the build should use the same AGP version. Class name for the included build object: org.gradle.composite.internal.DefaultIncludedBuild$IncludedBuildImpl_Decorated.
> Configure project :expo-av
Checking the license for package NDK (Side by side) 21.4.7075529 in /home/expo/Android/Sdk/licenses
License for package NDK (Side by side) 21.4.7075529 accepted.
Preparing "Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)".
"Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)" ready.
Installing NDK (Side by side) 21.4.7075529 in /home/expo/Android/Sdk/ndk/21.4.7075529
"Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)" complete.
"Install NDK (Side by side) 21.4.7075529 (revision: 21.4.7075529)" finished.
Checking the license for package CMake 3.10.2.4988404 in /home/expo/Android/Sdk/licenses
License for package CMake 3.10.2.4988404 accepted.
Preparing "Install CMake 3.10.2.4988404 (revision: 3.10.2)".
"Install CMake 3.10.2.4988404 (revision: 3.10.2)" ready.
Installing CMake 3.10.2.4988404 in /home/expo/Android/Sdk/cmake/3.10.2.4988404
"Install CMake 3.10.2.4988404 (revision: 3.10.2)" complete.
"Install CMake 3.10.2.4988404 (revision: 3.10.2)" finished.
> Configure project :expo-eas-client
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
> Configure project :expo-structured-headers
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
> Configure project :expo-updates-interface
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
> Configure project :expo
Using expo modules
  - expo-application (4.1.0)
  - expo-av (11.2.3)
  - expo-constants (13.1.1)
  - expo-eas-client (0.2.1)
  - expo-error-recovery (3.1.0)
  - expo-file-system (14.0.0)
  - expo-font (10.1.0)
  - expo-json-utils (0.3.0)
  - expo-keep-awake (10.1.1)
  - expo-manifests (0.3.0)
  - expo-modules-core (0.9.2)
  - expo-splash-screen (0.15.1)
  - expo-structured-headers (2.2.1)
  - expo-system-ui (1.2.0)
  - expo-updates (0.13.2)
Checking the license for package Android SDK Build-Tools 30.0.2 in /home/expo/Android/Sdk/licenses
License for package Android SDK Build-Tools 30.0.2 accepted.
Preparing "Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)".
"Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)" ready.
Installing Android SDK Build-Tools 30.0.2 in /home/expo/Android/Sdk/build-tools/30.0.2
"Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)" complete.
"Install Android SDK Build-Tools 30.0.2 (revision: 30.0.2)" finished.
Checking the license for package Android SDK Platform 31 in /home/expo/Android/Sdk/licenses
License for package Android SDK Platform 31 accepted.
Preparing "Install Android SDK Platform 31 (revision: 1)".
"Install Android SDK Platform 31 (revision: 1)" ready.
Installing Android SDK Platform 31 in /home/expo/Android/Sdk/platforms/android-31
"Install Android SDK Platform 31 (revision: 1)" complete.
"Install Android SDK Platform 31 (revision: 1)" finished.
Checking the license for package Android SDK Build-Tools 31 in /home/expo/Android/Sdk/licenses
License for package Android SDK Build-Tools 31 accepted.
Preparing "Install Android SDK Build-Tools 31 (revision: 31.0.0)".
"Install Android SDK Build-Tools 31 (revision: 31.0.0)" ready.
Installing Android SDK Build-Tools 31 in /home/expo/Android/Sdk/build-tools/31.0.0
"Install Android SDK Build-Tools 31 (revision: 31.0.0)" complete.
"Install Android SDK Build-Tools 31 (revision: 31.0.0)" finished.
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preReleaseBuild
> Task :app:bundleReleaseJsAndAssets FAILED
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/expo/workingdir/build/metro.config.js from /home/expo/workingdir/build/node_modules/import-fresh/index.js not supported.
metro.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename metro.config.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/expo/workingdir/build/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
[stderr] 
error require() of ES Module /home/expo/workingdir/build/metro.config.js from /home/expo/workingdir/build/node_modules/import-fresh/index.js not supported.
[stderr] 
metro.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
[stderr] 
Instead rename metro.config.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/expo/workingdir/build/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
at module.exports (/home/expo/workingdir/build/node_modules/import-fresh/index.js:28:9)
    at loadJs (/home/expo/workingdir/build/node_modules/cosmiconfig/dist/loaders.js:9:18)
    at Explorer.loadFileContent (/home/expo/workingdir/build/node_modules/cosmiconfig/dist/createExplorer.js:230:12)
    at /home/expo/workingdir/build/node_modules/cosmiconfig/dist/createExplorer.js:252:21
info Run CLI with --verbose flag for more details.
[stderr] 
FAILURE: Build failed with an exception.
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':app:bundleReleaseJsAndAssets'.
[stderr] 
> Process 'command 'node'' finished with non-zero exit value 1
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug
[stderr] 
option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 3m 44s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
8 actionable tasks: 8 executed
Unable to list file systems to check whether they can be watched. The whole state of the virtual file system has been discarded. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.`

### Reproducible demo or steps to reproduce from a blank project

`import { StyleSheet, View, Dimensions, Text } from 'react-native';
import appData from "./data.json"
import NetInfo from "@react-native-community/netinfo"
import React, { Component } from 'react';
import * as Updates from "expo-updates"
import * as SplashScreen from 'expo-splash-screen';
import {Asset} from "expo-asset"
import { Video } from 'expo-av';

var i=0
const data = appData

const {width, height} = Dimensions.get("screen")

export default class App extends Component {

   

  constructor(props){
    super(props);
    this.state = {
      conn_status: "",
      playlist: data,
    }
/*     this.prepare()
    this.InternetChecker()
    this.reactToUpdates() */
  }
  cacheResources = async () => {
    var videosA = data[0].src
    var dataCached = []
    var videosB = data[1].src
    var videosC = data[2].src
    console.log(videosA)
    console.log(videosB)
    console.log(videosC)
    const cacheVideosA = Asset.fromModule(videosA).downloadAsync()
    dataCached.push(cacheVideosA)  
    const cacheVideosB = Asset.fromModule(videosB).downloadAsync()
    dataCached.push(cacheVideosB)  
    const cacheVideosC = Asset.fromModule(videosC).downloadAsync()
    dataCached.push(cacheVideosC)  
    console.log(dataCached)
    /* videos.map(video => {
      return Asset.fromModule(video).downloadAsync()
    }) */
    return Promise.all(dataCached)
  }

  componentDidMount = () => {
    loadResource = async () => {
      await this.cacheResources()
      await this.prepare()
      await this.InternetChecker()
      await this.reactToUpdates()
    }
    loadResource()
  }

  reactToUpdates = async () => {
     Updates.addListener((e)=>{
      if (e.type === Updates.UpdateEventType.UPDATE_AVAILABLE) {
       Updates.reloadAsync()
      }
    })
  }

  prepare = async () => {
    try {
      await SplashScreen.preventAutoHideAsync();
      await new Promise(resolve => setTimeout(resolve, 3000));
    } catch (e) {
      console.warn(e);
    } finally {
      SplashScreen.hideAsync();
    }
  }

  InternetChecker = async () => {
    await NetInfo.fetch().then( state => {
      console.log("Connection Type", state.type)
      console.log("Is connected?", state.isConnected)
      if(state.isConnected === true){
        this.setState({
          conn_status: "online"
        })
      } else {
        this.setState({
          conn_status: "offline"
        })
      }
    })
  }

  videoUpdated(playbackStatus){
    if(playbackStatus['didJustFinish']){
      console.log(this.state.playlist[i].name+" just finished",Date().toLocaleString(),i);
      this.playNext(); 
    }
  }
  playNext(){
      let playlist = this.state.playlist;
      let temp = playlist[0];
      playlist.shift();
      playlist.push(temp);
      this.setState({playlist,})
      this.InternetChecker()
  }
  render() {
    if(this.state.conn_status === "online"){ 
      return (
        <View>
          <Video 
            onPlaybackStatusUpdate={(playbackStatus)=> this.videoUpdated(playbackStatus)}
            resizeMode="contain" 
            source={{uri: this.state.playlist[0].src}}
            useNativeControls = {false}
            rate={1.0}
            shouldPlay
            autoPlay
            volume={1.0}
            muted={false} 
            style={{height:height,width:width}} 
          />
        </View>
      );
    } else {
      return(
        <View>
          <Video 
          resizeMode="contain" 
          source={require("./assets/offline.mp4")}
          useNativeControls = {false}
          rate={1.0}
          shouldPlay
          autoPlay
          isLooping
          volume={1.0}
          muted={false} 
          style={{height:height,width:width}} />
        </View>
      )
    }
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
`

**Comment by ownsupernoob2** [comment]
I have the same problem

**Comment by aquib20034** [comment]
I've also the same problem, and still unable to resolve it.
Please help!

**Comment by joshnwosu** [comment]
Any update on this?

**Comment by aquib20034** [comment]
I used this json.
{
    "name": "highway-app",
    "version": "1.0.0",
    "main": "node_modules/expo/AppEntry.js",
    "scripts": {
        "start": "expo start",
        "android": "expo start --android",
        "ios": "expo start --ios",
        "web": "expo start --web",
        "eject": "expo eject"
    },
    "dependencies": {
        "@eliav2/react-native-collapsible-view": "^1.4.0",
        "@expo/vector-icons": "^13.0.0",
        "@react-native-async-storage/async-storage": "~1.17.3",
        "@react-native-community/datetimepicker": "6.5.2",
        "@react-native-community/netinfo": "9.3.5",
        "@react-native-picker/picker": "2.4.8",
        "@react-navigation/bottom-tabs": "^6.3.1",
        "@react-navigation/drawer": "^6.2.0",
        "@react-navigation/native": "^6.0.7",
        "@react-navigation/stack": "^6.0.11",
        "expo": "^47.0.3",
        "expo-app-loading": "~2.1.1",
        "expo-camera": "~13.1.0",
        "expo-font": "~11.0.1",
        "expo-image-manipulator": "~11.0.0",
        "expo-image-picker": "~14.0.2",
        "expo-location": "~15.0.1",
        "expo-permissions": "~14.0.0",
        "expo-secure-store": "~12.0.0",
        "expo-status-bar": "~1.4.2",
        "formik": "^2.2.9",
        "install": "^0.13.0",
        "pusher-chatkit-gifted-chat": "^1.0.19",
        "pusher-js": "^7.1.1-beta",
        "react": "18.1.0",
        "react-dom": "18.1.0",
        "react-hook-form": "^7.28.1",
        "react-native": "^0.70.5",
        "react-native-chart-kit": "^6.11.0",
        "react-native-dropdown-picker": "^5.3.0",
        "react-native-form-validator": "^0.1.3",
        "react-native-gesture-handler": "~2.8.0",
        "react-native-gifted-chat": "^1.0.2",
        "react-native-maps": "1.3.2",
        "react-native-modern-datepicker": "^1.0.0-beta.91",
        "react-native-range-slider-expo": "^1.4.2",
        "react-native-ratings": "^8.1.0",
        "react-native-reanimated": "^2.12.0",
        "react-native-safe-area-context": "4.4.1",
        "react-native-storage": "^0.2.4",
        "react-native-svg": "13.4.0",
        "react-native-web": "~0.18.9",
        "react-redux": "^7.2.6",
        "redux": "^4.1.2",
        "redux-thunk": "^2.4.1",
        "yup": "^0.32.11"
    },
    "devDependencies": {
        "@babel/core": "^7.12.9",
        "@types/react-native": "~0.64.12",
        "typescript": "~4.3.5"
    },
    "private": true
}


then build was created successfully!

**Comment by Abdullah-Raoufi** [comment]
I have the same problem.

**Comment by mr-abdellah** [comment]
> I've also the same problem, and still unable to resolve it.
> Please help!

any update bro? I've same issue 🤓

**Comment by Chrahuldeveloper** [comment]
Some one please reply on this i am also struggling with this error

**Comment by Trapintrovert** [comment]
Having the same problem. Any solution yet ??

**Comment by jangandibantingg** [comment]
> Probably dependencies versioning incompatibility
> 
> Try run
> 
> expo doctor expo doctor --fix-dependencies
> 
> then try to rebuild

not working for me bro.

**Comment by jangandibantingg** [comment]
> Some one please reply on this i am also struggling with this error

still error dude? any solution ?

**Comment by brentvatne** [comment]
hey there, check out the guide for troubleshooting build errors: https://docs.expo.dev/build-reference/troubleshooting/

at the bottom of the page there is more information on how to ask a good question after you've followed the guide if you're still stuck: https://docs.expo.dev/build-reference/troubleshooting/#how-to-ask-a-good-question

**Comment by jangandibantingg** [comment]
delete some error package in package.json and re export file png, I don't know why I had to remove the "react-native-navigation" but it worked  


`[stderr] FAILURE: Build completed with 2 failures.
[stderr] 1: Task failed with an exception.
[stderr] -----------
[stderr] * Where:
[stderr] Build file '/home/expo/workingdir/build/node_modules/react-native-navigation/lib/android/app/build.gradle' line: 5
[stderr] * What went wrong:`
 
```
[stderr] > Multiple task action failures occurred:
[stderr]    > A failure occurred while executing com.android.build.gradle.internal.res.Aapt2CompileRunnable
[stderr]       > Android resource compilation failed
[stderr]         ERROR:/home/expo/workingdir/build/android/app/build/generated/res/react/release/drawable-mdpi/assets_user.png: AAPT: error: file failed to compile.
```

**Comment by venanciokranvoski** [comment]
I keep trying this error any help I've followed all the guidelines and I'm still with the same error

**Comment by cheraa-git** [comment]
I also have the same problem. It appeared after installing the `react-native-orientation` package. After removing this package, the problem disappeared. If I can find solutions without removing the package, I will let you know

**Comment by venanciokranvoski** [comment]
I don't have this lib in my project, does anyone know how to use the expo key to set in build.graldew to build with ./gradlew buindRelease?

**Comment by brunoaiolfi** [comment]
i had a problem with react-native-navigation, i uninstall and installed again, it worked. But now i had the same problem and it doesn't worked.

**Comment by brunoaiolfi** [comment]
> i had a problem with react-native-navigation, i uninstall and installed again, it worked. But now i had the same problem and it doesn't worked.

I went to package.json and deleted react-native-navigation. Thats work for me

**Comment by jihaddeveloper** [comment]
My package.json -->

{
  "name": "misapp",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/datetimepicker": "6.5.2",
    "@react-native-picker/picker": "^2.4.8",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "axios": "^0.26.1",
    "bd-geojs": "^1.0.0",
    "expo": "^47.0.13",
    "expo-status-bar": "~1.4.2",
    "expo-updates": "~0.15.6",
    "firebase": "^8.10.1",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-modern-datepicker": "^1.0.0-beta.91",
    "react-native-paper": "^4.9.2",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-shadow-cards": "^1.0.2",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3"
  },
  "private": true
}


Getting same error, please help me.

**Comment by SethY8s** [comment]
> same issue, i think this issue is due to, "react-native-webview"

@umang752 Did you ever find a solution? currently using webview on our app and would like to continue to use it.

**Comment by brunoaiolfi** [comment]
> > same issue, i think this issue is due to, "react-native-webview"
> 
> @umang752 Did you ever find a solution? currently using webview on our app and would like to continue to use it.

can you show us the error log?

**Comment by chirag773** [comment]
Please help i am also stuck at this build error  ```Execution failed for task ':app:compileReleaseJavaWithJavac'.```

**Comment by venanciokranvoski** [comment]
this error happens.
1 - or your Expo is in version <=45 minor versions and are obsolete, the way to solve my problem was to compile it by react-native even with the command that is in react-native documentation, if it is just expo Eject it and use react-native's native template.

**Comment by kaloraat** [comment]
I tried creating build using `eas build --platform android` in a fresh expo project and it works perfectly fine.

As soon as I installed and used react-navigation packages, I see this  **Gradle build failed** error:

```
🤖 Android build failed:
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

So there must be something wrong/compatibility issues with the react-navigation packages. Stuck on this for few weeks now. Any help is appriciated.

**Comment by chirag773** [comment]
> Please help i am also stuck at this build error `Execution failed for task ':app:compileReleaseJavaWithJavac'.`

I solve this by removing expo-cli after I upgraded to expo SDK 48.
as per the documentation, expo-cli is now part of SDK 48 internally I guess

**Comment by Negerev** [comment]
> Я решаю эту проблему, удалив expo-cli после обновления до expo SDK 48. Согласно документации, expo-cli теперь является внутренней частью SDK 48, я думаю.

Thanks a lot, it worked for me!

**Comment by rouckay** [comment]
> Fixed this by creating a new file .npmrc in project folder then, setting ‘legacy-peer-deps=true’ and also run ‘npm config set legacy-peer-deps true’ in terminal

Thank you yes your solution is worked for me thank  you so much dear

**Comment by miteshdevg** [comment]
i have updated my expo version from 48 to 49 and after i am 
getting error in building in my ternimal


like below 
```

✖ Build failed

🤖 Android build failed:
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

i need help if anyone resolve it so please give me response.


and my package.json is below 



`  "dependencies": {
    "@api.video/react-native-player": "^1.0.2",
    "@api.video/react-native-video-uploader": "^1.0.0",
    "@expo/vector-icons": "^13.0.0",
    "@fortawesome/fontawesome-svg-core": "^1.3.0",
    "@fortawesome/free-brands-svg-icons": "^6.0.0",
    "@fortawesome/free-regular-svg-icons": "^6.0.0",
    "@fortawesome/free-solid-svg-icons": "^6.0.0",
    "@fortawesome/react-fontawesome": "^0.1.17",
    "@fortawesome/react-native-fontawesome": "^0.3.0",
    "@native-html/iframe-plugin": "^2.6.1",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-navigation/bottom-tabs": "^6.5.2",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/stack": "^6.0.7",
    "@shopify/flash-list": "1.4.3",
    "@tanstack/react-query": "^4.19.1",
    "@types/react": "~18.2.14",
    "dayjs": "^1.11.5",
    "expo": "49",
    "expo-apple-authentication": "~6.1.0",
    "expo-application": "~5.3.0",
    "expo-asset": "~8.10.1",
    "expo-auth-session": "~5.0.2",
    "expo-build-properties": "~0.8.3",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.4.12",
    "expo-file-system": "~15.4.5",
    "expo-font": "~11.4.0",
    "expo-image-picker": "~14.3.2",
    "expo-linking": "~5.0.2",
    "expo-media-library": "~15.4.1",
    "expo-navigation-bar": "~2.3.0",
    "expo-random": "~13.2.0",
    "expo-secure-store": "~12.3.1",
    "expo-sharing": "~11.5.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "~0.18.19",
    "firebase": "^9.15.0",
    "lodash": "^4.17.21",
    "node-fetch": "2.6.1",
    "prop-types": "^15.7.2",
    "expo-web-browser": "~12.3.2",
    "randombytes": "^2.1.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.40.0",
    "react-merge-refs": "^1.1.0",
    "react-native": "0.72.6",
    "react-native-calendars": "^1.1293.0",
    "react-native-check-version": "^1.1.1",
    "react-native-crypto": "^2.2.0",
    "react-native-device-info": "^10.6.0",
    "react-native-draggable-flatlist": "^4.0.1",
    "react-native-draglist": "^3.4.0",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-get-random-values": "~1.9.0",
    "react-native-image-viewing": "^0.2.2",
    "react-native-indicators": "^0.17.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-modalize": "^2.1.1",
    "react-native-popup-menu": "^0.15.12",
    "react-native-portalize": "^1.0.7",
    "react-native-progress": "^5.0.0",
    "react-native-purchases": "^7.3.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-reanimated-carousel": "^3.3.0",
    "react-native-render-html": "^6.3.4",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-shadow-2": "^7.0.6",
    "react-native-svg": "13.9.0",
    "react-native-swipeable-item": "^2.0.9",
    "react-native-toast-message": "^2.1.5",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-web": "~0.19.6",
    "react-native-webview": "^11.6.2",
    "typescript": "^5.1.6",
    "uuid": "^8.3.2",
    "wpapi": "^1.2.2"
  },`

**Comment by miteshdevg** [comment]
> same issue, i think this issue is due to, "react-native-webview"

i have used webview in my project,i think your right 
if you get solution please share with me.

**Comment by Parth0902** [comment]
> > same issue, i think this issue is due to, "react-native-webview"
> 
> I have used Webview in my project, i think you are right if you get a solution please share it with me.

I am facing similar issue have you found any solution?

**Comment by miteshdevg** [comment]
> > > same issue, i think this issue is due to, "react-native-webview"
> > 
> > 
> > I have used Webview in my project, i think you are right if you get a solution please share it with me.
> 
> I am facing similar issue have you found any solution?

Yes i got solution
Please check you build log existing any library name 


i have resolve it

if anyone facing issue same like me so please check your expo dashboard error log and try to find library name and install library

in my case i have install
`"expo-modules-autolinking": "1.2.0",
`

**Comment by dimmyjay** [comment]
remove all unnessary packages then try npx expo-doctor and try  npx expo install --check

**Comment by bhavnagautam109** [comment]
hey, my problem is solved my making solve the logs error... suppose incompatiblity  check expo doctor then , other errorr  will definetely solve this problem

**Comment by abdelbari-messah** [comment]
> > Please help i am also stuck at this build error `Execution failed for task ':app:compileReleaseJavaWithJavac'.`
> 
> I solve this by removing expo-cli after I upgraded to expo SDK 48. as per the documentation, expo-cli is now part of SDK 48 internally I guess

thank you so much , this solution work for me, i m using SDK 53
