### ISSUE TITLE
EAS Build - package.json not included

### ISSUE THREAD

**Issue by andy-HM** [expo/eas-cli#1501]
### Build/Submit details page URL

https://expo.dev/accounts/development_heroes.media/projects/HeroesFromCupid/builds/55927672-e6e2-4116-ab8d-2279da5168a7

### Summary

I am running `eas build` for Android.  However, I am receiving the attached error in the EAS console.  

When I run `eas build:inspect --platform [ios|android] --stage archive --output ~/target/output/path --profile production` I am not seeing the package.json file included and I am unsure why.  I do have a package-lock.json file which is included but not the package.json file.

<img width="1108" alt="198755837-8152cabb-3cf7-4f55-9eaa-7ac04aa859d2" src="https://user-images.githubusercontent.com/74470025/199382856-d049f220-c8a1-4950-b714-e2fb158bef3c.png">

### Managed or bare?

Managed

### Environment

 `npx expo-env-info` output:

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.3.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.11.0 - /opt/homebrew/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    IDEs:
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      babel-preset-expo: ~9.2.0 => 9.2.0 
      expo: ^46.0.0 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.6
    Expo Workflow: managed

`expo doctor` Output:

WARNING: expo-cli has not yet been tested against Node.js v18.3.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  (for more info, run: npm why @expo/config-plugins)

### Error output

The only helpful error I am receiving is the attached error above in the EAS console.  

The only error reported in the CLI is:

Waiting for build to complete. You can press Ctrl+C to exit.
✖ Build failed

🤖 Android build failed:
Unknown error. See logs for more information.

### Reproducible demo or steps to reproduce from a blank project

1. Open a terminal in your project directory.
2. Run `eas build:inspect --platform [ios|android] --stage archive --output ~/target/output/path --profile production`
3. Navigate to the output and verify that package.json is included.

This is likely just an issue with my project but more documentation and clarity is needed on how files are included or excluded during the build process.  It's clear that gitignore / easignore are used for this but my package.json is not being ignored.  

My gitignore:

.expo/*
npm-debug.*
*.jks
*.p8
*.p12
*.key
*.mobileprovision
*.orig.*
web-build/
web-report/
.firebase/
.DS_Store
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplify-build-config.json
amplify-gradle-config.json
amplifytools.xcconfig

**Comment by wkozyra95** [comment]
Can you try adding 
```
  "cli": {
    "requireCommit": true
    ...
  },
 ```
 In you eas.json? It will use git directly to create clone of your project, so if package.json is committed it will also be uploaded to EAS.
 
Do you have any other gitignore files? e.g. in parent directories or maybe you have a global gitignore?
Are you using .easignore?
How does the structure of your repository look like? Is eas.json/package.json in the root of the repository or in subdirectory?.

**Comment by andy-HM** [comment]
Hello @wkozyra95, thanks for the reply.  Making the suggested change worked for me and took care of the missing package.json.  

I do not have any other gitignores nor a global gitignore.  I am also not using easignore either so it is still unclear to me what the CLI is doing when the "requireCommit" option is not included or set to false.  

The eas.json and the package.json are in a sub directory of my repository though.  Though there are other files along side the package.json that are included in the build so it seems to be random.
