### ISSUE TITLE
EAS build failed after upgrade to sdk47

### ISSUE THREAD

**Issue by gobhi** [expo/eas-cli#1513]
### Build/Submit details page URL

https://expo.dev/accounts/gobhi/projects/dmx/builds/b4b18fa6-24b1-4c3c-b761-3448f97c475f

### Summary

I've updated to SDK47 and now when doing preview or development builds, i get the error with Fastlane (see issue in build submit details page).  Below

### Managed or bare?

Bare

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.11.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - /opt/homebrew/bin/npm
      Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /Users/gobhi/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.3 => 47.0.3
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.7 => 0.18.10
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.8
    Expo Workflow: bare

---

WARNING: expo-cli has not yet been tested against Node.js v18.11.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

Expected package @expo/config-plugins@^5.0.2
Found invalid:
  @expo/config-plugins@2.0.4
  (for more info, run: npm why @expo/config-plugins)

### Error output

▸ { platform:iOS Simulator, id:E5FAE80A-C4BD-4BFE-A831-2F7049886894, OS:15.5, name:iPhone 13 Pro Max }
▸ { platform:iOS Simulator, id:E4D323B3-630D-4D28-A329-6870D721E3B2, OS:15.5, name:iPhone 13 mini }
▸ { platform:iOS Simulator, id:DB03CB85-009E-4017-8EBE-14EC01AE8FD2, OS:15.5, name:iPhone SE (3rd generation) }
▸ { platform:iOS Simulator, id:A147CC3C-E896-4D76-9012-878356117872, OS:15.5, name:iPod touch (7th generation) }
▸ resolved source packages:
$ xcodebuild -showBuildSettings -workspace ./CassiusX.xcworkspace -scheme CassiusX -configuration Debug
[stderr] 2022-11-10 11:51:09.112 xcodebuild[4167:12185] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
[stderr] 2022-11-10 11:51:09.113 xcodebuild[4167:12185] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
[stderr] 2022-11-10 11:51:09.175 xcodebuild[4167:12185] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated: failed at lookup with error 3 - No such process.}
[stderr] 2022-11-10 11:51:09.175 xcodebuild[4167:12185] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
[stderr] 2022-11-10 11:51:09.175 xcodebuild[4167:12185] XType: unable to make a connection to the font daemon!
[stderr] 2022-11-10 11:51:09.175 xcodebuild[4167:12185] XType: XTFontStaticRegistry is enabled as fontd is not available.
[stderr] --- xcodebuild: WARNING: Using the first of multiple matching destinations:
[stderr] { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
[stderr] { platform:iOS Simulat

### Reproducible demo or steps to reproduce from a blank project

`eas build --profile development --platform ios`

**Comment by dan-online** [comment]
I've hit the same error after updating to sdk 47, perhaps this is similar to #860?

**Comment by pranavtad** [comment]
I'm having the same issue — has anyone been able to resolve this?

**Comment by aaronsmulktis** [comment]
Same here :/

**Comment by wesvh** [comment]
same here, on android
