### ISSUE TITLE
EAS build failing for Expo 46 iOS when using @stripe/stripe-react-native@0.19.0 and latest ios image

### ISSUE THREAD

**Issue by jsindos** [expo/eas-cli#1514]
### Build/Submit details page URL

https://expo.dev/accounts/jsindos/projects/pop-f/builds/c20ace6e-c134-4ec9-9412-347f5a8f798e

### Summary

Hi, I have been successfully building iOS with no problems using EAS on Expo 46. I recently upgraded a dependency to a higher version than Expo 46 supports, which led me to the following error when attempting to build:

```
The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'Stripe' from project 'Pods')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoModulesCore' from project 'Pods')
```

I found out this was because the version of Xcode was not high enough on EAS servers, so set the following configuration in `eas.json`:

```
  "build": {
    "production": {
      "ios": {
        "image": "latest"
      }
    }
  },
```

I am now getting the following error and am completely stumped:

```
The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs
          /Users/expo/Library/Developer/Xcode/DerivedData/popf-dgvfpmvrphsxsfajfxmvysuerzrl/Build/Intermediates.noindex/ArchiveIntermediates/popf/IntermediateBuildFilesPath/Pods.build/ Release-iphoneos/FBReactNativeSpec.build/Script-46EB2E0001E620.sh
          (in target 'FBReactNativeSpec' from project 'Pods')

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.210.0                 |
| sdk         | iPhoneOS16.0.sdk        |
+-------------+-------------------------+
```

Does anyone know how to solve this? The builds work fine locally, and it is only since I upgraded this dependency that I have started getting this problem.

### Managed or bare?

bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 2022.02.28.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 13.4/13F17a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.3 
      expo: ~46.0.2 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 0.57.0
      expo-cli: 6.0.1
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Blank, bare project with the following dependency and `eas.json` should re-create the problem

`npm i @stripe/stripe-react-native@0.19.0`

```
  "build": {
    "production": {
      "ios": {
        "image": "latest"
      }
    }
  },
```

**Comment by dsokal** [comment]
It doesn't seem to be a problem with EAS. Check out the Xcode build logs phase. Download the file and scroll to the bottom.
<img width="1307" alt="Screenshot 2022-11-15 at 11 23 34" src="https://user-images.githubusercontent.com/5256730/201895591-242f3e10-2b9a-4d16-9b26-d95fc9a5f153.png">
<img width="951" alt="Screenshot 2022-11-15 at 11 23 27" src="https://user-images.githubusercontent.com/5256730/201895601-9a1fc20d-b91b-4586-92f8-1e2f8931e8d4.png">
