### ISSUE TITLE
Wrong app slug read from expo.conf.js

### ISSUE THREAD

**Issue by Lerosen** [expo/eas-cli#1530]
### Summary

Hi, I just tried to build a dev client using `eas build --profile development`. However I get the following error:
`rror: Project config: Slug for project identified by "extra.eas.projectId" (xx-yyy-zzz) does not match the "slug" field (xx_yyy_zzz).`.

I can confirm that the eas project matches with the one from the error message with the dashes. However, in my expo.conf.js the same slug is set with dashes so I don't know here the underscores come from.

I tried to rollback to 2.0.0 and with this version everything works fine. With version 2.6 or 2.7.1 the error occurs.

### Managed or bare?

managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.15.0 - C:\Program Files\nodejs\node.EXE       
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^46.0.0 => 46.0.17
      react: 18.0.0 => 18.0.0
      react-native: 0.69.4 => 0.69.4
    Expo Workflow: managed

### Error output

npm run build:dev

> build:dev
> eas build --profile development

√ Select platform » Android
    Error: Project config: Slug for project identified by "extra.eas.projectId" (cg-update-app) does not match the "slug" field (cg_update_app). Learn more: https://expo.fyi/eas-project-id

### Reproducible demo or steps to reproduce from a blank project

Create a project with dashes in the slug?

**Comment by dsokal** [comment]
You must have changed the slug at some point. 

I cannot repro the issue:
<img width="969" alt="Screenshot 2022-11-17 at 12 09 36" src="https://user-images.githubusercontent.com/5256730/202430946-f8f3158e-57fe-434b-8bee-3f7e39c9fc2b.png">

**Comment by flexbox** [comment]
Hey @Lerosen 
Have you tried Side by Side installation ?

https://github.com/flexbox/appjs-one#side-by-side-installation--appconfigjs

**Comment by Lerosen** [comment]
@dsokal The issue happened when the project already existed. Have you tried to do the build again after the initial creation?
For me, the issue is reproducible, just tried it again today.
![image](https://user-images.githubusercontent.com/20213986/202495563-0ea7d9b2-6ee1-43bb-b3b4-836f0acab5eb.png)

**Comment by xccelerate-dev** [comment]
I was facing the same issue while running `eas build`. You probably changed the project slug but still have the old `extra.eas.projectId` in your app.json. Remove the projectId and when you build your project again, eas will generate a new projectId for you

**Comment by rbpolim** [comment]
> I was facing the same issue while running `eas build`. You probably changed the project slug but still have the old `extra.eas.projectId` in your app.json. Remove the projectId and when you build your project again, eas will generate a new projectId for you

Work for me, thank you :)
