### ISSUE TITLE
EAS Cli CICD Build  can't link exist  project  Issue

### ISSUE THREAD

**Issue by fengwangjie** [expo/eas-cli#1534]
### Summary

prerequisite: 
1.  i use expo-token login 
2. config eas project id 
3. i use earthly ci framework
```
 extra: {
    eas: {
      projectId: "xxxxxx"
    },
  }
```

### Managed or bare?

RUN eas build -p android --non-interactive --profile preview

### Environment

EAS CLI 2.7.1 environment info:
    +package-android |     System:
    +package-android |       OS: Linux 5.15 Debian GNU/Linux 10 (buster) 10 (buster)
    +package-android |       Shell: 5.0.3 - /bin/bash
    +package-android |     Binaries:
    +package-android |       Node: 16.18.1 - /usr/local/bin/node
    +package-android |       Yarn: 1.22.19 - /usr/local/bin/yarn
    +package-android |       npm: 8.19.2 - /usr/local/bin/npm
    +package-android |     Utilities:
    +package-android |       Git: 2.20.1 - /usr/bin/git
    +package-android |     npmPackages:
    +package-android |       @expo/webpack-config: ^0.17.2 => 0.17.3
    +package-android |       expo: ^47.0.3 => 47.0.6
    +package-android |       expo-cli: ^6.0.8 => 6.0.8
    +package-android |       expo-updates: ~0.15.5 => 0.15.5
    +package-android |       react: 18.1.0 => 18.1.0
    +package-android |       react-dom: 18.1.0 => 18.1.0
    +package-android |       react-native: 0.70.5 => 0.70.5
    +package-android |       react-native-web: ~0.18.7 => 0.18.10
    +package-android |     npmGlobalPackages:
    +package-android |       eas-cli: 2.7.1
    +package-android |       expo-cli: 6.0.8
    +package-android |     Project workflow: managed

### Error output

EAS project not configured.
    +package-android *failed* |     Error: Must configure EAS project by running 'eas init' before this
    +package-android *failed* |     command can be run in non-interactive mode

### Reproducible demo or steps to reproduce from a blank project

https://ci.earthly.dev/logs?logId=2f025596-2884-4e66-81b6-1e8c633923aa

**Comment by wkozyra95** [comment]
>  Using EAS CLI without a version control system is not recommended, use this mode only if you know what you are doing.

It looks like you are using EAS_NO_VCS env, it's not recommended, if you don't need it you should avoid it.

> Generated eas.json

You should not generate that file on the fly, it should be committed to your repo.

Given that eas.json is missing I suspect that it's a CI misconfiguration on your side. Maybe you are running eas build in the wrong directory where app.json/eas.json do not exist?

**Comment by fengwangjie** [comment]
@wkozyra95  thanks！ as you said，i lose my eas.json file  in docker container !
