### ISSUE TITLE
[Android] React Native AppState is the making an infinite loop with EAS Build

### ISSUE THREAD

**Issue by seb-glanum** [expo/eas-cli#1536]
### Summary

My App builded with EAS Build has a strange issue.
I'm using the AppState functionnality from React Native, with putting an event listener to see any changes for the state of my app. I have an infinite loop and functionnality is switching between being in background and coming foreground events. I just open my app and see that there is an infinite loop with these two changes.

I think this is an issue with EAS Build because on dev mode with Expo Go and the App builded with Expo CLI (Classic Build), I don't have any issues !!

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
      Watchman: 2021.09.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
    npmPackages:
      expo: 45.0.6 => 45.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 2.6.0
      expo-cli: 6.0.6
    Expo Workflow: managed

Expected package @expo/config-plugins@^4.1.0
Found invalid:
  @expo/config-plugins@5.0.4
  @expo/config-plugins@5.0.4
  (for more info, run: npm why @expo/config-plugins)

### Reproducible demo or steps to reproduce from a blank project

Very simple :

1/ Take the example in React Native Docs to listen to App changes ==> https://reactnative.dev/docs/appstate

```import React, { useRef, useState, useEffect } from "react";
import { AppState, StyleSheet, Text, View } from "react-native";

const AppStateExample = () => {
  const appState = useRef(AppState.currentState);
  const [appStateVisible, setAppStateVisible] = useState(appState.current);

  useEffect(() => {
    const subscription = AppState.addEventListener("change", nextAppState => {
      if (
        appState.current.match(/inactive|background/) &&
        nextAppState === "active"
      ) {
        console.log("App has come to the foreground!");
      }

      appState.current = nextAppState;
      setAppStateVisible(appState.current);
      console.log("AppState", appState.current);
    });

    return () => {
      subscription.remove();
    };
  }, []);

  return (
    <View style={styles.container}>
      <Text>Current state is: {appStateVisible}</Text>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});

export default AppStateExample;```

2/ Build your app with Expo Classic Build and EAS.

3/ See the differences with Expo Go Dev, Expo build classic and EAS !

**Comment by kbrandwijk** [comment]
It seems the infinite loop is caused by always calling `setAppStateVisible(appState.current);`, which causes a re-render, which triggers the `useEffect`, etc.

**Comment by seb-glanum** [comment]
@kbrandwijk Yes it causes re-render because it switching to active state and background state events indefinitely from the AppState's eventListener.

What I am facing here is that with EAS Build, this functionnality is unstable on Android, the value is changing all the time between active and background values. I don't have this issue with Classic Build and dev mode with Expo Go. With same code, this issue is not on iOS. I believe this an EAS build issue.

**Comment by dsokal** [comment]
Try building your project locally. Run prebuild and build it in Android Studio. There isn't anything special about EAS Build. It's basically doing the same thing.
