### ISSUE TITLE
expo-firebase-analytics not working with EAS UPDATE, Working fine with EXPO PUBLISH

### ISSUE THREAD

**Issue by viveksc1994** [expo/eas-cli#1537]
### Summary

After switching to 'eas update' facing an issue with firebase. Working fine with 'expo publish'. (Working fine in local env.)

### Managed or bare?

Managed

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7678000
    npmPackages:
      expo: 46.0.17 => 46.0.17
      react: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
    Expo Workflow: managed

### Error output

"Error: Firebase is not configured. Ensure that you have configured 'google-services.json' correctly."

### Reproducible demo or steps to reproduce from a blank project

Here is the minimal reproducible example - https://github.com/viveksc1994/expo_46_firebase_standalone_apk

Please add below details of yours

- In app.json file
  1. expo.extra.eas.projectId
  2. expo.updates.url
  3. expo.web.firebase - your own settings
- google-services.json - your own settings

**Now run in local env**
```
npm install
npx expo start -c
```
It is working fine in local env. (Open app and click on 'Please click Here', Showing firebase log in console).

**Check with eas update**

``npx eas update --branch dev --message 'published dev channel'``

When you scan QR and open app, and click on 'Please click Here'. It is showing error as per above screenshot.

**Check with classic publish method**

Remove below two properties from app.config
  1. expo.runtimeVersion
  2. expo.updates.url
 
Command to publish

``expo publish --release-channel dev``

When you scan QR and open app, and click on 'Please click Here'. It is not throwing any error.

**Comment by viveksc1994** [comment]
I have raised same issue with expo - [https://github.com/expo/expo/issues/20166](url)

**Comment by viveksc1994** [comment]
If anyone facing same issue, then please ref. this example - https://github.com/viveksc1994/expo_46_react_native_firebase
I have created this demo to use react-native-firebase with expo, expo go and eas update.

**Comment by quinlanj** [comment]
It looks like you've been able to get this working with `react-native-firebase`, and since we no longer support `expo-firebase-*` as mentioned [here](https://github.com/expo/expo/issues/20166#issuecomment-1325432829), I'll be closing this issue!
