### ISSUE TITLE
eas build: hermes requires libicu-dev on the OS for building [rn new architecture]

### ISSUE THREAD

**Issue by Joh4nnesHartl** [expo/eas-cli#1538]
### Build/Submit details page URL

https://expo.dev/accounts/johanneshartl/projects/fiskalcheck/builds/7959e10b-8e40-4642-a353-82c50dd94b54

### Summary

When trying to build an app on eas-build, the image is missing the required ICU libraries for hermes. When using the new architecture Hermes is mandatory => new architecture won't work with `eas build`

"To avoid substantially increasing the binary size of Hermes, we decided to implement it with another strategy by consuming and mapping the ICU facilities provided by the libraries included in the operating systems, at the cost of some (often minor) variance in behaviors across platforms." - https://reactnative.dev/blog/2021/10/26/toward-hermes-being-the-default

### Managed or bare?

bare

### Environment

`npx expo-env-info`:
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.14 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/projects/fiskalcheck/frontend/node_modules/.bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 30, 31
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0
    npmPackages:
      expo: ^47.0.7 => 47.0.7 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: bare
```

`expo doctor`:
```
Expected package @expo/config-plugins@^5.0.2

Found invalid:
  @expo/config-plugins@5.0.1
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@^5.0.5
Found invalid:
  @expo/prebuild-config@5.0.3
  (for more info, run: npm why @expo/prebuild-config)
```

### Error output

`Task ':ReactAndroid:hermes-engine:configureBuildForHermes'.`

```
[RUN_GRADLEW] CMake Error at CMakeLists.txt:523 (message):
[RUN_GRADLEW]   Unable to find ICU.
```
. . .

```
[RUN_GRADLEW] -- The following ICU libraries were not found:
[RUN_GRADLEW] --   uc (required)
[RUN_GRADLEW] --   i18n (required)
[RUN_GRADLEW] --   data (required)
[RUN_GRADLEW] --   uc (required)
[RUN_GRADLEW] -- Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY _ICU_REQUIRED_LIBS_FOUND) (Required is at least version "52")
[RUN_GRADLEW] -- Configuring incomplete, errors occurred!
```

### Reproducible demo or steps to reproduce from a blank project

- setup eas bare workflow project with RN-0.75
- add expo-localization & i18n (i18next)
- enable new architecture 
- run `eas build --platform android`

**Comment by wkozyra95** [comment]
You can install it in `eas-build-pre-install` hook, I'm not sure if all those packages are necessary, but we install those when building Expo Go
```
  sudo apt-get -y update
  sudo apt-get -y install icu-devtools libicu66 libicu-dev
```

https://github.com/expo/expo/blob/main/apps/eas-expo-go/package.json#L11
https://github.com/expo/expo/blob/main/apps/eas-expo-go/scripts/eas-build-pre-install.sh#L9

**Comment by Joh4nnesHartl** [comment]
@wkozyra95 
no permissions to install apt packages when running the pre-install script
![image](https://user-images.githubusercontent.com/54881042/203780778-6b7b4e53-c43a-40f0-bb62-b732adf3a820.png)

**Comment by wkozyra95** [comment]
this is not about sudo persmission, your script file does not have execute permission. You need to run 
`chmod +x ./scripts/eas-buld-pre-install.sh` locally and build again

**Comment by Joh4nnesHartl** [comment]
Shouldn't this be mentioned somewhere in the docs for setting up a bare-app using hermes on eas? or be installed on the worker everytime when 
```
"jsEngine": "hermes",
```
has been set?

**Comment by wkozyra95** [comment]
We plan to preinstall those dependencies on bulder instances, but at this point, RN new architecture is not officially supported yet.

**Comment by Joh4nnesHartl** [comment]
installing lib-icu in the pre-install script resolves the issue for me:
```
#!/usr/bin/env bash

if [ "$EAS_BUILD_PLATFORM" = "android" ]; then
  sudo apt-get -y install libicu-dev
fi
```
when is it planned to support RN new arch on eas? It is at least partway supported in the new SDK version (47).

**Comment by wkozyra95** [comment]
We don't have a date for official support, but the missing ICU should be added after the weekend.
