### ISSUE TITLE
EAS channel:delete | [GraphQL] Unexpected server error 

### ISSUE THREAD

**Issue by ValentinLevier** [expo/eas-cli#1544]
## eas channel:delete error

while i am trying to delete a channel via the cli: ```eas channel:delete <CHANNEL_NAME>``` it throws me an GraphQL error: 
``` [GraphQL] Unexpected server error (Expo error ID: XXXXXXX)```. 

**It seems that this error appears only when the channel has linked builds.**

### Expected behavior
it should delete the associated channel. 

### Managed or bare?

bare

### npx expo-env-info
```
 System:
      OS: macOS 12.4
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.3.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: 0.18.9 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.7.1
    Expo Workflow: managed
```

### Error output

CombinedError: [GraphQL] Unexpected server error (Expo error ID: b3990ae1-45b3-4dbf-8a8b-67046b26ced7).

### Reproducible demo or steps to reproduce from a blank project

1. create a channel (```eas channel:create CHANNEL```)
2. Make a build with a profile associated to this channel (```eas build --profile=PROFILE_ASSOCIATED_TO_THE_CHANNEL```)
3. try to delete the channel via the cli (```eas channel:delete <CHANNEL_NAME>```)

**Comment by baby230211** [comment]
facing the same issue

**Comment by edi** [comment]
Same issue here. Channel is not linked to any branch.

**Comment by whybtech** [comment]
Did you tried to delete your build before deleting the channel ?

**Comment by edi** [comment]
Same issue here. Tried removing the linked branch first, same error.

**Comment by quinlanj** [comment]
We've amended the error message to be more helpful when deleting channels. If you have a build that is subscribed to the channel you are trying to delete, the error message will tell you how to filter your builds by channel, then delete them (https://expo.fyi/delete-build)

**Comment by ValentinLevier** [comment]
> We've amended the error message to be more helpful when deleting channels. If you have a build that is subscribed to the channel you are trying to delete, you'll need to remove those builds before you can remove the channel. The error message will tell you how to filter your builds by channel, then delete them (https://expo.fyi/delete-build)

Thank you for your answer.
Since we can have hundreds of build attached to a specific channel, I am concerned about deleting those ones by hand on the UI as it can become a time-consumming task.

As far as i know, the eas-cli does not provide such a way to delete builds. I think it could be a must-have. 

Is there another way (e.g: an eas API, ...) to automate the process of deleting builds ?

**Comment by cdgmx** [comment]
agree with @ValentinLevier, sometimes we have a lot of native changes that requires multiple builds.
