### ISSUE TITLE
eas build fails at install dependencies

### ISSUE THREAD

**Issue by Arnav7501** [expo/eas-cli#1545]
### Build/Submit details page URL

https://expo.dev/accounts/arnav_123/projects/lbnapp_new/builds/b2c6f5bb-ba66-4927-ad49-680ae6b9c3df

### Summary

My program works fine when running with my environment. However, when eas runs "npm install" I get the dependency error [stderr] npm ERR! code ERESOLVE
[stderr] npm ERR! ERESOLVE could not resolve
[stderr] npm ERR! 
[stderr] npm ERR! While resolving: aws-amplify-react-native@6.0.8
[stderr] npm ERR! Found: graphql@16.6.0

I don't think the problem is with aws amplify, because i had the same dependency error for another module, when i deleted it now this dependency error comes up. I've tried everything, using legacy peer deps, force, deleting package-lock.json and node_modules and rebuilding, but the error just will not go away.

### Managed or bare?

Bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      npm: 9.1.2 - ~/lbnapp_new/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.19 => 0.16.19 
      expo: ^46.0.16 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.8
    Expo Workflow: managed

### Error output

Running "npm install" in the root dir of your repository 
[stderr] npm
[stderr] WARN ERESOLVE overriding peer dependency
[stderr] npm
[stderr] WARN While resolving: @urql/exchange-retry@0.3.0
[stderr] npm WARN
[stderr] Found: graphql@16.6.0
[stderr] npm WARN node_modules/graphql
[stderr] npm WARN   graphql@"^16.6.0" from the root project
[stderr] npm WARN
[stderr] 3 more (@graphql-typed-document-node/core, @urql/core, graphql-tag)
[stderr] npm WARN 
[stderr] npm WARN Could not resolve dependency:
[stderr] npm WARN peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0" from @urql/exchange-retry@0.3.0
[stderr] npm WARN node_modules/@urql/exchange-retry
[stderr] npm WARN   @urql/exchange-retry@"0.3.0" from @expo/cli@0.3.2
[stderr] npm WARN   node_modules/@expo/cli
[stderr] npm WARN 
[stderr] npm
[stderr] WARN Conflicting peer dependency: graphql@15.8.0
[stderr] npm WARN node_modules/graphql
[stderr] npm WARN   peer graphql@"^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0" from @urql/exchange-retry@0.3.0
[stderr] npm WARN   node_modules/@urql/exchange-retry
[stderr] npm WARN     @urql/exchange-retry@"0.3.0" from @expo/cli@0.3.2
[stderr] npm WARN     node_modules/@expo/cli
[stderr] npm ERR! code ERESOLVE
[stderr] npm ERR! ERESOLVE could not resolve
[stderr] npm ERR! 
[stderr] npm ERR! While resolving: aws-amplify-react-native@6.0.8
[stderr] npm ERR! Found: graphql@16.6.0
[stderr] npm ERR! node_modules/graphql
[stderr] npm ERR!   graphql@"^16.6.0" from the root project
[stderr] npm ERR!   peer graphql@"^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 || ^16.0.0" from @graphql-typed-document-node/core@3.1.1
[stderr] npm ERR!   node_modules/@graphql-typed-document-node/core
[stderr] npm ERR!     @graphql-typed-document-node/core@"^3.1.0" from @urql/core@2.3.6
[stderr] npm ERR!     node_modules/@urql/core
[stderr] npm ERR!       @urql/core@"2.3.6" from @expo/cli@0.3.2
[stderr] npm ERR!       node_modules/@expo/cli
[stderr] npm
[stderr] ERR!         @expo/cli@"0.3.2" from expo@46.0.17
[stderr] npm ERR!         node_modules/expo
[stderr] npm ERR!       1 more (@urql/exchange-retry)
[stderr] npm ERR!   2 more (@urql/core, graphql-tag)
[stderr] npm ERR! 
[stderr] npm ERR! Could not resolve dependency:
[stderr] npm ERR! peer graphql@"^14.0.0" from aws-amplify-react-native@6.0.8
[stderr] npm ERR! node_modules/aws-amplify-react-native
[stderr] npm ERR!   aws-amplify-react-native@"^6.0.5" from the root project
[stderr] npm ERR! 
[stderr] npm ERR! Conflicting peer dependency: graphql@14.7.0
[stderr] npm ERR! node_modules/graphql
[stderr] npm ERR!   peer graphql@"^14.0.0" from aws-amplify-react-native@6.0.8
[stderr] npm ERR!   node_modules/aws-amplify-react-native
[stderr] npm ERR!     aws-amplify-react-native@"^6.0.5" from the root project
[stderr] npm ERR! 
[stderr] npm ERR! Fix the upstream dependency conflict, or retry
[stderr] npm ERR! this command with --force, or --legacy-peer-deps
[stderr] npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
[stderr] npm ERR! 
[stderr] npm ERR! See /home/expo/.npm/eresolve-report.txt for a full report.
[stderr] 
[stderr] npm ERR! A complete log of this run can be found in:
[stderr] npm ERR!     /home/expo/.npm/_logs/2022-11-28T20_13_03_469Z-debug-0.log
npm exited with non-zero code: 1

### Reproducible demo or steps to reproduce from a blank project

unsure how you would reproduce

**Comment by shendric-lamar** [comment]
I have the same problem with different packages, I tried adding a "eas-build-pre-install" script in my package.json but that doesn't solve the issue...

**Comment by Arnav7501** [comment]
@shendric-lamar  tell me if you find a solution please, i just gave up

**Comment by andre-luiz1997** [comment]
I also have the same issue. I needed to override install dependencies with either --force or --legacy-peer-deps

**Comment by lanouvelleecole** [comment]
I have the same problem too, it's really annoying

**Comment by lanouvelleecole** [comment]
the command eas build fails because of dependency conflicts. How to run npm install --legacy-peer-deps instead of npm install,  during the build on expo.dev ?

**Comment by andre-luiz1997** [comment]
> the command eas build fails because of dependency conflicts. How to run npm install --legacy-peer-deps instead of npm install, during the build on expo.dev ?

That's exactly what I need to do, but I don't know how to with eas cli

**Comment by Arnav7501** [comment]
i seem to have found a temporary solution: install yarn and run yarn install, eas-cli then runs yarn install and it worked out for me. Make sure to save a copy though incase something goes wrong

**Comment by wkozyra95** [comment]
The issue started happening because the version of npm on eas changed.
- You can use yarn, it does not enforce peer dependencies.
- You can downgrade npm in eas-build-pre-install hook
- You can downgrade node via `node` field in eas.json build profile (it will also downgrade npm)
- You can add `.npmrc` with `legacy-peer-deps=true` and commit it.

All of those are workarounds, the only proper fix is to fix your dependencies, to make sure all peer dependencies are satisfied.

**Comment by maulik9211** [comment]
> The issue started happening because the version of npm on eas changed.
> 
> * You can use yarn, it does not enforce peer dependencies.
> * You can downgrade npm in eas-build-pre-install hook
> * You can downgrade node via `node` field in eas.json build profile (it will also downgrade npm) https://docs.expo.dev/build-reference/eas-json/#node
> * You can add `.npmrc` with `legacy-peer-deps=true` and commit it.
> 
> All of those are workarounds, the only proper fix is to fix your dependencies, to make sure all peer dependencies are satisfied.

The last one worked. Thank you.
You can add .npmrc with legacy-peer-deps=true and commit it.

**Comment by oladips772** [comment]
> > The issue started happening because the version of npm on eas changed.
> > 
> > * You can use yarn, it does not enforce peer dependencies.
> > * You can downgrade npm in eas-build-pre-install hook
> > * You can downgrade node via `node` field in eas.json build profile (it will also downgrade npm) https://docs.expo.dev/build-reference/eas-json/#node
> > * You can add `.npmrc` with `legacy-peer-deps=true` and commit it.
> > 
> > All of those are workarounds, the only proper fix is to fix your dependencies, to make sure all peer dependencies are satisfied.
> 
> The last one worked. Thank you. You can add .npmrc with legacy-peer-deps=true and commit it.

it worked for me too thanks

**Comment by lakshay1121** [comment]
> > The issue started happening because the version of npm on eas changed.
> > 
> > * You can use yarn, it does not enforce peer dependencies.
> > * You can downgrade npm in eas-build-pre-install hook
> > * You can downgrade node via `node` field in eas.json build profile (it will also downgrade npm) https://docs.expo.dev/build-reference/eas-json/#node
> > * You can add `.npmrc` with `legacy-peer-deps=true` and commit it.
> > 
> > All of those are workarounds, the only proper fix is to fix your dependencies, to make sure all peer dependencies are satisfied.
> 
> The last one worked. Thank you. You can add .npmrc with legacy-peer-deps=true and commit it.

Hey can you please tell where do we have to write legacy-peer-deps and include .npmrc

**Comment by jAndrew78** [comment]
> Hey can you please tell where do we have to write legacy-peer-deps and include .npmrc

I had the same question. Turns out, it's as simple as it sounds, though. 
Simply make a file in the base of your project named .npmrc
within the file type:
legacy-peer-deps=true

It's literally just one line, no quotes/nothing fancy.

You could also type the following in the terminal while in your project directory (which is what I did to see what happened):
npm config --location=project set legacy-peer-deps=true

Per the docs, location defaults to user, but I didn't want it effecting anything but this one project, and I saw someone mention it changed their global file without any flags, hence why I used the --location=project flag

references:
[https://github.com/npm/rfcs/discussions/283](url)
[https://docs.npmjs.com/cli/v9/commands/npm-config#location](url)
[https://docs.npmjs.com/cli/v9/commands/npm-config#set](url)

**Comment by dodyeid** [comment]
> The issue started happening because the version of npm on eas changed.
> 
> * You can use yarn, it does not enforce peer dependencies.
> * You can downgrade npm in eas-build-pre-install hook
> * You can downgrade node via `node` field in eas.json build profile (it will also downgrade npm) https://docs.expo.dev/build-reference/eas-json/#node
> * You can add `.npmrc` with `legacy-peer-deps=true` and commit it.
> 
> All of those are workarounds, the only proper fix is to fix your dependencies, to make sure all peer dependencies are satisfied.

Haha wow, that last one worked - genius! Thanks so much. So weird that this was needed. Do you know if this file might mess with future package installations? Or is it relatively harmless? I know that's a vague question...

**Comment by RohitKaushal7** [comment]
Hi, I am facing this issue with `pnpm`. I cant switch to yarn because I am using pnpm monorepo / workspaces. `legacy-peer-deps=true` didn't work for me.
```
- Node.js 16.18.1
- pnpm 7.0.0
- npm 8.1.2
- Expo CLI 6.0.0
```

**Comment by eatanga-git** [comment]
legacy-peer-deps=true did not work for me either.

my package json:
"expo": "^49.0.7",
"react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.3",

**Comment by Olalexy1** [comment]
> > Hey can you please tell where do we have to write legacy-peer-deps and include .npmrc
> 
> I had the same question. It's as simple as it sounds, though. Just make a file in the base of your project named .npmrc Within the file type: legacy-peer-deps=true
> 
> It's literally just one line, no quotes / nothing fancy.
> 
> You could also type the following in the terminal while in your project directory (which is what I did to see what happened): npm config --location=project set legacy-peer-deps=true
> 
> Per the docs, location defaults to user, but I didn't want it effecting anything but this one project, and I saw someone mention it changed their global file without any flags, hence why I used the --location=project flag
> 
> references: [npm/rfcs#283](https://github.com/npm/rfcs/discussions/283) https://docs.npmjs.com/cli/v9/commands/npm-config#set https://docs.npmjs.com/cli/v9/commands/npm-config#location

Thanks for this

**Comment by brentvatne** [comment]
the solution is described here:

https://github.com/expo/eas-cli/issues/1545#issuecomment-1331958946
