### ISSUE TITLE
Eas-Cli Managed Workflow - Cannot find 'expo-modules-autolinking' package in your project

### ISSUE THREAD

**Issue by mikefisher84** [expo/eas-cli#1552]
### Build/Submit details page URL

https://expo.dev/accounts/heir-jordan/projects/heir-mobile/builds/f5656dfe-d407-4b82-b603-d47aa21ed6f9

### Summary

I'm trying to do a an iOS build with EAS. My app is currently in the managed workflow and I do all local development and testing with Expo Go. 

When I run `eas build --platform ios` locally I get an error 
```
    Error: Cannot find 'expo-modules-autolinking' package in your project, make sure that you have 'expo' package installed
```

However when I run `eas build --platform android` I get no error what so ever and am able to run the build. 

My understanding is this is for Expo apps in the bare workflow but I'm confident I'm still in the managed workflow. I don't have any `ios` or `android` folders in my mobile app folder. 

```
app.config.ts      babel.config.js    eas.json           index.ts           metro.config.js    package.json       src                tsconfig.json
assets             coverage           import-aliases.js  jest.config.js     node_modules       readme.md          tailwind.config.js yarn-error.log
```

I should also mention this app is configured with a pnpm managed monorepo

### Managed or bare?

Managed 

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.11.0 - ~/.nodenv/versions/18.11.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.19.2 - ~/.nodenv/versions/18.11.0/bin/npm
      Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.6 => 47.0.6 
      metro: ^0.73.3 => 0.73.3 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.8
    Expo Workflow: managed
```

```
➜  mobile git:(main) expo doctor
WARNING: expo-cli has not yet been tested against Node.js v18.11.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)
* 
* 
```

### Reproducible demo or steps to reproduce from a blank project

1. `eas build --platform ios` 
2. receive error
```
 mobile git:(main) eas build --platform ios

    Error: Cannot find 'expo-modules-autolinking' package in your project, make sure that you have 'expo' package installed
```

**Comment by mikefisher84** [comment]
Edit I was able to resolve this issue by uninstalling `eas-cli` with `npm uninstall -g eas-cli` and reinstalling with `pnpm i -g eas-cli` I did notice I started having this issue when I updated to the latest `eas-cli` recently.

**Comment by kirtikapadiya** [comment]
@mikefisher84  I tried above solution but didn't work for me.

**Comment by stesvis** [comment]
> npm uninstall -g eas-cli

@kirtikapadiya did you find a solution?

**Comment by marcinjackowiak** [comment]
The only thing that worked for me was to do a clean install of all dependencies by running:
`npm ci`
This clears out node_modules and reinstalls all dependencies as defined in package-lock.json
https://docs.npmjs.com/cli/v9/commands/npm-ci

**Comment by FlaviaCohen** [comment]
Thank you @stesvis, I installed eas-cli in the project and it works now.
