### ISSUE TITLE
eas build local fails

### ISSUE THREAD

**Issue by maulik9211** [expo/eas-cli#1553]
### Summary

Background: I am slightly experienced full-stack developer but fairly new to React Native. I have no experience with Xcode and Android SDKs. I use eas build on expo's infrastructure. I am working on app with NFC capability so I constantly need to rebuild and install the app on physical iPhone device. Because I can't afford to buy priority build subscription for expo, I want to build the app on my MacBook Pro with M1 Pro chip.

Trials:
1. I tried upgrading SDK to v46 but It broke all my dependencies. I tried to fix them but it did not work, because underlying packages were not updated. So I had to revert to old dependencies.
2. I tried using "image" field in eas.json with different values provided in docs, but it did not make any difference. I think that was because my local machine has only one Xcode Build Tools installed.

If anyone can explain how to downgrade Xcode and handle it in "image" field in eas.json, it will be really helpful.

I tried to install Command_Line_Tools_for_Xcode_13.4 but i couldn't.
<img width="619" alt="Screenshot 2022-12-01 at 9 36 53 AM" src="https://user-images.githubusercontent.com/40969469/204963521-a53de014-4122-4ab5-9561-0abc4174945f.png">

### Managed or bare?

Managed (with expo-dev-client for nfc-manager package with plugin for native code)

### Environment

Output From `npx expo-env-info`
System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
      Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
npmPackages:
      expo: ~45.0.0 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
npmGlobalPackages:
      eas-cli: 2.8.0
      expo-cli: 6.0.8
Expo Workflow: managed

Output from `expo doctor`
🎉 Didn't find any issues with the project!

### Error output

Build failed
Starting from Xcode 14, resource bundles are signed by default, which requires setting the development team for each resource bundle target.
To resolve this issue, downgrade to an older Xcode version using the "image" field in eas.json, or upgrade to SDK 46 or higher.

### Reproducible demo or steps to reproduce from a blank project
`eas build --platform ios --local`

Because new projects will have Expo SDK > 45. This will not be reproducible.

**Comment by LucasSGomide** [comment]
Same issue here.
Can't upgrade to SDK 46 and can't build in SDK 45.

**Comment by bayramn** [comment]
"In a React Native Expo project, you can specify the version of Xcode that you want to use in the expo.ios.buildNumber field in the app.json file." - ChatGPT :)

**Comment by kodaraj** [comment]
@ maulik9211 Did you find any solution for this issue? 
I am also stuck on this issue and can't find any solution online.

**Comment by ymerdrengene** [comment]
any news on this?

**Comment by mwasiel78** [comment]
Same issue. Has anyone found a solution? Thanks.

**Comment by zthornto** [comment]
+1 on this.

Also, apologize if I'm just naive (I am not a proper app developer by any means), but has anyone figured out where you actually define an `image` in the eas config?

Borderline frustrating that the docs have an [entire section](https://docs.expo.dev/build/eas-json/#selecting-a-base-image) dedicated to it, but zero mention (as far as I can find) on where it actually lives within said config. `build`? `build.development`? `build.development.ios`? 

Appreciate any help.

**Comment by deepnothing** [comment]
> entire section

try this ` "base":{
      "ios":{
        "image":"macos-monterey-12.4-xcode-13.4"
      }
    },
    "production": {
      "extends":"base",
      "releaseChannel": "prod"
    },`

**Comment by ronsandova** [comment]
> > entire section
> 
> try this under build ` "base":{ "ios":{ "image":"macos-monterey-12.4-xcode-13.4" } }, "production": { "extends":"base", "releaseChannel": "prod" },`

It does't work -> same issue 

Asset validation failed (90725)
SDK version issue. This app was built with the iOS 15.5 SDK. All iOS and iPadOS apps submitted to the App Store must be built with the iOS 16.1 SDK or later, included in Xcode 14.1 or later.
