### ISSUE TITLE
Help to investigate why eas update not working

### ISSUE THREAD

**Issue by finom** [expo/eas-cli#1557]
### Summary

As far as I know this might be considered as a duplicate but none of the issues help how to debug the problem I'm describing. I run `eas update`, the command runs successfully but the app is not updating. I would be happy to investigate that but I can't even see logs in production. The app is published on TestFlight so far. Is there a way to see the logs? I've spend multiple days already and I hope you can help me to find a solution. Thank you!

### Managed or bare?

bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.0.1 - ~/.nvm/versions/node/v19.0.1/bin/node
      Yarn: 1.22.15 - /opt/homebrew/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v19.0.1/bin/npm
      Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.8 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      eas-cli: 2.7.1
      expo-cli: 6.0.8
    Expo Workflow: bare

--------------

Doctor: 🎉 Didn't find any issues with the project!

### Reproducible demo or steps to reproduce from a blank project

I don't know how to reproduce it.

Update:
There is what my billing page shows 
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/1082083/205159687-d59d2783-25a3-48b5-8265-ebb03ed745d1.png">

It looks like there was no even attempt to download the resources.

I also used Sentry to catch the problem. I've made sure that it works by throwing a random error but there is nothing about expo-asset or something like that.

**eas.json**

```json
{
  "cli": {
    "version": ">= 2.7.1"
  },
  "build": {
    "development": {
      "distribution": "internal",
      "android": {
        "gradleCommand": ":app:assembleDebug"
      },
      "ios": {
        "buildConfiguration": "Debug",
        "image": "latest"
      }
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}

```

**app.json**

```json
{
  "expo": {
    "name": "foo",
    "slug": "foo",
    "version": "1.0.8",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0,
      "url": "https://u.expo.dev/MY_PROJECT_ID"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.foo",
      "googleServicesFile": "./credentials/GoogleService-Info.plist",
      "buildNumber": "8"
    },
    "android": {
      "googleServicesFile": "./credentials/google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "package": "com.foo"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "expo-build-properties",
        {
          "ios": {
            "useFrameworks": "static"
          }
        }
      ]
    ],
    "extra": {
      "eas": {
        "projectId": "MY_PROJECT_ID"
      }
    },
    "owner": "finom",
    "runtimeVersion": "1.0.0"
  }
}
```

**package.json**

```json
{
  "name": "foo",
  "version": "0.0.0-no-version",
  "scripts": {
    "start": "cross-env NODE_OPTIONS=--openssl-legacy-provider expo start --tunnel --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "lint": "eslint --ext .ts,.js,.tsx --fix ./",
    "check-types": "tsc --noemit",
    "reinstall": "rm -rf node_modules yarn.lock && yarn",
    "test": "npm run lint && npm run check-types",
    "pod-install": "cd ios && arch -x86_64 pod install && cd ..",
    "pod-update": "cd ios && arch -x86_64 pod update && arch -x86_64 pod install && cd ..",
    "upgrade": "npx npm-check-updates -u && yarn",
    "submit": "expo prebuild && eas build --clear-cache --auto-submit",
    "update": "eas update --auto"
  },
  "dependencies": {
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@react-native-firebase/analytics": "^16.4.6",
    "@react-native-firebase/app": "^16.4.6",
    "@react-native-firebase/auth": "^16.4.6",
    "@react-native-firebase/firestore": "^16.4.6",
    "@react-native-firebase/storage": "^16.4.6",
    "@react-native-google-signin/google-signin": "^8.2.1",
    "@react-navigation/native": "^6.0.16",
    "@react-navigation/stack": "^6.3.7",
    "@sentry/react-native": "4.10.1",
    "base-64": "^1.0.0",
    "expo": "~47.0.8",
    "expo-asset": "~8.6.2",
    "expo-av": "~13.0.2",
    "expo-build-properties": "~0.4.1",
    "expo-constants": "~14.0.2",
    "expo-file-system": "~15.1.1",
    "expo-in-app-purchases": "~14.0.0",
    "expo-localization": "~14.0.0",
    "expo-splash-screen": "~0.17.5",
    "expo-status-bar": "~1.4.2",
    "expo-updates": "~0.15.6",
    "i18n-js": "^4.2.0",
    "lodash": "^4.17.21",
    "parse-color": "^1.0.0",
    "react": "18.1.0",
    "react-dom": "18.2.0",
    "react-native": "0.70.5",
    "react-native-card-stack-swiper": "^1.2.5",
    "react-native-emoji-selector": "^0.2.0",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-google-mobile-ads": "^8.2.2",
    "react-native-iap": "^12.4.8",
    "react-native-modal": "^13.0.1",
    "react-native-popable": "^0.4.3",
    "react-native-reanimated": "~2.13.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.2",
    "react-native-share": "^8.0.0",
    "react-native-typography": "^1.4.1",
    "react-native-ui-lib": "^6.25.0",
    "react-native-vector-icons": "^9.2.0",
    "react-use-promise": "^0.5.0",
    "use-change": "^1.0.9",
    "weighted": "^1.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.5",
    "@react-native/polyfills": "^2.0.0",
    "@types/base-64": "^1.0.0",
    "@types/fs-extra": "^9.0.13",
    "@types/gapi": "^0.0.43",
    "@types/gapi.auth2": "^0.0.56",
    "@types/gapi.client.sheets": "^4.0.20201030",
    "@types/i18n-js": "^3.8.3",
    "@types/lodash": "^4.14.191",
    "@types/parse-color": "^1.0.1",
    "@types/react": "~18.0.25",
    "@types/react-native": "~0.70.7",
    "@types/react-native-vector-icons": "^6.4.12",
    "@typescript-eslint/eslint-plugin": "^5.45.0",
    "@typescript-eslint/parser": "^5.45.0",
    "cross-env": "^7.0.3",
    "eslint": "^8.28.0",
    "eslint-config-airbnb": "19.0.4",
    "eslint-config-airbnb-typescript": "^17.0.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-react": "^7.31.11",
    "eslint-plugin-react-hooks": "^4.6.0",
    "typescript": "^4.9.3"
  },
  "private": true
}
```

**Comment by evenSosaAkido** [comment]
I'm having the exact same problem. `eas update` command works well. Everything looks good in the cli and dashboards but the app just doesn't get the update

**Comment by wkozyra95** [comment]
@finom You need to specify `channel` in eas.json build profile, otherwise, it assumes that you are on classic updates.

**Comment by evenSosaAkido** [comment]
@finom I got this solved. As @wkozyra95 said. The channel needs to be specified in the eas.json. 

I already had that but what fixed for me was removing this line from `android/app/src/main/AndroidManifest.xml` 

```
<meta-data android:name="expo.modules.updates.EXPO_UPDATES_RELEASE_CHANNEL" android:value="qa"/>
```

And also removing this line from `ios/<appname>/Supporting/Expo.plist`
```
    <key>EXUpdatesReleaseChannel</key>
    <string>qa</string>
```

**Comment by finom** [comment]
@wkozyra95 @evenSosaAkido you've saved my day! thank you very much:

```json
"production": {
  "channel": "main"
}
```

(main is the git branch name)

But I still think the CLI at least should warn about that and the issue isn't resolved in general.

**Comment by maniac-tech** [comment]
@finom as per the expo eas official documentation, `channel` is not related to git branches in any way. Doc I'm referring to: [Link](https://docs.expo.dev/eas-update/how-eas-update-works/#distributing-builds)

Quote from doc:

```
Channel: The channel is a name we can give to multiple builds to identify them easily.
It is defined in eas.json. For instance, we may have an Android and an iOS build with 
a channel named "production", while we have another pair of builds with a channel 
named "staging". Then, we can distribute the builds with the "production" channel 
to the public app stores, while keeping the "staging" builds on the Play Store Internal 
Track and TestFlight. Later when we publish an update, we can make it available to 
the builds with the "staging" channel first; then once we test our changes, we can 
make the update available to the builds with the "production" channel.

**Comment by amitava82** [comment]
I'm facing same issue. I'm using managed workflow. My last update on 7th Feb worked without any problems. I pushed another update yesterday but it isn't reflected on iOS or Android app. There hasn't been any change to my environment.

**Comment by amitava82** [comment]
OK I figured, I had excused free update limits. Make sure you check your plan 😄 
Visiting the update url can give you the hint.

**Comment by vicentepirozzi** [comment]
Hey @amitava82, i am facing the same issue and suspect maybe for exceeding free updates limits, but I didnt see anything pointing to that in the update url. Could you be more specific about how you figured out that was the problem. Thx!

**Comment by amitava82** [comment]
@vicentepirozzi If you go to update url, for example [here](https://u.expo.dev/959e95b0-e4f8-11e7-bff4-3bc9a86198ca?runtime-version=exposdk:46.0.0&channel-name=prod&platform=android) is mine, it'll say free limit exceeded if you crossed the limit. Otherwise if everything is alright, it'll show the files manifest.

**Comment by douglowder** [comment]
It seems that the problems described here are resolved (making sure `channel` is defined in build profile, checking free updates limits). Closing.

**Comment by quicksilverr** [comment]
Hey Guys, did all of this still it ain't working for me.

**Comment by karimdakroury** [comment]
> It seems that the problems described here are resolved (making sure `channel` is defined in build profile, checking free updates limits). Closing.

@douglowder Hi, when creating a build i did not specify any channel or branch but when i try to update it is asking for them. What should i do?

**Comment by bharathy-kannan** [comment]
Hi, 
I am using a bare workflow and recently trying out eas updates as I want to move away from codepush. I am on a free plan and I did an eas build and pushed my version. Now I made a small change to my code and pushed my updates. All in development channel and build. Now in my simulator/phone, I don't see any updates. I have been searching for answers for the past 2 days and I am stuck. My plan still has free builds and here is my json. 
`{
  "cli": {
    "version": ">= 10.2.4"
  },
  "build": {
    "development": {
      "developmentClient": false,
      "distribution": "internal",
      "channel": "development"
    },
    "preview": {
      "distribution": "internal",
      "channel": "preview"
    },
    "staging": {
      "distribution": "internal",
      "channel": "staging"
    },
    "production": {
      "channel": "production"
    }
  },
  "submit": {
    "production": {}
  }
}
`

**Comment by speedtreammanga** [comment]
Im trying to update my production build, but it does not work.

I am running `eas update -p ios --channel production -m "my message..."`.

I have both a `.env` and `.env.production` at the root of the project.

My `eas.json` looks something like this:
```json
{
  ...
  "build": {
    ...
    "production": {
      "distribution": "store",
      "channel": "production",
      "env": {...}
    }
  }
```
Before running eas update I bumped the version in `app.json`.

My phone does not download the update though and I haven't reach the free plan limit yet.

**Comment by CledirFL** [comment]
@speedtreammanga did you find the solutions?

**Comment by itwela** [comment]
lol so we all just can't get the update feature to work huh, maybe that means something
