### ISSUE TITLE
eas build No signing certificate "iOS Development" found

### ISSUE THREAD

**Issue by demc** [expo/eas-cli#1560]
### Build/Submit details page URL

https://expo.dev/accounts/niche/projects/niche/builds/1c038f88-80f2-403a-94a8-719731e0be31

### Summary

I have not been able to build for 1+ weeks. This suddenly started occurring and can not get any builds to complete.

### Managed or bare?

managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.19 - ~/niche/mobile/node_modules/.bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.1.0 => 9.1.0 
      expo: ^45.0.6 => 45.0.8 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 2.5.0
      expo-cli: 6.0.8
    Expo Workflow: bare

===

Expected package expo-modules-autolinking@~0.8.1 || ~0.9.0
Found invalid:
  expo-modules-autolinking@1.0.0
  expo-modules-autolinking@1.0.0
  (for more info, run: npm why expo-modules-autolinking)
Expected package @expo/config-plugins@^4.1.0
Found invalid:
  @expo/config-plugins@5.0.4
  @expo/config-plugins@5.0.4
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@^4.0.0
Found invalid:
  @expo/prebuild-config@5.0.7
  @expo/prebuild-config@5.0.7
  (for more info, run: npm why @expo/prebuild-config)

### Error output

▸ /Users/expo/workingdir/build/mobile/ios/Pods/Pods.xcodeproj: error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "36JYWX494D" with a private key was found. (in target 'expo-dev-menu-EXDevMenu' from project 'Pods')
▸ /Users/expo/workingdir/build/mobile/ios/Pods/Pods.xcodeproj: error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "36JYWX494D" with a private key was found. (in target 'expo-dev-launcher-EXDevLauncher' from project 'Pods')
▸ warning: Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
▸ /Users/expo/workingdir/build/mobile/ios/Pods/Pods.xcodeproj: error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "36JYWX494D" with a private key was found. (in target 'EXUpdates-EXUpdates' from project 'Pods')

### Reproducible demo or steps to reproduce from a blank project

1. This occurs when building our app: `eas build -p ios --profile production`
2. It happens every run both on eas servers and locally. 
3. I have replaced our Apple distribution certificates and profiles many times. 
4. No idea how to proceed.

**Comment by dsokal** [comment]
1. You actually have a bare workflow project, not managed one. See that the `prebuild` phase was skipped.
2. It seems you have your own `Gymfile`, EAS Build handles the credentials configuration by auto-generating the file. If you have your own Gymfile, you have to configure it on your own. See https://docs.expo.dev/build-reference/ios-builds/#default-gymfile
3. It's a project-specific issue and it doesn't have anything to do with EAS Build. If you cannot build your project locally, EAS Build cannot build it either.

**Comment by dimaportenko** [comment]
@demc did you find the solution?

**Comment by jaaywags** [comment]
Try the following

1. Go to Xcode - Preferences - Accounts - Manage Certificates
2. Click on the + at the bottom left, then Apple Distribution
3.If you do not have a certificate, add one (Apple Development), then click Done

You can also open the workspace in xcode, click on the project and go to Signing & Capabilities and then click the revoke button if there is one.
