### ISSUE TITLE
eas build failed in Configuring Xcode project

### ISSUE THREAD

**Issue by yzhe554** [expo/eas-cli#1574]
### Build/Submit details page URL

https://expo.dev/accounts/coop-poodle/projects/cheddar-staging/builds/1db4b5ea-504e-4a3e-9077-1cd93a83684b

### Summary

Build with `eas build --profile production --platform ios` for staging, it fails in Configuring Xcode project
```
Configuring Xcode project
Assigning provisioning profile '[COMPANY] Staging' (Apple Team ID: ******) to target '[COMPANY]staging'
Could not find target '[COMPANY]staging' in project.pbxproj
```
I tried to build dev environment, there was no errors.

### Managed or bare?

No

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
      Watchman: 2022.07.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 32
        Build Tools: 30.0.3, 32.0.0, 32.1.0, 33.0.0
        System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8512546
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    Expo Workflow: managed

expo doctor
Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5

### Error output

Configuring Xcode project
Assigning provisioning profile '[COMPANY] Staging' (Apple Team ID: ******) to target '[COMPANY]staging'
Could not find target '[COMPANY]staging' in project.pbxproj

### Reproducible demo or steps to reproduce from a blank project

`APP=staging eas build --profile production --platform ios`

**Comment by wkozyra95** [comment]
You probably did not add APP env in eas.json, so when app.config.js is evaluated on your machine it has a different name than what is evaluated on EAS worker because there is not env APP there.

**Comment by yzhe554** [comment]
Hi @wkozyra95 , thanks for your reply. This is my ess.json
```
{
  "cli": {
    "version": ">= 2.7.1"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "development-simulator": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "simulator": true
      }
    },
    "preview": {
      "distribution": "internal",
      "ios": {
        "simulator": true
      }
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
```

There are no errors if I build locally with `--local`. But we still want to use the cloud build as that's easier for writing CI up.

**Comment by yzhe554** [comment]
@wkozyra95 Thank you, I made it working by adding `env` variables into eas.json

**Comment by ogmzh** [comment]
@yzhe554 what do you mean you added the `env`variables to eas.json? what variables? how?
