### ISSUE TITLE
eas build ios simulator fails with Managed Workflow

### ISSUE THREAD

**Issue by sdinesmvc** [expo/eas-cli#1584]
### Build/Submit details page URL

https://expo.dev/accounts/renukacvbd/projects/AMS/builds/349ae2b5-d5fe-461c-8ee6-fb9f749ee44f

### Summary

I have the project in the managed workflow with the expo SDK version of 46 version. I am able to take eas android build with no issues. but I am trying to take an eas to build an ios simulator facing an error.

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      babel-preset-expo: ^9.2.2 => 9.2.2
      expo: ^46.0.0 => 46.0.17
      react: 18.0.0 => 18.0.0
      react-dom: 18.0.0 => 18.0.0
      react-native: 0.69.6 => 0.69.6
      react-native-web: ~0.18.7 => 0.18.10
    Expo Workflow: managed

### Error output

``
Please find the attached XCode log
[xcode-build-349ae2b5-d5fe-461c-8ee6-fb9f749ee44f.log](https://github.com/expo/eas-cli/files/10268105/xcode-build-349ae2b5-d5fe-461c-8ee6-fb9f749ee44f.log)
![error details](https://user-images.githubusercontent.com/70127380/208660800-64bc365a-a740-45ce-9388-f983834795b0.JPG)

### Reproducible demo or steps to reproduce from a blank project

I am unable to reproduce with a blank Project.

**Comment by sdinesmvc** [comment]
![error2](https://user-images.githubusercontent.com/70127380/208662057-8cbbbd12-ab1c-424d-9d7f-dc27fde5f260.JPG)
![error1 pg](https://user-images.githubusercontent.com/70127380/208662065-46005687-0bfa-41e0-b270-301d3eb39ea3.JPG)

Please find the error screenshot for more information.

**Comment by wkozyra95** [comment]
try adding `ios: {image: latest}` in eas.json build profile
https://docs.expo.dev/build-reference/eas-json/#image-1

**Comment by sdinesmvc** [comment]
> try adding `ios: {image: latest}` in eas.json build profile https://docs.expo.dev/build-reference/eas-json/#image-1
Now I got 2 new errors, please help with this.
![error-2-2](https://user-images.githubusercontent.com/70127380/208690020-ff47a311-dc9b-47c3-aa04-2b54d1548605.JPG)

![error-2-3](https://user-images.githubusercontent.com/70127380/208690011-5ef7a891-f42a-4f19-a6c8-c071c8a1822b.JPG)

**Comment by wkozyra95** [comment]
Maybe try setting the image to `macos-monterey-12.6-xcode-14.0` instead
or
Remove the image field from eas.json, and try downgrading expo-camera to 12.3.0

**Comment by sdinesmvc** [comment]
it is working setting the image to macos-monterey-12.6-xcode-14.0.
