### ISSUE TITLE
Build failed tar exited with non-zero code: 1

### ISSUE THREAD

**Issue by montanojd** [expo/eas-cli#1592]
### Build/Submit details page URL

https://expo.dev/accounts/deisyapp/projects/webos2/builds/e8aa60a1-8c60-439a-b09e-3df2aa248db7

### Summary

I have this error when compiling for iOS from Windows, I did not have this problem with expo build: ios
[stderr] __MACOSX/src/components/adMob/ads/._interstitialAds.js: Truncated tar archive
[stderr] tar: Error exit delayed from previous errors.
tar exited with non-zero code: 1

### Managed or bare?

Managed

### Environment

 System:
      OS: Windows 10 10.0.19041
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ~47.0.9 => 47.0.9
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.7 => 0.18.10
    Expo Workflow: managed

### Error output

[stderr] __MACOSX/src/components/adMob/ads/._interstitialAds.js: Truncated tar archive
[stderr] tar: Error exit delayed from previous errors.
tar exited with non-zero code: 1

### Reproducible demo or steps to reproduce from a blank project

[stderr] __MACOSX/src/components/adMob/ads/._interstitialAds.js: Truncated tar archive
[stderr] tar: Error exit delayed from previous errors.
tar exited with non-zero code: 1

**Comment by Amankumar1997** [comment]
you can fix this issue by removing __MACOSX folder and rebuild the app
