### ISSUE TITLE
Build issues adding Stripe w/ Apple Pay to ESA Build project

### ISSUE THREAD

**Issue by edotappstore** [expo/eas-cli#1594]
### Build/Submit details page URL

https://expo.dev/accounts/edotappstore/projects/BrainstormApp/builds/23d9f6da-0b9f-49b2-bff2-f72175ee4c1e

### Summary

Hi 
I am trying to enable Apple pay in my expo app with EAS build.

I have enabled Apple Pay capabilities in developer account along with marchantiid and certificate for payment processing.

![image](https://user-images.githubusercontent.com/98312418/209794178-100ae877-b63c-40cf-8e9f-555fd6ac8255.png)

And when i run the eas build command i.e. eas build --profile development --platform ios m getting following output 

![image](https://user-images.githubusercontent.com/98312418/209794459-95f944a7-4947-404a-8217-b5bdd74a2c43.png)

where Apple Pay payment Processing is getting disabled 

Am I missing any step or is there any extra configuration needs to be done from Apple Developer site?

Thank you

### Managed or bare?

Managed

### Environment

expo doctor
🎉 Didn't find any issues with the project!

after executing the npx expo-env-info command getting below error
![image](https://user-images.githubusercontent.com/98312418/209808852-a976cdbe-8c19-48f8-9417-788424e938f7.png)

### Reproducible demo or steps to reproduce from a blank project

Followed stripe documentation to configure in expo app
https://stripe.com/docs/refunds?dashboard-or-api=api#destination

**Comment by edotappstore** [comment]
Fixed By adding
```
"entitlements": {
        "com.apple.developer.in-app-payments": [
          "merchant.com.merchantID"
        ]
      }
```

**Comment by dhruv-bindra** [comment]
I'm running into the same issue!
1) Where did you add this?
2) Do I replace "merchantID" with my specific merchantID?

**Comment by hayelom123** [comment]
I'm running into the same issue!

Where did you add this?
Do I replace "merchantID" with my specific merchantID?

**Comment by hayelom123** [comment]
<img width="764" alt="image" src="https://github.com/expo/eas-cli/assets/70315287/e5bd2d88-d8b1-4b0b-bb01-f5e79971704d">

**Comment by hayelom123** [comment]
> Fixed By adding
> 
> ```
> "entitlements": {
>         "com.apple.developer.in-app-payments": [
>           "merchant.com.merchantID"
>         ]
>       }
> ```

in which file are you adding this code. app.json or eas

**Comment by garymc-MO** [comment]
> > Fixed By adding
> > ```
> > "entitlements": {
> >         "com.apple.developer.in-app-payments": [
> >           "merchant.com.merchantID"
> >         ]
> >       }
> > ```
> 
> in which file are you adding this code. app.json or eas

For anybody stumbling across this. Add in app.json or app.config.ts whichever setup you use
