### ISSUE TITLE
 Input is required, but stdin is not readable. Failed to display     prompt: Would you like to automatically create an EAS project for....?

### ISSUE THREAD

**Issue by smartbizlord** [expo/eas-cli#1608]
### Summary

I want to build the standalone app for deeplinking purposes but no matter which eas command I type in I get some error message.
it looks something like this:  Input is required, but stdin is not readable. Failed to display
    prompt: Would you like to automatically create an EAS project for
    @...?
I just only installed the eas cli 2 days ago

### Managed or bare?

Managed

### Environment

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/expo-dev-info - Not found
npm ERR! 404
npm ERR! 404  'expo-dev-info@latest' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2023-01-04T16_31_11_998Z-debug-0.log

- Finding all copies of expo-modules-autolinking
- Finding all copies of @expo/config-plugins
- Finding all copies of @expo/prebuild-config
- Finding all copies of @unimodules/core
- Finding all copies of @unimodules/react-native-adapter
- Finding all copies of react-native-unimodules
[17:32:50] 🎉 Didn't find any issues with the project!

### Reproducible demo or steps to reproduce from a blank project

<AuthProvider>
        <AuthModalScreen />
          <MainScreen />
</AuthProvider>

**Comment by dsokal** [comment]
1. What eas-cli version are you using?
2. Can you try reinstalling eas-cli and try again? This looks like an issue with yarn/npm installation.

**Comment by dsokal** [comment]
Closing because of the inactivity.

**Comment by KimGarza** [comment]
I see lots of talk about the eas-cli version but I saw then when version 2.0 was around people were still having this issue. And I saw one person mention upgrading to 2.1 now works but we are on 12.5... of eas-cli so I am not confident that is still the issue :(
