### ISSUE TITLE
 Error: Generating a new Keystore is not supported in --non-interactive      mode

### ISSUE THREAD

**Issue by HaxWallet** [expo/eas-cli#1612]
### Summary

✔ Using remote Android credentials (Expo server)
    Error: Generating a new Keystore is not supported in --non-interactive 
    mode
Error: Process completed with exit code 1.

building via github
i have keystore on my expo account, owner slug and project id on app.json is correct . 
getting this error anyway . many days trying , no progress 

### Managed or bare?

bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 3.3.0 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9014738
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

{
  "build": {
    "preview": {
      "android": {
        "buildType": "apk"
      }
    },
    "preview2": {
      "android": {
        "gradleCommand": ":app:assembleRelease"
      }
    },
    "preview3": {
      "developmentClient": true
    },
    "production": {}
  }
}

**Comment by dsokal** [comment]
Hi,
What's your use case for generating the keystore in CI?

**Comment by dsokal** [comment]
Closing because of the inactivity.
