### ISSUE TITLE
Support for latest Github Action shuld be added in a EAS Update .yml file

### ISSUE THREAD

**Issue by SubhamSubhasisPatra** [expo/eas-cli#1618]
### Summary
https://docs.expo.dev/eas-update/github-actions/ ( Followed this link )

The following warning is breaking the EAS Publish in the GitHub Actions. 

`The "set-output" command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ `

### Managed or bare?

bare

### Environment

Run actions/cache@v2
  with:
    key: Linux-yarn-
    restore-keys: Linux-yarn-
  env:
    MSYS: winsymlinks:nativestrict
    EXPO_TOKEN: ***
Warning: The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/[2](https://github.com/SubhamSubhasisPatra/jobs/6651768559#step:7:2)022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Error: Input required and not supplied: path

### REFER URL 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Reproducible demo or steps to reproduce from a blank project

Use the Old workflow to update to EAS .

**Comment by byCedric** [comment]
Hi @SubhamSubhasisPatra! The warning relates to the slightly outdated caching code in the example you linked. I just updated it with a new example (see PR https://github.com/expo/expo/pull/21385 = or the updated example at https://docs.expo.dev/eas-update/github-actions/).

If you want to use the manual github action cache, you can do that too. The code has changed (see [this example](https://github.com/actions/cache/blob/main/examples.md#node---yarn))

```diff
 - name: Find yarn cache
   id: yarn-cache-path
-  run: echo "::set-output name=dir::$(yarn cache dir)"
+  run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
 
 - name: Restore cache
   uses: actions/cache@v2
   with:
     path: ${{ steps.yarn-cache-path.outputs.dir }}
     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
     restore-keys: ${{ runner.os }}-yarn-
```

Hope this helps!
