### ISSUE TITLE
eas build showing some errors

### ISSUE THREAD

**Issue by alokdubey01** [expo/eas-cli#1623]
### Summary

![image](https://user-images.githubusercontent.com/72490595/212239987-cd5d35f0-34bc-4741-9c7f-53234ce461ec.png)

I am getting this error every time while building the app using eas build command.

### Managed or bare?

Android

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~47.0.12 => 47.0.12
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

{
  "cli": {
    "version": ">= 3.1.1"
    },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}

**Comment by szdziedzic** [comment]
Hi, does this issue still occur for you? It seems like it's old and stale. I can't reproduce it so far 🤔 Feel free to reopen if you still think it's broken.
