### ISSUE TITLE
EAS build fails for iOS with Managed Workflow, for Android it works

### ISSUE THREAD

**Issue by MichaelfromSooonah** [expo/eas-cli#1625]
### Build/Submit details page URL

https://expo.dev/accounts/mikego4projects/projects/soapp/builds/6aa3a5ba-cbad-46e5-a121-66d5b7ef7f40

### Summary

Expected:
Successfull iOS Build.
Android Build works.

IS:
Build failed: Build timeout
Your build exceeded the maximum build time of 45 minutes.

Run Fastlane shows:
› Linking   sooonah
⚠️  ld: duplicate method '+moduleName' in
┌─[category]: ExpoBridgeModule-f44ded592eeaab778e68afaa701a467f.o ExpoModulesCore/libExpoModulesCore.a
└─[class]: ExpoBridgeModule-5687ea8780aa9cd63782a4c30118428c.o ExpoModulesCore/libExpoModulesCore.a
⚠️  ld: method '+UIStatusBarAnimation:' in category from /Users/expo/Library/Developer/Xcode/DerivedData/sooonah-ferojuptmpvokaavpxfmpilczyiz/Build/Intermediates.noindex/ArchiveIntermediates/sooonah/BuildProductsPath/Release-iphoneos/React-CoreModules/libReact-CoreModules.a(RCTStatusBarManager.o) conflicts with same method from another category
› Generating debug sooonah » sooonah.app.dSYM

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ^47.0.13 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.7 => 0.18.10
      react-navigation: ^4.4.4 => 4.4.4
    Expo Workflow: managed

expo doctor
🎉 Didn't find any issues with the project!

### Reproducible demo or steps to reproduce from a blank project

It worked with SDK <46.
After update, I have this situation.
Inbetween no changes in own source code.

Please have a look. Must have something to do with build engine.

Thx!

**Comment by MichaelfromSooonah** [comment]
"Run Fastlane" ends with:
:
:
› Generating debug sooonah » sooonah.app.dSYM
› Executing sooonah » Bundle React Native code and images
    the transform cache was reset.

Then the Fail build error from above.

**Comment by MichaelfromSooonah** [comment]
Here some additional stderr outputs from "Run Fastlane"

Creating Gymfile
Gymfile created
Successfully loaded '/Users/expo/workingdir/build/ios/Gymfile' 📄
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                  Detected Values from './Gymfile'                                                                   |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| suppress_xcode_output | true                                                                                                                                        |
| clean                 | false                                                                                                                                       |
| scheme                | sooonah                                                                                                                                     |
| configuration         | Release                                                                                                                                     |
| export_options        |                                                                                                                                             |
| export_xcargs         | OTHER_CODE_SIGN_FLAGS="--keychain /var/folders/h2/gp9wlkv11lg0qj6y2mnqgc_40000gn/T/turtle-v2-b54a0dbb-c276-4169-8253-a6dd02cb6808.keychain" |
| disable_xcpretty      | true                                                                                                                                        |
| buildlog_path         | /Users/expo/workingdir/logs                                                                                                                 |
| output_directory      | ./build                                                                                                                                     |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
Resolving Swift Package Manager dependencies...
$ xcodebuild -resolvePackageDependencies -workspace ./sooonah.xcworkspace -scheme sooonah -configuration Release
▸ Command line invocation:
▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace ./sooonah.xcworkspace -scheme sooonah -configuration Release
▸ User defaults from command line:
▸     IDEPackageSupportUseBuiltinSCM = YES
▸ --- xcodebuild: WARNING: Using the first of multiple matching destinations:
▸ { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
▸ { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
▸ { platform:iOS Simulator, id:E4F0A83E-5E75-4C8A-A871-796043E2CD97, OS:16.0, name:iPhone 14 }
▸ { platform:iOS Simulator, id:8CF852C2-D053-4020-A861-01D707EE7C7B, OS:16.0, name:iPhone 14 Plus }
▸ { platform:iOS Simulator, id:FE2944BA-74BD-416E-93BB-3DC56388EF16, OS:16.0, name:iPhone 14 Pro }
▸ { platform:iOS Simulator, id:DD553D4E-CD22-4A2B-B095-50D480238D15, OS:16.0, name:iPhone 14 Pro Max }
▸ { platform:iOS Simulator, id:1F7C3904-A8F9-44F2-B6D0-31F51493EA22, OS:16.0, name:iPhone SE (3rd generation) }
▸ { platform:iOS Simulator, id:12DF1F1F-6206-4BDD-A49F-A0D3456DF497, OS:16.0, name:iPad (9th generation) }
▸ { platform:iOS Simulator, id:45E053AA-59FB-41B7-8DCA-2B11D2392A47, OS:16.0, name:iPad Air (5th generation) }
▸ { platform:iOS Simulator, id:7D6C0D20-8EEC-4074-9347-4F2DED6B610C, OS:16.0, name:iPad Pro (11-inch) (3rd generation) }
▸ { platform:iOS Simulator, id:A30864C0-A249-427B-B2F5-02B94465B342, OS:16.0, name:iPad Pro (12.9-inch) (5th generation) }
▸ { platform:iOS Simulator, id:823E8F2B-3928-438B-877F-E57CBB4D4227, OS:16.0, name:iPad mini (6th generation) }
▸ resolved source packages:
$ xcodebuild -showBuildSettings -workspace ./sooonah.xcworkspace -scheme sooonah -configuration Release
[stderr] --- xcodebuild: WARNING: Using the first of multiple matching destinations:
[stderr] { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
[stderr] { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
[stderr] { platform:iOS Simulator, id:E4F0A83E-5E75-4C8A-A871-796043E2CD97, OS:16.0, name:iPhone 14 }
[stderr] { platform:iOS Simulator, id:8CF852C2-D053-4020-A861-01D707EE7C7B, OS:16.0, name:iPhone 14 Plus }
[stderr] { platform:iOS Simulator, id:FE2944BA-74BD-416E-93BB-3DC56388EF16, OS:16.0, name:iPhone 14 Pro }
[stderr] { platform:iOS Simulator, id:DD553D4E-CD22-4A2B-B095-50D480238D15, OS:16.0, name:iPhone 14 Pro Max }
[stderr] { platform:iOS Simulator, id:1F7C3904-A8F9-44F2-B6D0-31F51493EA22, OS:16.0, name:iPhone SE (3rd generation) }
[stderr] { platform:iOS Simulator, id:12DF1F1F-6206-4BDD-A49F-A0D3456DF497, OS:16.0, name:iPad (9th generation) }
[stderr] { platform:iOS Simulator, id:45E053AA-59FB-41B7-8DCA-2B11D2392A47, OS:16.0, name:iPad Air (5th generation) }
[stderr] { platform:iOS Simulator, id:7D6C0D20-8EEC-4074-9347-4F2DED6B610C, OS:16.0, name:iPad Pro (11-inch) (3rd generation) }
[stderr] { platform:iOS Simulator, id:A30864C0-A249-427B-B2F5-02B94465B342, OS:16.0, name:iPad Pro (12.9-inch) (5th generation) }
[stderr] { platform:iOS Simulator, id:823E8F2B-3928-438B-877F-E57CBB4D4227, OS:16.0, name:iPad mini (6th generation) }
Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[stderr] --- xcodebuild: WARNING: Using the first of multiple matching destinations:
[stderr] { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
[stderr] { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
[stderr] { platform:iOS Simulator, id:E4F0A83E-5E75-4C8A-A871-796043E2CD97, OS:16.0, name:iPhone 14 }
[stderr] { platform:iOS Simulator, id:8CF852C2-D053-4020-A861-01D707EE7C7B, OS:16.0, name:iPhone 14 Plus }
[stderr] { platform:iOS Simulator, id:FE2944BA-74BD-416E-93BB-3DC56388EF16, OS:16.0, name:iPhone 14 Pro }
[stderr] { platform:iOS Simulator, id:DD553D4E-CD22-4A2B-B095-50D480238D15, OS:16.0, name:iPhone 14 Pro Max }
[stderr] { platform:iOS Simulator, id:1F7C3904-A8F9-44F2-B6D0-31F51493EA22, OS:16.0, name:iPhone SE (3rd generation) }
[stderr] { platform:iOS Simulator, id:12DF1F1F-6206-4BDD-A49F-A0D3456DF497, OS:16.0, name:iPad (9th generation) }
[stderr] { platform:iOS Simulator, id:45E053AA-59FB-41B7-8DCA-2B11D2392A47, OS:16.0, name:iPad Air (5th generation) }
[stderr] { platform:iOS Simulator, id:7D6C0D20-8EEC-4074-9347-4F2DED6B610C, OS:16.0, name:iPad Pro (11-inch) (3rd generation) }
[stderr] { platform:iOS Simulator, id:A30864C0-A249-427B-B2F5-02B94465B342, OS:16.0, name:iPad Pro (12.9-inch) (5th generation) }
[stderr] { platform:iOS Simulator, id:823E8F2B-3928-438B-877F-E57CBB4D4227, OS:16.0, name:iPad mini (6th generation) }
[stderr] 2023-01-13 13:12:07.667 xcodebuild[4268:13010] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
[stderr] 2023-01-13 13:12:08.623 xcodebuild[4279:13078] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
Detected provisioning profile mapping: {:"com.sooonah.soapp"=>"27ad06c3-3f0a-499b-9e91-7c39fe1b5828"}
+-------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                       Summary for gym 2.210.0                                                                                       |
+-------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
| workspace                                             | ./sooonah.xcworkspace                                                                                                                       |
| scheme                                                | sooonah                                                                                                                                     |
| clean                                                 | false                                                                                                                                       |
| output_directory                                      | ./build                                                                                                                                     |
| output_name                                           | sooonah                                                                                                                                     |
| configuration                                         | Release                                                                                                                                     |
| silent                                                | false                                                                                                                                       |
| skip_package_ipa                                      | false                                                                                                                                       |
| skip_package_pkg                                      | false                                                                                                                                       |
| export_options.method                                 | app-store                                                                                                                                   |
| export_options.provisioningProfiles.com.sooonah.soapp | 27ad06c3-3f0a-499b-9e91-7c39fe1b5828                                                                                                        |
| export_xcargs                                         | OTHER_CODE_SIGN_FLAGS="--keychain /var/folders/h2/gp9wlkv11lg0qj6y2mnqgc_40000gn/T/turtle-v2-b54a0dbb-c276-4169-8253-a6dd02cb6808.keychain" |
| build_path                                            | /Users/expo/Library/Developer/Xcode/Archives/2023-01-13                                                                                     |
| result_bundle                                         | false                                                                                                                                       |
| buildlog_path                                         | /Users/expo/workingdir/logs                                                                                                                 |
| destination                                           | generic/platform=iOS                                                                                                                        |
| suppress_xcode_output                                 | true                                                                                                                                        |
| xcodebuild_formatter                                  | xcpretty                                                                                                                                    |
| disable_xcpretty                                      | true                                                                                                                                        |
| skip_profile_detection                                | false                                                                                                                                       |
| xcodebuild_command                                    | xcodebuild                                                                                                                                  |
| skip_package_dependencies_resolution                  | false                                                                                                                                       |
| disable_package_automatic_updates                     | false                                                                                                                                       |
| use_system_scm                                        | false                                                                                                                                       |
| xcode_path                                            | /Applications/Xcode.app                                                                                                                     |
+-------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------+
$ set -o pipefail && xcodebuild -workspace ./sooonah.xcworkspace -scheme sooonah -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/expo/Library/Developer/Xcode/Archives/2023-01-13/sooonah\ 2023-01-13\ 13.12.08.xcarchive archive | tee /Users/expo/workingdir/logs/sooonah-sooonah.log > /dev/null

**Comment by MichaelfromSooonah** [comment]
I tried with different Build Environments and did a downgrade to Expo SDK 46.
Nothing helps. "Run fastlane" always took more than 45min.
This step took in Last good know build for iOS just 6min 30sec.

**Comment by MichaelfromSooonah** [comment]
Solved!

I found the solution...
In a file was an import automatically inserted:
`import { isJSDocUnknownTag } from 'typescript';`
This leads to the described problems.
Don't know where this import comes from :-(.

**Comment by LBeghini** [comment]
@MichaelfromSooonah I am facing the same error output, but I did not understand your solution.
What did you have to do?

**Comment by MichaelfromSooonah** [comment]
I use Microsoft Visual Code.
Apparently there is a feature that automatically inserts an "import" into the code if the editor thinks it is necessary.

I think I made a typo when adding some developments and Microsoft Visual Code automatically inserted the following line of code into the file:

import { isJSDocUnknownTag } from 'typescript';

Of course, I corrected my typo, but the import statement remained.
So I recommend you, to check your files for strange import statements.

**Comment by andrewgilliland** [comment]
@MichaelfromSooonah I have the exact same warnings in the run fastlane. Was it followed by a error:`../main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues`?

**Comment by maskowe** [comment]
@andrewgilliland  I got the same warnings in fastlane step with ios build.   But I don't have the error as you mentioned, and also do not have an invalid import (as mentioned above).    Were you able to resolve it for yourself?  Thanks.

**Comment by maskowe** [comment]
@andrewgilliland Interesting.   I’ll look into that. Thanks

**Comment by brunocrosier** [comment]
@steveafrost i don't know if you're experiencing the same problem i was, but this might help: https://github.com/expo/expo/issues/22711#issuecomment-1574913129

good luck!

**Comment by tadams39** [comment]
> Solved!
> 
> I found the solution... In a file was an import automatically inserted: `import { isJSDocUnknownTag } from 'typescript';` This leads to the described problems. Don't know where this import comes from :-(.

Thanks you so much, I was stuck on this for hours! 😅

**Comment by andrewgilliland** [comment]
@steveafrost where did you get the error?
```
eas.json is not valid.
- "env" is not allowed
```

Builds stopped working for me recently, and since I'm using that "ENTRY_FILE" value, I don't believe it's being read.

**Comment by steveafrost** [comment]
I receive that error when trying to build locally for either platform if the `env` key exists.
