### ISSUE TITLE
Using --json output with EAS_NO_VCS=1 causes resulting JSON to be invalid

### ISSUE THREAD

**Issue by oatsoda** [expo/eas-cli#1636]
### Summary

When using an EAS CLI command to output JSON, e.g. https://github.com/expo/eas-cli#eas-buildlist with `--json`, it seems that the output is prepended with "Using EAS CLI without version control system is not recommended, use this mode only if you know what you are doing.".

The docs say that errors would put in stdErr but that doesn't seem to be the case. (At least, attempting to separate the success output from the error output using Powershell Core doesn't help)

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-213.7172.25.2113.9123335
    npmPackages:
      expo: ^47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

### Error output

"Using EAS CLI without version control system is not recommended, use this mode only if you know what you are doing."

### Reproducible demo or steps to reproduce from a blank project

In **Powershell Core** (I've not tested on other platforms), run

```
$env:EAS_NO_VCS = 1
npx --yes eas-cli@latest build:list --non-interactive --json
```

And observe the output contains the warning before any JSON.

Try to separate the errors by piping **only the success** out, and then attempt to parse, just to prove it's invalid:

```
$env:EAS_NO_VCS = 1
npx --yes eas-cli@latest build:list --non-interactive --json 1> output.json
$json = Get-Content output.json
Write-Host $json
$json | ConvertFrom-Json
```

**Comment by adnanzafar123** [comment]
Thanks .that is working .......
