### ISSUE TITLE
[eas-cli] Umbrella issue for API error handling

### ISSUE THREAD

**Issue by barthap** [expo/eas-cli#164]
Feel free to edit/update this issue.

There are cryptic error messages when API requests fail, for example:
```
✖ Creating @barthap10/barthap-dogfood on Expo
    HTTPError: Response code 500 (Internal Server Error)
```

Since we reach API in two ways, we should handle both:
- GraphQL API - mostly this method: https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/graphql/client.ts#L44-L58
- REST `got` API

We should at least display error message from www by default. Also, maybe full stacktrace should be printed when given e.g. `EXPO_DEBUG` env variable. 

List of other related issues 
- [ ] #136 - When building for iOS 
- [ ] #163 - When registering projects

**Comment by byCedric** [comment]
I also want to add another use case which I ran into when working on the `channel` commands.

When we search for an app, it's based on user input (through project configuration). The app may or may not exist. It's a bit hard to create good feedback with this error handling kicking in with a `400` status when the app doesn't exist.

Take this query for example, just returning `null` for non-existing apps would be sufficient to signal there is no app with the name `@bycedrictest/hue-p1` (there is one, without `1` suffix).

```
query {
  app {
    byFullName(fullName: "@bycedrictest/hue-p1") {
      id
      name
      fullName
    }
  }
}
```
