### ISSUE TITLE
Apple servers threw an expected error from: https://appstoreconnect.apple.com/olympus/v1/session

### ISSUE THREAD

**Issue by jsindos** [expo/eas-cli#1645]
### Summary

I just upgraded `eas-cli` to `3.3.2` to take advantage of the new M1 workers. I had previously been running `0.57.0` (6 months old).

Just prior to upgrading, I had run an `eas build`, which had successfully authenticated with apple servers and uploaded my build.

Since upgrading, I am getting the error below when attempting to authenticate. I'm unsure how to proceed. I'll wait and try again later. It seems a bit odd that this error only just started occurring after I upgraded `eas-cli`.

```
› Using password for *** from your local Keychain
  Learn more: https://docs.expo.dev/distribution/security#keychain
✔ Logged in New session
› Team ***
Apple servers threw an expected error from: https://appstoreconnect.apple.com/olympus/v1/session
Authentication with Apple Developer Portal failed!
    Error: Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
```

### Managed or bare?

bare

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
      Watchman: 2022.11.14.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.3 
      expo: ^47.0.0 => 47.0.8 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.3.2
      expo-cli: 6.0.1
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Run blank project
With `eas-cli@3.3.2` try running `eas build` for iOS

**Comment by comontes** [comment]
same here

**Comment by secretyouth** [comment]
I am also having this issue.

Tried to delete my cookie and log back in.

`Authentication with Apple Developer Portal failed!
    AssertionError: An unexpected error occurred while completing authentication
    Code: ERR_ASSERTION`

**Comment by comontes** [comment]
after many tries, now it just worked, is like a hit or miss thing

**Comment by secretyouth** [comment]
I think the issue has been resolved - could have been an apple auth API issue.

Resolved for me as of now.

**Comment by dsokal** [comment]
Sorry for the bad experience. This was indeed an intermittent problem with Apple servers.
