### ISSUE TITLE
Apple App Store Submission rejected with code ITMS-90748 and no other information.

### ISSUE THREAD

**Issue by hoIIer** [expo/eas-cli#1659]
### Summary

After a successful build and submission through expo using `eas build -p ios --auto-submit`, the app was sent to Apple for submission.

I received an email back 5 minutes later that reads:
```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "react-chipsapp" 0.1.2 (0.1.2). Please correct the following issues, then upload again.

ITMS-90748: ${message}

Best regards,

The App Store Team
```

The `${message}` looks like a template placeholder that isn't populated and thus there is no information indicating what might be wrong.

I google searched for the specific error code and could not find anything!

What can I do to figure out why the app isn't being accepted?

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.7.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 9.2.0 - ~/.nvm/versions/node/v14.21.2/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: 45.0.0 => 45.0.0
      react: ~17.0.0 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 3.3.2
      expo-cli: 6.1.0
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

ios Simulator Version 12.4 (940.20)

### Error output

ITMS-90748: ${message} 

### Reproducible demo or steps to reproduce from a blank project

n/a

**Comment by rileymcnair** [comment]
Having the same problem

**Comment by jimmyz2** [comment]
Just experienced the same issue running `eas submit -p ios`. Any solutions or workarounds to this?

**Comment by konpapanik** [comment]
Same here. The build was done but i also get the error ITMS-90748 without further explanation or documentation about the error. Build is working on expo go and local. What is working in Expo go should be functional also at the builds. Those 2 tools should be sync in a way to be able to test in the expo go app without doubts. I start missing the expo classic builds.

**Comment by peterbee** [comment]
@rileymcnair @jimmyz2 @konpapanik For me, this only occurred the first submission.  After that Apple accepted the builds just fine.

Is anybody experiencing this issue repeatedly?

**Comment by hoIIer** [comment]
@peterbee it happened for 3 builds in a row for me

**Comment by jimmyz2** [comment]
@peterbee It also happened multiple times for me and still getting the when when submitting unfortunately.

Did you make any changes at all the 2nd time (Including incrementing the build number in app.json)?

**Comment by hoIIer** [comment]
For posterity:
https://developer.apple.com/forums/thread/723674
https://developer.apple.com/forums/thread/723940

**Comment by konpapanik** [comment]
@peterbee how you did the magic? For me it runs well also in simulator but when i uploaded next version again same error. Im now in version 1.4.0 :-). the version 1.3.0 was exact the same but the simulator build failed. Its a little foggy all that. @holler @jimmy any good news?

**Comment by hoIIer** [comment]
@konpapanik not yet but I will try again tonight. I tried again last night including using our main apple account owner email instead of my own dev email but that didn't work.

**Comment by jimmyz2** [comment]
@konpapanik @holler Solution that worked for me: Make sure your bundle ID is registered on the developer portal and doesn’t belong to any project already. Should be in Identifiers and you can add a new one there — make sure it matches the bundle ID in your app.json. Seems like the error is Apple can’t find your registered bundle ID

**Comment by dsokal** [comment]
This seems to be an issue with Apple. EAS doesn't send those emails.

See the links from @hoIIer:

> https://developer.apple.com/forums/thread/723674
> https://developer.apple.com/forums/thread/723940

**Comment by hoIIer** [comment]
@dsokal any idea how to get an answer from Apple? They haven't seemed to reply on those threads, and their email clearly has a bug in it where the template var isn't being populated. Very frustrating, we're stuck not knowing how to proceed.

**Comment by konpapanik** [comment]
Seems that the issue comes from multiple uploads of same identifier for an app that is removed but still kept in the records. I uploaded the exact same build with different identifier and was accepted. Its also possible the bundle to uploaded with transporter to all the accounts, if user has multiple. @holler see all the tabs in certificates, identifiers page for duplicates.  the only thing that i cannot really understand is why when you remove an app(which means someone removes an app for a reason) you cannot delete also the identifier to have clean space for uploading.

**Comment by hoIIer** [comment]
@konpapanik I tried using a brand new identifier and it failed with same message. At the same time for some reason Apple does not let me delete ANY identifiers from our apple account, despite that I deleted all apps (0 apps in ASC). So there's a graveyard of bundle identifiers I cannot delete.

It's very frustrating!

> you cannot delete also the identifier to have clean space for uploading.

Exactly. I will try again tonight and share any learnings here.

**Comment by wannagoapp** [comment]
> This seems to be an issue with Apple. EAS doesn't send those emails.
> 
> See the links from @hoIIer:
> 
> > https://developer.apple.com/forums/thread/723674
> > https://developer.apple.com/forums/thread/723940

I was having the same issue. **My project bundleIdentifier wasn't matching with Appstore's bundleId**. This solved it for me! Epic 😎

**Comment by konpapanik** [comment]
@hoIIer Try go the expo.dev yourproject credentials ios and see all parts have green valid.
if  you sync all those details with the app console profiles keys etc maybe will work.
Try also to add in the app.json 

"updates": {
        "fallbackToCacheTimeout": 0,
        "url": "https://u.expo.dev/yourprojecteasID"
      },

 and do 
eas update --branch production —message “updates”

and then 
eas build --profile production --platform ios
