### ISSUE TITLE
What exactly can one change through `eas update`?

### ISSUE THREAD

**Issue by feRpicoral** [expo/eas-cli#1662]
The docs say that, once you have configured your project, you can use `eas update` to make changes without having to create a new build.

Precisely, the docs say that

> Then, make any desired changes to your project's JavaScript, styling, or image assets.

But what exactly goes under "JavaScript"? Is it only the JSX itself? Or are npm packages included in that?

I would assume from this phrase that if I were to change my `app.json`/`app.config.ts` or my `eas.json`, I would need to make another build.

However, if I install a new package, do I need to create another build or just using `eas update` will do the trick?

When I say "docs", I am referring to this page:

https://docs.expo.dev/eas-update/getting-started/

**Comment by edi** [comment]
NPM packages are included since they're part of the final `bundle` you're updating.

**Comment by wkozyra95** [comment]
> But what exactly goes under "JavaScript"? Is it only the JSX itself? Or are npm packages included in that?

Javascript from npm libraries is included, but react-native packages often have native code, so when you are adding or updating a package like that you need to rebuild your app.

If you update a package and run `eas update`, then js code from the new version would run with native code for the old version, which in some cases might work. What will happen depends on the package, there is no one rule on how compatibility is maintained.
