### ISSUE TITLE
EAS build failure on "Configure Xcode project" step (potential bug with eas-cli 3.5.0?)

### ISSUE THREAD

**Issue by jacobhummel** [expo/eas-cli#1664]
### Build/Submit details page URL

https://expo.dev/accounts/reveltransit/projects/driver/builds/3ff01eca-a2d4-4691-b087-41aca45ef996

### Summary

We are hitting a new build failure when running with new EAS cli v3.5.0. (Started happening today 1/31, worked yesterday and before).

I believe the target name is not considering our `APP_ENV` env var that is used to generate the app name with our dynamic config. If you don't have that env var set it will use the app name "My App Local" instead of "My App Staging". I reproduced this issue, kicking off a build using eas-cli v3.4.1 on my machine passes.

It tries to target `MyAppNameLocal` instead of `MyAppNameStaging` when other jobs in the build are respecting that env var. Wondering if something changed with prebuild?

### Managed or bare?

Managed

### Environment

Run on Github Actions CI using expo/expo-github-action@v7
```
expo-cli (6.2.1)
eas-cli (3.5.0)
node (16.14.2)
ubuntu-latest (22.04.1)
```

### Error output

EAS build step "Configure Xcode project"
`Could not find target 'MyAppLocal' in project.pbxproj`

### Reproducible demo or steps to reproduce from a blank project

See "Configure Xcode project" step from the following builds

Failing build: 
- v3.5.0 on m1 https://expo.dev/accounts/reveltransit/projects/driver/builds/fea0c810-8663-46b7-86ed-cdffde8fc01f

Passing build:
- (same code version) v3.4.1 on intel (forgot to add m1 flag locally) https://expo.dev/accounts/reveltransit/projects/driver/builds/34d51ca2-0828-46d7-8972-5b7b713369ee
- (yesterday deployment) v3.4.1 on m1 https://expo.dev/accounts/reveltransit/projects/driver/builds/fea0c810-8663-46b7-86ed-cdffde8fc01f

**Comment by jacobhummel** [comment]
To add, found another failure that seems closely related. The Run fastlane step is failing as well on this build with a similar issue: https://expo.dev/accounts/reveltransit/projects/driver/builds/ddd452d4-6248-422f-b85b-b2e138ddad65. I'll try this same build/profile with version 3.4.1.

**Comment by Amrit0991** [comment]
Same deal here. We have "Zest" for our production build and "Zest Stage" for our internal staging build. EAS seems to be trying to use the production settings. 

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/4990803/215895320-8cc04122-8bb4-4dd6-974e-38bd25e9193e.png">

Will try 3.4.1 and get back.

**Comment by jacobhummel** [comment]
In the meantime I can build successfully by pinning to version 3.4.1

Before:
```
- name: Expo Setup
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
```

After:
```
- name: Expo Setup
        uses: expo/expo-github-action@v7
        with:
          expo-version: 6.2.1
          eas-version: 3.4.1
```

**Comment by wkozyra95** [comment]
It should be fixed in latest CLI https://github.com/expo/eas-cli/commit/2f1d454582b84b4396617fbae00a4dd2fc02fdf5
