### ISSUE TITLE
Authentication with Apple Developer Portal Failed (not fixed by 3.5.2)

### ISSUE THREAD

**Issue by tonymckendry** [expo/eas-cli#1677]
### Build/Submit details page URL

Failing in CLI - no page to share. 

### Summary

Likely related to: https://github.com/expo/eas-cli/issues/1672 

When attempting to use the `expo credentials:manager` in order to update an expired Push Notification cert, I am prompted to login to Apple but then receive the "Authentication with Apple Developer Portal Failed" error after successfully putting my credentials in. 

### Managed or bare?

Managed

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
    Expo Workflow: managed
```
    

### Error output

```
Authentication with Apple Developer Portal failed!
Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
    at CookieJar.setCookie (C:\Users\tmckendry\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\apple-utils\build\index.js:1:1124939)
    at CookieJar.setCookie (C:\Users\tmckendry\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\apple-utils\build\index.js:1:773128)
    at C:\Users\tmckendry\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\apple-utils\build\index.js:1:1087963
    at new Promise (<anonymous>)
    at C:\Users\tmckendry\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\apple-utils\build\index.js:1:1087744
    at Object.apply (C:\Users\tmckendry\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\apple-utils\build\index.js:1:1088761)
    at C:\Users\tmckendry\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\apple-utils\build\index.js:1:1057654
    at Array.forEach (<anonymous>)
    at responseInterceptor (C:\Users\tmckendry\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\apple-utils\build\index.js:1:1057627)
    at C:\Users\tmckendry\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\apple-utils\build\index.js:1:1055539
```

### Reproducible demo or steps to reproduce from a blank project

This error is not project-specific - run `expo credentials:manager` in any project.

**Comment by brentvatne** [comment]
you should use `eas credentials` rather than `expo credentials` - this command was only intended for the classic build service, which is now sunset

**Comment by tycobbb** [comment]
i'm still seeing this same error running other `eas` commands, e.g. `yarn eas device:create`, so it doesn't seem isolated to the use of `expo` in the op. on the latest version of `eas-cli`:

```sh
> yarn eas --version    
yarn run v1.22.19
$ /project-path/node_modules/.bin/eas --version
eas-cli/3.5.2 darwin-arm64 node-v16.18.1
```

**Comment by tonymckendry** [comment]
@brentvatne @tycobbb it did, tentatively, seem to work for me after switching over to using `eas credentials`. Thanks for the help. There's a popular Stackoverflow answer regarding dealing with expired push notification certs with Expo that mentions the expo command. I'll have to go leave a comment pointing people in the right direction.   

Leaving open in case @tycobbb is actually having a related problem - otherwise feel free to close.

**Comment by tycobbb** [comment]
i do still see the same error from this & the previous issue:

```sh
yarn eas device:create
yarn run v1.22.19
$ /<project-path>/node_modules/.bin/eas device:create
Found eas-cli in your project dependencies.
It's recommended to use the "cli.version" field in eas.json to enforce the eas-cli version for your project.
Learn more: https://github.com/expo/eas-cli#enforcing-eas-cli-version-for-your-project

This command lets you register your Apple devices (iPhones and iPads) for internal distribution of your app.
Internal distribution means that you won't need to upload your app archive to App Store / Testflight.
Your app archive (.ipa) will be installable on your equipment as long as you sign your application with an adhoc provisiong profile.
The provisioning profile needs to contain the UDIDs (unique identifiers) of your iPhones and iPads.

First of all, choose the Expo account under which you want to register your devices.
Later, authenticate with Apple and choose your desired Apple Team (if your Apple ID has access to multiple teams).

✔ You're inside the project directory. Would you like to use the <project-name> account? … yes
› Log in to your Apple Developer account to continue
✔ Apple ID: … ty.cobb@<domain>
› Restoring session /Users/ty/.app-store/auth/ty.cobb@<domain>/cookie
› Session expired Local session
› Using password for ty.cobb@<domain> from your local Keychain
  Learn more: https://docs.expo.dev/distribution/security#keychain
✔ Logged in New session
Authentication with Apple Developer Portal failed!
    Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by brentvatne** [comment]
@tycobbb - make sure you are using eas-cli@3.5.2

**Comment by tycobbb** [comment]
@brentvatne yeah, this using 3.5.2 (see previous message)

**Comment by brentvatne** [comment]
@tycobbb - i don't believe it is. run `yarn eas --version`

**Comment by tycobbb** [comment]
@brentvatne that's the comment i ran in my first command. and the output was:

```sh
> yarn eas --version    
yarn run v1.22.19
$ /project-path/node_modules/.bin/eas --version
eas-cli/3.5.2 darwin-arm64 node-v16.18.1
```

what is the blessed way to run eas commands then? i personally prefer to be able to install and use tools project-locally, because it minimizes the number of steps for people rolling onto a project to get up and running, and i work on a lot different projects =).

**Comment by hm1061998** [comment]
I got the same error even after upgrading to the latest eas-cli

`› Log in to your Apple Developer account to continue
√ Apple ID: ... vuvantuyen.vgasoft@gmail.com
› Restoring session C:\Users\Admin\.app-store\auth\vuvantuyen.vgasoft@gmail.com\cookie
› Session expired Local session
› The password is only used to authenticate with Apple and never stored on EASservers
  Learn more: https://bit.ly/2VtGWhU
√ Password (for vuvantuyen.vgasoft@gmail.com): ... ************
› Saving Apple ID password to the local Keychain
  Learn more: https://docs.expo.dev/distribution/security#keychain
√ Logged in New session
Authentication with Apple Developer Portal failed!
Failed to set up credentials.
    Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com   
    Request:developer.apple.com
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\working\mobile-app-scanPDF> eas --version
eas-cli/3.5.2 win32-x64 node-v16.14.0
PS D:\working\mobile-app-scanPDF> `

**Comment by hm1061998** [comment]
Fixed by 
`npm uninstall -g eas-cli --save`
`yarn global remove eas-cli    `
and run 
`npm install -g eas-cli   `

Then worked for me

**Comment by tycobbb** [comment]
> 

fwiw, removing & re-adding the package (project-locally, not globally) also fixed it for me!

**Comment by tycobbb** [comment]
> Fixed by `npm uninstall -g eas-cli --save` `yarn global remove eas-cli ` and run `npm install -g eas-cli `
> 
> Then worked for me

@brentvatne fwiw, removing & re-adding the package project-locally also fixed it for me. 🎉

**Comment by brentvatne** [comment]
thanks for the update. i have seen issues in the past where upgrading a global package with yarn doesn't work as expected (some dependencies appear to not be updated) -- this may have been what happened for you
