### ISSUE TITLE
"yes" utility doesn't work with eas build

### ISSUE THREAD

**Issue by vasiliiperfilev** [expo/eas-cli#1680]
### Summary

`yes | eas build --profile production --platform ios --local` command doesn't work. When prompt time happens it says `Error: Input is required, but stdin is not readable. Failed to display prompt: Do you want to log in to your Apple account?`

For context, I have 80 apps and I need to update provisioning certificates for all of them. To do this I have to run a local build and answer "yes" 3 times for each of them (240 inputs). I created a script that goes through all the apps and triggers the command above and cancels after the certificate update step of the build but it doesn't work apparently

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
System:
OS: macOS 12.5.1
Shell: 5.8.1 - /bin/zsh
Binaries:
Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
Managers:
CocoaPods: 1.11.3 - /Users/vasiliiperfilev/.rbenv/shims/pod
SDKs:
iOS SDK:
Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
Android SDK:
API Levels: 31, 32
Build Tools: 30.0.2, 30.0.3, 31.0.0
Android NDK: 22.1.7171670
IDEs:
Xcode: 14.2/14C18 - /usr/bin/xcodebuild
npmPackages:
@expo/webpack-config: ^0.17.0 => 0.17.4
expo: ^46.0.0 => 46.0.19
react: 18.0.0 => 18.0.0
react-dom: 18.0.0 => 18.0.0
react-native: 0.69.6 => 0.69.6
react-native-web: ~0.18.7 => 0.18.10
npmGlobalPackages:
eas-cli: 3.5.2
expo-cli: 6.1.0
Expo Workflow: managed

### Error output

Error: Input is required, but stdin is not readable. Failed to display prompt: Do you want to log in to your Apple account?

### Reproducible demo or steps to reproduce from a blank project

`yes | eas build --profile production --platform ios --local`

**Comment by dsokal** [comment]
Hi!

> For context, I have 80 apps and I need to update provisioning certificates for all of them.

- Can you clarify what's your use case? Is it for internal distribution?
- By "provisioning certificates" do you mean provisioning profiles?

**Comment by fabioglimb** [comment]
Same issue here

**Comment by vasiliiperfilev** [comment]
@dsokal so every year developers need to update provisioning profiles. We support 80 apps, so to update profiles we need to run `eas build`80 times and answer 'yes' to "Do you want to update the provisioning profile?" manually

**Comment by KiwiKilian** [comment]
@vasiliiperfilev Doesn't `--non-interactive` do the trick? Or does it not confirm to updating the certificates? We run from our pipeline on mac runners like this:
```
npx eas-cli build --profile development --platform ios --non-interactive --local
```

**Comment by vasiliiperfilev** [comment]
@KiwiKilian Yeah, it doesn't confirm updating the certificates, unfortunately, but thanks for the suggestion!

**Comment by janwirth** [comment]
Thi is also quite bothersome for me. Like 4 out of 5 times I forget to confirm the various prompts and come back to an unfinished build.

**Comment by eckler-matthew** [comment]
Is there any other trick to this? I simply want to say yes to every question, but can't find a way to do it without breaking something.

**Comment by janwirth** [comment]
See @KiwiKilian's response
