### ISSUE TITLE
CLI hangs for minutes after expected output has finished

### ISSUE THREAD

**Issue by malice00** [expo/eas-cli#1684]
### Summary

Running any eas cli command, blocks the console for several minutes before returning control back to the user. This is especially annoying when running from Jenkins, where it unnecessarily blocks the server for up to 10 minutes!

### Managed or bare?

managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 16.6.2 - ~/.nvm/versions/node/v16.6.2/bin/node
      Yarn: 1.22.18 - ~/.nvm/versions/node/v16.6.2/bin/yarn
      npm: 7.20.3 - ~/.nvm/versions/node/v16.6.2/bin/npm
    npmPackages:
      expo: ~47.0.12 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.9 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.5.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

In my case, I simply run something like:
`eas build:list --appBuildVersion=2`
After you output is shown, just wait (for 8-10 minutes!) until you get control of your shell back.

**Comment by wkozyra95** [comment]
> Running any eas cli command, blocks the console for several minutes before returning control back to the user.

Can you clarify what you mean by that, and when it is happening?
Is this happen only on CI or in interactive terminal too?
What do you mean block? Are you prompted for sth and it waits for an answer or is it just stop without any context?
What do you mean by "before returning control back to the user"? Is it a continue process or exists to the shell? Are there any errors?

If this is happening only in CI, then it's a correct behavior and you should use `--non-interactive` flag to disable any prompts.

**Comment by malice00** [comment]
I wanted to make a video or something to show this behavior, but wasn't able to reproduce it at home --> The difference between home and work is our corporate proxy, so I assume it has to do with that. I'll try again tomorrow.

To answer your questions: when I run eg `eas build:list --appBuildVersion=2 --json --non-interactive`, I get the expected JSON output, but the command-prompt doesn't return for several *minutes* -- I don't know what else to call it but 'hang'...

As I said, I'll try to make a video of it somehow, that might make it more clear...

Also, here's (part of) the output from CI (command `HTTP_PROXY=<our proxy> HTTPS_PROXY=<our proxy> http_proxy=<our proxy> https_proxy=<our proxy> eas build --profile preview --platform ios --non-interactive`):

![Screenshot 2023-02-12 at 17-43-23 SVAPPS » Navigator - Expo #15 Console Jenkins](https://user-images.githubusercontent.com/12972577/218324669-60807a13-ed4c-41b7-a225-526802a1131d.png)

The actual build has been finished for 13 minutes before `eas` returned 'control' back to Jenkins and my developers got their notification about it...

**Comment by malice00** [comment]
Here's a video when I request `build:list` on my laptop. It's ~50 seconds, but I feel it shows the issue quite clear:

https://user-images.githubusercontent.com/12972577/218497235-0ede7385-7afe-49ff-aee2-e6949d834f95.mp4

On my laptop I can obviously stop eas with ctrl-c, but in our CI this is not an option. Clock was added so you can clearly see that only eas is hanging.

As I mentioned, I assume it is because of the proxy -- all env-variations I know have been configured.

**Comment by wkozyra95** [comment]
The only thing that is happening after value is printed, is flushing analytics, but it's a bit surprising that it would block those requests because ther are sent to expo domain `cdp.expo.dev`, but it does not block other requests to expo servers.

You can verify if that is the issue by setting env `DISABLE_EAS_ANALYTICS=1`, or you can permanently disable them by running `eas analytics off` (this affects local installation only, so on CI it's easier to use env)

**Comment by malice00** [comment]
I used the env on my laptop and that actually solves the problem! I guess this means the analytics are not using the proxy-settings...
