### ISSUE TITLE
Error: Runtime version policies are only supported in the managed workflow

### ISSUE THREAD

**Issue by huy-lv** [expo/eas-cli#1689]
### Summary

Hi, I ran command `eas update --auto` and got this error. Please help :D
```
Error: Runtime version policies are only supported in the managed 
    workflow. In the bare workflow, runtime version needs to be set manually.
```

Runtime version policies are only supported
<img width="568" alt="image" src="https://user-images.githubusercontent.com/7688070/206857926-026e4a6b-a914-474a-a893-94aa9f5d3a24.png">

### What platform(s) does this occur on?

Android

### SDK Version

46

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.19.3 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.3/bin/yarn
      npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
      Watchman: 2022.11.28.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~46.0.17 => 46.0.17 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.0.0
      expo-cli: 6.0.5
    Expo Workflow: bare

### Minimal reproducible example

1. Build internal apk
2. update some code
3. run `eas update --auto`

**Comment by ethanj20** [comment]
We would like to use `appVersion` as the `runtimeVersion` in app.config.js per [this documentation](https://docs.expo.dev/eas-update/runtime-versions/#appversion-runtime-version-policy-available-in-sdk-46-and-higher) but the builds won't run on a simulator when this is set (they only run if the `runtimeVersion` is set to `sdkVersion`, or if the `runtimeVersion` is deleted entirely). Is this the expected workflow? I don't want to have to rebuild my app on expo servers every time I want to test a change, but `appVersion` is the best policy for us as we manage our OTA updates based on the `appVersion`. Is there a way to use this `runtimePolicy` without having to delete it from `app.config.js` before trying to run it on a simulator?

Thanks in advance.

<img width="188" alt="image" src="https://user-images.githubusercontent.com/74612986/220784389-9f951698-23c4-475b-b830-45eb38732d5b.png">

**Comment by ethanj20** [comment]
created a new issue for the above comment since it is a slightly different issue: https://github.com/expo/eas-cli/issues/1713

**Comment by ishahbaz7** [comment]
I just deleted the dist and ios directory. And it works for me.

**Comment by yamak-app** [comment]
im my case this solved my issue 

 "runtimeVersion": "1.0.0",

**Comment by swagatkytics** [comment]
im my case this solved my issue

"runtimeVersion": "exposdk:48.0.0",

**Comment by huszzsolt** [comment]
> I just deleted the dist and ios directory. And it works for me.


I started to get `You're currently using the bare workflow, where runtime version policies are not supported. You must set your runtime version manually. For example, define your runtime version as "1.0.0", not {"policy": "appVersion"} in your app config.`  for `eas update --branch eas-dev`, but this worked before.

Relealized from @ishahbaz7 comment, that I did a local build recently which probably confused expo. Deleting `android` , `ios` and `dist` (dist might not have been required) resolved the issue.

**Comment by nwazuo** [comment]
> > I just deleted the dist and ios directory. And it works for me.
> 
> I started to get `You're currently using the bare workflow, where runtime version policies are not supported. You must set your runtime version manually. For example, define your runtime version as "1.0.0", not {"policy": "appVersion"} in your app config.` for `eas update --branch eas-dev`, but this worked before.
> 
> Relealized from @ishahbaz7 comment, that I did a local build recently which probably confused expo. Deleting `android` , `ios` and `dist` (dist might not have been required) resolved the issue.

This solved it for me🚀
