### ISSUE TITLE
eas build -p ios failed when a digit in expo.name in app.json 

### ISSUE THREAD

**Issue by svkonovaloov** [expo/eas-cli#1692]
### Build/Submit details page URL

https://expo.dev/accounts/sergey_konovalov/projects/its1c/builds/3e9c0846-ad48-48f3-a605-fabc38b2f06e

### Summary

When expo.name in app.json is:
"Помощь 1С" - build **failed**
"Помощь IС" - build **OK** (IC = ic)
"IC Help" - build **OK** (IC = ic)

Please help me - I cant walkaround and name my app without digit (( cause 1C - is the name of ERP system and it is keyword customers searching the app

![image](https://user-images.githubusercontent.com/122823462/218347110-b370e6e2-639b-4ca3-9dc6-b60428015399.png)

### Managed or bare?

Managed

### Environment

C:\my\itp1c\itp1c-v07>npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows Server 2016 10.0.14393
    Binaries:
      Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
    Expo Workflow: managed

C:\my\itp1c\itp1c-v07>expo doctor
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with expo-cli on Windows. You may encounter issues using cmd.exe.

🎉 Didn't find any issues with the project!

### Error output

![image](https://user-images.githubusercontent.com/122823462/218347368-cc339cf6-b8f5-4064-b201-4ecfd5ce1b92.png)

### Reproducible demo or steps to reproduce from a blank project

I'm sorry but every time I try it takes 1 of 30 free builds ((

**Comment by wkozyra95** [comment]
When generating a project we take a name, normalize it(remove all non ascii characters or replace them) and use that as e.g. target name.

In your case target starts with a number, which is not allowed on iOS. I couldn't find previous thread, but in the past users soved that by picking a different name in app.json, and using localization to provide non ASCII name that users will see in stores.

I think you can add that to Info.plist, but I don't remember  the details.

**Comment by wkozyra95** [comment]
Check docs here https://docs.expo.dev/guides/localization/#translating-app-metadata

**Comment by svkonovaloov** [comment]
Thank you for helpful advise!
