### ISSUE TITLE
[IOS] Use fastlane match for generating credentials?

### ISSUE THREAD

**Issue by ravi-poonia** [expo/eas-cli#170]
Wouldn't it be possible to get credentials from fastlane match to generate ios build, so that we don't have to do it manually.

eas-cli uses fastlane gem to build the ipa file, it should be possible to use match credentials in there somewhere, right?

**Comment by ravi-poonia** [comment]
I know eas certificates is a terrific way to manage the certificates but if someone is coming from the fastlane environment then it could be really helpful if there was a way to reuse same credentials.

**Comment by thespacemanatee** [comment]
Did you find a solution?
