### ISSUE TITLE
Is there any way to set the ios app icons without Xcode on windows computer for react native bare workflow + expo?

### ISSUE THREAD

**Issue by Dofamen** [expo/eas-cli#1709]
Is there any way to set the ios app icons without Xcode on windows computer for react native bare workflow + expo?

I have this error when I try to publish my app into apple store,

Going to upload updated app to App Store Connect
This might take a few minutes. Please don't interrupt the script.
[altool] 2023-02-19 02:59:34.973 *** Error: Asset validation failed Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/. (ID: 304b3829-4df3-4d62-96d0-4cd607b2a47a) (90704)
[altool]  {
[altool]     NSLocalizedDescription = "Asset validation failed";
[altool]     NSLocalizedFailureReason = "Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/. (ID: 304b3829-4df3-4d62-96d0-4cd607b2a47a)";

_Originally posted by @Dofamen in https://github.com/expo/eas-cli/issues/877#issuecomment-1435962839_

**Comment by wkozyra95** [comment]
Technically yes, but it might be complicated.
- The simplest approach would be to modify the icon in app.json and run `expo prebuild`, but this will partially or fully override your local project changes. Also if your project is significantly different than projects generated by expo-cli, then `expo prebuild --clean` might be necessary, which will remove android/ios directories entirely and generate new ones.
- You can just add or replace files in your project. Replacing should be easy, but if you need to add sth missing, your will need to modify the config and that might get complicated.
- Mix of above 2 approaches would be to commit your change -> run `expo prebuild` -> investigate the diff and only commit parts related to the image change.
