### ISSUE TITLE
i add my Secrets to my project and i want get it in my build but i got undefined 

### ISSUE THREAD

**Issue by chirag-codealchemy** [expo/eas-cli#1718]
![Screenshot 2023-02-24 at 12 18 59 PM](https://user-images.githubusercontent.com/111970008/221111285-7398f8aa-c647-416d-9f04-86caeb74b5e7.png)

my configs are as follow  

**Babel.config.js**

module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: ["transform-inline-environment-variables"],
  };
};

**my_file.js**

import Constants from "expo-constants";

const appConfigKeys = Constants.expoConfig.extra;
console.log("🚀 ~ file: config.js:4 ~ appConfigKeys:", appConfigKeys. API_URL_IMAGE);   // got undefined
const envDatas = process.env;
console.log("🚀 ~ file: config.js:4 ~ envDatas:", envDatas. API_URL_IMAGE);   // got undefined

can you please help me to figure out how can i resolve this issue

**build command** 
expo run:android

is it because i build locally

**Comment by wkozyra95** [comment]
secrets are setting those values as env variables during build process, to pass them to your app code you need to do it explicitly https://docs.expo.dev/guides/environment-variables/

Also, secrets are only available during cloud builds, so if you run `expo run:android` or `eas build --local` they won't be available.

Looking at the names of those values it looks to me that none of them should be secrets, especially if you plan to embed them in js bundle. I would recommend hardcoding them in js or putting them in eas.json(note that eas.json approach will work with eas build --local, but not with `expo build:android`.
