### ISSUE TITLE
device:create seems to work but provisioning profile is missing

### ISSUE THREAD

**Issue by matmartic** [expo/eas-cli#1722]
### Summary

I run `eas device:create` to add an iphone 7 to our devices. It sends me the URL, I open it, install it and get to the "Your device is ready to run internal distribution builds". 

But after when I try doing an eas build, I get 
```
✔ Fetched Apple provisioning profiles
The provisioning profile is missing the following devices:
- 40e8....... (iPhone 7)
```

If I go through with the build anyway, it doesn't install the app, which makes sense since the provisionning profile is missing.

I tried doing it by manually adding the UDID during the device:create as well, and it seems to work, but it still says that the provisionning profile is missing when I try doing a build

Is it possible that since the iphone 7 uses the older UDID format, that it cannot be added to the devices? 
Could it be that ios15 is the problem?

My collegue just did it with his iPhone 12/ios16 and had no issues using the same steps. 
I also tried rebooting the phone as a last resort, but still the same problem. 

### Managed or bare?

managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.18 - /opt/homebrew/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
      Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 28, 29, 30, 31
        Build Tools: 30.0.2, 30.0.3, 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.1
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

- Have an iPhone 7
- `eas device:create` -> once url created, do the steps on the phone until success
- `eas build ...` once you log in with your appleId, it fetches distribution certificates & provisioning profiles
- Check if yellow warning appears `The provisioning profile is missing the following devices` + UDID of the iphone you're trying to add

**Comment by dsokal** [comment]
Hi,
I'm confused why you think this is a bug. I suppose you're skipping the provisioning profile re-generation somehow.
The "The provisioning profile is missing the following devices" warning doesn't say the **provisioning profile** is missing. It says that the newly registered device ID is not the (previously generated) provisioning profile. This is totally normal.
After this warning is printed, there should be a prompt asking if you want to regenerate the profile. You should answer "yes".

**Comment by dsokal** [comment]
Actually, the prompt is this. You should answer "Yes" and this will regenerate the provisioning profile.
<img width="893" alt="Screenshot 2023-02-27 at 10 14 38" src="https://user-images.githubusercontent.com/5256730/221522362-915ca028-ffc8-46b1-b0ad-0725b4a78aab.png">

**Comment by matmartic** [comment]
Hi, 
Thanks for your answer.
Indeed, I think I got confused with the phrasing. I did press yes, but the device didn't appear in the list of provisionned devices (therefore the build could not install on that iphone). In the meantime, I updated xcode this weekend to  14.2 , and now I'm getting a slightly different flow, but the result is still unchanged.

First I do `eas device:create` and go through that flow on that iphone until I get a success message. Then I do the build, and once it shows me the list of devices `Select devices for the ad hoc build` I can see my device and choose it. But as soon as I choose it, it doesn't show up in the list of devices that is displayed. Furthermore, when it gets to the section `Project Credentials Configuration` this device does not appear under "Provisionned devices". 

Also as you'll see in the screenshot, the choice for the iphone 7 is not a green circle like all the other options, rather an empty circle. When I choose it

![image](https://user-images.githubusercontent.com/15280410/221689267-e03f1305-6e38-4e31-b804-e7fa1eef7536.png)
![image](https://user-images.githubusercontent.com/15280410/221692013-385ed7e8-6c54-41c7-9ad7-7dca4fa7bfff.png)
![image](https://user-images.githubusercontent.com/15280410/221689559-b961859d-2a6d-45ef-9580-0145d48fe685.png)
![image](https://user-images.githubusercontent.com/15280410/221692586-7fa610c6-0932-4d29-9cd8-0bd02f091017.png)


To me this seems like a bug because I get a success message, but the device does not appear on the provisionned devices list, nor does the build work on that iphone.
On the apple developer portal, I do see the device in the provisionned device list.

**Comment by dsokal** [comment]
The answer to the issue is in your screenshot. 
![221689267-e03f1305-6e38-4e31-b804-e7fa1eef7536](https://user-images.githubusercontent.com/5256730/221796102-8f6f23a6-adef-4a85-ba80-d4f3a8d4645d.png)
The green dot indicates that the device is selected. Use space to select a device. The circle should change to green.

**Comment by matmartic** [comment]
@dsokal Thank you, I didn't realize I was missing that step.

**Comment by hasanfd** [comment]
we need a terminal UX engineer :)

**Comment by sgvolpe1** [comment]
> The answer to the issue is in your screenshot. ![221689267-e03f1305-6e38-4e31-b804-e7fa1eef7536](https://user-images.githubusercontent.com/5256730/221796102-8f6f23a6-adef-4a85-ba80-d4f3a8d4645d.png) The green dot indicates that the device is selected. Use space to select a device. The circle should change to green.

jajaja, 1 hour lost with this trouble, but i only need read this comment, thank you

**Comment by Naren219** [comment]
i'm having the same issue as @LucasLFurini here. i ran the `eas device:create` to open a registration page and registered both of my iphones. i then used this command `eas device:list` and it showed both of my devices.
 
![Screenshot 2023-07-19 at 12 29 58 PM](https://github.com/expo/eas-cli/assets/71474909/7ce3e777-4fbe-49b3-aff9-16eaa5477a25)

however, when i ran this command to build the preview config `eas build --profile preview --platform ios`, only one device is shown. 

![Screenshot 2023-07-19 at 12 38 06 PM](https://github.com/expo/eas-cli/assets/71474909/c2f0c011-ecd9-4ae8-a5b9-f0f1a848fcc2)

even when i look at the provisioning profile in the apple developer website, it says "Devices 1 total", so the other device wasn't even updated. i thought expo would automatically add these new devices as one of the device names were "iOS Device (added by Expo)". however, the other iphone is not added in like this. 

fyi: the device not showing up is an iPhone Xr.

i appreciate your help!

**Comment by dylanmeivis** [comment]
I was having the same issue as @LucasLFurini, @Naren219 and @eemebarbe. And I can confirm that after running the solution provided by @mspallek-valantic it worked for me as well and the provisioning profile was updated with the selected devices.

**Comment by lortschi** [comment]
> The answer to the issue is in your screenshot. ![221689267-e03f1305-6e38-4e31-b804-e7fa1eef7536](https://user-images.githubusercontent.com/5256730/221796102-8f6f23a6-adef-4a85-ba80-d4f3a8d4645d.png) The green dot indicates that the device is selected. Use space to select a device. The circle should change to green.

Oh man, please then inform users inside the configs how to select list items because I lost 1 week regarding this custom selection workflow.

**Comment by standyro** [comment]
I ran into this same issue! Thanks to @dsokal in this thread.

Something like `Press SPACEBAR to add a device to your provisioning profile` would help a lot here.

I kept hitting enter and wondering why it wouldn't generate a new one. doh

**Comment by moishinetzer** [comment]
+1 - This slipped me up as well today.

**Comment by Gbillington1** [comment]
> The green dot indicates that the device is selected. Use space to select a device. The circle should change to green.

I can't believe I just wasted 4 hours of my day clicking Enter instead of Space. fml

**Comment by b-murphy** [comment]
thanks a million for this!

**Comment by Pajimo** [comment]
> [@eemebarbe](https://github.com/eemebarbe), I had the same issue. It seems like the ad-hoc profile is not updating correctly. What fixed the issue for me was to delete the ad-hoc profile in Expo.
> 
> You can do so by running `eas credentials`: iOS > preview > Build Credentials > Provisioning Profile > "? Delete the provisioning profile associated with the AD_HOC configuration…" > Y
> 
> After that, run your build. I hope that helps!

This worked for me. Not sure why but it did.

**Comment by ibrust** [comment]
People weren't joking when they said we need a UX designer for the terminal here.

**Comment by EtherealData** [comment]
> The answer to the issue is in your screenshot. ![221689267-e03f1305-6e38-4e31-b804-e7fa1eef7536](https://user-images.githubusercontent.com/5256730/221796102-8f6f23a6-adef-4a85-ba80-d4f3a8d4645d.png) The green dot indicates that the device is selected. Use space to select a device. The circle should change to green.

omg! i was confused as well!

**Comment by moishinetzer** [comment]
Cc: @EvanBacon seems like people are still slipping up on this. Any way we could reopen this ticket to help others?

**Comment by rennard** [comment]
please change the UI to be more obvious, maybe it's user error but I just wasted hours on this

**Comment by shaoweipng** [comment]
my turn to lose 1 hour of my time on this - who would have clicked space instead of enter?

**Comment by fansilva1991** [comment]
> The answer to the issue is in your screenshot. ![221689267-e03f1305-6e38-4e31-b804-e7fa1eef7536](https://user-images.githubusercontent.com/5256730/221796102-8f6f23a6-adef-4a85-ba80-d4f3a8d4645d.png) The green dot indicates that the device is selected. Use space to select a device. The circle should change to green.

Thanks!
