### ISSUE TITLE
EAS build not launching correctly on iOS

### ISSUE THREAD

**Issue by ajgangal** [expo/eas-cli#1727]
### Build/Submit details page URL

https://expo.dev/accounts/memorateam/projects/memora-app/builds/94e56ea8-297b-4eb3-bb8e-0f0656ffcafb

### Summary

My app runs perfectly when I use `expo start` and run it in the Expo Go app.
When I create a build using EAS `eas build --development --platform ios` it runs successfully, and gives me an install link.

Upon installing on my phone, it opens only to a white blank screen for 10 seconds and crashes. It should show the development client screen (i think) but it doesn't. 

When I then run `expo start --dev-client` it does the same thing. QR code open the app, but it crashes within 10 seconds. 

Please help! 

I have checked my iOS credentials, certs and profiles and it all looks good. My guess is the installed app is not communicating with EAS for some reason, which I'm not aware of. 

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.17.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.15.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    IDEs:
      Xcode: 14.0/14A309 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 48.0.4 
      react: 17.0.1 => 18.2.0 
      react-dom: 17.0.1 => 18.2.0 
      react-native: 0.64.3 => 0.71.3 
      react-native-web: 0.17.1 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.5.2
      expo-cli: 6.3.2
    Expo Workflow: bare

### Error output

No error log, build is stuck on "start metro builder". 

### Reproducible demo or steps to reproduce from a blank project

Not sure how to reproduce, looking for help here :)

**Comment by cseelus** [comment]
Same problem. Builds created with `eas build -p ios`and installed on any iOS device just show the SplashScreen briefly and then a white screen indefinitely.
