### ISSUE TITLE
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

### ISSUE THREAD

**Issue by mattiarainieri** [expo/eas-cli#1732]
### Summary

When i try to build with eas locally i have the error written below.
I've install the latest version of Gradle (8.0.1) and Java (19.0.2) but the error persist

MacOS with M2

### Managed or bare?

Managed

### Environment

WARNING: The legacy expo-cli does not support Node +17. Migrate to the versioned Expo CLI (npx expo).
🎉 Didn't find any issues with the project!

### Error output

`[PREPARE_CREDENTIALS] Writing secrets to the project's directory
[PREPARE_CREDENTIALS] Injecting signing config into build.gradle
[RUN_GRADLEW] Running 'gradlew :app:assembleRelease' in /var/folders/mj/1cc59x_d49sgz9h8j9w50xnm0000gn/T/eas-build-local-nodejs/6c09b46b-4fd5-4068-86f2-9382c13e0ac0/build/android
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Could not open settings generic class cache for settings file '/private/var/folders/mj/1cc59x_d49sgz9h8j9w50xnm0000gn/T/eas-build-local-nodejs/6c09b46b-4fd5-4068-86f2-9382c13e0ac0/build/android/settings.gradle' (/Users/mattiarainieri/.gradle/caches/7.5.1/scripts/4m73o5hy0wcdtw9kuua74cbm8).
[RUN_GRADLEW] >
[RUN_GRADLEW] BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with
[RUN_GRADLEW] --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] >
[RUN_GRADLEW] Run with --scan to get full insights.
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 351ms
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.`

### Reproducible demo or steps to reproduce from a blank project

**eas.json file**

`{
  "cli": {
    "version": ">= 3.6.2"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "resourceClass": "m1-medium"
      }
    },
    "preview": {
       "android": {
        "buildType": "apk"
      },
      "distribution": "internal",
      "ios": {
        "resourceClass": "m1-medium"
      }
    },
    "production": {
      "ios": {
        "resourceClass": "m1-medium"
      }
    }
  },
  "submit": {
    "production": {}
  }
}
`

**Comment by anirudhj111** [comment]
@mattiarainieri , have been facing the same issue , any luck resolving this?

**Comment by rvasseur31** [comment]
> @mattiarainieri , have been facing the same issue , any luck resolving this?

I ran `npx expo prebuild` and I changed distributionUrl to `distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-all.zip` in `android/gradle/wrapper/gradle-wrapper.properties`

**Comment by mattiarainieri** [comment]
@rvasseur31 which file did you edit?

**Comment by rvasseur31** [comment]
> @rvasseur31 which file did you edit?

`android/gradle/wrapper/gradle-wrapper.properties`.

The file is generated with `npx expo prebuild`

**Comment by mattiarainieri** [comment]
@rvasseur31 Thank you, i've fix that but now i have another error 😂

**Comment by gianlucadifrancesco** [comment]
@rvasseur31 Do you know if there are some other alternatives, without running `expo prebuild`?

**Comment by rvasseur31** [comment]
Yes I found an other alternative, I reinstalled java from zero, I'm now using java 11 from Zulu :
```
➜ java --version
openjdk 11.0.18 2023-01-17 LTS
OpenJDK Runtime Environment Zulu11.62+17-CA (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.62+17-CA (build 11.0.18+10-LTS, mixed mode)
```

I'm not completely sure if it was this action that allowed me to correct this mistake but I prefer to talk about it

**Comment by gianlucadifrancesco** [comment]
> I reinstalled java from zero, I'm now using java 11 from Zulu

You made me discover that the Java version was actually the problem in my case: I was using Java 20 but **Java 11 was the right one**!

@mattiarainieri Could this be the problem in your case as well, since you were using Java 19?
For Android builds, Expo is using [Java 11 by default](https://docs.expo.dev/build-reference/infrastructure/#android-server-images), therefore this is most likely the solution.

To me it worked with _Java 11 (11.0.18)_ from Oracle (though I think it's the same with Zulu @rvasseur31).
Also, [this SO answer](https://stackoverflow.com/a/24657630) helped me in checking and making sure I was using the right Java version.

Thank you for your help!

**Comment by mxplusb** [comment]
I downgraded Java to Java 11, and implemented the Gradle recommendation, and this resolved my problem, too
