### ISSUE TITLE
iOS Build Fastlane Error Exit status: 65

### ISSUE THREAD

**Issue by imarc7** [expo/eas-cli#1733]
### Summary

I'm facing a Fastlane Error when I build the project using the command eas build.
The error logs are:

<img width="1042" alt="Screenshot 2023-03-04 at 7 45 06 PM" src="https://user-images.githubusercontent.com/18014534/222923980-11b51897-3080-41b5-9573-8a7f8ea08417.png">
<img width="1032" alt="Screenshot 2023-03-04 at 7 58 58 PM" src="https://user-images.githubusercontent.com/18014534/222923985-99be4e4e-ab46-4e44-b9f3-04afd82a2f1b.png">

React Native: 0.71.3
Expo: 48.0.4

### Managed or bare?

Managed

### Environment

npx: installed 2 in 2.877s

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
      npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.2

✖ Dependency tree validation for expo-modules-autolinking failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @expo/config-plugins failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @expo/prebuild-config failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @unimodules/core failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for @unimodules/react-native-adapter failed. This validation is only available on Node 16+ / npm 8.
✖ Dependency tree validation for react-native-unimodules failed. This validation is only available on Node 16+ / npm 8.
🎉 Didn't find any issues with the project!

### Reproducible demo or steps to reproduce from a blank project

"scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@expo-google-fonts/inter": "^0.2.2",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-navigation/bottom-tabs": "^6.5.6",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "axios": "^1.2.6",
    "deprecated-react-native-prop-types": "^2.2.0",
    "expo": "~48.0.4",
    "expo-build-properties": "~0.5.1",
    "expo-device": "~5.2.1",
    "expo-file-system": "~15.2.2",
    "expo-font": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-localization": "~14.1.1",
    "expo-location": "~15.1.1",
    "expo-network": "~5.2.1",
    "expo-notifications": "~0.18.1",
    "expo-splash-screen": "~0.18.1",
    "expo-status-bar": "~1.4.4",
    "expo-updates": "~0.16.3",
    "lottie-react-native": "5.1.4",
    "moment": "^2.29.3",
    "patch-package": "^6.5.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.71.3",
    "react-native-awesome-alerts": "^2.0.0",
    "react-native-calendars": "^1.1284.0",
    "react-native-check-box": "^2.1.7",
    "react-native-crypto-js": "^1.0.0",
    "react-native-dotenv": "^3.4.7",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-maps": "1.3.2",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "~3.20.0",
    "react-native-star-rating": "^1.1.0",
    "react-native-svg": "13.4.0",
    "react-native-use-keyboard-height": "^0.1.1",
    "react-native-webview": "11.26.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.0.27",
    "@types/react-native": "~0.70.6",
    "typescript": "^4.9.4"
  }

**Comment by BirukMengistu** [comment]
![image](https://github.com/expo/eas-cli/assets/27973561/96fe59a4-c0a7-450e-8a0b-7045079a6d23)
