### ISSUE TITLE
Eas build does not import secrets

### ISSUE THREAD

**Issue by suleymanbariseser** [expo/eas-cli#1735]
### Summary

I am using eas to build my expo application. My app contains some env files. They are api urls or some secret keys. I am putting api urls in eas.json directly and build imports them. I am putting secrets in expo.dev secret section. However, build does not import them. Btw, I am building app locally

### Managed or bare?

managed

### Environment

``` sh
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - /usr/local/bin/node
      Yarn: 1.22.18 - ~/.yarn/bin/yarn
      npm: 9.6.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.2 
      expo: ^46.0.14 => 46.0.16 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
      react-native-web: ~0.18.7 => 0.18.9 
    npmGlobalPackages:
      eas-cli: 3.6.0
    Expo Workflow: managed
```

```sh
Expected package @expo/config-plugins@^5.0.0
Found invalid:
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
```

### Reproducible demo or steps to reproduce from a blank project

upload env variables with `eas secret:push --scope project --env-file .env` then start to build app.

**Comment by wkozyra95** [comment]
Secrets by definition are secret, so we do not allow downloading them in any form. They are only available during cloud build, if you want to use them for the local build, you need to set those envs in your shell on your own.

Also note that secrets only set envs in your build environment, you need to have project configured correctlly to pass it to access them in js code of your application https://docs.expo.dev/guides/environment-variables/

**Comment by maxkrieger** [comment]
@wkozyra95 This is very unintuitive and contradicts documentation. See, for example, [here](https://docs.expo.dev/guides/environment-variables/#eas-build):

> [EAS Build](https://docs.expo.dev/build/introduction) uses Metro Bundler to build the JavaScript bundle embedded within your app binary, so it will use .env files uploaded with your build job to inline EXPO_PUBLIC_ variables into your code. EAS Build also lets you define environment variables within build profiles in eas.json and via EAS Secrets. Check out the EAS Build documentation on [environment variables and build secrets](https://docs.expo.dev/build-reference/variables) for more information.

The `--local` flag is *still* eas build (a salient difference being it's not billable by expo...). For all I would know, `eas secrets` maintains a parallel copy of secrets on my machines. It's undocumented behavior for `--local` to omit `.env` if it's right in the directory and **works on local development**!

**Comment by HialeahLiam** [comment]
I agree with @maxkrieger that this is very unintuitive. 

But in any case, [here's the part of the docs that states you can't use eas secrets when using EAS Build locally](https://docs.expo.dev/build-reference/local-builds/#limitations).

### Setting environment variable on linux/Mac
if you have a Mac like me, you can set your environment variable inside your `~/.zshrc` file to permanently set it across terminal sessions.
```bash
# somewhere in your .zshrc
export MY_SECRET=mysecretvalue
```

The value will now be available under `process.env`
