### ISSUE TITLE
iOS build for internal distribution fails 

### ISSUE THREAD

**Issue by b0n1q** [expo/eas-cli#1736]
### Summary

In managed workflow on SDK 47 with expo-document-picker and expo-notifications, fastlane fails in a profile having distribution: internal because of  value "Development" is not allowed for icloud-container-environment entitlement.

### Managed or bare?

Managed

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.2
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8609683
      Xcode: 13.0/13A233 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.0 => 0.17.4 
      expo: ^47.0.3 => 47.0.13 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ~0.18.10 => 0.18.12 
    Expo Workflow: managed

expo doctor
 Didn't find any issues with the project!

### Error output

error: exportArchive: exportOptionsPlist error for key "iCloudContainerEnvironment": value "Development" is not allowed
Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key "iCloudContainerEnvironment": value "Development" is not allowed" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key "iCloudContainerEnvironment": value "Development" is not allowed}
** EXPORT FAILED **
Exit status: 70

### Reproducible demo or steps to reproduce from a blank project

Try to build project using EAS and set in app.config.js

	config.plugins = [
		...config.plugins,
		[
			'expo-document-picker',
			{
				iCloudContainerEnvironment: isProduction() ? 'Production' : 'Development',
			},
		],
	]

**Comment by xgenem** [comment]
+1
