### ISSUE TITLE
Can't get 2FA verification code for Apple ID

### ISSUE THREAD

**Issue by andresespinosapc** [expo/eas-cli#1737]
### Summary

I'm trying to run `eas build`. When asking me to login, it also asks for Two-factor Authentication (2FA). I have 2FA enabled by phone call, if I try to login via web I do receive the phone call, but if I try through the eas-cli I don't receive any phone call.

As far as I know, Apple don't have an option to change the 2FA method to SMS one I have already configured it.

I've found that there's a way of getting a code from settings of a device, but if I enter that code into eas-cli it says "Invalid code". Here's the reference in the section "Receive a code from Settings on your trusted device": https://support.apple.com/en-gb/HT204974

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 3.6.0 - /usr/local/bin/fish
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
      Watchman: 2023.03.06.00 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.8
      react: 17.0.2 => 17.0.2
      react-dom: 17.0.2 => 17.0.2
      react-native: 0.68.2 => 0.68.2
      react-native-web: 0.17.7 => 0.17.7
    npmGlobalPackages:
      eas-cli: 2.5.1
    Expo Workflow: managed

Expected package @expo/config-plugins@^4.1.0
Found invalid:
  @expo/config-plugins@5.0.1
  @expo/config-plugins@2.0.4
  @expo/config-plugins@5.0.4
  @expo/config-plugins@5.0.4
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@^4.0.0
Found invalid:
  @expo/prebuild-config@5.0.3
  (for more info, run: npm why @expo/prebuild-config)

### Reproducible demo or steps to reproduce from a blank project

Put this in `eas.json`:

```
{
  "cli": {
    "version": ">= 0.50.0"
  },
  "build": {
    "preview": {
      "distribution": "internal",
      "channel": "preview",
    },
  },
  "submit": {
    "production": {}
  }
}
```

then run `yarn eas build --profile preview --platform ios` and try to login with an account that have 2FA enabled with phone call method.

**Comment by dsokal** [comment]
Duplicated issue. See https://github.com/expo/eas-cli/issues/1725
