### ISSUE TITLE
Swap Preparing credentials with Prebuild

### ISSUE THREAD

**Issue by TheBojda** [expo/eas-cli#1743]
### Build/Submit details page URL

https://expo.dev/accounts/thebojda/projects/my-app/builds/436f36a6-8043-4e06-a2bb-64b5aaf9f7c1

### Summary

My config plugin adds extensions to the iOS project, but the build system cannot sign it, because the "Preparing credentials" step is before "Prebuild", so the extensions do not exist in the credentials preparation phase. If the "Prebuild" step would be before the "Preparing credentials" step, it would solve the problem. I think it is a general problem if the config plugin generates extensions.

### Managed or bare?

managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    npmPackages:
      expo: ~48.0.6 => 48.0.6 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    Expo Workflow: managed

🎉 Didn't find any issues with the project!

### Reproducible demo or steps to reproduce from a blank project

The problem is clearly visible in the build: https://expo.dev/accounts/thebojda/projects/my-app/builds/436f36a6-8043-4e06-a2bb-64b5aaf9f7c1

If I run `npx expo prebuild` on the client side, the build process runs perfectly and generates the ipa: https://expo.dev/accounts/thebojda/projects/my-app/builds/f58e34d1-826b-4778-a4e3-1fa78524f06b

**Comment by wkozyra95** [comment]
https://docs.expo.dev/build-reference/app-extensions/

This is a guide on how to tell eas that prebuild will generate the additional target, and that cli need to provision additional credentials for them. You can specify those values directlly in app.json or inside config plugin. There are few plugins that already support that:
- https://github.com/OneSignal/onesignal-expo-plugin/blob/main/support/eas/getEasManagedCredentialsConfigExtra.ts
- https://github.com/bndkt/react-native-app-clip/blob/main/plugin/src/withConfig.ts 

or if you want to just provide credentials you have you can specify them in credentials. json https://docs.expo.dev/app-signing/local-credentials/#multi-target-project
