### ISSUE TITLE
EAS Build Error on 'Configure Xcode Project' Step

### ISSUE THREAD

**Issue by raineking** [expo/eas-cli#1747]
### Build/Submit details page URL

https://expo.dev/accounts/raineking/projects/sanctuary-mobile/builds/193f8f72-29b6-433d-bbdc-36b1662951ea

### Summary

I'm using a managed workflow with React Native/Expo on SDK46 and EAS version 3.8.0

I'm trying to publish my first EAS Build to the Apple Store after migrating from Classic Build but keep running into this error on the Configure Xcode project step in Expo

`Could not find target 'APP_NAME' in project.pbxproj`

and this error in the build step.

`Build failed
Could not find target 'APP_NAME' in project.pbxproj`

I've tried looking for this file to see if I can add my 'APP_NAME' in project.pbxproj but could not find it.

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.20 => 46.0.20 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.6 => 0.69.6 
    npmGlobalPackages:
      eas-cli: 3.7.2
      expo-cli: 6.3.2
    Expo Workflow: managed

### Error output

Configure Xcode Project error:

`Configuring Xcode project
Assigning provisioning profile '*[expo] 'PROFILE_NAME' AppStore 2023-03-15T18:59:14.382Z' (Apple Team ID: 'TEAM_NAME') to target 'APP_NAME'
Could not find target 'APP_NAME' in project.pbxproj`

Fail Build error:

`Build failed
Could not find target 'APP_NAME' in project.pbxproj`

### Reproducible demo or steps to reproduce from a blank project

`eas build --platform ios`

**Comment by wkozyra95** [comment]
name and slug on EAS Build worker are set to "build"

```
  "name": "build",
  "slug": "build",
```

so I suspect that you have some env variable set locally that is changing what is returned in app.config.ts and you did not set those values on the worker. You can use `env` field in eas.json for that.

https://docs.expo.dev/build-reference/variables/

**Comment by EricHasegawa** [comment]
@wkozyra95  We don't have a `.env` file and have not set environment variables anywhere else (to our knowledge). We tried to add our "name" and "slug" fields in the `env` field in `eas.json` and any relevant built-in environment variables from the link you sent but we are still getting the same error.

We added 

```     
"production": {
        "env": {
          "name": "Sanctuary",
          "slug": "sanctuary-mobile"
        }
      }
```
to `eas.json`, and also tried adding `"scheme": "sanctuarymobile"`, `"EAS_BUILD_ID": ...` and `"EAS_BUILD"=true`, _and_ `"name": "build"` and` "slug": "build"` for good measure.

None of this has worked and we are super confused about what to try next. What specifically do you recommend we put in our eas env section? In a similar issue you helped someone resolve this with environment variables (see [here](https://github.com/expo/eas-cli/issues/1574#issuecomment-1353877518)), but we're not sure which of them were set.

Any recommendations or help is appreciated!

**Comment by wkozyra95** [comment]
> What specifically do you recommend we put in our eas env section? 

I don't know what you have in your app.config.js/app.config.ts (I assume you are using one), but I expect you have sth like 
```
  slug: process.env.SOME_ENV_VARIABLE,
  name: process.env.SOME_OTHER_ENV,
  ...
```
you need to set those envs in eas.json


If you don't have anything like I described above, the other possibility is that you have something in your gitignore that excludes app.json/app.config.js/..., so the file is never uploaded to EAS Build worker.
