### ISSUE TITLE
can not read FLIPPER_VERSION

### ISSUE THREAD

**Issue by techamit95ch** [expo/eas-cli#1749]
### Build/Submit details page URL

https://expo.dev/accounts/amit_nonceblox/projects/om/builds/680c581d-3a23-42bd-9653-34984ecec954

### Summary

I am able to build apk locally using `cd  android && ./gradlew assembleRelease` command. but  `eas build -p android` getting error.  And I have declared everything in Gradle.properties

### Managed or bare?

bare

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.8.1 - /var/folders/78/nxhpt4nj39g0rhzw_qnpq8t80000gn/T/yarn--1679292107220-0.31122164537170205/node
      Yarn: 1.22.19 - /var/folders/78/nxhpt4nj39g0rhzw_qnpq8t80000gn/T/yarn--1679292107220-0.31122164537170205/yarn
      npm: 9.5.1 - /opt/homebrew/bin/npm
      Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 23, 29, 30, 31, 32, 33
        Build Tools: 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-32 | Google APIs ARM 64 v8a, android-32 | Google APIs Intel x86 Atom_64, android-32 | Google Play ARM 64 v8a, android-32 | Google Play Intel x86 Atom_64, android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.6 => 48.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
    npmGlobalPackages:
      eas-cli: 3.8.1
    Expo Workflow: bare

✨  Done in 4.66s.

### Error output

Mon, 20 Mar 2023 05:53:15 GMT
Running 'gradlew :app:bundleRelease' in /home/expo/workingdir/build/android
2
Mon, 20 Mar 2023 05:53:16 GMT
Downloading https://services.gradle.org/distributions/gradle-7.5.1-all.zip
3
Mon, 20 Mar 2023 05:53:18 GMT
10%
4
Mon, 20 Mar 2023 05:53:18 GMT
20%.
5
Mon, 20 Mar 2023 05:53:18 GMT
30%.
6
Mon, 20 Mar 2023 05:53:18 GMT
40%.
7
Mon, 20 Mar 2023 05:53:18 GMT
50%.
8
Mon, 20 Mar 2023 05:53:18 GMT
60%.
9
Mon, 20 Mar 2023 05:53:18 GMT
70%.
10
Mon, 20 Mar 2023 05:53:18 GMT
80%.
11
Mon, 20 Mar 2023 05:53:19 GMT
90%.
12
Mon, 20 Mar 2023 05:53:19 GMT
100
13
Mon, 20 Mar 2023 05:53:19 GMT
%
14
Mon, 20 Mar 2023 05:53:21 GMT
Welcome to Gradle 7.5.1!
15
Mon, 20 Mar 2023 05:53:21 GMT
Here are the highlights of this release:
16
Mon, 20 Mar 2023 05:53:21 GMT
 - Support for Java 18
17
Mon, 20 Mar 2023 05:53:21 GMT
 - Support for building with Groovy 4
18
Mon, 20 Mar 2023 05:53:21 GMT
- Much more responsive continuous builds
19
Mon, 20 Mar 2023 05:53:21 GMT
- Improved diagnostics for dependency resolution
20
Mon, 20 Mar 2023 05:53:21 GMT
For more details see https://docs.gradle.org/7.5.1/release-notes.html
21
Mon, 20 Mar 2023 05:53:22 GMT
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.5.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
22
Mon, 20 Mar 2023 05:53:23 GMT
Daemon will be stopped at the end of the build
23
Mon, 20 Mar 2023 05:54:25 GMT
> Task :react-native-gradle-plugin:pluginDescriptors
24
Mon, 20 Mar 2023 05:54:25 GMT
> Task :react-native-gradle-plugin:processResources
25
Mon, 20 Mar 2023 05:54:40 GMT
> Task :react-native-gradle-plugin:compileKotlin
26
Mon, 20 Mar 2023 05:54:40 GMT
> Task :react-native-gradle-plugin:compileJava NO-SOURCE
27
Mon, 20 Mar 2023 05:54:40 GMT
> Task :react-native-gradle-plugin:classes
28
Mon, 20 Mar 2023 05:54:40 GMT
> Task :react-native-gradle-plugin:inspectClassesForKotlinIC
29
Mon, 20 Mar 2023 05:54:40 GMT
> Task :react-native-gradle-plugin:jar
30
Mon, 20 Mar 2023 05:54:52 GMT
[stderr] 
FAILURE: Build failed with an exception.
31
Mon, 20 Mar 2023 05:54:52 GMT
[stderr] 
* Where:
32
Mon, 20 Mar 2023 05:54:52 GMT
[stderr] 
Build file '/home/expo/workingdir/build/android/app/build.gradle' line: 230
33
Mon, 20 Mar 2023 05:54:52 GMT
[stderr] 
* What went wrong:
34
Mon, 20 Mar 2023 05:54:52 GMT
[stderr] 
A problem occurred evaluating project ':app'.
35
Mon, 20 Mar 2023 05:54:52 GMT
[stderr] 
> Could not get unknown property 'FLIPPER_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
36
Mon, 20 Mar 2023 05:54:52 GMT
[stderr] 
* Try:
37
Mon, 20 Mar 2023 05:54:52 GMT
[stderr] 
> Run with --stacktrace option to get the stack trace.
38
Mon, 20 Mar 2023 05:54:52 GMT
[stderr] 
> Run with --info or --debug option to get more log output.
39
Mon, 20 Mar 2023 05:54:52 GMT
[stderr] 
> Run with --scan to get full insights.
40
Mon, 20 Mar 2023 05:54:52 GMT
[stderr] 
* Get more help at https://help.gradle.org
41
Mon, 20 Mar 2023 05:54:52 GMT
[stderr] 
BUILD FAILED in 1m 36s
42
Mon, 20 Mar 2023 05:54:52 GMT
5 actionable tasks: 5 executed
43
Mon, 20 Mar 2023 05:54:52 GMT
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

### Reproducible demo or steps to reproduce from a blank project

Currently can't share any links.

**Comment by wkozyra95** [comment]
make sure all the files that define properties you are using during a build are committed into git, otherwise, those files will not get uploaded to EAS Build worker.

To verify what is uploaded you can use `eas build:inspect --stage archive`

**Comment by wkozyra95** [comment]
Also if it was not a typo `Gradle.properties` should be named `gradle.properties`. it will work on macOS because the filesystem there is not case-sensitive, but it will not work EAS Build because it's on linux(case-sensitive filesystem).
