### ISSUE TITLE
EAS Build ARCHIVE FAILED Exit Status 65 on iOS Only with No Error Message

### ISSUE THREAD

**Issue by gtwilliams03** [expo/eas-cli#1751]
### Build/Submit details page URL

https://expo.dev/accounts/gtwilliams03/projects/severedlinks-react-native-app/builds/db0bf983-ae46-4f8d-9467-293fa805bd26

### Summary

This issue has had me down a month with one of my apps moving to SDK 48.  The build fails with `ARCHIVE FAILED Exit status: 65` but has no error message at the end of the `eas-cli` log output.  I am totally baffled.  I have ripped packages out of this codebase, deleted package.lock and node_modules and reinstalled them a I still get the error.  The Android build works fine.

The strange thing is there is no error message between the pair of `ARCHIVE FAILED` notices at the end of the log and no errors in the xcode log download.  It's just like it gets right to the end of the build and then dies on the last step.

### Managed or bare?

Managed

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
      npm: 9.6.2 - ~/.nvm/versions/node/v18.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.3.0 
      expo: ^48.0.7 => 48.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.11 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 6.3.2
    Expo Workflow: managed
```

```
» android: sentry-expo: No Sentry config found in app.json, builds will fall back to environment variables. Refer to @sentry/react-native docs for how to configure this.
» ios: sentry-expo: No Sentry config found in app.json, builds will fall back to environment variables. Refer to @sentry/react-native docs for how to configure this.
🎉 Didn't find any issues with the project!
```

### Error output

The strange thing is that there is no error message at the end of the `eas-cli` build log:

```
› Generating debug SeveredLinks » SeveredLinks.app.dSYM
› Executing SeveredLinks » Bundle React Native code and images
    the transform cache was reset.
› Executing SeveredLinks » [CP] Copy Pods Resources
› Executing SeveredLinks » Upload Debug Symbols to Sentry
› Executing SeveredLinks » [CP] Embed Pods Frameworks
› Signing   SeveredLinks » SeveredLinks.app
› Creating  SeveredLinks » SeveredLinks.app
    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
▸ ** ARCHIVE FAILED **
** ARCHIVE FAILED **
Exit status: 65
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.211.0                 |
| sdk         | iPhoneOS16.2.sdk        |
+-------------+-------------------------+
Looks like fastlane ran into a build/archive error with your project
It's hard to tell what's causing the error, so we wrote some guides on how
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make
sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the
the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there
[stderr] 
[!] Error building the application - see the log above
```

### Reproducible demo or steps to reproduce from a blank project

I actually cannot reproduce this since I have a second Expo eas build project for a different app that builds just fine.

**Comment by gtwilliams03** [comment]
I rolled the same code base back to SDK 47 and it built fine.

**Comment by gtwilliams03** [comment]
I'll leave the solution here in case it helps anyone else find a needle in a haystack.  I had a few warnings about duplicate property values being assigned.  I kind of ignored them since they were just warnings.  But I was still getting the `Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure` error without any actual errors in the fastlane or Xcode logs.  Turns out, if you happen to assign an `error:` property twice (i.e., `the property "error" was set multiple times in the object definition `), the warning actually causes an error to be emitted (which is why there was no error message).  Resolving this warning (even though there were a number of other duplicate assignment warnings), fixed the build.

```
/Users/expo/Library/Developer/Xcode/DerivedData/SeveredLinks-chtbwvsetxaswpbmirjommfynwra/Build/Intermediates.noindex/ArchiveIntermediates/SeveredLinks/BuildProductsPath/Release-iphoneos/main.jsbundle:74489:7: warning: the property "error" was set multiple times in the object definition.
      error: null,
      ^~~~~~~~~~~
/Users/expo/Library/Developer/Xcode/DerivedData/SeveredLinks-chtbwvsetxaswpbmirjommfynwra/Build/Intermediates.noindex/ArchiveIntermediates/SeveredLinks/BuildProductsPath/Release-iphoneos/main.jsbundle:74478:7: note: The first definition was here.
      error: {},
      ^~~~~~~~~

```

**Comment by zhzhf** [comment]
same issuss

**Comment by pfcodes** [comment]
This is happening to me too:

```
The following build commands failed:
	PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry /Users/expo/Library/Developer/Xcode/DerivedData/NOVADev-ansmewtojbpbuoejawopctydukzh/Build/Intermediates.noindex/ArchiveIntermediates/NOVADev/IntermediateBuildFilesPath/NOVADev.build/Debug-iphoneos/NOVADev.build/Script-5248EFF0623645EB8FA90864.sh (in target 'NOVADev' from project 'NOVADev')
(1 failure)
Exit status: 65
```

**Comment by akash-jadhav** [comment]
```
The following build commands failed:
	CompileC .......IntermediateBuildFilesPath/Pods.build/Release-iphoneos/RNDateTimePicker.build/Objects-normal/arm64/RNDateTimePickerShadowView.o /Users/expo/workingdir/build/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNDateTimePicker' from project 'Pods')
(1 failure)

Exit status: 65
```

**Comment by mikeRChambers610** [comment]
I am getting the same issue after going from SDK 49 to 50 and 51.

**Comment by mikeRChambers610** [comment]
@brentvatne Hey Breant do you know if there is any fix for this? I am still getting this issue in SDK 50 and 51. 

This is my error:   export var __INTERNAL_VIEW_CONFIG = {
  ^ export declaration must be at top level of module
(warning truncated)
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/EventWithFriends-drjrphfpgnpkpjfncndmgyxizedi/Build/Intermediates.noindex/ArchiveIntermediates/EventWithFriends/IntermediateBuildFilesPath/EventWithFriends.build/Release-iphoneos/EventWithFriends.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'EventWithFriends' from project 'EventWithFriends')
▸ (1 failure)
** ARCHIVE FAILED **
The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/EventWithFriends-drjrphfpgnpkpjfncndmgyxizedi/Build/Intermediates.noindex/ArchiveIntermediates/EventWithFriends/IntermediateBuildFilesPath/EventWithFriends.build/Release-iphoneos/EventWithFriends.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'EventWithFriends' from project 'EventWithFriends')
(1 failure)

Exit status: 65
+---------------------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.219.0                 |
| sdk         | iPhoneOS17.4.sdk        |
+-------------+-------------------------+
Looks like fastlane ran into a build/archive error with your project
It's hard to tell what's causing the error, so we wrote some guides on how
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make
sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the
the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there
[!] Error building the application - see the log above
Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.
