### ISSUE TITLE
Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com

### ISSUE THREAD

**Issue by Gibson10** [expo/eas-cli#1761]
### Summary

I am trying to build my app using eas cli. When I type `eas build --platform ios` expo asks whether "Do you want to log in to your Apple account?" Whether i select no or yes I am prompted to sign in with apple and then  i always get the same error 
"Authentication with Apple Developer Portal failed!
Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
Cryptic error? Learn more: https://expo.fyi/cryptic-error-eas"I have tried anything i could think of but its like a constant loop.
 

### Managed or bare?

managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.18.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/Documents/GitHub/apera/apera_applicatio_ios/node_modules/.bin/yarn
      npm: 9.6.2 - ~/Documents/GitHub/apera/apera_applicatio_ios/node_modules/.bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7935034
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 9.0.2 => 9.0.2 
      expo: ^46.0.0 => 46.0.0 
      react: ^18.0.0 => 18.0.0 
      react-dom: ^18.0.0 => 18.0.0 
      react-native: ^0.68.2 => 0.68.2 
      react-native-web: ^0.18.7 => 0.18.7 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 3.5.1
      expo-cli: 6.0.8
    Expo Workflow: bare

### Error output

Authentication with Apple Developer Portal failed!
Error: Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
Cryptic error? Learn more: https://expo.fyi/cryptic-error-eas

### Reproducible demo or steps to reproduce from a blank project

eas build --platform ios

**Comment by dsokal** [comment]
Can you please upgrade to the latest eas-cli and let me know if the issue goes away?

**Comment by zdnk** [comment]
I have the same issue on eas-cli 3.9.0

**Comment by evelant** [comment]
Also seeing this on 3.9.0. Can't make ios builds. @dsokal here's the issue from the last time this happened back in Feb https://github.com/expo/eas-cli/issues/1672

**Comment by dsokal** [comment]
Sorry for the inconvenience. A potential bugfix has been implemented in https://github.com/expo/eas-cli/releases/tag/v3.9.1. Please upgrade EAS CLI and let me know if this fixes the issue for you.

**Comment by szdziedzic** [comment]
I think It was resolved in https://github.com/expo/eas-cli/releases/tag/v3.9.1

**Comment by paule89123** [comment]
I've just started getting this error. I've upgraded to the latest eas-cli, but that didn't help.

**Comment by bradyllewis** [comment]
I just started getting this error today, as well. Insanely frustrating.

**Comment by tonyex3labs** [comment]
Same error eas-cli/7.1.3 darwin-arm64 node-v18.17.1

**Comment by Luis-ERP** [comment]
Same here 
eas-cli/7.1.3 darwin-arm64 node-v18.14.2

**Comment by xvision-solutions** [comment]
same here:

eas-cli/7.1.3 darwin-arm64 node-v20.9.0

**Comment by mikelCabezas** [comment]
same here... any eas-cli version

**Comment by evelant** [comment]
This seems to happen every few months when apple changes something on their servers. https://github.com/expo/eas-cli/issues/1672

**Comment by sykbn1** [comment]
Same issue here. 

eas-cli/7.1.3 darwin-arm64 node-v18.17.1

**Comment by mikelCabezas** [comment]
best solution I found... 
first prebuild with expo: 
`npx expo prebuild`
open in xcode, and archive for generate a distribuible app.
![Screenshot 2024-02-10 at 23 51 36](https://github.com/expo/eas-cli/assets/65063248/368520eb-50eb-4c2e-8487-47fa51a6964a)
