### ISSUE TITLE
EAS build failed after add another app icon set on Xcode

### ISSUE THREAD

**Issue by felixliu226** [expo/eas-cli#1762]
### Build/Submit details page URL

https://expo.dev/accounts/felixliu_labviso/projects/jcthplus/builds/d0af297f-98e0-43e9-85eb-5822107d7296

### Summary

I want to run an A/B test for different app icons on app store.

The app was built successfully with eas-cli. However, after I added another set of app icons in Xcode manually, and set Include All App Icon Asset to true. When I build the app again it failed with following message: 

```
The following build commands failed:
	CompileAssetCatalog /Users/expo/Library/Developer/Xcode/DerivedData/[appname]-drnjgfedkbhctrfrorjtenrunmdh/Build/Intermediates.noindex/ArchiveIntermediates/[appname]/InstallationBuildProductsLocation/Applications/[appname].app /Users/expo/workingdir/build/ios/[appname]/Images.xcassets (in target '[appname]' from project '[appname]')
```

### Managed or bare?

managed

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.8.1 - /opt/homebrew/bin/node
      Yarn: 3.4.1 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.12.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.4 => 48.0.4
      react: 18.2.0 => 18.2.0
      react-dom: ^18.2.0 => 18.2.0
      react-native: 0.71.4 => 0.71.4
      react-native-web: ^0.18.12 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.8.1
      expo-cli: 6.3.2
    Expo Workflow: bare

### Error output

The following build commands failed:
`	CompileAssetCatalog /Users/expo/Library/Developer/Xcode/DerivedData/[appname]-drnjgfedkbhctrfrorjtenrunmdh/Build/Intermediates.noindex/ArchiveIntermediates/[appname]/InstallationBuildProductsLocation/Applications/[appname].app /Users/expo/workingdir/build/ios/[appname]/Images.xcassets (in target '[appname]' from project '[appname]')`

### Reproducible demo or steps to reproduce from a blank project

1. create a blank project with icon 
2. open Xcode, add another app icon set, and Change the Include All App Icon Asset to Yes
3. build the project with `eas build`

**Comment by dsokal** [comment]
You can find the actual error in Xcode logs:

<img width="1263" alt="Screenshot 2023-04-03 at 11 40 45" src="https://user-images.githubusercontent.com/5256730/229472756-6c5d5e03-1f2d-4334-bb12-9301e4de2a28.png">

Search for `/* com.apple.actool.errors */`
