### ISSUE TITLE
EAS Update pushing updates from internal builds

### ISSUE THREAD

**Issue by pyrsmk** [expo/eas-cli#1763]
### Build/Submit details page URL

https://expo.dev/accounts/wizville_team/projects/WizvilleMobileDevelop

### Summary

We built Android and iOS apps for internal distribution and it appeared that some of our users had updates from EAS Update even if we did not run any EAS Update command. We have even no channels and no branches, and no mentions that something has been pushed to our users.

FWI: we are currently pushing a new version with `updates: { enabled: false }` to the stores.

### Managed or bare?

Managed

### Environment

```  
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /Users/aurelien/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.12 => 47.0.13
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.5 => 0.70.5
      react-native-web: ~0.18.9 => 0.18.12
    Expo Workflow: managed
```

```
Expected package expo-modules-autolinking@~1.0.0
Found invalid:
  expo-modules-autolinking@0.8.1
  (for more info, run: npm why expo-modules-autolinking)
Expected package @expo/config-plugins@^5.0.2
Found invalid:
  @expo/config-plugins@4.1.5
  @expo/config-plugins@4.1.5
  @expo/config-plugins@6.0.0
  @expo/config-plugins@4.1.1
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@^5.0.5
Found invalid:
  @expo/prebuild-config@4.0.3
  (for more info, run: npm why @expo/prebuild-config)
```

### Reproducible demo or steps to reproduce from a blank project

We built new internal apps with a previous version of our code, with the same process, and the impacted users don't seem to have this update. Hence, we don't know how to reproduce this.

**Comment by wkozyra95** [comment]
Your project is not configured for EAS Update, so if your users got an update it was using classic updates.

Classic update could be triggered by running `expo publish`, or `expo build:ios`/`expo build:android`. `expo build:*` commands do not work anymore, because classic build service was shutdown already in favor of EAS Build, but old build process did run publish before build, which is still succeeding.

Also if you are not using updates, why did you have `expo-updates package installed?
