### ISSUE TITLE
is there any way to not send the apk or aab to the expo, i just want to send it to the store

### ISSUE THREAD

**Issue by mrsants** [expo/eas-cli#1765]
### Do you understand that any feature requests opened in this repository will be closed?

Yes

**Comment by wkozyra95** [comment]
Yes go to https://play.google.com/console/developers/

**Comment by mrsants** [comment]
> Sim, vá para https://play.google.com/console/developers/ e faça o upload lá

great shitty answer, adjust the documentation you piece of shit

**Comment by wkozyra95** [comment]
Language like this is not acceptable. My answer to your question contained all information you needed, if you are not using EAS to upload your app to the store then you should follow Play Store documentation, there is nothing missing in our docs in that aspect.
