### ISSUE TITLE
Using eas build --local : Command "expo doctor" failed.

### ISSUE THREAD

**Issue by linaia** [expo/eas-cli#1778]
### Build/Submit details page URL

--local

### Summary

After solving this issue, I have this error displayed after the script runs expo-doctor : 

`[RUN_EXPO_DOCTOR] Command "expo doctor" failed.
Error: bash -c /Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/expo-cli/bin/expo.js doctor exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)`

### Managed or bare?

bare

### Environment

```
expo doctor
Expected package @expo/config-plugins@~6.0.0
Found invalid:
  @expo/config-plugins@5.0.4
  (for more info, run: npm why @expo/config-plugins)

npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.20.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.4 - /usr/local/bin/npm
      Watchman: 2022.12.12.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.10 => 48.0.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
    npmGlobalPackages:
      eas-cli: 3.9.0
      expo-cli: 6.0.8
    Expo Workflow: bare
```

### Error output

```
[RUN_EXPO_DOCTOR] Running "expo doctor"
[RUN_EXPO_DOCTOR] - Finding all copies of expo-modules-autolinking
[RUN_EXPO_DOCTOR] - Finding all copies of @expo/config-plugins
[RUN_EXPO_DOCTOR] [10:42:51] Expected package @expo/config-plugins@~6.0.0
[RUN_EXPO_DOCTOR] [10:42:51] Found invalid:
[RUN_EXPO_DOCTOR] [10:42:51]   @expo/config-plugins@5.0.4
[RUN_EXPO_DOCTOR] [10:42:51]   (for more info, run: npm why @expo/config-plugins)
[RUN_EXPO_DOCTOR] - Finding all copies of @expo/prebuild-config
[RUN_EXPO_DOCTOR] - Finding all copies of @unimodules/core
[RUN_EXPO_DOCTOR] - Finding all copies of @unimodules/react-native-adapter
[RUN_EXPO_DOCTOR] - Finding all copies of react-native-unimodules
[RUN_EXPO_DOCTOR] Command "expo doctor" failed.
Error: bash -c /Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/expo-cli/bin/expo.js doctor exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
    ...
    at spawnAsync (/Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawn (/Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/turtle-spawn/dist/index.js:27:47)
    at BuildContext.runGlobalExpoCliCommandAsync [as runGlobalExpoCliCommand] (/Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/eas-cli-local-build-plugin/dist/expoCli.js:14:39)
    at runExpoCliCommand (/Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/utils/project.js:23:20)
    at runExpoDoctor (/Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/common/setup.js:75:57)
    at /Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/common/setup.js:58:42
    at BuildContext.runBuildPhase (/Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/context.js:83:34)
    at setupAsync (/Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/common/setup.js:56:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async buildAsync (/Users/linaia/.npm/_npx/ac2fe9123ebf2e7d/node_modules/@expo/build-tools/dist/builders/android.js:19:5)

```

### Reproducible demo or steps to reproduce from a blank project

not yet

**Comment by linaia** [comment]
Using `npm why @expo/config-plugins`, I can see which package relies on @expo/config-plugins@5.0.4 : @react-native-firebase

`
@expo/config-plugins@5.0.4
node_modules/@react-native-firebase/app/node_modules/@expo/config-plugins
  @expo/config-plugins@"^5.0.4" from @react-native-firebase/app@17.4.2
  node_modules/@react-native-firebase/app
    @react-native-firebase/app@"^17.4.2" from the root project
    peer @react-native-firebase/app@"17.4.2" from @react-native-firebase/analytics@17.4.2
    node_modules/@react-native-firebase/analytics
      @react-native-firebase/analytics@"^17.4.2" from the root project
    peer @react-native-firebase/app@"17.4.2" from @react-native-firebase/messaging@17.4.2
    node_modules/@react-native-firebase/messaging
      @react-native-firebase/messaging@"^17.4.2" from the root project
`

**Comment by royscript** [comment]
lo pudiste solucionar? estoy en la misma

**Comment by royscript** [comment]
did you try with "npm audit fix --force"?

**Comment by linaia** [comment]
@royscript I'm using yarn not npm ;) how can I run this in the context of .npm/_npx/ ?

**Comment by wkozyra95** [comment]
When expo doctor fails the rest of the build process continues, so this log is not a reason for error and I suspect this is not the last line of cli output. Please provide complete logs and specify what the problem actually is, based on the issue description I don't even if the build failed or not.

> I can see which package relies on @expo/config-plugins@5.0.4 : react-native-firebase

So update that package to make sure it depends on the expected version of config-plugins.

**Comment by linaia** [comment]
updating seems to be on his way : https://github.com/invertase/react-native-firebase/pull/7029

**Comment by AntoRoshanm** [comment]
Command "expo doctor" failed.npx -y expo-doctor exited with non-zero code: 1 

This problem will appear when I execute the react native alter the apk.how to deal with this

**Comment by Aihcode** [comment]
Hola chicos la solución es ejecutar npx expo install --check desde la terminal PowerShell en windows y en Linux modo sudo user

**Comment by Aihcode** [comment]
Recuerden volver hacer login con eas y una vez ejecutado todo antes del crear su build ejecuten npx -y expo-doctor, 🍀 suerte y adelante!!

**Comment by Aihcode** [comment]
@linaia , I apologize for my previous comment. I only saw the message in Spanish on my phone, but thank you for providing the translation.

**Comment by jeisoncaguana** [comment]
Lo solucione de la siguiente manera (En macOS y Linux)

**El error**
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/01a8fe24-378e-45dd-9540-42214e54b0a2" />


**Mi solución:**
1. rm -rf node_modules
2. rm -rf package-lock.json 
3. npm install
4. npx expo install --check 
5. eas build:configure
6. eas build --platform android

![image](https://github.com/user-attachments/assets/db10ac7c-108a-4348-88c6-7dc3c51c8e3e)


**Nota**: El error de expo doctor se mantiene pero eh podido continuar apesar de ello
<img width="990" alt="image" src="https://github.com/user-attachments/assets/0b460770-7d67-44a0-9327-53e1342f3d8d" />
