### ISSUE TITLE
Android emulator frozen by saying yes to "Install and run the Android build on an emulator?"

### ISSUE THREAD

**Issue by Slapbox** [expo/eas-cli#1785]
### Summary

Android emulator frozen by saying yes to "Install and run the Android build on an emulator?"
If the emulator is already running, this will freeze it requiring a reboot.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
      Shell: 5.9 - /usr/bin/zsh
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
      Watchman: 4.9.0 - /usr/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 31, 32, 33
        Build Tools: 30.0.3, 31.0.0, 33.0.0
        System Images: android-31 | Google APIs Intel x86_64 Atom, android-31 | Google Play Intel x86 Atom_64
    npmPackages:
      expo: ~48.0.0 => 48.0.10 
      react-native: 0.71.6 => 0.71.6 
    npmGlobalPackages:
      eas-cli: 3.9.1
      expo-cli: 6.3.2
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by szdziedzic** [comment]
Which version of Android Studio are you using?

**Comment by szdziedzic** [comment]
Unfortunately, I wasn't able to reproduce this issue so far. I was testing it both on Linux and MacOS but haven't noticed any freezing happening to the emulator. I was also using different Android Studio versions when testing. Did you notice this issue for multiple different apps by any chance? Also, does our CLI print any output after saying `yes` in this case?

**Comment by Slapbox** [comment]
I'll keep a lookout for this and update next time it occurs - we don't rebuild terribly often.

In our case I think an old version of the app may still have been open on the emulator - I'm not sure if that's relevant.

**Comment by Slapbox** [comment]
Can't reproduce with Android Studio Flamingo.
