### ISSUE TITLE
EAS build failing while running gradlew locally

### ISSUE THREAD

**Issue by marcodluz** [expo/eas-cli#1786]
### Summary

I want to build my app locally using eas build, but expo is throwing error while running gradlew.

I have built for iOS with no problems, and it's already available on the AppStore. But Android is being more complicated.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
      Watchman: 2023.04.10.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 33, 33
        Build Tools: 30.0.3, 33.0.2
        System Images: android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.10 => 48.0.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.6 => 0.71.6
      react-native-web: ~0.18.7 => 0.18.12
    npmGlobalPackages:
      eas-cli: 3.9.1
      expo-cli: 6.3.2
    Expo Workflow: bare

✔ Validating global prerequisites versions passed
✔ Checking for incompatible packages passed
✔ Checking for conflicting global packages in project passed
✔ Verifying prebuild support package versions are compatible passed
✔ Checking dependency versions for compatibility with the installed Expo SDK passed
✖ Validating Expo Config failed
Issues:
  Error: Problem validating fields in app.json. Learn more.
   • Field: android/adaptiveIcon - must be object.
✔ Checking package.json for common issues passed

✖ Found one or more possible issues with the project. See above logs for issues and advice to resolve.

### Error output

[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:mergeReleaseResources'.
[RUN_GRADLEW] > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
[RUN_GRADLEW]    > Resource compilation failed (Failed to compile values resource file /private/var/folders/56/0997kkxx5db8vxjt45wlx2pw0000gn/T/eas-build-local-nodejs/640d687b-28b0-4543-a537-fa866709e8d0/build/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values/values.xml. Cause: java.lang.IllegalStateException: Can not extract resource from com.android.aaptcompiler.ParsedResource@560a3bb9.,Can not extract resource from com.android.aaptcompiler.ParsedResource@6ac09bf4.,Can not extract resource from com.android.aaptcompiler.ParsedResource@73e82976.). Check logs for more details.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] 2: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] java.lang.StackOverflowError (no error message)
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 2m 48s
[RUN_GRADLEW] Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
[RUN_GRADLEW] You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
[RUN_GRADLEW] See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
[RUN_GRADLEW] Execution optimizations have been disabled for 5 invalid unit(s) of work during this build to ensure correctness.
[RUN_GRADLEW] Please consult deprecation warnings for more details.
[RUN_GRADLEW] 158 actionable tasks: 158 executed
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.

### Reproducible demo or steps to reproduce from a blank project

My project: https://github.com/marcodluz/Reciply

Build command: eas build -p android --local --clear-cache

**Comment by marcodluz** [comment]
Does anyone has any recommendation? I really need this to work asp

**Comment by szdziedzic** [comment]
@marcodluz Did you check https://stackoverflow.com/questions/72335789/can-not-extract-resource-from-com-android-aaptcompiler? I might be wrong, but it looks like you might have a similar issue.

**Comment by marcodluz** [comment]
> @marcodluz Did you check https://stackoverflow.com/questions/72335789/can-not-extract-resource-from-com-android-aaptcompiler? I might be wrong, but it looks like you might have a similar issue.

Thank you! It worked. 

Apparently it was something related to my colours. I have changed everything for HEX and changed the "transparent" to "rgba(0, 0, 0, 0)".
I have also changed everything with exclamation points and interrogation points inside strings from "?" "!" to "\?" "\!".

**Comment by CristianFigueredo** [comment]
in my case, i had hsl values in my app.json. this works on ios but not on android.

**Comment by okekolawolesunday009** [comment]
am facing the same issue now
