### ISSUE TITLE
eas build Failed. [ios.infoPlist]: withIosInfoPlistBaseMod: [@react-native-firebase/auth] Your app.json file is missing ios.googleServicesFile. Please add this field.

### ISSUE THREAD

**Issue by GoldMyr1994** [expo/eas-cli#1789]
### Build/Submit details page URL

https://expo.dev/accounts/mauroconte/projects/mauroconteeasissue/builds/cdb047eb-26fc-4c0b-8866-8d60d3f25a8c

### Summary

EXPECTED
Expect that the eas build --platform ios starts a build on eas server.
Expect that the build starts as the one for android that starts correctly.

ACTUAL
The eas build is not starting giving error: Error: [ios.infoPlist]: withIosInfoPlistBaseMod: [@react-native-firebase/auth] Your app.json file is missing ios.googleServicesFile. Please add this field.

MORE INFO
looking at the android build process at the step 'Read app config' it is possible to see that google files are correctly imported from eas secrets and placed in the app.config
```
 "ios": {
    "bundleIdentifier": "com.mauroconteeasissue",
    "supportsTablet": true,
    "googleServicesFile": "/home/expo/workingdir/environment-secrets/598d1e5e-150d-476a-9264-6270b4964e98"
  },
  "android": {
    "package": "com.mauroconteeasissue",
    "adaptiveIcon": {
      "foregroundImage": "./assets/adaptive-icon.png",
      "backgroundColor": "#ffffff"
    },
    "googleServicesFile": "/home/expo/workingdir/environment-secrets/e0b316db-4b6e-4f1e-a76b-e9f7fd9a71dd"
  },
```

### Managed or bare?

Managed

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.15.0 - /opt/hostedtoolcache/node/18.15.0/x64/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.0 - /opt/hostedtoolcache/node/18.15.0/x64/bin/npm
    SDKs:
      Android SDK:
        API Levels: 27, 28, 29, 30, 31, 32, 33, 33, 33
        Build Tools: 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1, 33.0.2
        Android NDK: 25.2.9519653
    npmPackages:
      expo: ~48.0.[10](https://github.com/GoldMyr1994/mauroconteeasissue/actions/runs/4690277689/jobs/8313155784#step:6:11) => 48.0.10 
      react: [18](https://github.com/GoldMyr1994/mauroconteeasissue/actions/runs/4690277689/jobs/8313155784#step:6:19).2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    Expo Workflow: managed
```

```
- Validating global prerequisites versions...
✔ Validating global prerequisites versions passed
- Checking for incompatible packages...
✔ Checking for incompatible packages passed
- Checking for conflicting global packages in project...
✔ Checking for conflicting global packages in project passed
- Verifying prebuild support package versions are compatible...
✔ Verifying prebuild support package versions are compatible passed
- Checking dependency versions for compatibility with the installed Expo SDK...
✔ Checking dependency versions for compatibility with the installed Expo SDK passed
- Validating Expo Config...
- Validating Expo Config...
NOT SUPPORTED: option format. `validateFormats: false` can be used instead.
✔ Validating Expo Config passed
- Checking package.json for common issues...
✔ Checking package.json for common issues passed
```

### Error output

Run EXPO_DEBUG=true eas build --platform=ios --profile=production --non-interactive
ios.infoPlist: withIntrospectionBaseMods ➜ withIosBaseMods ➜ withGeneratedBaseMods ➜ withIosInfoPlistBaseMod
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withVersion ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withBuildNumber ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withUsesNonExemptEncryption ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withScheme ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withRequiresFullScreen ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withOrientation ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withDisplayName ➜ withInfoPlist
ios.infoPlist: withIosExpoPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withGoogle ➜ withInfoPlist
ios.infoPlist: withStaticPlugin ➜ withRunOnce ➜ withDevClient ➜ withGeneratedIosScheme ➜ withInfoPlist
ios.infoPlist: withStaticPlugin ➜ withIosSplashScreen ➜ withPlugins ➜ withStaticPlugin ➜ withIosSplashInfoPlist ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosUserInterfaceStyle ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosRootViewBackgroundColor ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosFacebook ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosBranch ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withIosAdMob ➜ withInfoPlist
ios.infoPlist: withFallback ➜ withPlugins ➜ withStaticPlugin ➜ withMaps ➜ withGoogleMapsKey ➜ withInfoPlist
ios.infoPlist: withRnFirebaseAuth ➜ withPlugins ➜ withStaticPlugin ➜ withIosCaptchaUrlTypes ➜ withInfoPlist
[ios.infoPlist]: withIosInfoPlistBaseMod: [@react-native-firebase/auth] Your app.json file is missing ios.googleServicesFile. Please add this field.
Error: [ios.infoPlist]: withIosInfoPlistBaseMod: [@react-native-firebase/auth] Your app.json file is missing ios.googleServicesFile. Please add this field.
    at setUrlTypesForCaptcha (/home/runner/work/mauroconteeasissue/mauroconteeasissue/node_modules/@react-native-firebase/auth/plugin/build/ios/urlTypes.js:54:15)
    at /home/runner/work/mauroconteeasissue/mauroconteeasissue/node_modules/@react-native-firebase/auth/plugin/build/ios/urlTypes.js:14:16
    at action (/home/runner/work/mauroconteeasissue/mauroconteeasissue/node_modules/@react-native-firebase/auth/node_modules/@expo/config-plugins/build/plugins/ios-plugins.js:13[7](https://github.com/GoldMyr1994/mauroconteeasissue/actions/runs/4690277689/jobs/8313155784#step:7:8):22)
    at action (/home/runner/work/mauroconteeasissue/mauroconteeasissue/node_modules/@react-native-firebase/auth/node_modules/@expo/config-plugins/build/plugins/withMod.js:235:2[9](https://github.com/GoldMyr1994/mauroconteeasissue/actions/runs/4690277689/jobs/8313155784#step:7:10))
    at interceptingMod (/home/runner/work/mauroconteeasissue/mauroconteeasissue/node_modules/@react-native-firebase/auth/node_modules/@expo/config-plugins/build/plugins/withMod.js:[12](https://github.com/GoldMyr1994/mauroconteeasissue/actions/runs/4690277689/jobs/8313155784#step:7:13)6:27)
    at action (/opt/hostedtoolcache/eas-cli/3.9.2/x64/node_modules/@expo/config-plugins/build/plugins/withMod.js:240:[14](https://github.com/GoldMyr1994/mauroconteeasissue/actions/runs/4690277689/jobs/8313155784#step:7:15))
    at async interceptingMod (/opt/hostedtoolcache/eas-cli/3.9.2/x64/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:[21](https://github.com/GoldMyr1994/mauroconteeasissue/actions/runs/4690277689/jobs/8313155784#step:7:22))
    at async interceptingMod (/opt/hostedtoolcache/eas-cli/3.9.2/x64/node_modules/@expo/config-plugins/build/plugins/withMod.js:1[26](https://github.com/GoldMyr1994/mauroconteeasissue/actions/runs/4690277689/jobs/8313155784#step:7:27):21)
    at async interceptingMod (/opt/hostedtoolcache/eas-cli/3.9.2/x64/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    at async interceptingMod (/opt/hostedtoolcache/eas-cli/3.9.2/x64/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:21)
    Error: build command failed.
Error: Process completed with exit code 1.

### Reproducible demo or steps to reproduce from a blank project

npx create-expo-app mauroconteissue

Inside the project run eas build:configure
```
➜  mauroconteeasissue git:(main) ✗ eas build:configure
EAS project not configured.
✔ Would you like to automatically create an EAS project for @mauroconte/mauroconteeasissue? … yes
✔ Created @mauroconte/mauroconteeasissue on Expo
✔ Linked local project to EAS project 15bcc2cc-099c-488d-b4d9-9e13e6b1d255
💡 The following process will configure your iOS and/or Android project to be compatible with EAS Build. These changes only apply to your local project files and you can safely revert them at any time.

✔ Which platforms would you like to configure for EAS Build? › All

✔ Generated eas.json

🎉 Your project is ready to build.

- Run eas build when you are ready to create your first build.
- Once the build is completed, run eas submit to upload the app to app stores.
- Learn more about other capabilities of EAS Build
```

Create ExpoToken and add to GitHub repository secret.
Create .github/workflows/test.yml.

Create firebase project -> Enable authentication -> Enable phone provider.
Create android app > download google-services.json.
Create iOS app > download GoogleService-Info.plist.
Add these two files to the .gitignore.
Add these two files as files secret to the expo project via web.

yarn add expo-dev-client
Yarn add expo-build-properties
yarn add @react-native-firebase/app
yarn add @react-native-firebase/auth

npx expo customize metro.config.js

Update metro.config.js
Update app.json to app.config.json
Update eas.json
Update package.json by adding resolutions
yarn install

see [https://github.com/GoldMyr1994/mauroconteeasissue](https://github.com/GoldMyr1994/mauroconteeasissue)

**Comment by wkozyra95** [comment]
You did not specify that explicitly, but I assume you reached a successful build because you created a file locally under `/home/expo/workingdir/environment-secrets/598d1e5e-150d-476a-9264-6270b4964e98`, is that correct?

The issue is caused by validation in `@react-native-firebase/auth`, it happens not only when we run `prebuild` on the server, but also when the config is evaluated locally in cli before the build. This is not a plugin maintained by Expo, if you think this is not a correct behavior I recommend opening an issue in `https://github.com/invertase/react-native-firebase/`

To make it work locally you can use sth like `googleServicesFile: process.env.GOOGLE_SERVICE_INFO_PLIST ?? './path/to/fake/services.json'` in app.config.js. (Since you were able to build that I assume you already have sth like that)

**Comment by GoldMyr1994** [comment]
Thanks @wkozyra95 for replay.
Sorry to have opened the issue in here I will try to do the same in `https://github.com/invertase/react-native-firebase/` as you suggested.

A little bit more of explanation ...

No I did not create any local files under `/home/expo/workingdir/environment-secrets/598d1e5e-150d-476a-9264-6270b4964e98`.

The successful build is reached only for android. 
As you can see in the images i tried to run these 3 commands from github actions:
`EXPO_DEBUG=true eas build --platform=android --profile=production --non-interactive`
`EXPO_DEBUG=true eas build --platform=ios --profile=production --non-interactive`
`EXPO_DEBUG=true eas build --platform=all --profile=production --non-interactive`

<img width="1418" alt="Screenshot 2023-04-14 alle 10 34 05" src="https://user-images.githubusercontent.com/7756919/231991458-4d6bbb6a-4169-405e-b03c-46a9fee324e5.png">
<img width="1437" alt="Screenshot 2023-04-14 alle 10 35 53" src="https://user-images.githubusercontent.com/7756919/231991473-6dd6c5bf-6349-4e45-9327-bfe1a0592253.png">

Don't know why but android passes that validation step and the build starts on eas server, for ios that validation is failing.

I don't want to commit the google services files to the repository. 
I'm not able to get this working throught eas secrets, at least not for iOS.
I'm able to fix this by creating the needed files in the github actions using github secrets using diffent names from the ones ignored in gitignore othewise the files are not uploaded. 
Something like this in ghithub actions:
```
      - name: 📄 google-services.json
        run: 
          echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 --decode > gs.json;
          echo ${{ secrets.GOOGLE_SERVICES_JSON_DEV }}| base64 --decode > gs-dev.json;
      
      - name: 📄 GoogleService-Info.plist
        run: 
          echo ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }} | base64 --decode > gsi.plist;
          echo ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_DEV }} | base64 --decode > gsi-dev.plist;
```


Thanks again for the answer!

**Comment by wkozyra95** [comment]
> Don't know why but android passes that validation step and the build starts on eas server, for ios that validation is failing.

It seems they have validation only for ios. https://github.com/invertase/react-native-firebase/blob/514e6bd51e7624a6403dda706f4e5b65cee63422/packages/app/plugin/src/ios/googleServicesPlist.ts#L35

Given the above my previous suggestion should fix the issue for you. Just add 
`googleServicesFile: process.env.GOOGLE_SERVICE_INFO_PLIST ?? './path/to/fake/services.json'`
Locally it will resolve to some fake file(you need to create it, but it won't be used for anything), and on EAS Build worker it will value from secrets.

**Comment by utlandingur** [comment]
In case someone else stumbles upon this, the fix is and the route cause is pretty straight forward
RNF/auth looks for your file locally before it gets built on EAS.
However, once its being built by EAS in the cloud your secrets supersede and previously set values.

So.
ensure you are gitignoring your google services files
```
# Google Services files
./google-services.json
./GoogleService-Info.plist
```

Eas should not have any env variables set and looks something like this
```
{
  "cli": {
    "version": ">= 7.3.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "channel": "development"
    },
    "development-simulator": {
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "simulator": true
      },
      "channel": "development-simulator"
    },
    "preview": {
      "distribution": "internal",
      "channel": "preview"
    },
    "production": {
      "channel": "production"
    }
  },
  "submit": {
    "production": {}
  }
}
```

app.json is static and gets augmented with any dynamic changes made in app.config.ts/js 
Don't have to, but i just removed app.json and moved it all into app.config.ts to make it easier.
You can access env variables here 

```
...
ios: {
      bundleIdentifier: "blah.blah.blah",
      runtimeVersion: {
        policy: "appVersion"
      },
      usesAppleSignIn: true,
      googleServicesFile:
        process.env.GOOGLESERVICE_INFO_PLIST ?? "./GoogleService-Info.plist"
    },
    android: {
      permissions: ["android.permission.RECORD_AUDIO"],
      package: "blah.blah.blah"",
      runtimeVersion: "1.0.0",
      googleServicesFile:
        process.env.GOOGLE_SERVICES_JSON ?? "./google-services.json"
    },
...
```

Notice where I am setting googleServicesFile. By using the ternary operator we can make sure that the RNF/auth is happy to see the googleservicesfile, and then once its in EAS it will just use file set with EAS secrets.


This was very badly explained in all docs. But this will solve it for you.

**Comment by AlanGreyjoy** [comment]
> In case someone else stumbles upon this, the fix is and the route cause is pretty straight forward RNF/auth looks for your file locally before it gets built on EAS. However, once its being built by EAS in the cloud your secrets supersede and previously set values.
> 
> So. ensure you are gitignoring your google services files
> 
> ```
> # Google Services files
> ./google-services.json
> ./GoogleService-Info.plist
> ```
> 
> Eas should not have any env variables set and looks something like this
> 
> ```
> {
>   "cli": {
>     "version": ">= 7.3.0"
>   },
>   "build": {
>     "development": {
>       "developmentClient": true,
>       "distribution": "internal",
>       "channel": "development"
>     },
>     "development-simulator": {
>       "developmentClient": true,
>       "distribution": "internal",
>       "ios": {
>         "simulator": true
>       },
>       "channel": "development-simulator"
>     },
>     "preview": {
>       "distribution": "internal",
>       "channel": "preview"
>     },
>     "production": {
>       "channel": "production"
>     }
>   },
>   "submit": {
>     "production": {}
>   }
> }
> ```
> 
> app.json is static and gets augmented with any dynamic changes made in app.config.ts/js Don't have to, but i just removed app.json and moved it all into app.config.ts to make it easier. You can access env variables here
> 
> ```
> ...
> ios: {
>       bundleIdentifier: "blah.blah.blah",
>       runtimeVersion: {
>         policy: "appVersion"
>       },
>       usesAppleSignIn: true,
>       googleServicesFile:
>         process.env.GOOGLESERVICE_INFO_PLIST ?? "./GoogleService-Info.plist"
>     },
>     android: {
>       permissions: ["android.permission.RECORD_AUDIO"],
>       package: "blah.blah.blah"",
>       runtimeVersion: "1.0.0",
>       googleServicesFile:
>         process.env.GOOGLE_SERVICES_JSON ?? "./google-services.json"
>     },
> ...
> ```
> 
> Notice where I am setting googleServicesFile. By using the ternary operator we can make sure that the RNF/auth is happy to see the googleservicesfile, and then once its in EAS it will just use file set with EAS secrets.
> 
> This was very badly explained in all docs. But this will solve it for you.

100% on the mark.

You _you can however_ use ENV vars for development builds in eas.json

The docs are pretty wild. But they get the job done :)

**Comment by HubertRyanOfficial** [comment]
> In case someone else stumbles upon this, the fix is and the route cause is pretty straight forward RNF/auth looks for your file locally before it gets built on EAS. However, once its being built by EAS in the cloud your secrets supersede and previously set values.
> 
> So. ensure you are gitignoring your google services files
> 
> ```
> # Google Services files
> ./google-services.json
> ./GoogleService-Info.plist
> ```
> 
> Eas should not have any env variables set and looks something like this
> 
> ```
> {
>   "cli": {
>     "version": ">= 7.3.0"
>   },
>   "build": {
>     "development": {
>       "developmentClient": true,
>       "distribution": "internal",
>       "channel": "development"
>     },
>     "development-simulator": {
>       "developmentClient": true,
>       "distribution": "internal",
>       "ios": {
>         "simulator": true
>       },
>       "channel": "development-simulator"
>     },
>     "preview": {
>       "distribution": "internal",
>       "channel": "preview"
>     },
>     "production": {
>       "channel": "production"
>     }
>   },
>   "submit": {
>     "production": {}
>   }
> }
> ```
> 
> app.json is static and gets augmented with any dynamic changes made in app.config.ts/js Don't have to, but i just removed app.json and moved it all into app.config.ts to make it easier. You can access env variables here
> 
> ```
> ...
> ios: {
>       bundleIdentifier: "blah.blah.blah",
>       runtimeVersion: {
>         policy: "appVersion"
>       },
>       usesAppleSignIn: true,
>       googleServicesFile:
>         process.env.GOOGLESERVICE_INFO_PLIST ?? "./GoogleService-Info.plist"
>     },
>     android: {
>       permissions: ["android.permission.RECORD_AUDIO"],
>       package: "blah.blah.blah"",
>       runtimeVersion: "1.0.0",
>       googleServicesFile:
>         process.env.GOOGLE_SERVICES_JSON ?? "./google-services.json"
>     },
> ...
> ```
> 
> Notice where I am setting googleServicesFile. By using the ternary operator we can make sure that the RNF/auth is happy to see the googleservicesfile, and then once its in EAS it will just use file set with EAS secrets.
> 
> This was very badly explained in all docs. But this will solve it for you.

I already tried of everything but i doesnt work

**Comment by HubertRyanOfficial** [comment]
It just works if I remove google-service.json from git ignore and run eas build and after put git ignore again.
