### ISSUE TITLE
Tablet supports true build failed - iOS

### ISSUE THREAD

**Issue by blackwolf08** [expo/eas-cli#179]
eas submit -p ios failed with following output

✖ Something went wrong when submitting your app to Apple App Store.
We couldn't figure out what went wrong. Please see logs to learn more.

[logs] Starting iOS app upload
[logs] Downloading archive
[logs] Uploading iOS app to TestFlight...
[logs] [23:08:18]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[logs] [23:08:19]: -------------------
[logs] [23:08:19]: --- Step: pilot ---
[logs] [23:08:19]: -------------------
[logs] [23:08:19]: Ready to upload new build to TestFlight (App: xxx)...
[logs] [23:08:21]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
[logs] [23:08:21]: Going to upload updated app to App Store Connect
[logs] [23:08:21]: This might take a few minutes. Please don't interrupt the script.
[logs] [23:09:00]: [Transporter Error Output]: ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.sunnydhama.jiitcompanion'."
[logs] [23:09:00]: Transporter transfer failed.
[logs] [23:09:00]:
[logs] [23:09:00]: ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.sunnydhama.jiitcompanion'."
[logs] [23:09:00]: [iTMSTransporter] [2020-12-28 23:09:00 PST] <main> DBG-X:   parameter ErrorMessage = ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.sunnydhama.jiitcompanion'.
[logs] [23:09:00]: [iTMSTransporter]  (1102)
[logs] 
[logs] [23:09:00]: [iTMSTransporter] [2020-12-28 23:09:00 PST] <main> DBG-X:   parameter ShouldUseRESTAPIs = false
[logs] 
[logs] [23:09:00]: [iTMSTransporter] [2020-12-28 23:09:00 PST] <main> ERROR: ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'xxx'."
[logs] 
[logs] [23:09:00]: [iTMSTransporter]
[logs] 
[logs] [23:09:00]: [iTMSTransporter]
[logs] 
[logs] [23:09:00]: [iTMSTransporter]
[logs] 
[logs] [23:09:00]: [iTMSTransporter] Package Summary:
[logs] [23:09:00]: [iTMSTransporter]  
[logs] 
[logs] [23:09:00]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[logs] 
[logs] [23:09:00]: [iTMSTransporter]    /var/folders/97/73j93h690g9gdn54bh_zskm40000gn/T/d20201228-75969-6ph005/1498321159.itmsp - Error Messages:
[logs] 
[logs] [23:09:00]: [iTMSTransporter]            ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.sunnydhama.jiitcompanion'."
[logs] 
[logs] [23:09:00]: [iTMSTransporter] [2020-12-28 23:09:00 PST] <main> DBG-X: Returning 1
[logs] 
[logs] [23:09:00]: iTunes Transporter output above ^
[logs] [23:09:00]: ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.sunnydhama.jiitcompanion'."
[logs] Return status of iTunes Transporter was 1: ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.sunnydhama.jiitcompanion'."
[logs] The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
[logs] [23:09:00]: [iTMSTransporter] [2020-12-28 23:09:00 PST] <main> DBG-X: The error code is: 1102
[logs] 
[logs] [23:09:00]: [iTMSTransporter] [2020-12-28 23:09:00 PST] <main>  INFO: Done performing authentication.
[logs] [!] Error uploading ipa file, for more information see above
[logs] fastlane pilot failed

**Comment by barthap** [comment]
This is not directly related to EAS Submit. It seems that App Store Connect requires your app to support both portrait and landscape orientation in order to be available for tablets. You can experiment with [`orientation`](https://docs.expo.io/versions/v41.0.0/config/app/#orientation) property in `app.json`, for more advanced usage take look at [`expo-screen-orientation`](https://docs.expo.io/versions/v41.0.0/sdk/screen-orientation/)

**Comment by brentvatne** [comment]
hi there! is this still an issue? do you know how we can reproduce it?

**Comment by sunnyscaler** [comment]
Yes I did in fact had orientation property in app.json, I had my app submitted to app store and play store long before I tried eas builds…issue was, when I was using eas to upload my app (instead of expo build approach) I was getting this error…I don’t know what’s the status of this error now…haven’t use eas since then…expo build was and still working fine for me.

Thanks @barthap @brentvatne

**Comment by barthap** [comment]
Thank you for your response!

It looks like it was an issue with Xcode project configuration:
- https://stackoverflow.com/questions/32728711/xcode-7-error-itms-90474-invalid-bundle-cant-submit-to-apple
- https://medium.com/@tomlarge/react-native-invalid-bundle-ipad-multitasking-support-requires-these-orientations-fix-db00984713d5

We should try reproducing it with the current prebuilding system. Eventually, if the`Requires full screen` setting is/becomes optional, we may add this error to _common submission errors_ and display more user-friendly message.

**Comment by sunnyscaler** [comment]
Thanks for such a prompt reply, I’ll try this…btw `eas` Is a great tool! 😄
