### ISSUE TITLE
Authentication with Apple Developer Portal failed!

### ISSUE THREAD

**Issue by quentinmodena** [expo/eas-cli#1805]
### Summary

When running `eas build -p ios --auto-submit` then pressing `yes` then connecting to my apple account i get the following error

Authentication with Apple Developer Portal failed!
You have no team associated with your Apple account, cannot proceed.
(Do you have a paid Apple Developer account?)

My account is actually linked to a team with an active paid Apple Developper account, yesterday (2023-04-20) i was able to do the process successfully for the same application.

### Managed or bare?

managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
      Shell: 5.1.4 - /bin/bash
    Binaries:
      Node: 18.16.0 - /usr/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.5.1 - /usr/bin/npm
    SDKs:
      Android SDK:
        API Levels: 30, 33
        Build Tools: 29.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    npmPackages:
      expo: ^48.0.0 => 48.0.9 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.6 => 0.71.6 
    npmGlobalPackages:
      eas-cli: 3.10.0
      expo-cli: 6.3.2
    Expo Workflow: managed

### Error output

Authentication with Apple Developer Portal failed!
You have no team associated with your Apple account, cannot proceed.
(Do you have a paid Apple Developer account?)
Error: You have no team associated with your Apple account, cannot proceed.
(Do you have a paid Apple Developer account?)
    at r.teams (/usr/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:850688)
    at t.selectTeamAsync (/usr/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:851461)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async t.validateSessionAsync (/usr/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:738507)
    at async Object.S [as loginWithUserCredentialsAsync] (/usr/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:709939)
    at async loginWithUserCredentialsAsync (/usr/lib/node_modules/eas-cli/build/credentials/ios/appstore/authenticate.js:84:24)
    at async loginAsync (/usr/lib/node_modules/eas-cli/build/credentials/ios/appstore/authenticate.js:56:16)
    at async authenticateAsUserAsync (/usr/lib/node_modules/eas-cli/build/credentials/ios/appstore/authenticate.js:129:27)
    at async authenticateAsync (/usr/lib/node_modules/eas-cli/build/credentials/ios/appstore/authenticate.js:101:16)
    at async AppStoreApi.ensureAuthenticatedAsync (/usr/lib/node_modules/eas-cli/build/credentials/ios/appstore/AppStoreApi.js:36:28)
    Error: build command failed.

### Reproducible demo or steps to reproduce from a blank project

eas build --platform ios --profile prod --auto-submit

**Comment by kazuma0129** [comment]
I'm having the same issue.

**Comment by quentinmodena** [comment]
I tried to remove and re-register my apple account from the paid Apple Developer account of my team, the problem still persist

**Comment by quentinmodena** [comment]
It actually works when i login directly to the main Apple Developer account (the one that pays the subscription).

My personnal account is linked to the main account with maximum permissions, see below

![Capture d’écran du 2023-04-24 11-42-54](https://user-images.githubusercontent.com/16798995/233960715-132ffe75-2c4d-49ce-919d-5f44873593af.png)

**Comment by byCedric** [comment]
Hi all! I can confirm that Apple is not returning any teams when authenticating with a non-admin subaccount. You should be able to work around this issue:

1. Using the original admin account when building/submitting.
2. Manually prepare the App Store Connect API key (ASC API), and configure it in `eas.json` using the `ascApiKey*` fields. ([learn more](https://docs.expo.dev/submit/eas-json/#ios-specific-options))

**Comment by quentinmodena** [comment]
Thanks for your reply, however this modification impacts pretty negativly our workflow since we have multiple developpers with different permission accounts.

Do you know if this modification is here to stay or if it's a temporary bug ?

This functionnality worked well with subaccounts before 2023-04-20

**Comment by byCedric** [comment]
Honestly, I can't give you a proper answer. Apple is notorious for randomly changing the API without any announcement or alternatives. It might be helpful to contact Apple directly and see if they can provide a clear answer. We've noticed that Fastlane has similar issues (e.g. [this](https://github.com/fastlane/fastlane/issues/21223), or [that](https://github.com/fastlane/fastlane/issues/21222)).

One thing that we found that might be related, is the Apple account type. If you have an `individual`-type account, it seems that no team is returned on the sub-account. But, for `organization`-type accounts, you can enable something called "Access to Certificates, Identifiers & Profiles" for each account. Some people have reported this in the past ([source](https://apple.stackexchange.com/questions/358552/apple-store-connect-access-to-certificates-identifiers-profiles-grayed-out/358562#358562)).

One thing that you could do, to maintain the original workflow as best as you can, is set up the credentials "locally". You should be able to use this on CI as well, but you might need some ways to securely store the important keys ([docs](https://docs.expo.dev/app-signing/local-credentials/)).

Will provide updates when we know more!

**Comment by quentinmodena** [comment]
I tried to contact Apple because since this change i can't access to the "Certificates, Identifiers & Profiles" page in the AppleStoreConnect from the subaccount. 

Looks related because i get the following error message : "Unable to find a team with the given Team ID 'XXXXXXXX' to which you belong. Please contact Apple Developer Program Support. https://developer.apple.com/support"

Following your message, i checked, we have an `organisation` type account but the "Access to Certificates, Identifiers & Profiles" checkbox doesn't appear in the user param page.

Will provide update when i get the reply from Apple

**Comment by quentinmodena** [comment]
Finnaly got an answer from Apple, both bugs are fixed for me

**Comment by Ladvace** [comment]
I'm still getting this error while trying to build for ios

`
Authentication with Apple Developer Portal failed!
You have no team associated with your Apple account, cannot proceed.
(Do you have a paid Apple Developer account?)
`

**Comment by Ladvace** [comment]
mmm, I just subscribed to the apple developer as an individual, so I have to check which is my "master account", since it should be mine

**Comment by nicsoid** [comment]
got same error.

**Comment by oamado** [comment]
I updated the package `"eas-cli": "^7.8.5",` and it works for me

**Comment by Ladvace** [comment]
it works for me too now

**Comment by kalashovkerim** [comment]
but not for me(

**Comment by kalashovkerim** [comment]
> The problem comes from Apple API apparently, they fixed the bug several times and it kept reappearing. We basically gave up and everyone on our team use the master Apple Developer Account now

Did you resovled the problem?

**Comment by bymw1990** [comment]
Any update on this issue? I used my apple account id for the developer portal and had the same problem. 7.8.5 did not work for me.

**Comment by kalashovkerim** [comment]
> Any update on this issue? I used my apple account id for the developer portal and had the same problem. 7.8.5 did not work for me.

I just reported to Apple support and after a few days (in my case a week) 
the problem has been fixed)

**Comment by bymw1990** [comment]
Thanks for the response - so I take that it had to be resolved at individual bases? I had the impression it was their api issues ...  I'll get in touch with the Apple support.

**Comment by JeffShomali** [comment]
Same here, I recenlty moved our app from individual account to use our organization and this issue is happening.

**Comment by halilibrahimcelik** [comment]
I also got the same error even if after applying  eas build --platform ios --profile prod --auto-submit this command nothing seems to be effective against this issue

**Comment by BasitJutt007** [comment]
Do you guys have setup `Apple Provisioning Profile` and `Apple Certificates`?
Because Apple uses `Code Signing` and these things are required for it to work
