### ISSUE TITLE
EAS requires a provisioning profile for an iOS framework target

### ISSUE THREAD

**Issue by callaars** [expo/eas-cli#1812]
### Build/Submit details page URL

https://expo.dev/accounts/josephsunsama/projects/sunsamamobile/builds/826afbf1-dd29-4b63-ab1f-bd68fc999f6a

### Summary

I got a bare React Native project in which we have an iOS target that's of a type "Framework". This framework doesn't need any code-signing but EAS requires there to be a provisioning profile. This means that this build keeps failing as Xcode reports that no code-signing is necessary and EAS tries to force one in.

I cannot find in the documentation any mention of this or how to resolve it, hence I think this might be an oversight.

### Managed or bare?

Bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
      npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
      Watchman: 2022.06.20.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 29, 30, 31, 32, 33
        Build Tools: 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0, 33.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-33 | Google APIs ARM 64 v8a
        Android NDK: 22.1.7171670
    IDEs:
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.1 => 0.71.1 
      react-native-web: 0.18.12 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.10.2
      expo-cli: 6.3.2
    Expo Workflow: bare

### Error output

error: FrameworkTarget does not support provisioning profiles. FrameworkTarget does not support provisioning profiles, but provisioning profile SOME_EXPO_PROVISIONING_PROFILE has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'FrameworkTarget' from project 'project'))

### Reproducible demo or steps to reproduce from a blank project

- Create a new iOS target of type "Framework" in a bare React Native project
- Set code-signing to automatic with team "None"
- Try to build the project in EAS

**Comment by wkozyra95** [comment]
I'll look into that, but having an example project that reproduces this issue would make it faster to address the issue. Can you prepare an example project like that?

**Comment by callaars** [comment]
Yes of course, I will do that on Monday first thing. Thank you!

**Comment by callaars** [comment]
Thanks all for helping, really appreciate it!
