### ISSUE TITLE
Debug build is not working 'Unable to load script'

### ISSUE THREAD

**Issue by Patafix** [expo/eas-cli#1818]
### Build/Submit details page URL

https://expo.dev/accounts/galouegessg/projects/Ecomode-DEV/builds/57ed9c95-1b8b-4c44-8497-01da50395b96

### Summary

We are trying to build a working APK in debug mode (and wihout dev-server).
But the apk is not working.

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
      npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    npmPackages:
      @expo/metro-config: ^0.5.2 => 0.5.2 
      expo: ~48.0.15 => 48.0.15 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
      react-native-web: ~0.18.7 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.10.2
    Expo Workflow: managed

---
✔ Validating global prerequisites versions passed
✔ Checking for incompatible packages passed
✔ Checking for conflicting global packages in project passed
✖ Verifying prebuild support package versions are compatible failed
Issues:
  Expected package @expo/config-plugins@~6.0.0
  Found invalid:
    @expo/config-plugins@5.0.4
    @expo/config-plugins@5.0.4
    (for more info, run: npm why @expo/config-plugins)
  Expected package @expo/prebuild-config@~6.0.0
  Found invalid:
    @expo/prebuild-config@5.0.7
    (for more info, run: npm why @expo/prebuild-config)
Advice:
  • Upgrade dependencies that are using the invalid package versions.
✔ Checking dependency versions for compatibility with the installed Expo SDK passed
✔ Validating Expo Config passed
✔ Checking package.json for common issues passed

### Error output

![image](https://user-images.githubusercontent.com/5347574/235147486-627e91d1-65f3-4637-a00a-6a8f4490b19b.png)
Unable to load script. Make sure you're either running Metro (run 'npx react-native start') or that your bundle 'index.android.bundle is packaged correctly for release.

### Reproducible demo or steps to reproduce from a blank project

We are trying to build a working APK in debug mode (and wihout dev-server).
We launch `eas build -p android -e internal-development`

With profile : 
```
"internal-development": {
      "developmentClient": false,
      "extends": "base",
      "android": {
        "buildType": "apk",
        "gradleCommand": ":app:assembleDebug"
      },
      "ios": {
        "buildConfiguration": "Debug"
      }
    }`

**Comment by wkozyra95** [comment]
This is how it's expected to work, debug builds are connecting to the bundler, and release builds are using bundled js. It should be possible to create debug build with bundled js, but it probably requires some native changes, so you would need to swith to bare workflow (run `expo prebuild` and commit android/ios directories)

**Comment by manickam1999** [comment]
After running `expo prebuild `and running `eas build -p android -e preview --local` didnt seem to help. I still get the same error output.

Code snippet from my `eas.json`

```
"preview": {
      "developmentClient": false,
      "android": {
        "buildType": "apk",
        "gradleCommand": ":app:assembleDebug"
      }
    },
```
