### ISSUE TITLE
eas build fails because build file cannot be found: Firebase config files saved in expo secrets not being transferred correctly

### ISSUE THREAD

**Issue by tmitboules** [expo/eas-cli#1821]
### Build/Submit details page URL

https://expo.dev/accounts/tmi/projects/AeonPass-Scanner/builds/a861555b-82bb-4617-bed1-b568e8dc44b7

### Summary

I want to make sure that I do not have to check my google-services.json & GoogleService-Info.plist files into my git repo. I uploaded each as a secret file in my expo project. I then followed the docs doing the following ... 

```
expo: {
    owner: "tmi",
    name: "AeonPass-Scanner",
    slug: "AeonPass-Scanner",
    version: "1.0.0",
    orientation: "portrait",
    icon: "./src/assets/icon.png",
    userInterfaceStyle: "light",
    splash: {
      image: "./src/assets/splash.png",
      resizeMode: "cover",
      backgroundColor: "#ffffff",
    },
    assetBundlePatterns: ["**/*"],
    jsEngine: "hermes",
    ios: {
      supportsTablet: true,
      bundleIdentifier: "com.tmitboules.AeonPassScanner",
      jsEngine: "hermes",
      googleServicesFile:
        process.env.GOOGLE_SERVICE_INFO_PLIST || "./GoogleService-Info.plist",
    },
    android: {
      googleServicesFile:
        process.env.GOOGLE_SERVICES_JSON || "./google-services.json",
      adaptiveIcon: {
        foregroundImage: "./src/assets/adaptive-icon.png",
        backgroundColor: "#ffffff",
      },
      package: "com.tmitboules.AeonPassScanner",
    },
    web: {
      favicon: "./assets/favicon.png",
    },
    extra: {
      eas: {
        projectId: "5824acd0-ca7a-4eff-9050-9b3836458c87",
      },
    },
    runtimeVersion: "exposdk:48.0.0",
    updates: {
      url: "https://u.expo.dev/5824acd0-ca7a-4eff-9050-9b3836458c87",
    },
    plugins: [
      "@react-native-firebase/app",
      "@react-native-firebase/auth",
      [
        "expo-build-properties",
        {
          ios: {
            useFrameworks: "static",
          },
        },
      ],
    ],
  },
```
  
  When I run locally this works just fine obviously. But when it builds, it can't find the file, although I see when it reads my config, it correctly links each env variable to the file in my expo secrets. 
  
 When building I get the following error
 
error: Build input file cannot be found: '/Users/expo/workingdir/build/ios/AeonPassScanner/GoogleService-Info.plist'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'AeonPassScanner' from project 'AeonPassScanner')
  
  

### Managed or bare?

Bare I guess, although I do not manage any native code. Just using plugins

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 30, 31, 33
        Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.15 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
    npmGlobalPackages:
      eas-cli: 3.10.0
      expo-cli: 6.3.2
    Expo Workflow: bare
    
    
    templates-MacBook-Pro:AeonPass-Scanner tony.boules$ expo doctor
┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (6.3.7).                 │
│   You are currently using expo-cli 6.3.2                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
🎉 Didn't find any issues with the project!

### Error output

  error: Build input file cannot be found: '/Users/expo/workingdir/build/ios/AeonPassScanner/GoogleService-Info.plist'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'AeonPassScanner' from project 'AeonPassScanner')

### Reproducible demo or steps to reproduce from a blank project

install deps

package json
```
{
  "name": "aeonpass-scanner",
  "version": "1.0.0",
  "scripts": {
    
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "update_test": "eas update --branch test"
  },
  "dependencies": {
    "@react-native-firebase/app": "^17.4.3",
    "@react-native-firebase/auth": "^17.4.3",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "expo": "~48.0.15",
    "expo-build-properties": "~0.6.0",
    "expo-dev-client": "~2.2.1",
    "expo-font": "~11.1.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-updates": "~0.16.4",
    "react": "18.2.0",
    "react-native": "0.71.7",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.0.14",
    "@types/react-native": "^0.71.6",
    "babel-plugin-inline-dotenv": "^1.7.0",
    "typescript": "^4.9.4"
  },
  "private": true
}

```

configure app

```
module.exports = {
  expo: {
    owner: "company",
    name: "app",
    slug: "app",
    version: "1.0.0",
    orientation: "portrait",
    icon: "./src/assets/icon.png",
    userInterfaceStyle: "light",
    splash: {
      image: "./src/assets/splash.png",
      resizeMode: "cover",
      backgroundColor: "#ffffff",
    },
    assetBundlePatterns: ["**/*"],
    jsEngine: "hermes",
    ios: {
      supportsTablet: true,
      bundleIdentifier: "com.example.app",
      jsEngine: "hermes",
      googleServicesFile:
        process.env.GOOGLE_SERVICE_INFO_PLIST || "./GoogleService-Info.plist",
    },
    android: {
      googleServicesFile:
        process.env.GOOGLE_SERVICES_JSON || "./google-services.json",
      adaptiveIcon: {
        foregroundImage: "./src/assets/adaptive-icon.png",
        backgroundColor: "#ffffff",
      },
      package: "com.example.app",
    },
    web: {
      favicon: "./assets/favicon.png",
    },
    extra: {
      eas: {
        projectId: "5824acd0-ca7a-4eff-9050-9b3836458c87",
      },
    },
    runtimeVersion: "exposdk:48.0.0",
    updates: {
      url: "https://u.expo.dev/5824acd0-ca7a-4eff-9050-9b3836458c87",
    },
    plugins: [
      "@react-native-firebase/app",
      "@react-native-firebase/auth",
      [
        "expo-build-properties",
        {
          ios: {
            useFrameworks: "static",
          },
        },
      ],
    ],
  },
};
```

generate android and ios config files from firebase

put them at the root of the project

save files as secrets in expo

configure eas build and run a build

**Comment by wkozyra95** [comment]
If you have bare project you need to follow instructions for react native apps not expo for third party libraries. Stuff like plugins or most of the values in app.json only take effect when you run `expo prebuild`, but EAS Build does not run it for bare projects. So in your case, secrets get uploaded, app.config.js resolves the path correctly, but native code is not aware of those files, because prebuild was not run.

If you don't need it to be a bare project just delete android and ios directories(or add it to gitgnore if you want to keep using it for local native development)
If you need to stay on bare you need to configure your native xcode/android project to use  files from secrets, or write [post install hooks](https://docs.expo.dev/build-reference/npm-hooks/) to copy secrets into appropriate locations in android/ios projects.
