### ISSUE TITLE
Android stops app on running due to the use of react-navigation

### ISSUE THREAD

**Issue by LavaCode** [expo/eas-cli#1827]
### Build/Submit details page URL

https://expo.dev/accounts/lavacode/projects/brinks

### Summary

When building the application Android stops the application due to the use react-navigation. 
If I remove react-navigation (from the Launcher.js, where the app starts) the app will open. 

### Managed or bare?

Bare

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 19.4.0 - /usr/local/bin/node
      npm: 9.3.1 - /usr/local/bin/npm
      Watchman: 2023.04.24.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9477386
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.0 => 44.0.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 3.10.2
      expo-cli: 6.3.7
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Repo: https://github.com/LavaCode/EAS-issues
Simply create .apk file and run the app on emulator.

**Comment by magbicaleman** [comment]
I tried using `expo-build-properties`  and the plugin settings
```javascript
    plugins: [
      [
        "expo-build-properties",
        {
          "android": {
            "buildToolsVersion": "33.0.0",
            "compileSdkVersion": 33,
            "minSdkVersion": 21,
            "targetSdkVersion": 33,
          },
        }
      ]
    ],
   
 ```
 
 Still getting error for build tools `30.0.3` even though I specified different version of build tools.
 
 ```
 [RUN_GRADLEW] Warning: Dependant package with key emulator not found!
[RUN_GRADLEW] 5 actionable tasks: 5 executed
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Could not determine the dependencies of task ':app:bundleReleaseResources'.
[RUN_GRADLEW] > Failed to install the following SDK components:
[RUN_GRADLEW]       build-tools;30.0.3 Android SDK Build-Tools 30.0.3
[RUN_GRADLEW]   Install the missing components using the SDK manager in Android Studio.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 15s
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
```

**Comment by dsokal** [comment]
Hey, 
My intuition tells me this doesn't necessarily have to be a problem with EAS Build. 
I'd suggest building the project locally and debugging it in Android Studio. Maybe it'll turn out this is a problem with `react-navigation`. In this case, you should report an issue in their repository https://github.com/react-navigation/react-navigation.

**Comment by LavaCode** [comment]
> Hey, 
> 
> My intuition tells me this doesn't necessarily have to be a problem with EAS Build. 
> 
> I'd suggest building the project locally and debugging it in Android Studio. Maybe it'll turn out this is a problem with `react-navigation`. In this case, you should report an issue in their repository https://github.com/react-navigation/react-navigation.

I actually decided to rebuild the app in Android Studio, like this I did not necessarily needed Expo/EAS anymore.
After a small test it appeared the app would work like this.
So after that I did work on a full rebuild. 
The app still uses React Navigation, but no Expo anymore. It was a though job, but like this I was able to finish the update of the application.
