### ISSUE TITLE
eas upload on iOS fails authentication after Apple password change and will never ask for credentials again

### ISSUE THREAD

**Issue by bfarrgaynor** [expo/eas-cli#1836]
### Summary

So, I changed my Apple ID password months ago. But cannot for the life of me get eas to allow submissions anymore. 

```
Your Apple ID or app-specific password is incorrect. Verify that you entered them correctly and try again.
```

I've tried:
- deleting the keychain item
- upgrading eas-cli to the latest

I CAN run a 'eas build' without issue and it is able to authenticate against Apple, but I CANNOT run eas submit. 

### Managed or bare?

Managed

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 9.6.5 - /usr/local/bin/npm
      Watchman: 2021.06.07.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 31
        Build Tools: 31.0.0, 34.0.0, 34.0.0
        System Images: android-31 | Google Play ARM 64 v8a, android-32 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.7 => 0.71.7 
      react-native-web: ~0.18.11 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.12.0
      expo-cli: 6.3.7
    Expo Workflow: managed

### Error output

Your Apple ID or app-specific password is incorrect. Verify that you entered them correctly and try again.

### Reproducible demo or steps to reproduce from a blank project

Run: eas submit
(select iOS)
error above is given

**Comment by szdziedzic** [comment]
Hi, could you show me the contents of your `eas.json` (please don't forget to censor any confidential data you have there before posting it here)?

**Comment by Rytis-J** [comment]
To delete the locally stored password, open the "Keychain Access" app, switch to "All Items", and search for "deliver. [Your Apple ID]" (example: deliver.bacon@expo.dev). Select the item you wish to modify and delete it. Next time running an Expo command you'll be prompted for a new password.


- From the official docs https://docs.expo.dev/app-signing/security/?redirected

**Comment by torchsmith** [comment]
I had this same error, but what fixed it for me was just manually re-typing in my apple id opposed to just letting it autofill.
