### ISSUE TITLE
eas credentials -p android error occured after using this command 

### ISSUE THREAD

**Issue by officialomkarjadhav** [expo/eas-cli#1838]
### Summary

PS F:\omkar\reactnative\E-learn> eas credentials -p android
EAS project not configured.
√ Would you like to automatically create an EAS project for @divineomkar/E-learn? ... yes
✔ Created @divineomkar/E-learn: https://expo.dev/accounts/divineomkar/projects/E-learn on Expo
✔ Linked local project to EAS project bdfaeb19-8f0a-4dcc-97dd-0aa77a7bafdf
√ Which build profile do you want to configure? » development
✔ Using build profile: development
Invalid format of Android applicationId. Only alphanumeric characters, '.' and '_' are allowed, and each '.' must be followed by a letter.
Error: Specify "android.package" in app.json and run this command again.
Cryptic error? Learn more: https://expo.fyi/cryptic-error-eas
Press any key to continue...

Invalid format of Android applicationId. Only alphanumeric characters, '.' and '_' are allowed, and each '.' must be followed by a letter.
Error: Specify "android.package" in app.json and run this command again.
Cryptic error? Learn more: https://expo.fyi/cryptic-error-eas
Press any key to continue...

--------------------------------------------------------------------------------------------------------------------

{
  "expo": {
    "name": "Elearn",
    "slug": "Elearn",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "package": "com.omkar.E-learn",
      "version": "1.0.0"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "bdfaeb19-8f0a-4dcc-97dd-0aa77a7bafdf"
      }
    }
  }
}

### Managed or bare?

Managed Expo framework

### Environment

{
  "expo": {
    "name": "Elearn",
    "slug": "Elearn",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "package": "com.omkar.E-learn",
      "version": "1.0.0"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "bdfaeb19-8f0a-4dcc-97dd-0aa77a7bafdf"
      }
    }
  }
}

### Error output

E-learn> eas credentials -p android
EAS project not configured.
√ Would you like to automatically create an EAS project for @divineomkar/E-learn? ... yes
✔ Created @divineomkar/E-learn: https://expo.dev/accounts/divineomkar/projects/E-learn on Expo
✔ Linked local project to EAS project bdfaeb19-8f0a-4dcc-97dd-0aa77a7bafdf
√ Which build profile do you want to configure? » development
✔ Using build profile: development
Invalid format of Android applicationId. Only alphanumeric characters, '.' and '_' are allowed, and each '.' must be followed by a letter.
Error: Specify "android.package" in app.json and run this command again.
Cryptic error? Learn more: https://expo.fyi/cryptic-error-eas
Press any key to continue...

Invalid format of Android applicationId. Only alphanumeric characters, '.' and '_' are allowed, and each '.' must be followed by a letter.
Error: Specify "android.package" in app.json and run this command again.
Cryptic error? Learn more: https://expo.fyi/cryptic-error-eas

### Reproducible demo or steps to reproduce from a blank project

{
  "expo": {
    "name": "Elearn",
    "slug": "Elearn",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "package": "com.omkar.E-learn",
      "version": "1.0.0"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "bdfaeb19-8f0a-4dcc-97dd-0aa77a7bafdf"
      }
    }
  }
}

**Comment by wkozyra95** [comment]
> Invalid format of Android applicationId. Only alphanumeric characters, '.' and '_' are allowed, and each '.' must be followed by a letter.

The error message is quite clear. If I'm missing something there please clarify what the problem is.
