### ISSUE TITLE
Android builds loses .env in gradle step, breaking build

### ISSUE THREAD

**Issue by SleeplessByte** [expo/eas-cli#1858]
### Build/Submit details page URL

https://expo.dev/accounts/derk-jan/projects/issue-eas-env/builds/fefe4947-a8fc-418b-8172-d9e7736fc2e4

_note: this was a fresh project using `nxp create-expo-app`. Even when doctor issues are resolved, problem persists. It doesn't matter if it's app.config.json, app.config.js, app.config.ts. Function export, or object export. It can even be app.json, and still show up as undefined after build succeeds_

### Summary

TL;DR this used to work in SDK 46 / 4 months ago. .env doesn't load in native build step.

- When using `.env` to inject values, it breaks the all the builds (including iOS), because at the final step, the env values are no longer available, where they were available before.
- In the build log above you should see `app.config.js ENV foo` which indicates the ENV is loaded correctly. You should see this in the `expo-doctor` step and the `prebuild` steps.
- Finally, `gradlew` breaks. You can make it not break by removing the `throw` in `app.config.js`, but then the app builds and shows `undefined`.

Minimal repo with barely any code provided below

_note: this works fine in web_

### Managed or bare?

Managed

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.19.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
      Yarn: 3.5.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\yarn.CMD
      npm: 8.19.3 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    npmPackages:
      @expo/webpack-config: ^18.0.4 => 18.0.4
      expo: ^48.0.17 => 48.0.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.12 => 0.18.12
    Expo Workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

Repro: https://github.com/XPBytes/issue-expo-eas-env

----------------------------

Make `.env`

```env
MY_TEST_VALUE="foo"
```

and load it in a file, so you know it works / is broken. In this case `App.tsx` text can be replaced.

```
// App.tsx
{process.env.MY_TEST_VALUE}
```

Use `'transform-inline-environment-variables'` for babel

Now make any build

```shell
eas build --platform android
```

### Workaround

```shell
eas secret:push --scope project --env-file .env
```

Then go to the secrets page and delete anything that had an empty value. Now it doesn't use your pushed `.env` anymore, but instead uses the secrets. It's not optimal, but it works!

**Comment by wkozyra95** [comment]
I suspect when app config is resolved during gradle build the cwd is not set to the root of the project, so .env file is not found.

If I'm right sth like
```
require('dotenv').config({ path: path.join(__dirname, '.env') })
```
should work for you

**Comment by SleeplessByte** [comment]
I will try this out on the linked repro and report back here.

Do note that this used to work and recently broke.

**Comment by SleeplessByte** [comment]
The build https://expo.dev/accounts/derk-jan/projects/issue-eas-env/builds/84b68050-7585-41c2-9b44-ac671272bf2a succeeded. I will do an APK build to verify it does still have the .env values.

In this case, probably want to update the relevant [section in the docs](https://docs.expo.dev/guides/environment-variables/#dotenv) and perhaps add it to [this one](https://docs.expo.dev/build-reference/variables/).

Also note that using _direnv_ isn't documented [here](https://docs.expo.dev/guides/environment-variables/#direnv) other than redirecting to their docs with no example or implementation guide and that also didn't work for me.

**Comment by wkozyra95** [comment]
> In this case, probably want to update the relevant [section in the docs](https://docs.expo.dev/guides/environment-variables/#dotenv) and perhaps add it to [this one](https://docs.expo.dev/build-reference/variables/).

First link you posted (https://docs.expo.dev/guides/environment-variables/) describes how to use env variables in expo project, it does not say anything about EAS Build, but at the beginning of that page there is a note with a link to a page about configuring env variables with EAS (the second link you posted)

We provide to ways of passing env variables to the build "env" field in **eas.json** and EAS Secrets. dotenv,direnv and other solution can probably by used but they are not considered to be "recommended" way of building on EAS, We of course want those approaches to work, but also we don't want to be responsible to maintain compatibility with those tools or explain how to use them.

> unfortunately it "works" but it doesn't. The value is replaced with undefined.

From what I see in the gradle phase correct value is printed, so value in app.config.js seems to be resolved correctly in that step.

I never used babel plugin to inline vars in the code, but reading the docs from https://docs.expo.dev/guides/environment-variables/#using-babel-to-inline-environment-variables-during-build-time I interpret that this plugin should take variables from it's environment, but when you add that dotenv part in your app.config.js it's setting env variables in that js script. I don't see anything that would give an expectation that setting env variables in app.config.js would affect env variables visible to babel.

To be honest I'm not really sure if this is a bug or intended behavior, but regardless this is not an EAS issue, it would also happen if you run prebuild and try to build if from e.g. Android Studio. If you disagree with that explanation and still believe this is a bug, you can open an issue in github.com/expo/expo

**Comment by SleeplessByte** [comment]
@wkozyra95 I understand you not wanting to take responsibility for this.

However, there isn't a single [issue template](https://github.com/expo/expo/issues/new/choose) in expo/expo that matches this problem. It is a problem in the EAS build pipeline that did not exist before. We have been using the exact same build steps for over a year using EAS, using `dotenv`, that now suddenly is broken.

It's listed in the documentation, but by saying "yeah it should maybe work but also don't do it because it's not the recommended way" doesn't really help anyone. Either remove it from the docs or help us keep it working.

Using the "env" key in `eas.json` does _not_ allow dynamic injection, forcing us to completely have to rewrite all CI. It also is incredibly shitty DX, which is sorta mentioned on [the same page](https://docs.expo.dev/build-reference/variables/#can-i-share-environment-variables-defined-in-easjson-with-expo-start-and-eas-update). This may be nice in theory, but in reality, whilst it may work, this feature (dotenv working as before) now no longer working without that being a purposeful change has already cost us several weeks of dev time.

I have read the docs many times over, and I created the repro to show that what is written in the docs just doesn't work any more. I don't know what else can be expected of a paying user of this service trying to help debug an issue.

**Comment by wkozyra95** [comment]
> It is a problem in the EAS build pipeline that did not exist before

No, this is not an issue with EAS Build, nothing changed there that would affect this case. Also, as I mentioned, if you would run `npx expo prebuild` and build resulting project in android studio you would get the same issue.

> We have been using the exact same build steps for over a year using EAS, using dotenv, that now suddenly is broken.

Nothing changed on EAS related to that, EAS just runs appropriate gradlew commands there. If sth changed it's a result of changes in your projects (maybe react native upgrade, maybe upgrade of some core expo packages).

> so I think it's a structural problem with ENV not being forwarded to the gradle process; the same issue happens on iOS builds.

No envs were ever passed to the gradle process if you used flow that you have in a repro repo. If it worked before then it worked because app.config.js was evaluated in the same process as babel, which might have changed (just guessing).

> I have read the docs many times over, and I created the repro to show that what is written in the docs just doesn't work any more.

No EAS docs even mentioned direnv or dotenv usage. https://docs.expo.dev/build-reference/variables/ documents how to use envs on EAS Build.

> If you run the built apk you can see that the value is undefined

I'm not claiming there is no issue(but I'm not convinced there is one either). When app.config.js was evaluated on EAS it resolved the correct value, so it's not an issue with passing those values to the build, but the issue is with project configuration to use those envs.

> Happy to try to have someone else "fix" this, but I don't know which issue template I should pick or how I should go about it, so any pointers would be appreciated.

If this is really a regression then it would be caused by either a change in react-native or versioned expo cli. I would recommend using CLI template for the issue.


I can't help you with making your current flow  work, I'm not convinced based on docs that it even supposed to work, but if you just want to fix passing envs to the build, then you can either:
- stop using babel transform. You know from logs on the last build you linked that env value in app.config.js was resolved correctly, so you can use extra field to pass it to the js bundle. https://docs.expo.dev/guides/environment-variables/#using-the-extra-field
- define your env variables in eas.json + EAS Secrets. Values set there are visible during entire build process, so this way you would be sure that whenever babel is executed those envs are present.

**Comment by SleeplessByte** [comment]
I think your guesses (either it being processed in the same process or something changing in expo's cli) are good pointers and only supported by the fact that I was able to make an old commit build just fine on EAS.

I have spoken at length with Brent about this and the upcoming SDK 49+ changes to .env strategies matches what the build process we had for the past year (which was broken but likely not because of EAS CLI) was trying to accomplish.

In the meanwhile, using EAS Secrets is exactly what we've been using to make it pass temporarily, which is meh because it starts obfuscating those values in the log even when they are not secrets, but it's good enough for now.

Thanks for the time.
