### ISSUE TITLE
EAS-CLI: Allow empty passwords for P12 files

### ISSUE THREAD

**Issue by KevinvdBurg** [expo/eas-cli#1869]
### Summary

I'm trying to set up an Expo project using an existing distribution certificate, but this certificate doesn't require a password. However, I'm encountering an error message stating "Please Enter A Valid Value" when I simply hit 'Enter'. If I input a space, it is deemed an incorrect password.

Not every certificate requires a password, so the CLI should accommodate this.

### Managed or bare?

n/a

### Environment

eas credentials

### Error output

`Please Enter A Valid Value`

### Reproducible demo or steps to reproduce from a blank project

Create a p12 without a password.

`eas credentials` --> `iOS` --> development --> `Do you want to log in to your Apple account?` Y --> select my company --> `All: Set up all the required credentials to build your project` --> `Generate a new Apple Distribution Certificate? (Y/n)` n ->
`Path to P12 file:` --> `P12 password:` --> empty password 🛑 **Please Enter A Valid Value** 🛑

**Comment by KevinvdBurg** [comment]
So I tried building locally a version that [accepts empty password](https://github.com/expo/eas-cli/commit/4730430be8c627a779240bca61f197e040fae353#diff-dd8fd4f10d21d57910fd37b954a7f3615e3680ca4bc9938c06c8d4234ad28e28L108) but then the `GraphQL` gives an error.

```Failed to set up credentials.
[GraphQL] Invalid PKCS#12 (.p12) file: PKCS#12 MAC could not be verified. Invalid password?
Cryptic error? Learn more```

**Comment by wkozyra95** [comment]
We do not support empty passwords for p12. I'm not sure if it's a bug in macOS keychain or in openssl, but a keystore with empty password created using one tool can't be read using the other.

To use that keystore you will need to add a password to the keystore.

**Comment by KevinvdBurg** [comment]
@wkozyra95 

We use services such as AppCenter and Azure DevOps that permit empty passwords; why doesn't Expo support this? I'm uncertain whether this is a bug in macOS keychain or in OpenSSL. However, it appears to be an Expo issue.

**Comment by wkozyra95** [comment]
> We use services such as AppCenter and Azure DevOps that permit empty password

Those services (I never used them, but I assume) only pass those credentials to the build. We are also managing and generating them. The other potential reason is that probably those services made an assumption that makes it work for you, but it might not be correct for others. e.g. Their implementation might work with keystores generated using macOS keychain, but it would fail if you pass a keystore created with openSSL.

We could technically support keystores without password and limit functionality in that case, but given the required work it does seem worth it. Especially where fixing it is very easy, just add a password to the Keystore.

> However, it appears to be an Expo issue.

Issue implies a bug, this is intended behavior/limitation.

**Comment by AJGeel** [comment]
Commenting for visibility. Also encountering this issue which is a blocker for us.

Working for a client, we are given a .p12 distribution certificate (that has no password) so unfortunately are unable to use EAS managed credentials. 

When trying to store this cert and the provisioning profiles in Expo, but are unable to proceed. We cannot generate a new certificate that does have a password. Any suggestions on how to resolve this?

![Screenshot_2024-10-23_at_15_44_54](https://github.com/user-attachments/assets/038e4b94-3b51-426e-98b0-c1c09186829c)

**Comment by AJGeel** [comment]
Update: it seems that we were able to circumvent this by adding a password to the certificate. 

This can be done by developers that have a Mac machine:

1.  Add the certificate to your 'Keychain Access';
2. Right click and export the certificate.
3. Simply add a password.

Currently waiting on a build to see if the integrity of the build is OK... 🤞

**Comment by aike19115** [comment]
@AJGeel Thanks for your solution, it works
