### ISSUE TITLE
expo sdk48 Execution failed for task ':app:mergeReleaseResources'.

### ISSUE THREAD

**Issue by rinaldycodes** [expo/eas-cli#1872]
### Summary

expo sdk48 Execution failed for task ':app:mergeReleaseResources'. failed when build

### Managed or bare?

managed

### Environment

[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':app:mergeReleaseResources'.
[stderr] 
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
[stderr] 
   > Resource compilation failed (Failed to compile values resource file /home/expo/workingdir/build/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values/values.xml. Cause: java.lang.IllegalStateException: Can not extract resource from com.android.aaptcompiler.ParsedResource@225bf008.). Check logs for more details.
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
2: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
java.lang.StackOverflowError (no error message)
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 7m 59s

### Error output

[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':app:mergeReleaseResources'.
[stderr] 
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
[stderr] 
   > Resource compilation failed (Failed to compile values resource file /home/expo/workingdir/build/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values/values.xml. Cause: java.lang.IllegalStateException: Can not extract resource from com.android.aaptcompiler.ParsedResource@225bf008.). Check logs for more details.
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
2: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
java.lang.StackOverflowError (no error message)
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 7m 59s

### Reproducible demo or steps to reproduce from a blank project

[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':app:mergeReleaseResources'.
[stderr] 
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
[stderr] 
   > Resource compilation failed (Failed to compile values resource file /home/expo/workingdir/build/android/app/build/intermediates/incremental/release/mergeReleaseResources/merged.dir/values/values.xml. Cause: java.lang.IllegalStateException: Can not extract resource from com.android.aaptcompiler.ParsedResource@225bf008.). Check logs for more details.
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
2: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
java.lang.StackOverflowError (no error message)
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 7m 59s

**Comment by Ubergizmo** [comment]
Hello, did you found the problem. I have the same issue and cant found the solution

**Comment by Serpentarius13** [comment]
Same here. Any solution?

**Comment by Ubergizmo** [comment]
> Same here. Any solution?

Sorry for my english. I found the issue. Look in the app.json file and Check the Color background for android e.g.: #00000 you must have 5 digits

**Comment by Serpentarius13** [comment]
> > Same here. Any solution?
> 
> Sorry for my english. I found the issue. Look in the app.json file and Check the Color background for android e.g.: #00000 you must have 5 digits

thanks man you helped out so much!!

**Comment by Th1nhNg0** [comment]
> > Same here. Any solution?
> 
> Sorry for my english. I found the issue. Look in the app.json file and Check the Color background for android e.g.: #00000 you must have 5 digits

Thanks I got this bug and take a lot of time try to fix it xD

**Comment by percy507** [comment]
> Sorry for my english. I found the issue. Look in the app.json file and Check the Color background for android e.g.: #00000 you must have 5 digits

Thanks a lot. I got this errror for wrong color syntax `##21B4D5`.

**Comment by aju-alen** [comment]
Life saver thread. I spent almost two days for this.
