### ISSUE TITLE
Unable to download file secrets from 1Password in pre-install lifecycle hook

### ISSUE THREAD

**Issue by ladyshaitan** [expo/eas-cli#1873]
### Build/Submit details page URL

https://expo.dev/accounts/rithmm/projects/rithmm-mobile/builds/9934c223-cb5b-47af-a76e-0a23498b138a

### Summary

I'm consolidating the secrets at my company into 1Password and error when I try to download files to the eas build host in a pre-install hook.  My questions are:

1. Is this approach inherently flawed?  Like should I not be attempting to write a file to the build host at all?
2. What are use cases for lifecycle hooks?  Are there other use patterns besides printing to stdout/sending curl requests for build notifications that I'm not thinking of?
3. What is the error indicating?

<img width="653" alt="Screenshot 2023-06-06 at 10 26 06 PM" src="https://github.com/expo/eas-cli/assets/10492916/bef856b3-98a2-4174-aea9-822a7aee3402">

### Managed or bare?

bare

### Environment

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
      npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 33
        Build Tools: 30.0.3, 33.0.2
        System Images: android-33 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.3.22 => 0.3.22
      expo: ~48.0.15 => 48.0.17
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.7 => 0.18.12
    Expo Workflow: bare

```

### Error output

```
Script 'eas-build-pre-install' is present in package.json, running it...
> ******-mobile@1.0.0 eas-build-pre-install
> eas-lifecycle-hooks/eas-build-pre-install.sh
Archive:  op.zip
op get user --me
Pulling down google-services.json from 1Password secrets
Pulling down GoogleService-Info.plist from 1Password secrets
[stderr] 
error:  cannot create /usr/local/bin/op.sig
[stderr] 
        Permission denied
[stderr] 
error:  cannot create /usr/local/bin/op
[stderr] 
        Permission denied
[stderr] 
eas-lifecycle-hooks/eas-build-pre-install.sh: 8: op: not found
[stderr] 
eas-lifecycle-hooks/eas-build-pre-install.sh: 11: op: not found
npm exited with non-zero code: 127
```

```
✔ Validating global prerequisites versions passed
✔ Checking for incompatible packages passed
✔ Checking for conflicting global packages in project passed
✖ Verifying prebuild support package versions are compatible failed
Issues:
  Expected package @expo/config-plugins@~6.0.0
  Found invalid:
    @expo/config-plugins@5.0.4
    @expo/config-plugins@5.0.4
    @expo/config-plugins@5.0.4
    @expo/config-plugins@5.0.4
    @expo/config-plugins@5.0.4
    @expo/config-plugins@5.0.4
    (for more info, run: npm why @expo/config-plugins)
  Expected package @expo/prebuild-config@~6.0.0
  Found invalid:
    @expo/prebuild-config@5.0.7
    @expo/prebuild-config@5.0.7
    (for more info, run: npm why @expo/prebuild-config)
Advice:
  • Upgrade dependencies that are using the invalid package versions.
✖ Checking dependency versions for compatibility with the installed Expo SDK failed
Issues:
  Some dependencies are incompatible with the installed expo version:
    @sentry/react-native@4.13.0 - expected version: 4.15.2
    sentry-expo@6.1.1 - expected version: ~6.2.0
  Your project may not work correctly until you install the correct versions of the packages.
  Install individual packages by running npx expo install @sentry/react-native@4.15.2 sentry-expo@~6.2.0
  Found outdated dependencies
Advice:
  • Use npx expo install --check to review and upgrade your dependencies.
✔ Validating Expo Config passed
✔ Checking package.json for common issues passed

✖ Found one or more possible issues with the project. See above logs for issues and advice to resolve.
```

### Reproducible demo or steps to reproduce from a blank project

pre-install-lifecycle-hook.sh
```
# !/bin/bash
curl -sSfo op.zip https://cache.agilebits.com/dist/1P/op2/pkg/v2.18.0/op_linux_amd64_v2.18.0.zip \
&& unzip -od /usr/local/bin/ op.zip && rm op.zip

echo op get user --me

echo "Pulling down google-services.json from 1Password secrets"
op document get google-services.json --out-file google-services.json

echo "Pulling down GoogleService-Info.plist from 1Password secrets"
op document get GoogleService-Info.plist --out-file GoogleService-Info.plist
```

**Comment by szdziedzic** [comment]
>Is this approach inherently flawed? Like should I not be attempting to write a file to the build host at all?

It's not flawed, you can write files to the build host

>What are use cases for lifecycle hooks? Are there other use patterns besides printing to stdout/sending curl requests for build notifications that I'm not thinking of?

The lifecycle hooks let you execute whatever bash script you want to execute, so downloading things or printing to the stdout are totally valid use cases. You can do other things as well, which can be performed using bash script if you have a use case for it. Basically, by using lifecycle hooks you can customize your build flow if there's a need for it.

>What is the error indicating?

It seems like you don't have permission to write to the `/usr/local/bin` directory, but you are trying to add the `op` executable there. I think you can modify your script to do 
```bash
curl -sSfo op.zip https://cache.agilebits.com/dist/1P/op2/pkg/v2.18.0/op_linux_amd64_v2.18.0.zip && sudo unzip -od /usr/local/bin/ op.zip && rm op.zip
```
instead of
```bash
curl -sSfo op.zip https://cache.agilebits.com/dist/1P/op2/pkg/v2.18.0/op_linux_amd64_v2.18.0.zip \
&& unzip -od /usr/local/bin/ op.zip && rm op.zip
```
(using sudo when unzipping) and it should make the error gone.

Although, I have one general question regarding this script. What is the use case for using 1Password to get the `google-services.json` and `GoogleService-Info.plist` files in this scenario? I mean it's totally valid approach, but it might be simpler for you in this case to use [EAS secrets](https://docs.expo.dev/build-reference/variables/#using-secrets-in-environment-variables) to get these files.

**Comment by ladyshaitan** [comment]
FYI I ended up just adding the files to eas secrets and everything worked just fine.  Thank you!
