### ISSUE TITLE
Unable to login non-interactive on the cli

### ISSUE THREAD

**Issue by JCaracutUniversalTransit** [expo/eas-cli#1877]
### Summary

Is it posible to login non-interactive on the cli same as the expo-cli before?

### Managed or bare?

Azure Pipeline

### Environment

✔ Check package.json for common issues
✔ Validate global prerequisites versions
✔ Validate Expo Config
✔ Check for conflicting global packages in project
✔ Check for incompatible packages
✔ Verify prebuild support package versions are compatible
✖ Check compatible dependency versions for the installed Expo SDK

Detailed check results:

Some dependencies are incompatible with the installed expo version:
  react-native@0.71.7 - expected version: 0.71.8
Your project may not work correctly until you install the correct versions of the packages.
Install individual packages by running npx expo install react-native@0.71.8
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

### Reproducible demo or steps to reproduce from a blank project

I want to setup to azure pipeline but I'm unable to login non-interactive on eas-cli

**Comment by wkozyra95** [comment]
- Go to https://expo.dev/accounts/[account]/settings/access-tokens
- Create robot user
- Generate access token
- Run `EXPO_TOKEN=sometoken eas build ....` on CI
