### ISSUE TITLE
EAS prebuild step suddenly can't detect monorepo anymore leading to build error.

### ISSUE THREAD

**Issue by maersk96** [expo/eas-cli#1879]
### Build/Submit details page URL

https://expo.dev/accounts/splitt/projects/splitt-app/builds/729200ea-fc9d-4c33-b854-a725a2a1a821

### Summary

I recently made a development build for IOS (using dev-client) which has been working flawlessly. Today i wanted to create an andoid equivalent but it failed. Then i tried IOS again and it fails with the same error.

I found that the prebuild step changes my dependencies and runs npm install again (https://docs.expo.dev/workflow/prebuild/#side-effects) and i am pretty sure this might be causing the error. At least the extra npm install is the cause. How do i avoid this extra npm install? How do i pass --no-install to the eas prebuild step?

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      npm: 9.2.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 3.13.2
    Expo Workflow: managed

### Error output

Running "npm install" in /Users/expo/workingdir/build/frontend directory
[stderr] 
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
[stderr] 
npm
[stderr] 
ERR! Cannot set properties of null (setting 'dev')
[stderr] 
[stderr] 
npm ERR! A complete log of this run can be found in:
[stderr] 
npm ERR!     /Users/expo/.npm/_logs/2023-06-13T10_29_33_405Z-debug-0.log
npm exited with non-zero code: 1

### Reproducible demo or steps to reproduce from a blank project

Can't. Not sure what magic (dependency updates) happen in the build steps.

**Comment by wkozyra95** [comment]
should be fixed now
