### ISSUE TITLE
Uploading to EAS Build: Request failed: 400 (Bad Request)

### ISSUE THREAD

**Issue by camnpr** [expo/eas-cli#1891]
### Build/Submit details page URL

https://snack.expo.dev/@camnpr/eas_build_error_400

### Summary

my run command under:

> npx eas build -p android --profile preview --clear-cache

return error: `Uploading to EAS Build: Request failed: 400 (Bad Request)`

i try use more is failure.

but it is no error before ten days.

it is network limit question?

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.17134
    Binaries:
      Node: 16.19.1 - D:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
      npm: 8.19.3 - D:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.0.0.0 AI-171.4408382
    npmPackages:
      @expo/webpack-config: 0.17.4 => 0.17.4
      expo: ~47.0.14 => 47.0.14
      react: 18.1.0 => 18.1.0
      react-dom: 18.1.0 => 18.1.0
      react-native: 0.70.8 => 0.70.8
      react-native-web: ^0.18.12 => 0.18.12
    Expo Workflow: bare

### Error output

Specified value for "android.package" in app.json is ignored because an android directory was detected in the project.
EAS Build will use the value found in the native code.
√ Using remote Android credentials (Expo server)
√ Using Keystore from configuration: Build Credentials xWJdzP3E8P (default)

Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive
√ Compressed project files 17m 49s (4.7 GB)
Your project archive is 4.7 GB. You can reduce its size and the time it takes to upload by excluding files that are unnecessary for the build process in .easignore file. Learn more: https://expo.fyi/eas-build-archive
× Uploading to EAS Build (4.7 GB / 4.7 GB)
Request failed: 400 (Bad Request)
    Error: build command failed.

### Reproducible demo or steps to reproduce from a blank project

demo: https://snack.expo.dev/@camnpr/eas_build_error_400

one blank page is recurrent.
PS: in my china.

**Comment by szdziedzic** [comment]
Hi, looking at the size of your archive 4.7 GB, I suspect that you are uploading the `node_modules` directory to the EAS servers. I think this is the issue here. This is not recommended. You can learn more about how to reduce the size of your project archive [here](https://expo.fyi/eas-build-archive).

**Comment by camnpr** [comment]
Since my git contains multiple projects and the rules of the git are in the root directory, does this result in multiple projects being uploaded to the EAS cloud service in one git repository?

EAS Build should be an exclusion rule for the configuration of the`. gitignore` file in the current directory

At the same time, it is also the packaging and uploading of files in the current directory to the EAS cloud space. I remember this was the case before, but the current rules are a bit strange.

**Comment by camnpr** [comment]
> By default, EAS CLI will produce the archive by copying all files starting from the root of the git repository with the exception of .git, node_modules, and all files matched by rules from .gitignore (or .easignore if it exists).

> EAS CLI always respects .gitignore files, but depending on your configuration there might be certain edge cases where EAS behavior is not 100% compliant with git.

What I mean is to try to stick to the `.gitignore` file in the current directory instead of the root directory.

Otherwise, I need to configure the excluded items in the '. gitignore' file in the root directory.

The `. gitignore` file in the root directory of the git project.

```bash
# EAS Build
/Project1
/Project2
/Project3
/Project4
/Project5
/Project6
/Project7
/Project8
/Project9
/Project10
/Project11
/Project12
/Project13
README.md
README_zh-CN.md
tempFragment.md
# @end eas-cli
```
@szdziedzic

**Comment by camnpr** [comment]
> By default, EAS CLI will produce the archive by copying all files starting from the root of the git repository with the exception of .git, node_modules, and all files matched by rules from .gitignore (or .easignore if it exists).

> EAS CLI always respects .gitignore files, but depending on your configuration there might be certain edge cases where EAS behavior is not 100% compliant with git.

What I mean is to try to stick to the `.gitignore` file in the current directory instead of the root directory.

Otherwise, I need to configure the excluded items in the '. gitignore' file in the root directory.

The `. gitignore` file in the root directory of the git project.

```bash
# EAS Build
/Project1
/Project2
/Project3
/Project4
/Project5
/Project6
/Project7
/Project8
/Project9
/Project10
/Project11
/Project12
/Project13
README.md
README_zh-CN.md
tempFragment.md
# @end eas-cli
```
@szdziedzic

**Comment by CVinfotech22** [comment]
thanks dude
