### ISSUE TITLE
iOS error "appBuildVersion" must be a string

### ISSUE THREAD

**Issue by oscarsalesdev** [expo/eas-cli#1892]
### Summary

I have a project developed with React-Native and Expo (eas-cli). The app is published in Android but now I'm trying to publish it to the Appstore.

In the app.json file I have: "version": "1.5.4"

Then I run "eas build -p ios" and get this error:

```
Compressing project files and uploading to EAS Build. Learn more
✔ Uploaded to EAS 2s
"appBuildVersion" must be a string
    Error: build command failed.
``` 

Then I just add random letters to the version: "version": "1.5.4.abc"

Run the same command again and then builds successfully and uploads the build to EAS. Ok, so then I try to submit that version to the Store, and then I get this other error:

```
Invalid app version number.
Versions are identified by CFBundleShortVersionString from Info.plist (expo.version in app.json).
If you're submitting an Expo project built with EAS Build, fix the version (expo.version) in app.json and build the project again.
```

Yes, I know the error says I can't use letters in my version name, but if I remove the letters, then I can't build. So I can't submit the app.

So I think that somehow eas-cli is converting my string "1.5.4" to a number, I guess. But when I add letters, it stays as a string.

Here's my app.json (I removed sensitive or unnecessary data):
```
{
  "expo": {
    "name": "Whatever",
    "version": "1.5.4",
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.myapp.whatever",
      "buildNumber": 5,
      "config": {
        "usesNonExemptEncryption": false
      } 
    }
}
``` 

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.17.0 - ~/Library/homebrew/bin/node
      Yarn: 1.22.19 - ~/Library/homebrew/bin/yarn
      npm: 8.15.0 - ~/Library/homebrew/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 18, 23, 26, 28, 29, 30, 31, 32, 33
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0
        System Images: android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 3.13.3
      expo-cli: 6.3.8
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Create an Expo project with the same versions I'm using. Set the version as "X.Y.Z", and then try to build the app with "eas build -p ios".

**Comment by wkozyra95** [comment]
https://docs.expo.dev/versions/latest/config/app/#buildnumber

buildNumber should be a string (appBuildVersion is a common name that we use for ios.buildNumber and android.versionCode).
