### ISSUE TITLE
EAS Update failing

### ISSUE THREAD

**Issue by adherb** [expo/eas-cli#1902]
### Build/Submit details page URL

https://expo.dev/accounts/adherb/projects/parkiq-native/builds/39c0f07d-0114-451c-b93d-10f94b2b4d28

### Summary

I have built a project for internal distribution using:
eas build --profile preview --platform ios

When I try and update the build I get errors:
eas update --branch preview --message "Updating the app"

### Managed or bare?

Managed

### Environment

✔ Check package.json for common issues
✔ Validate global prerequisites versions
✔ Validate Expo Config
✔ Check compatible dependency versions for the installed Expo SDK
✔ Check for conflicting global packages in project
✔ Check for incompatible packages
✔ Verify prebuild support package versions are compatible

Didn't find any issues with the project!

### Error output

expo-cli] Starting Metro Bundler
[expo-cli] 
[expo-cli] Web Bundling failed 15841ms
[expo-cli] 
[expo-cli] Error: Unable to resolve module ../Utilities/Platform from /Users/adamherbert/Documents/GitHub/beeper-native/node_modules/react-native/Libraries/ReactPrivate/ReactNativePrivateInterface.js: 
[expo-cli] 
[expo-cli] None of these files exist:
[expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform(.native|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx|.web.js|.native.js|.js|.web.jsx|.native.jsx|.jsx|.web.json|.native.json|.json)
[expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform/index(.native|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx|.web.js|.native.js|.js|.web.jsx|.native.jsx|.jsx|.web.json|.native.json|.json)
[expo-cli]   22 | import typeof deepFreezeAndThrowOnMutationInDev from '../Utilities/deepFreezeAndThrowOnMutationInDev';
[expo-cli]   23 | import typeof deepDiffer from '../Utilities/differ/deepDiffer';
[expo-cli] > 24 | import typeof Platform from '../Utilities/Platform';
[expo-cli]      |                              ^
[expo-cli]   25 |
[expo-cli]   26 | import {type DangerouslyImpreciseStyleProp} from '../StyleSheet/StyleSheet';
[expo-cli]   27 |
[expo-cli] Error: Unable to resolve module ../Utilities/Platform from /Users/adamherbert/Documents/GitHub/beeper-native/node_modules/react-native/Libraries/ReactPrivate/ReactNativePrivateInterface.js: 
[expo-cli] 
[expo-cli] None of these files exist:
[expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform(.native|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx|.web.js|.native.js|.js|.web.jsx|.native.jsx|.jsx|.web.json|.native.json|.json)
[expo-cli]   * node_modules/react-native/Libraries/Utilities/Platform/index(.native|.web.ts|.native.ts|.ts|.web.tsx|.native.tsx|.tsx|.web.js|.native.js|.js|.web.jsx|.native.jsx|.jsx|.web.json|.native.json|.json)
[expo-cli]   22 | import typeof deepFreezeAndThrowOnMutationInDev from '../Utilities/deepFreezeAndThrowOnMutationInDev';
[expo-cli]   23 | import typeof deepDiffer from '../Utilities/differ/deepDiffer';
[expo-cli] > 24 | import typeof Platform from '../Utilities/Platform';
[expo-cli]      |                              ^
[expo-cli]   25 |
[expo-cli]   26 | import {type DangerouslyImpreciseStyleProp} from '../StyleSheet/StyleSheet';
[expo-cli]   27 |
[expo-cli]     at ModuleResolver.resolveDependency (/Users/adamherbert/Documents/GitHub/beeper-native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:114:15)
[expo-cli]     at DependencyGraph.resolveDependency (/Users/adamherbert/Documents/GitHub/beeper-native/node_modules/metro/src/node-haste/DependencyGraph.js:277:43)
[expo-cli]     at Object.resolve (/Users/adamherbert/Documents/GitHub/beeper-native/node_modules/metro/src/lib/transformHelpers.js:169:21)
[expo-cli]     at Graph._resolveDependencies (/Users/adamherbert/Documents/GitHub/beeper-native/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
[expo-cli]     at Graph._processModule (/Users/adamherbert/Documents/GitHub/beeper-native/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
[expo-cli]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[expo-cli]     at async Graph._addDependency (/Users/adamherbert/Documents/GitHub/beeper-native/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
[expo-cli]     at async Promise.all (index 0)
[expo-cli]     at async Graph._processModule (/Users/adamherbert/Documents/GitHub/beeper-native/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
[expo-cli]     at async Graph._addDependency (/Users/adamherbert/Documents/GitHub/beeper-native/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
✖ Export failed

### Reproducible demo or steps to reproduce from a blank project

Create an expo project.

In eas.json add a previre channel.

Build the project using - eas build --profile preview --platform ios

Update the project using:
eas update --branch preview --message "Updating the app"

This is where the error occurs.

**Comment by szdziedzic** [comment]
Hi, this is probably a stupid question, but are you sure that you have all the necessary `node_modules` installed locally and up to date with the changes in your codebase?
