### ISSUE TITLE
Error 500 on submittion

### ISSUE THREAD

**Issue by pCyril** [expo/eas-cli#1903]
### Build/Submit details page URL

https://expo.dev/accounts/pcyril/projects/bamboche/submissions/4fdc848b-a245-494c-90c2-902afb1ed2f1

### Summary

When i run this command `eas submit -p ios --latest` the submittion doesn't work anymore.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 18.16.0 - /bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 9.5.1 - /bin/npm
    npmPackages:
      expo: ^48.0.0 => 48.0.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.7 => 0.18.10 
    npmGlobalPackages:
      eas-cli: 3.14.0
      expo-cli: 6.3.7
    Expo Workflow: managed

### Error output

[altool] 2023-06-27 14:20:49.135 *** Error: An unexpected error occurred An unexpected error occurred on the server side. If this problem persists, please contact us. (ID: f7ddfb4c-0e83-4228-9a6d-d4d5fdf8ce76) (500)
[altool]  {
[altool]     NSLocalizedDescription = "An unexpected error occurred";
[altool]     NSLocalizedFailureReason = "An unexpected error occurred on the server side. If this problem persists, please contact us. (ID: f7ddfb4c-0e83-4228-9a6d-d4d5fdf8ce76)";
[altool]     "original_server_error" =     {
[altool]         code = "UNEXPECTED_ERROR";
[altool]         detail = "An unexpected error occurred on the server side. If this problem persists, please contact us.";
[altool]         id = "f7ddfb4c-0e83-4228-9a6d-d4d5fdf8ce76";
[altool]         status = 500;
[altool]         title = "An unexpected error occurred";
[altool]     };
[altool] }
Application Loader output above ^
ERROR: REQUEST CREATE CONTAINER (ASSET_UPLOAD): received status code 500; internal server error. (500)
Error uploading '/var/folders/rp/_x4mwf8x2f52ml0n3qt65jw80000gn/T/93ee9df6-6962-4e39-9587-4c013599150b.ipa'.
An unexpected error occurred An unexpected error occurred on the server side. If this problem persists, please contact us. (ID: f7ddfb4c-0e83-4228-9a6d-d4d5fdf8ce76) (500)
The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
Could not download/upload from App Store Connect!
[stderr] 
[!] Error uploading ipa file: 
[stderr] 
 [Application Loader Error Output]: ERROR: REQUEST CREATE CONTAINER (ASSET_UPLOAD): received status code 500; internal server error. (500)
[stderr] 
[Application Loader Error Output]: Error uploading '/var/folders/rp/_x4mwf8x2f52ml0n3qt65jw80000gn/T/93ee9df6-6962-4e39-9587-4c013599150b.ipa'.
[stderr] 
[Application Loader Error Output]: An unexpected error occurred An unexpected error occurred on the server side. If this problem persists, please contact us. (ID: f7ddfb4c-0e83-4228-9a6d-d4d5fdf8ce76) (500)
[stderr] 
[Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
Fastlane pilot failed
fastlane exited with non-zero code: 1
Failed to submit the app
We couldn't figure out what went wrong. See logs to learn more.

### Reproducible demo or steps to reproduce from a blank project

To reproduce this issue i just have to run `eas submit -p ios --latest`

**Comment by pCyril** [comment]
It's maybe related to this https://status.expo.dev/incidents/9v8kjlcxs9q1

**Comment by pCyril** [comment]
I try to submit my app this morning, and it's work, i close this issue

**Comment by szdziedzic** [comment]
Hi @pCyril, thanks for reporting this! It was unrelated to [this](https://status.expo.dev/incidents/9v8kjlcxs9q1) outage, it seems like it was a temporary issue on Apple's side.
