### ISSUE TITLE
[eas update] Lifecycle hooks

### ISSUE THREAD

**Issue by feRpicoral** [expo/eas-cli#1916]
Are there lifecycle hooks like there are for `eas build` but for `eas update`?

`eas build` hooks: https://docs.expo.dev/build-reference/npm-hooks/

Since the env vars need to be set during an update (https://docs.expo.dev/eas-update/environment-variables/#setting-and-getting-environment-variables-when-publishing-an-update) I would like to have a script that checks if the required variables are set before performing the update.

I'm aware that I could have default values on `app.config.ts` but I don't feel comfortable fallbacking to production (my env var is to define the API URL) when it's not set.

**Comment by ladyshaitan** [comment]
I want this as well.

**Comment by pietgk** [comment]
i would also really like to have this option to.

**Comment by OwenMelbz** [comment]
Yeah this is tripping us up too, we came from a Bare project and cant use the runtime policies, so trying to automate this ourselves - but cant hook into the update process to do this :(
