### ISSUE TITLE
eas update + Expo Go - dynamic configuration results in undefined `Constants.manifest?.extra` for IOS and Android 

### ISSUE THREAD

**Issue by andre-wells** [expo/eas-cli#1917]
### Summary

Following the documentation for [Configuring EAS Update](https://github.com/expo/fyi/blob/main/eas-update-config.md), the `extra` property is `undefined` for IOS and Android (Web works, though). I can't use environment variables for my project.

### Managed or bare?

Manged

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 20.1.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ~48.0.18 => 48.0.19
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.10 => 0.18.12
    Expo Workflow: managed

### Create a new expo app with the Typescript template

```
 npx create-expo-app --template
? Choose a template: » - Use arrow-keys. Return to submit.
    Blank
    Blank (TypeScript)
>   Navigation (TypeScript)
    several example screens and tabs using react-navigation and TypeScript
    Blank (Bare)                             
```

### Initialize EAS and install dotenv
```
npx eas init --id [project id]
npx expo install dotenv
```

### Create a `.env` file at the project root

`.env`
```
API_URL=MyUrl
```

### Add `app.config.ts` for dynamic configuration

`app.config.ts`

```ts
import { ExpoConfig, ConfigContext } from 'expo/config';
import 'dotenv/config';

export default ({ config }: ConfigContext): ExpoConfig => {
  config.extra = {
    ...config.extra,    
    myApi: {
      apiUrl: process.env.API_URL,      
    },
  };

  return {
    ...config,
    name: 'eas-update-test',
    slug: 'eas-update-test',
    
  };
};

```

### Include the `extra` field on a component and run the project. Environment variables are loaded

`app\(tabs)\index.tsx`

```tsx
export default function TabOneScreen() {

  const extra = JSON.stringify(Constants.manifest?.extra, null, 2 );;
  console.log('extra', Constants.manifest?.extra);

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Tab One</Text>
      <View style={styles.separator} lightColor="#eee" darkColor="rgba(255,255,255,0.1)" />
      <EditScreenInfo path="app/(tabs)/index.tsx" />
      <Text>Extra field: {extra}</Text>
    </View>
  );
}
```

`extra` 

![image](https://github.com/expo/eas-cli/assets/66315105/0d12baa5-3687-4441-9d36-cfa9da3cdea3)

### Try run `eas update` but be prompted to complete configuration

```
npx eas update

It looks like you are using a dynamic configuration! Learn more: https://docs.expo.dev/workflow/configuration/#dynamic-configuration-with-appconfigjs)
Finish configuring EAS Update by adding the following to the project app.config.js:
Learn more: https://expo.fyi/eas-update-config

{
  "updates": {
    "url": "https://u.expo.dev/[project id]"
  },
  "runtimeVersion": {
    "policy": "sdkVersion"
  }
}

```

### Include the configuration in `app.json`

Complete `app.json` file

```json
{
  "expo": {
    "name": "eas-update-test",
    "slug": "eas-update-test",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "scheme": "myapp",
    "userInterfaceStyle": "automatic",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/images/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      }
    },
    "web": {
      "bundler": "metro",
      "favicon": "./assets/images/favicon.png"
    },
    "extra": {
      "eas": {
        "projectId": "[project id]"
      }
    },
    "owner": "andre-wells",
    "updates": {
      "url": "https://u.expo.dev/[project id]"
    },
    "runtimeVersion": {
      "policy": "sdkVersion"
    }
  }
}

```

### `extra` field is now `undefined` (but still works for web). 

This occurs on Expo Go on a virtual Android device and on a physical iPhone.
This occurs even if I move the config into `app.config.ts`.
**Note**: even the `eas` setting is missing.

![image](https://github.com/expo/eas-cli/assets/66315105/09b81170-329d-425e-952b-15e8feea8c3c)

**Comment by quinlanj** [comment]
hey @andre-wells can you use `Contants.expoConfig` instead and report back? `Constants.manifest` is deprecated, and we tell folks to use `Constants.expoConfig` instead. More details in the table here: https://docs.expo.dev/versions/latest/sdk/constants/#nativeconstants

**Comment by andre-wells** [comment]
Thanks @quinlanj I can access the variables via `Constants.expoConfig.extra`

I'm a little new to EAS and I know things have changed recently.

![image](https://github.com/expo/eas-cli/assets/66315105/d8a40d9a-0253-49f8-b962-78027c475dbe)
