### ISSUE TITLE
EAS update fails with error code EJSONEMPTY

### ISSUE THREAD

**Issue by dimonnwc3** [expo/eas-cli#1919]
### Summary

Try to publish update with EAS Update and getting an error:

```
CommandError: {"name":"EmptyJsonFileError","code":"EJSONEMPTY","isJsonFileError":true}
```

`dist` directory is not even created

### Managed or bare?

managed

### Environment

❯ npx expo-env-info

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.15.0 - ~/.asdf/installs/nodejs/18.15.0/bin/node
      Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.15.0/bin/yarn
      npm: 9.6.4 - ~/.asdf/plugins/nodejs/shims/npm
      Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/dimonn/.asdf/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: Flamingo 2022.2.1 Patch 1 Flamingo 2022.2.1 Patch 1
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.15 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.15.0
    Expo Workflow: managed

❯ npx expo-doctor
✔ Validating global prerequisites versions
✔ Checking for incompatible packages
✔ Checking for conflicting global packages in project
✖ Verifying prebuild support package versions are compatible
Issues:
  Expected package @expo/config-plugins@~6.0.0
  Found invalid:
    @expo/config-plugins@5.0.4
    (for more info, run: npm why @expo/config-plugins)
Advice:
  • Upgrade dependencies that are using the invalid package versions.
✔ Checking dependency versions for compatibility with the installed Expo SDK
✔ Validating Expo Config
✔ Checking package.json for common issues

✖ Found one or more possible issues with the project. See above logs for issues and advice to resolve.

### Error output

❯ eas update --channel=main --message="initial"
[expo-cli] CommandError: {"name":"EmptyJsonFileError","code":"EJSONEMPTY","isJsonFileError":true}

### Reproducible demo or steps to reproduce from a blank project

run `eas update --channel=main --message="initial"`

**Comment by quinlanj** [comment]
hey @dimonnwc3 , just to sanity check before we debug further, is your `app.json` or `package.json` empty?

**Comment by dimonnwc3** [comment]
> hey @dimonnwc3 , just to sanity check before we debug further, is your `app.json` or `package.json` empty?

`package.json` is not empty
I'm using dynamic configuration because of local secrets, with `app.config.js`
but I tried to use `app.json` for debugging as well and error is still here

**Comment by quinlanj** [comment]
@dimonnwc3 thanks for the info. We'll need to find out where your `EmptyJsonFileError`, presumably somewhere in your project there is an empty JSON file and we need to figure out which it is. 

Can you do the following:
1. Post your full error output, not just the errored line (`[expo-cli] CommandError:`). It will help me figure out where in the script the error happens.
2. Can you either share your github repo (if you are comfortable making it public) or send the .zip via email (you can send it to quin@expo.io)? If your project is quite complex, a simple version with the problem will be very much appreciated!

**Comment by dimonnwc3** [comment]
@quinlanj  thanks for your comment, it helped me to figure out

I've had an empty json file, referenced from my config, to localisation json file:
```
export default {
  expo: {
    ...
    locales: {
      en: "./lib/empty.json",
    },
    ...
  },
}
```

after adding empty object `{}` error is not present anymore
