### ISSUE TITLE
'Intercom/Intercom.h' file not found

### ISSUE THREAD

**Issue by ovidb** [expo/eas-cli#1923]
### Build/Submit details page URL

https://expo.dev/accounts/usebloom/projects/bloom/builds/879d08c5-b25d-44b6-a935-67bf89b3461c

### Summary

All of a sudden from today we started getting this error with Intercom. 

The build posted above is the first build we noticed this error popping up. We tried buidling an older version that was previously passing and we get the same error:

No version numbers of our packages seem to have changed - and reverting and running a build that previously passed successfully also now fails.

Previously passing build:
https://expo.dev/accounts/usebloom/projects/bloom/builds/40516895-1d49-449c-8120-89f3d3f963dd

Now failing under here:
https://expo.dev/accounts/usebloom/projects/bloom/builds/b184ff12-41fd-4015-b8d5-00c9718975c1

I would like to also mention that we've also tried building using the `--local` flag and it the build is successful

### Managed or bare?

managed

### Environment

  ```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
      Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/ovidb/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.4 => 0.17.4 
      expo: ~48.0.18 => 48.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.9 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.14.0
      expo-cli: 6.0.8
    Expo Workflow: managed
```
```
❯ npx expo-doctor  
✔ Validating global prerequisites versions
✔ Checking for incompatible packages
✔ Checking for conflicting global packages in project
✖ Verifying prebuild support package versions are compatible
Issues:
  Expected package @expo/config-plugins@~6.0.0
  Found invalid:
    @expo/config-plugins@5.0.4
    (for more info, run: npm why @expo/config-plugins)
Advice:
  • Upgrade dependencies that are using the invalid package versions.
✖ Checking dependency versions for compatibility with the installed Expo SDK
Issues:
  Some dependencies are incompatible with the installed expo version:
    @expo/webpack-config@0.17.4 - expected version: ^18.0.1
    @sentry/react-native@4.13.0 - expected version: 4.15.2
    @shopify/react-native-skia@0.1.195 - expected version: 0.1.172
    sentry-expo@6.1.1 - expected version: ~6.2.0
  Your project may not work correctly until you install the correct versions of the packages.
  Install individual packages by running npx expo install @expo/webpack-config@^18.0.1 @sentry/react-native@4.15.2 @shopify/react-native-skia@0.1.172 sentry-expo@~6.2.0
  Found outdated dependencies
Advice:
  • Use npx expo install --check to review and upgrade your dependencies.
✔ Validating Expo Config
✔ Checking package.json for common issues

✖ Found one or more possible issues with the project. See above logs for issues and advice to resolve.
```

### Error output

```
› Compiling @intercom/intercom-react-native Pods/intercom-react-native » IntercomModule.m

❌  (node_modules/@intercom/intercom-react-native/ios/IntercomAttributesBuilder.h:2:9)

  1 | #import <Foundation/Foundation.h>
> 2 | #import <Intercom/Intercom.h>
    |         ^ 'Intercom/Intercom.h' file not found
  3 | 
  4 | @interface IntercomAttributesBuilder : NSObject
  5 | + (ICMUserAttributes *)userAttributesForDictionary:(NSDictionary *)attributesDict;
  ```

### Reproducible demo or steps to reproduce from a blank project

Will try and provide one at a later time, but as said nothing has actually changed on our side. The build started failing even for previously successful builds

**Comment by ovidb** [comment]
Downgrading to `eas-cli@13.14.0` Fixed the issue for me. I will not close it as this still needs to be addressed

**Comment by szdziedzic** [comment]
This is strange because we weren't doing any significant changes / updating dependencies between `3.14.0` and `3.15.0` https://github.com/expo/eas-cli/releases/tag/v3.15.0. I'm wondering if this can be an issue with downloading/installing the Intercom pod 🤔 

Could you try to use the `Clear cache and retry the build` option on our website to retry the failed build to see if it helps?

**Comment by ovidb** [comment]
> Could you try to use the `Clear cache and retry the build` option on our website to retry the failed build to see if it helps?

Tried this - didn't help


> If it doesn't help you can try to set EAS_BUILD_DISABLE_COCOAPODS_CACHE to "1" and see how it goes.

Will try adding back the last version and do the above and report back


FYI other people had the same issue with the same plugin, so maybe it's not really related to the version of `eas-cli` as it looks like for them it worked with the latest version

https://github.com/cmaycumber/config-plugin-react-native-intercom/issues/68
