### ISSUE TITLE
Improve error message for submission: "The caller does not have permission"

### ISSUE THREAD

**Issue by Theeeus** [expo/eas-cli#1962]
### Summary

The app submission to the Play Store is failing with the message:
Google Api Error: Invalid request - The caller does not have permission

My app is already live on the play store and I'm submitting a new build to update the SDK.

### What platform(s) does this occur on?

Android

### SDK Version

48.0.0

### Environment

npx: installed 2 in 22.595s

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 29, 30, 31, 33
        Build Tools: 29.0.2, 29.0.3, 30.0.3, 33.0.0, 33.0.2
        System Images: android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-222.4459.24.2221.9862592
    npmPackages:
      expo: ^48.0.0 => 48.0.20
      react: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
    Expo Workflow: managed

### Minimal reproducible example

Starting the submit process

Downloading archive

Preparing artifact

Submitting Android app to Play Store...

Submitting the app with fastlane supply

[stderr] 
[!] Google Api Error: Invalid request - The caller does not have permission

+------------------------------------+------------------------------------------------------------------------------------------------+

|                                                     Summary for supply 2.212.1                                                      |

+------------------------------------+------------------------------------------------------------------------------------------------+

| aab                                | /tmp/submissions/2205358f-f446-4396-b55d-0df4e0132235/6e2fad38-c975-44ed-a917-e34e22f2b937.aab |

| track                              | internal                                                                                       |

| json_key                           | /tmp/submissions/2205358f-f446-4396-b55d-0df4e0132235/service-account.json                     |

| package_name                       | com.constructionrundriver.app                                                                  |

| changes_not_sent_for_review        | false                                                                                          |

| release_status                     | completed                                                                                      |

| skip_upload_apk                    | false                                                                                          |

| skip_upload_aab                    | false                                                                                          |

| skip_upload_metadata               | false                                                                                          |

| skip_upload_changelogs             | false                                                                                          |

| skip_upload_images                 | false                                                                                          |

| skip_upload_screenshots            | false                                                                                          |

| track_promote_release_status       | completed                                                                                      |

| validate_only                      | false                                                                                          |

| check_superseded_tracks            | false                                                                                          |

| timeout                            | 300                                                                                            |

| deactivate_on_promote              | true                                                                                           |

| rescue_changes_not_sent_for_review | true                                                                                           |

| ack_bundle_installation_warning    | false                                                                                          |

+------------------------------------+------------------------------------------------------------------------------------------------+

Fastlane supply failed
fastlane supply --aab /tmp/submissions/2205358f-f446-4396-b55d-0df4e0132235/6e2fad38-c975-44ed-a917-e34e22f2b937.aab --track internal --json_key /tmp/submissions/2205358f-f446-4396-b55d-0df4e0132235/service-account.json --package com.constructionrundriver.app --changes_not_sent_for_review false --release_status completed exited with non-zero code: 1

Failed to submit the app
We couldn't figure out what went wrong. See logs to learn more.

**Comment by Theeeus** [comment]
@brentvatne I tried changing the API Access in the Google Play Console but it didn't work

**Comment by brentvatne** [comment]
can you try creating a completely new service account? do you have admin access on google play console?

**Comment by Theeeus** [comment]
I tried and it didn't work. Is there anything specific to expo 48 that may be causing this?

**Comment by stesvis** [comment]
Has anybody figured out why it fails?
I am still getting this error (Expo 49).
```
Starting the submit process

Downloading archive

Preparing artifact

Submitting Android app to Play Store...

Submitting the app with fastlane supply

[stderr] 

[!] Google Api Error: Invalid request - The caller does not have permission

+------------------------------------+------------------------------------------------------------------------------------------------+

|                                                     Summary for supply 2.212.1                                                      |

+------------------------------------+------------------------------------------------------------------------------------------------+

| aab                                | /tmp/submissions/2577913f-7932-48f1-b68c-227fdaf7dd33/84d755ff-a7f7-4450-bfb5-d4a3e211d1b2.aab |

| track                              | internal                                                                                       |

| json_key                           | /tmp/submissions/2577913f-7932-48f1-b68c-227fdaf7dd33/service-account.json                     |

| package_name                       | com.igradeplus.mobile                                                                          |

| changes_not_sent_for_review        | false                                                                                          |

| release_status                     | completed                                                                                      |

| skip_upload_apk                    | false                                                                                          |

| skip_upload_aab                    | false                                                                                          |

| skip_upload_metadata               | false                                                                                          |

| skip_upload_changelogs             | false                                                                                          |

| skip_upload_images                 | false                                                                                          |

| skip_upload_screenshots            | false                                                                                          |

| track_promote_release_status       | completed                                                                                      |

| validate_only                      | false                                                                                          |

| check_superseded_tracks            | false                                                                                          |

| timeout                            | 300                                                                                            |

| deactivate_on_promote              | true                                                                                           |

| rescue_changes_not_sent_for_review | true                                                                                           |

| ack_bundle_installation_warning    | false                                                                                          |

+------------------------------------+------------------------------------------------------------------------------------------------+

Fastlane supply failed
fastlane supply --aab /tmp/submissions/2577913f-7932-48f1-b68c-227fdaf7dd33/84d755ff-a7f7-4450-bfb5-d4a3e211d1b2.aab --track internal --json_key /tmp/submissions/2577913f-7932-48f1-b68c-227fdaf7dd33/service-account.json --package com.igradeplus.mobile --changes_not_sent_for_review false --release_status completed exited with non-zero code: 1


Failed to submit the app
We couldn't figure out what went wrong. See logs to learn more.
```

**Comment by Theeeus** [comment]
@stesvis I created a completely new service account and it worked

**Comment by fseitun** [comment]
@Theeeus I just can't get this working, it has been failing for weeks!

**Comment by olarra** [comment]
In my case, I had not set the Google Service Account Key on the Expo Dev site under the credentials entry.

**Comment by pyramid-scheme-ceo** [comment]
In my case the permissions listed in [this guide](https://github.com/expo/fyi/blob/main/creating-google-service-account.md) weren't enough (nor the correct type) - only after I'd granted admin _account_ permissions did it start to work.

**Comment by jovani-delivertrade** [comment]
in my case, shame on me, forgot to hit the "invite user" button. lol
