### ISSUE TITLE
Metadata concatenates keywords with unnecessary space

### ISSUE THREAD

**Issue by andrewjshults** [expo/eas-cli#1963]
### Summary

When running `eas metadata:push` it sends the array of keywords over concatenated with `, ` when the [Apple Product Page docs](https://developer.apple.com/app-store/product-page/) indicate that only a comma is needed. If you're near the 100 character limit, this can cause a pull/push cycle to fail on the push as Apple counts but doesn't want the extra spaces.

### Managed or bare?

Managed

### Environment

`  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 19.4.0 - /opt/homebrew/bin/node
      Yarn: 3.3.1 - /opt/homebrew/bin/yarn
      npm: 9.3.1 - /opt/homebrew/bin/npm
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.0
      react: 18.2.0 => 18.2.0
      react-native: 0.72.1 => 0.72.1
      react-native-web: ~0.19.6 => 0.19.6
    npmGlobalPackages:
      eas-cli: 3.17.1
    Expo Workflow: managed`

`✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK`

### Error output

Uploading App Store configuration...
✔ Updated version and release info for 1.0
✖ Failed updating localized version for en-US
✔ Updated app categories
✔ Reloaded localized info
✔ Updated localized info for en-US
✔ Updated age rating declaration
✔ Updated store review details for 1.0

Store configuration upload encountered an error.

An attribute value is too long. - Keywords for English (U.S.) cannot be longer than 100 characters.

### Reproducible demo or steps to reproduce from a blank project

Create a `store.config.json` file 

`"keywords": [
                    "Productivity",
                    "Assistant",
                    "Delegate",
                    "Task",
                    "Help",
                    "Time Saver",
                    "Personal Assistant",
                    "Errand Runner",
                    "Life Organizer"
                ]`

`Productivity,Assistant,Delegate,Task,Help,Time Saver,Personal Assistant,Errand Runner,Life Organizer` - exactly 100 characters without spaces.

run `eas metadata:push` - get the error message from above

**Comment by szdziedzic** [comment]
Just published version `3.18.2` which should fix the issue
