### ISSUE TITLE
Build request failed - build command failed

### ISSUE THREAD

**Issue by yauheni-charniauski-purposetech** [expo/eas-cli#1964]
### Summary

I run this command

``` console
eas build --profile preview --platform android
```
and I get this:

```
Loaded "env" configuration for the "preview" profile: EXPO_PUBLIC_API_URL, EXPO_PUBLIC_something. Learn more
✔ Using remote Android credentials (Expo server)
✔ Using Keystore from configuration: Build Credentials R2nW3KDTA0 (default)

Compressing project files and uploading to EAS Build. Learn more
✔ Uploaded to EAS 1s
Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
    Error: build command failed.
   
   ```
   
   Yesterday everything worked fine, but today I faced with this issue...

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.12.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.4 - /usr/local/bin/npm
      Watchman: 2022.12.26.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.3 => 49.0.3 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
    npmGlobalPackages:
      eas-cli: 3.17.1
      expo-cli: 6.3.10
    Expo Workflow: managed

### Error output

Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
    Error: build command failed.

### Reproducible demo or steps to reproduce from a blank project

eas.json
```
{
    "cli": {
        "version": ">= 3.15.1"
    },
    "build": {
        "development": {
            "developmentClient": true,
            "distribution": "internal"
        },
        "preview": {
            "distribution": "internal",
            "env": {
                "EXPO_PUBLIC_API_URL": "2323213",
                "EXPO_PUBLIC_something": "123123"
            }
        },
        "production": {}
    },
    "submit": {
        "production": {}
    }
}
```

terminal command:
```
eas build --profile preview --platform android
```

**Comment by Tadimsky** [comment]
I'm having the same issue. Maybe an outage?

**Comment by berkaybeyaz1** [comment]
I am also facing the same error, status.expo and build queue metrics are showing normal for now 😩

**Comment by erdemgonul** [comment]
also having the same issue

**Comment by wesvh** [comment]
an outage?

**Comment by Darren120** [comment]
SAME SOMEONE HELP

**Comment by jorgelcff** [comment]
someone help us!!!!!!!!!!!! 
I NEED PUT ON MY APP ON

**Comment by Marcel0Henrique** [comment]
SAME SOMEONE HELP

**Comment by yauheni-charniauski-purposetech** [comment]
😂😂

**Comment by albertomedeiros** [comment]
Can somebody help us, we need build your application and catch the follow error:

Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.

**Comment by yauheni-charniauski-purposetech** [comment]
> Can somebody help us, we need build your application and catch the follow error:
> 
> Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.

EAS Build Major outage 
https://status.expo.dev/

**Comment by nvbach91** [comment]
Hi everyone, today I got this error, it seems like EAS can't connect to Google APIs
```
✖ Uploading to EAS Build (128 KB / 429 KB)
    FetchError: request to https://storage.googleapis.com/turtle-v2-projects/production/.../...?X-Goog-Alg
    orithm=GOOG4-RSA-SHA256&X-Goog-Credential=...t&X-Goog-Date=20230730T135950Z&X  
    -Goog-Expires=3600&X-Goog-SignedHeaders=host%3Bx-goog-content-length-range&X-Goog-Signature=...
    failed, reason: connect ETIMEDOUT 2a00:1450:4014:80f::2010:443       
    Code: ETIMEDOUT
```

**Comment by Jheysson** [comment]
My project is in WSL, when I run the command in the command windows of VSCode, it didn't work, but it did in the actual WSL command window

**Comment by wenlittleoil** [comment]
I have a similar problem.
<img width="960" height="326" alt="Image" src="https://github.com/user-attachments/assets/cf0a505c-2c32-4c11-8eb8-144602cb63a6" />
