### ISSUE TITLE
expo-splash-screen:compileReleaseKotlin FAILED - expo-splash-screen 0.20.5

### ISSUE THREAD

**Issue by nielsvanharen** [expo/eas-cli#1965]
### Build/Submit details page URL

https://expo.dev/accounts/cipio/projects/CiPiO/builds/b5a9ebe3-77f7-4c15-8dc1-0e1d6c968786

### Summary

Expo doctor told me to upgrade expo splash screen to 0.20.5 (was using 0.20.4) the android build is now failing.

### Managed or bare?

bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.16.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.1.2 
      expo: ^49.0.5 => 49.0.5 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      eas-cli: 3.17.1
    Expo Workflow: bare

✔ Check package.json for common issues
✔ Validate global prerequisites versions
✔ Validate Expo Config
✔ Check for conflicting global packages in project
✔ Check for incompatible packages
✔ Verify prebuild support package versions are compatible
✔ Check compatible dependency versions for the installed Expo SDK

Didn't find any issues with the project!

### Error output

[stderr] 
e: file:///home/expo/workingdir/build/node_modules/expo-splash-screen/android/src/main/java/expo/modules/splashscreen/SplashScreenReactActivityLifecycleListener.kt:16:3 'onContentChanged' overrides nothing

> Task :app:mergeReleaseResources

w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

508 actionable tasks: 508 executed

[stderr] 
FAILURE: Build failed with an exception.

[stderr] 
* What went wrong:

[stderr] 
Execution failed for task ':expo-splash-screen:compileReleaseKotlin'.

[stderr] 
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

[stderr] 
   > Compilation error. See log for more details

[stderr] 
* Try:

[stderr] 
> Run with --stacktrace option to get the stack trace.

[stderr] 
> Run with --info or --debug option to get more log output.

[stderr] 
> Run with --scan to get full insights.

[stderr] 
* Get more help at https://help.gradle.org

[stderr] 
BUILD FAILED in 5m 52s

Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

### Reproducible demo or steps to reproduce from a blank project

change expo-splash-screen to 0.20.5 and run an eas build

**Comment by fviak** [comment]
I am getting the same failure with `expo-splash-screen` 0.20.4 and `expo` 49.0.3

**Comment by miropls** [comment]
Also experiencing the same issue. `expo-splash-screen` 0.20.5, `expo` ^0.49.0, dependencies updated as per expo-doctor suggestions. Both local and EAS builds failing for Android.

**Comment by NOTamineRB** [comment]
Same issue here,  expo^0.49.0 build APK with expo failing.
(
Execution failed for task ':expo-splash-screen:compileReleaseKotlin'.)

**Comment by flowgrapher** [comment]
Experiencing same issue here with expo-splash-screen 0.20.5 and expo 49.0.0

**Comment by himrocks33** [comment]
I have the same issue... Anyone have a work around yet?

**Comment by brentvatne** [comment]
can someone please share a minimal reproducible example?

**Comment by Kudo** [comment]
that could be me to introduce the regression from https://github.com/expo/expo/pull/23747. upgrading `expo@~49.0.5` should help to resolve the problem.

**Comment by rbrki07** [comment]
Upgrading to `expo@~49.0.6` solved the problem for me.

**Comment by miropls** [comment]
Also confirming that building for Android locally and in EAS both succeed by updating expo to ~0.49.6 and running `expo install --fix`. Thanks for the quick response and fix @Kudo!

**Comment by Naveen-Prasanth-K** [comment]
Upgrading to expo49.0.6 is the solution. Its working..

**Comment by duggster** [comment]
I upgraded from SDK 48 to 49 a couple days ago, and am getting this android build error. When I upgraded it put me at expo 49.0.11, and expo-splash-screen 0.20.5. 
```
[stderr] 

FAILURE: Build failed with an exception.

[stderr] 

* What went wrong:

[stderr] 

Execution failed for task ':expo-splash-screen:compileDebugKotlin'.

[stderr] 

> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
```
Any ideas on what I can do?

**Comment by softov** [comment]
I only build using EAS, same problem.

For anyone looking for the solution.
I just changed from 
`"expo": "^49.0.0",`
to
`"expo": "~49.0.16",`

Then
`expo install --fix`

Fixed for me.
