### ISSUE TITLE
build:list command fails with no helpful information

### ISSUE THREAD

**Issue by LuKenneth** [expo/eas-cli#1977]
### Summary

We have a bitbucket CI/CD pipeline step that uses the output of `eas build:list --json --non-interactive` to determine next steps.
The message we see is `Error: build:list command failed.`

We then ran a few commands to see more information about the installed eas-cli and confirm it is installed and configured correctly. I will paste below the commands and corresponding outputs.

### Command
```
#!/bin/sh
type -a eas
```
### Output
```
/usr/local/bin/eas
```
---
### Command
```
eas --version
```
### Output
```
eas-cli/3.18.2 linux-x64 node-v16.18.1
```
---
### Command
```
eas whoami
```
### Output
```
Accounts:
 - [redacted] (Role: Developer)
```
---
### Command
```
eas diagnostics
```
### Output
```
 EAS CLI 3.18.2 environment info:
    System:
      OS: Linux 5.15 Alpine Linux
      Shell: 1.35.0 - /bin/ash
    Binaries:
      Node: 16.18.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    Utilities:
      Git: 2.38.5 - /usr/bin/git
    npmPackages:
      expo: ^48.0.0 => 48.0.10 
      expo-dev-client: ~2.2.1 => 2.2.1 
      expo-updates: ~0.16.4 => 0.16.4 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12
    Project workflow: managed
```

any advice?

### Managed or bare?

Managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Alpine Linux
      Shell: 1.35.0 - /bin/ash
    Binaries:
      Node: 16.18.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    npmPackages:
      expo: ^48.0.0 => 48.0.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12 
    Expo Workflow: managed

looks like expo doctor failed here:
```
/opt/atlassian/pipelines/agent/build/node_modules/expo-doctor/build/index.js:2
2023-08-03T16:20:11.532986651Z stderr P (()=>{var __webpack_modules__={47548:(e,r,n)=>{"use strict";Object.defineProperty(r,"__esModule",...
```

### Reproducible demo or steps to reproduce from a blank project

running
`eas build:list --json --non-interactive`

in `eas-cli/3.18.2 linux-x64 node-v16.18.1`

**Comment by szdziedzic** [comment]
Hi, could you try to run the same command with the `EXPO_DEBUG=1` flag?
