### ISSUE TITLE
Project wont load due to expo 48 upgrade: PluginError: Failed to resolve plugin  for module "react-native-email-link" relative to

### ISSUE THREAD

**Issue by codeSage-X** [expo/eas-cli#1999]
### Build/Submit details page URL

https://github.com/ArxelTech/VentlyApp

### Summary

After upgrading to expo version 48.0.9 the project has refused to build, this issue may be related to react native email link. Please , i need a solution. 

here is the error message: PluginError: Failed to resolve plugin  for module "react-native-email-link" relative to

### Managed or bare?

PluginError: Failed to resolve plugin  for module "react-native-email-link" relative to

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      @expo/webpack-config: ^18.0.1 => 18.0.1
      expo: ~48.0.9 => 48.0.9

### Error output

PluginError: Failed to resolve plugin  for module "react-native-email-link" relative to

### Reproducible demo or steps to reproduce from a blank project

Reproducible steps: https://github.com/ArxelTech/VentlyApp

**Comment by szdziedzic** [comment]
Hi, can you send me your build URL?
