### ISSUE TITLE
eas-cli v4.1.2 local build fails with eas-cli-local-build-plugin: not found

### ISSUE THREAD

**Issue by mgscreativa** [expo/eas-cli#2000]
### Summary

Upgraded eas-cli  to latest version (v4.1.2) and now local builds fail

 `$ npx eas build --profile development --platform android --clear-cache --local`

### Managed or bare?

Managed

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Linux 5.15 Linux Mint 21.2 (Victoria)
      Shell: 5.1.16 - /bin/bash
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 20230430.125247.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 33
        Build Tools: 30.0.3, 33.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86_64 Atom, android-32 | Google APIs Intel x86_64 Atom, android-33 | Google APIs Intel x86_64 Atom
    npmPackages:
      expo: ~49.0.5 => 49.0.6 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      eas-cli: 4.1.2
      expo-cli: 6.3.10
    Expo Workflow: managed

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

### Error output

> Loaded "env" configuration for the "development" profile: GOOGLE_SERVICES_FILE. Learn more: https://docs.expo.dev/build-reference/variables/
> ✔ Using remote Android credentials (Expo server)
> ✔ Using Keystore from configuration: Build Credentials XXX_XXX (default)
> sh: 1: eas-cli-local-build-plugin: not found
> npx exited with non-zero code: 127
>     Error: build command failed.

### Reproducible demo or steps to reproduce from a blank project

none

**Comment by mgscreativa** [comment]
Have to mention that downgrading eas-cli to v4.1.1 solves the issue

**Comment by szdziedzic** [comment]
Hi, I can't reproduce it on my device, even though I used the same `node` version, etc. 🤔

**Comment by mgscreativa** [comment]
Well, deleted node_modules and reinstalled them in my project, then ran `$ npx eas build --profile development --platform android --clear-cache --local` and got the same result...

> Loaded "env" configuration for the "development" profile: GOOGLE_SERVICES_FILE. Learn more: https://docs.expo.dev/build-reference/variables/
> ✔ Using remote Android credentials (Expo server)
> ✔ Using Keystore from configuration: Build Credentials 7qdSS_Y1BC (default)
> sh: 1: eas-cli-local-build-plugin: not found
> npx exited with non-zero code: 127
>     Error: build command failed.

**Comment by mgscreativa** [comment]
...downgrading eas-cli to v4.1.1 solved the issue again

**Comment by mgscreativa** [comment]
Hi1 I inform that upgrading to latest 5.0.2 worked again with local builds!

**Comment by TomasSestak** [comment]
having this with @7.5.0, downgrade to @6.1.0 fixed the issue

**Comment by nwagu** [comment]
I had same issue when I upgraded to eas-cli/10.2.1. I added `"eas-cli-local-build-plugin": "^1.0.124"` to my devDependencies, and that seemed to solve it.
