### ISSUE TITLE
Not supporting Android build on Windows is a huge limitation

### ISSUE THREAD

**Issue by shessafridi** [expo/eas-cli#2007]
### Do you understand that any feature requests opened in this repository will be closed?

Yes

**Comment by agrittiwari** [comment]
What do you mean by this? @shessafridi

**Comment by shessafridi** [comment]
> What do you mean by this? @shessafridi

`Error: Unsupported platform, macOS or Linux is required to build apps for Android.` This is an issue for me because I use Windows and cloud build takes a long time. It is definitely possible to build Android projects on Windows, I don't know why EAS doesn't support this.

**Comment by szdziedzic** [comment]
Hi, you can use WSL to run your builds on Windows. We are not planning to add support for native Windows at the moment.
