### ISSUE TITLE
"eas update:delete" doesn't work

### ISSUE THREAD

**Issue by yepMad** [expo/eas-cli#2012]
### Build/Submit details page URL

https://expo.dev/accounts/escola-happen/projects/quark/updates/9b93f0e0-43d2-4bdb-b548-2dc17161f85b

### Summary

Hey! I'm trying to do an emergency delete of an update group. But I'm getting an error. As a workaround, I just sent a new update.

### Managed or bare?

Bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.10121639
    npmPackages:
      expo: ^48.0.9 => 48.0.9
      react: 18.2.0 => 18.2.0
      react-native: ^0.71.4 => 0.71.4
    Expo Workflow: bare

### Error output

Unexpected server error (Expo error ID: 5d7fea32-af4c-4316-aa96-a7869fa825bc).
Request ID: 5d7fea32-af4c-4316-aa96-a7869fa825bc

### Reproducible demo or steps to reproduce from a blank project

Not sure if it's necessary. It should work just like a comand.

**Comment by quinlanj** [comment]
hey @yepMad I took a look at our server logs and the issue is that you are passing the wrong argument to the command. You'll need to pass in the group ID, which is the thing I've highlighted in red here:
![Screenshot 2023-08-23 at 3 56 48 PM](https://github.com/expo/eas-cli/assets/6380927/b58b48d6-8733-499c-b88c-6d459aacd4ec)

**Comment by quinlanj** [comment]
Please let me know if you are able to delete your update. I will also look into this workflow to make the user experience better so people dont run into this kind of thing in the future
