### ISSUE TITLE
Failed to upload the project tarball to EAS Build

### ISSUE THREAD

**Issue by 1623311678** [expo/eas-cli#2026]
### Summary

Failed to upload the project tarball to EAS Build

Compressing project files and uploading to EAS Build. Learn more
✖ Uploading to EAS Build (127 KB / 6.3 MB)
Failed to upload the project tarball to EAS Build

Reason: request to https://storage.googleapis.com/turtle-v2-projects/production/7d986165-0e82-4ff4-a727-b8db7f25a3bf/e0b9aa26-fb11-418c-a10a-4c58d4b53d55?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=www-production%40exponentjs.iam.gserviceaccount.com%2F20230827%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230827T132519Z&X-Goog-Expires=3601&X-Goog-SignedHeaders=host%3Bx-goog-content-length-range&X-Goog-Signature=1ea57402c1b5da14a26c5d73faf8130142e374edb56107881706d34e4845ed6eeb97c4b8dc3e5f9b55566a69082261745880e11f79f752d891c9b9600d750b6cf1b16ac6ece606bf279c99949f8f0a1c84d433250233ab8f67b3c00e7f4b6fd9367dea19c110689d927074367a54a8c0a7028cdf951279289d0200da87d0e3315c2461459780af0d0efe67258ab5494d68ba047bf4c7028ef5680faa9dfc76f1e884ed7e76386b003fb31d4e1c95fcc7dfccd7cbe852c37800aa6ad8033857483ff9e9285526afd7d4352ebde6f9f99197b609b271aa9ea004944516e10437c11db9b7fb0ce3cabb5199a2da08364235b1bec97a82327780b8c0f8087e6421b3 failed, reason: read ECONNRESET
    Error: build command failed.

<img width="762" alt="image" src="https://github.com/expo/eas-cli/assets/41052302/22abfabe-3c42-4521-8657-5dcdf50e1adf">

### Managed or bare?

No

### Environment

wangjunkai@192 expo-app % npx expo-env-info
npx: 2 安装成功，用时 4.689 秒

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.19.3 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.17 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.18 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.10 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 4.1.2
      expo-cli: 6.3.8
    Expo Workflow: managed

wangjunkai@192 expo-app % npx expo-doctor
npx: 1 安装成功，用时 4.607 秒
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✖ Check that native modules do not use incompatible support packages
Unexpected error while running 'Check that native modules do not use incompatible support packages' check:
Error: Dependency tree validation for @unimodules/core failed. This validation is only available on Node 16+ / npm 8.
✖ Check for legacy global CLI installed locally
Unexpected error while running 'Check for legacy global CLI installed locally' check:
Error: Dependency tree validation for expo-cli failed. This validation is only available on Node 16+ / npm 8.
✔ Check that packages match versions required by installed Expo SDK
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that native modules use compatible support package versions for installed Expo SDK
Unexpected error while running 'Check that native modules use compatible support package versions for installed Expo SDK' check:
Error: Dependency tree validation for expo-modules-autolinking failed. This validation is only available on Node 16+ / npm 8.
One or more checks failed, indicating possible issues with the project.

### Reproducible demo or steps to reproduce from a blank project

1 git clone https://github.com/1623311678/expo-app-demo.git
2 npm install 
3 eas build -p android --profile preview
4 found error as flow :

Compressing project files and uploading to EAS Build. Learn more
✖ Uploading to EAS Build (127 KB / 6.3 MB)
Failed to upload the project tarball to EAS Build

Reason: request to https://storage.googleapis.com/turtle-v2-projects/production/7d986165-0e82-4ff4-a727-b8db7f25a3bf/e0b9aa26-fb11-418c-a10a-4c58d4b53d55?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=www-production%40exponentjs.iam.gserviceaccount.com%2F20230827%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230827T132519Z&X-Goog-Expires=3601&X-Goog-SignedHeaders=host%3Bx-goog-content-length-range&X-Goog-Signature=1ea57402c1b5da14a26c5d73faf8130142e374edb56107881706d34e4845ed6eeb97c4b8dc3e5f9b55566a69082261745880e11f79f752d891c9b9600d750b6cf1b16ac6ece606bf279c99949f8f0a1c84d433250233ab8f67b3c00e7f4b6fd9367dea19c110689d927074367a54a8c0a7028cdf951279289d0200da87d0e3315c2461459780af0d0efe67258ab5494d68ba047bf4c7028ef5680faa9dfc76f1e884ed7e76386b003fb31d4e1c95fcc7dfccd7cbe852c37800aa6ad8033857483ff9e9285526afd7d4352ebde6f9f99197b609b271aa9ea004944516e10437c11db9b7fb0ce3cabb5199a2da08364235b1bec97a82327780b8c0f8087e6421b3 failed, reason: read ECONNRESET
    Error: build command failed.
wangjunkai@192 expo-app % npx expo-env-info

<img width="772" alt="image" src="https://github.com/expo/eas-cli/assets/41052302/d34a2287-2552-43a2-a068-2cab4b9b0564">

**Comment by lingfeif** [comment]
Same problem.

expo 47.0.0
eas-cli 4.1.2 
node 18.12.1
npm 8.19.2

**Comment by 1623311678** [comment]
Yes, I have access to Google Cloud from Beijing, China, but why can I use eas to publish before，We need an agent to obtain, but I wonder why eas can be used to publish before, I wonder if eas can be compatible
&nbsp;


1623311678
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月28日(星期一) 上午9:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [expo/eas-cli] Failed to upload the project tarball to EAS Build (Issue #2026)





 
Same problem.
 
expo 47.0.0
 eas-cli 4.1.2
 node 18.12.1
 npm 8.19.2

**Comment by 1623311678** [comment]
we need a vpn ,for China,if we wang to eas publish sucess

**Comment by 1623311678** [comment]
But my doubt is why we can use eas to publish before, now not, probably switched to Google cloud, expect eas can do some compatibility, so that Chinese users can also release eas without vpn

**Comment by ErikBoesen** [comment]
I am also experiencing this from the US.

**Comment by 1623311678** [comment]
> But my doubt is why we can use eas to publish before, now not, probably switched to Google cloud, expect eas can do some compatibility, so that Chinese users can also release eas without vpn



> I am also experiencing this from the US.

It's so unstable,

**Comment by 1623311678** [comment]
> I am also experiencing this from the US.

It's so unstable,

**Comment by dream-han** [comment]
Has the problem been solved now? I have also encountered the same problem

**Comment by 1623311678** [comment]
> Has the problem been solved now? I have also encountered the same problem

use vpn that can get google-cloud

**Comment by dream-han** [comment]
Thank you

**Comment by AbhayRajpootIndia** [comment]
In my case I had to first run EAS update once, then I was able to run EAS build.

**Comment by 775311653** [comment]
@1623311678 hello sir, can you tel me,how to set vpn to eas build。i use v2rayN, but i can't set proxy

**Comment by 1623311678** [comment]
> @1623311678 hello sir, can you tel me,how to set vpn to eas build。i use v2rayN, but i can't set proxy

I just tried it, you can also release eas without vpn, such as the release of android apk command: eas build -p Android --profile preview, if you use vpn, you do not need to set up any proxy for eas, only need you to access Google cloud, the link is: https://google.cloud.com/

**Comment by 1623311678** [comment]
if you not vpn,you can try publish more times. I try three times,only one time is successful



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 3, 2023 20:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [expo/eas-cli] Failed to upload the project tarball to EAS Build(Issue #2026)




 
@1623311678 hello sir, can you tel me,how to set vpn to eas build。i use v2rayN, but i can't set proxy

**Comment by 775311653** [comment]
@1623311678 thanks for answer,i have test many times,but its not work. its look like

**Comment by 1623311678** [comment]
verify if you can get google.cloud.com orgoogle.com？？



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 3, 2023 21:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [expo/eas-cli] Failed to upload the project tarball to EAS Build(Issue #2026)




 
@1623311678 thanks for answer， i test many times, but its also not work.   error its    × Uploading to EAS Build (73.9 KB / 73.9 KB)    Failed to upload the project tarball to EAS Build
 so can you teach me how to set vpn for eas。 or has other method to build app?  thanks you

**Comment by 1623311678** [comment]
expo can pack&nbsp; by local ，you can read document about release



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 3, 2023 21:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [expo/eas-cli] Failed to upload the project tarball to EAS Build(Issue #2026)




 
@1623311678 thanks for answer， i test many times, but its also not work.   error its    × Uploading to EAS Build (73.9 KB / 73.9 KB)    Failed to upload the project tarball to EAS Build
 so can you teach me how to set vpn for eas。 or has other method to build app?  thanks you

**Comment by 1623311678** [comment]
> @1623311678 thanks for answer， i test many times, but its also not work. error its × Uploading to EAS Build (73.9 KB / 73.9 KB) Failed to upload the project tarball to EAS Build so can you teach me how to set vpn for eas。 or has other method to build app? thanks you

try it as this document .https://docs.expo.dev/build-reference/local-builds/

**Comment by 1623311678** [comment]
> > @1623311678 thanks for answer， i test many times, but its also not work. error its × Uploading to EAS Build (73.9 KB / 73.9 KB) Failed to upload the project tarball to EAS Build so can you teach me how to set vpn for eas。 or has other method to build app? thanks you
> 
> try it as this document .https://docs.expo.dev/build-reference/local-builds/

build local for android :eas build -p android --profile preview --local

**Comment by 1623311678** [comment]
> @1623311678 thanks for answer， i test many times, but its also not work. error its × Uploading to EAS Build (73.9 KB / 73.9 KB) Failed to upload the project tarball to EAS Build so can you teach me how to set vpn for eas。 or has other method to build app? thanks you

看你是中国人，兄弟，如果还没解决的话，可以加我微信a1623311678 帮你看下

**Comment by 1623311678** [comment]
统一回复，如果还没解决的兄弟，可以加我微信a1623311678 帮你看下

**Comment by 775311653** [comment]
@1623311678 谢谢你兄弟，我最终在eas的官网论坛看到了一种解决办法了，通过github的action 功能,配置build命令 eas build -p all --profile preview --non-interactive  就可以打包了到expo上面了。不过打包好慢，我打个很小的应用都得10分钟。

**Comment by 1623311678** [comment]
买个vpn就行了，慢主要是他要进行原生的构建。很正常。action这个也没问题的，我之前倒是没注意看，不过taro也推出了类似的东西



---Original---
From: ***@***.***&gt;
Date: Sat, Nov 11, 2023 22:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [expo/eas-cli] Failed to upload the project tarball to EAS Build(Issue #2026)




 
@1623311678 谢谢你兄弟，我最终在eas的官网论坛看到了一种解决办法了，通过github的action 功能,配置build命令 eas build -p all --profile preview --non-interactive  就可以打包了到expo上面了。不过打包好慢，我打个很小的应用都得10分钟。

**Comment by 775311653** [comment]
嗯嗯，我也是有vpn的，本地git npm什么的代理配置都能用，不过这个eas就是不行，也不知道要怎么单独配置esa的代理。taro我还没用过，谢谢啦

**Comment by 1623311678** [comment]
不用配啊，我在公司是可以上外网的，能直接发。在家里直接用的啊哈加速器，也直接就能发。上周不翻墙偶尔也能发。🙈



---Original---
From: ***@***.***&gt;
Date: Sat, Nov 11, 2023 22:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [expo/eas-cli] Failed to upload the project tarball to EAS Build(Issue #2026)




 
嗯嗯，我也是有vpn的，本地git npm什么的代理配置都能用，不过这个eas就是不行，也不知道要怎么单独配置esa的代理。taro我还没用过，谢谢啦

**Comment by 775311653** [comment]
@nadavox i use github action to run build command

**Comment by nadavox** [comment]
Can you explain in more details ? Why it will solve my problem ?

**Comment by 775311653** [comment]
@nadavox Because your mistake is that you can not upload the project code to expo, do not understand why i can not set the vpn to upload, maybe you can try vpn upload.The build can then be performed using github's action feature.https://docs.expo.dev/eas-update/github-actions/ is the expo use making the operation of the action.Instead of packing your code from locally to expo, you use github's cloud server to upload it to expo

**Comment by nadavox** [comment]
But 3 weeks ago i did build and upload the build to expo.dev. why now i cant ? Is it new update ?

**Comment by 1623311678** [comment]
> But 3 weeks ago i did build and upload the build to expo.dev. why now i cant ? Is it new update ?

In my opinion, you may not be able to ask google Cloud where you are, I am Chinese, after I use the Aha accelerator to access Google, it can be published with eas, you can use a similar proxy.

In addition, sometimes eas may not be very stable, it is recommended to try several times

**Comment by 1623311678** [comment]
> i have the same issue. <img alt="Screenshot 2023-11-13 at 13 28 31" width="1330" src="https://user-images.githubusercontent.com/44653635/282447544-dec28526-337d-4bcb-aa8d-ce267efd1ef4.png"> i tried to write: eas update.
> 
> didnt work.

The reason for the problem is that expo put the build on Google Cloud, if you can't access Google Cloud, it means that you can't upload your code to eas service, in my opinion, you need a vpn so that you can access Google Cloud, and then you should be able to upload the build

**Comment by nadavox** [comment]
The google cloud thing is a new thibg ? 2 weeks ago i was able to build...

**Comment by 1623311678** [comment]
yes&nbsp;



---Original---
From: "nadav ***@***.***&gt;
Date: Tue, Nov 14, 2023 06:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [expo/eas-cli] Failed to upload the project tarball to EAS Build(Issue #2026)




 
The google cloud thing is a new thibg ? 2 weeks ago i was able to build...

**Comment by 1623311678** [comment]
two month ago ,i have this issue



---Original---
From: "nadav ***@***.***&gt;
Date: Tue, Nov 14, 2023 06:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [expo/eas-cli] Failed to upload the project tarball to EAS Build(Issue #2026)




 
The google cloud thing is a new thibg ? 2 weeks ago i was able to build...

**Comment by 1623311678** [comment]
when I can access google.com by vpn,I cam publish to eas success



---Original---
From: "nadav ***@***.***&gt;
Date: Tue, Nov 14, 2023 06:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [expo/eas-cli] Failed to upload the project tarball to EAS Build(Issue #2026)




 
The google cloud thing is a new thibg ? 2 weeks ago i was able to build...

**Comment by nadavox** [comment]
but i wrote here that two weeks ago i upload a build to expo. 
now i cant.
the VPN thing cant be the reason.

**Comment by nadavox** [comment]
ok. 
so i wake up today and it worked.... 
wierd....

**Comment by Atticuszz** [comment]
it works for me ,delete the project on expo.dev ,reinit the eas project loacally!good luck

**Comment by beanu** [comment]
> it works for me ,delete the project on expo.dev ,reinit the eas project loacally!good luck

Does this mean that I have to create a new project on expo.dev?

**Comment by beanu** [comment]
> it works for me ,delete the project on expo.dev ,reinit the eas project loacally!good luck

@Atticuszz Does this mean that I have to create a new project on expo.dev?

**Comment by Atticuszz** [comment]
yes，but  later  it showed
 up again，changing the ip by clash sometimes works，weird 😂

**Comment by khadishi** [comment]
I proxy this address and the problem was solved: storage.googleapis.com

**Comment by mmp-star** [comment]
https://github.com/expo/expo/issues/24128我在这个回复里面找到了解决方法：开全局代理不成的兄弟，需要将终端也也代理一下export https_proxy= http://127.0.0.1:7890/ http_proxy= http://127.0.0.1:7890/ all_proxy=socks5://127.0.0.1:7890 这是clashX的

**Comment by mmp-star** [comment]
这个解决方式对我很有效：https://github.com/expo/expo/issues/24128#issuecomment-1891655591
-----------
开全局代理不成的兄弟，需要将终端也也代理一下 export https_proxy=http://127.0.0.1:7890/ http_proxy=http://127.0.0.1:7890/ all_proxy=socks5://127.0.0.1:7890 这是clashX的

**Comment by laowus** [comment]
> ## 这个解决方法对我来说很有效：[expo/expo#24128 (comment)](https://github.com/expo/expo/issues/24128#issuecomment-1891655591)
> 开全局代理不成的兄弟，需要将终端也也代理一下export https_proxy= http://127.0.0.1:7890/ http_proxy= http://127.0.0.1:7890/ all_proxy=socks5://127.0.0.1:7890 这是clashX的

真的是, 我搞了一天了, 我翻墙了,  set https_proxy=http://127.0.0.1:7890
set http_proxy=http://127.0.0.1:7890  在终端打了这个 就可以打包了. 搞死了 中国人搞点开发 真卑微啊

**Comment by Linbubin** [comment]
如果按照上面兄弟引用的内容设置后还不行的话，再把翻墙软件的 TUN 设置为 on (我用的是 clash Verge,里面叫 虚拟网卡模式)

因为大概率是国人问题，所以这条就直接用中文回答了 :)

**Comment by Anskyuan** [comment]
> 如果按照上面兄弟引用的内容设置后还不行的话，再把翻墙软件的 TUN 设置为 on (我用的是 clash Verge,里面叫 虚拟网卡模式)
> 
> 因为大概率是国人问题，所以这条就直接用中文回答了 :)

我翻墙了, set https_proxy=http://127.0.0.1:7890/
set http_proxy=http://127.0.0.1:7890/ 在终端打了这个 也不好使，我是clashx
