### ISSUE TITLE
I deleted EAS cli file path /user/local/bin/eas after it failed to upgrade due to conflicting package managers

### ISSUE THREAD

**Issue by BlessingAdewale** [expo/eas-cli#2031]
### Summary

After attempting to build my app severally and getting build failed, I was told to run "when eas" command and delete the file path. After doing so, eas commands do not run again in my project. I get "no such file or directory". 

### Managed or bare?

Managed

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 19.7.0 - /usr/local/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
      Watchman: 2023.02.20.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /Users/user/.rvm/gems/ruby-3.0.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.4, macOS 11.3, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 28, 29, 30, 31, 33
        Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
        System Images: android-29 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 13.3/13E113 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.7 => 49.0.7 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
    npmGlobalPackages:
      eas-cli: 4.1.2
      expo-cli: 6.3.10
    Expo Workflow: managed

Need to install the following packages:
  expo-doctor
Ok to proceed? (y) 
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~7.2.2
Found invalid:
  @expo/config-plugins@5.0.4
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@~6.2.4
Found invalid:
  @expo/prebuild-config@5.0.7
  (for more info, run: npm why @expo/prebuild-config)
Advice: Upgrade dependencies that are using the invalid package versions.

One or more checks failed, indicating possible issues with the project.

### Error output

bash: eas: command not found

### Reproducible demo or steps to reproduce from a blank project

{
  "name": "risetest",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "lint": "eslint --ext .tsx --ext .ts src/",
    "format": "prettier --check ./src"
  },
  "dependencies": {
    "@expo-google-fonts/dm-sans": "^0.2.3",
    "@expo-google-fonts/space-grotesk": "^0.2.3",
    "@gorhom/bottom-sheet": "^4.4.7",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@reduxjs/toolkit": "^1.9.5",
    "@tanstack/react-query": "^4.33.0",
    "axios": "^1.5.0",
    "expo": "~49.0.7",
    "expo-app-loading": "^2.1.1",
    "expo-font": "~11.4.0",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "formik": "^2.4.3",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-calendars": "^1.1300.0",
    "react-native-confirmation-code-field": "^7.3.1",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-paper": "^5.10.3",
    "react-native-phone-number-input": "^2.1.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "13.9.0",
    "react-native-svg-transformer": "^1.1.0",
    "react-native-vector-icons": "^10.0.0",
    "react-redux": "^8.1.2",
    "yup": "^1.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@typescript-eslint/eslint-plugin": "^6.4.1",
    "@typescript-eslint/parser": "^6.4.1",
    "eslint": "^8.47.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "prettier": "^3.0.2"
  },
  "private": true
}

**Comment by szdziedzic** [comment]
I'm not sure if understood the issue correctly, but the recommended way to install the `eas-cli` package is
```
npm install -g eas-cli
# or
yarn global add eas-cli
```
depending on which package manger you want to use.

You can also use it by running `npx eas-cli@latest` command.

Let me know if any of these helps.

**Comment by BlessingAdewale** [comment]
It didn't solve anything. This is the actual problem. I ran this code "rm /users/local/bin/eas" and I'm facing the consequences. I did that because anytime I receive update that eas @5(I can't remember the actual version number) is available and I make effort to download using the command you wrote above, it will not reflect. I still keep on getting the update. That's why I used the command "rm /users/local/bin/eas" to delete the formal one and that now has affected the whole PC

**Comment by BlessingAdewale** [comment]
If I run _eas login_ for example, the command prompt does not recognize the eas command again.

**Comment by BlessingAdewale** [comment]
Not even one of the eas command

**Comment by BlessingAdewale** [comment]
I get error "No such file or directory found"

**Comment by BlessingAdewale** [comment]
> I'm not sure if understood the issue correctly, but the recommended way to install the `eas-cli` package is
> 
> ```
> npm install -g eas-cli
> # or
> yarn global add eas-cli
> ```
> 
> depending on which package manager you want to use.
> 
> You can also use it by running `npx eas-cli@latest` command.
> 
> Let me know if any of these helps.

Are you there?

**Comment by BlessingAdewale** [comment]
> If I run _eas login_ for example, the command prompt does not recognize the eas command again.
@szdziedzic

**Comment by pratham-jaiswal** [comment]
@BlessingAdewale afaik the problem is you using multiple node versions with nvm. I was having eas detect it's latest installed version, so I switched to each node version I have and deleted all. And now I'm having the same issue as yours.
