### ISSUE TITLE
EAS build fails with "fatal: unable to connect to github.com" and "connection timed out" for android

### ISSUE THREAD

**Issue by angarc** [expo/eas-cli#2032]
### Build/Submit details page URL

https://expo.dev/accounts/vivaimpulse/projects/my-brain-vibes-app/builds/7cc94a0e-6802-47d2-999d-866bc72afa37

### Summary

Expected behavior is for the "Install Dependencies" step of the pipeline to pass using `yarn install`.

Instead, the step is failing with error: `fatal: unable to connect to github.com:` and `github.com[0: 140.82.113.3]: errno=Connection timed out`

However, running `yarn install` locally works for me, and produces no errors. In the error output (pasted below), it looks like it got hung on running `git ls-remote --tags --heads git://github.com/CharlesMangwa/simple-markdown.git`

When I run that command locally, however, it doesn't hang, and this gets output:

```
33d963c760b8196bee01b1a5ba9974bc7f669af1        refs/heads/master
0e2fdc58ca9febabe52f748a15482f7e8808da99        refs/tags/0.0.9
5922a2a1c76913d2d6888d07e7faafda0cbdeb1f        refs/tags/0.1.0
50b12c8d86a2eaeb859dd98bb9dc2a144ce006c6        refs/tags/0.1.1
```

### Managed or bare?

managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 14.21.3 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 6.14.18 - /usr/local/bin/npm
      Watchman: 2023.07.03.00 - /opt/homebrew/bin/watchman
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: 8.3.0 => 8.3.0
      expo: ^48.0.0 => 48.0.20
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.3 => 0.71.3
      react-native-web: ~0.18.11 => 0.18.12
    Expo Workflow: managed

### Error output

```
Running "yarn install" in /home/expo/workingdir/build directory
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[stderr] 
error Command failed.
[stderr] 
Exit code: 128
[stderr] 
Command: git
[stderr] 
Arguments: ls-remote --tags --heads git://github.com/CharlesMangwa/simple-markdown.git
[stderr] 
Directory: /home/expo/workingdir/build
[stderr] 
Output:
[stderr] 
fatal: unable to connect to github.com:
[stderr] 
github.com[0: 140.82.113.3]: errno=Connection timed out
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn install exited with non-zero code: 128
```

### Reproducible demo or steps to reproduce from a blank project

The problem is, I don't get this issue locally. So I'm not sure how to reproduce it. I guess if there is way to trigger it on eas, it's to add this package [react-native-simple-markdown](https://www.npmjs.com/package/react-native-simple-markdown), to `package.json` and then run `eas build -p android`

**Comment by angarc** [comment]
Searching for how to solve the problem If i were getting it locally, it seems running 

`git config --global url."https://".insteadOf git://` would solve the problem, but of course I can't try this on your end. Is there anything I can do in my `package.json` so that it'll use `https://` instead of `git://` when building in eas? 

I've already tried this in my `package.json`:

```
  "dependencies": {
    "react-native-simple-markdown": "https://github.com/CharlesMangwa/react-native-simple-markdown#fba329526d4c7afe1782b33c8e670ca1fa29a633",
    ...
  },
```

and ran `eas build -p android`, but still the build failed at the same step on eas, despite working locally.

**Comment by szdziedzic** [comment]
Hi, you can actually use build hooks to run custom code on our end.

https://docs.expo.dev/build-reference/npm-hooks/

I've already tested it and if you add
```json
...,
"scripts": {
  ...,
  "eas-build-pre-install": "git config --global url.\"https://\".insteadOf git://",
  ...
},
...
```
to your `package.json` your build should start to work 🎉 .

**Comment by mlsbez** [comment]
I had the same issue and what worked for me was deleting yarn.lock
