### ISSUE TITLE
Cannot build android with eas - after firebase auth

### ISSUE THREAD

**Issue by sevketaydogdu** [expo/eas-cli#2043]
### Summary

After  addin firebase auth with google cant build android but ios works.(Production Builds)

In development build both of them works

### Managed or bare?

Managed

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.6.5 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
      Android SDK:
        API Levels: 33
        Build Tools: 29.0.2, 33.0.2
        System Images: android-33 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9862592
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.10.0 => 0.10.7 
      expo: ^49.0.9 => 49.0.9 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.3 => 0.72.3 
      react-native-web: ~0.19.6 => 0.19.8 
    npmGlobalPackages:
      eas-cli: 5.1.0
      expo-cli: 6.3.8
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

my app.json

```
{
  "expo": {
    "name": "Kolay Zikir: ZikirMatik",
    "slug": "ZikirMatik-Tamaugi",
    "owner": "antiquemedia",
    "version": "1.7.6",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "dark",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#010B00"
    },
    "updates": {
      "fallbackToCacheTimeout": 6000,
      "enabled": true,
      "checkAutomatically": "ON_LOAD",
      "url": "https://u.expo.dev/****************-e5aa-46d5-b5df-74ef2eb581ef"
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.antiquemedia.zikirmatik",
      "infoPlist": {
        "CFBundleAllowMixedLocalizations": true
      },
      "googleServicesFile": "./GoogleService-Info.plist"
    },
    "android": {
      "googleServicesFile": "./service-account-v02.json",
      "config": {
        "googleMobileAdsAppId": "ca-app-pub-**********~7444814863"
      },
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#010B00"
      },
      "package": "com.antiquemedia.zikirmatik"
    },
    "web": {
      "favicon": "./assets/icon.png",
      "bundler": "metro"
    },
    "experiments": {
      "tsconfigPaths": true
    },
    "scheme": "acme",
    "plugins": [
      [
        "expo-build-properties",
        {
          "android": {
            "compileSdkVersion": 33,
            "targetSdkVersion": 33,
            "buildToolsVersion": "33.0.0"
          },
          "ios": {
            "deploymentTarget": "13.0",
            "useFrameworks": "static"
          }
        }
      ],
      [
        "expo-updates",
        {
          "username": "antiquemedia"
        }
      ],
      "expo-localization",
      "./plugins/withAndroidStrategiesPlugin.js",
      "expo-router",
      "@react-native-google-signin/google-signin",
      "@react-native-firebase/app",
      "@react-native-firebase/auth",
      "react-native-iap"
    ],
    "extra": {
      "eas": {
        "projectId": "********-e5aa-46d5-b5df-74ef2eb581ef"
      }
    },
    "locales": {
      "tr": "./languages/turkish.json",
      "en": "./languages/english.json"
    },
    "runtimeVersion": {
      "policy": "sdkVersion"
    }
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-************~7444814863",
    "ios_app_id": "ca-app-pub-*****************~7991609772",
    "delay_app_measurement_init": true,
  }
}
```

`Running 'gradlew :app:bundleRelease' in /home/expo/workingdir/build/android 2

Downloading https://services.gradle.org/distributions/gradle-8.0.1-all.zip 3 10%. 4 20%. 5 30%. 6 40%. 7 50%. 8 60% 9 70%. 10 80% 11 90% 12 100% 13 Welcome to Gradle 8.0.1! 14 Here are the highlights of this release: 15

Improvements to the Kotlin DSL 16
Fine-grained parallelism from the first build with configuration cache 17
Configurable Gradle user home cache cleanup 18 For more details see https://docs.gradle.org/8.0.1/release-notes.html 19 To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.0.1/userguide/gradle_daemon.html#sec:disabling_the_daemon. 20 Daemon will be stopped at the end of the build 21
Task :expo-updates-gradle-plugin:pluginDescriptors 22 Task :expo-updates-gradle-plugin:processResources 23 Task :expo-dev-launcher-gradle-plugin:pluginDescriptors 24 Task :expo-dev-launcher-gradle-plugin:processResources 25 Task :gradle-plugin:pluginDescriptors 26 Task :gradle-plugin:processResources 27 Task :expo-dev-launcher-gradle-plugin:compileKotlin 28 Task :expo-dev-launcher-gradle-plugin:compileJava NO-SOURCE 29 Task :expo-dev-launcher-gradle-plugin:classes 30 Task :expo-dev-launcher-gradle-plugin:jar 31 Task :expo-dev-launcher-gradle-plugin:inspectClassesForKotlinIC 32 Task :gradle-plugin:compileKotlin 33 Task :gradle-plugin:compileJava NO-SOURCE 34 Task :gradle-plugin:classes 35 Task :gradle-plugin:jar 36 Task :gradle-plugin:inspectClassesForKotlinIC 37 Task :expo-updates-gradle-plugin:compileKotlin 38 Task :expo-updates-gradle-plugin:compileJava NO-SOURCE 39 Task :expo-updates-gradle-plugin:classes 40 Task :expo-updates-gradle-plugin:jar 41 Task :expo-updates-gradle-plugin:inspectClassesForKotlinIC 42 Configure project :app 43 ℹ️ Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@2.4.10) 44 ℹ️ Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.18.12) 45
[stderr] FAILURE: Build failed with an exception. 46

[stderr]

Where: 47
[stderr] Build file '/home/expo/workingdir/build/android/app/build.gradle' line: 183 48

[stderr]

What went wrong: 49
[stderr] A problem occurred evaluating project ':app'. 50

[stderr]

Cannot invoke method android() on null object 51
[stderr]

Try: 52
[stderr]

Run with --stacktrace option to get the stack trace. 53
[stderr]

Run with --info or --debug option to get more log output. 54
[stderr]

Run with --scan to get full insights. 55
[stderr]

Get more help at https://help.gradle.org 56
[stderr] BUILD FAILED in 2m 5s 57 15 actionable tasks: 15 executed 58 Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information. ```
`

**Comment by kadirguloglu** [comment]
i am getting the same error. I'm waiting for a solution as soon as possible

**Comment by szdziedzic** [comment]
Hi, I believe that the easiest way for you to debug this issue is to run `prebuild` locally and try to inspect and build the project in the Android Studio. You can also try to use the [`npx expo run:android`](https://docs.expo.dev/more/expo-cli/#compiling) command to build the project locally.

https://docs.expo.dev/debugging/runtime-issues/

Let me know if it helps

**Comment by sevketaydogdu** [comment]
@szdziedzic thank you for your interest. 
I found the propblem with "@react-native-google-signin/google-signin" pack fails with expo sdk 49 on android. 
Uninstalled this package and tried "expo-auth-session" it worked for me
