### ISSUE TITLE
Expo EAS build android apk crash on physical device 

### ISSUE THREAD

**Issue by ajithjojo** [expo/eas-cli#2049]
### Summary

I am new to expo , I build an app with expo and when i try to run with _npx expo run:android_   it was working fine on emulator , 
but when i generate a debug and preview build apk with eas App crash after showing splash screen.

I am attaching my package.json file

{
  "name": "deltacard",
  "version": "2",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^5.11.15",
    "@react-navigation/native": "^5.9.8",
    "@react-navigation/stack": "^5.14.9",
    "apisauce": "^3.0.1",
    "eas": "^0.1.0",
    "expo": "~49.0.8",
    "expo-app-loading": "^2.1.1",
    "expo-auth-session": "~5.0.2",
    "expo-barcode-scanner": "~12.5.3",
    "expo-camera": "~13.4.2",
    "expo-constants": "~14.4.2",
    "expo-image": "~1.3.2",
    "expo-image-picker": "~14.3.2",
    "expo-linking": "~5.0.2",
    "expo-random": "~13.2.0",
    "expo-secure-store": "~12.3.1",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "~0.18.12",
    "expo-web-browser": "~12.3.2",
    "formik": "^2.1.4",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-google-places-autocomplete": "^2.5.1",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "yup": "^1.2.0"
  },
  "resolutions": {
    "@expo/config-plugins": "~6.0.0",
    "@expo/prebuild-config": "~6.0.0",
    "@babel/core": "^7.20.2",
    "babel-loader": "8.3.0"
  },
  "packagerOpts": {
    "sourceExts": [
      "js",
      "json",
      "ts",
      "tsx",
      "jsx",
      "vue"
    ]
  },
  "private": true,
  "devDependencies": {
    "sharp-cli": "^4.1.1"
  }
}

I saw this on stackoverflow to fix , that realted to    "react-native-reanimated": "~3.3.0", 
but when i downgrade this , i got this as an error and asked me to upgrade

### Managed or bare?

Bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.0.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10671973
    npmPackages:
      expo: ~49.0.8 => 49.0.9
      react: 18.2.0 => 18.2.0
      react-native: 0.72.3 => 0.72.3
    Expo Workflow: bare
    
    **Doctor check**
    
    ✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that packages match versions required by installed Expo SDK
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~7.2.2
Found invalid:
  @expo/config-plugins@5.0.4
  (for more info, run: npm why @expo/config-plugins)
Expected package @expo/prebuild-config@~6.2.4
Found invalid:
  @expo/prebuild-config@5.0.7
  (for more info, run: npm why @expo/prebuild-config)
Advice: Upgrade dependencies that are using the invalid package versions.

Some dependencies are incompatible with the installed expo version:
  react-native@0.72.3 - expected version: 0.72.4
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

### Reproducible demo or steps to reproduce from a blank project

NA

**Comment by szdziedzic** [comment]
Hi, do you have `expo-updates` configured correctly in the same way as recommended in these docs? https://docs.expo.dev/versions/latest/sdk/updates/
https://docs.expo.dev/bare/installing-updates/

**Comment by jaslloyd** [comment]
@szdziedzic We have a very similar issue (after using expo-update) but on iOS following the details for the link you sent and launching on the physical device whist having iOS logs running i can see the following error when it crashed
![Screenshot 2023-09-12 at 16 43 43](https://github.com/expo/eas-cli/assets/3710874/1aeef3b1-5eba-4672-a09f-c459c8d052aa)

Does that mean anything to do you? We are on SDK 49 which pretty much same setup as poster
