### ISSUE TITLE
App built via EAS stuck on SplashScreen

### ISSUE THREAD

**Issue by RohitKaushal7** [expo/eas-cli#2061]
### Build/Submit details page URL

https://expo.dev/accounts/100xp/projects/azapp/builds/58eefda6-028a-4565-a6bf-9875d3eeffbf

### Summary

Hi, 
My app works fine in - 
✅ the development build. (both emulator and physical device)
✅ the release build I do locally using `./gradlew :app:assembleRelease` (both emulator and physical device)

❌ But when I make the apk build using `eas build`, app gets stuck in the splashscreen. I checked the adb logs in logcat, the react-native code never gets executed and there are no ReactNative logs.

found this error in logs.
`couldn't find DSO to load: libjscexecutor.so`

this error also comes in the apk buit locally but that still works fine. but eas apk is stuck on splashscreen.

Versions - 
"expo": "~48.0.18",
"react-native": "0.71.8",

### Managed or bare?

bare

### Environment

`pnpx expo-env-info`
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 19.0.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.7.1 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        Android NDK: 23.0.7196353-beta2
    IDEs:
      Android Studio: AI-213.7172.25.2113.9014738
```
`pnpx expo-doctor`

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✖ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✖ Check for common project setup issues
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK

Detailed check results:

Error: Problem validating fields in app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: experiments - should NOT have additional property 'tsconfigPaths'.
Error: Problem validating asset fields in app.json. Learn more: https://docs.expo.dev/
 • Field: Android.adaptiveIcon.foregroundImage - image should be square, but the file at './assets/adaptive-icon.png' has dimensions 1004x1024.
 • Field: icon - image should be square, but the file at './assets/icon.png' has dimensions 1004x1024.

The package "expo-modules-autolinking" should not be installed directly in your project. It is a dependency of other Expo packages, which will install it automatically as needed.

This project has native project folders but is also configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).

One or more checks failed, indicating possible issues with the project.
 ERROR  Command failed with exit code 1: expo-doctor
```

### Reproducible demo or steps to reproduce from a blank project

this is a basic project, which uses expo-updates, react-native-firebase etc, nothing fancy. the error is just with the eas build environment or something.

**Comment by RohitKaushal7** [comment]
`couldn't find DSO to load: libjscexecutor.so` error also appears on the apk built locally but the app still works fine whereas the eas built apk is stuck on the splashscreen.

**Comment by brentvatne** [comment]
hi there,

here are a couple guides for you try to troubleshoot this:
- https://expo.fyi/splash-screen-hanging
- https://docs.expo.dev/build-reference/troubleshooting/
