### ISSUE TITLE
Build failed with nighly react native v0.73

### ISSUE THREAD

**Issue by arasrezaei** [expo/eas-cli#2062]
### Build/Submit details page URL

https://expo.dev/accounts/arasrezaie/projects/Apotel/builds/abdb9ef8-2b44-4168-b2c5-f3c8ba254096

### Summary

failed to build as it requires java v17

### Managed or bare?

expo managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20220821.200817.0 - E:\Software\Watchman\bin\watchman.EXE
    npmPackages:
      expo: ^49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: ^18.2.0 => 18.2.0 
      react-native: ^0.73.0-nightly-20230922-353b31c7d => 0.73.0-nightly-20230922-353b31c7d 
      react-native-web: ^0.19.7 => 0.19.7 
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

try to build project with nighly version of react native

**Comment by szdziedzic** [comment]
Hi, good news here! You can use our image with JDK 17 by specifying the Android image as `latest` https://docs.expo.dev/build-reference/infrastructure/
