### ISSUE TITLE
Support for XCode 15

### ISSUE THREAD

**Issue by vishaljak** [expo/eas-cli#2065]
### Summary

My app has a widget created using expo config plugins, and it contains modifiers available only on iOS 17 which only the compatible xcode version can compile. All my eas builds are failing since they use an old version of xcode (14.3 iirc). 

This is the build environment on eas
<img width="1149" alt="Screenshot 2023-09-26 at 2 37 36 pm" src="https://github.com/expo/eas-cli/assets/78641916/7785746b-cf38-4bd7-b4ee-b8353b65f22e">
<img width="895" alt="Screenshot 2023-09-26 at 22 32 06" src="https://github.com/expo/eas-cli/assets/78641916/b1d6e41a-6e34-454a-905d-159525338be8">

`containerBackground` is the new and mandatory modifier on iOS 17 for widgets ([more about this here](https://developer.apple.com/documentation/swiftui/view/containerbackground(_:for:))).
<img width="865" alt="Screenshot 2023-09-26 at 2 38 05 pm" src="https://github.com/expo/eas-cli/assets/78641916/20db930d-53d4-4961-970d-9292d965bee2">

The project builds and runs fine locally, which means the xcode 14.x is highly likely the issue here.

### Managed or bare?

Managed

### Environment

output from `npx expo-env-info`

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.7.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.1.0 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.10.0 => 0.10.7 
      expo: ^49.0.3 => 49.0.8 
      metro: ^0.76.7 => 0.76.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.4 
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Hard to provide an example on here but just using a modifier or api exclusively available on iOS17 will cause the builds to fail on eas. But happy to provide more info on the error if needed

**Comment by szdziedzic** [comment]
We are working on adding an image with Xcode 15. It should be released soon, under the `latest` tag.

**Comment by Libero793** [comment]
@szdziedzic any update on this? I cant run a new build on eas for ios nor android at the moment - both fail because im on xcode 15

**Comment by brentvatne** [comment]
done! sorry for the delay: https://docs.expo.dev/build-reference/infrastructure/#macos-ventura-136-xcode-150-latest
