### ISSUE TITLE
Bun Failed to build IOS

### ISSUE THREAD

**Issue by AdzeB** [expo/eas-cli#2066]
### Build/Submit details page URL

https://dub.sh/pfI4NTh

### Summary

I get the following error when I use bun to build IOS ipa
Node found at: /Users/expo/.nvm/versions/node/v16.18.1/bin/node

```
/Users/expo/workingdir/build/node_modules/react-native/scripts/generate-specs-cli.js:45

  .demandOption(

   ^

​

TypeError: yargs.option(...).option(...).option(...).option(...).option(...).option(...).usage(...).demandOption is not a function

    at Object.<anonymous> (/Users/expo/workingdir/build/node_modules/react-native/scripts/generate-specs-cli.js:45:4)

    at Module._compile (node:internal/modules/cjs/loader:1155:14)

    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)

    at Module.load (node:internal/modules/cjs/loader:1033:32)

    at Function.Module._load (node:internal/modules/cjs/loader:868:12)

    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

    at node:internal/main/run_main_module:22:47

Command PhaseScriptExecution failed with a nonzero exit code
```

### Managed or bare?

Managed

### Environment

System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Managers:
      CocoaPods: 1.13.0 
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: ~0.18.7 => 0.18.12 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 5.3.0
      expo-cli: 6.3.10
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

- Removed Yarn and Yarn.lock from the project
- Bun install
- eas build -p ios

**Comment by iM-GeeKy** [comment]
Might be related to this [issue](https://github.com/expo/expo-github-action/issues/234)
