### ISSUE TITLE
Adding a Internal distribution profile using eas device:create doesn't work in iOS 17

### ISSUE THREAD

**Issue by raphaelm-gioa** [expo/eas-cli#2074]
### Summary

After having successfully built my local preview build using "eas build --local" In preview mode
I am left with the .ipa that I dragged to my iPhone using Xcode after having installed the provisioning profile. 
Had I thought it had successfully been installed, I realised that the 'eas device:create' process never worked and that my provisioning profile never installed
After inspecting the logs of my iPhone 14 Pro Max; I found this error
``` 
Failed to parse profile data. Error: NSError:
Desc   : Profil non valide
US Desc: Invalid Profile
Domain : MCProfileErrorDomain
Code   : 1000
Type   : MCFatalError
``` 

And another one 

```
Failure occurred while retrieving profile during OTA Profile Enrollment: NSError:
Desc   : Profil non valide
US Desc: Invalid Profile
Domain : MCProfileErrorDomain
Code   : 1000
Type   : MCFatalError
Extra info:
{
    MCPermanentlyRedirectedURLString = "https://expo.dev/register-device/XXXXX?udid=XXXXX";
}
```

which leads to a never-ending loop of me pressing on "Install profile" and being redirected in Safari to the Expo page, but really nothing installed

### What platform(s) does this occur on?

iOS

### SDK Version

^49.0.0

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.5.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
      Watchman: 2022.08.08.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9014738
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.10 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
      react-native-web: ~0.19.6 => 0.19.8 
    npmGlobalPackages:
      eas-cli: 3.12.1
    Expo Workflow: bare

### Minimal reproducible example

Try to add a device to an internal build using `eas device:create`; in iOS 17.0.2, the process doesn't go through.

**Comment by relasine** [comment]
I am seeing the same issue. 've been working with folks in getting their phone UUIDs in our provisioning profile for staging builds, and we've run into an issue with them. Specifically that they're having trouble with installing the profile. They see the profile available for installation within device Settings, opt to install without a problem. However, when they return back to the settings screen, it appears that the profile is still available to be installed.

We found a similar issue in the Apple developer forums (back in iOS 13), but no solutions. Never had this issue before. 

Both on iOS 17. One on iPhone 13 Pro, other on iPhone 15 Pro. 
Both of their UUIDs are appearing in our list of devices that can be added to the provisioning profile.

**Comment by Lewitje** [comment]
Having the same issue here:
iOS 17.1.1
iPhone 15 Pro Max
Install profile screen pops up but doesn't complete install it redirects to expo saying device is ready for development but the profile stays at 'downloaded'

**Comment by Lewitje** [comment]
https://github.com/expo/eas-cli/assets/4394390/0f6e1a05-8a9b-4bce-a865-b8f8b5c2dd87

**Comment by szdziedzic** [comment]
Hi,

It looks like a bug. I created an internal task to investigate it.

**Comment by bogdan2510** [comment]
Having the exact same issue. @szdziedzic any news related to this?

**Comment by szdziedzic** [comment]
I'm investigating it, trying to find the root cause

**Comment by szdziedzic** [comment]
Hi there, I tested that even though installation in iPhone UI doesn't look like it finished I was able to add the device successfully to EAS devices and it's available on my devices list in the `eas device:list` command output. I also tested that I can create an internal distribution build and install it on the device successfully.

So functionality-wise it's working, but the UI feedback isn't great. We will try to do something about it, but meanwhile, you should be able to successfully use these devices for internal distribution builds.

**Comment by carakessler** [comment]
My devie is listed on the `eas device:list` and I am having the same issue with adding the profile. However, when I install an internal distribution build, it doesn't work and says that the app cant be verified @szdziedzic

**Comment by pyrsmk** [comment]
Same here, device is listed, but we cannot install the app.

**Comment by eriktoor** [comment]
Hey has there been any update here? I think the issue I'm seeing is that I cannot download the provisioning profile to my iPhone despite it being added on the eas side and showing up in eas device:list.

**Comment by eriktoor** [comment]
Same thing happened to me. I thought that I hadn't installed the cert because of the UI experience, but after marking myself as a receiver of the internal distribution build in EAS I was able to download the build.

**Comment by gajojr** [comment]
@eriktoor How did you mark yourself as a receiver of the internal distribution build?

**Comment by Chirema** [comment]
So what I did to fix this:
- deleted all devices using `eas device:delete`
- deleted all profiles in https://developer.apple.com/account/resources/profiles/list
- ensured right devices (by UUID) are re-enabled in https://developer.apple.com/account/resources/devices/list
- identified the UUID of the device by using `eas device:create` website option (profile does not install, but you get a pop-up with the UUID)
- added **manually** devices with `eas device:create` using the **input option**, using the UUID in the eas device:create website option which does not work
- built with `eas build --profile development --platform ios`, re-created profile in command line
- downloaded and opened app successfully

EAS is amazing, but this is a bug which renders the ecosystem sadly useless to people who cannot fix this issue. Hopefully this issue is fixed soon! Maybe my workaround helps some people.

**Comment by oleg1994** [comment]
having the same issue, is there anyway to make it work ?

**Comment by erwannbst** [comment]
Same issue please reopen

**Comment by devk03** [comment]
Having the same issue. Please Reopen.
