### ISSUE TITLE
Build / IOS build failed (DVTAssertions error)

### ISSUE THREAD

**Issue by MohamedEltantawy176** [expo/eas-cli#2079]
### Summary

i get the following error when i try to build IOS with cache clear with:

eas build --platform ios --profile production --local --clear-cache

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.8.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.1.0 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.10.0 => 0.10.7 
      expo: ^49.0.0 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.5 => 0.72.5 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: managed

npx expo-doctor:

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

### Error output

[RUN_FASTLANE] Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
[RUN_FASTLANE] 2023-10-06 15:01:23.244 xcodebuild[32668:1121721] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22267/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
[RUN_FASTLANE] Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
[RUN_FASTLANE] Function: createItemModels(for:itemModelSource:)
[RUN_FASTLANE] Thread:   <_NSMainThread: 0x6000029982c0>{number = 1, name = main}
[RUN_FASTLANE] Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
[RUN_FASTLANE] ** ARCHIVE FAILED **
[RUN_FASTLANE] Exit status: 65

### Reproducible demo or steps to reproduce from a blank project

npx create-expo-app my-app

create and setup eas.json

eas build --platform ios --profile YOUR_PROFILE --local --clear-cache

**Comment by marcato15** [comment]
Having this same issue as well

**Comment by lukegardiner** [comment]
Same issue here too after updating to xCode 15.0 and macOS Sonoma 14.0 on M2 mac.

**Comment by CyonAlexRDX** [comment]
We have this problem with Sonoma and Xcode 15.... takes up 20% of all logs.

**Comment by AzaelContramaestre01** [comment]
same issuea with sonoma and xcode 15

**Comment by NTag** [comment]
Same issue, Sonoma, XCode 15, on a M2 MacBook Air.

It's really problematic as it prevents to build the app locally 🥲

**Comment by verbilonikita** [comment]
To fix an issue run iOS with env var --simulator='iPhone 15' or any preferred iPhone.

e.g.

    "ios": "react-native run-ios --simulator='IPhone 15'",

**Comment by PrajTS** [comment]
Adding `use_modular_headers!` solved this issue. In my case, the firebase packages were the ones causing the issue

**Comment by szdziedzic** [comment]
I believe that this is the same issue as [here](https://github.com/expo/eas-cli/issues/2111#issuecomment-1809954032). The message that you are mentioning is only a warning. Usually `Run Fastlane` phase doesn't contain all of the logs. If you follow my instructions from  https://github.com/expo/eas-cli/issues/2111#issuecomment-1809954032 you should be able to access Xcode logs to see the real error there.

Let me know if it helps!

**Comment by phil-hudson** [comment]
Same issue here:

Xcode 15.0.1

```
[RUN_FASTLANE] Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
[RUN_FASTLANE] 2023-11-30 12:33:37.325 xcodebuild[16491:86116] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22269/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
[RUN_FASTLANE] Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
[RUN_FASTLANE] Function: createItemModels(for:itemModelSource:)
[RUN_FASTLANE] Thread:   <_NSMainThread: 0x7f982d7098c0>{number = 1, name = main}
[RUN_FASTLANE] Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
[RUN_FASTLANE] 2023-11-30 12:33:37.326 xcodebuild[16491:86116] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22269/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
[RUN_FASTLANE] Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
[RUN_FASTLANE] Function: createItemModels(for:itemModelSource:)
[RUN_FASTLANE] Thread:   <_NSMainThread: 0x7f982d7098c0>{number = 1, name = main}
[RUN_FASTLANE] Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
[RUN_FASTLANE] ** ARCHIVE FAILED **
[RUN_FASTLANE] Exit status: 65

[RUN_FASTLANE] +---------------------------------------+
[RUN_FASTLANE] |           Build environment           |
[RUN_FASTLANE] +-------------+-------------------------+
[RUN_FASTLANE] | xcode_path  | /Applications/Xcode.app |
[RUN_FASTLANE] | gym_version | 2.217.0                 |
[RUN_FASTLANE] | sdk         | iPhoneOS17.0.sdk        |
```
```
    "expo": "^49.0.18",
```

**Comment by rajiv-jouvet-idnow** [comment]
Do we have an update regarding this issue? I am still facing this warning.
