### ISSUE TITLE
The "extra.eas.projectId" field is missing from your app config BUT "extra.eas.projectId" is present on app.json

### ISSUE THREAD

**Issue by carlosbernabeujuan** [expo/eas-cli#2084]
### Build/Submit details page URL

https://expo.dev/accounts/micappital/projects/micappital/builds/3d08aae1-44b2-48e8-b2e8-caf1d48abc6d

### Summary

I'm using ` eas build ` to build my app and I'm getting an error stating I do not have the "extra.eas.projectId" in my app.json, which I actually do. Build fails.

In app.json->expo:
`
    "extra": {
      "eas": {
        "projectId": "78ef5b1c-a6f0-4a65-9ca8-6e80fd89d309"  
      }
    },`

There is another user with a similar problem here: [https://stackoverflow.com/questions/76943134/error-the-extra-eas-projectid-field-is-missing-from-your-app-config](url)

### Managed or bare?

bare

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.0 - /usr/local/bin/node
      Yarn: 1.22.19 - ~/Desktop/Development/micappital/micappital-app-v2/node_modules/.bin/yarn
      npm: 9.9.0 - ~/Desktop/Development/micappital/micappital-app-v2/node_modules/.bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.17.2 => 0.17.4 
      expo: ~47.0.12 => 47.0.14 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.8 => 0.70.8 
      react-native-web: ~0.18.9 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 4.1.2
    Expo Workflow: managed

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

### Error output

Using app configuration:

{
  "name": "micappital",
  "slug": "micappital",
  "version": "1.0.0",
  "sdkVersion": "47.0.0",
  "platforms": [
    "ios",
    "android",
    "web"
  ]
}

The "extra.eas.projectId" field is missing from your app config.

### Reproducible demo or steps to reproduce from a blank project

Unfortunatelly, the error is with eas build, the only way to reproduce it is to try to build the project. Not sure how to share the steps.

**Comment by raqso** [comment]
@carlosbernabeujuan Please check your `.gitignore` file. Maybe the app.json is ignored there.

**Comment by carlosbernabeujuan** [comment]
Jesus... it worked. What a stupid mistake from my side. I have multiple devs working on the project and we also had multiple expo environments. Thank you for your help @raqso

**Comment by carlosbernabeujuan** [comment]
Thanks for everything team!
