### ISSUE TITLE
Eas Update not working - export failed

### ISSUE THREAD

**Issue by NOxDriver** [expo/eas-cli#2096]
### Summary

I have an app that is on the app stores and I often need to update the app with small bug fixes. 
I used to do Expo Publish, but now that I'm on SDK 49, I need to use eas update.

When I run that, I get the following error:
✖ Export failed
/*/node_modules/expo/bin/cli exited with non-zero code: 1
    Error: update command failed.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 9.5.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ~0.10.0 => 0.10.7 
      expo: ^49.0.13 => 49.0.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.4.0
      expo-cli: 6.3.10
    Expo Workflow: bare

✔ Check package.json for common issues
✔ Validate global prerequisites versions
✔ Validate Expo Config
✔ Check for conflicting global packages in project
✔ Check for incompatible packages
✔ Check compatible dependency versions for the installed Expo SDK
✔ Verify prebuild support package versions are compatible

Didn't find any issues with the project!

Package.json:
{
  "name": "***.app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@expo/config-plugins": "~7.2.2",
    "@expo/metro-config": "~0.10.0",
    "@expo/prebuild-config": "~6.2.4",
    "@gorhom/bottom-sheet": "^4",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-native-firebase/analytics": "^18.5.0",
    "@react-native-firebase/app": "^18.5.0",
    "@react-native-firebase/auth": "^18.5.0",
    "@react-native-firebase/firestore": "^18.5.0",
    "@react-native-firebase/functions": "^18.5.0",
    "@react-native-firebase/storage": "^18.5.0",
    "@react-navigation/material-bottom-tabs": "^6.2.16",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@rneui/base": "^4.0.0-rc.7",
    "@rneui/themed": "^4.0.0-rc.7",
    "@sentry/react-native": "5.5.0",
    "@turf/turf": "^6.5.0",
    "expo": "^49.0.13",
    "expo-application": "~5.3.0",
    "expo-av": "~13.4.1",
    "expo-build-properties": "~0.8.3",
    "expo-camera": "~13.4.4",
    "expo-checkbox": "~2.4.0",
    "expo-constants": "~14.4.2",
    "expo-dev-client": "~2.4.11",
    "expo-device": "~5.4.0",
    "expo-file-system": "~15.4.4",
    "expo-haptics": "~12.4.0",
    "expo-image-manipulator": "~11.3.0",
    "expo-image-picker": "~14.3.2",
    "expo-linking": "~5.0.2",
    "expo-location": "~16.1.0",
    "expo-mail-composer": "~12.3.0",
    "expo-media-library": "~15.4.1",
    "expo-network": "~5.4.0",
    "expo-notifications": "~0.20.1",
    "expo-splash-screen": "~0.20.5",
    "expo-store-review": "~6.4.0",
    "expo-task-manager": "~11.3.0",
    "expo-tracking-transparency": "~3.1.0",
    "expo-updates": "~0.18.16",
    "moment": "^2.29.4",
    "patch-package": "^6.5.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.6",
    "react-native-device-info": "^10.8.0",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-google-mobile-ads": "^11.1.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-maps": "1.7.1",
    "react-native-onboarding-swiper": "^1.2.0",
    "react-native-paper": "^4.12.4",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-stars": "^1.2.2",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webview": "13.2.2",
    "react-query": "^3.39.3",
    "sentry-expo": "~7.0.0",
    "shorthash": "^0.0.2",
    "styled-components": "^6.0.4",
    "update": "^0.7.4",
    "zustand": "^4.3.9"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3"
  },
  "resolutions": {
    "@expo/config-plugins": "^7.2.2",
    "@expo/prebuild-config": "^6.2.4",
    "expo-modules-autolinking": "~1.5.0"
  },
  "private": true,
  "dev": "APP_VARIANT=development expo start"
}

EAS.JSON:
{
  "cli": {
    "version": ">= 0.52.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "env": {
        "APP_VARIANT": "development"
      }
    },
    "preview": {
      "distribution": "internal",
      "developmentClient": true,
      "ios": {
        "simulator": true
      }
    },
    "production": {
      "android": {
        "buildType": "app-bundle"
      },
      "ios": {
        "image": "macos-ventura-13.3-xcode-14.3"
      }
    }
  },
  "submit": {
    "production": {
      "ios": {
***
      }
    }
  }
}

### Error output

✖ Export failed
/*/node_modules/expo/bin/cli exited with non-zero code: 1
    Error: update command failed.

### Reproducible demo or steps to reproduce from a blank project

I run eas update

**Comment by quinlanj** [comment]
hey @NOxDriver can you run
`npx expo  export --output-dir dist --dump-sourcemap --dump-assetmap --platform=all` and report on the output?

**Comment by NOxDriver** [comment]
Hi,

Thanks for being willing to help!

Here is what I got:

Error: JavaScript engine configuration is inconsistent between app.config.js and iOS native project.
In app.config.js: Hermes is enabled
In iOS native project: Hermes is not enabled

Please check the following files for inconsistencies:
  - /Users/nadavossendryver/Latest Sightings Dropbox/Nadav Ossendryver/Kruger/Technology/1_Phone_App/5.inHouse/LatestSightingsApp/app.config.js
  - /Users/nadavossendryver/Latest Sightings Dropbox/Nadav Ossendryver/Kruger/Technology/1_Phone_App/5.inHouse/LatestSightingsApp/ios/Podfile
  - /Users/nadavossendryver/Latest Sightings Dropbox/Nadav Ossendryver/Kruger/Technology/1_Phone_App/5.inHouse/LatestSightingsApp/ios/Podfile.properties.json
Learn more: https://expo.fyi/hermes-ios-config
Error: JavaScript engine configuration is inconsistent between app.config.js and iOS native project.
In app.config.js: Hermes is enabled

In iOS native project: Hermes is not enabled
Please check the following files for inconsistencies:
  - /Users/nadavossendryver/Latest Sightings Dropbox/Nadav Ossendryver/Kruger/Technology/1_Phone_App/5.inHouse/LatestSightingsApp/app.config.js
  - /Users/nadavossendryver/Latest Sightings Dropbox/Nadav Ossendryver/Kruger/Technology/1_Phone_App/5.inHouse/LatestSightingsApp/ios/Podfile
  - /Users/nadavossendryver/Latest Sightings Dropbox/Nadav Ossendryver/Kruger/Technology/1_Phone_App/5.inHouse/LatestSightingsApp/ios/Podfile.properties.json
Learn more: https://expo.fyi/hermes-ios-config
    at Object.maybeThrowFromInconsistentEngineAsync (/Users/nadavossendryver/Latest Sightings Dropbox/Nadav Ossendryver/Kruger/Technology/1_Phone_App/5.inHouse/LatestSightingsApp/node_modules/@expo/dev-server/build/HermesBundler.js:124:11)
    at async assertEngineMismatchAsync (/Users/nadavossendryver/Latest Sightings Dropbox/Nadav Ossendryver/Kruger/Technology/1_Phone_App/5.inHouse/LatestSightingsApp/node_modules/@expo/cli/build/src/export/fork-bundleAsync.js:24:5)
    at async Promise.all (index 0)
    at async Object.bundleAsync (/Users/nadavossendryver/Latest Sightings Dropbox/Nadav Ossendryver/Kruger/Technology/1_Phone_App/5.inHouse/LatestSightingsApp/node_modules/@expo/cli/build/src/export/fork-bundleAsync.js:29:5)
    at async Object.createBundlesAsync (/Users/nadavossendryver/Latest Sightings Dropbox/Nadav Ossendryver/Kruger/Technology/1_Phone_App/5.inHouse/LatestSightingsApp/node_modules/@expo/cli/build/src/export/createBundles.js:39:21)
    at async Object.exportAppAsync (/Users/nadavossendryver/Latest Sightings Dropbox/Nadav Ossendryver/Kruger/Technology/1_Phone_App/5.inHouse/LatestSightingsApp/node_modules/@expo/cli/build/src/export/exportApp.js:64:21)
    at async exportAsync (/Users/nadavossendryver/Latest Sightings Dropbox/Nadav Ossendryver/Kruger/Technology/1_Phone_App/5.inHouse/LatestSightingsApp/node_modules/@expo/cli/build/src/export/exportAsync.js:45:5)

What should I do?

**Comment by quinlanj** [comment]
Oh interesting... usually when that happens it's due to the app not being configured correctly. Could you check that everything is configured correctly using the guide here: https://docs.expo.dev/eas-update/debug/

**Comment by OdebisiidowuSolomon** [comment]
What solved my issue was to run the following command

npx expo start -c 

then eas update

**Comment by quinlanj** [comment]
Closed due to inactivity

**Comment by panchal-krunal** [comment]
Do we have any solution for this ?

**Comment by serkanbilsel** [comment]
i couldnt find solution yet..

**Comment by bd1354** [comment]
@serkanbilsel I'm having same issue

**Comment by va-p** [comment]
Hi,

I found a solution.

Steps for fix:

1 - Add environment variable in bashrc ”export NODE_OPTIONS=--max-old-space-size=8192”
2 - Before run eas update, run this command in your terminal: export NODE_OPTIONS=--max-old-space-size=8192
3 - After step 2, run eas update!

This is worked for me. OBS: I use linux, so, I tested only on linux!

**Comment by BohdanKhv** [comment]
Hi,
I had this issue because it was building for iOS, Android, and web. I don't work with web, so I have a bunch of native code in the app "eas update" was trying to update the web version, and it was causing that error.

Here's what worked for me:
Try specifying the platform you want to build for. 

eas update --branch production --platform ios --message "You fix message"
