### ISSUE TITLE
details of the error related to the provisioning profile

### ISSUE THREAD

**Issue by landvibe** [expo/eas-cli#2097]
### Build/Submit details page URL

https://expo.dev/accounts/infinistar/projects/diggerz

### Summary

At first, I encountered an error stating that the provisioning profile and certificate did not match. After replacing the provisioning profile, I ran the 'eas build'. However, another error occurred, and I cannot understand the content just by looking at the error message. I would like to know the detailed error information.

### Managed or bare?

managed

### Environment

```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
```
```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.2.1
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
      Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~49.0.13 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.4.0
    Expo Workflow: managed
```

### Error output

```
$ eas build -p ios --profile preview
Loaded "env" configuration for the "preview" profile: EXPO_PUBLIC_WEB_HOST. Learn more
✔ Using local iOS credentials (credentials.json)
✔ Would you like to set up Push Notifications for your project? › No

Compressing project files and uploading to EAS Build. Learn more
✔ Uploaded to EAS 2s
Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
Request ID: 34b1bbcc-d61c-4f7b-806c-31ceb01fbe50
Error message: Unexpected server error (Expo error ID: 34b1bbcc-d61c-4f7b-806c-31ceb01fbe50).
    Error: build command failed.
error Command failed with exit code 1.
```

### Reproducible demo or steps to reproduce from a blank project

I "At first, I encountered an error stating that the provisioning profile and certificate did not match. After replacing the provisioning profile, I ran the 'eas build'. However, another error occurred, and I cannot understand the content just by looking at the error message. I would like to know the detailed error information.

**Comment by landvibe** [comment]
The further analysis I conducted is as follows:

My Provisioning profile contains multiple certificates.
However, it seems that EAS only checks the fingerprint of the first certificate and doesn't review all of them.
Does EAS require the Provisioning profile to contain only one certificate?

below is original error message
the provisioning profile has 2 certificates and it has the distribution certificate fingerprint (in the error msg)
```
Build failed: Provisioning profile and distribution certificate don't match.
Profile's certificate fingerprint = ******, distribution certificate fingerprint = #######
```

**Comment by szdziedzic** [comment]
Hi,

When it comes to
```
Request ID: 34b1bbcc-d61c-4f7b-806c-31ceb01fbe50
Error message: Unexpected server error (Expo error ID: 34b1bbcc-d61c-4f7b-806c-31ceb01fbe50).
    Error: build command failed.
```
error. It was our infra having issues as far as I can tell looking at logs. So it doesn't seem related to provisioning profile issues. Did replacing the certificate help after retrying one more time?
