### ISSUE TITLE
EAS is reporting gradlew :app:assembleDebug builds to be "release" builds

### ISSUE THREAD

**Issue by viljark** [expo/eas-cli#2105]
### Build/Submit details page URL

https://expo.dev/accounts/rematocorp/projects/remato-sm-dev/builds/41fdeb9a-f44a-4669-a1ff-43a2146797cf

### Summary

Expo EAS is reporting gradlew :app:assembleDebug builds to be "release" builds, for example in this app.gradle.

This code in if gets executed in builds with development client, is this a regression on EAS side?

```
android {
    purgeBackgroundGeolocationDebugResources(applicationVariants)
}

def purgeBackgroundGeolocationDebugResources(applicationVariants) {
    applicationVariants.all { variant ->
        if (variant.buildType.name == "release") {
            println("[react-native-background-geolocation] Purging debug resources in release build")
            variant.mergeResourcesProvider.configure {
                doLast {
                    delete(fileTree(dir: outputDir, includes: ["raw_tslocationmanager*"]))
                }
            }
        }
    }
}
```

Relevant logs
```
Running 'gradlew :app:assembleDebug' in /home/expo/workingdir/build/android

> Configure project :app

 :information_source:  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@2.4.13)

 :information_source:  Applying gradle plugin 'expo-updates-gradle-plugin' (expo-updates@0.18.16)

Minifying disabled for variant debug, no upload task created

[react-native-background-geolocation] Purging debug resources in release build

Minifying disabled for variant release, no upload task created
```

### Managed or bare?

bare (prebuild)

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
      npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/lib/ruby/gems/3.1.0/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10406996
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.0 => 49.0.16 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.5.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Create new Expo SDK 49 project with react-native-background-geolocation installed:
https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-EXPO.md

run a build with development client ("developmentClient": true, in eas.json)

**Comment by brentvatne** [comment]
the `developmentClient` field sets the release to a debug build, thus `Running 'gradlew :app:assembleDebug'`

https://docs.expo.dev/eas/json/#developmentclient

**Comment by viljark** [comment]
@brentvatne how come variant.buildType.name is "release" then? Or is this a misconfiguration on the geolocation library side to use variant.buildType.name to detect debug builds?

**Comment by brentvatne** [comment]
<img width="891" alt="image" src="https://github.com/expo/eas-cli/assets/90494/7cd4b90b-3156-4f24-aa96-db28ce4a52b5">

from your logs, it appears that react-native-background-geolocation is detecting this as neither a debug nor release build.

> how come variant.buildType.name is "release" then? Or is this a misconfiguration on the geolocation library side to use variant.buildType.name to detect debug builds?

that could be the case! i don't know much about this library.

you can see pretty transparently what eas build is doing for you:

> Running 'gradlew :app:assembleDebug' in /home/expo/workingdir/build/android

if you want to debug this locally further, you can run `npx expo prebuild -p android` and inspect the results
