### ISSUE TITLE
Autoincrement buildNumber with Github Actions

### ISSUE THREAD

**Issue by quotentiroler** [expo/eas-cli#2116]
### Do you understand that any feature requests opened in this repository will be closed?

Yes

**Comment by quotentiroler** [comment]
Hello, some time has passed now since this topic was discussed but it seems that it is still impossible to use autoincrement on buildNumber together with github actions, unless there is some fancy workaround for the commit.

Since expo builds run on expo server, why is it necessary to overwrite the app.json file with the autoincrement set true? It would make more sense to autoincrement buildNumber only on the expo server if set to true and not overwrite app.json at all since the only reason why developers want autoincrement is to not have the same buildNumber twice in the expo builds, in order to successfully run eas submit. If the buildNumber is specified, it can be used, but if not and autoincrement is true, it should just autoincrement on the server, not in the repo. 

Thanks for considering my suggestion.

**Comment by brentvatne** [comment]
hi @quotentiroler - you are right, you don't need to overwrite the value! I recommend setting up remote version management as described here: https://docs.expo.dev/build-reference/app-versions/
