### ISSUE TITLE
iOS build fails with transient error

### ISSUE THREAD

**Issue by alkhatera** [expo/eas-cli#2122]
### Summary

Build fails after uploading the build files to EAS servers
Specifically after `Uploaded to EAS` is done

```
We've encountered a transient error. Try again shortly.
Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
Request ID: d9552eff-4da1-4da3-959d-fcf603e72583
```

### Managed or bare?

Managed

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22621
    Binaries:
      Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 3.4.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 30, 31, 33
        Build Tools: 30.0.2, 30.0.3, 33.0.0, 33.0.2, 34.0.0
        System Images: android-33 | Google APIs Intel x86_64 Atom
    IDEs:
      Android Studio: AI-222.4459.24.2221.9971841
    Expo Workflow: managed
```

### Error output

```
We've encountered a transient error. Try again shortly.
Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
Request ID: d9552eff-4da1-4da3-959d-fcf603e72583
```

### Reproducible demo or steps to reproduce from a blank project

run `npx eas build --profile development --platform ios` or `npx eas build --platform ios` and wait for the error to appear

**Comment by szdziedzic** [comment]
Hi,

I can't find any internal logs regarding this request ID. Does this error persist for you or was it a transient one?

**Comment by alkhatera** [comment]
It used to run fine on my Windows machine until today. I couldn't get it to build.

However, I just tried to build on my Mac machine and it worked!

**Comment by szdziedzic** [comment]
So even if you try to run a new build on your Windows machine right now it won't work? Are you using the latest CLI version?

**Comment by alkhatera** [comment]
Now I tried and it seems to work fine. Weird issue

**Comment by szdziedzic** [comment]
I think it could have been some transient issue with our infra. I will mark the issue as resolved, but let me know if you experience it again!
