### ISSUE TITLE
EAS build do not have error but ** ARCHIVE FAILED **  Exit status: 65

### ISSUE THREAD

**Issue by sadacode** [expo/eas-cli#2126]
### Summary

Migrating from Expo classic build to eas build but it always fails with 

https://expo.dev/accounts/bustrackie/projects/trackie/builds/4d512645-00a3-440b-a83b-8369905ac762

** ARCHIVE FAILED **  Exit status: 65
------------------------------------------------
 Executing trackie » Bundle React Native code and images

    Bundler cache is empty, rebuilding (this may take a minute)

› Executing trackie » [CP] Copy Pods Resources

› Executing trackie » [CP] Embed Pods Frameworks

› Executing trackie » [CP-User] [RNFB] Core Configuration

› Executing trackie » [CP-User] [RNFB] Crashlytics Configuration

› Executing trackie » [CP-User] [RNGoogleMobileAds] Configuration

› Signing   trackie » trackie.app

› Creating  trackie » trackie.app

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'fmt' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'abseil' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-debug' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'BoringSSL-GRPC' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RCT-Folly' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-utils' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'gRPC-Core' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-runtimescheduler' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'ReactCommon' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'gRPC-C++' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-NativeModulesApple' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-Codegen' from project 'Pods')

    Run script build phase '[CP-User] Generate app.manifest for expo-updates' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXUpdates' from project 'Pods')

▸ ** ARCHIVE FAILED **

2023-11-17 18:12:23.074 xcodebuild[35581:45614] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)

** ARCHIVE FAILED **

Exit status: 65

+-------------+-------------------------+

|           Build environment           |

+-------------+-------------------------+

| xcode_path  | /Applications/Xcode.app |

| gym_version | 2.213.0                 |

| sdk         | iPhoneOS16.4.sdk        |

+-------------+-------------------------+

Looks like fastlane ran into a build/archive error with your project

It's hard to tell what's causing the error, so we wrote some guides on how

to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/

Before submitting an issue on GitHub, please follow the guide above and make

sure your project is set up correctly.

fastlane uses `xcodebuild` commands to generate your binary, you can see the

the full commands printed out in yellow in the above log.

Make sure to inspect the output above, as usually you'll find more error information there

[!] Error building the application - see the log above

Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.

### Managed or bare?

Managed

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 2023.09.25.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.14.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
      Android SDK:
        API Levels: 27, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.1, 30.0.3
        System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.3.0 => 9.5.0 
      expo: ^49.0.6 => 49.0.18 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
    npmGlobalPackages:
      eas-cli: 5.8.0
      expo-cli: 6.3.10
    Expo Workflow: bare
    
    
    npx expo-doctor
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check npm/ yarn versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

### Error output

Xcode log google drive from EAS. The project works fine when make for "distribution": "internal",

https://drive.google.com/file/d/1qdz8fPfi0tG8yqna5TCXiSUoSCBNmVAA/view?usp=sharing

Last logs from fastlane

› Copying   ../../../Users/expo/Library/Developer/Xcode/DerivedData/trackie-ftrkcgwbsgbzcmceiitmerqvziqt/Build/Intermediates.noindex/ArchiveIntermediates/trackie/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Pods_trackie.framework/Headers/Pods-trackie-umbrella.h ➜ ../../../Users/expo/workingdir/build/ios/Pods/Target/ Support/ Files/Pods-trackie/Pods-trackie-umbrella.h

› Preparing Pods/Pods-trackie » Pods-trackie-Info.plist

› Compiling Pods/Pods-trackie » Pods-trackie-dummy.m

› Compiling Pods/Pods-trackie » Pods_trackie_vers.c

› Creating  Pods/Pods-trackie » Pods_trackie.framework

    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'trackie' from project 'trackie')

    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'trackie' from project 'trackie')

    Run script build phase '[CP-User] [RNFB] Core Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'trackie' from project 'trackie')

    Run script build phase '[CP-User] [RNFB] Crashlytics Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'trackie' from project 'trackie')

    Run script build phase '[CP-User] [RNGoogleMobileAds] Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'trackie' from project 'trackie')

› Executing [CP] Check Pods M

› Executing trackie » Start Packager on http://localhost:8081

› Executing trackie » [Expo] Configure project

› Copying   ios/trackie/GoogleService-Info.plist ➜ ./GoogleService-Info.plist

› Copying   ios/trackie/Supporting/Expo.plist ➜ ./Expo.plist

› Compiling trackie » SplashScreen.storyboard

› Preparing trackie » Info.plist

› Compiling trackie » trackie_vers.c

› Compiling trackie » main.m

› Compiling trackie » AppDelegate.mm

› Linking   trackie » trackie

⚠️  ld: method '+moduleName' in category from /Users/expo/Library/Developer/Xcode/DerivedData/trackie-ftrkcgwbsgbzcmceiitmerqvziqt/Build/Intermediates.noindex/ArchiveIntermediates/trackie/BuildProductsPath/Release-iphoneos/ExpoModulesCore/ExpoModulesCore.framework/ExpoModulesCore(ExpoBridgeModule-67835c281e72c2875d79b5cb283dbe2d.o) overrides method from class in /Users/expo/Library/Developer/Xcode/DerivedData/trackie-ftrkcgwbsgbzcmceiitmerqvziqt/Build/Intermediates.noindex/ArchiveIntermediates/trackie/BuildProductsPath/Release-iphoneos/ExpoModulesCore/ExpoModulesCore.framework/ExpoModulesCore(ExpoBridgeModule-39dc610558659414887c85f7debe2801.o)

⚠️  ld: method '+UIUserInterfaceStyle:' in category from /Users/expo/Library/Developer/Xcode/DerivedData/trackie-ftrkcgwbsgbzcmceiitmerqvziqt/Build/Intermediates.noindex/ArchiveIntermediates/trackie/BuildProductsPath/Release-iphoneos/RNDateTimePicker/RNDateTimePicker.framework/RNDateTimePicker(RNDateTimePickerManager.o) overrides method from class in /Users/expo/Library/Developer/Xcode/DerivedData/trackie-ftrkcgwbsgbzcmceiitmerqvziqt/Build/Intermediates.noindex/ArchiveIntermediates/trackie/BuildProductsPath/Release-iphoneos/React-Core/React.framework/React(RCTConvert.o)

⚠️  ld: method '+UIStatusBarAnimation:' in category from /Users/expo/Library/Developer/Xcode/DerivedData/trackie-ftrkcgwbsgbzcmceiitmerqvziqt/Build/Intermediates.noindex/ArchiveIntermediates/trackie/BuildProductsPath/Release-iphoneos/RNScreens/RNScreens.framework/RNScreens(RNSScreen.o) conflicts with same method from another category

⚠️  ld: method '+UIDatePickerMode:' in category from /Users/expo/Library/Developer/Xcode/DerivedData/trackie-ftrkcgwbsgbzcmceiitmerqvziqt/Build/Intermediates.noindex/ArchiveIntermediates/trackie/BuildProductsPath/Release-iphoneos/react-native-date-picker/react_native_date_picker.framework/react_native_date_picker(RNDatePickerManager.o) conflicts with same method from another category

› Generating debug trackie » trackie.app.dSYM

› Executing trackie » Bundle React Native code and images

    Bundler cache is empty, rebuilding (this may take a minute)

› Executing trackie » [CP] Copy Pods Resources

› Executing trackie » [CP] Embed Pods Frameworks

› Executing trackie » [CP-User] [RNFB] Core Configuration

› Executing trackie » [CP-User] [RNFB] Crashlytics Configuration

› Executing trackie » [CP-User] [RNGoogleMobileAds] Configuration

› Signing   trackie » trackie.app

› Creating  trackie » trackie.app

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'fmt' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'abseil' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-debug' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'BoringSSL-GRPC' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RCT-Folly' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'gRPC-Core' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-utils' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-runtimescheduler' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'ReactCommon' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'gRPC-C++' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-NativeModulesApple' from project 'Pods')

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-Codegen' from project 'Pods')

    Run script build phase '[CP-User] Generate app.manifest for expo-updates' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXUpdates' from project 'Pods')

▸ ** ARCHIVE FAILED **

2023-11-18 17:46:46.771 xcodebuild[35146:44033] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)

** ARCHIVE FAILED **

Exit status: 65

+-------------+-------------------------+

|           Build environment           |

+-------------+-------------------------+

| xcode_path  | /Applications/Xcode.app |

| gym_version | 2.213.0                 |

| sdk         | iPhoneOS16.4.sdk        |

+-------------+-------------------------+

Looks like fastlane ran into a build/archive error with your project

It's hard to tell what's causing the error, so we wrote some guides on how

to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/

Before submitting an issue on GitHub, please follow the guide above and make

sure your project is set up correctly.

fastlane uses `xcodebuild` commands to generate your binary, you can see the

the full commands printed out in yellow in the above log.

Make sure to inspect the output above, as usually you'll find more error information there

[!] Error building the application - see the log above

Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.

### Reproducible demo or steps to reproduce from a blank project

Its a EAS Build issue when making it for app store, so not sure what code to provide here

**Comment by vishaljnimblechapps** [comment]
i'm facing same issue, Anything on this ?

**Comment by ofer-malbin-lobix-me** [comment]
I am facing the same error.
For me the error appears after I added these settings in app.json:
expo.ios.entitlements: { "com.apple.developer.family-controls": true }

**Comment by Anyamborogass** [comment]
Same issue for me... :(

**Comment by wengqianshan** [comment]
I also encountered a similar `65` problem a few days ago.The following is my solution idea, which finally solved the problem. hope it help you.

1. Get detailed logs
```shell
export EAS_LOCAL_BUILD_SKIP_CLEANUP=1
eas build -p ios --local
```

2. After the build is completed, the cache directory will be output similar to: /var/folders/7d/lrm7kd194kbcvdx6zpl9zcmr0000gn/T/eas-build-local-nodejs/50c66fa9-dd56-4742-b18e-f7541d240807

3. Find the log file logs/app-app.log and find the following error
```
/var/folders/7d/lrm7kd194kbcvdx6zpl9zcmr0000gn/T/eas-build-local-nodejs/3abb902f-122c-490b-b6e3-d416d4e57ed2/build/ios/WKTV.xcodeproj: error: Provisioning profile "*[expo] com.xxxxxx. yyy AppStore 2024-01-18T17:02:50.071Z" doesn't include signing certificate "Apple Distribution: xxxxxx (xxxxxxx)". (in target 'xxxx' from project 'xxx')
```

4. Locate the certificate problem through the above problems, log in to expo.dev, find `Account settings -> Credentials`, and delete all certificates in `Apple Distribution Certificates`

5. Following the previous step, export the p12 file locally and upload it to `Apple Distribution Certificates` (I am not sure if this step is necessary, you can try it yourself)

6. Re-execute `eas build -p ios --local`

**Comment by ratneshkumarroot** [comment]
not worked fro me

**Comment by jvgeee** [comment]
This came up first in Google when I searched for it so I'll post a solution here:

EAS Build (local as well as in the cloud) was failing for me on IOS because Apple Developer had some updates and all of my provisioning profiles had become invalid. EAS should've notified me of this, but they didn't.

The solution: 

1. Go into your Apple Developer account and check your [Provisioning Profiles](https://developer.apple.com/account/resources/profiles/list), as well as your other certificates etc, see if anything's invalid.
2. If they're invalid: Delete them within Apple Developer
3. Then run `eas build` again and say `yes` when it asks if it should generate new provisioning profiles

**Comment by stewartmoreland** [comment]
adding on to @jvgeee's comment, the best method for determining issues in `--local` builds, is to ensure the `EAS_LOCAL_BUILD_SKIP_CLEANUP` is set to `=1`

```shell
export EAS_LOCAL_BUILD_SKIP_CLEANUP=1
```

This will ensure your XCode logs are retained after the local build is complete. After that, command + click the link to the `/var/folders/wn/<SOMETHING>/T/eas-build-local-nodejs/` directory to find the build output logs folder. This helped me determine where my error originated and what capability I needed to fix.

I think with that information, this issue thread could be resolved for many RN/Expo beginners (like me) who suffered from the same issue for hours before I finally realized that I was missing a lot of detail in the logs.

https://docs.expo.dev/build-reference/local-builds/#use-local-builds-for-debugging

Secondly, for the Expo team, I think the Apple entitlement / capability documentation could be updated to include attribute types. That would have helped me significantly. Instead of relying on those, I opened my project in XCode and added the required capabilities, looked in the `ios/<PROJECT_NAME>/<PROJECT_NAME>.entitlements` file to find out what XML data types were expected and translated those to JSON.

Hope this helps those who find this thread. 🙏

**Comment by Osilos** [comment]
> This came up first in Google when I searched for it so I'll post a solution here:
> 
> EAS Build (local as well as in the cloud) was failing for me on IOS because Apple Developer had some updates and all of my provisioning profiles had become invalid. EAS should've notified me of this, but they didn't.
> 
> The solution:
> 
> 1. Go into your Apple Developer account and check your [Provisioning Profiles](https://developer.apple.com/account/resources/profiles/list), as well as your other certificates etc, see if anything's invalid.
> 2. If they're invalid: Delete them within Apple Developer
> 3. Then run `eas build` again and say `yes` when it asks if it should generate new provisioning profiles

This was my issue thanks.

**Comment by gitnlsn** [comment]
> I also encountered a similar `65` problem a few days ago.The following is my solution idea, which finally solved the problem. hope it help you.
> 
> 1. Get detailed logs
> 
> ```shell
> export EAS_LOCAL_BUILD_SKIP_CLEANUP=1
> eas build -p ios --local
> ```
> 
> 2. After the build is completed, the cache directory will be output similar to: /var/folders/7d/lrm7kd194kbcvdx6zpl9zcmr0000gn/T/eas-build-local-nodejs/50c66fa9-dd56-4742-b18e-f7541d240807
> 3. Find the log file logs/app-app.log and find the following error
> 
> ```
> /var/folders/7d/lrm7kd194kbcvdx6zpl9zcmr0000gn/T/eas-build-local-nodejs/3abb902f-122c-490b-b6e3-d416d4e57ed2/build/ios/WKTV.xcodeproj: error: Provisioning profile "*[expo] com.xxxxxx. yyy AppStore 2024-01-18T17:02:50.071Z" doesn't include signing certificate "Apple Distribution: xxxxxx (xxxxxxx)". (in target 'xxxx' from project 'xxx')
> ```
> 
> 4. Locate the certificate problem through the above problems, log in to expo.dev, find `Account settings -> Credentials`, and delete all certificates in `Apple Distribution Certificates`
> 5. Following the previous step, export the p12 file locally and upload it to `Apple Distribution Certificates` (I am not sure if this step is necessary, you can try it yourself)
> 6. Re-execute `eas build -p ios --local`

Error persists for me.

**Comment by marlo22** [comment]
In my case, I had two versions of Xcode installed - one normally from the AppStore and the other (older) in the “Download” directory. When building my app, Expo was using the older version. Removing the older version of Xcode solved the problem.

I suppose a similar problem may occur if you have installed one version of Xcode, but it's too old to work with the latest version of React Native/Expo.
