### ISSUE TITLE
Resign command returns "Build in not retriable" error

### ISSUE THREAD

**Issue by rafcremer** [expo/eas-cli#2127]
### Summary

When running `eas build:resign`, and selecting the build and profiles, at the end I always get the following error:

```
Build in not retriable - {GUID}
Request ID: {GUID}
    Error: GraphQL request failed.
```

I don't have any visual indication that the build has been resigned after that, but if I run `eas build:resign` for a second time it seems like the provisioned profiles have already been included and I don't have to select them again.

### Managed or bare?

Bare

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
      npm: 6.14.17 - ~/.nvm/versions/node/v14.21.2/bin/npm
      Watchman: 2022.09.26.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8309675
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~48.0.21 => 48.0.21 
      react: 18.2.0 => 18.2.0 
      react-native: 0.71.14 => 0.71.14 
    npmGlobalPackages:
      eas-cli: 5.9.0
      expo-cli: 6.3.10
    Expo Workflow: bare

### Error output

```
Build in not retriable - {GUID}
Request ID: {GUID}
    Error: GraphQL request failed.
```

### Reproducible demo or steps to reproduce from a blank project

- run ` eas build:resign`
- select platform IOS
- select latest build
- log in to your Apple Developer account
- show devices registered in the Provisioning Profile
- select devices and continue

**Comment by jiangts** [comment]
+1

**Comment by szdziedzic** [comment]
Hi there! 👋  

I deployed a fix today which should fix this bug. Let me know if it starts to work for you. 

I also made the error message better so it specifies the exact reason why you can't retry/resign the build.

**Comment by szdziedzic** [comment]
I believe this is fixed now
