### ISSUE TITLE
Error: build command failed.

### ISSUE THREAD

**Issue by duriantaco** [expo/eas-cli#2128]
### Summary

Everything was working fine yesterday, and today I get this 

Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
    Error: build command failed.

### Managed or bare?

Managed

### Environment

(base) oha@Ohs-MacBook-Air taco_ai % npx expo-doctor
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

### Error output

Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.

### Reproducible demo or steps to reproduce from a blank project

{
  "name": "test",
  "version": "1.0.1",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "lint": "eslint .",
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~48.0.6",
    "expo-auth-session": "~4.0.3",
    "expo-status-bar": "~1.4.4",
    "expo-web-browser": "~12.1.1",
    "lottie-react-native": "5.1.4",
    "react": "18.2.0",
    "react-native": "0.71.14",
    "react-native-chart-kit": "^6.12.0",
    "react-native-confetti-cannon": "^1.5.2",
    "react-native-elements": "^3.4.3",
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.22.6",
    "@babel/preset-react": "^7.22.5",
    "@babel/runtime": "^7.22.6",
    "@testing-library/react-native": "^12.1.2",
    "jest": "^29.6.0",
    "metro-react-native-babel-preset": "^0.76.7"
  },
  "private": true
}

**Comment by greedydurian** [comment]
Is there an outage or something?

**Comment by pfcodes** [comment]
+1

**Comment by pfcodes** [comment]
Issue appears to be with how Free project build limits are metered. The dashboard says I've used 15/30 builds but the system is acting like I ran out of builds. Upgrading the subscription resolved the issue.

**Comment by pfcodes** [comment]
> Hi, which EAS CLI version are you using?

It turns out that in my case, VSCode was using a different node version from my terminal which had an old installation of eas-cli which did not show the error message about the build count limit being reached. When I ran the command in terminal I saw the error message about needing to upgrade. So in my particular case there was actually no bug with EAS.
