### ISSUE TITLE
Too many verification codes

### ISSUE THREAD

**Issue by zRelux** [expo/eas-cli#2143]
### Summary

Since yesterday I have been getting this error when trying to build with eas build.
```
Authentication with Apple Developer Portal failed!
Too many verification codes have been sent. Enter the last code you received or try again later.
```

I am wondering if it is related to the new app store changes. Not sure also on how to bypass this problem: I tried cleaning my `.app-store` folder, using `EXPO_NO_KEYCHAIN=1 `, without any major luck.

I also tried to look into the fastlane docs, but nothing there as well, I am hoping for any way to fix this, even doing all the setup again would be fine

### Managed or bare?

bare

### Environment

<details>
  <summary>Env</summary>

```
  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7 
      expo: ^49.0.7 => 49.0.13 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: ^0.72.6 => 0.72.6 
      react-native-web: ^0.19.9 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.9.1
    Expo Workflow: bare
```
```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~7.2.2
Found invalid:
  @expo/config-plugins@6.0.2
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions.

Some dependencies are incompatible with the installed expo version:
  @react-native-community/netinfo@9.4.1 - expected version: 9.3.10
  @shopify/flash-list@1.6.2 - expected version: 1.4.3
  expo-dev-client@2.4.11 - expected version: ~2.4.12
  expo-device@5.6.0 - expected version: ~5.4.0
  expo-document-picker@11.7.0 - expected version: ~11.5.4
  expo-file-system@15.4.4 - expected version: ~15.4.5
  expo-image@1.5.1 - expected version: ~1.3.5
  expo-image-manipulator@11.5.0 - expected version: ~11.3.0
  expo-image-picker@14.5.0 - expected version: ~14.3.2
  expo-insights@0.4.0 - expected version: ~0.2.0
  expo-linear-gradient@12.5.0 - expected version: ~12.3.0
  expo-localization@14.5.0 - expected version: ~14.3.0
  expo-updates@0.18.15 - expected version: ~0.18.17
  expo-web-browser@12.5.0 - expected version: ~12.3.2
  react-native-gesture-handler@2.13.1 - expected version: ~2.12.0
  react-native-pager-view@6.2.3 - expected version: 6.2.0
  react-native-reanimated@3.6.1 - expected version: ~3.3.0
  react-native-safe-area-context@4.7.2 - expected version: 4.6.3
  react-native-svg@13.14.0 - expected version: 13.9.0
  jest-expo@48.0.2 - expected version: ~49.0.0
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

</details>

### Reproducible demo or steps to reproduce from a blank project

Just run `eas build --platform ios`

**Comment by szdziedzic** [comment]
Good to hear it! 

I think it's just SMS rate limiting on Apple's side. We are not controlling it, just using their API when it comes to logging in/sending OTP.

I will close this issue because I believe the problem itself is not related to EAS CLI.

**Comment by gustavoelizalde** [comment]
I'm having the same issue.

Is there a waiting time to solve this?

Should not `eas-cli` request for the last code instead forcing the exit?

**Comment by gustavoelizalde** [comment]
@szdziedzic is there anything that could be done from the `eas-cli` perspective?

**Comment by jorgezerpa** [comment]
> @szdziedzic is there anything that could be done from the `eas-cli` perspective?

Exactly! it should request for the older code, when you try to login into https://appstoreconnect.apple.com/login it is the way it works

**Comment by thomas-coldwell** [comment]
Hey @szdziedzic - I'm in agreement here that it should not exit if the error is `Too many verification codes have been sent. Enter the last code you received or try again later.` as there should be a prompt for input from the user to enter their last code at this stage. 

I can see that it reaches this method and then throws https://github.com/expo/eas-cli/blob/56510f092527e458aa9dca19feac0b5d425dac56/packages/eas-cli/src/credentials/ios/appstore/authenticate.ts#L141, however, this seems to be part of the `@expo/apple-utils` package which is not public afaict and so would have to be an internal change to support this. If I am mistaken please let me know and I'd be more than happy to submit a PR here to support this :)

**Comment by wooller** [comment]
Just ran into this today too, I imagine its fairly low down on the priority list but having the cli allow inputting the most recent SMS code would be amazing!

**Comment by jorgezerpa** [comment]
@zane-commeatio Hi!

I went through this issue a couple weeks ago. It seems like it has nothing to do with Expo or eas-cli, the error comes from IOS servers. In my case, it just get fixed by wating a couple days without attemping getting a code. 

During that time, I figured it out how to make the builds using non-interactive mode, so you can try:

 `eas build --platform ios --non-interactive`

And this will start the build inmediatly (it will take more time than usually, but it works!). 

### Plus:
If you need to make a submit after your build (example -> submit to Testflight) you can make:
`eas submit --platform ios -- id {id-build} --non-interactive`

You can found the id-build on your expo dashboard -> go to your build -> in top-right corner you will se a button "View details" -> click on it and you will see your id-build.

## Important 
If you going to make the submit by this way, you will need to add this into the root object of your eas.json file:
```
 "submit": {
    "production": {
      "ios": {
        "appleId": { a string with the username or email of your apple account },
        "ascAppId": { a string. You can found this value on your apple developer console }
      }
    }
  }
```


Let me know if it works bro🚀
