### ISSUE TITLE
eas build --local fails for both of my apps with the same error -> A problem occurred configuring project ':expo-av'

### ISSUE THREAD

**Issue by mmuminovic** [expo/eas-cli#2144]
### Summary

For both of my apps, when I try `eas build --local` the builds fail with the same error message
I couldn't find any useful resource or someone who has similar issue

The builds succeeded when I use expo.dev for building

### Managed or bare?

Managed

### Environment

npx expo-env-info
`expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.6.1
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.5 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9514443
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ^9.5.0 => 9.5.2 
      expo: ^48.0.0 => 48.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.14 => 0.71.14 
    npmGlobalPackages:
      eas-cli: 5.9.1
      expo-cli: 6.3.10
    Expo Workflow: managed`
    
    npx expo-doctor
    `✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!`

package.json
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "npx expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "build:apk": "eas build --profile preview --platform android",
    "build:android": "eas build --profile production --platform android",
    "build:ios": "eas build --profile production --platform ios",
    "build:all": "eas build --profile production --platform all",
    "publish:ios": "eas submit -p ios --latest --profile production"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-firebase/analytics": "^18.7.1",
    "@react-native-firebase/app": "^18.7.1",
    "@react-navigation/bottom-tabs": "^5.11.2",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "@reduxjs/toolkit": "^1.8.1",
    "axios": "^0.27.2",
    "expo": "^48.0.0",
    "expo-av": "~13.2.1",
    "expo-build-properties": "~0.6.0",
    "expo-constants": "~14.2.1",
    "expo-dev-client": "~2.2.1",
    "expo-font": "~11.1.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-linking": "~4.0.1",
    "expo-location": "~15.1.1",
    "expo-sensors": "~12.1.1",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-store-review": "~6.2.1",
    "expo-updates": "~0.16.4",
    "i18next": "^20.2.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-i18next": "^11.8.13",
    "react-native": "0.71.14",
    "react-native-dropdown-picker": "^5.1.15",
    "react-native-elements": "^3.1.0",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-modal": "^11.10.0",
    "react-native-paper": "^4.8.1",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-side-menu": "^1.1.3",
    "react-native-size-matters": "^0.4.0",
    "react-native-swiper-flatlist": "^3.0.14",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^7.1.0",
    "react-redux": "^8.0.1",
    "styled-components": "^5.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "babel-preset-expo": "^9.5.0"
  },
  "private": true
}
`

### Error output

`[RUN_GRADLEW] > Configure project :app
[RUN_GRADLEW]  ℹ️  Applying gradle plugin 'expo-dev-launcher-gradle-plugin' (expo-dev-launcher@2.2.1)
[RUN_GRADLEW] > Configure project :expo-application
[RUN_GRADLEW] WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
[RUN_GRADLEW] > Configure project :expo-av
[RUN_GRADLEW] WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
[RUN_GRADLEW] FAILURE: Build completed with 2 failures.
[RUN_GRADLEW] 1: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * Where:
[RUN_GRADLEW] Script '/private/tmp/eas-build-local-nodejs/50e6c6b3-2b1c-4849-b1a1-4f9818bc2044/build/node_modules/expo-modules-autolinking/scripts/android/autolinking_implementation.gradle' line: 326
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem occurred evaluating project ':expo'.
[RUN_GRADLEW] > A problem occurred configuring project ':expo-av'.
[RUN_GRADLEW]    > Failed to notify project evaluation listener.
[RUN_GRADLEW]       > SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at '/private/tmp/eas-build-local-nodejs/50e6c6b3-2b1c-4849-b1a1-4f9818bc2044/build/android/local.properties'.
[RUN_GRADLEW]       > Could not get unknown property 'release' for SoftwareComponentInternal set of type org.gradle.api.internal.component.DefaultSoftwareComponentContainer.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] 2: Task failed with an exception.
[RUN_GRADLEW] -----------
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem occurred configuring project ':expo'.
[RUN_GRADLEW] > compileSdkVersion is not specified. Please add it to build.gradle
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] >
[RUN_GRADLEW] Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] ==============================================================================
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 1m 3s
[RUN_GRADLEW] 10 actionable tasks: 10 executed
[RUN_GRADLEW] Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

Build failed
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
npx exited with non-zero code: 1
    Error: build command failed.`

### Reproducible demo or steps to reproduce from a blank project

.

**Comment by mmuminovic** [comment]
> Can you try to set the `ANDROID_HOME` env variable?

I put it in env variables like this

```
{
    "cli": {
        "version": ">= 0.48.2"
    },
    "build": {
        "preview": {
            "distribution": "internal",
            "env": {
                "ANDROID_HOME": "/Users/username/Library/Android/sdk"
            }
        }
    },
    "submit": {
        "production": {}
    }
}

```

I found that installing the following in Android Studio resolved my issue
<img width="627" alt="Screenshot 2023-12-14 at 19 30 37" src="https://github.com/expo/eas-cli/assets/43971133/24c0725d-c1fa-4fb4-8ab2-a3f7386b710b">

Installing NDK was a solution I think

Were you considering writing some guide for `eas build --local` (what tools and dependencies should be installed on PC before) for both android and ios app? @szdziedzic

**Comment by reubennn** [comment]
I spent hours and hours trying to work out what the problem was thinking the issue was the EAS build configuration. I can confirm [the suggestions made](https://github.com/expo/eas-cli/issues/2144#issuecomment-1856400038) by @mmuminovic  solved the build issues. Thank you so much for making my day!!
