### ISSUE TITLE
eas init still show me the wrong project

### ISSUE THREAD

**Issue by SBRKH** [expo/eas-cli#2152]
### Summary

Hello,
I've got a RN project with 3 expo projects, each project have it's own app.json, credentials,...
I need to regenerate IOS certificate for one of those project (the 2nd) but when I try `eas credentials`, i've got :
 EAS project not configured.
✔ Existing EAS project found for @expo_pseudo/first_project (id = id_project). Configure this project? … no
EAS project ID configuration canceled for @expo_pseudo/first_project. Run 'eas init' to configure.

When i try eas init, it's always show me the first project even when i put 
```
"extra": {
      "env": "snd_project_name",
      "eas": {
        "projectId": "snd_project_id"
      }
    },
```
like the doc said
So i can't regen my ios cert.
I must have missed something, but I don't know what...

Thanks for the help

### Managed or bare?

MANAGED

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.9.0 - /usr/local/bin/node
      Yarn: 3.1.1 - /usr/local/bin/yarn
      npm: 10.1.0 - /usr/local/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6 
      react-native-web: ~0.19.9 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 5.9.1
      expo-cli: 6.3.10
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

idk what steps i can produce...

**Comment by szdziedzic** [comment]
Hi, do you have the correct `name, slug, and owner` fields value in your app config?

**Comment by SBRKH** [comment]
> Hi, do you have the correct `name`, `slug`, and `owner` fields value in your app config?

Hello, thank you for the reply !
You can see the app.json of the project i'm trying to init :
```
{
  "expo": {
    "name": "My App",
    "icon": "assets/project_name/apple/icon.png",
    "version": "3.0.3",
    "splash": {
      "image": "assets/project_name/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#FFFFFF"
    },
    "slug": "project_name",
    "extra": {
      "env": "project_name",
      "eas": {
        "projectId": "projectId"
      }
    },
    "ios": {
      "icon": "assets/project_name/apple/icon.png",
      "bundleIdentifier": "fr.my.package",
      "buildNumber": "490030003",
      "supportsTablet": true,
      "infoPlist": {
        "NSCameraUsageDescription": "aa",
        "NSPhotoLibraryUsageDescription": "aa",
        "NSPhotoLibraryAddUsageDescription": "aa"
      }
    },
    "android": {
      "icon": "assets/project_name/android/icon.png",
      "package": "fr.my.package",
      "versionCode": 490030003,
      "permissions": [
        "READ_EXTERNAL_STORAGE",
        "WRITE_EXTERNAL_STORAGE",
        "CAMERA",
        "ACCESS_MEDIA_LOCATION"
      ]
    }
  }
}```

Did i miss something ?

**Comment by szdziedzic** [comment]
Can you try to add the `owner` field to your app config? It's the name of the account to which the project is linked on EAS

**Comment by SBRKH** [comment]
@szdziedzic I try to add the `owner` field to the app.json but the result it's the same => eas init and eas credentials show me the wrong project.

**Comment by SBRKH** [comment]
I'm still blocked by this issue, can anyone help me ?

**Comment by nitai-b** [comment]
I am blocked by this issue as well. Not sure what to do. I've reached this point in my search to bring back notifications to my production android apps. I want to test with another eas project and I'm here. I can't link my local expo project to another eas project (remote).

**Comment by hugoh59** [comment]
Blocked too

**Comment by diegohmac-cco** [comment]
Same thing here!

**Comment by hssdiv** [comment]
you can also try adding `id` param into `eas init`

eas init --id=123123123 (where extra.eas.projectId=123123123)
