### ISSUE TITLE
How can we automate distribution of the download URL from an internal/preview build? 

### ISSUE THREAD

**Issue by jcohenho** [expo/eas-cli#2156]
I'd like to automatically send out a download URL of a build once it's finished. Is there a programmatic way to get the build ID that's autogenerated with each build? This would be helpful for creating the final URL which uses the build ID as the path.

**Comment by szdziedzic** [comment]
You can use `--json` and `--non-interactive` flags to achieve this.

https://github.com/expo/eas-cli?tab=readme-ov-file#eas-build

**Comment by dani-mp** [comment]
@szdziedzic just to double check, there's no way to do this automatically via Expo/EAS, right? i.e. configuring somewhere (or via the cli) that when a build is finished, the link is sent automatically via email to the stakeholders.

**Comment by szdziedzic** [comment]
@dani-mp You can use our email notifications https://expo.dev/accounts/[your-account-name]/settings/email-notifications or use webhooks for that https://docs.expo.dev/eas/webhooks/. I believe it should solve for your use case.
