### ISSUE TITLE
Custom EAS Build incorrectly evaluates path on Native Windows (WSL is fine)

### ISSUE THREAD

**Issue by OlliePugh** [expo/eas-cli#2160]
### Build/Submit details page URL

https://expo.dev/accounts/opugh/projects/rwg-client/builds/e6a39185-c5f7-4824-8ab0-a268cf3c659b

### Summary

The path uses `\` when on windows native, which escapes the characters in the path, so the pipeline can't find the build file.

### Managed or bare?

Bare

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 9.6.6 - ~\workspace\real-world-games\node_modules\.bin\npm.CMD
    IDEs:
      Android Studio: AI-222.4459.24.2221.9971841
    npmPackages:
      expo: ~49.0.13 => 49.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.9
    Expo Workflow: bare
    
    ✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly        
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK
 

### Error output

Failed to parse the custom build config file.
ENOENT: no such file or directory, open '/home/expo/workingdir/temporary-custom-build/client/.eas\build\development-build-android.yaml'

### Reproducible demo or steps to reproduce from a blank project

create-expo-app on windows, then create `.eas/build/build-name.yaml` and execute it `eas build -p android -e build-name`

**Comment by szdziedzic** [comment]
Hi 👋 ,

Yeah, it seems like the issue. I can take a look at it and try to make it better 😄.

**Comment by szdziedzic** [comment]
This should be fixed

**Comment by OlliePugh** [comment]
Awesome! Thanks for taking a look at this!
