### ISSUE TITLE
`eas submit -p ios` with app version management is not working correctly

### ISSUE THREAD

**Issue by siarheipashkevich** [expo/eas-cli#2161]
### Build/Submit details page URL

https://expo.dev/accounts/esupldevelopers/projects/esupl-kds/submissions/118fa60f-67e7-42e0-b336-73ca1c94d8f2

### Summary

App Store rejects submission when I use `"appVersionSource": "remote"` for managing versioning.

https://expo.dev/accounts/esupldevelopers/projects/esupl-kds/submissions/118fa60f-67e7-42e0-b336-73ca1c94d8f2

<img width="648" alt="image" src="https://github.com/expo/eas-cli/assets/7753600/dbf6ab83-de54-49ad-be70-60a0cd7d60ff">
<img width="657" alt="image" src="https://github.com/expo/eas-cli/assets/7753600/bc3ffc43-09b0-4c58-b217-0ee2bc79fb39">

### Managed or bare?

managed

### Environment

<img width="499" alt="image" src="https://github.com/expo/eas-cli/assets/7753600/20c5e3e8-4c6b-4969-a6f0-b482471d293a">
<img width="736" alt="image" src="https://github.com/expo/eas-cli/assets/7753600/22c37e2c-e570-4671-a53e-3d9bd798a68e">

### Error output

You've already submitted this version of the app.
Versions are identified by CFBundleShortVersionString from Info.plist (expo.version in app.json).
If you're submitting an Expo project built with EAS Build, increment the version (expo.version) in app.json and build the project again.

### Reproducible demo or steps to reproduce from a blank project

eas build -p ios --auto-submit

**Comment by szdziedzic** [comment]
Hi,

You are getting this error because if an app version [1.0.0] is already approved, you must increase the `version` number [1.0.1]. If you increase the `buildNumber` you will get the same error. With that being said, the `autoIncrement` option only bumps the `versionCode`/`buildNumber`. It is a known limitation that it does not support bumping `version` automatically.

https://docs.expo.dev/build-reference/app-versions/#remote-version-source

**Comment by siarheipashkevich** [comment]
Hi @szdziedzic, in that case it is not auto increment flow. Because we need manually increase the version number locally and commit this and only after that we should do submit ?

**Comment by szdziedzic** [comment]
I mean it's technically auto-incrementing your `versionCode`/`buildNumber` so in my opinion `autoIncrement` is a valid name, but I'm open to suggestions if you think it should be renamed. But yeah, I agree this `autoIncrement` version management process is only partially automated and it still requires some human action every time the new version is approved, that's right.

I see your standpoint and what you would like this feature to do. It is reasonable thinking and I understand you. However, it was built with this thought in mind:

```
The main goal of this feature is to avoid manual changes to the project every time you are uploading a new archive to run it on TestFlight/Play Store testing channels. When you are doing a production release, the user-facing version change should be explicit.
```
https://docs.expo.dev/build-reference/app-versions/#recommended-workflow

With that being said, we can consider implementing it in the future if this highly requested feature and when we finish building the features we currently prioritize.

Thanks for the discussion and let me know if you have any more questions!
