### ISSUE TITLE
Image Size v1.1.0 not compatible with expo-github-action

### ISSUE THREAD

**Issue by christina-kirk** [expo/eas-cli#2162]
### Summary

The latest version of image-size@1.1.0 requires a minimum node version of 18 but upgrading to node 18 breaks the expo-cli@5.6.0 which requires a node version >=12 <=16

The image-size@1.1.0 was released 9 hours ago as of 12/28/23 4:22EST

### Managed or bare?

Bare

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.1.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.0/bin/yarn
      npm: 10.2.3 - /opt/homebrew/bin/npm
      Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.0/15A240d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^41.0.0 => 41.0.1 
      react: ^16.14.0 => 16.14.0 
      react-dom: ^16.14.0 => 16.14.0 
      react-native: 0.63.5 => 0.63.5 
      react-native-web: ~0.13.12 => 0.13.18 
      react-navigation: ^3.9.2 => 3.13.0 
    npmGlobalPackages:
      eas-cli: 5.1.0
    Expo Workflow: bare

### Error output

  [2/4] Fetching packages...
  warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
  error image-size@1.1.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.20.2"
  error Found incompatible module.
  info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: The process '/usr/local/bin/yarn' failed with exit code 1

### Reproducible demo or steps to reproduce from a blank project

- Run the expo/expo-github-action@v7 or expo/expo-github-action@v8 in a project to reproduce

**Comment by szdziedzic** [comment]
Hi, 

I believe that your GitHub action run fails for you on installing dependencies, it doesn't feel like a bug in the action itself (please correct me if I'm wrong).

You are using really old Expo SDK version (41) the latest one is [49](https://blog.expo.dev/expo-sdk-49-c6d398cdf740). With SDK 46 the new [local Expo CLI](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421) was released. You can consider upgrading your SDK version to a more recent one (highly recommended).

Do you have the `expo-cli` installed as your project dependency? If so, it should be installed globally. Also the newest version of `expo-cli` is [`6.3.10`](https://www.npmjs.com/package/expo-cli) so you can try to upgrade it and make it support Node 18 by doing so.

**Comment by christina-kirk** [comment]
@szdziedzic 
Hm, maybe I'm in the wrong place I'm looking at this https://github.com/expo/expo-github-action library where you can run a Github Action to build within github and validate that builds are not broken: 
```      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
```
This step is failing and I'm not sure how my locally installed versions of expo would be impacting a github action that I don't seem to have direct control over. I filed an incident with that library as well.

**Comment by christina-kirk** [comment]
To any future readers looks like the image-size library resolved this on their own https://github.com/image-size/image-size/commit/fab15a51f60b47b4cef3a8842d3bbe97213cb2ab
