### ISSUE TITLE
.env is not being loaded on eas update

### ISSUE THREAD

**Issue by matart15** [expo/eas-cli#2174]
### Summary

I have `.env` file. it is working without problem on `expo dev`.

![Screenshot 2024-01-11 at 11 10 55](https://github.com/expo/eas-cli/assets/17027219/0baa7688-c24f-4068-bd17-86b314ccb16f)

But when i use `expo update`

![Screenshot 2024-01-07 at 15 02 03](https://github.com/expo/expo-cli/assets/17027219/55b224a0-a24f-4a10-bec9-f5ab67836a90)

### Managed or bare?

managed

### Environment

Need to install the following packages:
expo-env-info@1.0.5
Ok to proceed? (y)

expo-env-info 1.0.5 environment info:
System:
OS: macOS 14.1.2
Shell: 5.9 - /bin/zsh
Binaries:
Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
npm: 8.19.4 - ~/workplace/github/.../node_modules/.bin/npm
Managers:
CocoaPods: 1.11.3 - /usr/local/bin/pod
SDKs:
iOS SDK:
Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
IDEs:
Android Studio: 2021.3 AI-213.7172.25.2113.9123335
Xcode: 15.1/15C65 - /usr/bin/xcodebuild
Expo Workflow: managed

npx expo-env-info 5.87s user 2.57s system 62% cpu 13.478 total

### Reproducible demo or steps to reproduce from a blank project

1. create project
2. set secrets
3. create eas update
4. add some code to see process.env ( if my understanding is correct secrets should be there )
```ts
<Pressable
              onPress={() => {
                Alert.alert("", JSON.stringify(process.env));
              }}
            >
```
5. update pnpx eas-cli update --branch preview --message "update try"

**Comment by szdziedzic** [comment]
What Expo SDK version are you using?

**Comment by matart15** [comment]
package.json 

```
 "expo": "49.0.18",
```

pnpm expo -v
0.10.15

**Comment by szdziedzic** [comment]
Looking at your screenshot from https://github.com/expo/eas-cli/issues/2170, I see a warning about EAS CLI being installed as your project dependency. Can you remove it from your project dependencies and install the latest version globally?

**Comment by matart15** [comment]
ok. removed it from package.json
![image](https://github.com/expo/eas-cli/assets/17027219/78fbdac0-3210-431b-a137-4d55dad97a0d)

then tried `pnpx eas-cli update --branch preview --message "update try"`

results are same.

Even if i try `NODE_ENV=preview; pnpx eas-cli update --branch preview --message "update try"`

it shows only `{ NODE_ENV: "production" }`.

**Comment by matart15** [comment]
Just in case : 

```sh
❯ pnpx eas-cli -v
eas-cli/6.0.0 darwin-x64 node-v20.10.0
pnpx eas-cli -v  5.15s user 3.99s system 122% cpu 7.489 total
```

**Comment by brentvatne** [comment]
EAS Update does not pull in values from secrets. Secrets are *not* intended for updates! Secrets are values that will be present on an EAS Build worker temporarily to hold values like sensitive API keys to upload sourcemaps to Sentry and such things. You do not want to include these values in your update.

**Comment by matart15** [comment]
@brentvatne 

One thing I don't understand is 

If i write app that uses process.env.MY_SECRET_API_KEY to access endpoints and eas build it will work. 
Then I found small problem and runs `eas update` my app return `undefined` on process.env.MY_SECRET_API_KEY and breaks? doesn't this make `eas update` meaningless?

**Comment by quinlanj** [comment]
hey @matart15 , the problem is the way you are calling the environment variable. When `eas update` is run, we inline all your env var declarations from `.env` into the bundle. For example, if your code references `process.env.EXPO_PUBLIC_TEST`, we replace the value of it with what is referenced in your `.env` file. This is why when you print out `process.env`, you'll get an empty object. But if you reference it using JavaScript's dot notation like `process.env.EXPO_PUBLIC_TEST`, you should see be able to see it. 

Here are more details: https://docs.expo.dev/guides/environment-variables/#how-to-read-from-environment-variables

**Comment by matart15** [comment]
Woow. 
I missed this line on the docs.
> Alternative versions of the expression are not supported. For example, process.env['EXPO_PUBLIC_KEY'] or const {EXPO_PUBLIC_X} = process.env is invalid and will not be inlined.

I will try it again with dot notation

**Comment by MariuzM** [comment]
I'm testing this now and also noticed that my `EXPO_PUBLIC_API_URL=https://prod.api` that was built with eas production was replaced with my local .env that i use `EXPO_PUBLIC_API_URL=http://localhost:3000` 

I could see this as a problem when lets say i find a bug and i want to fix it fast but i forget to change `.env` file from Dev to Prod. so that means Dev URL will be pushed. 

Also another issue, even if i pushed `.env` file with `prod` url i was getting issues still tho on main screen i have it printed and it does show the prod url but issue is that its not able to connect, i can't debug the production build but maybe i need create a simple example to test.

**Comment by MariuzM** [comment]
I think i found solution
1. Create `.env.production` file 
2. Only use the PROD public env's
3. Run update like so `NODE_ENV=production eas update --branch production --message "test 1" -p ios`

**Comment by MariuzM** [comment]
Update
there is some issue with Axios.

After i added this 
<img width="469" alt="image" src="https://github.com/expo/eas-cli/assets/36937039/431bd16f-d9f8-44a4-959e-b6775b774018">

- Removed above change
- It started working, so ok i then made a build and pushed to app store, updated my phone with that all good.
- Then i made expo update and broke again. 
- Made another expo update still nothing
- Ok now i added same change (Alert) boom started working...

**Comment by redkean** [comment]
> Update: there is some issue with Axios.
> 
> <img alt="image" width="469" src="https://private-user-images.githubusercontent.com/36937039/317017322-431bd16f-d9f8-44a4-959e-b6775b774018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NzcwNjcsIm5iZiI6MTcxMjk3Njc2NywicGF0aCI6Ii8zNjkzNzAzOS8zMTcwMTczMjItNDMxYmQxNmYtZDlmOC00NGE0LTk1OWUtYjY3NzViNzc0MDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDAyNTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNmM1ZTJkMGNhNGEzNWJiNDcwZDMxZjhmZTg3NGU0M2IxZDIxZDljZTE0ZTNmZTI4MmU5NGM3OTI5YWE2MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J0ng9ZDmXcIXwRarva8MeleGjna-qBJeS_Qg83epyuY">
> * It started working, so ok i then made a build and pushed to app store, updated my phone with that all good.
> * Then i made expo update and broke again.
> * Made another expo update still nothing
> * Ok now i added same change (Alert) boom started working...
> * Removed that Alert and done Update all good still working...
> * But I'm sure if i do production build and push to test flight on the next expo update it will break i have no idea why, i feel like maybe when doing Expo Update, Axios needs to have some sort of Native component inside like this Alert? I just can't explain this sorry
> 
> My expo is configured like this <img alt="image" width="424" src="https://private-user-images.githubusercontent.com/36937039/317017976-418e0361-c594-465e-bb73-4eaab4e69c00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NzcwNjcsIm5iZiI6MTcxMjk3Njc2NywicGF0aCI6Ii8zNjkzNzAzOS8zMTcwMTc5NzYtNDE4ZTAzNjEtYzU5NC00NjVlLWJiNzMtNGVhYWI0ZTY5YzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDAyNTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMjBmNjM0N2M3NmFiYTA1YTk1Mzg0MzExNzJkNWI0N2VhZDQxYmI4MzEwNWU5ZGM0NjA5OWVlZjU4ZmZhMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uT7gagQmBsCzsdBgasix0OAJqqbhqBQ6DhquPUbhduw">
> 
> and then just couple interceptors but they don't do much

I'm experiencing this same issue, you can also replicate this in a local app dev (prebuild) and expo go.
 
In my case, we have 2 separate API url for prod and dev, if I try to run prod by adding `APP_ENV=production` at the start of dev server, the app loads contents from dev API. Then I tried adding console logs in my `axios.ts` file and it now suddenly works.

**Comment by evansendra** [comment]
The `--clear-cache` was a lifesaver.  Wasn't able to figure out why updating an `EXPO_PUBLIC_` environment variable in the relevant `.env` file wouldn't update after pushing an update, even after trying to push a small code change as well to attempt to force the change recognition.  Would it make sense to include a one liner about this in https://docs.expo.dev/eas-update/environment-variables/?

**Comment by ahmed-khlifi** [comment]
--clear-cache solved the issue, and i think it should be better for expo update to use the variables set in the production profile or in secrets instead of going with .env direclty

**Comment by Joshuapwilley** [comment]
This is a shit show. How many devs do you think have unknowingly pushed development environment configs to prod because of this? Why is this not documented CLEARLY somewhere?

And why does every single expo/eas service pull from/use environment variables differently? Seriously, what the fuck?

**Comment by jarredwitt** [comment]
It was pretty bad for us and sometimes clear cache wouldn't help so I wrote a script to handle it.

```js
const fs = require('fs');
const { spawn } = require('child_process');
const path = require('path');
const yargs = require('yargs/yargs');
const { hideBin } = require('yargs/helpers');

// Parse command-line arguments
const argv = yargs(hideBin(process.argv))
  .option('channel', {
    alias: 'c',
    type: 'string',
    describe: 'Specify the channel',
    demandOption: true,
  })
  .option('message', {
    alias: 'm',
    type: 'string',
    describe: 'Message for the update',
    default: '',
  })
  .option('clear-cache', {
    type: 'boolean',
    describe: 'Clear the cache',
    default: true,
  }).argv;

// Load the configuration file
const configFilePath = path.join(__dirname, 'eas.json');
const configData = JSON.parse(fs.readFileSync(configFilePath, 'utf8'));

// Extract environment variables for the specified channel
const channelConfig = configData.build[argv.channel] || {};
let envConfig = channelConfig?.env || {};

if (channelConfig.extends) {
  const extendsConfig = configData.build[channelConfig.extends]?.env || {};
  envConfig = { ...extendsConfig, ...envConfig };
}

Object.keys(envConfig).forEach((key) => {
  process.env[key] = envConfig[key];
});

// Construct the `eas update` command
const easCommand = `eas update --channel ${argv.channel} --json --non-interactive`;

if (argv.message) {
  easCommand += ` --message "${argv.message}"`;
}

if (argv['clear-cache']) {
  easCommand += ' --clear-cache';
}

// Execute the command
const child = spawn(easCommand, { env: process.env, shell: true, maxBuffer: 1024 * 1024 });

child.stdout.on('data', (data) => {
  console.log(data.toString());
});

child.stderr.on('data', (data) => {
  console.error(`stderr: ${data}`);
});

child.on('close', (code) => {
  console.log(`child process exited with code ${code}`);
});
```

It loads in the eas.json file from the repo, chooses the specified channel and spawns the eas update command with the relevant process variables. Not perfect by any stretch, but has saved us some heartache. Plus it's allowed us to do some cool things like provide update messages to the user when there is a new update.

**Comment by bstrackany** [comment]
FYI google brought me here ... if you're having this issue, read this: https://docs.expo.dev/eas/environment-variables/#eas-update?redirected and make sure you have your environment variables set up in the expo.dev portal. It won't pull from .env files (or didn't for me).
