### ISSUE TITLE
Failed to upload the project tarball to EAS Build

### ISSUE THREAD

**Issue by jinan5694** [expo/eas-cli#2177]
### Summary

run command below

eas build -p android --profile preview

### Managed or bare?

managed

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-231.9392.1.2311.11255304
    npmPackages:
      expo: ~49.0.15 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

### Error output

Failed to upload the project tarball to EAS Build

Reason: request to https://storage.googleapis.com/turtle-v2-projects/production/480339f3-d006-42cf-8750-d89eafae7466/eacd1eb0-75ab-47e3-9264-f327b3b94c24?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=www-production%40exponentjs.iam.gserviceaccount.com%2F20240112%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240112T123708Z&X-Goog-Expires=3601&X-Goog-SignedHeaders=host%3Bx-goog-content-length-range&X-Goog-Signature=70f317f5c7788c528825dc75007758f0697babecccb8103d307942c096ffbfa83c76cbdb7886d42597ca2c88361120895bd56fdcadbb7edb57b7024bb110a8f06820e92fd234547a8fd1443d4e1355668fcd9d61846bc13c144835aaf42b2e2aee0de5c7f87a8fd34d5233e3705c6b2d0edd6eb41d992d8dc20b7f61975e7ef372082c98afefe1229faef223502d196ec887a74f95c77f56095609b2286ee241c99a9665d0342f1f5de362fcaf43173dbe0b39bea4f83aa532e804b97573b4840320dc3fadc830d030cf9d54fddfc9f156e3e401831baedeb5e18b3d658fe2fb92a480fc6bfff7d66dfac1f8dd1589526bfd5952bcf7bc6c2e793f1f585b7e44 failed, reason: read ECONNRESET

Error: build command failed.

### Reproducible demo or steps to reproduce from a blank project

https://github.com/jinan5694/exop-ts

**Comment by szdziedzic** [comment]
Hi there,

Was it a one-off error or did it reoccur many times for you? Looking at the error message it was the connection error between your machine and the GCP servers where we upload the project tarballs. Do you mind disclosing where you are located?

**Comment by szdziedzic** [comment]
Oh okay, I see this information on your GH profile. 

I saw this error occur for users located in China before, but unfortunately, it doesn't seem like something we can control on our end because it is an error with communication with GCP and not Expo servers which causes this upload to fail 🤔. I'm wondering why connections to GCP tend to be often disrupted in China. Can you try using a VPN?

**Comment by jinan5694** [comment]
@szdziedzic thanks for response.i find method to resolve this issue today.

**Comment by jinan5694** [comment]
朋友们，我通过给终端设置代理的方式解决了这个问题。希望能帮助到你们。

**Comment by JuanRdBO** [comment]
@jinan5694 how did you resolve this? I'm running into the same issue

**Comment by jinan5694** [comment]
> @jinan5694 how did you resolve this? I'm running into the same issue

i has this issue because of my network.

i set proxy in terminal. and fix this.

**Comment by Q-inyin** [comment]
Try you soo much bro.   It saved a lot of my time

**Comment by Q-inyin** [comment]
> 朋友们，我通过给终端设置代理的方式解决了这个问题。希望能帮助到你们。

Try you soo much bro. It saved a lot of my time

**Comment by Q-inyin** [comment]
> 朋友们，我通过给终端设置代理的方式解决了这个问题。希望能帮助到你们。

谢谢大佬！！！！

**Comment by wenlittleoil** [comment]
> Oh okay, I see this information on your GH profile.
> 
> I saw this error occur for users located in China before, but unfortunately, it doesn't seem like something we can control on our end because it is an error with communication with GCP and not Expo servers which causes this upload to fail 🤔. I'm wondering why connections to GCP tend to be often disrupted in China. Can you try using a VPN?

Unfortunately, due to the Great Firewall of China, users in China have difficulty accessing external networks and must configure a network proxy on their devices.
