### ISSUE TITLE
Universal Links not working on iOS

### ISSUE THREAD

**Issue by sinan2000** [expo/eas-cli#2180]
### Build/Submit details page URL

https://expo.dev/accounts/sinan2000/projects/pocketchef-recipe-generator/builds/655bc067-68ab-4993-a62c-6345bf0a0cf8

### Summary

I cannot setup Universal Links for iOS. As the AASA file is correctly setup, I doubt if the EAS build command correctly takes the applinks I setup inside app.json for my app, as it simply does not open any type of link inside my app. I test it on TestFlight, and have iOS 17.2.1. I do NOT have access to a Macbook, so I develop only on the managed workflow and cannot eject.

### Managed or bare?

Managed

### Environment

 expo-env-info 1.0.5 environment info:
    System:
      OS: Windows 10 10.0.22631
    Binaries:
      Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.2 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ^49.0.21 => 49.0.21
      react: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
    Expo Workflow: managed
    
    ✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Some dependencies are incompatible with the installed expo version:
  @react-native-async-storage/async-storage@1.21.0 - expected version: 1.18.2
Your project may not work correctly until you install the correct versions of the packages.
Fix with: npx expo install --fix
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

### Reproducible demo or steps to reproduce from a blank project

I have setup the AASA file correctly on my website, and it is uploaded to apple's CDN: https://app-site-association.cdn-apple.com/a/v1/pocketchef.ro
Inside my app, at app.json, this is my iOS setup:
"ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.sinan2000.pocketchef",
      "buildNumber": "1.0.9",
      "associatedDomains": [
        "applinks:pocketchef.ro"
      ]
    },
Inside my App.js, I configured linking as such:
const linking = {
    prefixes: ['https://pocketchef.ro'],
    config: {
      screens: {
        screen1: {
            path: 'account/?mode=resetPassword',
            parse: {
              oobCode: (oobCode) => oobCode,
            },
        },
        screen2: {
            path: 'account/?mode=verifyEmail',
            parse: {
              oobCode: (oobCode) => oobCode,
            },
        },
      },
    },
  };
The links I would like to open have the format https://pocketchef.ro/account/?mode=...&oobCode=...

I have already tried with a couple of builds and it seems like Universal Links is not working at all... I cannot figure out the issue.

**Comment by sinan2000** [comment]
It appears like it solved by its own. Maybe the CDN from apple or their systems took time to update.

**Comment by Elue-dev** [comment]
hi my universal link works but want to ask a question,

when i use something like this: https://mysite.com, it works

but if it is prefixed by www, it dosent work
so: https://www.mysite.com, dosent work

is there any work around for this?

**Comment by sametsahin37** [comment]
> hi my universal link works but want to ask a question,
> 
> when i use something like this: https://mysite.com, it works
> 
> but if it is prefixed by www, it dosent work so: https://www.mysite.com, dosent work
> 
> is there any work around for this?

This saved my day, thanks.
