### ISSUE TITLE
EAS build should support variant node version

### ISSUE THREAD

**Issue by SirPhemmiey** [expo/eas-cli#220]
## Description

Why does EAS cloud build use exact node version `14.15.1` in its environment? At

## Expected Behavior

At least you can have something like `>= 14.15.1` and not exact 14.15.1. Because some folks might be using a different version (like me, I'm using 14.15.4 which is stable and in a monorepo) and downgrading our environment to 14.15.1 just to use eas build doesn't seem right (and will require a couple of changes on our end internally). 

## Observed Behavior

Eas build uses exact node version 14.15.1 in its environment and it fails if the app doesn't use that version also.

**Comment by wkozyra95** [comment]
We don't check node version used by your project in any way on our builders, if there is sth that verifies node version it's in your project. I just build a project created on node 10.

> At least you can have something like >= 14.15.1

I don't understand what you mean by that, we can't install a range of versions on the image and we certainly cannot install sth that does not exist (when we created the current docker image version 14.15.1 was the latest)

We plan to support a configurable build environment quite soon, but it'll mean that node would be installed in runtime and increase build time.

**Comment by wkozyra95** [comment]
https://docs.expo.io/build/eas-json/

You can now specify node and yarn versions in eas.json

**Comment by next6leo** [comment]
@wkozyra95 why is it not working?
{
  "cli": {
    "version": ">= 1.2.0"
  },
  "build": {
    "development": {
      "node": "16.17.0",
      "developmentClient": true,
      "distribution": "internal",
      "releaseChannel": "default",
      "ios": {
        "simulator": true
      }
    },
    "tester": {
      "releaseChannel": "tester",
      "android": {
        "buildType": "apk"
      }
    },
    "preview": {
      "releaseChannel": "uat"
    },
    "production": {
      "releaseChannel": "rel_0_10_0",
      "node": "16.17.0",
      "android": {
        "buildType": "apk"
      }
    }
  },
  "submit": {
    "production": { }
  }
}

**Comment by EmmanuelStocco** [comment]
Hello Everyone,

After two weeks stop in this problem and reading all articles and blog about this error, i finish find a solution. 
EAS updated your intern node from 16 to 18. For any reazon, gradlew is incompatable. So you need define in your eas settings your node version local, for eas build 

Go to eas settings and set for example:

 "production": {
      "android": {
        "node": "16.18.0",
        "buildType": "apk"
      }
    }
    
    eas build --profile production --platform android
    
    I hope it helps you,
    
    Greting from Brazil
