### ISSUE TITLE
EAS submit Invalid Apple ID was specified

### ISSUE THREAD

**Issue by RamboWasReal** [expo/eas-cli#2206]
### Build/Submit details page URL

https://expo.dev/accounts/lucietrottier/projects/cute-v3/builds/6b68e099-d3ff-4501-a1e9-7f1986756e72

### Summary

when i build all working well, but after when i want to submit i got this error Invalid Apple ID was specified. It should be a valid email address. Example: "name@example.com".

i don't know the reason why, 2 days before i had no error and all working well, i never had this error before

### Managed or bare?

manged

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.21 - ~/.nvm/versions/node/v18.19.0/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Managers:
      CocoaPods: 1.15.0 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.7 => 49.0.22
      expo-router: ^2.0.0 => 2.0.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.72.6 => 0.72.6
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 7.1.2
    Expo Workflow: managed

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

### Error output

[Error [ValidationError]: Invalid Apple ID was specified. It should be a valid email address. Example: "name@example.com".] {
  _original: { language: 'en-US', appleId: 'com.11h11media.cute-app' },
  details: [
    {
      message: 'Invalid Apple ID was specified. It should be a valid email address. Example: "name@example.com".',
      path: [Array],
      type: 'string.email',
      context: [Object]
    }
  ]
}

### Reproducible demo or steps to reproduce from a blank project

![Screenshot 2024-01-31 at 10 05 26 AM](https://github.com/expo/eas-cli/assets/42750910/6cce2faf-9e7a-4e39-ae92-679c8d632973)

eas.json

**Comment by szdziedzic** [comment]
Hi,

The `con.11h11media.cute-app` doesn't seem like a valid Apple ID value. Apple ID is the email address that you use to log in to your Apple Developer account. It seems like this is your bundle identifier. 

BTW I think that in your current submit setup you can drop the `appleId` altogether from your `eas.json` and it should still work fine.

**Comment by RamboWasReal** [comment]
thank you !! all is working now, i just removed like you said

thanks !

**Comment by RamboWasReal** [comment]
thank you !! all is working now, i just removed like you said

thanks !

**Comment by agospranzetti** [comment]
hi @szdziedzic , Im having the same issue , should I just removed the apple ID value all together from my eas file ? Thanks

**Comment by Balintataw** [comment]
I'm seeing this after updating to v7.1.3 yesterday but for Apple Team ID. Never had an issue before.
