### ISSUE TITLE
eas update not pushing updates to apps installed directly with APK

### ISSUE THREAD

**Issue by byronthe123** [expo/eas-cli#2210]
### Summary

I followed this article for migrating from `expo publish` to `eas update`. I completed all the steps without any error messages. After using the following command to publish my update `eas update --channel production`, I checked my app which was installed on an Android device directly via an APK. It is NOT receving any updates. Does `eas update` not work with apps installed via APK? If not, how am I supposed to update apps in this scenario as I can't put this app on the Google Play Store since it's an in-house corporate app which is only distributed via APKs.

### Managed or bare?

Managed

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10671973
    npmPackages:
      expo: ~50.0.5 => 50.0.5 
      metro: ^0.80.5 => 0.80.5 
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.2 => 0.73.2
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed
    
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

### Reproducible demo or steps to reproduce from a blank project

I do not have a reproducible demo.

**Comment by byronthe123** [comment]
Update, I figured out my issue. The `runtimeVersion` but be the same for the build and the update for the update work properly.

**Comment by yeakiniqra** [comment]
I am also facing the same Issue,How can I get rid of this?
PS F:\Web Development\React Native\UAPedia Update\UAPedia> eas update
√ Which branch would you like to use? » preview - current update: N/A
√ Provide an update message: ... Initial commit

Generated by create-expo-app 2.3.5.
[expo-cli] Starting Metro Bundler
[expo-cli]
[expo-cli] Error: Unable to resolve module .\node_modules\expo-router\entry.js from F:\Web Development\React Native\UAPedia Update\UAPedia/.: .\node_modules\expo-router\entry.js could not be found within the project or in these directories:
[expo-cli]   node_modules
[expo-cli] Error: Unable to resolve module .\node_modules\expo-router\entry.js from F:\Web Development\React Native\UAPedia Update\UAPedia/.: .\node_modules\expo-router\entry.js could not be found within the project or in these directories:
[expo-cli]   node_modules
[expo-cli]     at ModuleResolver.resolveDependency (F:\Web Development\React Native\UAPedia Update\UAPedia\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:138:15)
[expo-cli]     at DependencyGraph.resolveDependency (F:\Web Development\React Native\UAPedia Update\UAPedia\node_modules\metro\src\node-haste\DependencyGraph.js:231:43)
[expo-cli]     at F:\Web Development\React Native\UAPedia Update\UAPedia\node_modules\metro\src\lib\transformHelpers.js:156:21
[expo-cli]     at Server._resolveRelativePath (F:\Web Development\React Native\UAPedia Update\UAPedia\node_modules\metro\src\Server.js:1023:12)
[expo-cli]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[expo-cli]     at MetroBundlerDevServer.resolveRelativePathAsync (F:\Web Development\React Native\UAPedia Update\UAPedia\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:1204:12)
[expo-cli]     at MetroBundlerDevServer.metroLoadModuleContents (F:\Web Development\React Native\UAPedia Update\UAPedia\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:429:35)
[expo-cli]     at MetroBundlerDevServer.legacySinglePageExportBundleAsync (F:\Web Development\React Native\UAPedia Update\UAPedia\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:552:20)
[expo-cli]     at F:\Web Development\React Native\UAPedia Update\UAPedia\node_modules\@expo\cli\src\export\exportApp.ts:137:26
[expo-cli]     at async Promise.all (index 0)
✖ Export failed
F:\Web Development\React Native\UAPedia Update\UAPedia\node_modules\expo\bin\cli exited with non-zero code: 1
    Error: update command failed.
