### ISSUE TITLE
EAS Update not working on iOS

### ISSUE THREAD

**Issue by byronthe123** [expo/eas-cli#2213]
### Summary

I migrated from `expo publish` to `eas update`. On Android, this is working perfectly. However, for my iOS application, the updates are not going through. Here are the steps I followed:

1. Created a new iOS build
2. Submitted the build to App Store Connect using `eas submit`
3. Got the build reviewed and approved for internal distribution in App Store Connect
4. Using the internal distribution link, I was able to "Update" my existing iOS app via the Apple App Store and my app version reflected the latest build number that I had submitted to App Store connect.
5. I made more changes to my app and used `eas update` to push an update to Android and iOS. In my Android app (which was installed on devices using APKs, not the PlayStore), the update went through successfully. However, in my iOS app, the update did not go through. Previously, when I pushed an update using `expo publish`, it updated both iOS and Android.

Why are updates going through on Android and not on iOS? What is the correct way to update for iOS?

### Managed or bare?

Managed

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
      npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-223.8836.35.2231.10671973
    npmPackages:
      expo: ~50.0.5 => 50.0.5 
      metro: ^0.80.5 => 0.80.5 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.2 => 0.73.2 
      react-native-web: ~0.19.6 => 0.19.10 
    Expo Workflow: managed
    
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Error: Problem validating fields in D:\Programming\eos-native\app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: updates - should NOT have additional property 'channel'.

### Reproducible demo or steps to reproduce from a blank project

I do not have a reproducible demo.

**Comment by shiftreg** [comment]
@byronthe123 I have the same issues did you find a solution for this problem?
Regards

**Comment by byronthe123** [comment]
@shiftreg, the fix for me was to run `eas channel:edit`  which prompts you to select one of your channels and then ask you following question: `Which branch would you like to [channel] to point at?`. Make sure you select the branch which you would like to get updates from (it could be either `production` or `master`). My issue was that the `master` channel which is supposed to push updates to iOS was defaulted to getting updates from the `master` branch, but the branch I was currently working in was production (I'm not even sure how exactly this happened, but it probably happened during the setup for `eas update`  which caused a new `production` channel and `branch` to be created). Once I pointed the master channel to the production branch and then ran `eas update --channel production`, the updates got pushed to iOS as well.

![image](https://github.com/expo/eas-cli/assets/22138809/adaf7fb4-57ea-4e0e-ae1c-ff6c30367483)

**Comment by giniedigital** [comment]
Still not working

**Comment by speedtreammanga** [comment]
Did not work for me either

**Comment by nadav-mobileBrain** [comment]
worked for me , thx!
