### ISSUE TITLE
Error on build eas project

### ISSUE THREAD

**Issue by korizyx** [expo/eas-cli#2226]
### Summary

I'm trying to run the `eas build` command but unexpectedly, even logging into the apple developer account, I get a cookie error in the terminal...

I looked at several posts on github but nothing helped me... I've tried uninstalling eas and installing it, deleting cookies, running eas install --fix, deleting all modules, changing the password, using vpn but NONE of it has helped.

### Managed or bare?

Bare 

### Environment

EAS CLI 7.1.3 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.42.0. - /c/Program Files/Git/cmd/git
    npmPackages:
      expo: ~50.0.6 => 50.0.6
      expo-updates: ~0.24.10 => 0.24.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    Project workflow: managed

### Error output

√ How do you want to validate your account? ... device / sms
√ Please enter the 6 digit code ... 762385
√ Valid code
√ Logged in and verified
Authentication with Apple Developer Portal failed!
Cookie not in this host's domain. Cookie:developer-mdn.apple.com Request:developer.apple.com
    Error: device:create command failed.

### Reproducible demo or steps to reproduce from a blank project

eas build -p ios --auto-submit

**Comment by Niravpatel129** [comment]
Duplicate https://github.com/expo/eas-cli/issues/2224#issue-2128657151
