### ISSUE TITLE
● Validation Warning

### ISSUE THREAD

**Issue by sbhakat1** [expo/eas-cli#2228]
● Validation Warning:

  Unknown option "serializer.isThirdPartyModule" with value (module) =>
      /(?:^|[/\\])node_modules[/\\]/.test(module.path) was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "symbolicator.customizeStack" with value async (stack, _) => stack was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "watcher" with value {"additionalExts": ["cjs", "mjs"], "healthCheck": {"enabled": false, "filePrefix": ".metro-health-check", "interval": 30000, "timeout": 5000}, "unstable_workerThreads": false, "watchman": {"deferStates": ["hg.update"]}} was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "unstable_perfLoggerFactory" with value () => {
  class Logger {
    start() {}
    end() {}
    annotate() {}
    point() {}
    subSpan() {
      return this;
    }
  }
  return new Logger();
} was found.
  This is probably a typing mistake. Fixing it will remove this message.

Can anyone help me to figure out this error to start metro for React Native CLI

_Originally posted by @sbhakat1 in https://github.com/expo/expo/issues/23213#issuecomment-1939731243_

**Comment by szdziedzic** [comment]
Hi there, repro would be useful for us to help us understand what's happening better. Also, please stick to the issue template we have set up in this repo.

**Comment by szdziedzic** [comment]
If you want to ask questions in a more loosely structured form, you can do so at https://chat.expo.dev/
