### ISSUE TITLE
Build request failed due to "Unexpected Server Error" (EAS BUILD DOWN)

### ISSUE THREAD

**Issue by SleeplessByte** [expo/eas-cli#2247]
### Build/Submit details page URL

https://expo.dev/accounts/introcloud/projects/onderwijsdagen

### Summary

After the build is uploaded to EAS, the CLI errors out:

```
Compressing project files and uploading to EAS Build. Learn more: https://expo.fyi/eas-build-archive
✔ Uploaded to EAS 1s

Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
Request ID: 9c106a34-bce1-4e94-a87e-eb6cdc09c944
Error message: Unexpected server error (Expo error ID: 9c106a34-bce1-4e94-a87e-eb6cdc09c944).
    Error: build command failed.
```

No major changes have been made since the previous build, other than the binary assets (splash screen, icon, etc.) changing.

The error message says to report it if it persists. https://status.expo.dev/ does not report any ongoing issues. https://expo.dev/eas-build-status does show 0 current builds...

### Managed or bare?

Nabaged

### Environment

```
  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.11.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
      Yarn: 3.5.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\yarn.CMD
      npm: 10.2.4 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    npmPackages:
      @expo/webpack-config: ^18.1.2 => 18.1.2
      expo: ^48.0.20 => 48.0.20
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.71.8 => 0.71.8
      react-native-web: ~0.18.12 => 0.18.12
    Expo Workflow: managed
```
--------------------
```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✖ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Expected package @expo/config-plugins@~6.0.0
Found invalid:
  @expo/config-plugins@7.0.0
  @expo/config-plugins@7.0.0
  @expo/config-plugins@7.0.0
  @expo/config-plugins@7.0.0
  @expo/config-plugins@7.0.0
  @expo/config-plugins@7.0.0
  (for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions0.

One or more checks failed, indicating possible issues with the project.
```

### Error output

```
Starting iOS build
[
  {
    "extensions": {
      "requestId": "eb995003-7050-46cb-81f4-476148370d84",
      "code": "INTERNAL_SERVER_ERROR",
      "errorCode": "EAS_BUILD_DOWN",
      "metadata": {},
      "isTransient": false
    },
    "message": "Unexpected server error (Expo error ID: eb995003-7050-46cb-81f4-476148370d84).",
    "locations": [
      {
        "line": 3,
        "column": 5
      }
    ],
    "path": [
      "build",
      "createIosBuild"
    ]
  }
]
Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
Request ID: eb995003-7050-46cb-81f4-476148370d84
Error message: Unexpected server error (Expo error ID: eb995003-7050-46cb-81f4-476148370d84).
Error: Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
Request ID: eb995003-7050-46cb-81f4-476148370d84
Error message: Unexpected server error (Expo error ID: eb995003-7050-46cb-81f4-476148370d84).
    at handleBuildRequestError (C:\Users\Derk-Jan\scoop\persist\nvm\nodejs\v20.11.0\node_modules\eas-cli\build\build\build.js:147:15)
    at C:\Users\Derk-Jan\scoop\persist\nvm\nodejs\v20.11.0\node_modules\eas-cli\build\build\build.js:100:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startBuildAsync (C:\Users\Derk-Jan\scoop\persist\nvm\nodejs\v20.11.0\node_modules\eas-cli\build\build\runBuildAndSubmit.js:249:12)
    at async prepareAndStartBuildAsync (C:\Users\Derk-Jan\scoop\persist\nvm\nodejs\v20.11.0\node_modules\eas-cli\build\build\runBuildAndSubmit.js:235:19)
    at async runBuildAndSubmitAsync (C:\Users\Derk-Jan\scoop\persist\nvm\nodejs\v20.11.0\node_modules\eas-cli\build\build\runBuildAndSubmit.js:87:49)
    at async Build.runAsync (C:\Users\Derk-Jan\scoop\persist\nvm\nodejs\v20.11.0\node_modules\eas-cli\build\commands\build\index.js:41:9)
    at async Build._run (C:\Users\Derk-Jan\scoop\persist\nvm\nodejs\v20.11.0\node_modules\eas-cli\node_modules\@oclif\core\lib\command.js:80:22)
    at async Config.runCommand (C:\Users\Derk-Jan\scoop\persist\nvm\nodejs\v20.11.0\node_modules\eas-cli\node_modules\@oclif\core\lib\config\config.js:301:25)     
    Error: build command failed.
```

### Reproducible demo or steps to reproduce from a blank project

Cannot reproduce from a blank project

**Comment by SleeplessByte** [comment]
https://expo.dev/eas-build-status now shows that there are builds queued, but I am still receiving the same error messages.

**Comment by SleeplessByte** [comment]
I was able to make the builds work again by completely resetting the .env variables and stored secrets. My guess is that there was a corrupt or invalid value in either, and that eas-cli / graphql doesn't escape it properly (or rejects it properly).

**Comment by LeslieOA** [comment]
> I was able to make the builds work again by _creating a new project_ (so replacing the slug and eas project id). This instantly worked. No other changes were made.
> 
> Something must be wrong with the project on the expo side.
> 
> It seems to be related to _empty_ `eas secrets`.

I seem to be having the same issue. 
New blank project works great (`expo prebuild`), but the second I add secrets (usually via `eas secret:push` from an `.env`; this issue arises). 

[Here's a thread on Expo's Discord](https://discord.com/channels/695411232856997968/809586753719238656/1211241623476895774) I started.

**Comment by szdziedzic** [comment]
Hi,

I think that this PR should solve the issue that you encounter https://github.com/expo/eas-build/pull/347.

Thanks for reporting it!

**Comment by szdziedzic** [comment]
Hi, can you verify if the builds started to work for you?

**Comment by SleeplessByte** [comment]
@szdziedzic Can confirm they started building again. New error is:

```
For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.15.0
[!] Unable to find a specification for `EASClient` depended upon by `EXUpdates`
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
pod install exited with non-zero code: 1
```

Seems to be unrelated to this report, but also something that I shouldn't run into when nothing has changed native-wise.

**Comment by szdziedzic** [comment]
I'm not 100% sure about it, but I think that there were some issues with getting RN to work with CocoaPods 1.15. I believe that you are using CocoaPods 1.15, right?

Maybe downgrading can help?

**Comment by SleeplessByte** [comment]
@szdziedzic Nah, this is a managed project.

I managed to fix this error by deleting yarn.lock and reinstalling :/

**Comment by mirague** [comment]
Seeing this behaviour since a few days, any known regressions?

**Comment by Jheysson** [comment]
My project is in WSL, when I run the command in the command windows of VSCode, it didn't work, but it did in the actual WSL command window

**Comment by andrconstruction** [comment]
Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
Request ID: 68a60b2a-6b95-4aa0-9e52-512282023d6d
Error message: Unexpected server error (Expo error ID: 68a60b2a-6b95-4aa0-9e52-512282023d6d).
    Error: build command failed.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
