### ISSUE TITLE
After Apple app account holder transfer, app is unbuildable with eas.

### ISSUE THREAD

**Issue by nmateo** [expo/eas-cli#2268]
### Build/Submit details page URL

https://expo.dev/accounts/nmateo/projects/mob-waeve-interim/builds/53e5f51f-d7aa-4b0a-942d-26a3bd96c76f

### Summary

We use EAS to build iOS app, for months it has been working fine without issue but recently we were asked to transfer the app to a new apple account.
We transfered the app successfully, changed eas apple account to the new one, regenerated certificate / keys / profiles on the new account but every time we build we got an error that we haven't been able to correct.

### Managed or bare?

Managed iOS/ Bare Android

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Linux 6.4 Ultramarine Linux
      Shell: 5.2.15 - /bin/bash
    Binaries:
      Node: 18.17.1 - /usr/bin/node
      Yarn: 1.22.19 - /usr/bin/yarn
      npm: 8.19.2 - /usr/local/bin/npm
    npmPackages:
      @expo/metro-config: ^0.10.7 => 0.10.7 
      @expo/webpack-config: ^0.17.4 => 0.17.4 
      expo: ^49.0.8 => 49.0.8 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.4 => 0.72.4 
      react-native-web: ~0.19.6 => 0.19.7 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 7.2.0
    Expo Workflow: bare

### Error output

 Provisioning profile "*[expo] fr.waeve.mob AppStore 2024-03-06T11:31:06.312Z" doesn't match the entitlements file's value for the com.apple.developer.ubiquity-kvstore-identifier entitlement. Profile qualification is using entitlement definitions that may be out of date.

### Reproducible demo or steps to reproduce from a blank project

Create an expo App,  transfer apple app account holder to a new one, and build iOS app for production with eas.

**Comment by szdziedzic** [comment]
Hi, can you try to remove the contents of `~/app-store`?

**Comment by ololoepepe** [comment]
We're having the same issue after app transfer. The `~/.app-store` folder does not contain anything about entitlements, it looks like it's purpose is storing user auth data. Anyway, removing it does not have any effect, the issue persists.

**Comment by KubilayKartega** [comment]
any progress on this ?

**Comment by nmateo** [comment]
I fixed it.
If i remember correctly the issue, it was linked to the iCloud, because we let user upload photo/images from their phone, i just removed the "iCloud" part of it, which was probably still linked somehow to the old apple account and it worked.
