### ISSUE TITLE
EAS Build iOS - Incorrect Version Number

### ISSUE THREAD

**Issue by ilgiapa** [expo/eas-cli#2270]
### Summary

Incorrect Version Number between Info.plist and App.config.

Eas Web - Correct Version (App.Config) 
<img width="1220" alt="Screenshot 2024-03-08 alle 08 47 03" src="https://github.com/expo/eas-cli/assets/88229350/4b76fdc7-a624-486e-9e66-a07ef503b571">

Info Plist - Downloaded and ExtractedIPA Files - Wrong Version

<img width="509" alt="Screenshot 2024-03-08 alle 08 49 51" src="https://github.com/expo/eas-cli/assets/88229350/2db3275d-d77b-4dfc-95fe-e5b8f97a818a">
<img width="509" alt="Screenshot 2024-03-08 alle 08 49 58" src="https://github.com/expo/eas-cli/assets/88229350/5877b4b6-08e3-4284-9674-34cf6d935d2d">

Upload IPA on AppCenter 

<img width="650" alt="Screenshot 2024-03-08 alle 08 48 52" src="https://github.com/expo/eas-cli/assets/88229350/8336f985-000b-48c7-afc0-fb69207990f1">

### Managed or bare?

Managed

### Environment

```

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2023.09.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.13.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.6 => 50.0.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    npmGlobalPackages:
      eas-cli: 7.3.0
    Expo Workflow: managed
```

Detailed check results:

```
The following packages should be updated for best compatibility with the installed expo version:
  expo@50.0.7 - expected version: ~50.0.11
  expo-camera@14.0.5 - expected version: ~14.0.6
  expo-file-system@16.0.6 - expected version: ~16.0.8
  expo-dev-client@3.3.8 - expected version: ~3.3.9
Your project may not work correctly until you install the correct versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.
```

### Reproducible demo or steps to reproduce from a blank project

Start Build with EAS Build --platform ios.
Check the Version in Info Plist
Version is always **1.0(1)**

**Comment by szdziedzic** [comment]
I suspect it might be caused by one of your config plugins 🤔 

You can run prebuild locally `npx expo prebuild -p ios` and inspect the `Info.plist`

Then you can remove all config plugins and do the same and see if the version looks good. If it's all good you can add them sequentially and check which one is causing it.

**Comment by ilgiapa** [comment]
Hi @szdziedzic 

I did the prebuild, the Info.plist inside **iOS folder** has the correct version, but when a run the **eas build** and download the IPA, Info.plist has ever 1.0.

I tried to run **eas build** with and without **iOS Folder**, but with the same result, the IPA on EAS with Version 1.0.

**Comment by ilgiapa** [comment]
@szdziedzic 

just to be more precise, Attached is the Info.plist of the PRE BUILD.
Version is 4.0.1, but the Info.plist inside downloaded IPA after **eas build** contains 1.0.

![image](https://github.com/expo/eas-cli/assets/88229350/eda17eaa-cf9a-46ed-b9a4-d27127da8cf3)

**Comment by szdziedzic** [comment]
Can you send me a URL of your build?

**Comment by ilgiapa** [comment]
@szdziedzic no, it's a Managed Workflow.
The only difference from my other RN Managed Workflow Apps it's that in this Project [Expo Native Module](https://docs.expo.dev/modules/native-module-tutorial/).

The Apps works great, Native Module works great, everything works, the weird thing is that after downloading the IPA from Expo, inside the PLIST file the version is 1.0 instead of the version of app.config.js.

So, before distribute the app via App Center, I need to unpack the IPA, change the PLIST Version and resign the IPA with a SH Script.

The only difference is Native Module, but I don't know if that's the problem.

Thanks

**Comment by sddanila** [comment]
I have created several builds since this was posted, but this is the first time I ran into this issue. 

I have a couple of questions for @ilgiapa:
1. What did you use to unpack the IPA and resign it?
2. Is this issue a one-off or is it persisting for you?
