### ISSUE TITLE
[EAS] ** ARCHIVE FAILED ** Exit status: 65

### ISSUE THREAD

**Issue by AleshkovDenis** [expo/eas-cli#2275]
### Build/Submit details page URL

https://expo.dev/accounts/denisaleshkov/projects/minimeet/builds/96298c2a-41de-46e5-a7c0-a6bc3c3fd457

### Summary

Hi! I'm trying to build ios and getting that without any useful information to resolve build

### Managed or bare?

Managed

### Environment

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

### Error output

› Executing App » [CP-User] [RNFB] Core Configuration

      A firebase.json file was not found, whilst this file is optional it is recommended to include it to configure firebase services in React Native Firebase.

› Signing   App » App.app
› Creating  App » App.app

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » App/App » Build Phases » '[CP-User] [RNFB] Core Configuration'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » Pods/abseil » Build Phases » 'Create Symlinks to Header Folders'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script

    Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any o

▸ ** ARCHIVE FAILED **

** ARCHIVE FAILED **

Exit status: 65

​

+---------------------------------------+

|           Build environment           |

+-------------+-------------------------+

| xcode_path  | /Applications/Xcode.app |

| gym_version | 2.219.0                 |

| sdk         | iPhoneOS17.2.sdk        |

+-------------+-------------------------+

### Reproducible demo or steps to reproduce from a blank project

eas build -p ios  --clear-cache

**Comment by AleshkovDenis** [comment]
fixed

**Comment by rgomezp** [comment]
> fixed

how did you fix this?
