### ISSUE TITLE
Internal Server Error: 'd', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, 

### ISSUE THREAD

**Issue by Aris-ngoy** [expo/eas-cli#2305]
### Summary

eas-cli/7.6.2 darwin-x64 node-v18.19.1

Internal Server Error: 'd', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)

Internal Server Error: 'd', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 2)

Internal Server Error: 'd', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 1)

✖ Failed to sync capability identifiers app.abela
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    Error: build command failed.

### Managed or bare?

Managed

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
      npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
      Watchman: 2024.01.22.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.13 => 50.0.13 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.5 => 0.73.5 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: bare

### Error output

✔ Synced capabilities: No updates

Internal Server Error: 'd', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)

Internal Server Error: 'd', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 2)

Internal Server Error: 'd', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 1)

✖ Failed to sync capability identifiers app.abela
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    Error: build command failed.

### Reproducible demo or steps to reproduce from a blank project

eas build -p ios production

**Comment by heyjamesknight** [comment]
Same issue.

**Comment by deho0701** [comment]
Same issue.

**Comment by lumamontes** [comment]
I was having the same issue but updating eas-cli and then building again worked for me:

`npm install -g eas-cli`

**Comment by ThangNV1205** [comment]
I also encountered a similar error even when using the latest version of eas-cli globally. I removed it globally and installed it directly into the project, and the build went smoothly.

**Comment by impe93** [comment]
Same error here, I tried what @lumamontes said but I still get the error. One thing to notice is that when I'm bumping up the node version from 16 to 18.20.2, I get the connection error, but if I downgrade to version 16 again, everything works like a charm. I don't see how those 2 things are connected but that's what i've noticed. Other than that I HAVE TO switch to node version 18 because the latest plugin "expo-privacy-manifest-polyfill-plugin" to fix stuff on iOS env privacy need a function that seems to be only present on node 18. I'm a bit scared about this because I've to deploy an update for Monday lol

**Comment by bportman** [comment]
Event though I already had eas-cli installed globally and things were working fine for a while, running `npm install -g eas-cli` fixed this for me when the error started popping up.

**Comment by JamesHemery** [comment]
Same error on latest version, I didn't have it two hours ago.

**Comment by Nikita-Shuminskiy** [comment]
use npx (npx eas build --profile) instead of eas(eas build --profile) it worked

**Comment by Heverson** [comment]
> I was having the same issue but updating eas-cli and then building again worked for me:
> 
> `npm install -g eas-cli`

Worked for me, thanks!

**Comment by jottenlips** [comment]
same issue, reinstalling did not fix

```
 eas --version
eas-cli/9.2.0 darwin-arm64 node-v20.14.0
```

**Comment by rcarter** [comment]
Receiving this after updating eas-cli to v10.0.0 today. Reverted to v9.2.0 and all worked fine.

**Comment by steviec** [comment]
Getting this same issue, none of the above solutions fixed it for me :(. I'm getting it only when attempting an `eas build` with a particular profile; all the other ones work fine. There's nothing different, AFAICT, about this one.

**Comment by nitishanand99** [comment]
idk how but I did these steps and it worked for me,
- downgrade to the last but one version of eas-cli `sudo npm install -g eas-cli@10.0.2`
- `sudo npm i`
- upgraded to the latest again `sudo npm i -g eas-cli`
- then used sudo for eas build `sudo eas build -p ios -e development`
the last step probably did the trick.

**Comment by NandoGoulartt** [comment]
> npm install -g eas-cli

Funcionou para mim

**Comment by opmat** [comment]
I experienced the same issue after I upgraded to eas-cli@10.1.1 today. I had to downgrade to version 10.0.0 before the build was successful.

The exact error I got was 

```
Internal Server Error: 'd', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)


Internal Server Error: 'd', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 2)


Internal Server Error: 'd', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 1)

✖ Failed to sync capability identifiers ng.fob.mobile
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    Error: build command failed.
```
My environment info is below

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
      Yarn: 1.22.22 - ~/.yarn/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v18.20.3/bin/npm
    Managers:
      CocoaPods: 1.11.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.1 
      expo: ^50.0.19 => 50.0.19 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.1.1
    Expo Workflow: managed
```

**Comment by MariuzM** [comment]
One second it was building locally fine and next started this happening...

**Comment by szdziedzic** [comment]
Hi, all!

It seems possible that Apple is doing some maintenance on their Developer Portal again 🤔 

At what point of running the `eas build` command did it fail for you? 

I believe that it is possible to know the exact request that failed if you use the `EXPO_APP_STORE_DEBUG=1 EXPO_DEBUG=1` flags when running the `eas build` command. It would be helpful information for me because I'm having a hard time replicating the issue at the moment on my machine.

A few months ago in version [`7.6.0`](https://github.com/expo/eas-cli/blob/main/CHANGELOG.md#760---2024-03-18) we added a logic to switch between the `developer.apple.com` and `developer-mdn.apple.com` domains when one of them is under the maintenance, but this error seems to not be caught by this logic. I will try to make it better by switching the domain on every internal server error we see because I believe it seems to work.

**Comment by szdziedzic** [comment]
I just released the new `10.2.0` EAS CLI version that will try to resolve the issue by switching between the `developer.apple.com` and `developer-mdn.apple.com` domains on every internal server error. 

Please, let me know if it helps in your case.

**Comment by gchen1196** [comment]
PATCH https://developer.apple.com/services-account/v1/bundleIds/
Error: Request failed with status code 501 (PATCH https://developer.apple.com/services-account/v1/bundleIds/)

Internal Server Error: 'd', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)

PATCH https://developer-mdn.apple.com/services-account/v1/bundleIds/
Error: Request failed with status code 503 (PATCH https://developer-mdn.apple.com/services-account/v1/bundleIds/)
-- App Store Connect Error JSON --
{
  "errors": [
    {
      "id": "610b951e-a7cb-925ebda53f72",
      "status": "503",
      "code": "SERVICE_NOTACTIVE",
      "title": "This request can not be processed right now",
      "resultCode": 10405,
      "detail": "Service not available because of maintenance activities, please try again after some time."
    }
  ]
}
-- End ASC Error JSON --

**Comment by tmw102** [comment]
I had an agreement outstanding in App Store Connect. Once I had signed it, this error went away.

**Comment by rgomezp** [comment]
I had removed my app from review so it was marked as "developer rejected". Once I removed the old build from the release, it started working

**Comment by Seanmclem** [comment]
I was already using npx so no global install issue. I logged into the _app store connect_ website to make sure my account/app was in good standing. It was. So I tried `npx eas build` again, and it just worked. So try that and try again before spending too much time searching.

**Comment by LKL2017** [comment]
any updates here?  I'm using `eas-cli/12.4.1` and `node-v20.13.1`, meet the same issue

**Comment by saurabhbhatia** [comment]
Same problem, `eas-cli@lates` and `node v22.5.1`

**Comment by noahkurz** [comment]
Same issue here as @saurabhbhatia

**Comment by mcr5fh** [comment]
Seeing 500s as well, and the global install did not help, nor did a downgrade, even to v12.5.0. My app store connect looks to be in good standing as well. Anyone have any luck here?

Example command: 

```
EXPO_APP_STORE_DEBUG=1 EXPO_DEBUG=1 EAS_PWD=$PWD EAS_LOCAL_BUILD_SKIP_CLEANUP=1 npx eas build --profile production --platform ios --local
```

And this is the stack trace

```
⠇ Logging in...Error: Request failed with status code 503 (POST https://idmsa.apple.com/appleauth/auth/signin)
✖ Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
d [Error]: Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    at t.getAppleResponseError (/path/to/project/node_modules/@expo/apple-utils/build/index.js:1:828021)
    at block (/path/to/project/node_modules/@expo/apple-utils/build/index.js:1:834431)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async O (/path/to/project/node_modules/@expo/apple-utils/build/index.js:1:834956)
    at async T (/path/to/project/node_modules/@expo/apple-utils/build/index.js:1:833825)
    at async t.requestAsync (/path/to/project/node_modules/@expo/apple-utils/build/index.js:1:836214)
    at async /path/to/project/node_modules/@expo/apple-utils/build/index.js:1:704687
    at async w (/path/to/project/node_modules/@expo/apple-utils/build/index.js:1:703817)
    at async Object.S [as loginWithUserCredentialsAsync] (/path/to/project/node_modules/@expo/apple-utils/build/index.js:1:703396)
    at async loginWithUserCredentialsAsync (/path/to/project/node_modules/eas-cli/build/credentials/ios/appstore/authenticate.js:84:24) {
  response: {
    status: 503,
    statusText: 'Service Temporarily Unavailable',
    headers: {
      server: 'Apple',
      date: 'Sat, 19 Oct 2024 00:57:55 GMT',
      'content-type': 'text/html',
      'content-length': '190',
      connection: 'keep-alive'
    },
    config: {
      url: 'https://idmsa.apple.com/appleauth/auth/signin',
      method: 'post',
      data: '{"accountName":"REDACTED","password":"REDACTED","rememberMe":true}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      withCredentials: true,
      adapter: [Function (anonymous)],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      jar: [M],
      maxRedirects: 0,
      baseURL: 'https://idmsa.apple.com/appleauth',
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 116,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [TLSSocket],
      _header: 'POST /appleauth/auth/signin HTTP/1.1\r\n' +
        'Accept: application/json, text/javascript\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: Xcode\r\n' +
        'X-Xcode-Version: 7.0 (7A120f)\r\n' +
        'X-Requested-With: XMLHttpRequest\r\n' +
        'X-Apple-Widget-Key: REDACTED\r\n' +
        'X-APPLE-HC: 1:12:20241019005755:REDACTED::16739\r\n' +
        'Cookie: myacinfo=REDACTED' +
        'Content-Length: 116\r\n' +
        'Host: idmsa.apple.com\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/appleauth/auth/signin',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: true,
      host: 'idmsa.apple.com',
      protocol: 'https:',
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: '<html>\r\n' +
      '<head><title>503 Service Temporarily Unavailable</title></head>\r\n' +
      '<body>\r\n' +
      '<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n' +
      '<hr><center>Apple</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n'
  }
}
```

**Comment by superunrelated** [comment]
Same here. No mention about an Apple outage here though: https://developer.apple.com/system-status/

**Comment by SirFroweey** [comment]
Same issue

**Comment by K-E-L** [comment]
Same, tried downgrading eas-cli to 12.5.1, tried upgrading to Node 22, running out of ideas

**Comment by mcr5fh** [comment]
FYI, I just added `--non-interactive` and was able to successfully build and upload to ASC

Full command that worked: `EXPO_APP_STORE_DEBUG=1 EXPO_DEBUG=1 EAS_PWD=$PWD EAS_LOCAL_BUILD_SKIP_CLEANUP=1 npx eas build --profile production --non-interactive --platform ios --local`

Saw the idea here: https://github.com/expo/eas-cli/issues/2497#issuecomment-2293756027

**Comment by JosDaw** [comment]
For non-Mac users facing this issue, this worked: `eas build --profile production --non-interactive --platform ios`. 

@mcr5fh Thanks for the help!!

**Comment by lperotti399** [comment]
I just had this same issue and used eas build --profile production --non-interactive --platform ios.   Thank you @mcr5fh you are a life saver!

**Comment by saurabhbhatia** [comment]
I got the build working with the `--non-interactive` switch too, but still fails in the `eas submit` as it requires us to select a was build. Any ideas there ?

**Comment by lperotti399** [comment]
I have the same issue as @saurabhbhatia

**Comment by lperotti399** [comment]
seems like others are facing the same issue in this thread https://forums.developer.apple.com/forums/thread/749354

**Comment by K-E-L** [comment]
I downloaded the build from the Expo site, then uploaded it through the Transporter app on the Mac App Store, and it worked! Now I am able to see it in TestFlight.

**Comment by lperotti399** [comment]
I was able to get the eas build and eas submit to work using eas build --non-interactive   --platform ios  --auto-submit

Prior to running this I had to set up my production profile with the proper submit information in my eas.json file.  That documentation is here https://docs.expo.dev/submit/eas-json/

**Comment by ESarcomere** [comment]
I am using a windows laptop. I get this error when I run this : npx eas build --profile production --non-interactive --platform ios
Distribution Certificate is not validated for non-interactive builds.
Failed to set up credentials.
Credentials are not set up. Run this command again in interactive mode.

And when I try:  npx eas build --profile production --platform ios
I get :
Error: Request failed with status code 503 (POST https://idmsa.apple.com/appleauth/auth/signin)
× Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
...
 status: 503,
    statusText: 'Service Temporarily Unavailable',
    
   Has anyone fixed this? Can I even build ios apps from windows laptops?

**Comment by sudhakarAndroid** [comment]
I'm also getting same error.

× Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    Error: build command failed.

**Comment by alessiapacca** [comment]
@lperotti399 great solution, worked for me!!

**Comment by nars-bramble** [comment]
@lperotti399 
getting the below error when using the "--non-interactive" command

Failed to set up credentials.
Credentials are not set up. Run this command again in interactive mode.
    Error: build command failed.

**Comment by saurabhbhatia** [comment]
Looks like this is now acknowledge as service degradation https://status.expo.dev

**Comment by devsphere-apps** [comment]
**What are the methods not worked for me**

-  npm install -g eas-cli
-  npm uninstall -g eas-cli expo-cli
-  npm install -g eas-cli
-  npm install -g eas-cli@latest
-   eas logout
-   eas login
-   npm cache clean
-   npm cache clean --force
-   removed my app from review so it was marked as "developer rejected". 

**Worked for me**

- eas build --platform ios --non-interactive  // --non-interactive worked
- eas submit --platform ios

**Comment by alessiapacca** [comment]
@nars-bramble did you setup your eas.json? should be: 
"submit": {
    "production": {
      "ios": {
        "appleId": "yourappleid",
        "ascAppId": "yourappid",
        "appleTeamId": "yourteamid"
      }
    }
  }

**Comment by AyoCodess** [comment]
> FYI, I just added `--non-interactive` and was able to successfully build and upload to ASC
> 
> Full command that worked: `EXPO_APP_STORE_DEBUG=1 EXPO_DEBUG=1 EAS_PWD=$PWD EAS_LOCAL_BUILD_SKIP_CLEANUP=1 npx eas build --profile production --non-interactive --platform ios --local`
> 
> Saw the idea here: [#2497 (comment)](https://github.com/expo/eas-cli/issues/2497#issuecomment-2293756027)

this worked, but i don't like it.

**Comment by nars-bramble** [comment]
@alessiapacca Yes, updated the eas file before running the command and got the following error.

Failed to set up credentials.
Credentials are not set up. Run this command again in interactive mode.
Error: build command failed.

**Comment by AbdessamadAe** [comment]
Running eas build in debug mode throws back the error with the following response.:
```
response: {
    status: 503,
    statusText: 'Service Temporarily Unavailable',
    headers: {
      server: 'Apple',
      date: 'Sat, 19 Oct 2024 18:28:31 GMT',
      'content-type': 'text/html',
      'content-length': '190',
      connection: 'keep-alive'
    },
```

**Comment by AbdessamadAe** [comment]
Issue was fixed here: https://github.com/expo/eas-cli/issues/2639
Just upgrade to latest eas-cli

**Comment by nars-bramble** [comment]
Issue got resolved once I updated the cli to new version. Thanks guys!

**Comment by sam-abdul** [comment]
Try npm install -g eas-cli@latest if npm install -g eas-cli isnt working

**Comment by pH-7** [comment]
Confirming that updating eas to the latest version would do it.

**Comment by LucasParra** [comment]
Confirming that installing the last version of eas-cli fixes the problem, I use node18 just for reference

**Comment by Thxmxs** [comment]
npm install -g eas-cli worked for me

im using:
node: 20.14.0
"expo": "~51.0.31"

**Comment by navigiljshuusko** [comment]
npm install -g eas-cli worked for me too

Thank you.

**Comment by saurabhbhatia** [comment]
Forgot to confirm, this worked perfectly. Thank you so much for such quick turnaround.

**Comment by bx-hamza** [comment]
For the people for whom upgrading eas-cli didn't solve the issue, running 'sudo' with your build will allow the credentials update to occur, as per [nitishanand99](https://github.com/nitishanand99) instructions.

> idk how but I did these steps and it worked for me,
> 
> * downgrade to the last but one version of eas-cli `sudo npm install -g eas-cli@10.0.2`
> * `sudo npm i`
> * upgraded to the latest again `sudo npm i -g eas-cli`
> * then used sudo for eas build `sudo eas build -p ios -e development`
>   the last step probably did the trick.

**Comment by JoPoTe** [comment]
> I was having the same issue but updating eas-cli and then building again worked for me:
> 
> `npm install -g eas-cli`

Worked like a charm :) thank you!

**Comment by GregBaLpro** [comment]
Confirming here `npm install -g eas-cli` worked for me too.

**Comment by BilegtGG** [comment]
guys keep calm goto https://appstoreconnect.apple.com/ accept new terms then im ok

**Comment by VadymBezsmertnyi** [comment]
The change in the eas.json version to:
```
"cli": {
    "version": ">= 10.0.2"
}
```
and the addition of:
```
"submit": {
    "production": {
        "ios": {
            "ascAppId": "*******"
        }
    }
}
```
helped me solve the issue.

**Comment by Palvaran** [comment]
VadymBezsmertnyi, thanks. That helped me and I was able to submit.

**Comment by jottenlips** [comment]
```
rm -rf ~/.app-store                                     
EXPO_NO_KEYCHAIN=1 eas submit --platform ios 
```

Fixed my authentication issues on EAS 12.6.2

**Comment by gursewak-sohi** [comment]
Just `eas logout` and `eas login` again.

**Comment by Patrick-web** [comment]
This issue needs to be reopened cause it keeps happening

**Comment by GoLuxBusiness** [comment]
Same

**Comment by GoLuxBusiness** [comment]
Whatever apple ID you're using to sign into your developer account you're trying to push the app to.

Sign that apple ID into your iPhone or iPad. It will then allow you to verify from device instead of SMS and it works everytime!

**Comment by bajahranks** [comment]
@GoLuxBusiness I don't have any apple products, so what other option do I have.

**Comment by huybui21** [comment]
`Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Apple service errors:
- Verification codes can’t be sent to this phone number at this time. Please try again later.
If you encounter persistent issues with Apple 2FA SMS authentication, you can try using these workarounds: https://expo.fyi/apple-2fa-sms-issues-workaround.md.'. Retrying after 3 seconds (remaining: 3)

× Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Apple service errors:
- Verification codes can’t be sent to this phone number at this time. Please try again later.
If you encounter persistent issues with Apple 2FA SMS authentication, you can try using these workarounds: https://expo.fyi/apple-2fa-sms-issues-workaround.md.
    Error: build command failed.`
The error still occurs, does anyone have a solution to fix it? I use eas-cli 15.0.15

**Comment by bajahranks** [comment]
@huybui21 +1

**Comment by wajahat9876** [comment]
i tried to install eas cli globally but did not worked for me than i tried this comand and this worked use npx (npx eas build --profile) instead of eas(eas build --profile) it worked

**Comment by mister-conor** [comment]
Experiencing this issue also. (eas-cli/16.6.1 win32-x64 node-v22.14.0)

**Comment by Josiassejod1** [comment]
For me I had to set my node version `nvm use 20` for it to get working for me.

**Comment by ngokevin** [comment]
Nothing above worked. Latest NVM, latest EAS, old EAS, relogging in and out.

I had to create my own certificate manually.

You need to:

	1.	Create a new Certificate Signing Request (CSR) on your machine:
	•	Keychain Access → Certificate Assistant → Request a Certificate from a Certificate Authority
	•	Save the .certSigningRequest
	2.	Go to [Apple Developer → Certificates](https://developer.apple.com/account/resources/certificates/list)
	3.	Create a new Apple Distribution certificate, upload your .certSigningRequest
	4.	Download the new .cer and install it (double-click it)

Because you created the CSR on your local machine, the resulting .cer will be paired with the private key automatically in your Keychain.

	5.	Now go back to “My Certificates”, and you should see: Apple Distribution: Your Name
  > private key

 Right-click the cert and Export → now you’ll see .p12 as an option.

**Comment by ngokevin** [comment]
I received this error because my eas-cli was outdated. I did update it and kept getting the error. But it was because I was running eas through yarn package.json script. Running it through command line raw as an eas command ensured the correct version

**Comment by daehyeonmun2021** [comment]
Updating eas-cli version solved my issue

```
npm install -g eas-cli
# or
yarn global add eas-cli
```

**Comment by Tranthanh98** [comment]
same issue in 2026.
not sure it's issue of Apple server or eas

**Comment by AaronH2001** [comment]
@Tranthanh98 did you find a solution? I'm getting the same error and can't log in.

**Comment by Tranthanh98** [comment]
> [@Tranthanh98](https://github.com/Tranthanh98) did you find a solution? I'm getting the same error and can't log in


It’s totally issue from Apple Server, wait for several  hours or use Xcode cloud to build

**Comment by tchesa** [comment]
> Just `eas logout` and `eas login` again.

that worked for me.
