### ISSUE TITLE
I am trying to build the iOS version of an application locally whose Expo. I have no issues building the Android version but run into issues when building the iOS. I can build the iOS version when I generate the Xcode project myself but cannot via eas.

### ISSUE THREAD

**Issue by leo3773** [expo/eas-cli#2307]
### Build/Submit details page URL

https://expo.dev/accounts/leonardostan/projects/TotalJobs/builds/16ef6b61-260e-4496-b1e0-913660b94938

### Summary

I am trying to build the iOS version of an application locally whose Expo. I have no issues building the Android version but run into issues when building the iOS. I can build the iOS version when I generate the Xcode project myself but cannot via eas.

### Managed or bare?

Managed 

### Environment

PS C:\Users\Leodora\TotalJobsios\TotalJobs> npx expo-doctor
WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check package.json for common issues
✔ Validate global prerequisites versions
✔ Validate Expo Config
✔ Check for incompatible packages
✔ Check for conflicting global packages in project
✔ Verify prebuild support package versions are compatible
✔ Check compatible dependency versions for the installed Expo SDK

Didn't find any issues with the project!

### Error output

Sat, 30 Mar 2024 22:36:26 GMT

Build failed: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.

### Reproducible demo or steps to reproduce from a blank project

Sat, 30 Mar 2024 22:32:55 GMT

[stderr] 

2024-03-30 15:32:55.147 xcodebuild[2680:9408] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
Sat, 30 Mar 2024 22:32:57 GMT

Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
Sat, 30 Mar 2024 22:32:58 GMT

[stderr] 

2024-03-30 15:32:58.192 xcodebuild[2689:9442] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
Sat, 30 Mar 2024 22:32:58 GMT

[stderr] 

2024-03-30 15:32:58.479 xcodebuild[2680:9421] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
Sat, 30 Mar 2024 22:32:59 GMT

[stderr] 

2024-03-30 15:32:59.029 xcodebuild[2689:9476] Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition; Sat, 30 Mar 2024 22:33:15 GMT

⚠️  (../../../../include/event2/event.h:1463:10)

  @param eb the event_base structure returned by event_base_new()
         ^ parameter 'eb' not found in the function declaration [-Wdocumentation]; Sat, 30 Mar 2024 22:35:42 GMT

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » TotalJobs/TotalJobs » Build Phases » 'Start Packager'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script
Sat, 30 Mar 2024 22:35:42 GMT

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » TotalJobs/TotalJobs » Build Phases » 'Bundle React Native code and images'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script
Sat, 30 Mar 2024 22:35:42 GMT

› Executing TotalJobs » [CP] Check Pods Manifest.lock; Sat, 30 Mar 2024 22:36:19 GMT

❌  error: File /Users/expo/Library/Developer/Xcode/DerivedData/TotalJobs-gbnzcigqpacqsfdrpvtiamfyqxnd/Build/Intermediates.noindex/ArchiveIntermediates/TotalJobs/BuildProductsPath/Release-iphoneos/TotalJobs.app/main.jsbundle does not exist. This must be a bug with React Native, please report it here: https://github.com/facebook/react-native/issues

**Comment by szdziedzic** [comment]
Hi,

I found this in `Xcode logs`:
```
Error: Unable to resolve module ./src/screens/ReseñasScreen from /Users/expo/workingdir/build/App.js: 

​

None of these files exist:

  * src/screens/ReseñasScreen(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)

  * src/screens/ReseñasScreen/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs)
  ```
  
 It looks like the `ReseñasScreen` can't be found. I'm wondering if this can be because it includes a non-English letter in the name (`ñ`) 🤔 . Can you try to rename it to `ResenasScreen` and try again?

**Comment by leo3773** [comment]
Gracias, perfecto, thank you very much

**Comment by szdziedzic** [comment]
I'm happy that it worked. I'm closing the issue.
