### ISSUE TITLE
Unexpected server error on Android buils

### ISSUE THREAD

**Issue by Noxel** [expo/eas-cli#2314]
### Summary

Hi, just wanted to make a fix on an app in expo 49 but can't build it. I have no idea what's the problems. I search at my side on compare this project with other that i can build with eas-cli but could not find a difference. 
It happend for a week now. 

I have post a [message ](https://discord.com/channels/695411232856997968/943205994123657246/1224740209321840680) at the discord server.

### Managed or bare?

bare

### Environment

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✖ Check native tooling versions
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✖ Check for common project setup issues
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that native modules use compatible support package versions for installed Expo SDK
Detailed check results:
Expected package @expo/config-plugins@~7.2.2
Found invalid:
@expo/config-plugins@7.8.4
@expo/config-plugins@7.8.4
@expo/config-plugins@7.8.4
(for more info, run: npm why @expo/config-plugins)
Advice: Upgrade dependencies that are using the invalid package versions0.
This project has native project folders but is also configured to use Prebuild. EAS Build will not sync your native configuration if the ios or android folders are present. Add these folders to your .gitignore file if you intend to use prebuild (aka "managed" workflow).
Cocoapods version check failed. Cocoapods may not be installed or there may be an issue with your Cocoapods installation. Installing version 1.15.2 or higher is recommended.
One or more checks failed, indicating possible issues with the project.

### Error output
```
Starting Android build

[
  {
    "extensions": {
      "requestId": "922[68](https://gitlab.ci.novadys.cloud/dev/novatime/mobile/intervenants/-/jobs/266042#L68)9c9-9ac3-4f20-be2f-ace00cee5[71](https://gitlab.ci.novadys.cloud/dev/novatime/mobile/intervenants/-/jobs/266042#L71)3",
      "code": "INTERNAL_SERVER_ERROR",
      "errorCode": "EAS_BUILD_DOWN",
      "metadata": {},
      "isTransient": false
    },
    "message": "Unexpected server error (Expo error ID: 922689c9-9ac3-4f20-be2f-ace00cee5713).",
    "locations": [
      {
        "line": 3,
        "column": 5
      }
    ],
    "path": [
      "build",
      "createAndroidBuild"
    ]
  }
]

Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
Request ID: 9226[89](https://gitlab.ci.novadys.cloud/dev/novatime/mobile/intervenants/-/jobs/266042#L89)c9-9ac3-4f20-be2f-ace00cee5713
Error message: Unexpected server error (Expo error ID: 922689c9-9ac3-4f20-be2f-ace00cee5713).
Error: Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, report the issue.
Request ID: 922689c9-9ac3-4f20-be2f-ace00cee5713
Error message: Unexpected server error (Expo error ID: 922689c9-9ac3-4f20-be2f-ace00cee5713).
    at handleBuildRequestError (/root/.npm/_npx/e25a38a8cc65d08e/node_modules/eas-cli/build/build/build.js:147:15)
    at /root/.npm/_npx/e25a38a8cc65d08e/node_modules/eas-cli/build/build/build.js:100:17
    at process.processTicksAndRejections (node:internal/process/task_queues:[95](https://gitlab.ci.novadys.cloud/dev/novatime/mobile/intervenants/-/jobs/266042#L95):5)
    at async startBuildAsync (/root/.npm/_npx/e25a38a8cc65d08e/node_modules/eas-cli/build/build/runBuildAndSubmit.js:261:12)
    at async prepareAndStartBuildAsync (/root/.npm/_npx/e25a38a8cc65d08e/node_modules/eas-cli/build/build/runBuildAndSubmit.js:247:19)
    at async runBuildAndSubmitAsync (/root/.npm/_npx/e25a38a8cc65d08e/node_modules/eas-cli/build/build/runBuildAndSubmit.js:88:49)
    at async Build.runAsync (/root/.npm/_npx/e25a38a8cc65d08e/node_modules/eas-cli/build/commands/build/index.js:41:9)
    at async Build._run (/root/.npm/_npx/e25a38a8cc65d08e/node_modules/@oclif/core/lib/command.js:80:22)
    at async Config.runCommand (/root/.npm/_npx/e25a38a8cc65d08e/node_modules/@oclif/core/lib/config/config.js:301:25)
    Error: build command failed.
```
### Reproducible demo or steps to reproduce from a blank project

One on my project has this problem on every build or the last week but other projects are fine.

I juste do a npx eas-cli build --pofile prod --platform android --non-interactive

**Comment by szdziedzic** [comment]
You use the `latest` EAS CLI version, right?

**Comment by Noxel** [comment]
> You use the `latest` EAS CLI version, right?
The `latest` EAS CLI with npx

**Comment by szdziedzic** [comment]
Interesting, I can't see anything super helpful in our internal logs. Can you show me what your `eas.json` looks like?

**Comment by szdziedzic** [comment]
Hi there @Noxel,

I think I know what's wrong. It seems like you have a disallowed unicode character in the build job's `node` version value. There are 2 ways to set the `node` value:
1. directly in `eas.json` by using the `node` field
2. by having a `.nvmrc` file in your project dir (we read the version from there by default)

Do you use any of these by any chance?

Removing this character should solve the issue. I will try to make the error message better as a follow-up. We validate the build job in EAS CLI before sending it to EAS servers, so I'm confused why your `node` version passed the validation.

![image](https://github.com/expo/eas-cli/assets/55145344/584df758-b14f-45f3-9080-d41189e2487c)

**Comment by Noxel** [comment]
Hi @szdziedzic,

Unfortunately we don't use any of these, i try to affect a value to the `node `field directly in `eas.json` but it doesn't change the outcome of the build request.

In fact we use the version 18 of `node `for our pipeline, so I don't know where the `buildEnvironment `took this version fo `node`. 

How can we detect some false information in the build job send to EAS ?

**Comment by wodin** [comment]
@Noxel what do you get if you run the command shown here to see what will get uploaded to the build servers:
https://github.com/expo/fyi/blob/main/eas-build-archive.md#what-files-are-included-in-the-archive

Then search in those files for `20.9`?

e.g. `grep -rl '20\.9' ~/target/output/path`

**Comment by Noxel** [comment]
Hi @wodin sorry for the late response.
I did search for `20.9` in my local and when the pipeline executes `eas build` but couldn't find anything.

**Comment by RalfiBahar** [comment]
Having the same issue. Is there a solution?

**Comment by Noxel** [comment]
My problem resolved itself. I was unable to identify what was blocking the build from being sent.
