### ISSUE TITLE
[eas-cli] `eas build` does not fail if one of the builds on EAS fails

### ISSUE THREAD

**Issue by timvlaer** [expo/eas-cli#232]
Hi there, thanks for the awesome eas project, it made me win a lot of time with my app builds 😅 

I wonder if it's possible to let the build command fail in case on of the builds on the EAS server fails. 

I'm using the `build` and `submit` commands in a CI environment. I build both iOS and Android apps at the same time, if one of them fails, the process still continues because the command properly exists with exit code 0. (And then the submit is trying to submit the previous build which obviously doesn't work 😉  )

**Comment by barthap** [comment]
Hello, this issue is resolved by #272. It will be published with the next version of `eas-cli` package.

**Comment by timvlaer** [comment]
Great news, thanks @barthap !
