### ISSUE TITLE
EAS Build Fails When Trying to Install sqlite3 Pod

### ISSUE THREAD

**Issue by TheRealMikeD** [expo/eas-cli#2321]
### Build/Submit details page URL

https://expo.dev/accounts/duckandbeaver/projects/your-daily/builds/79f0d7bd-ebef-425d-bb44-2cf7775e737d

### Summary

Builds are failing on EAS with the same error each time: a failure to install a pod for sqlite3 because the server could not be contacted.

### Managed or bare?

Managed with custom dev client

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 12.7.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.18 - /usr/local/bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10811636
      Xcode: 14.2/14C18 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.15 => 50.0.15 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: ^0.73.6 => 0.73.6 
      react-native-web: ~0.19.6 => 0.19.7 
    npmGlobalPackages:
      eas-cli: 7.6.2
    Expo Workflow: managed

### Error output

From the "Install Pods" phase of EAS Build:

[!] Error installing sqlite3
[!] /usr/bin/curl -f -L -o /var/folders/p2/2788nfhd7xq3pnnk81v00sf00000gn/T/d20240411-1839-1nxnrca/file.zip https://www.sqlite.org/2023/sqlite-src-3420000.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.14.3 cocoapods-downloader/2.1'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to www.sqlite.org port 443 after 75011 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 1 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to www.sqlite.org port 443 after 75008 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 2 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:00 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to www.sqlite.org port 443 after 75007 ms: Couldn't connect to server
[!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `A000494126174E7B917C3AB7` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
Error: Unknown error. See logs of the Install pods build phase for more information.

### Reproducible demo or steps to reproduce from a blank project

I'm honestly not even sure why the pod for sqlite3 is attempting to install.  It's not in the dependencies for my project, and I don't see sqlite3 anywhere in the package-lock.json file.

Without knowing why it's trying to install during EAS Build, I'm not sure how I would create a minimal reproducible example.  If someone can help me figure out how/why it's in there, I'll be happy to try to create a reproducible example.

**Comment by TheRealMikeD** [comment]
FWIW, the same curl call that is failing works perfectly fine (with a different destination folder) on my dev machine.  So I don't think it is just that the server and/or file are truly unavailable.

**Comment by jafework** [comment]
I just ran into this problem, something was cached weird.

1. If you have any cache keys defined in eas.json try to set them to new values and retry
2. You can try running expo prebuild then go to your ios directory and run pod repo update -> I found this also helped clear out some things. 

Good Luck

**Comment by anthonyringoet** [comment]
I saw this as a one-time error. Have your retried at another time?

**Comment by darrencrossley** [comment]
we also had this issue - rerunning today seems to work now.

**Comment by szdziedzic** [comment]
Hi there, thanks for the report!

It was a real issue yesterday. It seems like the `www.sqlite.org` blocked all of the requests coming from our internal builder's network, therefore failing all of the builds trying to install the SQLite pod. Fortunately, we were able to resolve the issue shortly and it should no longer be a problem.

**Comment by asfakhuseng** [comment]
still its not working for us.

**Comment by claudesortwell** [comment]
Still an issue for us also.

**Comment by davidfraim** [comment]
Not working

**Comment by CarlMenke** [comment]
+ 1

**Comment by nodir-js** [comment]
Worked with VPN

**Comment by pr0xyMity** [comment]
Still not working for me, I'm trying to build it on Mac mini M2
