### ISSUE TITLE
EAS Build error for iOS, sqlite3.org not found

### ISSUE THREAD

**Issue by RyanShofeur** [expo/eas-cli#2330]
### Build/Submit details page URL

https://expo.dev/accounts/rromero95/projects/shofeur-app-driver/builds/a680d1c7-058e-4310-ba5c-1124bc802db9

### Summary

When running `eas build --profile production --platform ios` The build on EAS fails when running `Installing sqlite3 (3.42.0)`

### Managed or bare?

bare

### Environment

user@user-MacBook-Air app % npx expo-env-info
Need to install the following packages:
expo-env-info@1.2.0
Ok to proceed? (y) 

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.2 - /opt/homebrew/bin/node
      npm: 10.5.0 - /opt/homebrew/bin/npm
      Watchman: 2024.04.01.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.0.1/15A507 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~50.0.15 => 50.0.15 
      react: 18.2.0 => 18.2.0 
      react-native: 0.73.6 => 0.73.6 
      react-navigation: ^4.4.4 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 7.2.0
      expo-cli: 6.3.10
    Expo Workflow: bare
    
    user-MacBook-Air app % npx expo-doctor
(node:55057) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check that native modules do not use incompatible support packages
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

### Error output

Installing sqlite3 (3.42.0)
[!] Error installing sqlite3
[!] /usr/bin/curl -f -L -o /var/folders/p2/2788nfhd7xq3pnnk81v00sf00000gn/T/d20240414-1808-1q9zeeo/file.zip https://www.sqlite.org/2023/sqlite-src-3420000.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.14.3 cocoapods-downloader/2.1'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to www.sqlite.org port 443 after 75008 ms: Couldn't connect to server

### Reproducible demo or steps to reproduce from a blank project

eas build --profile production --platform ios

**Comment by claudesortwell** [comment]
An issue for us also, running the sqlite install command that fails on EAS has no issues locally. 

https://expo.dev/accounts/haydensmith/projects/pearler/builds/03f11f7c-554a-4351-8df2-e80e05bb5be8

**Comment by szdziedzic** [comment]
Hi, our last fix doesn't seem to work for all of the developers https://github.com/expo/eas-cli/issues/2321#issuecomment-2051505001

I've just triggered a prod deployment that should fix the issue for all of you. I will let you know when it lands.

**Comment by szdziedzic** [comment]
Hi,

I believe that now it should finally be fixed for everybody. Can you check @claudesortwell @RyanShofeur 🙏?

**Comment by claudesortwell** [comment]
> Hi,
> 
> 
> 
> I believe that now it should finally be fixed for everybody. Can you check @claudesortwell @RyanShofeur 🙏? 

Thanks, fixed for me

**Comment by szdziedzic** [comment]
Cool, so I think I can close it

**Comment by RyanShofeur** [comment]
@szdziedzic Can we reopen this issue, I am using expo 51 and the issue seems to be back. Logs below

`[!] CocoaPods could not find compatible versions for pod "sqlite3":
  In Podfile:
    EXUpdates (from `../node_modules/expo-updates/ios`) was resolved to 0.25.15, which depends on
      sqlite3 (~> 3.45.3+1)
    sqlite3 (from `https://github.com/TykeeLabs/sqlite3pod-mirror.git`, branch `master`)
[!] [Codegen] warn: using experimental new codegen integration`

When running pod install:
`[Codegen] >>>>> Searching for codegen-enabled libraries in react-native.config.js
[Codegen] Processing rnasyncstorage
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, macos, tvos, visionos for rnasyncstorage
[Codegen] Processing FBReactNativeSpec
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Processing rncore
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Processing rngesturehandler_codegen
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, macos, tvos, visionos for rngesturehandler_codegen
[Codegen] Processing safeareacontext
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, tvos, visionos for safeareacontext
[Codegen] Processing rnscreens
[Codegen] Searching for podspec in the project dependencies.
[Codegen] Supported Apple platforms: ios, tvos, visionos for rnscreens
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/ryanromero/Desktop/Shofeur/shofeur-app-driver/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/ryanromero/Desktop/Shofeur/shofeur-app-driver/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/ryanromero/Desktop/Shofeur/shofeur-app-driver/node_modules/react-native/ReactCommon
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/ryanromero/Desktop/Shofeur/shofeur-app-driver/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/ryanromero/Desktop/Shofeur/shofeur-app-driver/ios/build/generated/ios
[Codegen] Generating Native Code for ios
[Codegen] Generated artifacts: /Users/ryanromero/Desktop/Shofeur/shofeur-app-driver/ios/build/generated/ios
[Codegen] Creating component provider.
[Codegen] Generated provider in: /Users/ryanromero/Desktop/Shofeur/shofeur-app-driver/node_modules/react-native/React/Fabric
[Codegen] Done.
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `fmt` from `../node_modules/react-native/third-party-podspecs/fmt.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.74.1/react-native-artifacts-0.74.1-hermes-ios-debug.tar.gz
Pre-downloading: `sqlite3` from `https://github.com/TykeeLabs/sqlite3pod-mirror.git`, branch `master`
[!] CocoaPods could not find compatible versions for pod "sqlite3":
  In Podfile:
    EXUpdates (from `../node_modules/expo-updates/ios`) was resolved to 0.25.15, which depends on
      sqlite3 (~> 3.45.3+1)

    sqlite3 (from `https://github.com/TykeeLabs/sqlite3pod-mirror.git`, branch `master`)

[!] [Codegen] warn: using experimental new codegen integration`

**Comment by marlo22** [comment]
I had a similar issue. I run `pod repo update` in my terminal and this resolved the problem.

**Comment by marlo22** [comment]
@RyanShofeur, I had a similar issue. I run `pod repo update` in my terminal and this resolved the problem.

**Comment by wodin** [comment]
@RyanShofeur that's a different issue. The problem seems to be that it wants version `3.45.3+1`, but the version in that repository is `3.42.0`:
https://github.com/TykeeLabs/sqlite3pod-mirror/blob/5085cbd5dbd1e7a747aa56c9070f2573c04b4332/sqlite3.podspec#L3

**Comment by chunghn** [comment]
Same issue for me. 
```
[INSTALL_PODS] [!] CocoaPods could not find compatible versions for pod "sqlite3":
[INSTALL_PODS]   In Podfile:
[INSTALL_PODS]     EXUpdates (from `../node_modules/expo-updates/ios`) was resolved to 0.25.19, which depends on
[INSTALL_PODS]       sqlite3 (~> 3.45.3+1)
[INSTALL_PODS] None of your spec sources contain a spec satisfying the dependency: `sqlite3 (~> 3.45.3+1)`.
```

**Comment by chunghn** [comment]
Solve by npx expo prebuild -> cd ios -> pod install
I am a newbie and would be great if anyone explained this fix, thanks.

**Comment by wodin** [comment]
> Solve by npx expo prebuild -> cd ios -> pod install
> I am a newbie and would be great if anyone explained this fix, thanks.

Depending on exactly how you build and whether or not you have made changes to the `ios` directory that you want to keep, the following would probably have fixed it too:

Add this to `.gitignore`:
```
/android/
/ios/
```

**Comment by chunghn** [comment]
Thanks for your reply. I'm building with --local flag. And I leave an old ios dir. I guess it is the reason I failed?

**Comment by wodin** [comment]
Yes, most likely. But if you add the directories to `.gitignore` then `eas build` will not copy them to the temporary build directory when it builds, so it will automatically run `prebuild` in the build directory.
