### ISSUE TITLE
EAS Cli is not recognized after installation

### ISSUE THREAD

**Issue by kralion** [expo/eas-cli#2369]
### Build/Submit details page URL

I am wanting to build but i can't because of that error

### Summary

I installed eas cli from the docs, with `npm install --global eas-cli` after succesful installation i check for `eas login` but i shows me this. even restarting my OS 

![image](https://github.com/expo/eas-cli/assets/66649036/22caf4fe-7b75-4d70-a7b9-949a84246edc)
![image](https://github.com/expo/eas-cli/assets/66649036/427199e0-27e9-4dd0-904c-08f36ddede71)

### Managed or bare?

Bare

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22621
    Binaries:
      Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD

## Terminal reloaded
![image](https://github.com/expo/eas-cli/assets/66649036/970071e2-11bf-4698-9585-efbfab05cdea)

### Reproducible demo or steps to reproduce from a blank project

it is happening with all my projects

**Comment by AbishekVimal** [comment]
I'm facing the same issue too.  Still have not figured out the solution for this! I have 3 projects finished but cannot build because of this one issue!

**Comment by szdziedzic** [comment]
It doesn't seem like an issue/bug with EAS CLI. It looks like a problem with your Node installation on a Windows machine - binaries installed via `npm` don't seem to be added to PATH.

I would start with finding the directory where `node` and `npm` are installed on your machine, then look for the `bin` dir with the `eas` executable in it. If you add this dir to your PATH you should have it working.

**Comment by kralion** [comment]
My node installation is configured correctly
![image](https://github.com/expo/eas-cli/assets/66649036/50f7c8f0-eaf0-4ff5-aaf6-9fa6eeb8f544)
![image](https://github.com/expo/eas-cli/assets/66649036/9e3251a5-98e2-4609-b481-4b30998ea468)

**Comment by furkanuzundev** [comment]
use **eas** command with **npx** was worked for me. for examlpe: `npx eas update`

**Comment by linjinxing** [comment]
I'm facing the same issue too. Still have not figured out the solution for this! 
    "eas": "^0.1.0",
    "expo": "~51.0.18",

**Comment by linjinxing** [comment]
work for me
npm install -g eas-cli and npm uninstall -g eas

**Comment by FlavioScimeca** [comment]
```
npm install -g eas-cli
# or
yarn global add eas-cli
```
for using npm solved the issue

**Comment by idflxw0** [comment]
you can try using with npx like` npx eas <your commands>`. it worked for me

**Comment by kralion** [comment]
It's working, fixed with npx

**Comment by Mr-Roy-alt** [comment]
Here is how I solved it:
- Opened the Command Prompt as an Administrator to execute the command, then 
`npm install -g eas-cli
# or
yarn global add eas-cli`
- Restarted the PC, and I was good to go.
