### ISSUE TITLE
Unable to make iOS build on MacOS

### ISSUE THREAD

**Issue by Ibrahim-Arif** [expo/eas-cli#2377]
### Summary

For the last couple of weeks, I have been facing an issue with EAS builds, whenever I try to make a new iOS build it first gives me a message to upgrade the EAS-CLI package even though I already have the latest one installed, and when it tries to register the bundle identifier it gives a weird error. 
    
    
I have tried with multiple bundle identifiers, and the error remains the same. 

### Managed or bare?

Managed

### Environment

ibrahimarif@Ibrahims-MacBook-Pro ESL-Wombat % sudo npx expo-env-info

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 3.2.57 - /bin/sh
    Binaries:
      Node: 20.11.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8193401
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.4 => 51.0.4 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
    npmGlobalPackages:
      eas-cli: 9.0.3
    Expo Workflow: managed

--------------

ibrahimarif@Ibrahims-MacBook-Pro ESL-Wombat % sudo npx expo-doctor
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

### Error output

```
**✖ Failed to register bundle identifier XXX 
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
This request can not be processed right now - Service not available because of maintenance activities, please try again after some time.
    Error: build command failed.is** 
```

### Reproducible demo or steps to reproduce from a blank project

this happens when I try to make a new build for a new Expo project on SDK 50 or 51.

the command I'm using is: eas build -p ios -- profile production

And if I use the same command on a Windows laptop with the same project it works fine.

**Comment by szdziedzic** [comment]
what is the output of the `eas --version` command on your machine?

**Comment by ahmadtech199** [comment]
**Hello @Ibrahim-Arif,**
Is this problem solved?

**Comment by Ibrahim-Arif** [comment]
> **Hello @Ibrahim-Arif,** Is this problem solved?

Yes, it turned out I had 2 versions of EAS installed on my Mac, one was latest and second was very old version in the global packages folder, so i uninstalled the old version and now using the latest version which works well.

**Comment by ahmadtech199** [comment]
Yes, like me , i used `where eas `, and i found 3 install from same package,I removed it, and then install it again, and it works now.

Thank you
