### ISSUE TITLE
Could not read bundle identifier from Xcode project (target = XXXX, build configuration = Release).

### ISSUE THREAD

**Issue by Giosevid** [expo/eas-cli#2383]
### Summary

Hello i have a project made with react native cli and receive the next issue when run `eas build -p ios --profile develop ` `Specified value for "xxx.xxxx.xxxx" in app.config.js or app.json is ignored because an ios directory was detected in the project.
EAS Build will use the value found in the native code.
Could not read bundle identifier from Xcode project (target = XXXXXXX, build configuration = Release).`

### Managed or bare?

Managed

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.2.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.12 => 0.72.12 
    npmGlobalPackages:
      eas-cli: 8.0.0
    Expo Workflow: bare

### Error output

Could not read bundle identifier from Xcode project (target = XXXXXX, build configuration = Release).

### Reproducible demo or steps to reproduce from a blank project

run: eas build -p ios --profile develop

**Comment by szdziedzic** [comment]
Hey, are sure that your native directories (`./android` and `./ios`) are in a good state? It seems like they are not 🤔 

If you want to be on a `managed` flow (you don't want to do anything in native code) you can delete the native directories and if you are using [CNG](https://docs.expo.dev/workflow/continuous-native-generation/) you can run `npx expo --clean` to regenerate them

**Comment by thaiscristine** [comment]
I found the same issue but in a bare React Native project. 

"Could not read bundle identifier from Xcode project (target = XXXX, build configuration = Release-Test)"

@Giosevid how did you solve the issue?
