### ISSUE TITLE
Build no longer working [Could not locate a valid AppDelegate at root]

### ISSUE THREAD

**Issue by lander854** [expo/eas-cli#2400]
### Build/Submit details page URL

https://expo.dev/accounts/librex/projects/rtro/builds/96097dbf-c26e-4623-91a7-43df3744bda9

### Summary

Setting the update request headers in 'Expo.plist' to '{"expo-channel-name":"production"}'
Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build/apps/mobile"
Please report this as an issue on https://github.com/expo/expo/issues

### Managed or bare?

bare

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
      Yarn: 1.22.22 - ~/projects/PX2_Mono/apps/mobile/node_modules/.bin/yarn
      npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 28, 29, 30, 31, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 33.0.2, 34.0.0, 35.0.0
        System Images: android-33 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11709847
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^50.0.14 => 50.0.14
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: ^0.73.5 => 0.73.5
    npmGlobalPackages:
      eas-cli: 9.1.0
    Expo Workflow: bare

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Didn't find any issues with the project!

### Error output

[INSTALL_PODS] Pod installation complete! There are 114 dependencies from the Podfile and 168 total pods installed.
[INSTALL_PODS] [!] Can't merge pod_target_xcconfig for pod targets: ["expo-dev-menu", "Main", "ReactNativeCompatibles", "SafeAreaView", "Vendored"]. Singular build setting DEFINES_MODULE has different values.
[INSTALL_PODS] [!] Can't merge pod_target_xcconfig for pod targets: ["expo-dev-menu", "Main", "ReactNativeCompatibles", "SafeAreaView", "Vendored"]. Singular build setting DEFINES_MODULE has different values.
[INSTALL_PODS] [!] hermes-engine has added 1 script phase. Please inspect before executing a build. See https://guides.cocoapods.org/syntax/podspec.html#script_phases for more information.
[CALCULATE_EXPO_UPDATES_RUNTIME_VERSION] Resolved runtime version: 1.0.1
[CONFIGURE_XCODE_PROJECT] Configuring Xcode project
[CONFIGURE_XCODE_PROJECT] Assigning provisioning profile '*[expo] com.rtro AppStore 2024-02-23T12:35:43.285Z' (Apple Team ID: 2BKZ3YTY2W) to target 'rtro'
[CONFIGURE_EXPO_UPDATES] Setting the update request headers in 'Expo.plist' to '{"expo-channel-name":"production"}'
[CONFIGURE_EXPO_UPDATES]
UnexpectedError: Could not locate a valid AppDelegate at root

### Reproducible demo or steps to reproduce from a blank project

could not replicate on a blank, currently using a lot of libraries in the project.

**Comment by szdziedzic** [comment]
@lander854 can you try to update your project dependencies `npx expo install --check`?

**Comment by makbeth** [comment]
@lander854 have you managed to fix that? And how?

**Comment by lander854** [comment]
@makbeth what I did was move the project outside of the monorepo, seems like expo EAS is doing a shallow copy when used in a monorepo, missing some deep nested files
