### ISSUE TITLE
MODULE_NOT_FOUND with version 0.4.2

### ISSUE THREAD

**Issue by gjsduarte** [expo/eas-cli#241]
Hey there,

I just wanted to inform that I started receiving the following error message when using version **0.4.2** via npx: 

```
Error: Cannot find module '/Users/guilherme/.npm/_npx/91612/lib/node_modules/eas-cli/node_modules/@babel/runtime/helpers/interopRequireDefault.js'
Code: MODULE_NOT_FOUND
```

For now, I reverted back to 0.4.1.

Cheers

**Comment by wkozyra95** [comment]
Probably one of the dependencies (most likely @babel runtime `7.12.17` ) published an invalid value, at the same time eas builds also started to fail for the same reason. This issue was happening for under an hour and was fixed shortly after you created that issue.
