### ISSUE TITLE
`eas update` command failed

### ISSUE THREAD

**Issue by Santa0727** [expo/eas-cli#2421]
### Summary

I am using expo project and I wanted to update it so I tried to run `eas update` command but, it failed with the following error:

[expo-cli] Error: Unable to resolve module .\node_modules\expo\AppEntry.js from <my_project>/.: .\node_modules\expo\AppEntry.js could not be found within the project or in these directories:
[expo-cli]   node_modules
[expo-cli] Error: Unable to resolve module .\node_modules\expo\AppEntry.js from <my_project>/.: .\node_modules\expo\AppEntry.js could not be found within the project or in these directories:
[expo-cli]   node_modules
[expo-cli]     at ModuleResolver.resolveDependency (<my_project>\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:138:15)
[expo-cli]     at DependencyGraph.resolveDependency (<my_project>\node_modules\metro\src\node-haste\DependencyGraph.js:231:43)
[expo-cli]     at <my_project>\node_modules\metro\src\lib\transformHelpers.js:156:21
[expo-cli]     at Server._resolveRelativePath (<my_project>\node_modules\metro\src\Server.js:1023:12)
[expo-cli]     at MetroBundlerDevServer.resolveRelativePathAsync (<my_project>\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:1204:12)
[expo-cli]     at MetroBundlerDevServer.metroLoadModuleContents (<my_project>\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:429:35)
[expo-cli]     at MetroBundlerDevServer.legacySinglePageExportBundleAsync (<my_project>\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:552:20)       
[expo-cli]     at <my_project>\@expo\cli\src\export\exportApp.ts:137:26
[expo-cli]     at async Promise.all (index 0)
[expo-cli]     at exportAppAsync (<my_project>\node_modules\@expo\cli\src\export\exportApp.ts:127:7)
✖ Export failed
<my_project>\expo\bin\cli exited with non-zero code: 1
    Error: update command failed.
   

This is my package.json
{
  ...,
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@types/react-native-htmlview": "^0.16.4",
    "axios": "^1.6.2",
    "expo": "~51.0.9",
    "expo-image-picker": "~15.0.5",
    "expo-status-bar": "~1.12.1",
    "expo-updates": "~0.25.15",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-htmlview": "^0.17.0",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "6.3.0",
    "react-native-reanimated": "~3.10.1",
    "react-native-root-toast": "^3.5.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-tab-view": "^3.5.2",
    "react-redux": "^8.1.3",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2",
    "reselect": "^4.1.8"
  },
  "devDependencies": {
    "@babel/core": "^7.24.0",
    "@types/react": "~18.2.79",
    "@types/react-native": "~0.70.6",
    "typescript": "^5.3.3"
  },
  "private": true,
  "resolutions": {
    "@types/react": "~18.2.14",
    "@types/react-dom": "18.2.0"
  }
}

eas-cli version is eas-cli/9.2.0 win32-x64 node-v20.9.0

I was working before, but after I update some packages by running `npx expo install --fix`, it doesn't work.
I tried to recover, cleaning cache, clear node_modules, re-installing node_modules... and so on but still no luck. :(

### Managed or bare?

managed

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD 
      npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD  
    IDEs:
      Android Studio: AI-231.9392.1.2311.11076708
    npmPackages:
      expo: ~51.0.9 => 51.0.12
      react: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
    Expo Workflow: managed

### Error output

- Exporting...
[expo-cli] 2024-06-11T12:01:25.026Z expo:telemetry:detachedClient Event received: action
[expo-cli] 2024-06-11T12:01:25.520Z expo:env No environment variables loaded from .env files.
[expo-cli] 2024-06-11T12:01:25.552Z expo:telemetry:detachedClient Event received: Start Project
[expo-cli] 2024-06-11T12:01:25.557Z expo:start:server:devServer Stopping dev server (bundler: metro)
[expo-cli] 2024-06-11T12:01:25.557Z expo:start:server:devServer Stopped dev server (bundler: metro) 
[expo-cli] 2024-06-11T12:01:25.574Z expo:start:server:metro:router Using app as the root directory for Expo Router.
[expo-cli] 2024-06-11T12:01:26.554Z expo:metro:config react-native-reanimated package.json: <my_project>\node_modules\react-native-reanimated\package.json
[expo-cli] 
[expo-cli] Expo Metro config:
[expo-cli] - Version: 0.18.5
[expo-cli] - Extensions: ts, tsx, mjs, js, jsx, json, cjs, scss, sass, css
[expo-cli] - React Native: <my_project>\node_modules\react-native
[expo-cli] - Watch Folders:
[expo-cli] - Node Module Paths:
[expo-cli] - Env Files: .env.production.local,.env.local,.env.production,.env
[expo-cli] - Sass: null
[expo-cli] - Reanimated: 3.10.1
[expo-cli]
[expo-cli] 2024-06-11T12:01:27.676Z expo:start:server:metro:multi-platform Enabling alias: react-native-vector-icons -> @expo/vector-icons
[expo-cli] 2024-06-11T12:01:27.676Z expo:metro:withMetroResolvers Appending 5 custom resolvers to Metro config. (has custom resolver: false)
[expo-cli] 2024-06-11T12:01:27.683Z expo:telemetry:detachedClient Event received: metro config
[expo-cli] 2024-06-11T12:01:29.208Z expo:start:server:urlCreator URL: http://<my_local_ip>:8081
[expo-cli] Starting Metro Bundler
[expo-cli]
[expo-cli] 2024-06-11T12:01:29.545Z expo:start:server:middleware:serveStatic Serving static files from: <my_project>\public
[expo-cli] 2024-06-11T12:01:29.994Z expo:start:server:urlCreator URL: exp://<my_local_ip>:8081
[expo-cli] 2024-06-11T12:01:32.690Z expo:telemetry:detachedClient Actor received
[expo-cli] 2024-06-11T12:01:33.042Z expo:metro:options Disabling lazy bundling for export build
[expo-cli] 2024-06-11T12:01:33.045Z expo:metro:options Disabling lazy bundling for export build
[expo-cli] 2024-06-11T12:01:33.663Z expo:metro:withMetroResolvers Custom resolver threw: FailedToResolveNameError. (module: .\node_modules\expo\AppEntry.js, platform: ios)
[expo-cli] 2024-06-11T12:01:33.696Z expo:metro:withMetroResolvers Custom resolver threw: FailedToResolveNameError. (module: .\node_modules\expo\AppEntry.js, platform: ios)
[expo-cli] 2024-06-11T12:01:33.719Z expo:metro:withMetroResolvers Custom resolver threw: FailedToResolveNameError. (module: .\node_modules\expo\AppEntry.js, platform: android)
[expo-cli] 2024-06-11T12:01:33.728Z expo:metro:withMetroResolvers Custom resolver threw: FailedToResolveNameError. (module: .\node_modules\expo\AppEntry.js, platform: android)
[expo-cli] 2024-06-11T12:01:33.743Z expo:start:platforms:android:adbServer Stopping ADB server
[expo-cli] 2024-06-11T12:01:33.743Z expo:start:platforms:android:adbServer ADB server is not running
[expo-cli] 2024-06-11T12:01:33.998Z expo:start:server:devServer Stopping dev server (bundler: metro)
[expo-cli] 2024-06-11T12:01:34.000Z expo:start:server:devServer Stopped dev server (bundler: metro)
[expo-cli] Error: Unable to resolve module .\node_modules\expo\AppEntry.js from <my_project>/.: .\node_modules\expo\AppEntry.js could not be found within the project or in these directories:
[expo-cli]   node_modules
[expo-cli] Error: Unable to resolve module .\node_modules\expo\AppEntry.js from <my_project>/.: .\node_modules\expo\AppEntry.js could not be found within the project or in these directories:
[expo-cli]   node_modules
[expo-cli]     at ModuleResolver.resolveDependency (<my_project>\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:138:15)
[expo-cli]     at DependencyGraph.resolveDependency (<my_project>\node_modules\metro\src\node-haste\DependencyGraph.js:231:43)
[expo-cli]     at <my_project>\node_modules\metro\src\lib\transformHelpers.js:156:21
[expo-cli]     at Server._resolveRelativePath (<my_project>\node_modules\metro\src\Server.js:1023:12)
[expo-cli]     at MetroBundlerDevServer.resolveRelativePathAsync (<my_project>\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:1204:12)
[expo-cli]     at MetroBundlerDevServer.metroLoadModuleContents (<my_project>\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:429:35)
[expo-cli]     at MetroBundlerDevServer.legacySinglePageExportBundleAsync (<my_project>\node_modules\@expo\cli\src\start\server\metro\MetroBundlerDevServer.ts:552:20)       
[expo-cli]     at <my_project>\node_modules\@expo\cli\src\export\exportApp.ts:137:26
[expo-cli]     at async Promise.all (index 0)
[expo-cli]     at exportAppAsync (<my_project>\node_modules\@expo\cli\src\export\exportApp.ts:127:7)
✖ Export failed
<my_project>\node_modules\expo\bin\cli exited with non-zero code: 1
Error: <my_project>\node_modules\expo\bin\cli exited with non-zero code: 1
    at ChildProcess.completionListener (C:\<my_user_directory>\AppData\Roaming\npm\node_modules\eas-cli\node_modules\@expo\spawn-async\build\spawnAsync.js:41:23)
    at Object.onceWrapper (node:events:629:26)
    at ChildProcess.emit (node:events:514:28)
    at cp.emit (C:\<my_user_directory>\AppData\Roaming\npm\node_modules\eas-cli\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at spawnAsync (C:\<my_user_directory>\AppData\Roaming\npm\node_modules\eas-cli\node_modules\@expo\spawn-async\build\spawnAsync.js:7:23)
    at expoCommandAsync (C:\<my_user_directory>\AppData\Roaming\npm\node_modules\eas-cli\build\utils\expoCli.js:80:52)
    at buildBundlesAsync (C:\<my_user_directory>\AppData\Roaming\npm\node_modules\eas-cli\build\project\publish.js:144:53)
    at UpdatePublish.runAsync (C:\<my_user_directory>\AppData\Roaming\npm\node_modules\eas-cli\build\commands\update\index.js:77:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdatePublish._run (C:\<my_user_directory>\AppData\Roaming\npm\node_modules\eas-cli\node_modules\@oclif\core\lib\command.js:80:22)
    at async Config.runCommand (C:\<my_user_directory>\AppData\Roaming\npm\node_modules\eas-cli\node_modules\@oclif\core\lib\config\config.js:301:25) {
  pid: 27776,
  output: [
    '\n' +
      'Expo Metro config:\n' +
      '- Version: 0.18.5\n' +
      '- Extensions: ts, tsx, mjs, js, jsx, json, cjs, scss, sass, css\n' +
      '- React Native: <my_project_directory>\\node_modules\\react-native\n' +
      '- Watch Folders: \n' +
      '- Node Module Paths: \n' +
      '- Env Files: .env.production.local,.env.local,.env.production,.env\n' +
      '- Sass: null\n' +
      '- Reanimated: 3.10.1\n' +
      '\n' +
      'Starting Metro Bundler\n',
    '2024-06-11T12:01:25.026Z expo:telemetry:detachedClient Event received: action\n' +
      '2024-06-11T12:01:25.520Z expo:env No environment variables loaded from .env files.\n' +
      '2024-06-11T12:01:25.552Z expo:telemetry:detachedClient Event received: Start Project\n' +
      '2024-06-11T12:01:25.557Z expo:start:server:devServer Stopping dev server (bundler: metro)\n' +
      '2024-06-11T12:01:25.557Z expo:start:server:devServer Stopped dev server (bundler: metro)\n' +
      '2024-06-11T12:01:25.574Z expo:start:server:metro:router Using app as the root directory for Expo Router.\n' +
      '2024-06-11T12:01:26.554Z expo:metro:config react-native-reanimated package.json: <my_project_directory>\\node_modules\\react-native-reanimated\\package.json\n' +
      '2024-06-11T12:01:27.676Z expo:start:server:metro:multi-platform Enabling alias: react-native-vector-icons -> @expo/vector-icons\n' +
      '2024-06-11T12:01:27.676Z expo:metro:withMetroResolvers Appending 5 custom resolvers to Metro config. (has custom resolver: false)\n' +
      '2024-06-11T12:01:27.683Z expo:telemetry:detachedClient Event received: metro config\n' +
      '2024-06-11T12:01:29.208Z expo:start:server:urlCreator URL: http://<my_local_ip>:8081\n' +
      '2024-06-11T12:01:29.545Z expo:start:server:middleware:serveStatic Serving static files from: <my_project_directory>\\public\n' +
      '2024-06-11T12:01:29.994Z expo:start:server:urlCreator URL: exp://<my_local_ip>:8081\n' +
      '2024-06-11T12:01:32.690Z expo:telemetry:detachedClient Actor received\n' +
      '2024-06-11T12:01:33.042Z expo:metro:options Disabling lazy bundling for export build\n' +
      '2024-06-11T12:01:33.045Z expo:metro:options Disabling lazy bundling for export build\n' +
      '2024-06-11T12:01:33.663Z expo:metro:withMetroResolvers Custom resolver threw: FailedToResolveNameError. (module: .\\node_modules\\expo\\AppEntry.js, platform: ios)\n' +
      '2024-06-11T12:01:33.696Z expo:metro:withMetroResolvers Custom resolver threw: FailedToResolveNameError. (module: .\\node_modules\\expo\\AppEntry.js, platform: ios)\n' +
      '2024-06-11T12:01:33.719Z expo:metro:withMetroResolvers Custom resolver threw: FailedToResolveNameError. (module: .\\node_modules\\expo\\AppEntry.js, platform: android)\n' +
      '2024-06-11T12:01:33.728Z expo:metro:withMetroResolvers Custom resolver threw: FailedToResolveNameError. (module: .\\node_modules\\expo\\AppEntry.js, platform: android)\n' +
      '2024-06-11T12:01:33.743Z expo:start:platforms:android:adbServer Stopping ADB server\n' +
      '2024-06-11T12:01:33.743Z expo:start:platforms:android:adbServer ADB server is not running\n' +
      '2024-06-11T12:01:33.998Z expo:start:server:devServer Stopping dev server (bundler: metro)\n' +
      '2024-06-11T12:01:34.000Z expo:start:server:devServer Stopped dev server (bundler: metro)\n' +
      'Error: Unable to resolve module .\\node_modules\\expo\\AppEntry.js from <my_project_directory>/.: .\\node_modules\\expo\\AppEntry.js could not be found within the project or in these directories:\n' +
      '  node_modules\n' +
      'Error: Unable to resolve module .\\node_modules\\expo\\AppEntry.js from <my_project_directory>/.: .\\node_modules\\expo\\AppEntry.js could not be found within the project or in these directories:\n' +
      '  node_modules\n' +
      '    at ModuleResolver.resolveDependency (<my_project_directory>\\node_modules\\metro\\src\\node-haste\\DependencyGraph\\ModuleResolution.js:138:15)\n' +
      '    at DependencyGraph.resolveDependency (<my_project_directory>\\node_modules\\metro\\src\\node-haste\\DependencyGraph.js:231:43)\n' +
      '    at <my_project_directory>\\node_modules\\metro\\src\\lib\\transformHelpers.js:156:21\n' +
      '    at Server._resolveRelativePath (<my_project_directory>\\node_modules\\metro\\src\\Server.js:1023:12)\n' +
      '    at MetroBundlerDevServer.resolveRelativePathAsync (<my_project_directory>\\node_modules\\@expo\\cli\\src\\start\\server\\metro\\MetroBundlerDevServer.ts:1204:12)\n' +   
      '    at MetroBundlerDevServer.metroLoadModuleContents (<my_project_directory>\\node_modules\\@expo\\cli\\src\\start\\server\\metro\\MetroBundlerDevServer.ts:429:35)\n' +     
      '    at MetroBundlerDevServer.legacySinglePageExportBundleAsync (<my_project_directory>\\node_modules\\@expo\\cli\\src\\start\\server\\metro\\MetroBundlerDevServer.ts:552:20)\n' +
      '    at <my_project_directory>\\node_modules\\@expo\\cli\\src\\export\\exportApp.ts:137:26\n' +
      '    at async Promise.all (index 0)\n' +
      '    at exportAppAsync (<my_project_directory>\\node_modules\\@expo\\cli\\src\\export\\exportApp.ts:127:7)\n'
  ],
  stdout: '\n' +
    'Expo Metro config:\n' +
    '- Version: 0.18.5\n' +
    '- Extensions: ts, tsx, mjs, js, jsx, json, cjs, scss, sass, css\n' +
    '- React Native: <my_project_directory>\\node_modules\\react-native\n' +
    '- Watch Folders: \n' +
    '- Node Module Paths: \n' +
    '- Env Files: .env.production.local,.env.local,.env.production,.env\n' +
    '- Sass: null\n' +
    '- Reanimated: 3.10.1\n' +
    '\n' +
    'Starting Metro Bundler\n',
  stderr: '2024-06-11T12:01:25.026Z expo:telemetry:detachedClient Event received: action\n' +
    '2024-06-11T12:01:25.520Z expo:env No environment variables loaded from .env files.\n' +
    '2024-06-11T12:01:25.552Z expo:telemetry:detachedClient Event received: Start Project\n' +
    '2024-06-11T12:01:25.557Z expo:start:server:devServer Stopping dev server (bundler: metro)\n' +
    '2024-06-11T12:01:25.557Z expo:start:server:devServer Stopped dev server (bundler: metro)\n' +
    '2024-06-11T12:01:25.574Z expo:start:server:metro:router Using app as the root directory for Expo Router.\n' +
    '2024-06-11T12:01:26.554Z expo:metro:config react-native-reanimated package.json: <my_project_directory>\\node_modules\\react-native-reanimated\\package.json\n' +
    '2024-06-11T12:01:27.676Z expo:start:server:metro:multi-platform Enabling alias: react-native-vector-icons -> @expo/vector-icons\n' +
    '2024-06-11T12:01:27.676Z expo:metro:withMetroResolvers Appending 5 custom resolvers to Metro config. (has custom resolver: false)\n' +
    '2024-06-11T12:01:27.683Z expo:telemetry:detachedClient Event received: metro config\n' +
    '2024-06-11T12:01:29.208Z expo:start:server:urlCreator URL: http://<my_local_ip>:8081\n' +
    '2024-06-11T12:01:29.545Z expo:start:server:middleware:serveStatic Serving static files from: <my_project_directory>\\public\n' +
    '2024-06-11T12:01:29.994Z expo:start:server:urlCreator URL: exp://<my_local_ip>:8081\n' +
    '2024-06-11T12:01:32.690Z expo:telemetry:detachedClient Actor received\n' +
    '2024-06-11T12:01:33.042Z expo:metro:options Disabling lazy bundling for export build\n' +
    '2024-06-11T12:01:33.045Z expo:metro:options Disabling lazy bundling for export build\n' +
    '2024-06-11T12:01:33.663Z expo:metro:withMetroResolvers Custom resolver threw: FailedToResolveNameError. (module: .\\node_modules\\expo\\AppEntry.js, platform: ios)\n' +
    '2024-06-11T12:01:33.696Z expo:metro:withMetroResolvers Custom resolver threw: FailedToResolveNameError. (module: .\\node_modules\\expo\\AppEntry.js, platform: ios)\n' +
    '2024-06-11T12:01:33.719Z expo:metro:withMetroResolvers Custom resolver threw: FailedToResolveNameError. (module: .\\node_modules\\expo\\AppEntry.js, platform: android)\n' +
    '2024-06-11T12:01:33.728Z expo:metro:withMetroResolvers Custom resolver threw: FailedToResolveNameError. (module: .\\node_modules\\expo\\AppEntry.js, platform: android)\n' +
    '2024-06-11T12:01:33.743Z expo:start:platforms:android:adbServer Stopping ADB server\n' +
    '2024-06-11T12:01:33.743Z expo:start:platforms:android:adbServer ADB server is not running\n' +
    '2024-06-11T12:01:33.998Z expo:start:server:devServer Stopping dev server (bundler: metro)\n' +
    '2024-06-11T12:01:34.000Z expo:start:server:devServer Stopped dev server (bundler: metro)\n' +
    'Error: Unable to resolve module .\\node_modules\\expo\\AppEntry.js from <my_project_directory>/.: .\\node_modules\\expo\\AppEntry.js could not be found within the project or in these directories:\n' +
    '  node_modules\n' +
    'Error: Unable to resolve module .\\node_modules\\expo\\AppEntry.js from <my_project_directory>/.: .\\node_modules\\expo\\AppEntry.js could not be found within the project or in these directories:\n' +
    '  node_modules\n' +
    '    at ModuleResolver.resolveDependency (<my_project_directory>\\node_modules\\metro\\src\\node-haste\\DependencyGraph\\ModuleResolution.js:138:15)\n' +
    '    at DependencyGraph.resolveDependency (<my_project_directory>\\node_modules\\metro\\src\\node-haste\\DependencyGraph.js:231:43)\n' +
    '    at <my_project_directory>\\node_modules\\metro\\src\\lib\\transformHelpers.js:156:21\n' +
    '    at Server._resolveRelativePath (<my_project_directory>\\node_modules\\metro\\src\\Server.js:1023:12)\n' +
    '    at MetroBundlerDevServer.resolveRelativePathAsync (<my_project_directory>\\node_modules\\@expo\\cli\\src\\start\\server\\metro\\MetroBundlerDevServer.ts:1204:12)\n' +     
    '    at MetroBundlerDevServer.metroLoadModuleContents (<my_project_directory>\\node_modules\\@expo\\cli\\src\\start\\server\\metro\\MetroBundlerDevServer.ts:429:35)\n' +       
    '    at MetroBundlerDevServer.legacySinglePageExportBundleAsync (<my_project_directory>\\node_modules\\@expo\\cli\\src\\start\\server\\metro\\MetroBundlerDevServer.ts:552:20)\n' +
    '    at <my_project_directory>\\node_modules\\@expo\\cli\\src\\export\\exportApp.ts:137:26\n' +
    '    at async Promise.all (index 0)\n' +
    '    at exportAppAsync (<my_project_directory>\\node_modules\\@expo\\cli\\src\\export\\exportApp.ts:127:7)\n',
  status: 1,
  signal: null
}
    Error: update command failed.

### Reproducible demo or steps to reproduce from a blank project

{
  "name": "demo-test",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@types/react-native-htmlview": "^0.16.4",
    "axios": "^1.6.2",
    "expo": "~51.0.9",
    "expo-image-picker": "~15.0.5",
    "expo-status-bar": "~1.12.1",
    "expo-updates": "~0.25.15",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.74.1",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-htmlview": "^0.17.0",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "6.3.0",
    "react-native-reanimated": "~3.10.1",
    "react-native-root-toast": "^3.5.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "react-native-tab-view": "^3.5.2",
    "react-redux": "^8.1.3",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2",
    "reselect": "^4.1.8"
  },
  "devDependencies": {
    "@babel/core": "^7.24.0",
    "@types/react": "~18.2.79",
    "@types/react-native": "~0.70.6",
    "typescript": "^5.3.3"
  },
  "private": true,
  "resolutions": {
    "@types/react": "~18.2.14",
    "@types/react-dom": "18.2.0"
  }
}

**Comment by jmoussu** [comment]
I have the same situation since today it's seems to be on windows 10 and 11 but not on mac

**Comment by stesvis** [comment]
Same here, from today:
```
[expo-cli] Error: Unable to resolve module .\node_modules\expo-router\entry.js from <my project>: .\node_modules\expo-router\entry.js could not be found within the project or in these directories:
[expo-cli]   node_modules
```
Versions:
```    "expo": "~51.0.8",
    "expo-asset": "~10.0.6",
    "expo-constants": "~16.0.2",
    "expo-image": "~1.12.11",
    "expo-linear-gradient": "~13.0.2",
    "expo-linking": "~6.3.1",
    "expo-localization": "~15.0.3",
    "expo-location": "~17.0.1",
    "expo-router": "~3.5.16",
    "expo-secure-store": "~13.0.1",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.6",
    "expo-updates": "~0.25.14",
```

**Comment by JayzeeHuang** [comment]
same. used to works fine, but now cannot eas update. Error: Unable to resolve module .\node_modules\expo\AppEntry.js

**Comment by Andycapn** [comment]
Same issue here, downgrading to 51.0.9 seems to fix it for me but introduces other issues.

**Comment by stesvis** [comment]
It's fixed with the latest update! `"expo": "~51.0.14"`

**Comment by Santa0727** [comment]
@stesvis  It works! Thank you very much! 😀

**Comment by stesvis** [comment]
> @stesvis It works! Thank you very much! 😀

All i did was to check expo doctor and see that there was an update :)
