### ISSUE TITLE
IOS local build fail - ARCHIVE FAILED 

### ISSUE THREAD

**Issue by tipleavalentin** [expo/eas-cli#2424]
### Summary

When I run "eas build --platform ios --local --clear-cache" I get this error at the end:
Error: Unable to resolve module /tmp/eas-ios/build/node_modules/expo/AppEntry.js from /private/tmp/eas-ios/build/.: 

None of these files exist:
  * ../../../../tmp/eas-ios/build/node_modules/expo/AppEntry.js(.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css)
  
If I skip dir cleanup I can see the file node_modules/expo/AppEntry.js is present so it should be fine.
Live development work with no issues.
Two weeks ago I managed to successfully build an .ipa file, now it's not working. :(

### Managed or bare?

bare

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.14.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.8.1 - /usr/local/bin/npm
      Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11926650
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.1 => 19.0.1 
      expo: ^51.0.13 => 51.0.13 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
      react-native-web: ~0.19.11 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.2.0
    Expo Workflow: managed

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Error: Problem validating fields in /Users/vtiplea/Public/Projects/mobile/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: android - should NOT have additional property 'useNextNotificationsApi'.

### Error output

From terminal:
 (1 failure)
[RUN_FASTLANE] ** ARCHIVE FAILED **
[RUN_FASTLANE] 
[RUN_FASTLANE] 
[RUN_FASTLANE] The following build commands failed:
[RUN_FASTLANE]  PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/vtiplea/Library/Developer/Xcode/DerivedData/Mobile-bxregnhwofiiuqadqaxzzwveacvs/Build/Intermediates.noindex/ArchiveIntermediates/Mobile/IntermediateBuildFilesPath/Mobile.build/Release-iphoneos/Mobile.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'Mobile' from project 'Mobile')
[RUN_FASTLANE] (1 failure)
[RUN_FASTLANE] Exit status: 65

From logs:

Starting Metro Bundler
warning: Bundler cache is empty, rebuilding (this may take a minute)
/private/tmp/eas-ios/build/.:0: error: Unable to resolve module /tmp/eas-ios/build/node_modules/expo/AppEntry.js from /private/tmp/eas-ios/build/.: 
Error: Unable to resolve module /tmp/eas-ios/build/node_modules/expo/AppEntry.js from /private/tmp/eas-ios/build/.: 

None of these files exist:
  * ../../../../tmp/eas-ios/build/node_modules/expo/AppEntry.js(.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.mjs|.native.mjs|.mjs|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.cjs|.native.cjs|.cjs|.ios.scss|.native.scss|.scss|.ios.sass|.native.sass|.sass|.ios.css|.native.css|.css)

### Reproducible demo or steps to reproduce from a blank project

eas build --platform ios --local --clear-cache

**Comment by ahmad-elafify-pci** [comment]
I am also facing this issue, posted about it in the discord and had only seen 2 people post about it in the discord and received no response.

**Comment by tipleavalentin** [comment]
> I am also facing this issue, posted about it in the discord and had only seen 2 people post about it and received no response.

Hi!
I updated the expo package to 51.0.14 and I tried again the build.
Luckily it worked just fine now.

**Comment by szdziedzic** [comment]
>Hi!
I updated the expo package to 51.0.14 and I tried again the build.
Luckily it worked just fine now.

Good to hear it! @ahmad-elafify-pci did it also help you?

**Comment by ahmad-elafify-pci** [comment]
> > Hi!
> > I updated the expo package to 51.0.14 and I tried again the build.
> > Luckily it worked just fine now.
> 
> Good to hear it! @ahmad-elafify-pci did it also help you?

Same here! Today I did an expo-doctor and an `npx expo install --fix` which installed these dependencies: 
```
  expo@51.0.13 - expected version: ~51.0.14
  expo-camera@15.0.10 - expected version: ~15.0.11
  expo-dev-client@4.0.17 - expected version: ~4.0.18
  expo-image@1.12.11 - expected version: ~1.12.12
  expo-updates@0.25.16 - expected version: ~0.25.17
```

After that completed, I was able to finally build for ios again using eas build --local!  🎉

**Comment by szdziedzic** [comment]
Awesome!
