### ISSUE TITLE
react-native-element and react-native-paper icons no longer showing in eas build

### ISSUE THREAD

**Issue by VCSJacob** [expo/eas-cli#2427]
### Build/Submit details page URL

https://expo.dev/accounts/vcs-jacob/projects/VCS/builds/3ea8e2f2-f5aa-4a85-a264-1ca64d0c069e

### Summary

I have several components that use react-native-paper IconButtons and react-native-element Icon components. The Icons and Buttons render perfectly fine in expo-go. I have made several builds of my app and the icons always rendered, but as of today no Icons are rendered on the build of the app. Even when I download a past build where the icons showed, they are no longer there.

### Managed or bare?

Managed

### Environment

npx expo start

### Error output

No errors are shown

### Reproducible demo or steps to reproduce from a blank project

eas build

**Comment by szdziedzic** [comment]
can you see the icons when you do `npx expo run:ios` or `npx expo run:android`?

**Comment by VCSJacob** [comment]
Yes, the icons are rendered correctly when I run `npx expo run:android`, but they are not there when I install the eas build version

**Comment by VCSJacob** [comment]
I ran npx `expo prebuild` before I used eas build and the issue was gone, the icons rendered.

**Comment by VCSJacob** [comment]
The issue has came back, icons renders with expo-dev-client build but not with eas build
