### ISSUE TITLE
EAS devlopment-simulator build failing on IOS

### ISSUE THREAD

**Issue by DinShpati** [expo/eas-cli#2454]
### Build/Submit details page URL

https://expo.dev/accounts/dinshpati/projects/barnacleAI/builds/03c6cc37-87e1-4c89-9158-1cc1d48e3238

### Summary

Hello team,

My app is failing when trying to build on the IOS simulator:

I run the following command and it fails in the fastline
eas build --profile development-simulator --platform ios

Error:
error: unknown command 'generate-modules-provider'. See ' --help'.

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » project/project » Build Phases » 'Start Packager'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script
⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » project/project » Build Phases » 'Bundle React Native code and images'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script
   
   Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.

Using:  "expo": "^49.0.11"

Please let me know if anymore info is needed.

Thanks

### Managed or bare?

Managed

### Environment

  npx expo-env-info
  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.1 - /opt/homebrew/bin/node
      npm: 10.5.0 - /opt/homebrew/bin/npm
      Watchman: 2024.03.25.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: ^49.0.11 => 49.0.11 
      react: 18.2.0 => 18.2.0 
      react-native: 0.72.10 => 0.72.10 
    npmGlobalPackages:
      eas-cli: 10.1.1
      expo-cli: 6.3.10
    Expo Workflow: managed
    
    
    npx expo-doctor
    ✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

Detailed check results:

Expected package expo-modules-autolinking@~1.5.0
Found invalid:
  expo-modules-autolinking@1.11.1
  (for more info, run: npm why expo-modules-autolinking)
Advice: Upgrade dependencies that are using the invalid package versions0.

One or more checks failed, indicating possible issues with the project.
    
    

### Error output

error: unknown command 'generate-modules-provider'. See ' --help'.

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » project/project » Build Phases » 'Start Packager'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script
⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » project/project » Build Phases » 'Bundle React Native code and images'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script
   
   Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.

### Reproducible demo or steps to reproduce from a blank project

eas build --profile development-simulator --platform ios

**Comment by szdziedzic** [comment]
Hi, can you try to fix issues highlighted by the `expo-doctor` during the build process?

```
Expected package expo-modules-autolinking@~1.5.0
Found invalid:
  expo-modules-autolinking@1.11.1
```

**Comment by DinShpati** [comment]
Had to uninstall and re-install the NPM modules and that updated a couple other ones and that seemed to fix it!
Thank you!

**Comment by tjdibbs** [comment]
update @expo/config to latest version - This works for me...
