### ISSUE TITLE
expo 51 SwiftCompile normal arm64 Compiling Failing on iOS

### ISSUE THREAD

**Issue by Janendran** [expo/eas-cli#2457]
### Summary

SwiftCompile normal arm64 Compiling\ noop-file.swift

### Managed or bare?

Managed

### Environment

System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.4.1 - /opt/homebrew/bin/node
      Yarn: 1.22.19 - /opt/homebrew/bin/yarn
      npm: 10.8.1 - /opt/homebrew/bin/npm
      Watchman: 2024.07.08.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2021.2 AI-212.5712.43.2112.8815526
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.0 => 51.0.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.6 => 0.19.10 
    npmGlobalPackages:
      eas-cli: 10.1.1
    Expo Workflow: bare

### Error output

[RUN_FASTLANE] ▸ ** ARCHIVE FAILED **
[RUN_FASTLANE] ▸ The following build commands failed:
[RUN_FASTLANE] ▸ 	SwiftCompile normal arm64 Compiling\ noop-file.swift /var/folders/xr/37snnd7d1275sdjnphp8p28c0000gn/T/eas-build-local-nodejs/9729f3db-6d12-46d4-aa00-c1cfd59002fd/build/iOS/xxx/noop-file.swift (in target 'xxx' from project 'xxx')
[RUN_FASTLANE] ▸ 	SwiftCompile normal arm64 /var/folders/xr/37snnd7d1275sdjnphp8p28c0000gn/T/eas-build-local-nodejs/9729f3db-6d12-46d4-aa00-c1cfd59002fd/build/iOS/xxx/noop-file.swift (in target 'xxx' from project 'xxx')
[RUN_FASTLANE] ▸ 	SwiftCompile normal arm64 /Users/xxx/Library/Developer/Xcode/DerivedData/xxx-fynpvwcehmfobngujoedeivujnxz/Build/Intermediates.noindex/ArchiveIntermediates/xxx/IntermediateBuildFilesPath/xxx.build/Release-iphoneos/xxx.build/DerivedSources/GeneratedAssetSymbols.swift (in target 'xxx' from project 'xxx')
[RUN_FASTLANE] ▸ 	SwiftCompile normal arm64 /var/folders/xr/37snnd7d1275sdjnphp8p28c0000gn/T/eas-build-local-nodejs/9729f3db-6d12-46d4-aa00-c1cfd59002fd/build/ios/Pods/Target\ Support\ Files/Pods-xxx/ExpoModulesProvider.swift (in target 'xxx' from project 'xxx')
[RUN_FASTLANE] ▸ (4 failures)
[RUN_FASTLANE] ** ARCHIVE FAILED **

### Reproducible demo or steps to reproduce from a blank project

eas build --platform ios --local

**Comment by szdziedzic** [comment]
Can you use `EAS_LOCAL_BUILD_SKIP_CLEANUP=1` and `EAS_LOCAL_BUILD_WORKINGDIR` variables to try to get to the Xcode logs and check if there is something useful in them?

 https://docs.expo.dev/build-reference/local-builds/

**Comment by Janendran** [comment]
@szdziedzic thanks, I can't see anything wrong in the Xcode logs, and I see the same error message as the console log.

I removed the noop-file.swift and ExpoModulesProvider.swift from the Compile sources, and I can build successfully from Xcode. 

<img width="707" alt="Screenshot 2024-07-15 at 18 41 14" src="https://github.com/user-attachments/assets/fae22fb8-f5aa-4bd0-8631-0dd6cc9ef07a">

**Comment by szdziedzic** [comment]
Hi,

Is there a chance you can set up a minimal reproducible example, please? It's harder for me to help you without it.

What is the output of `npx expo-doctor@latest` for you? You mentioned that you are on managed workflow, but it seems like you have `ios` directory in your project. Is there a chance that your `ios` directory is malformed when running `npx expo prebuild` during the build? Can you check the prebuild logs?

**Comment by Janendran** [comment]
npx expo-doctor@latest                               
(node:96081) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Warning: Root-level "expo" object found. Ignoring extra keys in Expo config: "name", "displayName", "ignite"
Learn more: https://expo.fyi/root-expo-object
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check that packages match versions required by installed Expo SDK

**Comment by Janendran** [comment]
@szdziedzic could you please help me with this?

**Comment by mrevanzak** [comment]
how did you solve this

**Comment by Nantris** [comment]
Same issue on SDK 52, only after moving from Intel-based Mac to a Silicon M2.

Whoops forgot I'm on a newer XCode version. Upgrading to `expo-localization@16.1.5` fixed this. Unfortunately it broke Android.
