### ISSUE TITLE
Allow apk and ipa download using the CLI

### ISSUE THREAD

**Issue by mauro-codes** [expo/eas-cli#246]
I'm integrating `eas build` on my build pipeline on Azure. 

My goal is to build the apk using `eas build` and then save the artifact so the QA can access it from Azure. 

I didn't find any way to download the apk using the CLI. It would be really useful to be able to download the apk or the ipa file for CI/CD pipelines that rely on artifacts.

**Comment by brentvatne** [comment]
you can run `eas build:view <build-id>` to get the build artifact url when the build is complete, or if you want for the build to complete after running `eas build` the artifact url will be printed. does this handle your needs?

**Comment by mauro-codes** [comment]
Hi Brent! Thanks for your feedback. Getting the artifact URL after the build seems to be a good step in the right direction. I think I can work with that. Thanks for taking the time to respond.

**Comment by brentvatne** [comment]
we would consider having a flag to output the result as json to make it easier to parse if you wanted to open a pr for this

**Comment by luyx2412** [comment]
Hi Brentvatne, Can you guide me on how can I copy the URL when finish run "eas build". Because I need the URL to send via email or use for another case.

Thanks
