### ISSUE TITLE
Execution failed for task ':react-native-community_art:compileDebugJavaWithJavac' when to try build android after update to 51 sdk

### ISSUE THREAD

**Issue by JackCat1** [expo/eas-cli#2462]
### Build/Submit details page URL

https://expo.dev/accounts/jackcat1/projects/cckzMApp/builds/303734f0-fccd-429c-93e2-1f784b3f1630

### Summary

After updating the SDK to version 51, it is not possible to build for development

### Managed or bare?

Managed

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045
    Binaries:
      Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
      npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-241.18034.62.2411.12071903
    npmPackages:
      babel-preset-expo: ~11.0.0 => 11.0.12
      expo: ~51.0.21 => 51.0.21
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.3 => 0.74.3
      react-native-web: ~0.19.6 => 0.19.12
    Expo Workflow: managed

WARNING: We recommend using PowerShell or Bash via WSL 2 for development with Expo CLI on Windows. You may encounter issues using cmd.exe.

✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

### Error output

> Task :app:processDebugMainManifest
/home/expo/workingdir/build/android/app/src/debug/AndroidManifest.xml:6:5-162 Warning:
	application@android:usesCleartextTraffic was tagged at AndroidManifest.xml:6 to replace other declarations but no other declaration present
/home/expo/workingdir/build/android/app/src/debug/AndroidManifest.xml Warning:
	provider#expo.modules.filesystem.FileSystemFileProvider@android:authorities was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present
> Task :app:processDebugManifest
> Task :app:processDebugManifestForPackage
> Task :react-native-community_art:compileDebugJavaWithJavac
/home/expo/workingdir/build/node_modules/@react-native-community/art/android/src/main/java/com/reactnativecommunity/art/ARTShapeShadowNode.java:25: error: cannot find symbol
import static com.facebook.react.common.ArrayUtils.copyArray;
                                       ^
  symbol:   class ArrayUtils
  location: package com.facebook.react.common
/home/expo/workingdir/build/node_modules/@react-native-community/art/android/src/main/java/com/reactnativecommunity/art/ARTShapeShadowNode.java:25: error: static import only from classes and interfaces
import static com.facebook.react.common.ArrayUtils.copyArray;
^
Note: /home/expo/workingdir/build/node_modules/@react-native-community/art/android/src/main/java/com/reactnativecommunity/art/ARTGroupShadowNode.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
/home/expo/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java:84: warning: [removal] onCatalystInstanceDestroy() in NativeModule has been deprecated and marked for removal
  public void onCatalystInstanceDestroy() {
              ^
> Task :react-native-community_art:compileDebugJavaWithJavac FAILED
> Task :react-native-async-storage_async-storage:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/expo/workingdir/build/node_modules/@react-native-async-storage/async-storage/android/src/javaPackage/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
> Task :app:processDebugResources
> Task :expo-modules-core:compileDebugKotlin
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:20:26 'Promise' is deprecated. AsyncFunction will crash when called. Use expo.modules.kotlin.Promise instead
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:63:51 'Promise' is deprecated. AsyncFunction will crash when called. Use expo.modules.kotlin.Promise instead
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:90:54 'Promise' is deprecated. AsyncFunction will crash when called. Use expo.modules.kotlin.Promise instead
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/defaultmodules/CoreModule.kt:6:34 'ReactFeatureFlags' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/defaultmodules/CoreModule.kt:71:12 'ReactFeatureFlags' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/events/KModuleEventEmitterWrapper.kt:97:7 'constructor Event<T : Event<(raw) Event<*>>!>(Int)' is deprecated. Deprecated in Java
w: file:///home/expo/workingdir/build/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverterHelper.kt:44:17 'get(String!): Any?' is deprecated. Deprecated in Java
FAILURE:
Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-community_art:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by Lyubomir-Stavrev-Dev** [comment]
Hello I can't see that the issue is closed, how did you maneged to fix the issue as I have the same ?

**Comment by JackCat1** [comment]
I removed "react-native-community_art" lib.

**Comment by HasanKhan999** [comment]
If someone is still facing this, just comment out the line

`import static com.facebook.react.common.ArrayUtils.copyArray;`

in the directory

`node_modules/@react-native-community/art/android/src/main/java/com/reactnativecommunity/art/ARTShapeShadowNode.java`

**Comment by abikali** [comment]
Hey, I'm facing the exact same error.
How did you manage to fix it?

**Comment by ashishAmz** [comment]
Hi, I am facing this issue, is it resolved?

**Comment by il4mb** [comment]
i had same issue, i remove pakage and it fix
