### ISSUE TITLE
EAS builds crashing with 'bun install ' SIGTRAP

### ISSUE THREAD

**Issue by imattaai** [expo/eas-cli#2471]
### Build/Submit details page URL

https://expo.dev/accounts/jdevelopit/projects/taskn-mobile/builds/fa9c44ec-eea7-4bdf-9a20-10a7fed40fb5

### Summary

How can we reproduce the crash?
Create a production build through EAS.
Assuming your project uses bun:
my local builds work:

eas build --platform ios
I'm on Expo 49 but builds were not an issue until this

Relevant log output
Running "bun install" in /Users/expo/workingdir/build directory
bun install v1.1.13 (bd6a6051)
============================================================
Bun v1.1.13 (bd6a6051) macOS Silicon
Args: "bun" "install"
Elapsed: 56ms | User: 18ms | Sys: 18ms
RSS:
29.66MB | Peak: 29.66MB | Commit: 1.07GB | Faults: 677
panic(main thread): Segmentation fault at address 0xAA5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
bun install exited with signal: SIGTRAP
Stack Trace (bun.report)
Bun v1.1.13 ([bd6a605](https://github.com/oven-sh/bun/tree/bd6a6051203ff577240615ff4e242270035a36b7)) on macos aarch64 [InstallCommand]

Segmentation fault at address 0x00000AA5

2 unknown/js code
src.install.install.PackageManager.PackageInstaller.installPackage__anon_86684
src.install.install.PackageManager.installPackages__anon_86680
src.install.install.PackageManager.installWithManager__anon_86666
src.cli.install_command.InstallCommand.exec
src.cli.Cli.start
main
2 unknown/js code

### Managed or bare?

bare

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 17.9.1 - ~/.nvm/versions/node/v17.9.1/bin/node
      npm: 8.11.0 - ~/.nvm/versions/node/v17.9.1/bin/npm
      Watchman: 2024.05.06.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.10121639
      Xcode: 14.3/14E222b - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^19.0.0 => 19.0.0 
      expo: ^49.0.0 => 49.0.21 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.72.7 => 0.72.7 
      react-native-web: ~0.19.6 => 0.19.9 
    npmGlobalPackages:
      eas-cli: 9.0.3
    Expo Workflow: bare

### Error output

Running "bun install" in /Users/expo/workingdir/build directory
bun install v1.1.13 (bd6a6051)
============================================================
Bun v1.1.13 (bd6a6051) macOS Silicon
Args: "bun" "install"
Elapsed: 56ms | User: 18ms | Sys: 18ms
RSS:
29.66MB | Peak: 29.66MB | Commit: 1.07GB | Faults: 677
panic(main thread): Segmentation fault at address 0xAA5
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
https://bun.report/1.1.13/Mi1bd6a605AA__urqzD2/4yDm431Dm9s9Dmw3B2tqB__A2AqqF
bun install exited with signal: SIGTRAP

### Reproducible demo or steps to reproduce from a blank project

Try to build for expo with bun installed?

eas build --platform ios

See crash error?
I believe bun needs to be upgraded in pipeline. 

See https://github.com/oven-sh/bun/issues/12820

**Comment by szdziedzic** [comment]
Hi @imattaai,

I see that in the [issue reported in the Bun repo](https://github.com/oven-sh/bun/issues/12820) Jarred suggested using Bun v1.20.0. To do so, you can specify `"1.20.0"` as a value in the [`bun` field in your `eas.json` file](https://docs.expo.dev/eas/json/#bun). Can you try if it works for you?

**Comment by imattaai** [comment]
No luck here, I've tried different versions including 1.20.0 and latest here.
The pipeline keeps crashing and not offering me enough details,

My local builds are working with 
"eas build --profile production --platform ios --local" v(1.1.13),

In eas.json
```
"production": {
      "channel": "production",
      "bun": "1.1.25"
    }
```
    
```
Running "bun install" in /Users/expo/workingdir/build directory
bun install v1.1.25 (fe62a614)
============================================================
Bun v1.1.25 (fe62a614) macOS Silicon
macOS v14.5
Args: "bun"
"install"
Features: extracted_packages(18) 
Elapsed: 490ms | User: 210ms | Sys: 239ms
RSS: 86.41MB | Peak: 86.41MB | Commit: 1.07GB | Faults: 235
panic: Bus error at address 0x4AEB8BE496A
oh no: Bun has crashed. This indicates a bug in Bun, not your code.
To send a redacted crash report to Bun's team,
please file a GitHub issue using the link below:
 https://bun.report/1.1.25/Mi1fe62a61AggB__+2vzY__A48qCtp7monC
bun install exited with signal: SIGTRAP
```
