### ISSUE TITLE
Authentication with Apple Developer Portal failed!

### ISSUE THREAD

**Issue by vishnugautam-jv** [expo/eas-cli#2475]
### Summary

My friend has an Apple developer account set up and he grant me admin access. When i tried to build the project using EAS I get the following error. My eas cli version is eas-cli/10.2.1 darwin-arm64 node-v22.4.0

### Managed or bare?

bare

### Environment

 ✔Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that native modules use compatible support package versions for installed Expo SDK
✖ Check that packages match versions required by installed Expo SDK

Detailed check results:

(node:6538) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following packages should be updated for best compatibility with the installed expo version:
  expo@51.0.22 - expected version: ~51.0.23
  expo-dev-client@4.0.20 - expected version: ~4.0.21
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

One or more checks failed, indicating possible issues with the project.

### Error output

```Authentication with Apple Developer Portal failed!
You have no team associated with your Apple account, cannot proceed.
(Do you have a paid Apple Developer account?)
    Error: build command failed.``` 

### Reproducible demo or steps to reproduce from a blank project

expo login
expo build:configure
expo build --platform ios
package.json is 
```{
  "name": "jvchatapp-frontend",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest"
  },
  "jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)"
    ]
  },

  "dependencies": {
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.10.1",
    "@stomp/stompjs": "^7.0.0",
    "@types/react": "~18.2.79",
    "axios": "^1.7.2",
    "expo": "~51.0.22",
    "expo-av": "^14.0.6",
    "expo-dev-client": "~4.0.20",
    "expo-document-picker": "^12.0.2",
    "expo-file-system": "^17.0.1",
    "expo-image-picker": "^15.0.7",
    "expo-status-bar": "~1.12.1",
    "react": "18.2.0",
    "react-native": "0.74.3",
    "react-native-gifted-chat": "^2.4.0",
    "react-native-paper": "^5.12.3",
    "react-native-paper-dropdown": "^2.1.0",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-video": "^6.4.3",
    "react-test-renderer": "^18.2.0",
    "socket.io-client": "^4.7.5",
    "sockjs-client": "^1.6.1",
    "stompjs": "^2.3.3",
    "text-encoding": "^0.7.0",
    "typescript": "~5.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "jest": "^29.7.0",
    "jest-expo": "^51.0.3"
  },
  "private": true
}
```

**Comment by szdziedzic** [comment]
Could you verify that the Apple Account that you are using is paid and up-to-date?

**Comment by vishnugautam-jv** [comment]
> Could you verify that the Apple Account that you are using is paid and up-to-date?

Yes our account is paid and up to date. Do you want any more details?

**Comment by szdziedzic** [comment]
Interesting, it seems like it can be the same issue as https://github.com/expo/eas-cli/issues/1805#issuecomment-1520064035 🤔 

It seems like it's a bug on Apple's end because it seems like their API is not returning any teams when authenticating with a non-owner subaccount 🤔

**Comment by vishnugautam-jv** [comment]
> Interesting, it seems like it can be the same issue as [#1805 (comment)](https://github.com/expo/eas-cli/issues/1805#issuecomment-1520064035) 🤔
> 
> It seems like it's a bug on Apple's end because it seems like their API is not returning any teams when authenticating with a non-owner subaccount 🤔

ya right. I will try to do it with the actual account owner credentials. I will keep you posted.

**Comment by ProjectProgramAMark** [comment]
hello! do we have any updates on this? still running into this issue

**Comment by szdziedzic** [comment]
@vishnugautam-jv did trying actual account owner credentials help you?

**Comment by ProjectProgramAMark** [comment]
it's not been completed, we've still got this issue

**Comment by MilanBarande** [comment]
Encountering the same issue but this is on Apple's side from what I understood

**Comment by JCcastagne** [comment]
Issue remains.

**Comment by cryyram** [comment]
Same, it works for submitting when you add the ascApiKey* fields to ios, but for just building locally for example `eas build --platform ios --local`, it still fails.
