### ISSUE TITLE
"Install dependencies" phase takes longer then expected error eas build android

### ISSUE THREAD

**Issue by sabaturgay** [expo/eas-cli#2480]
### Summary

I use bun to install the dependencies, there were no issues with that on July 24. The install was taking 30 sec, then suddenly it started to take 10 min for IOS builds and more than 30 min (which is failing the build) for android after July 25. There were no changes in dependencies in this period. Please let me know if you need more info. Thanks in advance. 
Current environment:
eas-cli:  10.2.1
bun: 1.1.21

### Managed or bare?

Managed

### Environment

 expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.10.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 10.2.3 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2022.2 AI-222.4459.24.2221.9971841
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~11.0.0 => 11.0.12 
      expo: 51.0.22 => 51.0.22 
      expo-router: ~3.5.16 => 3.5.20 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.3 => 0.74.3 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 10.2.2
    Expo Workflow: managed
   
## npx expo-doctor:
  ✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check native tooling versions
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check for issues with metro config
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

The following packages should be updated for best compatibility with the installed expo version:
  expo@51.0.22 - expected version: ~51.0.24
  typescript@5.5.2 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

### Error output

`Running "bun install" in /home/expo/workingdir/build/packages/chatlok directory
bun install v1.1.21 (70ca2b76)
Resolving dependencies
Resolved, downloaded and extracted [2]
"Install dependencies" phase takes longer then expected and it did not produce any logs in the past 15 minutes. Consider evaluating your package.json file for possible issues with dependencies
"Install dependencies" phase takes a very long time and it did not produce any logs in the past 30 minutes. Most likely an unexpected error happened with your dependencies which caused the process to hang and it will be terminated
"Install dependencies" phase was inactive for over 30 minutes. Please evaluate your package.json file`

### Reproducible demo or steps to reproduce from a blank project

bun v1.1.21 install step on android build is stuck. Same for yarn install

**Comment by szdziedzic** [comment]
Hi, I have a few questions:
1. Are you using cloud or local builds?
2. If you are using cloud builds, are you setting a custom [`bun` version in your `eas.json` file](https://docs.expo.dev/eas/json/#bun) matching your local version? The `bun` version installed on EAS builders may vary depending on what image you use: https://docs.expo.dev/build-reference/infrastructure/#android-server-images.

**Comment by sabaturgay** [comment]
Hello,

I use cloud builds and have ensured that the bun version in my eas.json configuration matches my local version. I've gathered some details from both the last successful build and the recent failed builds (both for android):
both have Intel, 4 vCPUs, 16 GB RAM
## Succeeded build env 
```
Using image "ubuntu-22.04-jdk-17-ndk-26.1.10909125" based on "ubuntu-2204-jammy-v20240614"
Installed software:
- NDK 26.1.10909125
- Node.js 18.18.0
- Bun 1.1.13
- Yarn 1.22.21
- pnpm 9.3.0
- npm 9.8.1
- Java 17
- node-gyp 10.1.0
Resolved builder image to 'sdk-51'.
```
### Custom tool installs:
`Installing bun@1.1.8`

## Failed build env 
```
Using image "ubuntu-22.04-jdk-17-ndk-26.1.10909125" based on "ubuntu-2204-jammy-v20240614"
Installed software:
- NDK 26.1.10909125
- Node.js 18.18.0
- Bun 1.1.13
- Yarn 1.22.21
- pnpm 9.3.0
- npm 9.8.1
- Java 17
- node-gyp 10.1.0
Resolved builder image to 'sdk-51'.
```
### Custom tool installs:
`Installing bun@1.1.8`

I've tried using bun install --yarn and then removed the bun.lock file to test with Yarn, but I'm still encountering issues. I also switched to the 'latest' Docker image, but that didn't resolve the problem either. This issue isn't limited to Android builds; it's also affecting iOS builds. Previously, the iOS build's dependency installation step took a maximum of 50 seconds, but now it's taking up to 10 minutes.

**Comment by szdziedzic** [comment]
@sabaturgay You mentioned that your current environment on your local machine is `bun: 1.1.21`. Can you use the same version on EAS servers instead of `1.1.8` and check if it helps?

**Comment by sabaturgay** [comment]
@szdziedzic tested as you mentioned, the taken steps:
- remove bun.lockb
- install bun@1.1.8
- install deps again and create bun.lockb
- update eas.json to have bun@1.1.8
Unfortunately, I am experiencing the same issue

**Comment by szdziedzic** [comment]
@sabaturgay Can you send me a link to your builds? Can you send me your `package.json` + `bun.lockb` as well?

**Comment by sabaturgay** [comment]
@szdziedzic I have invited you to a repo which I have shared all the needed info. Thanks in advance for helping.

**Comment by itajenglish** [comment]
I am also experiencing the same thing but I don’t use bun. Oddly enough my internal builds seem to work but my Play Store builds are failing with the same error. This currently blocking my Prod app releases for Android.

**Comment by szdziedzic** [comment]
@sabaturgay I'm not sure what's going on here, but I ran the install dependencies phase on EAS Build for your `package.json` + `bun.lockb` and it took 22s 🤔 
<img width="955" alt="Screenshot 2024-08-13 at 16 57 19" src="https://github.com/user-attachments/assets/52eab466-1ab9-43ee-8ace-29b2625156e4">

https://github.com/sabaturgay/share-code/pull/1/files - This is how I run it

**Comment by szdziedzic** [comment]
Amount of packages installed is slightly more in my build:
```
2891 packages installed [22.01s]
```
vs your build:
```
2882 packages installed [646.73s]
```

There are also different amounts of blocked post installs
```
Blocked 12 postinstalls. Run `bun pm untrusted` for details.
```
vs
```
Blocked 8 postinstalls. Run `bun pm untrusted` for details.
```

**Comment by szdziedzic** [comment]
I see that you run

```
Script 'eas-build-pre-install' is present in package.json, running it...
yarn run v1.22.21
$ cd ../../ && node tools/scripts/eas-build-pre-install.mjs . packages/chatlok && cp bun.lockb packages/chatlok
Done in 0.12s.
```

in your preinstall hook 🤔 

Maybe this is causing some issues?

**Comment by szdziedzic** [comment]
Can you try to run `bun install --verbose` in your pre-install hook so we can see more output?

**Comment by sabaturgay** [comment]
Hey,
bun install --verbose was a good idea, just detected the install is stuck on puppeteer postinstall (while downloading chrome). I have upgraded puppeteer from v21 to v23 and it is resolved. Thanks for your help.
