### ISSUE TITLE
EAS build its failing

### ISSUE THREAD

**Issue by nicoleRss** [expo/eas-cli#2483]
### Build/Submit details page URL

https://expo.dev/accounts/teamcore

### Summary

When trying to run `eas build -p ios --profile preview ` and `eas build -p android --profile preview` command is failing on prebuild step. The project has custom build with the following configuration:

![Captura de pantalla 2024-08-07 a la(s) 12 35 07 p m](https://github.com/user-attachments/assets/d3ac9e55-a187-4a47-89f2-1299bd25d5e7)

![Captura de pantalla 2024-08-07 a la(s) 12 36 56 p m](https://github.com/user-attachments/assets/e03a95bb-4a61-4f21-a470-8f120c5ac196)

IOS URL
https://expo.dev/accounts/teamcore/projects/teamcorev3/builds/62683938-f1eb-4f83-ae19-19951b0ff20e

Android URL
https://expo.dev/accounts/teamcore/projects/teamcorev3/builds/32447b49-9242-4a5f-99cb-2dc948df872d

### Managed or bare?

bare

### Environment

`expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
      npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.24 => 51.0.24 
      react: 17.0.2 => 17.0.2 
      react-native: 0.67.4 => 0.67.4 
      react-navigation: ^4.4.3 => 4.4.4 
    npmGlobalPackages:
      eas-cli: 10.2.2
    Expo Workflow: bare`

![Captura de pantalla 2024-08-07 a la(s) 12 44 17 p m](https://github.com/user-attachments/assets/faf86817-3cf9-4281-8edc-72a43b2914c6)

### Reproducible demo or steps to reproduce from a blank project

npm install -g eas-cli

eas login

eas build:configure

eas build -p android --profile preview

**Comment by Janendran** [comment]
you need to run "npx expo install --check"

**Comment by szdziedzic** [comment]
Hi @nicoleRss,

Can you try creating a `.npmrc` file in the project root directory with:
```
legacy-peer-deps=true 
```
?
