### ISSUE TITLE
[expo-updates] Use `--profile` in `fingerprint:generate` and `runtimeversion:resolve` to fetch related environment variables

### ISSUE THREAD

**Issue by tfcornerstone** [expo/eas-cli#2484]
### Summary

Currently when using `eas build`, the local fingerprint uploaded to EAS is different from the output of `expo-updates fingerprint:generate` locally. The reason for this is the difference in env variables. No reason to maintain environment variables in different places when it can be read from the `eas.json` profile. 

### What platform(s) does this occur on?

Android, iOS

### SDK Version

51.0.0

### Environment

N/A

### Minimal reproducible example

Try to build using EAS with environment variables and compare the fingerprint to normal `expo-updates` fingerprint

**Comment by Kudo** [comment]
hi there! could you share your build id? e.g. https://expo.dev/accounts/XXX/projects/XXX/builds/ee1bad22-a2c6-4c10-8ef2-281ea15980ee, the ee1bad22-a2c6-4c10-8ef2-281ea15980ee is the build id.

**Comment by tfcornerstone** [comment]
@Kudo 

2baa711b-ff01-4229-ab24-fdf4f7ebd9c8

I resolved the issue by setting the env variables of local to match the env variables in `eas.json` production profile.

**Comment by mirague** [comment]
This sounds like a pretty good addition, or is there a more "eas"-like way to achieve this?

**Comment by mirague** [comment]
@Kudo any more insights or initiatives planned to align fingerprints between local and cloud builds?

**Comment by Kudo** [comment]
@mirague ideally local/cloud fingerprint should be aligned. would love to hear your use cases and figure out how fingerprint is inconsistent between local and cloud

**Comment by jonsherrard** [comment]
@Kudo  running into a wall with this, want to commit a fingerprint.json locally, but that seems to be modified in many ways by things like APP_VARIANT differences in the iosIdentifier, and then `eas env:exec --non-interactive preview "npx expo-updates fingerprint:generate --platform ios  --debug` for example (used in github actions) generates totally different runtime fingerprints to `yarn dlx -q @expo/fingerprint fingerprint:generate > fingerprint.json` - the latter seems to be platform agnostic and the former requires a platform parameter.
