### ISSUE TITLE
CAn't install was cli

### ISSUE THREAD

**Issue by Babster** [expo/eas-cli#2486]
### Summary

I'm new to Mac dev, bought new computer and follow official site instructions starting from react native.dev and following to docs.expo.dev.
there are issues on almost every step and the below I couldn't solve.

ossuser@Mac-mini-MACbook ~ % npm install -g eas-cli
npm warn deprecated osenv@0.1.5: This package is no longer supported.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.4.5: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @oclif/screen@3.0.8: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated glob@6.0.4: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported

changed 414 packages in 35s

39 packages are looking for funding
  run ⁠ npm fund ⁠ for details
ossuser@Mac-mini-MACbook ~ % eas login
zsh: command not found: eas

### Managed or bare?

don't know what it is

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.16.0 - /usr/local/bin/node
      npm: 10.8.1 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 10.2.2

### Error output

it's above

### Reproducible demo or steps to reproduce from a blank project

just buy new computer and try to install your soft on it

**Comment by szdziedzic** [comment]
How did you install Node and npm? It seems like the issue is that binaries installed by npm (like `eas`) aren't in your PATH, so it seems like something is wrong with your Node/npm setup.

I personally use [volta](https://volta.sh/) as my node version manager, but [nvm](https://github.com/nvm-sh/nvm) is also a super popular (or even more popular) choice. Would you mind trying one of these tools? I believe that once you set up your node version using them, everything should be prepared correctly and npm binaries should be in your PATH.

**Comment by zaazbb** [comment]
I met the same issue.
```
PS D:\test\expo\myapp> npm install -g eas-cli@11.0.2
npm warn deprecated osenv@0.1.5: This package is no longer supported.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.4.5: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @oclif/screen@3.0.8: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated glob@6.0.4: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
```

**Comment by zaazbb** [comment]
i install nodejs on windows using winget, as below.
```
winget install Schniz.fnm
fnm env --use-on-cd | Out-String | Invoke-Expression
fnm use --install-if-missing 20
node -v
npm -v
```

**Comment by zaazbb** [comment]
Ignore those warnings,  the eas commands can run correctly.
