### ISSUE TITLE
Bun install fails on EAS Cloud Build

### ISSUE THREAD

**Issue by anudit** [expo/eas-cli#2491]
### Build/Submit details page URL

https://expo.dev/accounts/anuditnagar/projects/omnid-app/builds/0ca32f8b-87a6-4a02-890d-963526864dda

### Summary

![image](https://github.com/user-attachments/assets/03c30749-12f3-4759-b4dc-5a251331e49b)

### Managed or bare?

Managed

### Environment

Creating new worker instance
Intel, 4 vCPUs, 16 GB RAM
Using image "ubuntu-22.04-jdk-17-ndk-26.1.10909125" based on "ubuntu-2204-jammy-v20240614"
Installed software:
- NDK 26.1.10909125
- Node.js 18.18.0
- Bun 1.1.13
- Yarn 1.22.21
- pnpm 9.3.0
- npm 9.8.1
- Java 17
- node-gyp 10.1.0
Resolved builder image to 'sdk-51'.
EAS Build environment variables:
  SHELL=/bin/sh
  NVM_INC=/home/expo/.nvm/versions/node/v18.18.0/include/node
  JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
  PWD=/usr/local/eas-build-worker
  LOGNAME=expo
  SYSTEMD_EXEC_PID=751
  HOME=/home/expo
  LANG=en_US.UTF-8
  INVOCATION_ID=34a3e6dbcdca48eca4e3f873ac37c916
  ANDROID_NDK_HOME=/home/expo/Android/Sdk/ndk/26.1.10909125
  NVM_DIR=/home/expo/.nvm
  ANDROID_HOME=/home/expo/Android/Sdk
  USER=expo
  SHLVL=0
  ANDROID_SDK_ROOT=/home/expo/Android/Sdk
  JOURNAL_STREAM=8:20680
  PATH=/home/expo/workingdir/bin:/home/expo/.nvm/versions/node/v18.18.0/bin:/opt/bundletool:/home/expo/Android/Sdk/build-tools/29.0.3:/home/expo/Android/Sdk/ndk/26.1.10909125:/home/expo/Android/Sdk/cmdline-tools/tools/bin:/home/expo/Android/Sdk/tools:/home/expo/Android/Sdk/tools/bin:/home/expo/Android/Sdk/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/expo/.bun/bin
  NVM_BIN=/home/expo/.nvm/versions/node/v18.18.0/bin
  EAS_BUILD_WORKER_DIR=/home/expo/eas-build-worker
  _=/home/expo/.nvm/versions/node/v18.18.0/bin/node
  CI=1
  MAESTRO_DRIVER_STARTUP_TIMEOUT=120000
  EAS_BUILD=true
  EAS_BUILD_RUNNER=eas-build
  EAS_BUILD_PLATFORM=android
  NPM_CACHE_URL=http://10.4.0.19:4873/
  NVM_NODEJS_ORG_MIRROR=http://10.4.0.203:8081/
  EAS_BUILD_NPM_CACHE_URL=http://10.4.0.19:4873/
  EAS_BUILD_PROFILE=development
  EAS_BUILD_GIT_COMMIT_HASH=74f803046fbf52257499ae7dac37043dbe6c61ac
  EAS_BUILD_ID=0ca32f8b-87a6-4a02-890d-963526864dda
  EAS_BUILD_WORKINGDIR=/home/expo/workingdir/build
  EAS_BUILD_PROJECT_ID=36f03bb5-6dde-49e8-8655-444bf2d7eed7
  GRADLE_OPTS=-Dorg.gradle.jvmargs="-Xmx14g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" -Dorg.gradle.parallel=true -Dorg.gradle.daemon=false
  EAS_BUILD_USERNAME=anuditnagar
  __EAS_BUILD_ENVS_DIR=/home/expo/workingdir/env
Builder is ready, starting build

### Reproducible demo or steps to reproduce from a blank project

⠀

**Comment by szdziedzic** [comment]
Hi @anudit,

This issue seems similar to https://github.com/expo/eas-cli/issues/2480 🤔 

I tried to run `bun install` with your `package.json`, but I truly couldn't get it to be stuck and the whole process took a few seconds. Can you try to run `bun install --verbose` so we can see more logs?

What `bun` version are you using locally? Can you try to install the `latest` bun version during the build process (as of today `1.1.22`), by setting`"bun": "1.1.22"` in your eas.json? It would also be helpful if you could provide me with a reproducible example.

**Comment by szdziedzic** [comment]
Did anything change in your dependencies between the last successful build (commit 2562beeda232e132b1c87a06043ebae2925126df) and the failed build (commit c137fb7caef3a02b2336ed04dd91e2a887b0be49)?

**Comment by anudit** [comment]
@szdziedzic Manually setting the version in `eas.json` worked, thanks!

![image](https://github.com/user-attachments/assets/3deacbaa-39c0-4780-bd48-a2607f9ae2c7)
