### ISSUE TITLE
Setting provisioning profile on Apple Watch Target

### ISSUE THREAD

**Issue by Aximem** [expo/eas-cli#2578]
### Build/Submit details page URL

https://expo.dev/accounts/gowod/projects/gowod-app/builds/286a07f9-99b7-4290-9153-6bba87063a64

### Summary

We have an error when trying to build our iOS App because of Apple Watch Target which has no provisioning profile.  

```
error: No profiles for 'xx.watchkitapp' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'xx.watchkitapp'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'XXWatch' from project 'XX')
```

There is a similar issue (https://github.com/expo/eas-cli/issues/795) but it doesn't provide a solution. For now we are building manually the archive but could you provide a documentation / explanation on how to perform to manually set the provisioning profile on another target. 

Should we use a config plugin ? 

### Managed or bare?

Bare

### Environment

```
expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 21.7.1 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 10.5.0 - /usr/local/bin/npm
      Watchman: 2024.03.18.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /Users/maxime/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.4, iOS 17.4, macOS 14.4, tvOS 17.4, visionOS 1.1, watchOS 10.4
    IDEs:
      Android Studio: 2022.3 AI-223.8836.35.2231.10671973
      Xcode: 15.3/15E204a - /usr/bin/xcodebuild
    npmPackages:
      expo: 51 => 51.0.14 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.1 => 0.74.1 
      react-native-web: ~0.19.6 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 9.0.3
    Expo Workflow: bare
```

### Reproducible demo or steps to reproduce from a blank project

Add a target for Apple Watch and try to generate an iOS build on EAS

**Comment by szdziedzic** [comment]
Hi,

Are you using credentials managed by EAS? If so can you try to run `npx expo prebuild` and try to build the prebuild version and see if there are any differences?

**Comment by Aximem** [comment]
Hi @szdziedzic Yes we are using credentials managed by EAS.   
When running prebuild we have the "automatically manage signing" activated on the watch target (contrary to XCode error shown) and we are able to build everything manually thanks to XCode Managed Profile.  

This issue if more a question than an issue on how can we use credentials managed by EAS on a target that is not the main one ?   
Do we need to write a config plugin that manually set a provisioning profile for this target only and then use EAS Configuration/Credentials ? I couldn't find documentation about this use case.

**Comment by Aximem** [comment]
We couldn't find a way to handle this case with credentials managed by EAS. Even after setting credentials on EAS platform and set manual signin on watch target, we got some strange issues, like entitlements file not readable anymore etc.   

We made it by managing credentials ourself, with credentials.json: 

```
{
  "ios": {
    "XX": {
      "distributionCertificate": {
        "path": "credentials/ios/dist-cert.p12",
        "password": "XX"
      },
      "provisioningProfilePath": "credentials/ios/XX_App.mobileprovision"
    },
    "XXWatch": {
      "distributionCertificate": {
        "path": "credentials/ios/dist-cert.p12",
        "password": "XX"
      },
      "provisioningProfilePath": "credentials/ios/XX_Watch.mobileprovision"
    }
  }
}
```

**Comment by alexcraviotto** [comment]
@Aximem Credentials are not defined in credentials.json 

Im receiving this errror.

**Comment by Aximem** [comment]
@alexcraviotto I tried again today, I'm not facing this issue.   
Since we weren't able to manage Apple Watch target with EAS credentials we ended up using iOS "local" credentials definition for multiple targets, like explained in Expo documentation:  https://docs.expo.dev/app-signing/local-credentials/#multi-target-project
