### ISSUE TITLE
Allow auto-committing when using --non-interactive

### ISSUE THREAD

**Issue by zencephalon** [expo/eas-cli#258]
I'd like to combine iOS's `autoIncrement` build option with CI builds. Currently this fails because it can't commit with `--non-interactive`.

**Comment by brentvatne** [comment]
currently autoincrement will just bump the version of the project locally, so you would need to commit and then push those changes to have them actually have an impact when run on ci. would this still be useful to you in this state?

**Comment by zencephalon** [comment]
@brentvatne To meet my company's needs I did the following:

* Removed the `autoIncrement` configuration from `eas.json`
* Wrote scripts to do the increments
* In a Github Action execute the increment scripts, commit the increment, and then execute `eas build`

Committing and pushing in a Github Action is quite easy (https://github.com/marketplace/actions/add-commit). One way `eas` could have provided more value in this process would be to just leave `git` in a dirty state after doing the version increments and let me handle doing the commit.

The current system requires working around because it offers to do the increment for me, fine, but then it also wants to do the commit for me, but not in a non-interactive way. If I could specify like a `--auto-increment-commit-message` or something to keep it non-interactive then it could work. Otherwise, if I could do a `--skip-commit` so it doesn't have to prompt about the message, that would also help.

**Comment by brentvatne** [comment]
thank for your the feedback @zencephalon!

**Comment by wkozyra95** [comment]
If you set `EAS_BUILD_AUTOCOMMIT=1` it should work with `eas-cli@0.7.0`

It works only for the commit that is run as part of the build process (when incrementing version), you still need to have a clean git tree before running that command.

**Comment by zencephalon** [comment]
Thank U, that's great!

**Comment by robertherber** [comment]
When running this on CI I'm running into this error (with EAS_BUILD_AUTOCOMMIT=1): `Error: git exited with non-zero code: 128`

It's working locally. I guess it shouldn't be needed but I've also added an SSH Key in the CI flow.

Any ideas?

**Comment by brentvatne** [comment]
@robertherber - do you have some git hooks or are you trying to push after the commit?

this env var will just commit your changes. https://github.com/expo/eas-cli/blob/342c78a4f6eab058f837e12305a8ec8d9e005310/packages/eas-cli/src/build/build.ts#L239-L243

https://github.com/expo/eas-cli/blob/342c78a4f6eab058f837e12305a8ec8d9e005310/packages/eas-cli/src/build/utils/repository.ts#L180-L183

**Comment by robertherber** [comment]
I just have a prepush hook (using Husky) so it shouldn't affect a commit. Not really getting anymore helpful from the logs either =/

**Comment by wkozyra95** [comment]
Can you run it with `DEBUG=* eas build` and post the entire output?

Also, have you tried running the same commands in ci?
```
git add -u
git commit -m examplemeessage
```
most likely that error there is because name and email in git is not setup on ci, you might need to run
```
git config --global user.name "Example Name"                                                                                                                                                                                                                                                                    
git config --global user.email "example@email"      
```

**Comment by robertherber** [comment]
I figured it out. I think a linebreak had snuck into the auth token.
