### ISSUE TITLE
Apple Sign-In capability reset during EAS build

### ISSUE THREAD

**Issue by klase** [expo/eas-cli#2599]
### Summary

We want to use "Sign in with Apple" under a different primary App ID, and have selected the "Group with an existing primary App ID" option in the Apple Developer Portal (under Identifiers > `<bundle_id>` Capabilities > Apple Sign-In). However, when running an EAS build, this setting is automatically reset to "Enable as a primary App ID."

This seems to occur during the "Synced capabilities: Enabled: Sign In with Apple" step in the build process.

Is there a way to prevent this reset, or a configuration option in EAS that would allow us to maintain the "Group with an existing primary App ID" setting during builds?

### Managed or bare?

Managed

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.5
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
      Yarn: 1.22.21 - /usr/local/bin/yarn
      npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, visionOS 1.0, watchOS 10.2
    IDEs:
      Android Studio: 2023.2 AI-232.10300.40.2321.11567975
      Xcode: 15.2/15C500b - /usr/bin/xcodebuild
    npmPackages:
      babel-preset-expo: ~11.0.0 => 11.0.7
      expo: ^51.0.10 => 51.0.10
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.1 => 0.74.1
      react-native-web: ~0.19.10 => 0.19.12
    npmGlobalPackages:
      eas-cli: 12.5.0
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

- Create a managed Expo project 
- In the Apple Developer Portal go to Identifiers  > `<bundle_id>` > Capabilities > Sign in with Apple, choose "Group with an existing primary App ID".
- Run `eas build --platform ios`
- The above setting is then reset to "Enable as a primary App ID"

**Comment by szdziedzic** [comment]
It seems likely to be a bug I will check it. For now, you can do `EXPO_NO_CAPABILITY_SYNC=1 eas build` https://docs.expo.dev/build-reference/ios-capabilities/.

**Comment by occultus73** [comment]
@szdziedzic I am still experiencing this issue with the latest version of eas-cli.

**Comment by occultus73** [comment]
```
{
  "expo": {
    "ios": {
      "entitlements": {
        "com.apple.developer.applesignin": ["Default"]
      }
    }
  }
}

```
This seems to be a better workaround, as it forces sign in with apple capability to be on, instead of off.
