### ISSUE TITLE
"fastlane ran into a build/archive error with your project"

### ISSUE THREAD

**Issue by samvoults** [expo/eas-cli#2609]
### Summary

I created a new expo project : npx create-expo-app test-ios-build
I configured everything with : eas build:configure
And when I run : eas build --platform ios --local

I got :

```
[RUN_FASTLANE] ▸ ** ARCHIVE FAILED **
[RUN_FASTLANE] ** ARCHIVE FAILED **
[RUN_FASTLANE] Exit status: 65
[RUN_FASTLANE] 
[RUN_FASTLANE] +---------------------------------------+
[RUN_FASTLANE] |           Build environment           |
[RUN_FASTLANE] +-------------+-------------------------+
[RUN_FASTLANE] | xcode_path  | /Applications/Xcode.app |
[RUN_FASTLANE] | gym_version | 2.221.1                 |
[RUN_FASTLANE] | sdk         | iPhoneOS17.5.sdk        |
[RUN_FASTLANE] +-------------+-------------------------+
[RUN_FASTLANE] Looks like fastlane ran into a build/archive error with your project
[RUN_FASTLANE] It's hard to tell what's causing the error, so we wrote some guides on how
[RUN_FASTLANE] to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[RUN_FASTLANE] Before submitting an issue on GitHub, please follow the guide above and make
[RUN_FASTLANE] sure your project is set up correctly.
[RUN_FASTLANE] fastlane uses `xcodebuild` commands to generate your binary, you can see the
[RUN_FASTLANE] the full commands printed out in yellow in the above log.
[RUN_FASTLANE] Make sure to inspect the output above, as usually you'll find more error information there
[RUN_FASTLANE] 
[RUN_FASTLANE] [!] Error building the application - see the log above
[RUN_FASTLANE] Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.
```

Am I the only one? This happens with my other project too. I reset the certificates, the provisioning profiles, upgraded to the last recent expo version and did `npx expo install --fix`. I don't understand what's the problem so first I want to be sure the issue in on my side.

### Managed or bare?

Managed

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.4.1 - /usr/local/bin/node
      npm: 10.8.3 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 31, 32, 33, 34
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0, 33.0.0, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-31 | Intel x86_64 Atom, android-32 | Google APIs ARM 64 v8a, android-32 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-34 | Google Play ARM 64 v8a, android-35 | Google Play ARM 64 v8a
    IDEs:
      Android Studio: 2024.1 AI-241.15989.150.2411.11948838
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.28 => 51.0.36 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 12.5.1
      expo-cli: 6.3.10
    Expo Workflow: managed

### Reproducible demo or steps to reproduce from a blank project

npx create-expo-app test-ios-build
eas build:configure
eas build --platform ios --local

**Comment by samvoults** [comment]
Ok I manager to make it work, sorry.

**Comment by ekusiadadus** [comment]
I've solved it, with updating mac 15.0.0 -> 15.0.1

**Comment by szdziedzic** [comment]
@samvoults what was wrong in your case?

**Comment by samvoults** [comment]
> @samvoults what was wrong in your case?

When I ran the command to build my app and EAS asked if I wanted to log in to Apple Store Connect, I chose 'No' when I actually should have chosen 'Yes' now I have set the Universal Link on my project.
