### ISSUE TITLE
Google Service Account Keys cannot be set up in --non-interactive mode

### ISSUE THREAD

**Issue by KimGarza** [expo/eas-cli#2610]
### Build/Submit details page URL

https://expo.dev/accounts/kgarza/projects/elemental_editor/builds/4c62ca85-66b1-4cc5-bd0c-7534c7c4df7b

### Summary

When I run this `eas submit --platform android --latest --profile development --non-interactive` in my CI/CD pipeline yml file through github actions, after the build succeeds I get this error.
```
Looking up credentials configuration for com.anonymous.app_name...
Google Service Account Keys cannot be set up in --non-interactive mode.
    Error: submit command failed.
Error: Process completed with exit code 1.
```
I have only one Google Service Account Key in my expo account. I am using this method after pulling my hair out trying to resolve issues using it within my gihub repository secrets or google secret manager and other errors there. 

(The below errors are unrelated to this inquiry but I thought I would share the errors I consistently got after vigorous troubleshooting, tweaking formatting and all sorts of nonsesne to the key downloaded directly from google.)

Issue using google secret:
`Error: google-github-actions/auth failed with: failed to parse service account key JSON credentials: unexpected token '�', "��#y�l�_;�"... is not valid JSON`

Issue using github repository secret: 
`[logs] /usr/lib/ruby/3.0.0/openssl/pkey.rb:348:in `initialize': [!] Neither PUB key nor PRIV key: unsupported (OpenSSL::PKey::RSAError)`

### Managed or bare?

I though Managed but I guess bare? (I don't remember ejecting but okay lel)

### Environment

expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 10 10.0.19045        
    Binaries:
      Node: 20.12.1 - G:\node\node.EXE
      npm: 10.8.2 - G:\repos\PixiPatch\node_modules\.bin\npm.CMD
    npmPackages:
      expo: ^51.0.32 => 51.0.32
      expo-router: ~3.5.21 => 3.5.23
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: ^0.74.5 => 0.74.5
      react-native-web: ~0.19.10 => 0.19.12
      react-navigation: ^5.0.0 => 5.0.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

Used eas credentials to add the Google Account Service Key it found in my proj which was accurate and untampered withs since recieving the json.

```
- name: EAS Submit
  env:
    EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
  run: |
    if [ "${{ github.ref }}" == "refs/heads/main" ]; then
      eas submit --platform android --latest --profile production --non-interactive
    else
      eas submit --platform android --latest --profile development --non-interactive
    fi
```

**Comment by szdziedzic** [comment]
Hi,

I believe you don't have any Android submission credentials set up on your **EAS account** (Expo servers). When doing a submission for the first time locally the EAS CLI will prompt you about it. You can also upload it using the website.

https://docs.expo.dev/submit/android/

**Comment by KimGarza** [comment]
> Hi,
> 
> I believe you don't have any Android submission credentials set up on your **EAS account** (Expo servers). When doing a submission for the first time locally the EAS CLI will prompt you about it. You can also upload it using the website.
> 
> https://docs.expo.dev/submit/android/

Okay awesome! I will try that when I start my build process again. I realized it is still in draft mode on the Google Play Console so when I resolve that I will try again! Thank you so much :)
