### ISSUE TITLE
eas build error: "ExpoAppStaging" requires a provisioning profile. Select a provisioning profile in the Signing & Capabilities editor

### ISSUE THREAD

**Issue by uyend** [expo/eas-cli#2617]
### Summary

Hey team, I get this error when trying to run the command below. Any idea how to resolve this because it seems like my provisioning profile and certificate match. 

![Screenshot 2024-10-11 at 11 57 23 AM](https://github.com/user-attachments/assets/737faf05-fe8c-4e72-9b17-875e63897f10)
![Screenshot 2024-10-11 at 11 57 36 AM](https://github.com/user-attachments/assets/cf89d32b-ad57-44f2-8877-7ee2dd9e3f37)

Command
 
`eas build --platform ios --profile development --local`

eas.json file
```
{
  "cli": {
    "appVersionSource": "local"
  },
  "build": {
    "development": {
      "credentialsSource": "local",
      "android": {
        "buildType": "apk"
      },
      "ios": {
        "buildConfiguration": "release"
      }
    }
}
```

## Note: 
- I have not logged into my apple account cause it hasn't prompted me.
- I also can't log in due to having a federated account when just running `eas build` without any flags

### Managed or bare?

Managed

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: macOS 14.6.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.18.0/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.2 AI-242.21829.142.2421.12409432
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ~51.0.37 => 51.0.37 
      expo-router: ~3.5.23 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
      react-native-web: ~0.19.10 => 0.19.12 
    npmGlobalPackages:
      eas-cli: 12.5.1
    Expo Workflow: managed

### Error output

 error: "NAMEOFAPP" requires a provisioning profile. Select a provisioning profile in the Signing & Capabilities editor. (in target 'NAMEOFAPP' from project 'NAMEOFAPP')

### Reproducible demo or steps to reproduce from a blank project

1. Create expo project
2. Configure eas.json and use local credentials 
3. Run `eas build --platform ios --profile development --local`

**Comment by szdziedzic** [comment]
Hi,

Can you check if the bundle ID for which the profile was generated matches the bundle ID of the app you want to build? This can sometimes get out of sync if you use env vars to set your bundle ID and some of them are present in the build process other then ones used in EAS CLI.

**Comment by uyend** [comment]
> Hi,
> 
> Can you check if the bundle ID for which the profile was generated matches the bundle ID of the app you want to build? This can sometimes get out of sync if you use env vars to set your bundle ID and some of them are present in the build process other then ones used in EAS CLI.

yeap it matches!

**Comment by uyend** [comment]
Nvm that worked thank you 😅
