### ISSUE TITLE
Android build hangs/stuck after upgrading to expo 51 

### ISSUE THREAD

**Issue by nitinpatelm** [expo/eas-cli#2618]
### Build/Submit details page URL

none

### Summary

[RUN_GRADLEW] > Configure project :expo
[RUN_GRADLEW] Using expo modules
[RUN_GRADLEW] - expo-application (5.9.1)
[RUN_GRADLEW]   - expo-asset (10.0.10)
[RUN_GRADLEW]   - expo-av (14.0.7)
[RUN_GRADLEW]   - expo-background-fetch (12.0.1)
[RUN_GRADLEW]   - expo-constants (16.0.2)
[RUN_GRADLEW]   - expo-file-system (17.0.1)
[RUN_GRADLEW]   - expo-font (12.0.10)
[RUN_GRADLEW]   - expo-haptics (13.0.1)
[RUN_GRADLEW]   - expo-image-loader (4.7.0)
[RUN_GRADLEW]   - expo-image-picker (15.0.7)
[RUN_GRADLEW]   - expo-keep-awake (13.0.2)
[RUN_GRADLEW]   - expo-location (17.0.1)
[RUN_GRADLEW]   - expo-media-library (16.0.5)
[RUN_GRADLEW]   - expo-modules-core (1.12.25)
[RUN_GRADLEW]   - expo-notifications (0.28.18)
[RUN_GRADLEW]   - expo-secure-store (13.0.2)
[RUN_GRADLEW]   - expo-splash-screen (0.27.6)
[RUN_GRADLEW]   - expo-system-ui (3.0.7)
[RUN_GRADLEW]   - expo-task-manager (11.8.2)
[RUN_GRADLEW]   - expo-web-browser (13.0.3)
[RUN_GRADLEW]   - unimodules-app-loader (4.6.0)
[RUN_GRADLEW] > Configure project :react-native-reanimated
[RUN_GRADLEW] Android gradle plugin: 8.2.1
[RUN_GRADLEW] Gradle: 8.8
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets
[RUN_GRADLEW] (node:87067) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
[RUN_GRADLEW] (Use `node --trace-deprecation ...` to show where the warning was created)
[RUN_GRADLEW] Starting Metro Bundler
[RUN_GRADLEW] warning: Bundler cache is empty, rebuilding (this may take a minute)
[RUN_GRADLEW] Android Bundled 22859ms node_modules/expo-router/entry.js (3801 modules)
[RUN_GRADLEW] Writing bundle output to: /private/var/folders/57/5v6md6zs0cnctkt9_s559f5w0000gn/T/eas-build-local-nodejs/acd396c1-aaec-4475-99a2-55c8c9f44129/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle
[RUN_GRADLEW] Writing sourcemap output to: /private/var/folders/57/5v6md6zs0cnctkt9_s559f5w0000gn/T/eas-build-local-nodejs/acd396c1-aaec-4475-99a2-55c8c9f44129/build/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map
[RUN_GRADLEW] Copying 57 asset files
[RUN_GRADLEW] Done writing bundle output
[RUN_GRADLEW] Done writing sourcemap output

### Managed or bare?

managed

### Environment

```
[RUN_GRADLEW] > Configure project :expo
[RUN_GRADLEW] Using expo modules
[RUN_GRADLEW] - expo-application (5.9.1)
[RUN_GRADLEW]   - expo-asset (10.0.10)
[RUN_GRADLEW]   - expo-av (14.0.7)
[RUN_GRADLEW]   - expo-background-fetch (12.0.1)
[RUN_GRADLEW]   - expo-constants (16.0.2)
[RUN_GRADLEW]   - expo-file-system (17.0.1)
[RUN_GRADLEW]   - expo-font (12.0.10)
[RUN_GRADLEW]   - expo-haptics (13.0.1)
[RUN_GRADLEW]   - expo-image-loader (4.7.0)
[RUN_GRADLEW]   - expo-image-picker (15.0.7)
[RUN_GRADLEW]   - expo-keep-awake (13.0.2)
[RUN_GRADLEW]   - expo-location (17.0.1)
[RUN_GRADLEW]   - expo-media-library (16.0.5)
[RUN_GRADLEW]   - expo-modules-core (1.12.25)
[RUN_GRADLEW]   - expo-notifications (0.28.18)
[RUN_GRADLEW]   - expo-secure-store (13.0.2)
[RUN_GRADLEW]   - expo-splash-screen (0.27.6)
[RUN_GRADLEW]   - expo-system-ui (3.0.7)
[RUN_GRADLEW]   - expo-task-manager (11.8.2)
[RUN_GRADLEW]   - expo-web-browser (13.0.3)
[RUN_GRADLEW]   - unimodules-app-loader (4.6.0)
[RUN_GRADLEW] > Configure project :react-native-reanimated
[RUN_GRADLEW] Android gradle plugin: 8.2.1
[RUN_GRADLEW] Gradle: 8.8
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets
[RUN_GRADLEW] (node:87067) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
[RUN_GRADLEW] (Use `node --trace-deprecation ...` to show where the warning was created)
[RUN_GRADLEW] Starting Metro Bundler
[RUN_GRADLEW] warning: Bundler cache is empty, rebuilding (this may take a minute)
[RUN_GRADLEW] Android Bundled 22859ms node_modules/expo-router/entry.js (3801 modules)
[RUN_GRADLEW] Writing bundle output to: /private/var/folders/57/5v6md6zs0cnctkt9_s559f5w0000gn/T/eas-build-local-nodejs/acd396c1-aaec-4475-99a2-55c8c9f44129/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle
[RUN_GRADLEW] Writing sourcemap output to: /private/var/folders/57/5v6md6zs0cnctkt9_s559f5w0000gn/T/eas-build-local-nodejs/acd396c1-aaec-4475-99a2-55c8c9f44129/build/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map
[RUN_GRADLEW] Copying 57 asset files
[RUN_GRADLEW] Done writing bundle output
[RUN_GRADLEW] Done writing sourcemap output
```

Stuck at this point no further processing is happening.

### Error output

[RUN_GRADLEW] > Configure project :expo
[RUN_GRADLEW] Using expo modules
[RUN_GRADLEW] - expo-application (5.9.1)
[RUN_GRADLEW]   - expo-asset (10.0.10)
[RUN_GRADLEW]   - expo-av (14.0.7)
[RUN_GRADLEW]   - expo-background-fetch (12.0.1)
[RUN_GRADLEW]   - expo-constants (16.0.2)
[RUN_GRADLEW]   - expo-file-system (17.0.1)
[RUN_GRADLEW]   - expo-font (12.0.10)
[RUN_GRADLEW]   - expo-haptics (13.0.1)
[RUN_GRADLEW]   - expo-image-loader (4.7.0)
[RUN_GRADLEW]   - expo-image-picker (15.0.7)
[RUN_GRADLEW]   - expo-keep-awake (13.0.2)
[RUN_GRADLEW]   - expo-location (17.0.1)
[RUN_GRADLEW]   - expo-media-library (16.0.5)
[RUN_GRADLEW]   - expo-modules-core (1.12.25)
[RUN_GRADLEW]   - expo-notifications (0.28.18)
[RUN_GRADLEW]   - expo-secure-store (13.0.2)
[RUN_GRADLEW]   - expo-splash-screen (0.27.6)
[RUN_GRADLEW]   - expo-system-ui (3.0.7)
[RUN_GRADLEW]   - expo-task-manager (11.8.2)
[RUN_GRADLEW]   - expo-web-browser (13.0.3)
[RUN_GRADLEW]   - unimodules-app-loader (4.6.0)
[RUN_GRADLEW] > Configure project :react-native-reanimated
[RUN_GRADLEW] Android gradle plugin: 8.2.1
[RUN_GRADLEW] Gradle: 8.8
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets
[RUN_GRADLEW] (node:87067) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
[RUN_GRADLEW] (Use `node --trace-deprecation ...` to show where the warning was created)
[RUN_GRADLEW] Starting Metro Bundler
[RUN_GRADLEW] warning: Bundler cache is empty, rebuilding (this may take a minute)
[RUN_GRADLEW] Android Bundled 22859ms node_modules/expo-router/entry.js (3801 modules)
[RUN_GRADLEW] Writing bundle output to: /private/var/folders/57/5v6md6zs0cnctkt9_s559f5w0000gn/T/eas-build-local-nodejs/acd396c1-aaec-4475-99a2-55c8c9f44129/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle
[RUN_GRADLEW] Writing sourcemap output to: /private/var/folders/57/5v6md6zs0cnctkt9_s559f5w0000gn/T/eas-build-local-nodejs/acd396c1-aaec-4475-99a2-55c8c9f44129/build/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map
[RUN_GRADLEW] Copying 57 asset files
[RUN_GRADLEW] Done writing bundle output
[RUN_GRADLEW] Done writing sourcemap output

### Reproducible demo or steps to reproduce from a blank project

[RUN_GRADLEW] > Configure project :expo
[RUN_GRADLEW] Using expo modules
[RUN_GRADLEW] - expo-application (5.9.1)
[RUN_GRADLEW]   - expo-asset (10.0.10)
[RUN_GRADLEW]   - expo-av (14.0.7)
[RUN_GRADLEW]   - expo-background-fetch (12.0.1)
[RUN_GRADLEW]   - expo-constants (16.0.2)
[RUN_GRADLEW]   - expo-file-system (17.0.1)
[RUN_GRADLEW]   - expo-font (12.0.10)
[RUN_GRADLEW]   - expo-haptics (13.0.1)
[RUN_GRADLEW]   - expo-image-loader (4.7.0)
[RUN_GRADLEW]   - expo-image-picker (15.0.7)
[RUN_GRADLEW]   - expo-keep-awake (13.0.2)
[RUN_GRADLEW]   - expo-location (17.0.1)
[RUN_GRADLEW]   - expo-media-library (16.0.5)
[RUN_GRADLEW]   - expo-modules-core (1.12.25)
[RUN_GRADLEW]   - expo-notifications (0.28.18)
[RUN_GRADLEW]   - expo-secure-store (13.0.2)
[RUN_GRADLEW]   - expo-splash-screen (0.27.6)
[RUN_GRADLEW]   - expo-system-ui (3.0.7)
[RUN_GRADLEW]   - expo-task-manager (11.8.2)
[RUN_GRADLEW]   - expo-web-browser (13.0.3)
[RUN_GRADLEW]   - unimodules-app-loader (4.6.0)
[RUN_GRADLEW] > Configure project :react-native-reanimated
[RUN_GRADLEW] Android gradle plugin: 8.2.1
[RUN_GRADLEW] Gradle: 8.8
[RUN_GRADLEW] > Task :app:createBundleReleaseJsAndAssets
[RUN_GRADLEW] (node:87067) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
[RUN_GRADLEW] (Use `node --trace-deprecation ...` to show where the warning was created)
[RUN_GRADLEW] Starting Metro Bundler
[RUN_GRADLEW] warning: Bundler cache is empty, rebuilding (this may take a minute)
[RUN_GRADLEW] Android Bundled 22859ms node_modules/expo-router/entry.js (3801 modules)
[RUN_GRADLEW] Writing bundle output to: /private/var/folders/57/5v6md6zs0cnctkt9_s559f5w0000gn/T/eas-build-local-nodejs/acd396c1-aaec-4475-99a2-55c8c9f44129/build/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle
[RUN_GRADLEW] Writing sourcemap output to: /private/var/folders/57/5v6md6zs0cnctkt9_s559f5w0000gn/T/eas-build-local-nodejs/acd396c1-aaec-4475-99a2-55c8c9f44129/build/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map
[RUN_GRADLEW] Copying 57 asset files
[RUN_GRADLEW] Done writing bundle output
[RUN_GRADLEW] Done writing sourcemap output

**Comment by janmallari** [comment]
Have you fixed this? @nitinpatelm

**Comment by nitinpatelm** [comment]
no am not able to fix it @janmallari

**Comment by szdziedzic** [comment]
@nitinpatelm what's the output of the expo-doctor for your project?

**Comment by Richard-97** [comment]
I'm facing the same issue for 2-3 days, `expo-doctor` returns no warnings/errors.

**Comment by nitinpatelm** [comment]
> I'm facing the same issue for 2-3 days, `expo-doctor` returns no warnings/errors.

same here

**Comment by Richard-97** [comment]
After running `./gradlew build --warning-mode all`, it's stopped here (I closed the window after 2-3 hours without update).

```
> Task :app:createBundleReleaseJsAndAssets
env: load .env
env: export EXPO_PUBLIC_API_URL
Starting Metro Bundler
warning: Bundler cache is empty, rebuilding (this may take a minute)
Android Bundled 5051ms node_modules/expo-router/entry.js (1541 modules)
Writing bundle output to: /Users/rusnar/Documents/Projects/fuudo/mobile-app-courier/android/app/build/generated/assets/createBundleReleaseJsAndAssets/index.android.bundle
Writing sourcemap output to: /Users/rusnar/Documents/Projects/fuudo/mobile-app-courier/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map
Copying 26 asset files
Done writing bundle output
Done writing sourcemap output
<===----------> 23% EXECUTING [3m 6s]
> IDLE
> IDLE
> IDLE
> :app:createBundleReleaseJsAndAssets
> IDLE
```

**Comment by margretheluth** [comment]
i am getting the same issue after upgrading to expo 51. Any update?

**Comment by luffy-taro** [comment]
Similar issue with `expo@51.0.37`, build gets stuck at following on eas and fails after timeout. No issues reported by expo doctor, fails both locally and on EAS. Though development build works. Metro bundler along with `expo export` seems to be working. 

> Task :expo-modules-core:lintVitalAnalyzeRelease

Using openjdk 17.

**Comment by shovel-kun** [comment]
Tracking issue here: https://github.com/nativewind/nativewind/issues/1139

**Comment by janmallari** [comment]
> Similar issue with `expo@51.0.37`, build gets stuck at following on eas and fails after timeout. No issues reported by expo doctor, fails both locally and on EAS. Though development build works. Metro bundler along with `expo export` seems to be working. 
> 
> > Task :expo-modules-core:lintVitalAnalyzeRelease
> 
> Using openjdk 17. 
> 
> Edit - it was an issue with one of the dependencies nativewind 4

How did you figure it out, so I know how to deal with future issues like this?

**Comment by luffy-taro** [comment]
> How did you figure it out, so I know how to deal with future issues like this?

Removed dependencies one by one to see if build works. I don't know if there's better way.

**Comment by margretheluth** [comment]
> Similar issue with `expo@51.0.37`, build gets stuck at following on eas and fails after timeout. No issues reported by expo doctor, fails both locally and on EAS. Though development build works. Metro bundler along with `expo export` seems to be working.
> 
> > Task :expo-modules-core:lintVitalAnalyzeRelease
> 
> Using openjdk 17.
> 
> Edit - it was an issue with one of the dependencies nativewind 4

I have nativewind 4 in my project. How did you fix it?

**Comment by luffy-taro** [comment]
> Tracking issue here: [nativewind/nativewind#1139](https://github.com/nativewind/nativewind/issues/1139)

@margretheluth see this. You might need to switch between different minor versions.

**Comment by markwitt1** [comment]
I am having the same issue with Expo 52

**Comment by disolaterX** [comment]
Same issue with Expo 52, happens for android build only tho using nativewind v4

**Comment by Richard-97** [comment]
After fully rekoving nativewind from the project, the build worked. I installed nativewind version 4.0.1., reinstall node_modules, prebuild expo and it worked.
Hope it helps.

**Comment by baptiste-mnh** [comment]
Same issue on Android with 
 - Expo v52
 - Nativewind 4.0.36
 
 The issue happen when I add the `import "../global.css";` in my root layout file.

**Comment by d-haxton** [comment]
My tailwind config was including all node_modules causing everything to hang. Was unable to get any error message until locally:

` ./node_modules/.bin/expo export:embed --eager --platform ios --dev false`

Which gave me:
```
warn - Your `content` configuration includes a pattern which looks like it's accidentally matching all of `node_modules` and can cause serious performance issues.
warn - Pattern: `./**/*.js`
```

Removed that pattern from my `tailwind.config.js` and everything worked again.
