### ISSUE TITLE
EAS build failed after install expo-updates, the error  Execution failed for task ':app:createReleaseUpdatesResources'.

### ISSUE THREAD

**Issue by saeed115** [expo/eas-cli#2634]
### Summary

I use expo-updates to reload the app for Force RTL to take effect the build success if I remove expo-updates, I install expo-updates as **eas update:configure**

### Managed or bare?

Managed

### Environment

  expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 20.13.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 10.8.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20240728.093121.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
    IDEs:
      Android Studio: AI-233.14808.21.2331.11842104
    npmPackages:
      expo: ~51.0.38 => 51.0.38
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.74.5 => 0.74.5
    Expo Workflow: managed
    
    ## packages.json
    
{
"name": "new",
  "version": "1.0.0",
  "main": "expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@expo-google-fonts/tajawal": "^0.2.3",
    "@hookform/resolvers": "^3.9.0",
    "@miblanchard/react-native-slider": "^2.6.0",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-community/datetimepicker": "8.0.1",
    "@react-native-community/netinfo": "11.3.1",
    "@react-native-firebase/analytics": "^21.0.0",
    "@react-native-firebase/app": "^21.0.0",
    "@react-native-firebase/messaging": "^21.0.0",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "@rn-primitives/select": "^1.0.5",
    "@rn-primitives/slot": "^1.0.3",
    "@rn-primitives/tabs": "^1.0.3",
    "@rn-primitives/types": "^1.0.3",
    "@sentry/react-native": "~5.24.3",
    "@shopify/flash-list": "1.6.4",
    "@tanstack/react-query": "^5.52.2",
    "axios": "^1.7.5",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "dayjs": "^1.11.13",
    "expo": "~51.0.38",
    "expo-build-properties": "~0.12.5",
    "expo-constants": "~16.0.2",
    "expo-dev-client": "~4.0.28",
    "expo-device": "~6.0.2",
    "expo-file-system": "~17.0.1",
    "expo-font": "~12.0.10",
    "expo-image": "~1.13.0",
    "expo-image-picker": "~15.0.7",
    "expo-localization": "~15.0.3",
    "expo-location": "~17.0.1",
    "expo-notifications": "~0.28.18",
    "expo-sharing": "~12.0.1",
    "expo-splash-screen": "~0.27.6",
    "expo-status-bar": "~1.12.1",
    "lucide-react-native": "^0.429.0",
    "nativewind": "^4.1.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.52.2",
    "react-native": "0.74.5",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-maps": "1.14.0",
    "react-native-modal-datetime-picker": "^18.0.0",
    "react-native-otp-entry": "^1.7.1",
    "react-native-qrcode-svg": "^6.3.2",
    "react-native-raw-bottom-sheet": "^3.0.0",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-svg": "15.2.0",
    "react-native-toast-message": "^2.2.0",
    "react-native-ui-lib": "^7.29.0",
    "react-native-webview": "13.8.6",
    "tailwind-merge": "^2.5.2",
    "yup": "^1.4.0",
    "expo-updates": "~0.25.27"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@tanstack/eslint-plugin-query": "^5.52.0",
    "@types/react": "~18.2.45",
    "metro-config": "^0.81.0",
    "tailwindcss": "^3.3.2",
    "typescript": "~5.3.3"
  },
  "private": true
}

    
   ## eas.json
   
 {
  "cli": {
    "appVersionSource": "remote",
    "promptToConfigurePushNotifications": false
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "autoIncrement": true,
      "env": {
        "SENTRY_AUTH_TOKEN": "@SENTRY_AUTH_TOKEN"
      },
      "channel": "development"
    },
    "preview": {
      "distribution": "internal",
      "autoIncrement": true,
      "env": {
        "SENTRY_AUTH_TOKEN": "@SENTRY_AUTH_TOKEN"
      },
      "channel": "preview"
    },
    "production": {
      "autoIncrement": true,
      "env": {
        "SENTRY_AUTH_TOKEN": "@SENTRY_AUTH_TOKEN"
      },
      "channel": "production"
    }
  },
  "submit": {
    "production": {}
  }
}

### Error output

Error: @build-script-error-begin
Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. SHA-1 for file /home/expo/workingdir/build/global.css.android.js is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
@build-script-error-end
at createManifestForBuildAsync (/home/expo/workingdir/build/node_modules/expo-updates/utils/build/createManifestForBuildAsync.js:44:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at /home/expo/workingdir/build/node_modules/expo-updates/utils/build/createUpdatesResources.js:26:5
> Task :app:createReleaseUpdatesResources FAILED
> Task :app:createBundleReleaseJsAndAssets_SentryUploadCleanUp SKIPPED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:createReleaseUpdatesResources'.
> Process 'command 'node'' finished with non-zero exit value 1
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org/.
BUILD FAILED in 11m 6s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
1583 actionable tasks: 1583 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

### Reproducible demo or steps to reproduce from a blank project

No Reproducible demo

**Comment by BartoszDadok** [comment]
@saeed115  Were you able to fix that problem?

**Comment by AndonMitev** [comment]
@saeed115  How to?

**Comment by BartoszDadok** [comment]
For it was a conflict between libraries. I identified the conflict by uninstalling and reinstalling the libraries, one by one. The conflict was related to using `expo-cli`, as far as I remember.
