### ISSUE TITLE
Authentication with Apple Developer Portal failing with 503 status code

### ISSUE THREAD

**Issue by brentvatne** [expo/eas-cli#2639]
When authenticating with the Apple Developer Portal through EAS CLI, you may see the following error:

```
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
```

We are investigating this and expect investigation to take time as the issue involves external services and it is the weekend, currently night time in North America. Thank you for understanding.

**Comment by arapocket** [comment]
Thanks

**Comment by nicholasareed** [comment]
`--non-interactive` works for building/submitting, but in the future it would be nice for other commands to have that option (I am trying to `eas device:create` and get the auth error but have no flags to try). Maybe I'm misunderstanding what the auth error is though, and re-auth is required anyways when adding devices.

**Comment by hitesh-y** [comment]
When attempting to build the iOS version of my app using **npx eas build -p ios**, I encountered the following error:

**_Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later_**   

    Error: build command failed. 
    
    Are there any options to solve this issue?

**Comment by Niyasp** [comment]
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later .. Same issue Here

**Comment by Alberteda** [comment]
Same here, and still experiencing the same error "Authentication with Apple Developer Portal failed!", using the alternative `--non-interactive`

**Comment by suksin** [comment]
same here, tried using `--non-interactive` but getting same error as op.

**Comment by pwellner** [comment]
Workaround seems to be adding `ascAppId` to the `eas.json` file.  This Id is found on your App Store Connect page (called Apple Id). I added this number (as a string) to `submit.production.ios.ascAppId` and submit worked.

**Comment by suksin** [comment]
> Workaround seems to be adding `ascAppId` to the `eas.json` file. This Id is found on your App Store Connect page (called Apple Id). I added this number (as a string) to `submit.production.ios.ascAppId` and submit worked.

@pwellner can you please share snapshot of eas.json, how did you add it?

**Comment by qoobes** [comment]
@pwellner did this help you when authenticating or submitting to the store? It didn't solve my authentication problems

**Comment by michel-reyes** [comment]
This work for me
`eas build --platform ios --profile preview --non-interactive`

**Comment by MariuzM** [comment]
I don’t understand how ni works for you guys 
<img width="753" alt="image" src="https://github.com/user-attachments/assets/c170d0de-c7e9-4667-b4f3-e04e5ea9c09f">

**Comment by brianGammon** [comment]
The `--non-interactive` flag won't work for those of us who need to generate or regenerate credentials

**Comment by mvlach** [comment]
And what if I'm trying it for the first time - there is no solution, just wait :)

**Comment by nodespell** [comment]
same problem here, neither with or without --non-interactive works.

**Comment by nicholasareed** [comment]
Rough that Apple did this on a Friday...I'm not expecting any resolution until Monday at least. Apple-induced furlough I suppose for the weekend!

**Comment by EddyFromPoker** [comment]
+1

**Comment by DanielAmah** [comment]
Try with this 

Expo 50.0.17

`eas build -p ios --auto-submit-with-profile=production --non-interactive  --no-wait`

Ensure you have this set in a eas.json

 "submit": {
    "production": {
      "ios": {
        "ascAppId": "",
        "appleId": "",
        "appleTeamId": ""
      }
    }
  }

**Comment by byCedric** [comment]
We just rolled out a fix in `eas-cli@12.5.4`. If you run into this issue, upgrade to the latest version of `eas-cli`.

**Comment by qoobes** [comment]
You fucking saints 🥹 Thank you so much

**Comment by brianGammon** [comment]
> We just rolled out a fix in `eas-cli@12.5.4`. If you run into this issue, upgrade to the latest version of `eas-cli`.

Confirmed. Thank you ❤️

**Comment by maulik9211** [comment]
I love this community 🫶

**Comment by s-alad** [comment]
GOATS

**Comment by mmasiulis** [comment]
It worked once, but after running the command second time, I'm still getting 
```
Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)
```
`eas-cli/12.5.4 darwin-arm64 node-v20.18.0`

**Comment by byCedric** [comment]
@mmasiulis Can you share a screenshot or the logs of what you see? (you can hide the email / team id / other sensitive parts)

**Comment by mmasiulis** [comment]
@byCedric Sure, 

```
If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them.
This is optional, but without Apple account access you will need to provide all the missing values manually and we can only run minimal validation on them.
✔ Do you want to log in to your Apple account? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: … xxxxxx
› Restoring session /Users/mantasmasiulis/.app-store/auth/mantasmasiulis@gmail.com/cookie
› Team xxxxxx
› Provider xxxxx
✔ Logged in Local session
✔ Bundle identifier registered xxxxxx
✔ Synced capabilities: No updates

Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)


Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
This request can not be processed right now - Service not available because of maintenance activities, please try again after some time.'. Retrying after 3 seconds (remaining: 3)

✖ Failed to sync capability identifiers com.peachhealth.app
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
This request can not be processed right now - Service not available because of maintenance activities, please try again after some time.
    Error: build command failed.
Command failed with exit code 1: /Users/mantasmasiulis/.nvm/versions/node/v20.18.0/bin/eas build --platform ios --profile production
```

**Comment by cgrcnr** [comment]
updating eas-cli worked for me `npm install -g eas-cli` thx

**Comment by ESarcomere** [comment]
I did this: npm install -g eas-cli
THhn I ran this: npx eas build --profile production --platform ios
And I got this error:
× Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    Error: build command failed.
    
 And when I try this:  npx eas build --profile production --non-interactive --platform ios
 I get this:
Distribution Certificate is not validated for non-interactive builds.
Failed to set up credentials.
Credentials are not set up. Run this command again in interactive mode.
    Error: build command failed.

**Comment by byCedric** [comment]
@mmasiulis Can you try wiping your existing cookie? It might somehow be corrupted, and this line tells us its being loaded:

```
Restoring session /Users...
```

You can wipe the whole email address folder, and logging in again.

**Comment by byCedric** [comment]
@ESarcomere What does `npx eas --version` give you, when running the command in your project?

**Comment by ESarcomere** [comment]
eas-cli/12.5.3 win32-x64 node-v22.9.0

**Comment by ESarcomere** [comment]
Okay so for some reason when I install the new eas-cli  my npx is successfully running eas-cli@12.5.4, but my global installation is still using 12.5.3. 
So when I ran the following command:  npx eas-cli@12.5.4 build --profile production --non-interactive --platform ios
It worked

**Comment by vyashya12** [comment]
Awesome guys, keep up the great support

**Comment by dev-joaovitor** [comment]
im having the problem when i try to submit the last build.

eas cli installed globally, version:
eas-cli/12.5.3 win32-x64 node-v20.11.1

message:
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
Submission failed
    Error: submit command failed.

**Comment by gianmarcodelfreo** [comment]
> We just rolled out a fix in `eas-cli@12.5.4`. If you run into this issue, upgrade to the latest version of `eas-cli`.

love you

**Comment by mmasiulis** [comment]
@byCedric Apparently it started working on the next morning, forgot to inform you. Thx for support!

**Comment by araadt** [comment]
```
*[main][~/dev/artemis]$ eas device:create

_(...)_

✔ You're inside the project directory. Would you like to use the _(...)_ account? … yes
› Log in to your Apple Developer account to continue
✔ Apple ID: … _(...)_
› Restoring session /Users/andy/.app-store/auth/_(...)_/cookie
› Team _(...)_
› Using password for _(...)_ from your local Keychain
  Learn more: https://docs.expo.dev/distribution/security#keychain
✔ Logged in New session
› Team _(...)_

_(...)_

Authentication with Apple Developer Portal failed!
An unexpected error occurred while completing authentication
    Error: device:create command failed.

*[main][~/dev/artemis]$ npx eas --version
eas-cli/12.6.0 darwin-arm64 node-v22.9.0```

I'm still getting API auth errors (with a known-good password) on version `12.6.0`. Does this remain an issue? Is there a way to pull `--verbose` logs?

**Comment by trentcowden** [comment]
Still getting this error!

`eas-cli/12.6.0 darwin-arm64 node-v20.15.1`

Running `eas build` with the `--non-interactive` flag did work in the meantime.

**Comment by 0xPT** [comment]
Still getting this error as well on 12.6.1. I downgraded to 12.5.4 and it worked

**Comment by bbrowning918** [comment]
Both 12.5.4 and 12.6.2 throw a 503 for me from [this call](https://github.com/expo/eas-cli/blob/3782767f9aaac753cc5a24e8389b5ea0968c4be9/packages/eas-cli/src/credentials/ios/appstore/authenticate.ts#L141).

In snooping on the request there are header clues xcode gets involved, reported as version: 7.0 (7A120f) which is substantially different to version 16.1 (16B40) which is what I have installed.

Could there be something deeper in `@expo/apple-utils` where one or more of macOS 15.0.1, arm64 or xcode is tripping up the call to Apple?

```
eas-cli/12.6.2 darwin-arm64 node-v18.18.2

  EAS CLI 12.6.2 environment info:
    System:
      OS: macOS 15.0.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v18.18.2/bin/yarn
      npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    Utilities:
      Git: 2.33.0 - /usr/local/bin/git
    npmPackages:
      expo: 51.0.38 => 51.0.38 
      expo-updates: 0.25.27 => 0.25.27 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5
    Project workflow: managed
```

**Comment by Darren120** [comment]
happening in latest version, ./types/alternatives not found

**Comment by rs-mnl** [comment]
Hi all, errors authenticating with Apple persist for me using eas-cli 12.6.2.

I believe the issue is with keychain access to the local device, probably due to some recent changes with macOS managing secrets or dev tool privileges since Xcode was just updated last week, too.

I have mitigated the issue by prepending `EXPO_NO_KEYCHAIN=1` to my build commands like so:

`EXPO_NO_KEYCHAIN=1 eas build -p ios --local --profile development`
So maybe the root of this issue is not fully resolved, as users still report errors? Or is it their own (mis)configurations? If you append `EAS_DEBUG=true` to your `eas build` then you will see exactly where they error with and can investigate further...

I also want to give deep thanks to the project developers and maintainers of Expo and eas-cli for such an excellent developer tool set they have built. I can still remember that to develop iOS apps, you had to create  .cer and .mobileprovision creds on Apple's website, downloading/install the files manually, and then softly chant to the current version of Xcode as it verified that you performed the authentication rituals without error

... how far we've come 🥲

**Comment by Darren120** [comment]
if ur getting module not found, try updagraing to 12.5.4, and clear ur npx cache

**Comment by sugaith** [comment]
bombs exploding here as well

**Comment by samchencode** [comment]
I'm still getting the error. Two different devices. 
I ran `eas build` and `eas device:create` on `eas-cli@12.5.4` and `eas-cli@13.1.1`

~~~
✔ Logged in, verify your Apple account to continue

Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)

✖ Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    Error: build command failed.
~~~

**Comment by mstooks** [comment]
it looks like this issue is still occurring as of 11/11/2024 with the most recent eas-cli

As @ESarcomere mentioned, this command worked for me:

```npx eas-cli@12.5.4 build --profile production --non-interactive --platform ios```

**Comment by jameskennethrobinson** [comment]
Totally new expo project, and am getting this error...

**Comment by YarDubovyk** [comment]
Similar problem when trying to build a project

`Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)


Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
This request can not be processed right now - Service not available because of maintenance activities, please try again after some time.'. Retrying after 3 seconds (remaining: 3)

✖ Failed to sync capability identifiers xxxxxxxxx
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
This request can not be processed right now - Service not available because of maintenance activities, please try again after some time.
    Error: build command failed.`
    
    `eas-cli/13.2.3 darwin-x64 node-v21.6.2`

**Comment by csulit** [comment]
Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)

✖ Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later

**Comment by ahmadtech199** [comment]
> This is the output I am having, this shows that eas-cli has 7.8.0 version installed, however in the above command  
> 
> ```
> ★ eas-cli@13.3.0 is now available.
> To upgrade, run npm install -g eas-cli.
> Proceeding with outdated version.
> 
> eas-cli/7.8.2 darwin-arm64 node-v20.9.0
> ```
> 
> I tried "npm install -g eas-cli" multiple times, but still not updating.

**Comment by MariuzM** [comment]
> This is the output I am having, this shows that eas-cli has 7.8.0 version installed, however in the above command
> 
> ```
> ★ eas-cli@13.3.0 is now available.
> To upgrade, run npm install -g eas-cli.
>  Proceeding with outdated version.
>  
>  eas-cli/7.8.2 darwin-arm64 node-v20.9.0
> ```
> 
> I tried "npm install -g eas-cli" multiple times, but still not updating.

try `where eas` to see if you have multiple installs

**Comment by wasimkham** [comment]
Is anyone else still getting this error? I tried all the steps. 

Removing eas and installing it with `npm install -g eas-cli` on numerous occasions. Removing it manually and with `npm`. I've tried deleing the entry in keychain it creates and doesn't work. I just get the error:

```
✔ Logged in, verify your Apple account to continue

Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later'. Retrying after 3 seconds (remaining: 3)

✖ Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later
    Error: build command failed.
```
    
Could it be my node version?

```
⇒  eas --version
eas-cli/13.4.1 darwin-arm64 node-v22.11.0
```

**Comment by wasimkham** [comment]
> Hi all, errors authenticating with Apple persist for me using eas-cli 12.6.2.
> 
> I believe the issue is with keychain access to the local device, probably due to some recent changes with macOS managing secrets or dev tool privileges since Xcode was just updated last week, too.
> 
> I have mitigated the issue by prepending `EXPO_NO_KEYCHAIN=1` to my build commands like so:
> 
> `EXPO_NO_KEYCHAIN=1 eas build -p ios --local --profile development` So maybe the root of this issue is not fully resolved, as users still report errors? Or is it their own (mis)configurations? If you append `EAS_DEBUG=true` to your `eas build` then you will see exactly where they error with and can investigate further...

I must have missed this on my first scan through. This worked for me!! Thank you. What a nightmare. It may be to do with using macOS 15.1. For anyone still having this issue, try this!

**Comment by jameswagoner** [comment]
Same outcome as [dmateertf](https://github.com/dmateertf). Using NPX for eas submit to get the latest version. Also pointed to `12.5.4` and same results.

**Comment by AlyceBittar** [comment]
I'm experiencing the same issue as @dmateertf and @jameswagoner as well, I tried changing version back to `12.4.2` and the issue persists.

<img width="867" alt="Screenshot 2024-12-05 at 1 02 07 PM" src="https://github.com/user-attachments/assets/f7c6e2f0-9007-48bb-a3c9-d919a6d881ef">

**Comment by schlosser** [comment]
Also seeing this, should re re-open this ticket  @byCedric ?

**Comment by AlyceBittar** [comment]
I tried using a previous work around mentioned above, where the `--non-interactive` flag is added to the `eas build -p ios` cmd which did allow my build to complete, but am still unable to see it in my App Store Connect builds.

**Comment by jameswagoner** [comment]
@AlyceBittar 

I had the same result. The build is sitting there in Expo dashboard. Ultimately I will just download the build, use Transport (in the app store) to upload. I add a new platform in apple connect, select the uploaded build farther down the page, then save for review.

**Comment by j0pp** [comment]
I am experiencing the same issue running `eas build` and `eas device:create`. Also tried to downgrade to `12.5.4` and same issue.

**Comment by nickdep217** [comment]
I am experiencing the same thing with version 13.4.3 currently. I have tried some of the flags mentioned above

**Comment by szdziedzic** [comment]
Hey,

If you see the `InternalServerError` from Apple servers thrown after going into 2FA flow, it's actually a separate issue from the one that @byCedric fixed above. Let's track it here: https://github.com/expo/eas-cli/issues/2698

**Comment by szdziedzic** [comment]
I pinned it so it's easier to find it
