### ISSUE TITLE
EAS Build not detecting bun in a monorepo

### ISSUE THREAD

**Issue by Jussinevavuori** [expo/eas-cli#2658]
### Build/Submit details page URL

https://expo.dev/accounts/mhrakenneoy/projects/mh-hirvi/builds/9cd3fe83-c207-4381-b9fe-8aebe639ddd2

### Summary

Using bun in monorepo, with or without "packageManager": "bun@1.1.32", EAS build does not recognize bun and attempts yarn. (With "packageManager" specified, attempts using "yarn@bun@1.1.32" and fails. Without it, defaults to yarn and fails for another reason.)

### Managed or bare?

managed

### Environment

expo-env-info 1.2.0 environment info:
  System:
    OS: macOS 15.0.1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
    Watchman: 2024.09.02.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 24.0, iOS 18.0, macOS 15.0, tvOS 18.0, visionOS 2.0, watchOS 11.0
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 16.0/16A242d - /usr/bin/xcodebuild
  npmPackages:
    react: 18.2.0 => 18.2.0 
  npmGlobalPackages:
    eas-cli: 12.6.0
    expo-cli: 6.3.10
  Expo Workflow: bare

Running 14 checks on your project...
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check if the project meets version requirements for submission to app stores
✔ Check dependencies for packages that should not be installed directly
✔ Check for common project setup issues
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check native tooling versions
✔ Check Expo config (app.json/ app.config.js) schema
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:

Advice: Use 'npx expo install --check' to review and upgrade your dependencies.

The following packages should be updated for best compatibility with the installed expo version:
  @sentry/react-native@5.34.0 - expected version: ~5.24.3
  @types/react@18.3.12 - expected version: ~18.2.79
  typescript@5.6.3 - expected version: ~5.3.3
Your project may not work correctly until you install the expected versions of the packages.
Found outdated dependencies
One or more checks failed, indicating possible issues with the project.

## When `packageManager` specified

```
We detected that 'apps/mobile' is a yarn workspace
Running "yarn install" in /Users/expo/workingdir/build directory
error This project's package.json defines "packageManager": "yarn@bun@1.1.32". However the current global version of Yarn is 1.22.21.
Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
```

## Without specifying `packageManager`

```
We detected that 'apps/mobile' is a yarn workspace
Running "yarn install" in /Users/expo/workingdir/build directory
yarn install v1.22.21
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
error Error: http://10.94.183.70:4873/@mh%2feslint-config: no such package available
    at params.callback [as _callback] (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:66148:18)
    at self.callback (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:140874:22)
    at Request.emit (node:events:517:28)
    at Request.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:141846:10)
    at Request.emit (node:events:517:28)
    at IncomingMessage.<anonymous> (/Users/expo/.nvm/versions/node/v18.18.0/lib/node_modules/yarn/lib/cli.js:141768:12)
    at Object.onceWrapper (node:events:631:28)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Unknown error. See logs of the Install dependencies build phase for more information.
```

### Reproducible demo or steps to reproduce from a blank project

# Setup reproducible demo

1. Create new Bun project as monorepo root.
2. Create new Expo project in `apps/mobile` with `bunx create-expo-app@latest`
4. Follow Expo guides for:
     1. [Using Bun](https://docs.expo.dev/guides/using-bun/) in Expo project.
     4. [Working in Monorepo]
3. Create new local package `@monorepo/example` at `packages/example`.
     1. Export any variable from the package.
     2. Include in `apps/mobile`'s dependencies as `"@monorepo/example": "workspace:*"`.
     3. Import variable into Expo code. (https://docs.expo.dev/guides/monorepos/).
5. Run `bun install`.
6. Configure build with `eas build:configure`
7. Attempt build with `eas build --platform ios`

**Comment by Jussinevavuori** [comment]
Finally solved the issue after a long while. The issue was that `bun.lockb` was included in `.gitignore` which caused EAS to not detect the monorepo as a Bun workspace.

This might be relevant to add to the documentation that the lockfile must not be .gitignored.

**Comment by Jussinevavuori** [comment]
Finally solved the issue after a long while. The issue was that bun.lockb was included in .gitignore which caused EAS to not detect the monorepo as a Bun workspace.

This might be relevant to add to the documentation that the lockfile must not be .gitignored.

**Comment by dominictobias** [comment]
Hm I still have this issue.

```
{
  "cli": {
    "appVersionSource": "remote"
  },
  "build": {
    "development": {
      "bun": "1.1.38",
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "bun": "1.1.38",
      "developmentClient": true,
      "distribution": "internal",
      "ios": {
        "simulator": true
      }
    },
    "production": {
      "bun": "1.1.38",
      "autoIncrement": true
    }
  }
}
```

Then `bunx eas build --local --profile preview` tries to use `yarn`...

```
[INSTALL_DEPENDENCIES] Running "yarn install" in /var/folders/h3/hv71zxj97vj0lkm3zsg7375r0000gq/T/eas-build-local-nodejs/c8b4afab-5052-476c-a5ff-97e6105809c4/build directory
[INSTALL_DEPENDENCIES] yarn install v1.22.22
[INSTALL_DEPENDENCIES] info No lockfile found.
[INSTALL_DEPENDENCIES] [1/4] Resolving packages...
[INSTALL_DEPENDENCIES] error Package "" refers to a non-existing file '"/private/var/folders/h3/hv71zxj97vj0lkm3zsg7375r0000gq/T/eas-build-local-nodejs/c8b4afab-5052-476c-a5ff-97e6105809c4/data-layer"'.
[INSTALL_DEPENDENCIES] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[INSTALL_DEPENDENCIES]
Error: yarn install exited with non-zero code: 1
```

**Comment by Jussinevavuori** [comment]
@dominictobias Do you have a `bun.lockb` file at the root of your project and have you ensured that it is not in your `.gitignore` file?

**Comment by dominictobias** [comment]
> @dominictobias Do you have a `bun.lockb` file at the root of your project and have you ensured that it is not in your `.gitignore` file?

Yes but after you said this I got a hunch - I hadn't made a git commit yet. Committing it seems to have done the trick thanks.
