### ISSUE TITLE
eas submit -p ios fails on fastlane

### ISSUE THREAD

**Issue by alexandrumogic** [expo/eas-cli#2689]
### Summary

Running **eas submit -p ios** fails on fastlane step, I couldn't find any instructions on expo for this issue.

What should I do?

### Managed or bare?

bare

### Environment

    System:
      OS: macOS 14.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    Managers:
      CocoaPods: 1.15.2 - /Users/alexandrumogic/.rvm/gems/ruby-2.7.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 24, 26, 28, 30, 31, 32, 33, 34, 35
        Build Tools: 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-26 | ARM 64 v8a, android-29 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-VanillaIceCream | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12550806
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmPackages:
      expo: ^51.0.14 => 51.0.38 
      expo-router: ~3.5.16 => 3.5.23 
      react: 18.2.0 => 18.2.0 
      react-native: 0.74.2 => 0.74.2 
    Expo Workflow: bare

### Error output

[logs] [altool] 2024-11-14 03:56:22.740 *** Error: Unable to upload archive. Failed to authenticate for session: (
[logs] [altool]     "Error Domain=ITunesConnectionAuthenticationErrorDomain Code=3004 \"Cannot verify client's JWT headers.\" UserInfo={NSLocalizedRecoverySuggestion=Cannot verify client's JWT headers., NSLocalizedDescription=Cannot verify client's JWT headers., NSLocalizedFailureReason=App Store operation failed.}"
[logs] 
[logs] [altool] ) (-1011)
[logs] 
[logs] [altool]  {
[logs] 
[logs] [altool]     NSLocalizedDescription = "Unable to upload archive.";
[logs] 
[logs] [altool]     NSLocalizedFailureReason = "Failed to authenticate for session: (\n    \"Error Domain=ITunesConnectionAuthenticationErrorDomain Code=3004 \\\"Cannot verify client's JWT headers.\\\" UserInfo={NSLocalizedRecoverySuggestion=Cannot verify client's JWT headers., NSLocalizedDescription=Cannot verify client's JWT headers., NSLocalizedFailureReason=App Store operation failed.}\"\n)";
[logs] 
[logs] [altool] }

### Reproducible demo or steps to reproduce from a blank project

Run eas submit -p ios

**Comment by szdziedzic** [comment]
It seems like your app store API key used for submission might not have required permission/be revoked.

**Comment by vitdanylov** [comment]
hello, still present, does anyone managed to solve this?
would appreciate any info
Thank you in advance
