### ISSUE TITLE
Firebase project not found or not correctly mentioned on config.json 

### ISSUE THREAD

**Issue by Adbhutashra** [expo/eas-cli#2695]
### Summary

EAS BUILD FAILED AAB FILE, when trying  build aab file for android so i am getting errors , i am also attaching an image for your reference.
<img width="1440" alt="Screenshot 2024-11-15 at 1 48 11 PM" src="https://github.com/user-attachments/assets/1321f3e6-77a9-4b02-97ca-a415e2204bbe">

### Managed or bare?

Bare

### Environment

 expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 14.4.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
      Yarn: 1.22.22 - ~/.nvm/versions/node/v22.11.0/bin/yarn
      npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
      Watchman: 2024.11.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
      Android SDK:
        API Levels: 30, 31, 33, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-33 | Google Play Intel x86_64 Atom, android-34 | Google Play Intel x86_64 Atom, android-35 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: 2024.2 AI-242.21829.142.2421.12409432
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 13.2.0
      expo-cli: 6.3.12
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

When creating an aab file from the command eas build -p android or yarn app:build-android so i am getting
Android build failed only i have checked it on expo dashboard and attached the screenshot , please anyone help me out.

**Comment by szdziedzic** [comment]
Hey, do you have your `google-services.json` set up for a project? If so is this file gitignored? If that's the case you may want to follow this guide to unblock yourself: https://docs.expo.dev/build-reference/variables/#how-to-upload-a-secret-file-and-use-it-in-my-app-config.
