### ISSUE TITLE
Authentication with Apple Developer Portal failed!

### ISSUE THREAD

**Issue by ilyadynin** [expo/eas-cli#2712]
### Summary

When I try to run `git:(dev-alt) ✗ npx eas build --platform ios --profile development` it fails because of Authentication with Apple Developer Portal failed!
The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

### Managed or bare?

managed

### Environment

    System:
      OS: macOS 15.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 10.8.3 - ~/.nvm/versions/node/v20.13.1/bin/npm
      Watchman: 2024.08.12.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7583922
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: ^0.18.8 => 0.18.11 
      expo: ^51.0.38 => 51.0.38 
      expo-router: ~3.5.23 => 3.5.24 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.74.5 => 0.74.5 
    npmGlobalPackages:
      eas-cli: 13.1.1
    Expo Workflow: managed

### Error output

  Learn more: https://docs.expo.dev/distribution/security#keychain
✖ Logging in...
Authentication with Apple Developer Portal failed!
The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

### Reproducible demo or steps to reproduce from a blank project

I don't know how reproduce this.

**Comment by SeanNFT** [comment]
Getting the same error

Was working this morning and then stopped working in the evening time

**Comment by ilyadynin** [comment]
@SeanNFT I tried like 10 times, and a minute ago it started working again - maybe a global issue? Nevertheless it started the build so I hope it gets through.

**Comment by Darren120** [comment]
related to https://github.com/expo/eas-cli/issues/2651 but this is happening on 13.3.0

**Comment by SeanNFT** [comment]
@ilyadynin been trying for quite a few hours lmao and it's just after working thankfully.

Major pain when it does happen

**Comment by TimelyToga** [comment]
There were some items I needed to fill out in the app store connect portal, but even after agreeing to new terms I was still not able to proceed. 

After 30 minutes of trying, I reverted to version v13.2.3 and I was able to submit a build successfully.

**Comment by Darren120** [comment]
@TimelyToga it started working for everyone 10 mins ago, prob just expo server  / apple server issue, those are all private repos

**Comment by landabaso** [comment]
Same.

**Comment by itsdarrylnorris** [comment]
I've been attempting to build all day but haven't been able to due to this issue. Any updates on this?

**Comment by landabaso** [comment]
> I've been attempting to build all day but haven't been able to due to this issue. Any updates on this?

Keep trying. It eventually starts working again.

**Comment by szdziedzic** [comment]
Oh, this seems like a bug on our end. At least providing a better error message would be helpful. Can you run the command with `EXPO_DEBUG=1` so I can see a full stack trace?

**Comment by rsinger86** [comment]
@szdziedzic I am also getting this error when running `eas device:create` 

EAS is an awesome set of tools! Let me know if I can provider more info.

**Comment by JavaScriptJohn** [comment]
I'm still getting this a week later. Any updates?

**Comment by TimelyToga** [comment]
@szdziedzic Here are the relevant pieces of the error code for me: 

```✔ Logged in, verify your Apple account to continue

Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Service errors:
- Verification codes can’t be sent to this phone number at this time. Please try again later.'. Retrying after 3 seconds (remaining: 3)

✖ Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Service errors:
- Verification codes can’t be sent to this phone number at this time. Please try again later.
Error: Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Service errors:
- Verification codes can’t be sent to this phone number at this time. Please try again later.
    at t.getAppleResponseError (/Users/timbo/Library/Application Support/fnm/node-versions/v18.16.0/installation/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:856522)
    at block (/Users/timbo/Library/Application Support/fnm/node-versions/v18.16.0/installation/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:864570)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async O (/Users/timbo/Library/Application Support/fnm/node-versions/v18.16.0/installation/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:865082)
    at async I (/Users/timbo/Library/Application Support/fnm/node-versions/v18.16.0/installation/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:863935)
    at async t.requestAsync (/Users/timbo/Library/Application Support/fnm/node-versions/v18.16.0/installation/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:862471)
    at async t.idmsaRequestAsync (/Users/timbo/Library/Application Support/fnm/node-versions/v18.16.0/installation/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:736419)
    at async t.requestAuthAsync (/Users/timbo/Library/Application Support/fnm/node-versions/v18.16.0/installation/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:751126)
    at async t.handleTwoFactorAuthentication (/Users/timbo/Library/Application Support/fnm/node-versions/v18.16.0/installation/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:745676)
    at async Object.w [as loginWithUserCredentialsAsync] (/Users/timbo/Library/Application Support/fnm/node-versions/v18.16.0/installation/lib/node_modules/eas-cli/node_modules/@expo/apple-utils/build/index.js:1:728315)```
    
    Whenever I get this error it's usually because there is some stupid agreement update / terms that I need to sign. It would be nice if we got a more descriptive error message in that case and this case. I wouldn't keep trying if I could have just seen this error the whole time.

**Comment by sobbey99** [comment]
Any updates on this issue ? I am still getting constantly that error and can't make the build
Ok, I tried downgrading the eas-cli to the node js and nothing fixes it

eas-cli/14.0.2 linux-x64 node-v22.11.0

`Internal Server Error: 'h', 'Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Service errors:
- Verification codes can’t be sent to this phone number at this time. Please try again later.'. Retrying after 3 seconds (remaining: 3)

✖ Logging in...
Authentication with Apple Developer Portal failed!
Received an internal server error from Apple's App Store Connect / Developer Portal servers, please try again later. Service errors:
- Verification codes can’t be sent to this phone number at this time. Please try again later.
    Error: build command failed`

**Comment by brentvatne** [comment]
hi there, this should be resolved - please refer to: https://github.com/expo/eas-cli/issues/2698#issuecomment-2532459498

if this doesn't resolve your issue, please create a new issue with detailed information.

**Comment by lucksp** [comment]
I also have a Developer Portal error
```
✔ Logged in New session
✔ Select a Team › IdentaFly LLC - Company/Organization (xxxx)
✔ Select a Provider › IdentaFly LLC (xxxx)
✖ Couldn't switch to provider IdentaFly LLC (xxxx)
Authentication with Apple Developer Portal failed!
Apple 401 detected - You are either not logged in, your account doesn't have access to the requested data, or the page doesn't exist
    Error: build command failed.
```
