### ISSUE TITLE
What happened to the QR code for downloading dev builds on iOS devices after running this command? eas build --local --platform=ios --profile=development 

### ISSUE THREAD

**Issue by jadams777** [expo/eas-cli#2724]
### Build/Submit details page URL

https://expo.dev/accounts/wowsers07/projects/expo-dev-1

### Summary

There is no QR code to download a dev build to my iOS device after running eas build --local --platform=ios --profile=development 
This used to work, but not anymore. How do I get a development build on my iPhone for free?

### Managed or bare?

managed

### Environment

  expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.20.5 - /opt/homebrew/opt/node@18/bin/node
      Yarn: 1.22.22 - /opt/homebrew/bin/yarn
      npm: 10.8.2 - /opt/homebrew/opt/node@18/bin/npm
      Watchman: 2024.11.11.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.16.2 - /Users/macdaddy/.gem/ruby/3.3.6/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
    IDEs:
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.11 => 52.0.11 
      expo-router: ~4.0.9 => 4.0.9 
      react: 18.3.1 => 18.3.1 
      react-dom: 18.3.1 => 18.3.1 
      react-native: 0.76.3 => 0.76.3 
      react-native-web: ~0.19.13 => 0.19.13 
    npmGlobalPackages:
      eas-cli: 13.4.1
      expo-cli: 6.3.12
    Expo Workflow: managed

Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check if the project meets version requirements for submission to app stores
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for app config fields that may not be synced in a non-CNG project
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check Expo config (app.json/ app.config.js) schema
✔ Validate packages against React Native Directory package metadata
✔ Check that native modules do not use incompatible support packages
✔ Check for legacy global CLI installed locally
✔ Check that packages match versions required by installed Expo SDK
✔ Check that native modules use compatible support package versions for installed Expo SDK

Didn't find any issues with the project!

### Error output

There is no error. It produces a local .ipa file. But how do I get it on my iPhone? What's missing is the QR code. 

### Reproducible demo or steps to reproduce from a blank project

Run the following commands:
- npx create-expo-app@
- npx expo install expo-dev-client
- sudo npm install -g eas-cli
- eas build --local --platform=ios --profile=development --clear-cache

**Comment by avaziman** [comment]
when you do --local you are building locally and the build doesn't get uploaded to expo's servers, and thus no expo link, you can install the local build by connecting the iPhone to the PC and using apps like Apple Configurator (just drag the ipa to the iPhone) or uploading to testflight (both require the device to be authorized)

**Comment by machinesoul11** [comment]
i second this. i'm unable to scan to be able to download and have always used expo dev build on my device and not simulator. 

i dragged the app to my Iphone and it says it can't be installed because of the integrity can't be verified.

**Comment by szdziedzic** [comment]
Hi, we’ve never provided QR codes for downloading ad-hoc builds to your device when using local builds. This is because QR codes link to the app archives hosted on our servers, and app archives generated with the --local mode are not stored on our servers; they are only available on your local machine. As suggested above, you may need to rely on another option to install a signed `ipa` on your device.
