### ISSUE TITLE
Maestro tests flow fail to install app on simutor for latest image 

### ISSUE THREAD

**Issue by Volland** [expo/eas-cli#2742]
### Build/Submit details page URL

https://expo.dev/accounts/mykin-ai/projects/kin/builds/6fb00d27-86c1-4080-bb3f-4bd2b6f2967c

### Summary

I follow a documentation for setup e2e test with maestro . Ios test work nice but android fail on "Install app to Emulator"I follow the documentation for setup the e2e test with the Maestro.

### Managed or bare?

bare 

### Environment

  expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.0
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
      Yarn: 3.5.1 - ~/.nvm/versions/node/v18.18.2/bin/yarn
      npm: 9.9.3 - ~/Documents/work/hyphen/hyphen-wallet/node_modules/.bin/npm
      Watchman: 2024.12.02.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.1, iOS 18.1, macOS 15.1, tvOS 18.1, visionOS 2.1, watchOS 11.1
      Android SDK:
        API Levels: 33, 33, 34, 34
        Build Tools: 30.0.3, 33.0.0, 33.0.1, 34.0.0, 35.0.0
        System Images: android-33 | Google Play ARM 64 v8a, android-34-ext8 | Google Play ARM 64 v8a, android-34-ext8 | Google Play Intel x86_64 Atom, android-34 | Android TV ARM 64 v8a, android-34 | Android TV Intel x86 Atom, android-34 | Google TV ARM 64 v8a, android-34 | Google TV Intel x86 Atom, android-34 | Google APIs ARM 64 v8a, android-34 | Google APIs Intel x86_64 Atom, android-34 | Google Play ARM 64 v8a, android-34 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: 2023.3 AI-233.14808.21.2331.11842104
      Xcode: 16.1/16B40 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~19.0.1 => 19.0.1 
      expo: ^51.0.0 => 51.0.36 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: ~0.75.0 => 0.75.4 
    npmGlobalPackages:
      eas-cli: 13.3.0

### Error output

Installing "android/app/build/outputs/apk/release/app-release.apk"
adb: failed to install android/app/build/outputs/apk/release/app-release.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl443830765.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #33 (current version is #30)]
Performing Streamed Install
/bin/bash -eo pipefail /tmp/eas-build/0ceed7d4-410f-4f2e-b56d-a3adde96adf2/steps/514e2fc6-1d8e-40f7-a982-7b7e8c6cf461/scripts/c6b10a59-33d1-4fc7-aad1-2090d0cca778.sh exited with non-zero code: 1

### Reproducible demo or steps to reproduce from a blank project

Build settings :
```yaml
build:
  name: Create a build and run Maestro tests on it
  steps:
    - eas/build
    - eas/maestro_test:
        inputs:
          flow_path: |
            maestro/flows/smoke-test.yaml

```

build config
 
```
    "preview-maestro": {
      "withoutCredentials": true,
      "config": "build-and-maestro-test.yml",
      "distribution": "internal",
      "ios": {
        "simulator": true,
        "resourceClass": "large",
        "image": "latest"
      },
      "android": {
        "buildType": "apk",
        "resourceClass": "large",
        "image": "latest"
      },
      "env": {
        "APP_VARIANT": "preview",
        "NODE_ENV": "production",
        "MAESTRO_APP_ID": "ai.mykin.app.preview"
      },
      "node": "18.18.0"
    },
```

**Comment by szdziedzic** [comment]
This option should be now available on production
