### ISSUE TITLE
eas submit stuck on waiting for an available submitter

### ISSUE THREAD

**Issue by arapocket** [expo/eas-cli#2758]
### Summary

I know there was a previous bug with apple's developer portal failing. Updating the cli fixed that one for me. Wondering if this might be a another related issue.

From yesterday I keep getting stuck on `Submitting your app to Apple App Store Connect: waiting for an available submitter` every time I try to do a submit. I did have one build go through while the cli was still stuck on that message, but am no longer able to get a build through.

### Managed or bare?

bare

### Environment

expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 20.11.1 - /usr/local/bin/node
      Yarn: 1.22.22 - ~/agebold-web/node_modules/.bin/yarn
      npm: 10.2.4 - /usr/local/bin/npm
      Watchman: 2024.09.16.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.15.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.5, iOS 17.5, macOS 14.5, tvOS 17.5, visionOS 1.2, watchOS 10.5
    IDEs:
      Android Studio: 2024.1 AI-241.19072.14.2412.12360217
      Xcode: 15.4/15F31d - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 7.5.0
    Expo Workflow: bare

✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check for common project setup issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with Metro config
✔ Check npm/ yarn versions
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check native tooling versions
✖ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

The following packages should be updated for best compatibility with the installed expo version:
  @react-native-async-storage/async-storage@1.24.0 - expected version: 1.23.1
  @react-native-community/datetimepicker@8.2.0 - expected version: 8.0.1
  @react-native-picker/picker@2.10.1 - expected version: 2.7.5
  @shopify/flash-list@1.7.1 - expected version: 1.6.4
  expo@51.0.32 - expected version: ~51.0.39
  expo-dev-client@4.0.25 - expected version: ~4.0.29
  expo-localization@16.0.0 - expected version: ~15.0.3
  expo-notifications@0.28.16 - expected version: ~0.28.19
  expo-splash-screen@0.27.5 - expected version: ~0.27.7
  expo-updates@0.25.24 - expected version: ~0.25.27
  lottie-react-native@7.0.0 - expected version: 6.7.0
  react@18.3.1 - expected version: 18.2.0
  react-native-gesture-handler@2.20.0 - expected version: ~2.16.1
  react-native-reanimated@3.15.1 - expected version: ~3.10.1
  react-native-safe-area-context@4.14.0 - expected version: 4.10.5
  react-native-screens@3.35.0 - expected version: 3.31.1
  @types/react@18.3.4 - expected version: ~18.2.79

### Reproducible demo or steps to reproduce from a blank project

1. eas build with --local
2. try to submit the build

**Comment by szdziedzic** [comment]
We had a partial outage yesterday that caused this issue. It was already fixed.

**Comment by blake41** [comment]
I'm having this same problem. I updated the cli to see if that was the problem.

**Reproducible demo or steps to reproduce from a blank project**

1. I ran eas build -p ios --auto-submit initially, and then cancelled the submission because it was waiting for an hour
2. I tried eas submit -p ios and same issue, hanging indefinitely. I tried a few times

**Comment by Daneyl** [comment]
I am also facing the same issue.

**Comment by blake41** [comment]
@Daneyl i found that it ended up going through, when i checked my email i had a confirm, something was messed up in the UI not letting me know it went through. i did try it a number of times and let it hang for like 10 minutes each time

**Comment by romainlouvet** [comment]
same issue

**Comment by saaspeter** [comment]
same issue, always stuck on this step. "Submitting your app to Apple App Store Connect: waiting for an available submitter"

**Comment by Amund-Fremming** [comment]
Same issue here. Been stuck for over two hours, still nothing.

**Comment by sixpathdev** [comment]
> Same issue here. Been stuck for over two hours, still nothing.

I resulted to using Transporter to upload the build to app store @Amund-Fremming

**Comment by Amund-Fremming** [comment]
Okay, great! I managed to submit my app after removing an invalid profile I had. I also upgraded the EAS CLI to version 14.5.0. @sixpathdev

**Comment by sixpathdev** [comment]
@Amund-Fremming what profile did you remove?

**Comment by TiagoAndreAlmeida** [comment]
i facing same problem now, still stuck for last 4hours

**Comment by fynally** [comment]
`Submitting your app to Apple App Store Connect: waiting for an available submitter`

I have been in this stage for hours now. What's going on please?

**Comment by bbrimacombe** [comment]
Same issue here. Hanging on: 
"Submitting your app to Apple App Store Connect: waiting for an available submitter"
for over 1 hour. It worked perfectly last week. We've changed nothing on our end. 
On UI I see: Free Tier Queue
We are also getting this error:
✖ Failed to create TestFlight group...
Failed to create an internal TestFlight group. This can be done manually in the App Store Connect website.
UnexpectedAppleResponse: The provided entity includes an attribute with an invalid value - Public link limit cannot be applied to internal group
Which I don't know if we've seen before. Our TestFlight group looks fine on App Store Connect.

**Comment by schimini** [comment]
Same, currently stuck . @fynally are you using a local build?

**Comment by maximilian** [comment]
@fynally @schimini Also stuck, did it work? Been in queue for almost 2 hours now. It's my first submission so not sure how normal this is during peak times?

**Comment by maximilian** [comment]
@schimini  I guess we'll wait and see then :)

**Comment by kntbruh** [comment]
Same issue, Queued for 2 hours now

**Comment by salememd** [comment]
Anyone solved this?

**Comment by rehmange** [comment]
I am getting the same issue. I have changed the version of EAS, but the error still exists.

**Comment by rehmange** [comment]
> Anyone solved this?

No

**Comment by schimini** [comment]
From my experience it was not an issue. You just need to wait :(

**Comment by zollipaul** [comment]
> I had to upgrade to a paid plan to get this to work, how sad :/

Same here. From what you said @albertbethlowsky it looks like they introduced a delay for the free tier, (for me especially on apple app store submissions). So maybe not a bug, rather an incentive to buy a paid plan.

**Comment by Player-i** [comment]
i am having the same problem, I am using the free tier. How long does it take to submit the build for the free tier?

**Comment by robjoyce1921** [comment]
Same problem. Seems hung at "Submitting your app to Apple App Store Connect: waiting for an available submitter"   Will let it run and run to test the theory that this is a free tier "feature".  Welcome any official comment from Expo that would remove the ambiguity.

**Comment by fpinatares** [comment]
I fixed it by upgrading to on demand plan... 😕

**Comment by albertbethlowsky** [comment]
Btw for Apple it is way faster building through Xcode and connecting to App Store Connect directly. You can even setup pipelines that does this for you if you want 😄

**Comment by robjoyce1921** [comment]
> Same problem. Seems hung at "Submitting your app to Apple App Store Connect: waiting for an available submitter" Will let it run and run to test the theory that this is a free tier "feature". Welcome any official comment from Expo that would remove the ambiguity.

I walked away and left it running.  Eventually completed.  Not sure how long since I walked away, but I'd guess 4 to 5 hours later.

**Comment by WilliamWelsh** [comment]
I feel like a deliberate change was made to get people to move to the on-demand plan, because it seems like one day randomly it suddenly started taking hours, and it's been like that ever since

**Comment by WilliamWelsh** [comment]
Guys - you can literally just download the Transporter (official by Apple) app from the Mac store, and drag your IPA in there and hit deliver. Super fast, don't need Expo to send your file to App Store Connect

**Comment by Ahmet-Dedeler** [comment]
@WilliamWelsh Not everyone is on Mac 💀

For me it just worked almost instantly when I tried at a different time the next day. Only solution I guess is wait or message the Expo team asking them to make it faster, with enough people asking they'll make it faster over time (which I hope they do!!)

**Comment by Drew-drashy** [comment]
I'm experiencing the same issue and have tried it a couple of times, but the output remains the same. Could you clear the queue, but nothing is happening?

**Comment by ursnj** [comment]
This is the issue always with my builds, looks like we need to really see alternatives ?

**Comment by rswearin** [comment]
Submitting your app to Apple App Store Connect: waiting for an available submitter

**Comment by YasserDbeis2** [comment]
Happening right now. Glad I checked this thread--downloading the .ipa and uploading to Apple's transport app took like 3 minutes lol

**Comment by devops-zenithavenir** [comment]
Same here, we have this problem right now as well!

**Comment by hl11jp** [comment]
Having this problem right now, using the Transporter app works

**Comment by Shervanator** [comment]
Having the same issue here as well

**Comment by ArmenPattern** [comment]
My eas submit was started 1 day ago and is still not processing. And I can't cancel the workflow

**Comment by arilishu** [comment]
Is there any reoslution here?
The process use to take an hour

**Comment by tgamziani** [comment]
Same issue here...

**Comment by unravel-the-sky** [comment]
I've been struggling with the same issue for submitting my app to testflight using eas submit, and been taking 2-3 hours at least per submission. i used this method and i can confirm it works:
- Grab the latest URL from `eas build:list`
- Open Apple's [Transporter app](https://apps.apple.com/app/transporter/id1450874784) 
- Drag the .ipa in, hit Deliver

and takes about 2-3 minutes in total! 

As i understand, the only advantage of using eas submit is that it auto-creates TestFlight groups on first submission.
