### ISSUE TITLE
eas submit uses incorrect bundleIdentifier

### ISSUE THREAD

**Issue by deelo55** [expo/eas-cli#2779]
### Summary

.env:
`BUNDLE_ID=com.myapp.dev`

eas.json
```
"production": {
 "BUNDLE_ID"=com.myapp.prod
}
```

app.config.js:
` bundleIdentifier: process.env.BUNDLE_ID,`

When I run eas submit with a production build it uses the bundle id com.myapp.dev and fails.
I have to edit the BUNDLE_ID in .env to match the production bundle ID, in order to run eas submit.

### Managed or bare?

Managed

### Environment

Managed

### Error output

Not relevant

### Reproducible demo or steps to reproduce from a blank project

Not relevant

**Comment by szdziedzic** [comment]
The Expo CLI prioritizes `.env` environment variables when bundling JS code for your application. That's why we recommend adding `.env` files to `.gitignore`/`.easignore` and using server-side defined env variables for your builds, to prevent any confusing situations like this.

https://docs.expo.dev/eas/using-environment-variables/

**Comment by deelo55** [comment]
If I add to .easignore and specify the value in eas.json without server variables, it doesn't work either:
```
Specified value for "ios.bundleIdentifier" in app.config.ts is ignored because an ios directory was detected in the project.
EAS Build will use the value found in the native code.
```

Using server-side variables lacks the transparency of having the values in eas.json. 
The code actually uses the values in eas.json when submitting, just not in the initial check.

Would be great if this could be amended to use EAS.json to build the config file before running and not having to rely on server variables.

At the moment, its feels buggy that it uses the value in .env when describing the build in the terminal output but then uses a different value in the build.
