### ISSUE TITLE
cannot find symbol import expo.core.ExpoModulesPackage

### ISSUE THREAD

**Issue by aeftimia** [expo/eas-cli#2789]
### Build/Submit details page URL

https://expo.dev/accounts/aeftimia/projects/app/builds/99af3b55-e014-4afe-bbbb-154a92ae3fde

### Summary

I'm trying to deploy a minimal react-native-webview project, and eas build seems to fail with this error on `gradlew :app:bundleRelease`:

```
> Task :app:compileReleaseJavaWithJavac FAILED
/home/expo/workingdir/build/packages/mobile/app/android/app/build/generated/autolinking/src/main/java/com/facebook/react/PackageList.java:14: error: cannot find symbol
import expo.core.ExpoModulesPackage;
                ^
  symbol:   class ExpoModulesPackage
  location: package expo.core
/home/expo/workingdir/build/packages/mobile/app/android/app/build/generated/autolinking/src/main/java/com/facebook/react/PackageList.java:62: error: cannot find symbol
      new ExpoModulesPackage(),
          ^
  symbol:   class ExpoModulesPackage
  location: class PackageList
2 errors
> Task :expo-modules-core:buildCMakeRelWithDebInfo[armeabi-v7a]
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

I tried installing expo-modules-core as shown in my setup from a blank project. I'm new to this, but I've exhausted my options regarding what else I can find or think of to try.

### Managed or bare?

bare

### Environment

npx expo-env-info

```
  expo-env-info 1.2.1 environment info:
    System:
      OS: macOS 15.1.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 23.5.0 - /opt/homebrew/bin/node
      npm: 10.9.2 - /opt/homebrew/bin/npm
    Managers:
      CocoaPods: 1.16.2 - /opt/homebrew/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 24.2, iOS 18.2, macOS 15.2, tvOS 18.2, visionOS 2.2, watchOS 11.2
    IDEs:
      Android Studio: 2024.2 AI-242.23339.11.2421.12700392
      Xcode: 16.2/16C5032a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~52.0.20 => 52.0.20 
      react: 18.3.1 => 18.3.1 
      react-native: 0.76.5 => 0.76.5 
    npmGlobalPackages:
      eas-cli: 14.2.0
    Expo Workflow: bare

```
npx expo-doctor
```
Enabled experimental React Native Directory checks. Unset the EXPO_DOCTOR_ENABLE_DIRECTORY_CHECK environment variable to disable this check.
Running 15 checks on your project...
✔ Check package.json for common issues
✔ Check Expo config for common issues
✔ Check native tooling versions
✔ Check for common project setup issues
✖ Check dependencies for packages that should not be installed directly
✔ Check npm/ yarn versions
✔ Check for issues with Metro config
✔ Check if the project meets version requirements for submission to app stores
✖ Check for app config fields that may not be synced in a non-CNG project
✖ Validate packages against React Native Directory package metadata
✔ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check that native modules use compatible support package versions for installed Expo SDK

Detailed check results:


Advice: Add '/android' and '/ios' to your .gitignore file if you intend to use CNG / Prebuild. Learn more: https://docs.expo.dev/workflow/prebuild/#usage-with-eas-build

Advice: 
- Update React Native Directory to include metadata for unknown packages. Alternatively, set expo.doctor.reactNativeDirectoryCheck.listUnknownPackages in package.json to false to skip warnings about packages with no metadata, if the warning is not relevant.

```

### Error output

> Task :app:compileReleaseJavaWithJavac FAILED
/home/expo/workingdir/build/packages/mobile/app/android/app/build/generated/autolinking/src/main/java/com/facebook/react/PackageList.java:14: error: cannot find symbol
import expo.core.ExpoModulesPackage;
                ^
  symbol:   class ExpoModulesPackage
  location: package expo.core
/home/expo/workingdir/build/packages/mobile/app/android/app/build/generated/autolinking/src/main/java/com/facebook/react/PackageList.java:62: error: cannot find symbol
      new ExpoModulesPackage(),
          ^
  symbol:   class ExpoModulesPackage
  location: class PackageList
2 errors
> Task :expo-modules-core:buildCMakeRelWithDebInfo[armeabi-v7a]
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

### Reproducible demo or steps to reproduce from a blank project

```
npx install-expo-modules@latest --template blank
npx expo install react-native-webview
npx expo install @react-native/gradle-plugin
npx expo install @babel/runtime
npx expo install expo-asset
npx expo install expo-modules-core
npx expo run --platform android
```

App.js:
```
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, View } from 'react-native';
import { WebView } from 'react-native-webview';

export default function App() {
  return (
      <WebView 
      style={styles.container}
      source={{ uri: 'https://example.com/' }} >
      <StatusBar style="auto" />
      </WebView>
  );
}

const styles = StyleSheet.create({
  container: {
    marginTop: 10,
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by aeftimia** [comment]
Confirming this also happens without Webview

export default function App() {
  return (
      <View style={styles.container} >
      <StatusBar style="auto" />
      </View>
  );
}

**Comment by LongHP105** [comment]
I've got the same problem. 
How can I deal with this?

**Comment by LongHP105** [comment]
**Investigation**
The local android build: ✅
* using import expo.modules.ExpoModulesPackage;

The EAS service build: ❌
* using import from expo.core.ExpoModulesPackage

**Comment by LongHP105** [comment]
@aeftimia 
I found that the problem is that my project is using pnpm, so it somehow cannot resolve dependencies correctly.

so if you use pnpm too, maybe this approach you can try:
* add `node-linker=hoisted` to .npmrc

It solved my issue.

**Comment by aeftimia** [comment]
Thanks! That worked for me too!

**Comment by delphinebugner** [comment]
Hi! Also had the issue, unfortunately adding `node-linker=hoisted` is not possible in my project. 

If someone else is in the same situation: you can add in your app package.json:  

- `"expo-modules-autolinking": "*"`

That will help pnpm finds its way and make the native error disappear. 

**Edit on Jun 2025**: this is actually a bad practice and can lead to conflicts and errors; Instead, use the publicHoistPattern in .npmrc file: 

```yml
publicHoistPattern:
  - '*expo-modules-autolinking'
  - '*expo-modules-core'
  - '*babel-preset-expo'
  ```

**Comment by itsbjoern** [comment]
The solution offered here didn't work for us in a pnpm monorepo so I'm just cross-referencing my answer from this other related issue: https://github.com/expo/expo/issues/31005#issuecomment-2582885069

**Comment by Elinaldo1** [comment]
> Hi! Also had the issue, unfortunately adding `node-linker=hoisted` is not possible in my project.
> 
> If someone else is in the same situation: you can add in your app package.json:
> 
> * `"expo-modules-autolinking": "*"`
> 
> That will help pnpm finds its way and make the native error disappear.


This solution worked for me, using pnpm.

**Comment by gmonte** [comment]
> Hi! Also had the issue, unfortunately adding `node-linker=hoisted` is not possible in my project.
> 
> If someone else is in the same situation: you can add in your app package.json:
> 
> * `"expo-modules-autolinking": "*"`
> 
> That will help pnpm finds its way and make the native error disappear.

I'm migrating a managed expo to a pnpm workspace (with an empty .npmrc) and I'm facing the same error on eas build android.

I also tried migrating the app's private repository (non-monorepo) from npm to pnpm and was getting the same error. I noticed that adding `shamefully-hoist=true` or `node-linker=hoisted` to my `.nvmrc` made the build work, but I can't use that in my monorepo.

So I cleaned my `.nvmrc`, did a clean install of the dependencies, ran `pnpm why expo-modules-autolinking` to find out which version of this package my expo was using, and added that exact version as a dependency to my app. It worked perfectly. ✨ Thanks @delphinebugner ! ❤️

**Comment by gmonte** [comment]
If you are facing issues with `eas build ios` try it https://github.com/facebook/react-native/issues/38283#issuecomment-2625317955

**Comment by raho13** [comment]
> [@aeftimia](https://github.com/aeftimia) I found that the problem is that my project is using pnpm, so it somehow cannot resolve dependencies correctly.
> 
> so if you use pnpm too, maybe this approach you can try:
> 
> * add `node-linker=hoisted` to .npmrc
> 
> It solved my issue.

I did this and it was built successfully but now the application does not connect to the internet

**Comment by myudak** [comment]
broo im still have this issue with eas build android

**Comment by ashwamegh** [comment]
> Hi! Also had the issue, unfortunately adding `node-linker=hoisted` is not possible in my project.
> 
> If someone else is in the same situation: you can add in your app package.json:
> 
> * `"expo-modules-autolinking": "*"`
> 
> That will help pnpm finds its way and make the native error disappear.

This Worked for me as well, Thanks :)

**Comment by wendellli99** [comment]
> > Hi! Also had the issue, unfortunately adding `node-linker=hoisted` is not possible in my project.
> > If someone else is in the same situation: you can add in your app package.json:
> > 
> > * `"expo-modules-autolinking": "*"`
> > 
> > That will help pnpm finds its way and make the native error disappear.
> 
> This Worked for me as well, Thanks :)

`npx expo-doctor` gives this error if I add `expo-modules-autolinking` to package.json. 

> ✖ Check dependencies for packages that should not be installed directly
> The package "expo-modules-autolinking" should not be installed directly in your project. It is a dependency of other Expo packages, which will install it automatically as needed.
> Advice:
> Remove these packages from your package.json.

**Comment by Vadko** [comment]
On top of adding `expo-modules-autolinking` is not correct by output of `expo-doctor`, it also breaks Pods installation. This is not a proper solution

**Comment by bobbyquantum** [comment]
A [publicHoistPattern](https://pnpm.io/next/settings#publichoistpattern) targeting the packages with linking issues directly in pnpm-workspace.yaml solved this problem for me, without changing the global hoisted setting or adding anything to package.json.

```yaml 
packages:
  - 'packages/*'
publicHoistPattern:
  - '*expo-modules-core'
  - '*expo-modules-autolinking'
  - '*babel-preset-expo'
```

**Comment by delphinebugner** [comment]
Update: using 

> packages:
>   - 'packages/*'
> publicHoistPattern:
>   - '*expo-modules-core'
>   - '*expo-modules-autolinking'
>   - '*babel-preset-expo'

worked in our case (we need to keep node-linker: isolated). I join the other **dis-recommanding** :

- `"expo-modules-autolinking": "*"`

... because when upgrading to Expo 53, previous versions of `expo-modules-autolinking`, `babel-preset-expo` and  `expo-modules-core` remained in the `node_modules`, creating conflicts.

**Comment by Bin-Huang** [comment]
Just add this to `.npmrc`, it worked for me.
```
public-hoist-pattern[]=*expo-modules-autolinking
public-hoist-pattern[]=*expo-modules-core
public-hoist-pattern[]=*babel-preset-expo
```

**Comment by armanmamyan** [comment]
> [@aeftimia](https://github.com/aeftimia) I found that the problem is that my project is using pnpm, so it somehow cannot resolve dependencies correctly.
> 
> so if you use pnpm too, maybe this approach you can try:
> 
> * add `node-linker=hoisted` to .npmrc
> 
> It solved my issue.

This solution fully covered my case with Expo 53

**Comment by nbcraft** [comment]
For anyone using `pnpm` and expo SDK53 and reading this and still struggling, this https://github.com/expo/eas-cli/issues/3066#issuecomment-3007877176 got me across the finish line.

Fixing the pnpm version (to `10.16.0` in my case) in all the `eas.json` builds finally got my build passing.

Also, I'm not sure if those steps were necessary or correct, but this is the other changes I applied:
- Installing `expo-linking` directly in the project
- Adding a `pnpm-workspace.yaml` file with:
  ```yaml
  packages:
    - 'packages/*'
  publicHoistPattern:
    - '*expo-modules-core'
    - '*expo-modules-autolinking'
    - '*babel-preset-expo'
  nodeLinker: hoisted
  ```

**Comment by arapocket** [comment]
@nbcraft That worked for me! Only I didn't need `nodeLinker: hoisted` (that wasn't working for me)
