### ISSUE TITLE
[Feature Request] Automatically choose all registered devices with --non-interactive

### ISSUE THREAD

**Issue by leoskyrocker** [expo/eas-cli#279]
Hi team, thanks for building EAS. We're actively looking to create a CICD pipeline for internal distribution, and currently I'm running into an issue where already registered devices need to be selected in the interactive mode.

This creates an issue where we cannot allow team members to sign up as registered device on their own, and create a new build that can be installed on their device without manual intervention.

It'd be nice if there's something like `--select-all-devices=true --non-interactive` so that I can opt into updating the list of devices every time we make a build.

**Comment by wkozyra95** [comment]
When new devices are added we need to generate a new provisioning profile and to do that we need to have access to apple account which is an interactive operation. It's sth that we might look into in the future, but not anytime soon.
