### ISSUE TITLE
Always get 401 unauthorized with private package repo

### ISSUE THREAD

**Issue by paydaycay** [expo/eas-cli#285]
Hi,

I'm always getting "Request failed \"401 Unauthorized\"" during the build.

I added my npmToken as specified in the [doc](https://docs.expo.io/build-reference/how-tos/#how-to-use-private-package-repositories) and added a .npmrc file like this in my project : 
```
//myprivaterepo.com/:_authToken="${NPM_TOKEN}"
```
I also tried with a more complete .npmrc file : 
```
always-auth=true
registry=https://myprivaterepo.com/
//myprivaterepo.com/:_authToken="${NPM_TOKEN}"
```
But it still fails.

I don't know how to solve this. 

Could you help me please ?

**Comment by paydaycay** [comment]
Sorry I found my mistake... My .npmrc file was in my gitignore... Sorry

**Comment by amorealz** [comment]
Hey @paydaycay was your private registry something different than the npmjs.org registry? I'm trying to make it work with AWS Codeartifact and I'm currently experiencing an error even after my project dependencies are installed correctly from the private registry.

Everything is working up to the prebuild phase where it is failing, while trying to create the ios native project:
```
Prebuilding managed project
- Creating native project directories (./ios and ./android) and updating .gitignore
[stderr] [23:12:01] Unexpected response: Unauthorized. From url: https://my-private-registry-123456.d.codeartifact.eu-central-1.amazonaws.com:443/npm/my-private-registry/expo-template-bare-minimum/-/expo-template-bare-minimum-44.0.11.tgz
- Creating native project directories (./ios and ./android) and updating .gitignore
✖ Failed to create the native project.
```

Apart from fixing the .npmrc in your .gitignore, do you made any additional configuration to make it work?

**Comment by avedisklf** [comment]
@amorealz I fixed it on my end by adding --namespace @packagescope to the aws codeartifact login command It seems like that expo package does not work with code artifact so by namespacing only our private package uses codeartifact and the rest are still using yarnpkg, it worked.

**Comment by amorealz** [comment]
Just as an update, I asked for help in the expo discord server when the issue happened. They were super helpful and they actually created the fix and merged it a couple of weeks later. This is the link to the PR if you guys want to take a look:

https://github.com/expo/expo-cli/pull/4223

[kbrandwijk](https://github.com/kbrandwijk)
👆Props to this guy

**Comment by rei-shaholli** [comment]
> @amorealz I fixed it on my end by adding --namespace @packagescope to the aws codeartifact login command It seems like that expo package does not work with code artifact so by namespacing only our private package uses codeartifact and the rest are still using yarnpkg, it worked.

Thank you so much! I was like wth is going on!
