### ISSUE TITLE
Allow specifying Release Channel in `eas build`

### ISSUE THREAD

**Issue by defrex** [expo/eas-cli#292]
`expo build` allows you to specify `--release-channel`, however no such option appears to exist for `eas build`. 

What is the intended way to specify the release channel?

**Comment by leoskyrocker** [comment]
as far as I'm aware, eas build does not perform an over-the-air (OTA) update. Release channel is really built around the OTA update feature if I understand correctly.

**Comment by defrex** [comment]
I mean, release channels are related to OTA updates, but are you saying `eas build` isn't compatible with OTA updates? I'd expect to be able to use it to push that kind of update, especially if it's meant to completely replace `expo build` eventually, which obviously does support release channels.

I'd like to use both update mechanisms together, since while OTA updating is nice for existing users, I also want new users to download the latest JS when they install the binary.

**Comment by dsokal** [comment]
Hi guys,

Please see the docs - https://docs.expo.io/build/eas-json/

You can specify the release channel in your build profile, sth like:
```
{
  "builds": {
    "android": {
      "release": {
        "workflow": "generic",
        "releaseChannel": "debug"
      }
    }
  }
}
```

**Comment by cheeaun** [comment]
I think this is still a needed feature, at least for my use-case where the release channels are dynamically generated.

For example, my project has this script (in `package.json`):

```json
{
  ...
  "scripts": {
    "current-version": "node -e 'console.log(require(\"./app.json\").expo.version)'",
    "build": "expo build:ios --release-channel staging-`npm run current-version --silent`"
  }
}
```

... which generates `staging-2.0.1`, based on the app version.

If the release channel is now hard-coded in `eas.json`, I can't really modify it from `eas build`, unless I write a script to dynamically generate `eas.json`?

**Comment by codebutler** [comment]
> I think this is still a needed feature, at least for my use-case where the release channels are dynamically generated.
> 
> For example, my project has this script (in `package.json`):
> 
> ```json
> {
>   ...
>   "scripts": {
>     "current-version": "node -e 'console.log(require(\"./app.json\").expo.version)'",
>     "build": "expo build:ios --release-channel staging-`npm run current-version --silent`",
>     "publish": "expo publish --release-channel staging-`npm run current-version --silent`"
>   }
> }
> ```
> 
> ... which generates `staging-2.0.1`, based on the app version.
> 
> If the release channel is now hard-coded in `eas.json`, I can't really modify it from `eas build`, unless I write a script to dynamically generate `eas.json`?

Can the expo team please provide guidance on how to handle dynamic release channels with EAS? We've been doing something similar to @cheeaun. If this is no longer recommended, how can we ensure JS code isn't published code to an incompatible build (missing native dependencies) and how do we hotfix specific releases?

**Comment by abdulmuksith3** [comment]
For EAS build with multiple release channels you would have to do `eas build --profile <profile-name>`. And from what I understood from their documents is that `releaseChannel` is only supported in classical builds and in eas.json it has been changed to just `channel`.

Hope it helps!

**Comment by tamis-laan** [comment]
> For EAS build with multiple release channels you would have to do `eas build --profile <profile-name>`
> 
> Hope it helps!

And `--profile` is the same as `--release-channel`? Why the naming change?

**Comment by AuthorProxy** [comment]
profile is not the same as release channel, release channel is more specific, you can have different channels under production profile, reopen this task @dsokal , it is important, now we should continue use old expo build

**Comment by J-Noel1523** [comment]
> @AuthorProxy
> 
> I see, I find it difficult to find information/documentation about this. Is there some tutorial? Interface expo.io isn't very explanatory either.

OTA is possible with eas. I just did it with the preview profile. Regarding your question though, I'm quite confused too since in regular expo publish you could specify a release channel. I think there is a way to do something similar with eas. still learning...

**Comment by yingwei1025** [comment]
So do `eas build --profile dev`  is equal to `expo build --release-channel dev`  ?  I got more than 3 release channel that serving different purpose, it is safe to using eas build?

**Comment by remento-matheus** [comment]
Let's reopen this issue! It's still relevant and super valuable

**Comment by abdulmuksith3** [comment]
> So do `eas build --profile dev` is equal to `expo build --release-channel dev` ? I got more than 3 release channel that serving different purpose, it is safe to using eas build?

Yes, it is completely safe and the same. I also did migrate from expo build to EAS few weeks ago and I do have 3 release channels.  

To my knowledge the only differences between the two builds are: 
  1. EAS builds are faster and smaller in size.
  2. EAS build does not publish the build automatically, like expo build does. Which, is a good thing.
  3. EAS builds comply with the latest Android SDK requirements, idk if expo build complies.

**Comment by greeze** [comment]
No, I don't think it is the same. The `--profile <name>` pulls a statically-defined profile block out of `eas.json`. That block can contain a static `channel` value but does not allow the `channel` to be dynamically defined. (I haven't found the `channel` key to be respected at all during my `eas build` but that's probably a different bug.)

**Comment by moygoca1** [comment]
This needs to be reopen, we have a few release channels that we like to use for testing purposes before we were able to do:

 `expo build --release-channel ${RELEASE_CHANNEL} `

Now we have to hard code the release channel in eas.jso which removes the ability  to set them dynamically which is currently use by our CI, having multiple profiles is not a replacement for this issue.

**Comment by vince-roy** [comment]
`eas update --auto` seems to create a branch and a channel that have the name of the current git branch, but `eas build` has no such behaviour? Does anyone know how we're supposed to reconcile the two (especially in the context of continuous deployments via Github Actions)
