### ISSUE TITLE
Can't upgrade past version 0.4.3 due to git status check  

### ISSUE THREAD

**Issue by gjsduarte** [expo/eas-cli#324]
After upgrading past version 0.4.3 I can't build the project anymore due to the way the working directory is being checked for changes.

In my current CI pipeline, I'm bumping the mobile app version and **amending the current commit** with all the changes.
But when I run eas build on the next command it always fails with the output below:
```
Warning! Your git working tree is dirty.
This operation needs to be run on a clean working tree, please commit all your changes before proceeding.
    Error: Please commit all changes. Aborting...
```

Even after setting the `EAS_BUILD_AUTOCOMMIT=1` the error is still the same.

**Comment by wkozyra95** [comment]
`EAS_BUILD_AUTOCOMMIT=1` is intended to auto-commit if  eas-cli is making some changes during build, for the actual build process you still need clean git.

> In my current CI pipeline, I'm bumping the mobile app version and amending the current commit with all the changes.

Clearly, you are not if you see that message, run git status before build to check what files are you missing. 
btw if you piping stdout to file make sure it's not written to the directory with the project

**Comment by gjsduarte** [comment]
Thanks for the follow-up @wkozyra95. I was indeed piping the build output to a file within the project directory. Making sure that file is git ignored solved the problem.
