### ISSUE TITLE
Unable to access private scoped NPM packages during EAS Build

### ISSUE THREAD

**Issue by Joebourne** [expo/eas-cli#339]
Hi there 👋 

When running a hosted build triggered by `eas build --platform ios` it fails at the step `yarn install`, throwing the following error:

```
[stderr] error An unexpected error occurred: "https://registry.yarnpkg.com/@*****/*****/-/*****-2.3.16.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/expo/workingdir/build/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: yarn exited with non-zero code: 1Error: yarn exited with non-zero code: 1
```

Before I continue, here's some high level information about the project architecture:
- We're using a monorepo set up with `yarn workspaces` and the `yarn install` step is automatically run from the root by EAS CLI
- The app we're building is an ejected Expo app that sits at `./packages/[appName]` (where `.` is the repo root)
- The packages that are 404ing are inside another package at `./packages/mobile-app-core`

As per [the Expo documentation](https://docs.expo.io/build-reference/how-tos/#how-to-use-private-package-repositories), I am providing an `NPM_TOKEN` via Expo Secrets in the browser UI.

I have also tried adding a `.npmrc` file at the project root with the line `//registry.npmjs.org/:_authToken=${NPM_TOKEN}` as per the [NPM documentation](https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#create-and-check-in-a-project-specific-npmrc-file).

I replicated the workflow locally with the following steps and did not receive the same 404s as in EAS builds:
- log out of npm and yarn and run `yarn cache clean`
- run `yarn install` => seeing 404 when trying to access private packages ❌
- set `NPM_TOKEN` to the same value as being used in the EAS build server
- add a `.npmrc` file at the project root with the line `//registry.npmjs.org/:_authToken=${NPM_TOKEN}`
- run `yarn install` => installs successfully ✅

Here are a few more notes from the debugging process:
- having a `.npmrc` file in each package of the monorepo did not work
- I logged `NPM_TOKEN` during `yarn preinstall` just to make sure it was correct at the time of `yarn install`
- I tried to use `npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"` without success

Please could someone help with this issue? Is there anything unique about the EAS Build environment that might cause this? I can provide our Expo account details privately if someone from support would like a closer look.

Also, it would be really helpful if there was a way to SSH into the EAS build process, as debugging is very time consuming with logging as the only option. Is this possible or something Expo is looking into?

Thanks for your help! 🙇

**Comment by wkozyra95** [comment]
yarn have some weird behavior when registry in yarn.lock does not match registry that it should use(it's fixed in yarn 2, but it won't be backported to v1), also error message suggest that request was to `registry.yarnpkg.com` and i think it should be npm url there, but I'm not 100%, I didn't work with private registries much.

Thing you can try:
- using  exact node and yarn version you have locally (can be specified in eas.json), older version of yarn might not have that problem
- removing yarn.lock
- removing yarn.lock and running npm install
- removing `~/yarnrc.yml` (it's unlikely that this is an issue, but with yarn it's hard to tell)

**Comment by Joebourne** [comment]
Thanks for your help. 

As you suggest, I'm not trying to specify the Yarn and Node versions but it looks like my build is still trying to use NPM.

Here is my eas.json:
```
{
  "builds": {
    "ios": {
      "release": {
        "workflow": "generic",
        "node": "12.13.0",
        "yarn": "1.22.4"
      }
    }
  }
}
```

On the off chance you are Expo staff and can access builds, here's the one failing: https://expo.io/accounts/festicket/builds/13f8504b-4edf-4e1b-a60a-5c2bdc68e562/logs

In case you can't, here are the first few lines of the 'Install dependencies' step:

```
We have detected that 'packages/festicket-mobile-app' is a workspace
Running npm in the root dir of your repository 
[stderr] npm
[stderr] WARN deprecated @hapi/joi@17.1.1: Switch to 'npm install joi'
```

**Comment by wkozyra95** [comment]
What exactly did you change there? npm is used if there is package-lock.json and yarn when there is yarn.lock, so I assume you made all changes I suggested at once?

From logs I see that request is accessing http://10.254.24.9:4873 which is our npm cache, for private packages it shouldn't happen, do you ustill have npmrc in your project with config for private pacjkages?

**Comment by Joebourne** [comment]
Got there! In the end I changed my `.npmrc` file to this and it worked:

```
//registry.yarnpkg.com/:_authToken=${NPM_TOKEN}
registry=https://registry.yarnpkg.com/
```

While my `yarn.lock` file was pointing to packages in the Yarn registry, perhaps some sort of config on the build server was pointing it to NPM.

Thanks for your help. Is there a way for users to SSH into the EAS Builds? There's a very long feedback loop as it is, and it would make for a much smoother debugging experience.

**Comment by wkozyra95** [comment]
> Thanks for your help. Is there a way for users to SSH into the EAS Builds? There's a very long feedback loop as it is, and it would make for a much smoother debugging experience.

We don't plan to add any remote access to workers at this point, but it's possible we will get back to that in the future. We plan to support builds on the local machines, it wouldn't help in your specific case, but it should handle most of the same issue as remote access would.
