### ISSUE TITLE
How to use apt-get in EAS build hooks

### ISSUE THREAD

**Issue by Joebourne** [expo/eas-cli#342]
I'm trying to install some packages with `apt-get` as mentioned in the [Expo docs](https://docs.expo.io/build-reference/infrastructure/#configuring-build-environment). 

I've added the script `"eas-build-post-install": "../../scripts/ci/get-translations.sh"` in my package.json (using `../../` as my app is in a monorepo) and the `get-translations.sh` file is being run successfully.

It contains the following lines:
```
sudo apt-get -y update
sudo apt-get -yq install python-pip
sudo pip install --upgrade pip
sudo pip install transifex-client
```

The post install script fails with the following output:
```
[stderr] sudo: apt-get: command not found
[stderr] sudo: apt-get: command not found
[stderr] sudo: pip: command not found
[stderr] sudo: pip: command not found
```

I also tried running all commands without `sudo` and still got 'command not found' errors.

Please could you explain how to run `apt-get` in the build hooks?

Here's a build log in case seen by Expo staff: https://expo.io/accounts/festicket/builds/eb30aac4-bf89-4f55-aa60-a7934f100e5a/logs

**Comment by wkozyra95** [comment]
> I also tried running all commands without sudo and still got 'command not found' errors.

yes you need to run without sudo, I just tried ` "eas-build-pre-install": "apt-get update"` and it worked

**Comment by Joebourne** [comment]
@wkozyra95 I've tried it now in `eas-build-pre-install` 
```
Script 'eas-build-pre-install' is present in package.json, running it...
yarn run v1.22.10
$ npm config set "//registry.yarnpkg.com/:_authToken" "${NPM_TOKEN}" && npm config set registry "https://registry.yarnpkg.com/" && apt-get -y update && apt-get -yq install python-pip && pip install --upgrade pip && pip install transifex-client && tx pull --all --force --parallel --no-interactive
[stderr] /bin/sh: apt-get: command not found
```
and `eas-build-post-install` 
```
Script 'eas-build-post-install' is present in package.json, running it...
yarn run v1.22.10
$ apt-get -y update && apt-get -yq install python-pip && pip install --upgrade pip && pip install transifex-client && tx pull --all --force --parallel --no-interactive && yarn bundle:ios
[stderr] /bin/sh: apt-get: command not found
```
and I'm still getting 'command not found'.

Can you see anything wrong with my commands?

[eas-build-pre-install log](https://expo.io/accounts/festicket/builds/efa692a7-a68d-41b5-8469-d7501c749719/logs)
[eas-build-post-install log](https://expo.io/accounts/festicket/builds/5c49eef0-4f73-4d8b-9817-a9c184658de9/logs)

**Comment by wkozyra95** [comment]
How did you define it in package.json? maybe try adding in the first line of your script
```
#!/usr/bin/env bash
```
or if you write commands directly in package.json
```
"eas-build-post-install": "bash -c 'apt-get update && apt-get install somepackage'"
```

**Comment by wkozyra95** [comment]
You linked ios build, apt-get package manager command

**Comment by Joebourne** [comment]
Ahh of course, worked with `brew`. Why is `apt-get` described in the docs out of interest?

**Comment by wkozyra95** [comment]
because android builds are ran on linux

**Comment by Joebourne** [comment]
Makes sense. Thanks!

**Comment by Joebourne** [comment]
Do you have any advice for how to use the hooks for both platforms? I need to run an `eas-build-post-install` hook in my iOS and Android builds but if I put `apt-get` commands in the hook the iOS build will fail, and if I put `brew` commands in the hook the Android build will fail.

**Comment by wkozyra95** [comment]
there is a lot of options
- based on env $OSTYPE
- output of `uname -S`
- you can check with `command -v apt-get` before calling apt-get
