### ISSUE TITLE
Building Android apk results in aab file

### ISSUE THREAD

**Issue by IronYeti** [expo/eas-cli#347]
After submitting an Android build, with `"buildType": "apk"` and `"distribution": "internal"` the build service finishes.  It thinks it built an apk file ("You can download the APK file" and "Download APK" button) but the download link is, in fact, an aab file.

**Comment by brentvatne** [comment]
acknowledged, we will investigate shortly

**Comment by IronYeti** [comment]
Resolved in v0.11.0 release
https://github.com/expo/eas-cli/releases/tag/v0.11.0
