### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by brianhiss** [expo/eas-cli#356]
When I run `eas build --platform ios`, I eventually get an error after 30 minutes.

> Error: Timeout reached! It is taking longer than expected to finish the build, aborting...

Yes, the builds go on to eventually finish online.

It would be nice if we could set `timeoutSec` in `waitForBuildEndAsync()`, unless I am missing where we could do this?

https://github.com/expo/eas-cli/blob/db0b6bfcf5ad330e1c8b19072d3377d272360af1/packages/eas-cli/src/build/create.ts#L74

Having this throw an error makes running multiple bash commands after the build impossible unless we build a whole webhooks flow on top of this. It would be nice to chain bash commands after this to run `eas submit -p ios --latest` or something else.

At a minimum, maybe we can match the current [EAS Limitations](https://docs.expo.io/build-reference/limitations/) of 60 minutes, so at least the service expectations and cli tool are in sync there?

Hope this was the right place for this as it relates to the `eas-cli` package. Thank you, great product/service!

**Comment by brentvatne** [comment]
increased to 1 hour in #370
