### ISSUE TITLE
eas build pre command doesn't work with yarn 2 (berry)

### ISSUE THREAD

**Issue by natew** [expo/eas-cli#375]
If I just put something simple like `echo hi` it gives this:

```
Script 'eas-build-pre-install' is present in package.json, running it...
2
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)
3
4
$ yarn run [--inspect] [--inspect-brk] <scriptName> ...
5
yarn exited with non-zero code: 1
```

Which is a yarn 2 error code: https://discord.com/channels/695411232856997968/809586753719238656/837050004543111198

Perhaps needs to detect yarn 2 and run using vanilla npm. I'm trying to run something *before* iOS install, so another solution would be to add this hook:

`eas-build-pre-pod-install`

**Comment by wkozyra95** [comment]
it should work now
