### ISSUE TITLE
Can't run concurrent builds in CI

### ISSUE THREAD

**Issue by Joebourne** [expo/eas-cli#379]
Hi there,

We have multiple developers working on feature branches that use EAS to build internal distribution binaries for our testers to access.

However, when one branch is building and a second is triggered, the build fails and we receive the following error:

```
Your other builds are still pending. Wait for them to complete before running this command again.
```

Is there a way to queue EAS builds? We're currently running the following command:

```
eas build --profile release --platform all --non-interactive
```

I see there is a `--no-wait` flag, but in our case we need to wait for a successful EAS build before continuing with the next steps in CI.

Thanks!

**Comment by ide** [comment]
EAS Build in the preview is limited to one build per account for several reasons including capacity planning with hardware/cloud providers. If enough businesses need higher concurrency limits it might make sense for EAS to offer higher limits in an enterprise-like plan. Roughly how many concurrent builds do you think you would need?

**Comment by Joebourne** [comment]
Thanks for your reply.

We have 3 app devs working concurrently and pushing regularly, a `main` branch building several times a day, branches for previous versions of the app, and we have plans to grow the team.

One build at a time isn't going to be feasible for us! Devs will need to coordinate when they push code and constantly monitor the CI platform to avoid build failures.

Is there not generally demand for enterprise use already?

**Comment by wkozyra95** [comment]
We changed it here https://github.com/expo/eas-cli/commit/342c78a4f6eab058f837e12305a8ec8d9e005310 , but it's not released yet. The concurrency limit is still 1, but you will be able to schedule more than one build at the time

When EAS will go out of "preview" phase there will be different concurrency options, but neither pricing nor what those options will be is not yet finalized.

**Comment by Joebourne** [comment]
Ok thanks @wkozyra95.

Is there a timeline for leaving the 'preview' phase?

**Comment by ide** [comment]
We'll announce on blog.expo.io when there is an update.

**Comment by brentvatne** [comment]
we don't have an exact timeline, but it's in the order of months - if that helps with your planning.
