### ISSUE TITLE
iOS build fails for App store distribution in non-interactive mode 

### ISSUE THREAD

**Issue by vladimir-neykov-mw** [expo/eas-cli#393]
Hello,

our project's CI/CD pipeline (non-interactive mode) executes the following command 

> npx eas-cli@0.13.0 build --platform ios --profile $BITBUCKET_DEPLOYMENT_ENVIRONMENT --non-interactive

and stops with the message

> Distribution Certificate is not validated for non-interactive builds.

The certificates are valid. The distribution mode is ```store```.
The additional option ```--skip-credentials-check```  does not help, same result there. 
Why do the commands stop there and do not trigger the remote Expo builds service?
<br/><br/>
On the other side following command works

> npx eas-cli@0.12.0 build --platform ios --profile $BITBUCKET_DEPLOYMENT_ENVIRONMENT --non-interactive --skip-credentials-check

and the ipa artifact is created in Expo.

**Comment by rimidalv2018** [comment]
> npx eas-cli@0.14.1 build --platform ios --profile $BITBUCKET_DEPLOYMENT_ENVIRONMENT --non-interactive

works now. Thank you!

The command outputs 

> Distribution Certificate is not validated for non-interactive builds.
Skipping Provisioning Profile validation on Apple Servers because we aren't authenticated.

and successfully continues the build at Expo side.
