### ISSUE TITLE
Build fails silently from CI in non-interactive mode

### ISSUE THREAD

**Issue by couchcryptid** [expo/eas-cli#395]
Running eas (0.14.0) build as part of my Gitlab CI pipeline and this is as far as it gets before failing silently:
```
$ eas build --platform all --non-interactive --profile dev
- Linking to project @org/project
✔ Linked to project @org/project
✔ Using remote Android credentials (Expo server)
- Uploading to EAS Build (0 / 1.7 MB)
✔ Uploaded to EAS 
✔ Using remote iOS credentials (Expo server)
```

It was working on 5/7, so I tried downgrading back to 0.13.0, but no dice. To make matters more confusing, the same code runs perfectly locally. Have tried completely nuking my credentials and access tokens and recreating them, but that doesn't seem to the the issue either.

**Comment by macsj200** [comment]
I am also seeing this on my project. It also seems to be failing silently locally.

**Comment by yohanndulong** [comment]
Same problem

`eas build --platform ios
√ Linked to project @helyxteam/toodays-staging
√ Using remote iOS credentials (Expo server)
If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them.
This is optional, but without Apple account access you will need to provide all the values manually and we can only run minimal validation on them.
√ Do you want to log in to your Apple account? ... yes

› Log in to your Apple Developer account to continue
√ Apple ID: ... xxxxx@xxxxx.io
› Restoring session C:\Users\xxxx\.app-store\auth\xxxx\cookie
› Team Helyx (XXXX)
› Provider Helyx (XXXX)
√ Logged in Local session
√ Bundle identifier registered io.xxxx
√ Synced capabilities
√ Fetched Apple distribution certificates`

**Comment by yohanndulong** [comment]
It's works ! Thx!
