### ISSUE TITLE
Synced capabilities: Disabled: Associated Domains

### ISSUE THREAD

**Issue by berkcoker** [expo/eas-cli#421]
Even though I have defined the associatedDomains field in app.json, the "eas build" command disables this functionality on my Apple Identifier. Any ideas on how to resolve this problem?

**Comment by brentvatne** [comment]
hi there! please update to eas-cli 0.15.1, this will handle syncing entitlements correctly for managed projects on eas build

**Comment by JAWS-tm** [comment]
Hi ! I'm facing the same issue, I have the `associatedDomains` property set for the `webcredentials` but when I run `eas build` EAS disable the Associated Domains capability : 
`Synced capabilities: Enabled: Sign In with Apple | Disabled: Associated Domains`
