### ISSUE TITLE
Error: Could not read bundle identifier from Xcode project.

### ISSUE THREAD

**Issue by TrevorNovak** [expo/eas-cli#425]
I am trying to migrate away from `expo build` to `eas build` however, I am getting this error `Error: Could not read bundle identifier from Xcode project.` when attempting to build our iOS app. We have had our bundle identifier in the `app.config.js` file, however, that appears to be deprecated. The migration docs do not describe how to setup expo and xcode together and I have tried everything I can think of to no avail. Am I missing something here? Are there any docs that you can point me to so that I can properly configure iOS? I have run `eas build:configure` but the result is

```
✔ Which platforms would you like to configure for EAS Build? › All

✔ Validated eas.json
✔ iOS project configured

✔ No changes were necessary, the project is already configured correctly.

🎉 Your iOS and Android projects are ready to build.

- Run eas build when you are ready to create your first build.
```

Any help would be appreciated.

**Comment by dsokal** [comment]
Hi!
From what I understand, you previously had a managed workflow project and you converted it to bare workflow. Could you tell me what steps you followed to do so? Have you run `expo eject` or just started the new project from scratch? I'd be grateful for the repro steps.

**Comment by TrevorNovak** [comment]
> Hi!
> From what I understand, you previously had a managed workflow project and you converted it to bare workflow. Could you tell me what steps you followed to do so? Have you run `expo eject` or just started the new project from scratch? I'd be grateful for the repro steps.

Hi dsokal. We are still using a managed workflow. I am simply trying to pivot from `expo build` to `eas build`. The migration docs that I am referring to are these https://docs.expo.io/build-reference/migrating/ -- I was under the impression that EAS is now ready for managed workflows to migrate. Is this incorrect?

**Comment by dsokal** [comment]
Sorry for the late response. I must have overlooked the notification. 

The `Error: Could not read bundle identifier from Xcode project` error can only appear when you have a "generic" project (a one that has `ios` and `android` directories in the project root, those contain Xcode and Gradle projects). This is why I asked if you've run `expo eject` because this command converts a managed workflow project to a bare (generic) one.

- Can you show the contents of the `eas.json` file? 
- Do you have `android` and/or `ios` directories in the root of your project?

**Comment by TrevorNovak** [comment]
@dsokal Thanks for your help. It appears that there was a ios directory in our project for some unknown reason. I did not put these two things together but after you mentioned it, I removed it and it builds now. Thanks for your help!
