### ISSUE TITLE
How to submit latest Android EAS build in CI environment

### ISSUE THREAD

**Issue by cesargdm** [expo/eas-cli#428]
I would expect to be able to submit an android  eas build from a CI environment by running

```
eas submit -p android --latest --key=/path/to/google-services.json
```

But I don't think by having a .json file in my repo is a good security practice. Is there a way to upload the .json to your servers or to specify the value in a env variable?

I don't have any trouble with iOS by doing `EXPO_APPLE_APP_SPECIFIC_PASSWORD=xxx eas submit -p ios --latest --apple-id=user@example.com --asc-app-id=1234567890`

Thanks in advance.

**Comment by nitrique** [comment]
Hi, you probably don't need the google-services.json but the authentication credentials as described here https://github.com/expo/fyi/blob/master/creating-google-service-account.md

**Comment by cesargdm** [comment]
@nitrique thanks! I've already followed that guide, but I could not get it to work. Maybe I'm doing something wrong. I'll try to setup that again.

**Comment by dsokal** [comment]
You don't need to commit the json file to the repo.
- Convert your `google-services.json` file to a base64-encoded string like this:
  `$ base64 google-services.json`
- Copy the output of the command and set an env variable on your CI, sth like `GOOGLE_SERVICES_BASE64`
- Later, in a bash script:
   `echo $GOOGLE_SERVICES_BASE64 | base64 --decode > google-services.json`
- Now you can use the json the same way as on your local machine:
  `eas submit -p android --latest --key=/path/to/google-services.json`
