### ISSUE TITLE
Error: Build configuration 'Release does not exist in list with id

### ISSUE THREAD

**Issue by nitrique** [expo/eas-cli#430]
Hi,

From about 2 days, we get the following error on our build environment :

```bash
All credentials are ready to build @e*****/e***** (com.*******.***)
- Compressing project files
- Uploading to EAS Build (0 / 8.7 MB)
✔ Uploaded to EAS 1s
    Error: Build configuration 'Release does not exist in list with id 
    '00E357021****517003FC87E'
```

Used CLI version : `"eas-cli": "^0.16.0",`

Nothing changed on our side on build script. We are on gitlab's CI/CD env with docker runner in private env.

Thanks,
Regards.

Nicolas

**Comment by adrian-chang-alcover** [comment]
I have the same issue even on an empty new project created by `npx react-native init AwesomeTSProject --template react-native-template-typescript` and followed by `eas build:configure` and `eas build --platform ios`

**Comment by cjoftheweb** [comment]
This only seems to happen with `0.16`. Downgrading to `0.15.1` fixed the issue for me.

**Comment by Noxel** [comment]
Same for me, downgrading to 0.15.1 fixed the issue.

**Comment by nitrique** [comment]
Same here, as mentioned on Discord, 0.15.1 fixed the issue. Hope next version will fix it.
Suggest to keep this ticket open and keep it until next working version

**Comment by brentvatne** [comment]
thank you @adrian-chang-alcover for the information. we'll look into it.

**Comment by dsokal** [comment]
This will be fixed in the next EAS CLI release.
