### ISSUE TITLE
EAS Build Error: Unable to resolve module react/jsx-runtime from /build/workingdir/build/.../App.tsx: react/jsx-runtime could not be found within the project.

### ISSUE THREAD

**Issue by chybisov** [expo/eas-cli#433]
I have a problem with eas build, it gives me this error.
![image](https://user-images.githubusercontent.com/18644653/120196623-bb319000-c228-11eb-8a61-604d1997a1e3.png)

babel.config.js ->

```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ['babel-preset-expo'],
    ],
    plugins: [
      ['@babel/plugin-transform-react-jsx', {
        runtime: 'automatic',
      }],
      ['formatjs', {
        idInterpolationPattern: '[sha512:contenthash:base64:6]',
        ast: true
      }],
      'inline-dotenv',
      'react-native-reanimated/plugin',
    ],
  };
};
```

eas.json ->

```
{
  "builds": {
    "android": {
      "release": {
        "workflow": "managed",
        "env": {
          ...
        },
        "releaseChannel": "production",
        "node": "16.2.0",
        "yarn": "1.22.5"
      }
    },
    "ios": {
      "release": {
        "workflow": "managed",
        "env": {
          ...
        },
        "releaseChannel": "production",
        "node": "16.2.0",
        "yarn": "1.22.5"
      }
    }
  }
}
```

I've tried all the standard stuff like removing node_modules, cleaning metro cache etc. I think it's something with the new jsx transform feature. It works perfectly with classic build and in dev mode, but maybe EAS somehow not understand how to deal with it.

Btw everything works with the new `expo run:android`.

Build ID: 6d009733-316a-4d65-9ca4-74edff70bd69

**Comment by brentvatne** [comment]
try doing a fresh clone of your project into a new directory on your computer and running `expo run:ios` from there, i would expect that you will see the same error

**Comment by chybisov** [comment]
@brentvatne I'm using windows and can't run ios build, all of the above are about android, but eas build fails for ios as well. As I know local eas build currently not work with windows.

**Comment by brentvatne** [comment]
this seems to be some issue with @babel/plugin-transform-react-jsx - i don't know what exactly could be going wrong but i have no reason to believe it is related to eas build. if you can create a minimal reproducible example i'd be happy to investigate. otherwise you can try removing that from your project and see if it builds, then go from there.

**Comment by chybisov** [comment]
@brentvatne this issue still present. I'll try to make a reproducible example next week.

**Comment by brentvatne** [comment]
feel free to ping me when you have that and i'll reopen

**Comment by chybisov** [comment]
@brentvatne hi! Here is an example code [eas-example.zip](https://github.com/expo/eas-cli/files/6763567/eas-example.zip). It produces the same error as in Build ID above.

**Comment by brentvatne** [comment]
@chybisov - you are using react@17 in that project, that version is not supported in react-native@63. see: https://github.com/facebook/react-native/blob/27651720b40cab564a0cbd41be56a02584e0c73a/package.json#L84-L86

**Comment by chybisov** [comment]
@brentvatne I've downgraded react to v16.13.1 and issue still present with exactly same error.

**Comment by brentvatne** [comment]
@chybisov - afaik the 'automatic' runtime in @babel/plugin-transform-react-jsx only works in react@17

**Comment by chybisov** [comment]
@brentvatne so after expo includes RN 64 in the next release it should work?

**Comment by brentvatne** [comment]
yup
