### ISSUE TITLE
 eas build

### ISSUE THREAD

**Issue by Jparrgam** [expo/eas-cli#435]
Hello everyone, I have an error when creating a build with eas, I send you the specific error that it gives me in the terminal

`eas build -p android --profile develop`

`Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, please report the issue.
    CombinedError: [GraphQL] Unexpected server error.
`

**Comment by johntvogt** [comment]
I am getting the same issue since yesterday as well....just did a re-run of the failed job I have and it worked so looks like a glitch but would be nice to know what happened from the Expo team!!!
