### ISSUE TITLE
Fix typo: Expo CLI -> EAS CLI

### ISSUE THREAD

**Issue by brentvatne** [expo/eas-cli#450]
https://github.com/expo/eas-cli/blob/2bdaa0d428a3170a7b92debf8745f7f2f4f7a26c/packages/eas-cli/src/project/ios/scheme.ts#L77

**Comment by dsokal** [comment]
https://github.com/expo/eas-cli/commit/176026645c1a91c6134202cd3b4e2dbb80ddfdbf
