### ISSUE TITLE
v0.17.0 mistakenly disabled Sign in with Apple entitlement

### ISSUE THREAD

**Issue by cruzach** [expo/eas-cli#452]
In a bare project with 
```
<key>com.apple.developer.applesignin</key>
    	<array>
		<string>Default</string>
	</array>
```

included in entitlements, and 
```
"ios": {
      "usesAppleSignIn": true
    },
```
    
in app.json. Running `eas build -p ios` results in:

```
✔ Logged in Local session
✔ Bundle identifier registered
✔ Synced capabilities: Enabled: Apple Pay Payment Processing | Disabled: Sign In with Apple
```

(see **Disabled: Sign In with Apple**)

reverting to v0.16.0 fixes the behavior, so looks like this was a regression

**Comment by cruzach** [comment]
looks like this is due to how we're parsing the xml files...

the only way to repro is to add spacing to the entitlements file. so this works:
```
<plist version="1.0">
  <dict>
    <key>aps-environment</key>
    <string>development</string>
    <key>com.apple.developer.applesignin</key>
    <array>
      <string>Default</string>
    </array>
  </dict>
</plist>
```
but this doesnt:
```
 <plist version="1.0">
  <dict>
    <key>aps-environment</key>
    <string>development</string>
<key>com.apple.developer.applesignin</key>
    	<array>
		<string>Default</string>
	</array>
  </dict>
</plist>
```
here is a repro- https://github.com/cruzach/eas-cli-452

**Comment by dsokal** [comment]
@cruzach I tried to repro that and it worked fine with both files :/

**Comment by dsokal** [comment]
<img width="885" alt="Screenshot 2021-06-14 at 16 47 40" src="https://user-images.githubusercontent.com/5256730/121911784-57cb5600-cd30-11eb-8f19-30a224a038be.png">

**Comment by dsokal** [comment]
I also tried to repo the issue with the example app you provided - https://github.com/cruzach/eas-cli-452 - but with no luck. I'd grateful for detailed repro steps.

**Comment by cruzach** [comment]
Hm I know I was able to repro with that repo earlier, but now cloning it and running the same commands doesn't reproduce it for me either 🤔 

I'll close this for now until I find a way to reliably reproduce it

**Comment by summerkiflain** [comment]
@cruzach This issue is happening for me too: I have enabled sign in with Apple capability in both apple portal and entitlements file, but running `eas build --profile staging --platform ios` disables it `✔ Synced capabilities: Enabled: Associated Domains | Disabled: Sign In with Apple` and then eas build fails due to missing capability. how can I fix this, I have tried enabling and regenerating provisioning profiles multiple times but its doesn't fix the issue.
