### ISSUE TITLE
Inherit from platform independent base

### ISSUE THREAD

**Issue by brian-visikon** [expo/eas-cli#463]
We currently have a set of environment specific environment variables defined inside eas.json.
These are the same for different platforms.

We obviously also use the same the same workflow for all platforms.

But inheritance only works when extending configurations from inside the same platform, apparently you cannot have configurations outside the specific platforms.

This leads to a lot of duplicate information, which need to be maintained in several places.

I would love to have something like this:
```{
  "builds": {
    "qa": {
      "workflow": "generic",
      "distribution": "internal",
      "env": {
        "SOME_ENV_VAR": "42",
        "MANY_MORE": "true"
      }
    },

    "prod": {
      "workflow": "generic",
      "env": {
        "SOME_ENV_VAR": "foo",
        "MANY_MORE": "true"
      }
    },

    "android": {
      "preview": {
        "extends": "qa"
      },
      "release": {
        "extends": "prod"
      }
    },

    "ios": {
      "preview": {
        "extends": "qa",
        "enterpriseProvisioning": "universal"
      },
      "release": {
        "extends": "prod"
      }
    }
  }
}
```

**Comment by brentvatne** [comment]
this does indeed seem to be useful! we'll consider this or something similar that would solve the same issue

**Comment by dsokal** [comment]
This can be solved with the new `eas.json` format. See https://docs.expo.dev/build/eas-json/


```
{
  "build": {
    "prod": {
      "env": {
        "SOME_ENV_VAR": "foo",
        "MANY_MORE": "true"
      },
      "android": { ... },
      "ios": { ... }
    },
    "qa": {
      "env": {
        "SOME_ENV_VAR": "42",
        "MANY_MORE": "true"
      },
      "android": { ... },
      "ios": { ... }
    }
  }
}
```
