### ISSUE TITLE
Viewing the git hash

### ISSUE THREAD

**Issue by brian-visikon** [expo/eas-cli#466]
When doing a lot of builds, being able to see the git hash of a build would be a real time saver.

I'm running the latest 0.17.0 client, and according to the changelog, the hash has been sent to the server since 0.6.0.

But how do I view it?

It's not in the web console and it's also not included when doing a `eas build:view $build_id`.

**Comment by brentvatne** [comment]
hi there! this is included in build metadata on the website now, and we plan to include this in the `eas build:view` and `eas build:list` metadata soon as well :)
