### ISSUE TITLE
building on own infrastructure is using the wrong port for loading the js bundle

### ISSUE THREAD

**Issue by f-ricci** [expo/eas-cli#471]
What am I trying to accomplish?

A bare workflow build with a physical device as target in order to develop the IAP integration.

------

The command I'm using is:

`eas build --platform ios --profile dev --local`

my `eas.json` looks like this

```json
{
  "builds": {
    "android": {
      "release": {
        "workflow": "managed"
      }
    },
    "ios": {
      "dev": {
        "distribution": "internal",
        "workflow": "generic",
        "credentialsSource": "local",
        "schemeBuildConfiguration": "Debug",
        "env": {
          "ENVIRONMENT": "dev",
          "RCT_METRO_PORT": "19000"
        }
      },
    }
  }
}
```

Even though I specify the `RCT_METRO_PORT` to be the same as the port `expo start` uses.

I also tried to build using the remote eas build service but with luck as the app crashes on the launch screen.

*Quick Solution*

The solution for now is to develop using `RCT_METRO_PORT=8081 react-native start`.

*Real solution*

Provide the same configuration to the eas build as the one used for the `expo start` in order to maintain consistency.

**Comment by brentvatne** [comment]
it sounds like your concern is that building locally the env var isn't being set? does the `"ENVIRONMENT": "dev"` env var have the expected side effect for you?

**Comment by f-ricci** [comment]
@brentvatne "...building locally the env var isn't being set?..." Not quite.

The variables present in the `"env"` key are set correctly inside the app but they might not be correctly forwarded to the adequate processes that actually build app during the multi step phase that take place when building the app.

**Comment by brentvatne** [comment]
@f-ricci - if you'd like to investigate, please prefer to http://github.com/expo/eas-build - it's all open source.

**Comment by wkozyra95** [comment]
- envs are passed to gradlew call correctly if they are not passed further to the packager then you need to handle that in your native project config
- for a managed project, development-client is a recommended approach (you can also use it in bare projects, but you would need to configure your project to support that) https://docs.expo.io/clients/introduction/
