### ISSUE TITLE
Error: Generating a new Keystore is not supported in --non-interactive mode

### ISSUE THREAD

**Issue by oriharel** [expo/eas-cli#476]
Hi, 
Since the last update (0.18) I'm getting this when I run
`eas build --platform all --non-interactive`
In my CI:
`Error: Generating a new Keystore is not supported in --non-interactive mode`
 
I have credentials set on Android (Classic) and it used to work.
Please help.

**Comment by quinlanj** [comment]
You can fix this by copying your Android Classic credentials to the EAS credentials. You can do this in our UI by:
1. Going to the Android Classic credentials tab for your project: [https://expo.io/accounts/[account]/projects/[project]/credentials?platform=android-classic](https://expo.io/accounts/[account]/projects/[project]/credentials?platform=android-classic)
2. Download the keystore
3. Go to the Android EAS credentials tab and upload the keystore

I've attached some screenshots below for clarification. Also, it is nice to hear from you again @oriharel  , sorry for the inconvenience!
![Screen Shot 2021-06-25 at 12 16 05 PM](https://user-images.githubusercontent.com/6380927/123475427-3e3bd100-d5b0-11eb-82f1-794058f01ede.png)
![Screen Shot 2021-06-25 at 12 16 22 PM](https://user-images.githubusercontent.com/6380927/123475432-3f6cfe00-d5b0-11eb-9fb4-e73385830353.png)

**Comment by oriharel** [comment]
I ended up running `eas build --platform android` on eas-cli 0.18.1, and probably based on what @brentvatne it just updated automatically.
