### ISSUE TITLE
Google Api Error: Changes cannot be sent for review automatically

### ISSUE THREAD

**Issue by robertherber** [expo/eas-cli#489]
I'm getting the following when publishing to Google Play:
```log
Google Api Error: badRequest: Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the Google Play Console UI. - Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true. Once committed, the changes in this edit can be sent for review from the Google Play Console UI.
```

Seems like it works ONCE after promoting the internal track to the alpha track. But obviously I don't want to do that manually every time - now I'm stuck with a failing CI.

I've tried with different release status flags - but all result in this error. Any ideas?

**Comment by barthap** [comment]
Related https://github.com/fastlane/fastlane/issues/18670

**Comment by techpanga** [comment]
Hope someone can help from expo. We are using paid service for expo.

**Comment by barthap** [comment]
As the fix was released with fastlane 2.189.0 (https://github.com/fastlane/fastlane/pull/19117), it can be applied to EAS Submit too. It will be implemented soon.

For clarification, what `changesNotSentForReview` means (from [Google Play API docs](https://developers.google.com/android-publisher/api-ref/rest/v3/edits/commit#query-parameters)):

> Indicates that the changes in this edit will not be reviewed until they are explicitly sent for review from the Google Play Console UI. These changes will be added to any other changes that are not yet sent for review.

**Comment by barthap** [comment]
For anyone still having this issue:
This was resolved in `eas-cli@0.24.1`, when you encounter this error, re-run submission with:
```
eas submit -p android --changes-not-sent-for-review
```

**Comment by tyrauber** [comment]
Anyone have any idea why I might be running into this issue with `eas-cli/0.36.1`? `changes-not-sent-for-review` does not appear to be a command line argument.
```
$ eas submit -p android --profile production --changes-not-sent-for-review
 ›   Error: Unexpected argument: --changes-not-sent-for-review
 ```

**Comment by wkozyra95** [comment]
all platform specific options for submit were moved to eas.json submit profile

https://docs.expo.dev/submit/eas-json/

**Comment by tyrauber** [comment]
Ahh,  perfect! Thank you @wkozyra95

**Comment by wkozyra95** [comment]
> EAS submit profile isn't being picked up or merged correctly.

You need to specify name of the profile, by default `eas submit` is using profile `production` if it's defined

**Comment by ZEAL-MATCH-LTD** [comment]
@wkozyra95 Well spotted, thank you for your swift response. i can see that the `changesNotSentForReview` flag is now being merged in.
