### ISSUE TITLE
 Location in the UIBackgroundModes key

### ISSUE THREAD

**Issue by berkcoker** [expo/eas-cli#506]
The `eas build` command seems to be adding "location" to the UIBackgroundModes key in our Info.plist. Our binary is rejected due to this behavior on AppStore. Simply using `expo build:ios` however does not produce the same behavior. Would appreciate the help, we like this new service, but cannot use it currently.

**Comment by brentvatne** [comment]
hi there! do you have `expo-task-manager` or `expo-background-fetch` installed in your project?

**Comment by fab-c** [comment]
Same here. Our app.json define only "fetch" in "UIBackgroundModes"
```
        "UIBackgroundModes": [
          "fetch"
        ]
```
but after `eas build` info.plist contains "fetch", "location" and Apple reject our app due to "location" in "UIBackgroundModes".

We love eas, and we hope it will be fixed quickly ;)

In the meantime, we will use `expo build` and `eas submit`

**Comment by brentvatne** [comment]
@fab-c - you can work around this by removing `UIBackgroundModes` from expo-task-manager and expo-background-fetch plugins in your node_modules using patch-package. we'll address this in our next sdk release

**Comment by brentvatne** [comment]
related: https://github.com/expo/expo/pull/13888

**Comment by brentvatne** [comment]
this will be resolved in sdk 43 thanks to https://github.com/expo/expo/pull/14142. until then, you can use the workaround described above: https://github.com/expo/eas-cli/issues/506#issuecomment-888703012

**Comment by fimbres** [comment]
I'm still facing this in sdk 51, how can I remove this permission in my app?

**Comment by maskowe** [comment]
Any new information….am also on SDK 51 and am getting rejected with this using EAs build.?

**Comment by maskowe** [comment]
> [@fab-c](https://github.com/fab-c) - you can work around this by removing `UIBackgroundModes` from expo-task-manager and expo-background-fetch plugins in your node_modules using patch-package. we'll address this in our next sdk release

Do you have a solution yet for expo 51 version?   Thanks

**Comment by maskowe** [comment]
For anyone else, I corrected this by uninstalling expo task manager and taking the fetch out of the ios inforPList values.
