### ISSUE TITLE
ERRRO BUILD

### ISSUE THREAD

**Issue by igorskiter** [expo/eas-cli#510]
In build show this massege "Error: There is no profile named base for platform android" and even running the command eas build:configure I can't run the build.

**Comment by dsokal** [comment]
Hi!
Can you please share your eas.json and let me know what's the exact command you executed?

The error message is basically saying that there's no build profile named "base" for platform "android" in eas.json.

**Comment by brentvatne** [comment]
it sounds like you are trying to run a build for a profile named "base" when that isn't defined in eas.json

**Comment by brentvatne** [comment]
closing this but happy to help if we hear back.
