### ISSUE TITLE
Setting EAS environment variables in app.config.js

### ISSUE THREAD

**Issue by wbobeirne** [expo/eas-cli#528]
I'm using the [suggested environment variable technique of setting the `.extra` key on my manifest](https://docs.expo.io/guides/environment-variables/#using-app-manifest--extra), and reading from `expo-constants` in my app. When I try to use this technique in combination with `eas.json` env variables, it doesn't work because the environment variables don't seem to be available in `app.config.js`, so the extra keys aren't set.

I could load the `eas.json` myself and use `process.env.EAS_BUILD_PROFILE ` to load it, but then I can't have different env vars for iOS and Android since there's no `EAS_BUILD_PLATFORM`, so I'd have to either go with Android or iOS. Something like this:

```ts
import easBuildConfigs from './eas.json';

const easConfig = easBuildConfigs.builds.android[process.env.EAS_BUILD_PROFILE];
const ENV_VAR = easConfig?.env?.SITE_URL || process.env.ENV_VAR;

export default {
  /* ... */
  extra: {
    ENV_VAR,
  }
}
```

I also assume this wouldn't work with secret env vars either, though I haven't tried. I didn't see any suggested approaches for how to combine these two, so let me know if there's something better I should be doing.

**Comment by wbobeirne** [comment]
I just decided to maintain my own environment variable dictionaries in `app.config.js` and use `EAS_BUILD_PROFILE` to select from that. I'll leave this issue open in case I just have this wrong, but that seems like the simplest solution.

**Comment by wkozyra95** [comment]
Sth like that is already in progress, when running `eas build` all the values from `env` field in eas.json for selected profile will be loaded into environment before evaluating app.config.js. We are also considering adding env with build profile name, but I'm not sure if we decided on that yet.

For now the only approach is to duplicate those envs in local environment and in eas.json

**Comment by wbobeirne** [comment]
Yeah, you also can't rely on `eas.json` in there because doing a regular `expo publish` wouldn't get the vars either, so it needs to handle both cases. Feel free to close out if y'all don't feel this problem represents an actionable issue, or if you already had something open for the work you mentioned.

**Comment by Ricool06** [comment]
Hi so just a quick one: the fix by @wkozyra95 seems to only work on Android. For iOS builds, I have to use @wbobeirne's workaround (editing the app.config.js to explicitly include content from eas.json).

**Comment by wkozyra95** [comment]
@Ricool06 it will be fixed in the next release, but either way it shouldn't affect you. envs were not passed to the function that just resolved ios entitlements,  which I assume are always the same in your app. I assume it didn't work for you because you threw an error if some env was missing
