### ISSUE TITLE
"eas build --platform ios" command silently fails

### ISSUE THREAD

**Issue by sebastianekstrom** [expo/eas-cli#529]
## What
I've managed to run `eas build --platform ios` a few times in the past, but as of today I can no longer run the command, it fails right away with the following prompt:

```
~/projects/<project-name> on master
$ eas build --platform ios
✔ Linked to project @XXX/<project-name>

We've found multiple schemes in your Xcode project:

~/projects/<project-name> on master
```

I get no prompt or anything, the process just ends.

## Why
After some debugging by manually adding logs in the CLI on my local machine (`/usr/local/lib/node_modules/eas-cli`) I've noticed that the culprit is that `scheme` is an empty array (`[]`) here: https://github.com/expo/eas-cli/blob/0e7d7f765a4a842a948a9ba13ec17a06a66ebfb0/packages/eas-cli/src/project/ios/scheme.ts#L65

## My local env
`eas-cli/0.22.0 darwin-x64 node-v12.13.0`

Please let me know if I can provide any more info to help debug the issue!

**Comment by wkozyra95** [comment]
Can you check if you have a file `ios/*.xcodeproj/xcshareddata/xcschemes/*.xcscheme`
- if there is no file matching that, open your project in xcode and change scheme to shared(it will create that file)
- if file exists please post here the content and name
Also include output of `xcodebuild -list` called from ios directory

If it's a bug on our side specifying scheme name in eas.json should fix that, if not then there is problem with you project config. Scheme name is the name of the `.xcscheme` file

**Comment by sebastianekstrom** [comment]
Hey @wkozyra95!

I have no files at all in the `ios/*.xcodeproj/xcshareddata/xcschemes` folder, as a matter of fact all of these folders, and/or their child folders, are empty:
```
~/projects/*/ios/ProjectName
~/projects/*/ios/ProjectName.xcworkspace
~/projects/*/ios/ProjectName.xcodeproj
```

which means I can't open the project in Xcode.

Output of `xcodebuild -list` command:

```
$ xcodebuild -list
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -list

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

xcodebuild: error: The directory /Users/*/projects/* does not contain an Xcode project, workspace or package.
```

**Comment by wkozyra95** [comment]
if you want to build bare project you need to fix(or add in this case) native code
if you want to build managed project remove ios directory
