### ISSUE TITLE
eas under pipeline

### ISSUE THREAD

**Issue by jacyuan** [expo/eas-cli#548]
Hi,

I tried to use eas build in pipeline. The EXPO_TOKEN is configured as env variable.

When we do `eas build -p ios --profile xxx`, the cli ask us to login for our apple account.

Is there a way to set some env variables, in order to avoid these manuel interactions please ?

Thanks a lot.

**Comment by brentvatne** [comment]
please refer to https://docs.expo.dev/build/building-on-ci/
