### ISSUE TITLE
Multiple ways of logging, which one should we use for new commands?

### ISSUE THREAD

**Issue by byCedric** [expo/eas-cli#55]
I see that the [`eas whoami`](https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/commands/whoami.ts#L4) command [uses this logger](https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/log.ts). But I also see that the [`eas login`](https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/commands/login.ts#L9) and [`eas logout`](https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/commands/logout.ts#L10) both use `this.log`. Which one is preferred?

**Comment by fson** [comment]
`this.log` defined in the command base class is the "default" in oclif, but using it outside the command methods is tedious. We could define a custom `Command` base class to make it also use `log.ts`, but it seems easier to just not use `this.log`.
