### ISSUE TITLE
(IOS) EAS throw error if i set CFBundleVersion and CFBundleIdentifier how environment variables

### ISSUE THREAD

**Issue by khomyn01** [expo/eas-cli#551]
Info.plist
`
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
`
Error:
<img width="467" alt="Screenshot 2021-08-06 at 17 30 07" src="https://user-images.githubusercontent.com/62264019/128525906-db5698dd-503c-42fa-8cf2-5f051c6e0c50.png">

This error does not throw with eas-cli@0.21.0

**Comment by brentvatne** [comment]
what version of eas-cli are you using?

**Comment by brentvatne** [comment]
this should have been fixed in the latest eas-cli (0.23.0) - https://forums.expo.dev/t/eas-build-fails-after-upload-ios/55210/8
