### ISSUE TITLE
EAS build issue on Android and IOS

### ISSUE THREAD

**Issue by okeybond** [expo/eas-cli#557]
Trying to use EAS Build on a existing expo project and getting the below error for iOS

`› Compiling Pods/Pods-NaijaWorld » Pods-NaijaWorld-dummy.m
› Packaging Pods/Pods-NaijaWorld » libPods-NaijaWorld.a
› Executing NaijaWorld » [CP] Check Pods Manifest.lock
› Executing NaijaWorld » Start Packager
› Compiling NaijaWorld » noop-file.swift
› Compiling NaijaWorld » main.m
› Compiling NaijaWorld » app_vers.c
› Compiling NaijaWorld » AppDelegate.m
› Linking   NaijaWorld » app
⚠️  ld: method '+UIDatePickerMode:' in category from /Users/expo/Library/Developer/Xcode/DerivedData/NaijaWorld-gtomxvmgdquxugbdwnnkqbcfpuic/Build/Intermediates.noindex/ArchiveIntermediates/NaijaWorld/BuildProductsPath/Release-iphoneos/React-Core/libReact-Core.a(RCTDatePickerManager.o) conflicts with same method from another category

❌  ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1205.0.22.9.0_0' Reader: '1200.0.32.29_0')', using libLTO version 'LLVM version 12.0.0, (clang-1200.0.32.29)' for architecture arm64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

⚠️  Pods/boost-for-react-native: iOS@8.0 deployment version mismatch, expected >= 9.0 <= 14.4.99
⚠️  Pods/GoogleSignIn: iOS@8.0 deployment version mismatch, expected >= 9.0 <= 14.4.99
⚠️  Pods/AppAuth: iOS@7.0 deployment version mismatch, expected >= 9.0 <= 14.4.99
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	Ld /Users/expo/Library/Developer/Xcode/DerivedData/NaijaWorld-gtomxvmgdquxugbdwnnkqbcfpuic/Build/Intermediates.noindex/ArchiveIntermediates/NaijaWorld/InstallationBuildProductsLocation/Applications/app.app/app normal
▸ (1 failure)
** ARCHIVE FAILED **
The following build commands failed:
	Ld /Users/expo/Library/Developer/Xcode/DerivedData/NaijaWorld-gtomxvmgdquxugbdwnnkqbcfpuic/Build/Intermediates.noindex/ArchiveIntermediates/NaijaWorld/InstallationBuildProductsLocation/Applications/app.app/app normal
(1 failure)
`

The error below for Android
`Task :unimodules-react-native-adapter:generateReleaseRFile
> Task :unimodules-react-native-adapter:compileReleaseKotlin FAILED
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/apploader/RNHeadlessAppLoader.kt: (4, 27): Unresolved reference: ReactApplication
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/apploader/RNHeadlessAppLoader.kt: (21, 39): Unresolved reference: ReactApplication
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/apploader/RNHeadlessAppLoader.kt: (22, 65): Unresolved reference: ReactApplication
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/apploader/RNHeadlessAppLoader.kt: (46, 19): Unresolved reference: destroy
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt: (15, 40): Unresolved reference: PermissionAwareActivity
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt: (16, 40): Unresolved reference: PermissionListener
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt: (172, 17): Unresolved reference: PermissionAwareActivity
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt: (238, 28): Unresolved reference: PermissionAwareActivity
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt: (244, 26): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Activity?
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt: (244, 80): Too many arguments for public final fun requestPermissions(p0: Array<(out) String!>, p1: Int): Unit defined in android.app.Activity
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt: (252, 62): Unresolved reference: PermissionListener
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt: (253, 12): Unresolved reference: PermissionListener
[stderr] e: /build/workingdir/build/node_modules/@unimodules/react-native-adapter/android/src/main/java/org/unimodules/adapters/react/permissions/PermissionsService.kt: (261, 67): Unresolved reference: PermissionAwareActivity
> Task :app:bundleReleaseJsAndAssets
info Writing bundle output to:, /build/workingdir/build/android/app/build/generated/assets/react/release/index.android.bundle
info Writing sourcemap output to:, /build/workingdir/build/android/app/build/generated/sourcemaps/react/release/index.android.bundle.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 58 asset files
info Done copying assets
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':unimodules-react-native-adapter:compileReleaseKotlin'.
[stderr] > Compilation error. See log for more details
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 5m 26s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings
357 actionable tasks: 357 executed
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.`

package.json
`{
  "name": "XXXXX",
  "version": "0.0.0",
  "description": "XXXXX",
  "author": "XXXXX",
  "private": false,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "@expo/spawn-async": "^1.5.0",
    "@expo/vector-icons": "^12.0.0",
    "@react-native-async-storage/async-storage": "^1.13.0",
    "@react-native-community/datetimepicker": "^3.5.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "6.0.0",
    "@react-native-community/viewpager": "5.0.11",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/material-bottom-tabs": "^5.3.15",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "@redux-offline/redux-offline": "expo",
    "axios": "^0.21.1",
    "babel-preset-expo": "8.3.0",
    "color": "^3.1.2",
    "expo": "^41.0.0",
    "expo-app-loading": "^1.0.1",
    "expo-apple-authentication": "~3.1.0",
    "expo-asset": "~8.3.1",
    "expo-constants": "~10.1.3",
    "expo-crypto": "~9.1.0",
    "expo-firebase-analytics": "~4.0.2",
    "expo-font": "~9.1.0",
    "expo-google-sign-in": "~9.1.0",
    "expo-image-manipulator": "~9.1.0",
    "expo-image-picker": "~10.1.4",
    "expo-keep-awake": "~9.1.2",
    "expo-linear-gradient": "~9.1.0",
    "expo-linking": "~2.2.3",
    "expo-mail-composer": "~10.1.2",
    "expo-network": "~3.1.1",
    "expo-notifications": "~0.11.6",
    "expo-permissions": "~12.0.1",
    "expo-splash-screen": "~0.10.2",
    "expo-updates": "~0.5.4",
    "expo-web-browser": "~9.1.0",
    "firebase": "8.2.3",
    "flatted": "^2.0.1",
    "lodash": "^4.17.20",
    "moment": "^2.22.2",
    "native-base": "^2.15.2",
    "pluralize": "^7.0.0",
    "prop-types": "^15.7.2",
    "qs": "^6.9.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "react-native-action-button": "^2.8.5",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-async-storage": "^0.0.1",
    "react-native-elements": "^0.16.0",
    "react-native-embed-instagram": "^0.1.1",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-global-props": "^1.1.5",
    "react-native-image-placeholder": "^1.0.14",
    "react-native-image-progress": "^1.1.1",
    "react-native-material-dropdown-v2": "^0.11.1",
    "react-native-paper": "^4.8.1",
    "react-native-read-more-text": "^1.1.0",
    "react-native-reanimated": "~2.1.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.0.0",
    "react-native-search-header": "^0.3.4",
    "react-native-snap-carousel": "^3.8.1",
    "react-native-step-indicator": "0.0.11",
    "react-native-webview": "11.2.3",
    "react-native-youtube-iframe": "^2.1.1",
    "react-navigation": "^3.13.0",
    "react-navigation-collapsible": "^3.0.4",
    "react-redux": "^7.2.4",
    "react-redux-firebase": "^3.10.0",
    "recompose": "^0.30.0",
    "redux": "^4.0.0",
    "redux-devtools-extension": "^2.13.5",
    "redux-firestore": "^0.15.0",
    "redux-persist": "^4.10.2",
    "redux-thunk": "^2.3.0",
    "sentry-expo": "^3.1.0",
    "uuid": "^3.3.2",
    "youtube-api-search": "0.0.5"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/preset-env": "^7.6.2",
    "@babel/preset-react": "^7.0.0",
    "@expo/webpack-config": "~0.12.63",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "jest-expo": "^41.0.0",
    "react-test-renderer": "^17.0.1",
    "semantic-release": "^17.4.0",
    "semantic-release-expo": "^2.2.3",
    "semantic-release-git-branches": "^1.2.1"
  },
  "jest": {
    "preset": "jest-expo",
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "setupFiles": [
      "./jest/setup.js"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|@sentry/.*)"
    ],
    "verifyConditions": [
      "semantic-release-expo",
      "@semantic-release/changelog",
      "@semantic-release/git",
      "@semantic-release/npm"
    ],
    "prepare": [
      "semantic-release-expo",
      "@semantic-release/changelog",
      "@semantic-release/npm",
      {
        "path": "@semantic-release/git",
        "assets": [
          "CHANGELOG.md",
          "package.json",
          "package-lock.json",
          "app.json"
        ]
      }
    ],
    "publish": false,
    "success": false,
    "fail": false
  }
}
`

eas.json
`{
  "build": {
    "release": {},
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    }
  }
}`

Please assist

**Comment by brentvatne** [comment]
https://forums.expo.dev/t/eas-build-for-ios-fails/55324
