### ISSUE TITLE
Linking.addEventListener('url') won't fire when app is built with eas:build 

### ISSUE THREAD

**Issue by pdandradeb** [expo/eas-cli#558]
After dealing with [some issues related to uncommited files](https://github.com/expo/eas-cli/issues/515#issuecomment-897852087) I've managed to build the app with `eas:build` but there are some weird things going on.

The most critical is that the app is not reacting after opened through a deeplink (which in our case means that our login flow is broken). To be clear: the app opens but my handler is not being fired. The weird thing is that the same app build with `expo:build` is working perfectly (link to the APKs below).

I also noticed that status bar behavior is different from one build to the other. Here's the result with `eas:build`]

![Screenshot_20210812-155614](https://user-images.githubusercontent.com/30743/129255014-a1458e0f-85dd-48be-a14f-c7e0237cdaad.png)
![Screenshot_20210812-151729](https://user-images.githubusercontent.com/30743/129255024-3dbc4b0f-e94e-4789-a7cf-38350dfaee0f.png)

Here's the (expected) result when build with `expo:build`:
![Screenshot_20210812-155500](https://user-images.githubusercontent.com/30743/129255046-c76c6cfb-d5e5-4e98-84dd-6477b542fb13.png)
![Screenshot_20210812-155526](https://user-images.githubusercontent.com/30743/129255061-20faff50-589f-4271-86cb-410b11053eea.png)

Does anybody have a clue of what could that be?

Sorry for not preparing a clean reproducible demo but here's [our repo](https://github.com/appjusto/app/) and our [app.config.ts](https://github.com/appjusto/app/blob/main/app.config.ts) and the APKs:

* [Built with expo:build](https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40appjusto/app-justo-courier-dev-ddd9eac46711411ea878a82488ce9691-signed.apk)
* [Built with eas:build](https://expo.dev/accounts/appjusto/projects/app-justo-courier-dev/builds/4b2d4da4-1bc3-41a6-9368-322a18f3abce)

**Comment by brentvatne** [comment]
we need a minimal reproducible example. here is my minimal example demonstrating that this does indeed work: https://github.com/brentvatne/linking-example

**Comment by Svarto** [comment]
@pdandradeb did you manage to solve that status bar issue? I'm running into the same, something changed between expo build and eas and I can't figure out how to fix it.

@brentvatne I see you use the component StatusBar with style=auto, what does auto mean in this context? Also, this was not needed before EAS as with Expo what you set in app.json persisted through the app. Is this no longer the case?

**Comment by fadani** [comment]
I had the exact same issue with `Linking.addEventListener('url')` in our login flow, and used @brentvatne's example to see what was the difference between a working setup and mine. The bit that i had to do to solve this was to add 

```
"scheme": "https",
```
to my app.json, which was not required with `expo:build`. I didn't have to modify the existing `intentFilters` setup.

hope this helps

**Comment by brentvatne** [comment]
@fadani - could you possibly update my example repo or provide a more detailed example demonstrating where you encountered this issue? how were you redirecting back to your app?

**Comment by dsokal** [comment]
Closing because of the inactivity.

**Comment by crystalball808** [comment]
So is there any solution?  Have the same problem on android

**Comment by pdandradeb** [comment]
Hey @brentvatne and @dsokal, it seems that `eas` build is adding just the first `intentFilter` to `AndroidManifest.xml` and ignoring the others.

Here's the [minimal reproducible example](https://github.com/appjusto/appjusto-test) which has multiple `intentFilters` configured. Using `expo` build all of them are included in the `AndroidManifest.xml`. [Here's both versions of AndroidManifest.xml](https://gist.github.com/pdandradeb/18efdb698ee493a4cde98e6a250bba84) I've got using apkanalyzer.

Another difference from both versions is the initial URL when the app is open directly. Using the `expo` build the initial URL is `https://exp.hos:443/....` while the `eas` the URL is empty. Here's the screenshots:

Build with expo:
![Screenshot_20211119-111734](https://user-images.githubusercontent.com/30743/142642362-ea5749f9-d291-4873-992a-630acf116407.png)

Build with eas:
![Screenshot_20211119-113055](https://user-images.githubusercontent.com/30743/142642372-7d694750-b579-489b-8003-e7784134814b.png)

The deeplinks are:
https://test.appjusto.com.br/deeplink2
https://test.appjusto.com.br/deeplink
https://test.appjusto.com.br/other-deeplink

**Comment by brentvatne** [comment]
the initial url difference is intentional. the behavior on eas build is correct, the behavior on expo build has been around for a while but it doesn't make a lot of sense.

however, your observation about intent filters appears to indeed point to an issue. we'll look into it

**Comment by pdandradeb** [comment]
Hey, thanks for checking this out.
Does the `0.39.0` version includes this fix?

**Comment by brentvatne** [comment]
@pdandradeb - you will need to us expo-cli@5.0.0-rc.3 on eas build to pull in the fix. you can set this version in your build profile with the `expoCli` field

**Comment by pdandradeb** [comment]
@brentvatne got this error:

```
Error: eas.json is not valid [ValidationError:
"build.courier-live-internal.expoCli" failed custom validation because
expo-cli@5.0.0-rc.3 is not a valid version. "build.courier-live-store.expoCli"
failed custom validation because expo-cli@5.0.0-rc.3 is not a valid version]
```

eas.json
```
{
  "build": {
    "courier-live-internal": {
      "env": {
        "FLAVOR": "courier",
        "ENV": "live"
      },
      "releaseChannel": "live-v6",
      "distribution": "internal",
      "android": {
        "buildType": "apk"
      },
      "expoCli": "expo-cli@5.0.0-rc.3"
    }
  }
}
```

also tried with just `5.0.0-rc.3` but it didn't work either.

eas version:
`eas-cli/0.39.0 darwin-arm64 node-v14.17.2`

**Comment by dsokal** [comment]
@pdandradeb This is probably a bug on our side. I'll look into this.

**Comment by pdandradeb** [comment]
hey @dsokal, thanks for the fix but it seems that there's another issue going on. the build started but it failed with this message:

```
[stderr] /root/workingdir/build/android/app/src/main/AndroidManifest.xml:14:13-88 Error:
[stderr] 	Attribute meta-data#org.unimodules.core.AppLoader#react-native-headless@value value=(org.unimodules.adapters.react.apploader.RNHeadlessAppLoader) from [:unimodules-react-native-adapter] AndroidManifest.xml:14:13-88
[stderr] 	is also present at [:expo-modules-core] AndroidManifest.xml:14:13-86 value=(expo.modules.adapters.react.apploader.RNHeadlessAppLoader).
[stderr] 	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:12:9-14:91 to override.
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:processReleaseMainManifest'.
[stderr] > Manifest merger failed : Attribute meta-data#org.unimodules.core.AppLoader#react-native-headless@value value=(org.unimodules.adapters.react.apploader.RNHeadlessAppLoader) from [:unimodules-react-native-adapter] AndroidManifest.xml:14:13-88
[stderr]   	is also present at [:expo-modules-core] AndroidManifest.xml:14:13-86 value=(expo.modules.adapters.react.apploader.RNHeadlessAppLoader).
[stderr]   	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:12:9-14:91 to override.
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 7m 20s
```

Tried with expo-cli and the build was successful.

**Comment by dsokal** [comment]
@pdandradeb can you please open another issue?

**Comment by pdandradeb** [comment]
@dsokal [just did](https://github.com/expo/eas-cli/issues/853) but couldn't reproduce yet in a blank project.

**Comment by pdandradeb** [comment]
Hey @dsokal @brentvatne, updating to SDK 44 resolves the issue https://github.com/expo/eas-cli/issues/853 but this one remains. My app is not being notified by `Linking.useURL` when opened with a deeplink. This happens only when built with `eas-cli`. Building with `expo-cli` still works perfectly as before.

I'm trying to understand the reason but each build is taking more than 30 minutes so it has been painful to debug it. 

<img width="442" alt="Screen Shot 2022-01-21 at 10 34 00" src="https://user-images.githubusercontent.com/30743/150541808-fba51575-1c0e-4e10-9359-252829b8fb29.png">

One thing I've noticed [comparing the AndroidManifest.xml](https://gist.github.com/pdandradeb/c8f9ea990a85bb69a0a47ee72b18c325) from our app with the reproducible is that this scheme is being added to all intent filters of our app (it has many):

`<data android:scheme="exp+app-justo-courier" />`

(from our app AndroidManifest.xml):
<img width="503" alt="Screen Shot 2022-01-21 at 11 54 11" src="https://user-images.githubusercontent.com/30743/150548206-4b5a1d78-7dc8-45c9-b802-107e0cb01917.png">

(from reproducible's AndroidManifest.xml):
<img width="516" alt="Screen Shot 2022-01-21 at 11 45 34" src="https://user-images.githubusercontent.com/30743/150548291-697b1d1c-5cf4-43d3-8fe7-c13b8c2b1458.png">

Do you know when this is added and could that confuse the intent filters? That's my only lead so far.

We're working on our app for a year and a half and reassembling it piece by piece to understand what is going on - taking 30 minutes each build, is a nightmare. Any thoughts would very appreciated.

Here's our [app.config](https://github.com/appjusto/app/blob/sdk44/app.config.ts) and here's the [reproducible's](https://github.com/appjusto/appjusto-test/blob/status-bar/app.json).

As I mentioned when opened the issue, the status bar behavior is also different from one build to another but I haven't started to understand why yet.

**Comment by brentvatne** [comment]
@pdandradeb - android builds were slower last week due to a mitigation we had in place to handle a jcenter outage, but that should be improved now. you can also test this locally using `expo run:android` and then [clean up the changes from `prebuild` afterwards](https://expo.fyi/prebuild-cleanup). if you just want to see the generated AndroidManifest, you can run `expo prebuild -p android --clean` and inspect it, and clean up when you're done.

the scheme you're seeing there is being added by the expo-dev-client config plugin: https://github.com/expo/expo/blob/main/packages/expo-dev-client/plugin/src/getDefaultScheme.ts

https://github.com/expo/expo/blob/main/packages/expo-dev-client/plugin/src/withGeneratedAndroidScheme.ts#L25

would you be able to create an issue on https://github.com/expo/expo/issues that outlines the problem and provides a minimal example?

**Comment by pdandradeb** [comment]
@brentvatne thanks for your reply.

> would you be able to create an issue on https://github.com/expo/expo/issues that outlines the problem and provides a minimal example?

Yes, finally. I've created another issue with detailed information here: https://github.com/expo/eas-cli/issues/947

I thought would make sense to keep it at this repo but let me know if I should add the issue on expo repo.

**Comment by MasoudJB** [comment]
@pdandradeb Did you find a way to trigger Linking.addEventListener('url') with EAS build?

**Comment by WisaniShilumani** [comment]
Having the same issue. Anyone have a fix?

**Comment by brentvatne** [comment]
if you believe you are experiencing this please create a new issue on https://github.com/expo/expo/issues and fill out the issue template so that we have the information that we need to help :)
