### ISSUE TITLE
eas build failing but local pre-build and run-android is working

### ISSUE THREAD

**Issue by lHersey** [expo/eas-cli#564]
## Description

Hello everyone!

I created a [config-plugin](https://www.npmjs.com/package/with-rn-get-social) for a SDK that my team is trying to implement, it just changes a couple of keys on `build.gradle`.

If I run `prebuild` or `run:android` everything works normally but if I run `eas build` (even with `--local`) it fails because of android manifest merge.

I ran `EAS_LOCAL_BUILD_SKIP_CLEANUP=1 eas build --profile development --platform android --local` to checkout what is the difference, if I remove the `eas-build.gradle` from `build.gradle` the build success, if the line is there the build fails

```
[RUN_GRADLEW] See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
[RUN_GRADLEW] /private/var/folders/lz/zhd2r3g548703w2drpkx70jm0000gp/T/eas-build-local-nodejs/79e595ef-c139-4919-ac9c-ecefe5140007/build/android/app/src/debug/AndroidManifest.xml Error:
[RUN_GRADLEW]   Attribute data@host at AndroidManifest.xml requires a placeholder substitution but no value for <getsocial_hostName_0> is provided.
[RUN_GRADLEW] /private/var/folders/lz/zhd2r3g548703w2drpkx70jm0000gp/T/eas-build-local-nodejs/79e595ef-c139-4919-ac9c-ecefe5140007/build/android/app/src/debug/AndroidManifest.xml Error:
[RUN_GRADLEW]   Attribute data@host at AndroidManifest.xml requires a placeholder substitution but no value for <getsocial_hostName_1> is provided.
[RUN_GRADLEW] /private/var/folders/lz/zhd2r3g548703w2drpkx70jm0000gp/T/eas-build-local-nodejs/79e595ef-c139-4919-ac9c-ecefe5140007/build/android/app/src/debug/AndroidManifest.xml Error:
[RUN_GRADLEW]   Attribute data@host at AndroidManifest.xml requires a placeholder substitution but no value for <getsocial_scheme> is provided.
[RUN_GRADLEW] FAILURE: Build failed with an exception.
```

Now at first sight the error is about the sdk that I'm trying to implement, but if I run the same build with the same command `./gradlew :app:assembleDebug` without the `apply from: "./eas-build.gradle"` at the end of `app/build.gradle` builds correctly

## Steps to reproduce
1. Run `expo init`
2. Configure eas
```json
{
  "build": {
    "release": {},
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    }
  }
}

```
2. Add the `config-plugin` [config-plugin](https://www.npmjs.com/package/with-rn-get-social)
I got the appid from the [demo app](https://github.com/getsocial-im/getsocial-react-native-sdk/blob/master/sdk7demo/android/app/build.gradle) so you can use this one safely.
```json
{
  "plugins": [
    [
      "with-rn-get-social", { "appId": "VwQZq89f0V1" }
    ]
  ]
}
```
3. Run 
```sh
EAS_LOCAL_BUILD_SKIP_CLEANUP=1 eas build --profile development --platform android --local
//or 
eas build --profile development --platform android 
```

**Comment by brentvatne** [comment]
the error is likely only occurring in release builds, which is why you see this when running a `eas build --local` but not with `expo run:android`. you can do `expo run:android --variant release` and it will likely reproduce the same error.

you need to configure the manifest placeholders for this library: https://docs.getsocial.im/knowledge-base/manual-integration/android/#configure-manifest

**Comment by brentvatne** [comment]
oh, also, here's an example of setting manifest placeholders: https://github.com/expo/expo/blob/195c777bdd033237bd6e61da9bfb96eb56ad705a/packages/expo-app-auth/plugin/src/withAppAuth.ts#L12-L28

**Comment by lHersey** [comment]
I ran `expo run:android --variant release` and it worked (without the defaultConfig placeholders)

Also I was running `./gradlew :app:assembleDebug`, on the since I'm creating a developmentClient it uses that gradlew command, so it's a debug build, not a release build I think

Thanks for the help!
