### ISSUE TITLE
Using eas.json with expo start for env variables

### ISSUE THREAD

**Issue by Borduhh** [expo/eas-cli#565]
We followed the environment variable guide for EAS (https://docs.expo.dev/build-reference/variables/). However, this now breaks our local development using the `expo start` command since it doesn't load the `eas.json` file.

Is there a workaround for this or plans to implement an `eas start` command?

**Comment by wkozyra95** [comment]
env variables from eas.json are evaluated when running `eas build` to simplify workflow for people that need different config to avoid sth like this
```
EAS_PROFILE=staging eas build --profile staging
```

I recommend thinking about it as to separate entities, eas as your ci/cd pipeline and expo-cli as your local development environment, then the fact that you need to configure them separately is not that surprising

> Is there a workaround for this 

you can just create a script with envs and source it before calling `expo start` or use a tool like direnv to do that when you enter directory automatically

> plans to implement an eas start command?

no, eas-cli is not a replacement for expo-cli, it will take over all cloud functionalities like build/publish/submit but everything related to local development will stay in expo-cli
