### ISSUE TITLE
eas build -p ios with simulator target should prompt to download and install in simulator

### ISSUE THREAD

**Issue by brentvatne** [expo/eas-cli#572]
We should save the hassle of extracting the tar.gz and installing it in the simulator then running it by just doing this automatically. The code for this should be basically the same as installing the Expo client app in the simulator.

**Comment by EvanBacon** [comment]
I've moved this feature request from expo-cli `expo build:ios` since we want to apply new features to `eas build`.

**Comment by brentvatne** [comment]
@kbrandwijk - very much so! perhaps not exactly as described in this issue but some mechanism to download and install simulator builds from EAS would be very welcome

**Comment by szdziedzic** [comment]
This functionality is released now 🎉 Feel free to test it in the newest `eas-cli` version 😄
