### ISSUE TITLE
v0.26.0 moving eas submit options to the app.json file is incompatible with gitlab ci

### ISSUE THREAD

**Issue by reuben-harcourt** [expo/eas-cli#601]
### Summary

Changes in v0.26.0 to move the params out of the cli command and into the eas.json submit profile are incompatible with referencing the google service account path as an environment variable in Gitlab CI.

#### Pre v26
`eas submit --platform android --latest --key=$GOOGLE_SERVICE_ACCOUNT`

#### Post v26
`eas submit --platform android --latest --profile ci`

eas.json:
```
...
"ci": {
      "android": {
        "track": "alpha",
        "serviceAccountKeyPath": "$GOOGLE_SERVICE_ACCOUNT" 
      },
...
```

The changes in release v0.26.0 moved things like the --key param into the submit profile, so I added `$GOOGLE_SERVICE_ACCOUNT` as the value in there, however, this doesn't seem to successfully reference the gitlab CI environment variable, it instead treats it as just a string.

Has anyone else come across this yet since the v0.26.0 update? For obvious reasons I can't simply commit the google service account to the repo and hardcode the path in the eas.json. Am I doing something wrong or is this change simply incompatible?

### Environment

```
EAS CLI 0.26.0 environment info:
    System:
      OS: Linux 5.4 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 12.22.6 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    Utilities:
      Git: 2.11.0 - /usr/bin/git
    npmPackages:
      expo: ^42.0.0 => 42.0.3 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 
```

### Error output

```
File $GOOGLE_SERVICE_ACCOUNT doesn't exist.
A Google Service Account JSON key is required to upload your app to Google Play Store.
If you're not sure what this is or how to create one, Learn more: https://expo.fyi/creating-google-service-account
    Error: Input is required, but stdin is not readable.
error Command failed with exit code 1.
```

### Reproducible demo or steps to reproduce from a blank project

Use gitlab ci referencing the google service account key path in the eas.json submit profile as a gitlab ci variable

**Comment by DominikIlski** [comment]
Same issue here

**Comment by dsokal** [comment]
Hi @reuben-harcourt,
Thanks for reporting. Can you please elaborate on what is exactly your use case? 

From reading the description, I'd say that this is not an issue (and anything we want to change/fix). Usually, every CI service lets you define the env variables for a job. This means that you know the value of `GOOGLE_SERVICE_ACCOUNT` before starting the job. If you know the path before starting the job, you can hardcode it in `eas.json`. 

Also, you don't need to commit the file to the repository:
- Set an env var (e.g. `GOOGLE_SERVICE_ACCOUNT`) to the base64-encoded Google Service Account key.
- Write a CI job that decodes the base64 and saves the result to a fixed path, e.g. `/tmp/key.json`:
    `echo $GOOGLE_SERVICE_ACCOUNT | base64 --decode > /tmp/key.json`
- Set the "hardocoded" path in eas.json: 
  ```
  "ci": {
      "android": {
        "track": "alpha",
        "serviceAccountKeyPath": "/tmp/key.json" 
  }
  ```

**Comment by reuben-harcourt** [comment]
Thanks for the recommendations @dsokal, that does fix the issue. It's a pretty common use case i've got.

I have a CI job that runs when I bump the apps version:
```
npx eas-cli build --non-interactive --platform all
npx eas-cli submit --latest --platform ios --asc-app-id=blablabla --apple-id=blablabla
npx eas-cli submit --latest --platform android --key=$GOOGLE_SERVICE_ACCOUNT --track=alpha
```

The $GOOGLE_SERVICE_ACCOUNT referred to a Gitlab CI env file.

Once the `--key` got moved to the submit profile in the latest release, gitlab is no longer evaluating the env variable into the file's path.

Again, thanks for the recommendations. However, I suspect this will be a recurring question people have unless new documentation covers this, since setting CI environment files is commonplace, and requiring an extra step to pull it out of an env variable into a temp file is a little bit of a pain, just my two cents.

**Comment by dsokal** [comment]
Ok, fair enough. I didn't know Gitlab lets you mark an env variable as a file. I'll implement the support for this soon :)

**Comment by dsokal** [comment]
It should work in the latest version - 0.27.0 
https://github.com/expo/eas-cli/releases/tag/v0.27.0

**Comment by reuben-harcourt** [comment]
Awesome, I've implemented that along with the `eas build --auto-submit` feature ❤️. We are loving using eas, thank you
