### ISSUE TITLE
EXPO_DEBUG=1 eas build -p ios with eas-cli@0.28.2 fails with unhelpful generic error.

### ISSUE THREAD

**Issue by harrisrobin** [expo/eas-cli#648]
### Summary

If you run

```sh
EXPO_DEBUG=1 eas build -p ios
```

eas-cli fails with "CombinedError: [GraphQL] Unexpected server error.

<img width="399" alt="image" src="https://user-images.githubusercontent.com/3880008/134801230-0796af0d-85a9-4012-b015-53d7fc6cbba8.png">

### Environment
```
  EAS CLI 0.28.2 environment info:
    System:
      OS: macOS 12.0
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - ~/.volta/tools/image/node/14.16.1/bin/node
      Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
      npm: 7.7.2 - ~/.volta/tools/image/npm/7.7.2/bin/npm
    Utilities:
      Git: 2.22.0 - /usr/local/bin/git
    npmPackages:
      expo: ~42.0.3 => 42.0.3
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
```
### Error output

```
Failed to setup credentials.
    CombinedError: [GraphQL] Unexpected server error.
```

This is the error despite having EXPO_DEBUG=1

### Reproducible demo or steps to reproduce from a blank project

Since this happens with eas build after signing in with Apple Credentials, I don't see how I can setup a public reproducible demo. Please let me know what's acceptable here.

**Comment by harrisrobin** [comment]
@brentvatne this does not happen after I downgrade to `EAS CLI 0.27.1`. It appears to be a regression with a release after that version.

**Comment by brentvatne** [comment]
@harrisrobin - thanks, i passed this on to the folks that work on credentials. can you please share the related account and app name?

**Comment by harrisrobin** [comment]
@brentvatne after updating to `eas-cli/0.29.1 darwin-x64 node-v14.16.1` it's now working for some reason. No change in my config on my end, but we can close this!

**Comment by quinlanj** [comment]
@harrisrobin good to hear! i tried to repro this the other day, but i wasn't able to. If this problem pops up again, please open another issue. It is really hard to fix the issue if there is no reliable way to repro - any other info you can give us (like account name, project, etc) would be super helpful in lieu of this!
