### ISSUE TITLE
[eas build android local] .apk with generated time like '0:3' instead of '00:03' in filename

### ISSUE THREAD

**Issue by SrBrahma** [expo/eas-cli#661]
### Summary

After successfully running `eas build --profile development --platform android --local`, the file e.g. `build-4-8-2021-0:3.apk` is generated instead of `build-4-8-2021-00:03.apk`. The hour and minute fields are not left padded with zeroes.

Also, I think YYYY-MM-DD-HH:MM format would be better to alphabetically sorting the generated apks.

### Environment

  EAS CLI 0.29.1 environment info:
    System:
      OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.15.4 - ~/n/bin/node
      Yarn: 1.22.4 - ~/n/bin/yarn
      npm: 7.19.1 - ~/n/bin/npm
    Utilities:
      Git: 2.30.2 - /usr/bin/git
    npmPackages:
      expo: ~42.0.3 => 42.0.4 
      expo-dev-client: ^0.5.1 => 0.5.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      eas-cli: 0.29.1
      expo-cli: 4.12.0

### Reproducible demo or steps to reproduce from a blank project

Just run `eas build --profile development --platform android --local` on any project

**Comment by dsokal** [comment]
Install the latest `eas-cli-local-build-plugin` to get rid of the problem.
