### ISSUE TITLE
Using locale for System Dialog prompts crashes EAS build at FastLane step

### ISSUE THREAD

**Issue by amrhassab** [expo/eas-cli#665]
### Summary

When using files to implement Locale for System Dialog prompts, by setting the locale field in app.json, EAS build crashes while classic expo build still works.

### Environment

  EAS CLI 0.29.1 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.1 - /usr/local/bin/node
      Yarn: 1.22.5 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
    npmPackages:
      expo: ~42.0.1 => 42.0.4
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: ~0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      eas-cli: 0.29.1
      expo-cli: 4.12.1

### Error output

```
› Copying ../../../xxx/Documents/xxx/playground/example/ios/example/Supporting/ar.lproj/InfoPlist.strings ➜ ar.lproj/InfoPlist.strings

❌  error: Build input file cannot be found: '/Users/xxx/Documents/xxx/playground/example/ios/example/Supporting/ar.lproj/InfoPlist.strings' (in target 'example' from project 'example')

› Compiling example » LaunchScreen.xib
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	CopyStringsFile /Users/expo/Library/Developer/Xcode/DerivedData/example-aoifdmkcrqrofsguvgnrcnqyppbd/Build/Intermediates.noindex/ArchiveIntermediates/example/InstallationBuildProductsLocation/Applications/example.app/ar.lproj/InfoPlist.strings /Users/xxx/Documents/xxx/playground/example/ios/example/Supporting/ar.lproj/InfoPlist.strings
▸ (1 failure)
** ARCHIVE FAILED **
The following build commands failed:
	CopyStringsFile /Users/expo/Library/Developer/Xcode/DerivedData/example-aoifdmkcrqrofsguvgnrcnqyppbd/Build/Intermediates.noindex/ArchiveIntermediates/example/InstallationBuildProductsLocation/Applications/example.app/ar.lproj/InfoPlist.strings /Users/xxx/Documents/xxx/playground/example/ios/example/Supporting/ar.lproj/InfoPlist.strings
(1 failure)
Exit status: 65
+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.185.1                 |
| sdk         | iPhoneOS14.5.sdk        |
+-------------+-------------------------+

```

### steps to reproduce from a blank project and minimal example project

0) create you own minimal example by following the steps or use [mine](https://github.com/amrhassab/example)
1) create a project with expo init (select blank)
2) add locale json file to root directory with NSPhotoLibraryUsageDescription and NSCameraUsageDescription in any language (you can use ios-permission-descriptions-ar.json file from my [minimal example](https://github.com/amrhassab/example))
3) run expo prebuild
4) edit app.json to have:

```
"ios": {
      "infoPlist": {
        "CFBundleAllowMixedLocalizations": true,
        "NSPhotoLibraryUsageDescription": "This app needs access to your photos or camera in order to etc etc",
        "NSCameraUsageDescription": "This app needs access to your camera in order for you to etc etc"
      },
      "bundleIdentifier": "xxxxxxxxx"
    },
    "locales": {
      "ar": "./ios-permission-descriptions-ar.json"
    },
```

5) run expo prebuild --clean
6) run eas build:configure
7) run eas build --profile development --platform ios

observe crash in fastlane step

**Comment by EvanBacon** [comment]
The repo you provided contains an ios and android folder, making this a bare project.

I can repro the issue if I pull the repo you provided and run `expo run:ios` on it, meaning that your local project is misconfigured and you must manually fix it.

However, if I revert the project back to managed workflow (by running `expo prebuild --clean`), and rerun `expo run:ios`, everything appears to work as expected.

This leads me to believe that something was manually modified in your native ios folder, which would make the project bare workflow, meaning that most changes to your app.json would be ignored. In the bare workflow you must manually ensure that your Xcode project builds.

**Comment by wkozyra95** [comment]
if you have android and ios directories we are treating your project as bare and just building as it is with only minimal configuration, if you want to build it as a managed project on eas, then you should add android and ios directories to .gitignore

`../../../xxx/Documents/xxx/playground/example/ios/example/Supporting/ar.lproj/InfoPlist.strings ➜ ar.lproj/InfoPlist.strings`

it looks like eas  build is trying to access path from your local machine, which means your xcodeproj is misconfigured, we should probably fix that on our side, but in general `expo run:ios` is intended for local development, so issues like that are likely to happen.

**Comment by wkozyra95** [comment]
yes, if directories are already committed or staged adding them to gitignore is not enough, you need to explicitly remove them from git state (either by deleting them or using `git rm`), this just how the git works. But now if you create those directories back it should still work.

**Comment by amrhassab** [comment]
Ok great, thank you. Closing this issue because it is resolved.
