### ISSUE TITLE
Support manifestPlaceholders when showing release channel meta data in web interface

### ISSUE THREAD

**Issue by tobiasr** [expo/eas-cli#667]
### Summary

We're using manifestPlaceholders in our app/build.gradle to setup different release channels for different environment variables. This works very well! 

After a build is done via eas:build the Android version is listing the chosen release channel to be: `${expoReleaseChannel}` which is the placeholder variable name, not it's content. The app is however configured for the content of the variable so what it shown is incorrect.

### Environment

NA

### Reproducible demo or steps to reproduce from a blank project

1. Create a project
2. Setup manifestPlaceholders in defaultConfig in the app/build.gradle like this:
```
manifestPlaceholders = [
                expoReleaseChannel:project.env.get("EXPO_RELEASE_CHANNEL").toString(),
                expoUpdatesUrl:project.env.get("EXPO_UPDATES_URL").toString(),
        ]
```
3. Use the manifestPlaceholders in AndroidManifest.xml like this:
```
<meta-data android:name="expo.modules.updates.EXPO_RELEASE_CHANNEL" android:value="${expoReleaseChannel}"/>
<meta-data android:name="expo.modules.updates.EXPO_UPDATE_URL" android:value="${expoUpdatesUrl}"/>
```
4. Start a cloud build with those env-variables set for Android
5. The web interface data on that build should have Release channel be the variable name instead of the variables content.

**Comment by wkozyra95** [comment]
We don't have any good way to read those values if they are configured this way, whatever progress we make about parsing gradle files there will always be a way for those values to go out of sync with what we resolve. To properly resolve those values we would need to run actual build and populate that back which is not really feasible with current architecture
