### ISSUE TITLE
error installing private npm package

### ISSUE THREAD

**Issue by jesuscovam** [expo/eas-cli#681]
Hi, I'm having issues installing private packages in when using eas build for android.

<img width="1013" alt="Screen Shot 2021-10-08 at 17 19 18" src="https://user-images.githubusercontent.com/46403187/136630564-9cfd2f69-5354-4519-ac0c-f3b0ac5a8fd4.png">

the secret is also in the expo admin page

<img width="1167" alt="Screen Shot 2021-10-08 at 17 26 16" src="https://user-images.githubusercontent.com/46403187/136631048-ed91e079-3fd0-4b07-b746-3d4c11803428.png">

this is my eas.json
```
{
  "build": {
    "release": {
      "env": {
        "NPM_TOKEN": "my_code_..._is_long"
      }
    },
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    }
  },
  "submit": {
    "release": {}
  }
}
```

my .npmrc
```
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```

and this is the command i submit to spawn the build
```
eas build --platform android --profile release
```

thanks for having the time to help me!🙏🏼

**Comment by dsokal** [comment]
I wrote up a docs page for future people struggling with private npm packages:
https://docs.expo.dev/build-reference/private-npm-packages/
