### ISSUE TITLE
Build request failed - CombinedError: [GraphQL] Entity not authorized

### ISSUE THREAD

**Issue by emac3** [expo/eas-cli#694]
### Summary

Since this morning builds fail with an error. I tried to login again with `eas login`, but no luck.

### Environment

  EAS CLI 0.32.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - /var/folders/cx/c6zgtcwj2sb08ld9821twt7h0000gn/T/yarn--1634625745983-0.8051240578579084/node
      Yarn: 1.22.15 - /var/folders/cx/c6zgtcwj2sb08ld9821twt7h0000gn/T/yarn--1634625745983-0.8051240578579084/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
    npmPackages:
      expo: ~42.0.0 => 42.0.3
      react-native: 0.64.1 => 0.64.1

### Error output

```
Starting iOS build
Build request failed. Make sure you are using the latest eas-cli version. If the problem persists, please report the issue.
    CombinedError: [GraphQL] Entity not authorized: CustomerEntity[***] (viewer = RobotViewerContext,
    action = READ, ruleIndex = -1)
```

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by wma-alvin** [comment]
Same issue

**Comment by hinsxd** [comment]
> Not sure if it will help, but If you are using tokens to authenticate you can try regenerating them, if you log in via login and password try deleting `~/.expo/state.json` or invalidate all sessions from `https://expo.dev/settings` by clicking `Log out of other sessions`

It fails in CI (which uses EXPO_TOKEN) as shown above (`RobotViewerContext`) and I encountered this in CI too. I think it might be an auth error rather than session error.

**Comment by cruzach** [comment]
fix deployed, no update to eas-cli necessary

**Comment by erisvaldojunior** [comment]
Is it still happening? got the same error today (Admin Bot User).

**Comment by NxsHbb** [comment]
> Is it still happening? got the same error today (Admin Bot User).

I got the same error today

**Comment by CaioMars** [comment]
I solved this issue by removing `eas: projectId` from `app.json`:

    "extra": {
      "eas": {
        "projectId": "a1b2c3d4-e5f6-g7h8i9-j1k2-l3m4n5o6p7"
      }
    }

I need a build for development, the company's Expo project ID is different than my account's project ID, thus the problem...

**Comment by maheshItlalan** [comment]
I solved this issue by removing eas: projectId from app.json:. As below 

"extra": {
  "eas": {
    
  }
}
