### ISSUE TITLE
AssertionError [ERR_ASSERTION]: You must be in your project directory in order to perform this action

### ISSUE THREAD

**Issue by lucholabs** [expo/eas-cli#698]
### Summary

Im getting this error trying to build credentials

 What do you want to do? › All: Set up all the required credentials to build your project
AssertionError [ERR_ASSERTION]: You must be in your project directory in order to perform this action

### Environment

  EAS CLI 0.32.0 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
    npmPackages:
      expo: ^42.0.4 => 42.0.4 
      expo-cli: ^4.12.1 => 4.12.1 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ^0.17.1 => 0.17.5 
    npmGlobalPackages:
      eas-cli: 0.28.0
      expo-cli: 4.11.0

### Error output

AssertionError [ERR_ASSERTION]: You must be in your project directory in order to perform this action

### Reproducible demo or steps to reproduce from a blank project

eas credentials
Build Credentials: Manage everything needed to build your project
All: Set up all the required credentials to build your project

**Comment by HristoEftimov** [comment]
I am also facing this issue and I am in the root directory of the project :/ Doesn't matter which option I will choose, it's always the same error `AssertionError [ERR_ASSERTION]: You must be in your project directory in order to perform this action`. Any ideas?

**Comment by dsokal** [comment]
@HristoEftimov what EAS CLI version are you using? Are you sure you're running the command in the project directory? I'd suggest opening another issue.

**Comment by lucholabs** [comment]
Hey guys, this was just a incompatibility btw libraries.    My case it was gulp.js

check the log we you try to compile with EAS.

**Comment by kirtikapadiya** [comment]
I'm using managed workflow expo sdk 45 and trying to create ios build getting same issue 
eas-cli@0.48.2 
node@v14.16.0
expo@45.0.3
![ios build](https://user-images.githubusercontent.com/20786875/168742165-5588ab29-6bce-4065-94e5-bb28c602e230.png)

**Comment by AlastairTaft** [comment]
Hitting this too, I'm in the project directory. Will debug and post back if I find a solutions.

**Comment by TerrniT** [comment]
```
AssertionError [ERR_ASSERTION]: You must be in your project directory in order to perform this action
Cryptic error? Learn more:
```
So i am just run `eas config` And find a syntax error in my `app.json`

```
 ├─ File: C:\Users\user\projects\react-native\GoogleAuth\app.json
    └─ Cause: SyntaxError: JSON5: invalid character '\"' at 6:5
      4 |     "slug": "GoogleAuth",
      5 |     "plugins": ["@react-native-google-signin/google-signin"]
    > 6 |     "version": "1.0.0",
        |     ^
      7 |     "orientation": "portrait",
      8 |     "icon": "./assets/icon.png",
      9 |     "userInterfaceStyle": "light",
```
It works for me after fix syntax error

**Comment by oussamachah2020** [comment]
m getting this error , `Unexpected: Config `_internal.projectRoot` isn't defined by expo-cli, this is a bug.`
