### ISSUE TITLE
When OTA updates are disabled, Updates.releaseChannel is always 'default' on iOS

### ISSUE THREAD

**Issue by cameronmurphy** [expo/eas-cli#699]
### Summary

Hi,

We've got an app where we've disabled OTA updates. We're interested in the app booting as quickly as possible. People often use our app in ares where there isn't great reception and we don't want them downloading a JavaScript bundle before the app finishes booting.

We're in the process of ejecting and we're using the `Updates.releaseChannel` constant to decide which configuration to load as documented here https://docs.expo.dev/distribution/release-channels/

Everything works as expected on Android, but on iOS the release channel is always `default`. This can be resolved by changing `updates.enabled` to true and running `eas build:configure` but we would prefer not to do this.

### Environment

  EAS CLI 0.32.0 environment info:
    System:
      OS: macOS 11.6
      Shell: 3.3.1 - /usr/local/bin/fish
    Binaries:
      Node: 14.18.0 - /private/var/folders/5m/r25wkqy93g34y3257c1mr0xm0000gn/T/xfs-70f8bf32/node
      Yarn: 3.0.2 - /private/var/folders/5m/r25wkqy93g34y3257c1mr0xm0000gn/T/xfs-70f8bf32/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
    npmPackages:
      expo: ^42.0.5 => 42.0.5
      expo-cli: 4.12.1 => 4.12.1
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      eas-cli: 0.31.1
      expo-cli: 4.12.3

### Reproducible demo or steps to reproduce from a blank project

Run `expo init` and choose bare workflow. Replace the contents of App.js with the below:
```
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import * as Updates from 'expo-updates';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Release channel: {Updates.releaseChannel}</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Modify `app.json` to disable updates like so:
```
{
  "expo": {
    "updates": {
      "enabled": false
    }
    ...
```

Run `eas build:configure`. Add a `preview` release channel to `eas.json` like so:
```
{
  "build": {
    "preview": {
      "distribution": "internal",
      "releaseChannel": "staging"
    }
    ...
```

Run `eas device:create` and link an iOS device to your provisioning profile. Run `eas build --platform ios --profile preview` and scan the resulting QR code on your iOS device to install the build.

Open the app, it will tell you the release channel is default.

**Comment by dsokal** [comment]
Hi @cameronmurphy,

According to my knowledge, you shouldn't depend on `Updates.releaseChannel` when updates are disabled. I suspect it works on Android without explicit reason. (I think people working on Expo Update can tell you more (cc @jonsamp @jkhales) about it)

If you want to conditionally set some env vars for your project you should set them in `eas.json` (https://docs.expo.dev/build-reference/variables/) and then update `app.json` to pass them to your code (https://docs.expo.dev/guides/environment-variables/#using-app-manifest--extra).

**Comment by jonsamp** [comment]
I agree with @dsokal's response. Also, it's really understandable that you'd like your users to get their apps open as soon as possible. If you like the benefits of the `expo-updates` library, but want apps to load immediately, you could set the `expo.updates.fallbackToCacheTimeout` property as `0`. This `fallbackToCacheTimeout` property in **app.json** will pause on the splash screen to check if there's a new update for the set amount of milliseconds. By setting it to `0`, the app will pause for no time, and will open the app up immediately. Once the app is open, if there's a new update, expo-updates will attempt to download the new update in the background as the user uses the app. Once it downloads the update, the next time the user opens the app, they'll see the new update.

If your updates are small (JS-only changes usually), this could work, and it wouldn't cost your users much data. With that, turning updates off completely is also a good solution, just wanted to explain another approach in case it meets your requirements.
