### ISSUE TITLE
Publishing an OTA after eas:build crashes the app due to missing env vars

### ISSUE THREAD

**Issue by SharjeelAliCS** [expo/eas-cli#700]
Couldn't find any exact issue on this, so decided to ask here. 
Anyway, I built an app through `eas build`, then installed the APK on android, and everything works fine for the specific release channel.
When trying to test that OTA updates work using `expo publish` on the same release channel, the APK app crashes right after it downlaods the update.
Upon further inspection, the issue is that `expo publish` doesn't have access to the ENV variables defined in the `eas.json` file, while `eas build` does use them perfectly fine.

And yes, I tried `--target bare` as well for publishing.

So is it not possible to access ENV vars from `eas.json` when running `expo publish`? Or do I just need to wait for `eas update` to be publicly released?

**Comment by SharjeelAliCS** [comment]
@dsokal Hello, I noticed you assigned someone to this. I was wondering if you could confirm then: Can `expo publish` NOT access `eas.json` env variables?

**Comment by brentvatne** [comment]
this is covered in docs now: https://docs.expo.dev/build-reference/variables/#common-questions
