### ISSUE TITLE
`eas secret:create` fails with `CombinedError: [GraphQL] Not authorized.` with Organization + bot token

### ISSUE THREAD

**Issue by mako-taco** [expo/eas-cli#714]
### Summary

Running `eas secret:create --name=XYZ --value ABC --force` fails with `[GraphQL] Not authorized.` in a github workflow when using `expo/expo-github-action@v6` and authenticating with a token (as opposed to logging in).

The same token is successfully used to run `eas build` in the same environment.

excerpt from my github workflow:

```
      - uses: expo/expo-github-action@v6
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          eas-version: latest
          eas-cache: true
```

### Environment

  EAS CLI 0.33.1 environment info:
    System:
      OS: Linux 5.8 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.22.7 - /opt/hostedtoolcache/node/12.22.7/x64/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /opt/hostedtoolcache/node/12.22.7/x64/bin/npm
    Utilities:
      Git: 2.33.1 - /usr/bin/git
    npmPackages:
      expo: ~42.0.1 => 42.0.4 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: ~0.13.12 => 0.13.18 

### Error output

- Linking to project @***/***
✔ Linked to project @***/***consumer (​https://expo.dev/accounts/***/projects/***​)
    CombinedError: [GraphQL] Not authorized.
Error: Process completed with exit code 1.

### Reproducible demo or steps to reproduce from a blank project

Run `eas secret:create --name=XYZ --value ABC --force` when logged out of eas, with EXPO_TOKEN set to a valid token.

**Comment by dsokal** [comment]
Hey @mako-taco,

Thanks for reporting! Unfortunately, I couldn't repro the issue:
- https://github.com/dsokal/eas-test/runs/4078457607?check_suite_focus=true
- https://github.com/dsokal/eas-test/runs/4078479001?check_suite_focus=true
- https://github.com/dsokal/eas-test/runs/4078500752?check_suite_focus=true
- https://github.com/dsokal/eas-test/runs/4078508259?check_suite_focus=true

Maybe this was a transient error on our servers. Can you check if it's still not working for you?

**Comment by mako-taco** [comment]
thank you, i will check today. 

i notice you have a username set, in addition to a token. i was using a bot token (and no username). perhaps that has something to do with it.

**Comment by dsokal** [comment]
Actually, I also tested a config without the username set - https://github.com/dsokal/eas-test/commit/a18732004c30d4d40b54af2649c59a7bdac8b79d
It also worked, see the 3rd link from the previous comment.

**Comment by mako-taco** [comment]
Ok, so when I ran this again using my organizations's bot's access token, it failed.  When I tried to create a secret in my workflow using a _personal_ access token, it succeeded.

**Comment by mako-taco** [comment]
@dsokal anything else I can help with here?  Is using a bot token for creating secrets is something that is intended to be supported?

**Comment by dsokal** [comment]
This is a bug on the server side. This should be addressed by the end of the week. Sorry for the inconvenience.

**Comment by mako-taco** [comment]
no problem, thanks for being so responsive!

**Comment by dsokal** [comment]
@mako-taco this should work fine now :)
