### ISSUE TITLE
Eas build Only: ❌ Metro encountered an error: While trying to resolve module `css-tree` 

### ISSUE THREAD

**Issue by Jonatthu** [expo/eas-cli#720]
### Summary

This happens when I am using the next command:

eas build --profile preview --local -p ios --clear-cache

This is the eas.json config.
```
		"preview": {
			"distribution": "internal",
			"ios": {
				"simulator": true
			}
		},
```

### Environment

  EAS CLI 0.33.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.0 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 7.20.2 - /usr/local/bin/npm
    Utilities:
      Git: 2.31.0 - /opt/homebrew/bin//git
    npmPackages:
      expo: 42.0.0 => 42.0.0 
      expo-dev-client: 0.4.5 => 0.4.5 
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.33.1
      expo-cli: 4.11.0

### Error output

❌ Metro encountered an error:
While trying to resolve module `css-tree` from file `/private/var/folders/wr/sss6fkwj5l7b7l51g2kxktq80000gp/T/eas-build-local-nodejs/3f1998cb-f675-4371-9e30-ad4c7341f322/build/frontend/node_modules/react-native-svg/src/css.tsx`, the package `/private/var/folders/wr/sss6fkwj5l7b7l51g2kxktq80000gp/T/eas-build-local-nodejs/3f1998cb-f675-4371-9e30-ad4c7341f322/build/frontend/apps/portfolio/ios/build/Build/Products/Release-iphonesimulator/portfolio.app/assets/__node_modules/css-tree/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/private/var/folders/wr/sss6fkwj5l7b7l51g2kxktq80000gp/T/eas-build-local-nodejs/3f1998cb-f675-4371-9e30-ad4c7341f322/build/frontend/apps/portfolio/ios/build/Build/Products/Release-iphonesimulator/portfolio.app/assets/__node_modules/css-tree/lib/index.js`. Indeed, none of these files exist:

  * /private/var/folders/wr/sss6fkwj5l7b7l51g2kxktq80000gp/T/eas-build-local-nodejs/3f1998cb-f675-4371-9e30-ad4c7341f322/build/frontend/apps/portfolio/ios/build/Build/Products/Release-iphonesimulator/portfolio.app/assets/__node_modules/css-tree/lib/index.js(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * /private/var/folders/wr/sss6fkwj5l7b7l51g2kxktq80000gp/T/eas-build-local-nodejs/3f1998cb-f675-4371-9e30-ad4c7341f322/build/frontend/apps/portfolio/ios/build/Build/Products/Release-iphonesimulator/portfolio.app/assets/__node_modules/css-tree/lib/index.js/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)

[RUN_FASTLANE] › Generating debug iTrustCapital » portfolio.app.dSYM
[RUN_FASTLANE] ▸ ** BUILD FAILED **
[RUN_FASTLANE] ▸ The following build commands failed:
[RUN_FASTLANE] ▸        PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /var/folders/wr/sss6fkwj5l7b7l51g2kxktq80000gp/T/eas-build-local-nodejs/3f1998cb-f675-4371-9e30-ad4c7341f322/build/frontend/apps/portfolio/ios/build/Build/Intermediates.noindex/iTrustCapital.build/Release-iphonesimulator/iTrustCapital.build/Script-00DD1BFF1BD5951E006B06BC.sh
[RUN_FASTLANE] ▸ (1 failure)
[RUN_FASTLANE] ** BUILD FAILED **
[RUN_FASTLANE] 
[RUN_FASTLANE] 

### Reproducible demo or steps to reproduce from a blank project

https://github.com/Jonatthu/portfolio

**Comment by dsokal** [comment]
Hello @Jonatthu,

It seems to me this is not a problem with EAS CLI but with your project and the dependencies you're using. I cloned your repo and tried to run a cloud build (EAS Build) and it failed while installing dependencies. Most likely because you committed `node_modules` to the repo (https://github.com/Jonatthu/portfolio/tree/master/node_modules). This is an anti-pattern.

Can you please share the whole log output from the build command and share it as a file?

--- 

```
	"distribution": "internal",
	"ios": {
		"simulator": true
	}
```

You should not mix `"distribution": "internal"` with `"simulator": true`. If you want to build for internal distribution on Android and for iOS simulator you can configure it like:

```
  "android": {
    "distribution": "internal"
  },
  "ios": {
    "simulator": true
  },
```

**Comment by dsokal** [comment]
I removed `node_modules` from the cloned repo and ran another build - it succeeded. Maybe try doing the same?

**Comment by Jonatthu** [comment]
It worked after upgrading my xcode to 13.1
