### ISSUE TITLE
CLI doesn't warn about being outdated if not logged in

### ISSUE THREAD

**Issue by kbrandwijk** [expo/eas-cli#724]
### Summary

Normally, when there's an update available, the CLI will warn about being outdated. However, if you're not logged in to Expo yet, it prompts for the login, and skips the outdated warning.

### Environment

```
EAS CLI 0.34.0 environment info:
    System:
      OS: Linux 5.10 Debian GNU/Linux 9 (stretch) 9 (stretch)
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 14.17.5 - /usr/local/bin/node
      Yarn: 1.22.11 - /usr/local/bin/yarn
      npm: 6.14.14 - /usr/local/bin/npm
    Utilities:
      Git: 2.11.0 - /usr/bin/git
    npmPackages:
      expo: ^43.0.0 => 43.0.0 
      expo-dev-client: ~0.6.3 => 0.6.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.2 => 0.64.2 
      react-native-web: 0.17.1 => 0.17.1 
```

### Reproducible demo or steps to reproduce from a blank project

- Have an outdated eas cli installed
- Be logged out
- Run, for example, `eas build`
- See the login prompt only
- Run the command again after logging in
- See the outdated warning

**Comment by dsokal** [comment]
Talked with @kbrandwijk on Discord and it seems that this was a transient error with NPM.
