### ISSUE TITLE
eas build --auto-submit

### ISSUE THREAD

**Issue by humarkx** [expo/eas-cli#731]
### Summary

When using --auto-submit, it only builds, the submission never gets triggered

`npx eas-cli build --platform=ios --profile=development --non-interactive --auto-submit-with-profile=production`

![image](https://user-images.githubusercontent.com/13049940/140048278-13aa0bd2-72cc-4020-97d9-0f71524da777.png)

### Environment

  EAS CLI 0.34.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.16.1 - /usr/local/bin/node
      Yarn: 1.22.11 - ~/Projects/heyfina/heyfina-app/node_modules/.bin/yarn
      npm: 8.1.2 - /opt/homebrew/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
    npmPackages:
      expo: ^42.0.0 => 42.0.3
      expo-dev-client: ^0.6.3 => 0.6.3
      react: ^17.0.2 => 17.0.2
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    npmGlobalPackages:
      eas-cli: 0.34.0
      expo-cli: 4.12.10

### Error output

No error output

### Reproducible demo or steps to reproduce from a blank project

Running a build with --auto-submit or --auto-submit-with-profile

**Comment by dsokal** [comment]
Hi @humarkx,
Thanks for reporting. I tried to repro this issue but with no luck. Could you please share your `eas.json`?

**Comment by humarkx** [comment]
![image](https://user-images.githubusercontent.com/13049940/141108693-1e0d8c46-ff15-4ad1-bd58-055be0677cbc.png)

--auto-submit-with-profile  still doesn't work. 
I am still required to run eas submit afterwards :(

**Comment by dsokal** [comment]
Hey @humarkx, the fix is still not released. It'll be included in the next version.
