### ISSUE TITLE
Failed to install Expo CLI after trying to build with EAS

### ISSUE THREAD

**Issue by tusharkhatiwada** [expo/eas-cli#739]
### Summary

I am trying to do a build for ios using the command `eas build -p ios` but the build is failing with the following error:

**`Build failed: Failed to install Expo CLI. Make sure you specified the correct version in eas.json.`**

Here's my `eas.json` config:

```
{
  "build": {
    "preview": {
      "ios": {
        "simulator": true,
        "cache": {
          "disabled": true
        },
        "expoCli": "4.12.12"
      }
    },
    "production": {
      "releaseChannel": "production",
      "cache": {
        "disabled": true
      },
      "expoCli": "4.12.12",
      "ios": {
        "autoIncrement": "buildNumber"
      }
    }
  },
  "submit": {
    "production": {}
  },
  "cli": {
    "version": ">= 0.34.1"
  }
}
```

I tried to add the following line on package.json file as well. But that didn't work. https://github.com/veged/coa/issues/99
```
 "resolutions": {
    "coa": "2.0.2"
  },
```

![image](https://user-images.githubusercontent.com/5126590/140491828-19e447c9-5290-40e7-8fea-2ba075fb555c.png)

### Environment

```
 EAS CLI 0.34.1 environment info:
    System:
      OS: macOS 11.6.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Utilities:
      Git: 2.31.1 - /usr/local/bin/git
    npmPackages:
      expo: ^42.0.0 => 42.0.5
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
```

### Reproducible demo or steps to reproduce from a blank project

It was working 3 days ago with the same command `eas build -p ios`. Now it's not.

**Comment by RWOverdijk** [comment]
Resolutions only work with yarn I think. 

You should install the version specifically, I think it's stuck in your lock file maybe?

**Comment by tusharkhatiwada** [comment]
@RWOverdijk I manually installed the package with `yarn add coa` , but still the same problem.

![image](https://user-images.githubusercontent.com/5126590/140497734-378a28dd-dab5-40ab-b07e-c307e0a2baa0.png)

**Comment by RWOverdijk** [comment]
That might be because you're not directly using it. Some other package is. Check your lock file and look for coa. Or use ls to see why it's in your project to find out where the problem is

**Comment by tusharkhatiwada** [comment]
`expo-cli` is using that package and the build server is trying to install `expo-cli`. So unless the patch is released we can't do anything about it then.
I guess I'll try to make a PR

**Comment by RWOverdijk** [comment]
It's just weird to me, because those versions were pulled from npm. Is there some sort of build cache that needs to be invalidated maybe?

**Comment by tusharkhatiwada** [comment]
This issue has now been fixed. The maintainer turned off the npm proxy for the time being and it's working now.
