### ISSUE TITLE
Set Update priority in play store release

### ISSUE THREAD

**Issue by har2008preet** [expo/eas-cli#759]
To set the release [update priority](https://developer.android.com/guide/playcore/in-app-updates) for in-app update through cli.

**Comment by brentvatne** [comment]
can you provide more information about this and possibly a link to how this is accomplished with fastlane or some other tool?

**Comment by har2008preet** [comment]
@brentvatne i have recently configured jenkins for this using [Google Play Publisher](https://plugins.jenkins.io/google-play-android-publisher/) plugin. There is [Triple-T](https://github.com/Triple-T/gradle-play-publisher) lib as well, but was not able to integrate it properly. Internally, i think, it is done with [google play publisher edit](https://developers.google.com/android-publisher/api-ref/rest/v3/edits.tracks/update) api. If you want any other thing, please let me know.

**Comment by mjr** [comment]
Any update on this?

**Comment by mjr** [comment]
> can you provide more information about this and possibly a link to how this is accomplished with fastlane or some other tool?

This link explains a little about it:
https://developer.android.com/guide/playcore/in-app-updates/native#update-priority

**Comment by zetachang** [comment]
this could be really helpful
