### ISSUE TITLE
Local variables not working on building the app on android

### ISSUE THREAD

**Issue by felpsio** [expo/eas-cli#769]
### Summary

It doesn't load the local variables from dotenv/config when building the project on Android.

### Environment

EAS CLI 0.36.1 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    Utilities:
      Git: 2.33.1 - /opt/homebrew/bin/git
    npmPackages:
      expo: ^43.0.0 => 43.0.2 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.36.1
      expo-cli: 4.13.0

### Error output

It can't load any env variable. The variables works fine when I use the app with `expo start`. But they aren't accessible when I build it with `eas build -p android`

### Reproducible demo or steps to reproduce from a blank project

app.config.js
```
import 'dotenv/config';

export default {
  name: 'App',
  ...
  "android": {
    "package": "com.app.android",
    "versionCode": 42,
    "adaptiveIcon": {
      "foregroundImage": "./src/assets/images/adaptive-icon.png",
      "backgroundColor": "#ffffff"
    }
  },
  extra: {
    ENV: process.env.ENV,
  },
};
```

.env
```
env=DEV
```

app.jsx
```
const env = Constants.manifest?.extra.ENV;
```

**Comment by brentvatne** [comment]
please refer to https://docs.expo.dev/build-reference/variables/

**Comment by felpsio** [comment]
@brentvatne any guess why my env config works on ios and not on android?

**Comment by brentvatne** [comment]
if you can share a minimal reproducible example i'm happy to help you understand that! https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mnemosx** [comment]
Hi @felpsio,
Have you been able to resolve this?

**Comment by felpsio** [comment]
@mnemosx I duplicated the variables on eas.json and my .env file. I just need to use the eas.json envs on "production". So it makes pretty simple for me to manage. Locally the normal ".env" file works normal

**Comment by mnemosx** [comment]
> @mnemosx I duplicated the variables on eas.json and my .env file. I just need to use the eas.json envs on "production". So it makes pretty simple for me to manage. Locally the normal ".env" file works normal

Thanks! I was hoping I could find a solution for secrets that I wouldn't want to store in `eas.json`, but I now understand that you were probably talking about regular variables not secrets such as api keys.
