### ISSUE TITLE
EAS iOS build failed: Compatible version of some pods could not be resolved. Fully Managed Workflow

### ISSUE THREAD

**Issue by durgesh2007** [expo/eas-cli#774]
### Summary

iOS build failed:
Compatible version of some pods could not be resolved.
You are seeing this error because either:
  - Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that update value of "cache.key" field in the eas.json to invalidate the cache.
  - Some of your npm packages have native code that depend on different versions of the same pod. Please see logs for more info.

**Tried as per above error message said cache.key to invalid or any string in eas.json file**
No fix yet, need a more clear idea about this error.

eas.json file:

{
  "build": {
    "preview": {
      "ios": {
        "node": "16.13.0",
        "simulator": true,
        "cache": {
          "key": "181121"
        }
      }
    },
    "release": {},
    "release-stage": {
      "ios": {
        "releaseChannel": "stage",
        "image": "latest",
        "cache": {
          "disabled": true,
          "key": "17112021"
        }
      }
  },
  "cli": {
    "version": ">= 0.35.0",
    "requireCommit": true
  }
}

### Environment

**C:\_Projects\XXX>expo diagnostics**

  Expo CLI 4.12.10 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Expo Workflow: managed

**C:\_Projects\XXX>eas diagnostics**

  EAS CLI 0.36.1 environment info:
    System:
      OS: Windows 10 10.0.19042
    Binaries:
      Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.27.0.

### Error output

Installing pods
Installing unimodules:
 expo-app-auth@10.2.2 from ../node_modules/expo-app-auth/ios
 expo-application@3.1.2 from ../node_modules/expo-application/ios
 expo-constants@10.1.3 from ../node_modules/expo-constants/ios
 expo-device@3.2.0 from ../node_modules/expo-device/ios
 expo-error-recovery@2.1.0 from ../node_modules/expo-error-recovery/ios
 expo-facebook@11.0.5 from ../node_modules/expo-facebook/ios
 expo-file-system@11.0.2 from ../node_modules/expo-file-system/ios
 expo-font@9.1.0 from ../node_modules/expo-font/ios
 expo-image-loader@2.1.1 from ../node_modules/expo-image-loader/ios
 expo-keep-awake@9.1.2 from ../node_modules/expo-keep-awake/ios
 expo-localization@10.1.0 from ../node_modules/expo-localization/ios
 expo-location@12.0.4 from ../node_modules/expo-location/ios
 expo-modules-core@0.4.8 from ../node_modules/expo-modules-core/ios
 expo-network@3.1.1 from ../node_modules/expo-network/ios
 expo-notifications@0.11.6 from ../node_modules/expo-notifications/ios
 expo-permissions@12.0.1 from ../node_modules/expo-permissions/ios
 expo-splash-screen@0.13.5 from ../node_modules/expo-app-loading/node_modules/expo-splash-screen/ios
 expo-structured-headers@1.0.1 from ../node_modules/expo-structured-headers/ios
 expo-updates@0.5.5 from ../node_modules/expo-updates/ios
 unimodules-app-loader@2.1.0 from ../node_modules/unimodules-app-loader/ios
 unimodules-barcode-scanner-interface@6.1.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
 unimodules-camera-interface@6.1.0 from ../node_modules/unimodules-camera-interface/ios
 unimodules-constants-interface@6.1.0 from ../node_modules/unimodules-constants-interface/ios
 unimodules-core@7.1.2 from ../node_modules/@unimodules/core/ios
 unimodules-face-detector-interface@6.1.0 from ../node_modules/unimodules-face-detector-interface/ios
 unimodules-file-system-interface@6.1.0 from ../node_modules/unimodules-file-system-interface/ios
 unimodules-font-interface@6.1.0 from ../node_modules/unimodules-font-interface/ios
 unimodules-image-loader-interface@6.1.0 from ../node_modules/unimodules-image-loader-interface/ios
 unimodules-permissions-interface@6.1.0 from ../node_modules/unimodules-permissions-interface/ios
 unimodules-react-native-adapter@6.2.2 from ../node_modules/@unimodules/react-native-adapter/ios
 unimodules-sensors-interface@6.1.0 from ../node_modules/unimodules-sensors-interface/ios
 unimodules-task-manager-interface@6.1.0 from ../node_modules/unimodules-task-manager-interface/ios
Found some duplicated unimodule packages. Installed the ones with the highest version number.
Make sure following dependencies of your project are resolving to one specific version:
 expo-modules-core, expo-splash-screen
Auto-linking React Native modules for target `XXXXXXXX`: RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNReanimated, RNSVG, RNScreens, RNVectorIcons, lottie-react-native, react-native-geolocation-service, react-native-maps, react-native-safe-area-context, react-native-view-shot, react-native-viewpager, and stripe-react-native
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
CocoaPods 1.11.2 is available.
To update use: `sudo gem install cocoapods`
For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.11.2
[!] CocoaPods could not find compatible versions for pod "ExpoModulesCore":
  In Podfile:
    ExpoModulesCore (from `../node_modules/expo-modules-core/ios`)
Specs satisfying the `ExpoModulesCore (from `../node_modules/expo-modules-core/ios`)` dependency were found, but they required a higher minimum deployment target.
[stderr] [!] `<PBXResourcesBuildPhase UUID=`XXXXXXXXXXXXXXX`>` attempted to initialize an object with an unknown UUID. `XXXXXXXXXXXXXXXX` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
Error: Compatible version of some pods could not be resolved.
You are seeing this error because either:
  - Versions in the Podfile.lock cached by EAS do not match required values for some of the libraries, it can be triggered when upgrading Expo SDK or any other library with native code. To fix that update value of "cache.key" field in the eas.json to invalidate the cache.
  - Some of your npm packages have native code that depend on different versions of the same pod. Please see logs for more info.

### Reproducible demo or steps to reproduce from a blank project

https://github.com/durgesh2007/sample-facebook-login-code

**Comment by dsokal** [comment]
Hi @durgesh2007,
Thanks for reporting.

1. You don't need to change the cache key if you disabled cache entirely:
```
"cache": {
  "disabled": true,
  "key": "17112021" // <- this does not make sense with the line above
}
```
2. Could you please share the build details page URL?
3. The repo you shared (https://github.com/durgesh2007/sample-facebook-login-code) is empty.

**Comment by durgesh2007** [comment]
Hi @dsokal,
Thanks for the response,

I have created a build successfully 2 months ago there is no issue, after a few fixes now I'm trying to make a build then gives me the above error.

in 2 months ago build did not set any cache flag, after getting this issue trying to set flags for clearing cache.

Build cmd: eas build --profile release-stage --platform ios --clear-cache

Previous eas.json file(2 months ago):
{
  "builds": {
    "ios": {
      "release": {
        "buildType": "release"
      },
      "release-stage": {
        "buildType": "release",
        "releaseChannel": "stage"
      },
      "development": {
        "buildType": "development-client",
        "distribution": "internal",
        "enterpriseProvisioning": "adhoc",
        "autoIncrement": true,
        "image": "latest"
      }
    }
  }
}

Now eas.json file:
{
  "build": {
    "preview": {
      "ios": {
        "simulator": true,
        "cache": {
          "key": "181121"
        }
      }
    },
    "release": {},
    "release-stage": {
      "ios": {
        "releaseChannel": "stage",
        "cache": {
          "disabled": true
        }
      }
    },
    "development": {
      "ios": {
        "enterpriseProvisioning": "adhoc",
        "autoIncrement": true,
        "image": "latest",
        "developmentClient": true,
        "distribution": "internal"
      }
    }
  },
  "cli": {
    "version": ">= 0.35.0",
    "requireCommit": true
  }
}

pls, let me know if you need more details.
I'm struggling with this issue since last week.

**Comment by dsokal** [comment]
Could you please share the build details page URL?

**Comment by durgesh2007** [comment]
No, actually it's private repo.

**Comment by dsokal** [comment]
Sorry, we can't help you if you don't provide a reproducible demo or steps to reproduce from a blank project.

**Comment by durgesh2007** [comment]
Hi @dsokal,

1. Please use the following link to the Reproducible demo or steps to reproduce from a blank project:
https://github.com/durgesh2007/sample-facebook-login-code

2. command: eas build --profile release-stage --platform ios --clear-cache

3. 
![Screenshot (338)](https://user-images.githubusercontent.com/89899451/142661368-c14fb183-6a5b-4dd1-b103-713ab3a020d4.png)
![Screenshot (339)](https://user-images.githubusercontent.com/89899451/142661377-53ad29ad-8678-4b9a-9854-ca1914db5805.png)
![Screenshot (340)](https://user-images.githubusercontent.com/89899451/142661378-6aa2f141-731b-4349-980e-87bd62e76ed9.png)
![Screenshot (341)](https://user-images.githubusercontent.com/89899451/142661380-b7dcffc2-e5f9-4783-904e-76b481016ec2.png)
![Screenshot (342)](https://user-images.githubusercontent.com/89899451/142661381-03574e50-529b-4f22-90a8-2ef3dd1deb3d.png)
![Screenshot (343)](https://user-images.githubusercontent.com/89899451/142661382-17f99104-d523-472b-aedc-3d8b7e25def2.png)
Please see my attached screenshots:

**Comment by brentvatne** [comment]
you are using expo sdk 41 with versions of expo packages that are incompatible with it. run `expo doctor` to see information about that.

**Comment by brentvatne** [comment]
hi @durgesh2007 - it turns out this was on our end. we did not enforce a version of expo-google-app-auth and so your app uses an incompatible version for sdk 41. please change the expo-google-app-auth version to exactly 8.1.7 and run your build again

**Comment by durgesh2007** [comment]
Dear @brentvatne,
Thank you so much, now the build is generated successfully....!
