### ISSUE TITLE
`eas build:configure` fails to run if no `git` installed

### ISSUE THREAD

**Issue by psnet** [expo/eas-cli#779]
### Summary

`eas build:configure` fails to run if no `git` command available (no git installed)

### Environment

Windows 10
EAS CLI 0.37.0

### Error output

eas build:configure
💡 The following process will configure your iOS and/or Android project to be compatible with EAS Build. These changes only apply to your local project files and you can safely revert them at any time.

√ Which platforms would you like to configure for EAS Build? » All
    Error: git command not found, install it before proceeding

### Reproducible demo or steps to reproduce from a blank project

Use any project and dont install `git` and try to run `eas build:configure` - it will fail to run

### Expected behaviour

I think EXPO/EAS should not depend on `git` installed in system.

**Comment by dsokal** [comment]
Hi @psnet,
Thanks for reporting. Actually, EAS CLI does not require you to have `git` installed. If you want to use the CLI without Git, you should set the `EAS_NO_VCS=1` environment variable. See https://expo.fyi/eas-vcs-workflow for more details.

**Comment by solmaz006** [comment]
hi how can i set EAS_NO_VCS=1 environment variable
please say me

**Comment by KelvynSinhorini** [comment]
> oi como posso definir EAS_NO_VCS = 1 variável de ambiente por favor me diga

https://stackoverflow.com/a/73500190
