### ISSUE TITLE
Generate an unsigned .aab

### ISSUE THREAD

**Issue by chunlaw** [expo/eas-cli#782]
In the [documentation](https://docs.expo.dev/app-signing/app-credentials/), it is stated that "EAS Build can generate signed or **unsigned** applications". I would like to ask the steps to generate an unsigned app.

I have tried to remove the Android Keystore but the build process has been blocked by asking me to submit/generate a new one. I know it is a must to submit a signed .aab to Play Store. However, as a vendor, my app will be signed by the institution and it is required me to submit an unsigned .aab. How could I accomplish it by EAS build?

**Comment by chunlaw** [comment]
I have found the way to un-signing the aab via zip and zipalign.

**Comment by first-dev** [comment]
Hi @chunlaw, can you please share more details, links, sources or anything.
Thank you.
