### ISSUE TITLE
EAS build vs expo build: code executing differences

### ISSUE THREAD

**Issue by psnet** [expo/eas-cli#799]
### Summary

I tried both build systems and behavior of “back” button in android is different:

In old classic expo build when I press “back” app is not really closed, it is running in background, when I run app again it is opened immediately.

In new EAS build when I press “back” button and run it again (all with same 2 seconds delay) I see splash loading screen which stays visible much less time than when app is really closed (“cold” start) but splash screen means that app is loading again (!) but app was not really (fully) closed. Some code of app works like it is cold start (inits) and some code (mostly animations with “useNativeDriver”) is still running.

This looks very strange.

Are big differences in handling “back” button in these build systems and why on new EAS build I see splash startup screen every time I open app even after 2 seconds? On old expo build system the same code base works as expected (no splash screen on reopen app)

### Environment

SDK: 42
eas: 0.37.0

### Reproducible demo or steps to reproduce from a blank project

Original discussion is here https://forums.expo.dev/t/eas-build-vs-expo-build-code-executing-differences/59384

The same problem has other users. Such strange behavior is in any project.

**Comment by brentvatne** [comment]
hi there! the best place to post an issue is https://github.com/expo/expo/issues - please share a reproducible example there.
