### ISSUE TITLE
Add support to git-crypt keys

### ISSUE THREAD

**Issue by veeramarni** [expo/eas-cli#803]
There is support to secrets in the EAS through UI which only support text. But if we have encrypted files using git-crypt, we need to run `git-crypt unlock  ./path-of-file-to-store-key` before installing the git project. How to pass the key which is a binary file?

Details of git-crypt can be found here https://thearjunmdas.github.io/entries/encrypt-decrypt-files-with-git/

**Comment by dsokal** [comment]
Hi!
Can you elaborate on what is exactly your use case?

> How to pass the key which is a binary file?
You can for example convert the binary file to a base64-encoded string like this:
`base64 file > file.b64`
and then set an env var with the contents of `file.b64`. You'll need to decode the env on the EAS worker. E.g. using npm hooks: https://docs.expo.dev/build-reference/how-tos/#eas-build-specific-npm-hooks

**Comment by wkozyra95** [comment]
This is example of how to pass ssh keys to fetch private submodules https://docs.expo.dev/build-reference/how-tos/#how-to-use-git-submodules

It should be very easy to adapt this script to pass encryption key instead and unlock repo

**Comment by dsokal** [comment]
Closing the issue because of the inactivity.
