### ISSUE TITLE
React Native Expo Build Failing due to cocoapods version

### ISSUE THREAD

**Issue by Bidireac** [expo/eas-cli#807]
### Summary
I am trying to build and test push notifications in a react-native app with firebase, but everytime I run eas build --platform ios, I keep getting an error regarding the cocoapods.

### Environment
eas.json file looks like this: 
```
{
  "cli": {
    "version": ">= 0.38.3"
  },
  "build": {
    "development": {
      "distribution": "internal",
      "android": {
        "gradleCommand": ":app:assembleDebug"
      },
      "ios": {
        "buildConfiguration": "Debug",
        "cocoapods": "1.11.2"
      }
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}

```

### Error output
Error from the expo.dev:
```
The version of CocoaPods used to generate the lockfile (1.11.2) is higher than the version of the current executable (1.10.1). Incompatibility issues may arise.
```
I have run the pod --version command to check, and I have the latest version which at the moment is 1.11.2, so I don't understand why it complains about it, nor why it says that the current executable is a different version.

Error inside the terminal:
```
Build failed: Your project requires a newer version of CocoaPods, you can update it in the build profile in eas.json by either:
- changing the current version under key "cocoapods"
- switching to an image that supports that version under key "image"
```

### Reproducible demo or steps to reproduce from a blank project

expo init

npm install @react-native-firebase/analytics
npm install @react-native-firebase/app
npm install @react-native-firebase/in-app-messaging
npm install @react-native-firebase/messaging

cd ios/
pod install --repo-update
cd ..

expo run:ios

eas build --platform ios

**Comment by brentvatne** [comment]
you can [specify the cocoapods version that you want to use](https://docs.expo.dev/build/eas-json/#configuring-your-build-tools)

might be neat for us to detect it, though!
