### ISSUE TITLE
How to change the name of my app for the eas submit to the App Store

### ISSUE THREAD

**Issue by jesuscovam** [expo/eas-cli#814]
### Summary

I'm having this error where the AppStore is blocking my eas submit because the name of the app is on their registry for an old app i submitted before. I have changed the name of the app.json but it doesn't change the name when its submitted to the store
<img width="861" alt="Screen Shot 2021-12-02 at 12 59 48" src="https://user-images.githubusercontent.com/46403187/144477774-66e614ac-94bb-4be8-a393-018e230024ba.png">

I saw somebody else managed to fix this for expo upload but I'm not sure how to do it with eas submit
[expo upload solution](https://benborgers.com/posts/expo-app-name)

### Environment

  EAS CLI 0.38.3 environment info:
    System:
      OS: macOS 11.4
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
      Yarn: 1.22.10 - /opt/homebrew/bin/yarn
      npm: 7.22.0 - ~/.nvm/versions/node/v14.17.1/bin/npm
    Utilities:
      Git: 2.32.0 - /opt/homebrew/bin/git
    npmPackages:
      expo: ~43.0.0 => 43.0.2
      expo-dev-client: ~0.6.3 => 0.6.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.38.3
      expo-cli: 4.13.0

### Error output

✖ Failed to create App Store app slissto app
The provided entity includes an attribute with a value that has already been used on this account. - The app name you entered is already being used for another app in your account. If you would like to use the name for this app you will need to submit an update to your other app to change the name, or remove it from App Store Connect.
Please visit https://appstoreconnect.apple.com and resolve any warnings, then try again.
    Error: Submission failed

### Reproducible demo or steps to reproduce from a blank project

```
{
  "expo": {
    "name": "Slissto: Aplicación para prestadores de servicio",
    "slug": "slissto-slisstos",
    "version": "1.0.1",
    "orientation": "portrait",
    "icon": "./assets/images/icon_beta.png",
    "scheme": "slissto-slisstos",
    "userInterfaceStyle": "automatic",
    "jsEngine": "hermes",
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "slissto",
            "project": "slissto-slisstos",
            "authToken": "xxxxxxxx"
          }
        }
      ]
    },
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.slissto.slisstos"
    },
    "android": {
      "versionCode": 2,
      "package": "com.slissto.slisstos"
    },
    "web": {
      "favicon": "./assets/images/favicon.png"
    },
    "plugins": ["sentry-expo"]
  }
}

```

**Comment by dsokal** [comment]
Hi @jesuscovam, 
Just provide `appName` in the submit profile: https://docs.expo.dev/submit/eas-json/#appname
Let me know if this helped.

**Comment by jesuscovam** [comment]
> Hi @jesuscovam, Just provide `appName` in the submit profile: https://docs.expo.dev/submit/eas-json/#appname
> 
> ```
> {
>   "submit": {
>     "production": {
>       "ios": {
>         "appName": "foobar"
>       }
>     }
>   }
> }
> ```
> 
> Let me know if this helped.

yes It was that and kinda feel embarrassed but thank you 🙏🏼
