### ISSUE TITLE
Release channel set in eas.json is not reflected in Updates.releaseChannel (iOS only)

### ISSUE THREAD

**Issue by Goszu** [expo/eas-cli#819]
### Summary

Release channel set in `eas.json` is not reflected in Updates.releaseChannel. This happens only with iOS build.
`Configure expo updates` step correctly returns `Setting the release channel in 'Expo.plist' to 'pre-prod'`.
Updates.releaseChannel returns `default`.

On Android everything works correctly.

### Environment

 EAS CLI 0.38.3 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.1.8 - /usr/local/bin/bash
    Binaries:
      Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v12.18.2/bin/yarn
      npm: 8.1.4 - ~/.nvm/versions/node/v12.18.2/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
    npmPackages:
      expo: ^43.0.0 => 43.0.3 
      expo-dev-client: ^0.6.3 => 0.6.3 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.38.3
      expo-cli: 4.13.0

### Reproducible demo or steps to reproduce from a blank project

populate eas.json with:
```
{
  "cli": {
    "version": ">= 0.38.2"
  },
  "build": {
    "dev": {
      "releaseChannel": "pre-prod",
      "distribution": "internal",
      "developmentClient": true
    },
    "pre-prod": {
      "releaseChannel": "pre-prod"
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}
```

run `eas build --profile dev --platform ios`

install the app on on physical device (iOS 15.1.1)

run the app locally `expo start --dev-client`

log the value of `Updates.releaseChannel`

**Comment by dsokal** [comment]
Hi @Goszu,
Have you, by any chance, disabled OTA updates? See https://github.com/expo/eas-cli/issues/699 and let me know if this is the same issue.

**Comment by Goszu** [comment]
Hi @dsokal 
No I didn't disable OTA updates but https://github.com/expo/eas-cli/issues/699 looks similar.
I did more testing and in my case it only happens on internal build using development client (and only on iOS).
I created a built using `pre-prod` profile and uploaded it to test flight and can confirm that release channel works correctly there.

**Comment by Goszu** [comment]
Thank you @byCedric 🍻

**Comment by byCedric** [comment]
No problem, it was a team effort :) Thanks for finding this bug, we still need to deploy some new SDK versions so hang on tight!

**Comment by iuliuvisovan** [comment]
So just to confirm, in SDK 46 a build with this config:
```
 "staging-local": {
      "distribution": "internal",
      "channel": "staging",
      "ios": {
        "simulator": true
      }
    },
```

will produce an app that when run on the Simulator will have the `default` release channel.

Is this the intended behaviour? And will it correctly use the staging channel when installed through TestFlight?

**Comment by humandevs** [comment]
Yeah, this is broken still. Updates.channel is blank, unless an update has been pushed via Updates (the initial build is just "blank" even though it's in the channel specified by the profile:

{
  "build": {
    "release": {
      "channel": "release",
      "releaseChannel": "release",
      }
    }
}

Outputs Updates.channel = null and Updates.releaseChannel = "default"

**Comment by humandevs** [comment]
Ah, this happens if you build a development build. Updates.channel is available if you build a production build.
