### ISSUE TITLE
Login Issue.

### ISSUE THREAD

**Issue by Kumar2106** [expo/eas-cli#831]
### Summary

I have installed the EAS cli yestered, and tried to login in with my account. i have tried the command eas login but it is giving me error telling 

Log in to EAS
               error:- Input is required , but stdin is not redeable.

I am unable to login into EAS using cli.

### Managed or bare?

Currently it is bare, i have not generated any build till now because of this error.

### Environment

EAS CLI 0.39.0 environment info:
    System:
      OS: Windows 10 10.0.22000
    Binaries:
      Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
      Yarn: No HADOOP_CONF_DIR set.
Please specify it either in yarn-env.cmd or in the environment. - C:\Program Files\hadoop\bin\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.33.0. - /mingw64/bin/git
    npmPackages:
      expo: ~43.0.2 => 43.0.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Project workflow: generic

### Error output

EXPO_DEBUG=true eas login
Log in to EAS
    Error: Input is required, but stdin is not readable.

### Reproducible demo or steps to reproduce from a blank project

You have to just enter 

eas login

this will produce the error.

**Comment by wkozyra95** [comment]
there are some issues on windows with detecting whether you are in interactive terminal e.g. https://github.com/nodejs/node/issues/3006

The terminal you are using does not set `process.stdout.isTTY` correctly, so we can't display prompt for login/password

Try using PowerShell instead

**Comment by Kumar2106** [comment]
I am now using command prompt it is working right now, but i got some another issue, do i need a play console and Apple developer account to use the eas services, because currently i am not having either of them.

**Comment by brentvatne** [comment]
you need an apple developer account if you are going to do an internal distribution or app store build for ios. you do not need a google play developer account to build your android app but you do need it to submit it.

**Comment by nandorojo** [comment]
I got this same error for a very different cause. I had a GitHub action like this:

```yml
      - name: Publish update
        run: eas update --auto
```

However, since I was in a monorepo, this was running in the root. Adding `working-directory` fixed that. Pretty obscure case, but figured I'd share in case it happens to anyone else

**Solution:**

```yml
      - name: Publish update
        working-directory: ./apps/expo
        run: eas update --auto
```

**Comment by bernardoeuler** [comment]
I got the same error while trying to build:

```yaml
       - run: eas build --non-interactive --platform all
```

Did anyone find a solution that works here too?

**Comment by Roshdy** [comment]
try run `eas update:configure`

**Comment by erichcervantez** [comment]
Same thing happened to me, but I was trying to use the Git Bash terminal.  Switched over to a regular Windows command prompt window and it worked from there.

**Comment by samayo** [comment]
> Same thing happened to me, but I was trying to use the Git Bash terminal. Switched over to a regular Windows command prompt window and it worked from there.

Thanks a lot. You save me from a miserable experience. I wish the developers didn't release this up until it was stable and functional to use.
