### ISSUE TITLE
App Submission Detail point to wrong URL

### ISSUE THREAD

**Issue by giautm** [expo/eas-cli#843]
https://github.com/expo/eas-cli/blob/ef566b3f9c01e12e8120801a34e9b64c1959e22e/packages/eas-cli/src/submit/utils/urls.ts#L27

Based on my app, it should be:
`/accounts/${app.ownerAccount.name}/projects/${app.slug}/submissions/${id}`

**Comment by dsokal** [comment]
Please fill in the issue template.
