### ISSUE TITLE
[iOS] runtimeVersion from Expo.plist ignored

### ISSUE THREAD

**Issue by hannojg** [expo/eas-cli#855]
### Summary

I know that the issue is not specific to the eas-cli itself, but rather to the build service, however, I still thought it fits best here (please correct me otherwise).
The official documentation states that for a runtime version in a bare project you have to set `EXUpdatesRuntimeVersion` in the `Expo.plist` (see [here](https://docs.expo.dev/distribution/runtime-versions/#configuration-for-the-bare-workflow)).
I did this, and when building the project locally I can see that when inspecting the built ipa file that the contained `Expo.plist` contains the runtime version (obviously). However, when building the app with `eas build` this configuration is ignored. The resulting ipa file's `Expo.plist` doesn't contain the `runtimeVersion`.

To me, it feels like Runtime Versions are not supported yet with eas build?

### Managed or bare?

Bare

### Environment

```  
EAS CLI 0.40.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Utilities:
      Git: 2.33.1 - /usr/local/bin/git
    npmPackages:
      expo: ^43.0.1 => 43.0.3 
      expo-dev-client: ~0.6.3 => 0.6.3 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: ~0.65.2 => 0.65.2 
      react-native-web: 0.17.5 => 0.17.5 
    npmGlobalPackages:
      eas-cli: 0.40.0
      expo-cli: 4.12.12
    Project workflow: generic
```

### Error output

There is no error output by the CLI itself

### Reproducible demo or steps to reproduce from a blank project

1. Create a bare expo project (dev client)
2. Set a `EXUpdatesRuntimeVersion` key value in the `Expo.plist`
3. Build the iOS app with eas
4. See how your set runtime version has been ignored in the final build artifact

**Comment by dsokal** [comment]
Hi @hannojg,

- Could you please share the build details URL? Only Expo team members will be able to view the page.
- Can you please share your eas.json and let me know which build profile you're using to build the app?

**Comment by hannojg** [comment]
* Build URL: https://expo.dev/accounts/skillnation/projects/Overscore/builds/7bd2e58f-78a2-40df-a3f6-9347fd32e8d1
* The `eas.json`, used profile `debug-internal`:

```json
{
  "cli": {
    "version": ">= 0.40.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal",
      "android": {
        "gradleCommand": ":app:assembleDebug"
      },
      "ios": {
        "scheme": "Debug",
        "buildConfiguration": "Debug",
        "cocoapods": "1.11.2"
      }
    },
    "staging-internal": {
      "distribution": "internal",
      "credentialsSource": "local",
      "ios": {
        "scheme": "Staging",
        "buildConfiguration": "StagingDebug",
        "cocoapods": "1.11.2"
      }
    },
    "debug-internal": {
      "extends": "staging-internal",
      "ios": {
        "scheme": "Debug",
        "buildConfiguration": "Debug"
      }
    },
    "production": {}
  },
  "submit": {
    "production": {}
  }
}

```

**Comment by hannojg** [comment]
Whow, so I just wanted to test this a bit more and run:
```bash
npx eas-cli build:inspect --profile debug-internal -p ios -s pre-build --output ...
```
**When the Compressing project files job is running I can see that the runtime version gets removed from the Expo.plist**

running `git diff` shows this:
```diff
diff --git a/ios/overscore/Supporting/Expo.plist b/ios/overscore/Supporting/Expo.plist
index 872fc44b..86198322 100644
--- a/ios/overscore/Supporting/Expo.plist
+++ b/ios/overscore/Supporting/Expo.plist
@@ -14,7 +14,5 @@
     <string>43.0.0</string>
     <key>EXUpdatesURL</key>
     <string>https://exp.host/@skillnation/Overscore</string>
-    <key>EXUpdatesRuntimeVersion</key>
-    <string>1.0.0+bundleVersion.7+ios-staging+overscore+0.40.0-staging.0</string>
   </dict>
-</plist>
+</plist>
\ No newline at end of file
```

**Comment by hannojg** [comment]
@dsokal Thanks for investigating that!

I already set the `runtimeVersion` but in the dynamic config, so in my `app.config.js`, which looks like this:

```js
export default ({ config }) => {
  const updatedConfig = {
    ...config,
  };
  const runtimeVersion = process.env.EXPO_RUNTIME_VERSION;
  if (
    typeof runtimeVersion === "string" &&
    runtimeVersion.length > 0
  ) {
    updatedConfig.runtimeVersion = runtimeVersion;
  }

  return updatedConfig;
};
```

As far as I can tell, this has no impact on the eas build that gets created (other than that I know that its working, because in CI we run `EXPO_RUNTIME_VERSION=... npx expo publish ...` and there I can see in the logs that the runtime version gets picked up.

Did you expect that setting the `runtimeVersion` has an impact on the native ios build?

**Comment by dsokal** [comment]
Ah, I see! Do you set the `EXPO_RUNTIME_VERSION` env var when running `eas build`? If not, this is the problem.

**Comment by dsokal** [comment]
Also, see the doc - https://docs.expo.dev/build-reference/variables/#common-questions

**Comment by hannojg** [comment]
Omg, you are right. I think in the CI script I forgot to set the env. Let me double-check on this, but  I think that's it … (I thought putting it in the Expo.plist would be enough - maybe this should be added to the documentation for runtime version that eas build depends on the value in the app.json for that?)

**Comment by hannojg** [comment]
Yes, when setting the runtime version env when calling `eas build` everything works as expected. Closing this for now, thx!

**Comment by jkhales** [comment]
Happy you were able to resolve this @hannojg, but @dsokal is right that this is weird behavior, thanks for bringing it to our attention!
