### ISSUE TITLE
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoHaptics' from project 'Pods')

### ISSUE THREAD

**Issue by TomasSestak** [expo/eas-cli#859]
### Summary

When I run eas build, the build fails
https://expo.dev/accounts/yolk/projects/orbi-app/builds/bd2ee066-22ff-4153-9577-011f07174efc

### Managed or bare?

Bare

### Environment

EAS CLI 0.41.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.4 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: 43.0.3 => 43.0.3 
      expo-dev-client: ^0.6.3 => 0.6.3 
      expo-updates: ~0.10.13 => 0.10.15 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: ^0.13.12 => 0.13.18
    Project workflow: generic

### Error output

❌  (node_modules/expo-haptics/ios/HapticsModule.swift:26:34)

  24 |   }
  25 | 
> 26 |   enum NotificationType: String, EnumArgument {
     |                                  ^ cannot find type 'EnumArgument' in scope
  27 |     case success
  28 |     case warning
  29 |     case error

❌  (node_modules/expo-haptics/ios/HapticsModule.swift:43:29)

  41 |   }
  42 | 
> 43 |   enum ImpactStyle: String, EnumArgument {
     |                             ^ cannot find type 'EnumArgument' in scope
  44 |     case light
  45 |     case medium
  46 |     case heavy

❌  (node_modules/expo-haptics/ios/HapticsModule.swift:7:5)

   5 |     name("ExpoHaptics")
   6 | 
>  7 |     function("notificationAsync") { (notificationType: NotificationType) in
     |     ^ cannot find 'function' in scope
   8 |       let generator = UINotificationFeedbackGenerator()
   9 |       generator.prepare()
  10 |       generator.notificationOccurred(notificationType.toFeedbackType())

### Reproducible demo or steps to reproduce from a blank project

Install expo-haptics and run eas build for ios

**Comment by barthap** [comment]
Hello, could you please provide which version of `expo-haptics` do you have installed in your `package.json`?
The errors suggest that your haptics code is trying to access some new code added in `expo@44.0.0` which is not available in your version (`43.0.3`). You can either:
- Upgrade `expo` to 44
- Downgrade `expo-haptics` to `11.0.3` I think.

My suspicions should be correct if your haptics version is `11.1.0`.

Some tips to avoid such errors in future:
- use `expo install` instead of `yarn add` / `npm i` when installing expo packages - this command will ensure correct versions
- you can manually see which package versions are correct for your expo version [here (for expo@43.x.x)](https://github.com/expo/expo/blob/5d6ccde6366b94961f774ed563192348aaf143a9/packages/expo/bundledNativeModules.json#L55)

**Comment by TomasSestak** [comment]
Hi, thank you for your response.

I had the same idea - so I did expo install expo-haptics and ended up with
"expo-haptics": "~11.0.3" in package.json 
and
  - EXHaptics (11.0.3):
    - ExpoModulesCore
in Podfile.lock

and it was still failing, after that I posted here.

I also had idea to upgrade SDK but https://docs.expo.dev/workflow/upgrading-expo-sdk-walkthrough/ this link insn't updated, so I didn't know there is new SDK version. Thank you for the blog post link. I upgraded and It works fine now. Thank you!

just a note: yarn global add expo-cli@latest still installs 5.0.1

**Comment by shandiz** [comment]
Hi, I'm getting the exact same error on expo 44. (Managed. not Bare)
I've uninstalled expo-haptics, and reinstalled it using "expo install". I have "expo-haptics": "~11.0.3" in package.json and the expo version is 44.0.0. However, I'm getting the exact same errors:

❌  (node_modules/expo-haptics/ios/HapticsModule.swift:26:34)

  24 |   }
  25 | 
> 26 |   enum NotificationType: String, EnumArgument {
     |                                  ^ cannot find type 'EnumArgument' in scope
  27 |     case success
  28 |     case warning
  29 |     case error

❌  (node_modules/expo-haptics/ios/HapticsModule.swift:43:29)

  41 |   }
  42 | 
> 43 |   enum ImpactStyle: String, EnumArgument {
     |                             ^ cannot find type 'EnumArgument' in scope
  44 |     case light
  45 |     case medium
  46 |     case heavy

❌  (node_modules/expo-haptics/ios/HapticsModule.swift:7:5)

   5 |     name("ExpoHaptics")
   6 | 
>  7 |     function("notificationAsync") { (notificationType: NotificationType) in
     |     ^ cannot find 'function' in scope
   8 |       let generator = UINotificationFeedbackGenerator()
   9 |       generator.prepare()
  10 |       generator.notificationOccurred(notificationType.toFeedbackType())
› Compiling expo Pods/Expo » Expo-dummy.m
› Compiling expo Pods/Expo » EXAppDefinesLoader.m
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'ExpoHaptics' from project 'Pods')
▸ 	CompileSwift normal arm64 /Users/expo/workingdir/build/node_modules/expo-haptics/ios/HapticsModule.swift (in target 'ExpoHaptics' from project 'Pods')
▸ (2 failures)
** ARCHIVE FAILED **
