### ISSUE TITLE
EAS build fails on iOS with ** ARCHIVE FAILED **

### ISSUE THREAD

**Issue by irakli-g** [expo/eas-cli#860]
### Summary

I'm trying to build my project with EAS and I end up with the issue. I've made many changes but could not go pass the ARCHIVE FAILED error. Any help would be appreciated.

my app.json

```
{
    "expo": {
        "name": "bilibo",
        "slug": "bilibo",
        "owner": "XXXXX",
        "description": "Bilibo was built exclusively for students helping them to organise academic life, share experiences, create groups, prepare for exams, upload, share and store study materials, manage tasks, and many more.",
        "version": "1.0.0",
        "privacy": "hidden",
        "orientation": "portrait",
        "icon": "./app/assets/icon.png",
        "entryPoint": "./app/App.tsx",
        "splash": {
            "image": "./app/assets/splash.png",
            "resizeMode": "contain",
            "backgroundColor": "#ffffff"
        },
        "updates": {
            "fallbackToCacheTimeout": 0
        },
        "assetBundlePatterns": ["**/*"],
        "primaryColor": "#6a51c6",
        "ios": {
            "supportsTablet": false,
            "usesIcloudStorage": true,
            "infoPlist": {
                "UIBackgroundModes": "remote-notification",
                "NSUserTrackingUsageDescription": "The app uses this information to deliver personalized ads.",
                "NSCameraUsageDescription":"The app uses camera to upload photos directly to the app.",
                "NSLocationWhenInUseUsageDescription":"The app uses location to automatically set Country and City fields at registration.",
                "NSPhotoLibraryUsageDescription":"The app uses photo library to upload photos directly to the app."
            },
            "jsEngine": "hermes",
            "bundleIdentifier": "XXXXX"
        },
        "android": {
            "softwareKeyboardLayoutMode": "pan",
            "adaptiveIcon": {
                "foregroundImage": "./app/assets/adaptive-icon.png",
                "backgroundColor": "#FFFFFF"
            },
            "jsEngine": "hermes",
            "useNextNotificationsApi": true
        },
        "plugins": ["expo-tracking-transparency", 
            [
            "expo-document-picker",
            {
              "appleTeamId": "XXXXX"
            }
          ]]
    }
}

```

### Managed or bare?

Managed

### Environment

```
  EAS CLI 0.41.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.0 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 7.17.0 - /usr/local/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: ^43.0.0 => 43.0.0 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.1
    Project workflow: managed
```

### Error output

```
Compiling expo-task-manager Pods/EXTaskManager » EXTaskManager.m

▸ ** ARCHIVE FAILED **

▸ The following build commands failed:

▸ PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/expo/Library/Developer/Xcode/DerivedData/bilibo-crdkdifzvghelvevlkgcthtngadr/Build/Intermediates.noindex/ArchiveIntermediates/bilibo/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-49F93F43B9AB98D31CB55A39585BC5D3.sh (in target 'EXUpdates' from project 'Pods')

▸ (1 failure)

** ARCHIVE FAILED **
The following build commands failed:
 PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/expo/Library/Developer/Xcode/DerivedData/bilibo-crdkdifzvghelvevlkgcthtngadr/Build/Intermediates.noindex/ArchiveIntermediates/bilibo/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-49F93F43B9AB98D31CB55A39585BC5D3.sh (in target 'EXUpdates' from project 'Pods')

(1 failure)
Exit status: 65
```

### Reproducible demo or steps to reproduce from a blank project

It's difficult to reproduce this issue i've been working on my project for past 4 months and start to run builds only recently, in particular, today.

**Comment by dsokal** [comment]
Hi @irakli-g,
Could you please share your build details page URL (it can be only viewed by the Expo team members)? The error output you shared is too generic to say anything.

**Comment by irakli-g** [comment]
@dsokal https://expo.dev/accounts/homos/builds/6fb36bd5-e0c9-4a9c-9386-7074d539743f this is the build details URL.

**Comment by mariomurrent-softwaresolutions** [comment]
@dsokal I'm having a similar error after upgrading to SDK44:

Mine seems to be more generic and no idea what's failing:

https://expo.dev/accounts/lightstalker89/projects/dec112-react-native/builds/b7480a8a-9e09-4e81-aa5a-3e23195bda61

**Comment by wkozyra95** [comment]
@irakli-g If you check xcode logs in the last section there is an error from expo-updates, sth about entrypoint of your application is misconfigured.

@mariomurrent-softwaresolutions your js does not compile 
```
error Unable to resolve module ./appleHealth from /Users/expo/workingdir/build/utils/message.ts: 
```

**Comment by mariomurrent-softwaresolutions** [comment]
> @irakli-g If you check xcode logs in the last section there is an error from expo-updates, sth about entrypoint of your application is misconfigured.
> 
> @mariomurrent-softwaresolutions your js does not compile
> 
> ```
> error Unable to resolve module ./appleHealth from /Users/expo/workingdir/build/utils/message.ts: 
> ```

Uh, did I oversee something? Where did you finde this error message? ... 
Seems like I'm blind. 
The interesting thing is, why does it work with SDK43 :D ...

**Comment by irakli-g** [comment]
@wkozyra95 yes I'm not using the default entry point I've changed it right from the start. Please look at the attached images, am I doing something wrong there?
<img width="977" alt="Screenshot 2021-12-21 at 18 30 23" src="https://user-images.githubusercontent.com/70649220/146946738-05790810-5b5d-41d5-84ef-26e8a515fa84.png">
<img width="523" alt="Screenshot 2021-12-21 at 18 30 37" src="https://user-images.githubusercontent.com/70649220/146946750-17204380-95bf-4cbd-a2f1-341045885bb4.png">
<img width="518" alt="Screenshot 2021-12-21 at 18 31 02" src="https://user-images.githubusercontent.com/70649220/146946753-0edf98c5-0150-43a2-bf7b-31922d0b17c7.png">

**Comment by wkozyra95** [comment]
Custom entry points do not work with eas yet,

With classic build we bundled js separately and sent it to the worker, so we could decide which file is an entrypoint, but with eas, the react-native build script is responsible for building js code.

**Comment by mariomurrent-softwaresolutions** [comment]
@wkozyra95 
Error: Unable to resolve module expo-updates from /private/tmp/expo/build/utils/app.ts: expo-updates could not be found within the project or in these directories:
  node_modules

expo-updates is actually installed but not found? Why is this happening?

**Comment by irakli-g** [comment]
@wkozyra95 I've reverted entry point to default one but my build still fails. Can you please take a look?
https://expo.dev/accounts/homos/projects/bilbbo/builds/b28d0553-ce93-4d4e-ab6a-0a7ef1541f44

**Comment by mariomurrent-softwaresolutions** [comment]
> @wkozyra95 I've reverted entry point to default one but my build still fails. Can you please take a look?
> 
> https://expo.dev/accounts/homos/projects/bilbbo/builds/b28d0553-ce93-4d4e-ab6a-0a7ef1541f44

Have You upgraded to the latest versions of expo SDK and cli?
Can you build it locally on your machine?

**Comment by irakli-g** [comment]
@mariomurrent-softwaresolutions  Yes, I've updated Expo SDK and eas-cli too.

I'm seeing this error and I can't figure out why
<img width="1030" alt="Screenshot 2021-12-26 at 22 25 36" src="https://user-images.githubusercontent.com/70649220/147416912-b09b9d8a-b586-4f3f-afa1-31ce9f61cb04.png">

**Comment by wkozyra95** [comment]
@irakli-g I'm not sure about that entitlements error, but your last app store builds is failing because your js does not build correctlly. Check "Xcode logs" section for more details

```
Error: Unable to resolve module ./app/aws-exports from /Users/expo/workingdir/build/App.js: 
```

You can verify what files are uploaded to eas workers with
`eas build:inspect --platform ios --output /example/path --stage archive`
or you can run "partial" build and debug it from there (it will configure project the same way as on eas but it won't run actual fastlane/gradle)
`eas build:inspect --platform ios --output /example/path --stage pre-build`

**Comment by irakli-g** [comment]
@wkozyra95 thanks for getting back to me. aws-exports file has my aws amplify configurations and was generated automatically by aws amplify. It contains ids and secrets that should not be shared by others thus it is automatically added to .gitignore.

I assume this is the reason why it can't locate aws-exports. I can remove it from .gitignore but might there be a better way for handling this?

**Comment by wkozyra95** [comment]
https://docs.expo.dev/build-reference/variables/

You can create secret with content of that file and restore it in [npm hook](https://docs.expo.dev/build-reference/how-tos/#eas-build-specific-npm-hooks) from env 
e.g. `echo "$SECRET_NAME" | base64 -d > ./app/aws-exports`

Also, note that anyone can extract those values from apk/ipa, so unless it's a public repo there is no harm in committing those files.

**Comment by irakli-g** [comment]
@wkozyra95 thanks.

My build finished successfully. I'm going to close this issue but I still get this 

```
Failed to read entitlementsUnexpected key "com.apple.developer.icloud-container-identifiers" while parsing <dict/>.
```
Error in fastlane. Is this something to worry about? Does the issue come from expo's side and shall I create a different issue for this? I've showed my apple settings but I can provide more details if this issue is from my side.

**Comment by wkozyra95** [comment]
It looks like the entitlements file is ignored because of the error, so icloud stuff will probably not work. Try adding `iCloudContainerEnvironment: Production` to the plugin config (next to appleTeamId)

**Comment by irakli-g** [comment]
Unfortunately, it was unsuccessful https://expo.dev/accounts/homos/projects/bilbbo/builds/66262ead-b993-4522-b2fa-b96cc1eb0cbd 

I need iCloud to support one of my app's core features.

**Comment by irakli-g** [comment]
@wkozyra95 hi. I've been keeping track of your PRs for this issue and they appear to be merged. Shall I update something on my end to try it out?

**Comment by dsokal** [comment]
@irakli-g The PRs are merged indeed, but we still need to publish `@expo/config-plugins` to npm and upgrade it in this repo.

**Comment by irakli-g** [comment]
@dsokal I see. Thanks for letting me know. How can I subscribe for those updates? Perhaps, it will be mentioned here before this issue is closed?

**Comment by dsokal** [comment]
Yes, the issue will be closed after upgrading `@expo/config-plugins`.

**Comment by wkozyra95** [comment]
@irakli-g fix was deployed yesterday
