### ISSUE TITLE
Can't build Android when using  applicationIdSuffix

### ISSUE THREAD

**Issue by harshit525** [expo/eas-cli#866]
### Summary

I have defined 3 build types in Android project debug, release and staging and using applicationIdSuffix for different product flavours.

eas-cli@36.0 was able to build this project on staging but after eas-cli@37.3 I get the following error when trying to build for staging.

` Error: "applicationIdSuffix" in app/build.gradle is not supported.`

### Managed or bare?

Bare

### Environment

 EAS CLI 0.41.1 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
      Yarn: 1.22.15 - ~/.yarn/bin/yarn
      npm: 8.0.0 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Utilities:
      Git: 2.31.1 - /usr/local/bin/git
    npmPackages:
      expo: ~42.0.1 => 42.0.4 
      expo-updates: ^0.8.5 => 0.8.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      eas-cli: 0.41.1
      expo-cli: 5.0.1
    Project workflow: generic

### Reproducible demo or steps to reproduce from a blank project

`eas build --profile staging`

**Comment by wkozyra95** [comment]
Unfortunately, we never supported that. In the past, it might have worked because we just took the first applicationId in the file to resolve which credentials should be used. 
If you want to have multiple flavors in the project you need to use `applicationId` to define it for every flavor
