### ISSUE TITLE
[iOS Build] Failing with workspace error

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [expo/eas-cli#873]
I'm trying to build the iOS app via EAS CLI, but I'm no getting the following error.

`[!] Please close any current Xcode sessions and use `dec112reactnative.xcworkspace` for this project from now on.
102
[!] An error occurred while processing the post-integrate hook of the Podfile.
103
104
undefined method `expo_patch_react_imports!' for #<Pod::Podfile:0x00007feae2c934a0>`

and at the bottom

`[stderr] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `6CC80D02CF384F6F8196D1F0` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
124
pod exited with non-zero code: 1`

Full output should be here: https://expo.dev/accounts/lightstalker89/projects/dec112-react-native/builds/ab1a4a64-635b-49d2-9e71-9fd821765f6f

Any idea why this is happening from one build to another?

**Comment by dsokal** [comment]
Please fill in the issue template.

**Comment by mariomurrent-softwaresolutions** [comment]
@dsokal Well, how should I fill in the stuff for reproducing the issue?
It just appeared without changing anything ...

**Comment by dsokal** [comment]
There are a few other fields in the issue template other than the repro steps. 
As for the repro steps, you could, for example, link a build that was successful and then another that failed.

Also, keep in mind the quote from the issue template:
```
If you leave out sections there is a high likelihood your issue will be closed. If you have a question, not a bug report, please post it on our forums instead.
```
