### ISSUE TITLE
eas build --auto-submit not work when --non-interactive is set

### ISSUE THREAD

**Issue by wwwenjie** [expo/eas-cli#875]
### Managed or bare?

bare

### Environment

  EAS CLI 0.42.4 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.3/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/local/bin/git
    npmPackages:
      expo: ~40.0.0 => 40.0.1 
      expo-updates: ~0.4.0 => 0.4.2 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: ~0.63.4 => 0.63.4 
      react-native-web: ~0.13.12 => 0.13.18 
    npmGlobalPackages:
      expo-cli: 4.8.1
    Project workflow: generic

### Error output

- Uploading to EAS Build (0 / 2.9 MB)
✔ Uploaded to EAS  Learn more: https://expo.fyi/eas-build-archive

🤖 Android build details: https://expo.dev/accounts/xxxxxxxx/builds/xxxxxxxx
🍎 iOS build details: https://expo.dev/accounts/xxxxxxxx/builds/xxxxxxxx

🤖 Android submission

Looking up credentials configuration for com.hodlnaut.mobile...
    Error: Google Service Account Keys cannot be set up in --non-interactive 
    mode.
error Command failed with exit code 1.

### Reproducible demo or steps to reproduce from a blank project

run eas build with `--auto-submit` and `--non-interactive`

**Comment by evenSosaAkido** [comment]
@wwwenjie I'm having the same issue.. did you closed because you solved somehow?

**Comment by wwwenjie** [comment]
> 

I can't remember a bit, but it seems that putting google-service-account.json into the codebase will automatically recognize it. You can take a look at this https://docs.expo.dev/submit/android/#submitting-your-app-using-ci

**Comment by KimGarza** [comment]
> > 
> 
> I can't remember a bit, but it seems that putting google-service-account.json into the codebase will automatically recognize it. You can take a look at this https://docs.expo.dev/submit/android/#submitting-your-app-using-ci

This link doesn't take you to any information regarding the Google Service Account. There is another link but it just talks about the steps in the Google Play Console. 
I am currently having this error using eas submit --platform android --latest --profile production --non-interactive
