### ISSUE TITLE
Missing app icon even though icon is set up properly in `app.config.ts`

### ISSUE THREAD

**Issue by garrett-gottlieb** [expo/eas-cli#877]
### Build/Submit details page URL

https://expo.dev/accounts/garrettg/projects/blogcast/submissions/6d3b36af-1619-4ac2-a7f0-a08b75c45930

### Summary

Using this icon, putting it as `icon: './images/icon.png'` in `app.config.ts` and confirming it is RGB with no alpha channel (photo also uploaded). I created the icon using the Figma template and followed the guide exactly at https://docs.expo.dev/guides/app-icons/. I've tried resaving with Photoshop after "flattening" the layer as well. Nothing seems to work. When debugging the app in the simulator, it shows the icon (and splash screen) properly.
![icon](https://user-images.githubusercontent.com/1219054/147425025-c383113b-36a1-4ed3-9897-9e67bbf8ff3a.png)
<img width="261" alt="Screen Shot 2021-12-26 at 8 18 12 PM" src="https://user-images.githubusercontent.com/1219054/147425079-3c432367-f7a0-46ea-897b-05f551b8d755.png">

### Managed or bare?

bare

### Environment

★ eas-cli@0.42.4 is now available, please upgrade.
Proceeding with outdated version

  EAS CLI 0.39.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 12.22.7 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react-native: 0.64.3 => 0.64.3
    npmGlobalPackages:
      eas-cli: 0.39.0
    Project workflow: generic

### Error output

[stderr] [!] Error uploading ipa file: 
[stderr]  [Transporter Error Output]: ERROR ITMS-90713: Missing Info.plist value. A value for the Info.plist key 'CFBundleIconName' is missing in the bundle 'com.blogcastapp'. Apps built with iOS 11 or later SDK must supply app icons in an asset catalog and must also provide a value for this Info.plist key. For more information see http://help.apple.com/xcode/mac/current/#/dev10510b1f7.
[stderr] [Transporter Error Output]: ERROR ITMS-90022: Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 10.0. To support older versions of iOS, the icon may be required in the bundle outside of an asset catalog. Make sure the Info.plist file includes appropriate entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_interface
[stderr] [Transporter Error Output]: ERROR ITMS-90704: Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/.
[stderr] \nERROR ITMS-90704: Missing App Icon. An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, or watchOS. Without this icon, apps cannot be submitted for review. For details, see https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/. entries referencing the file. See https://developer.apple.com/documentation/bundleresources/information_property_list/user_interface
[stderr] [Transporter Error Output]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
fastlane pilot failedfastlane exited with non-zero code: 1

### Reproducible demo or steps to reproduce from a blank project

`eas build --non-interactive --platform ios --auto-submit --clear-cache`

**Comment by garrett-gottlieb** [comment]
Upon further investigation, the `Images.xcassets > AppIcon` is empty. Should this completed by `eas-cli` for a bare Expo project or should it be done manually?

**Comment by dsokal** [comment]
Uh, sorry the docs are misleading. The part about EAS Build generating app icons is correct but it only applies to Expo managed projects (the ones without **android/** and **ios/** directories). If you want to set icons for a bare workflow project, you should do that manually (with Xcode).

**Comment by dass2808** [comment]
> Uh, sorry the docs are misleading (we'll fix them). The part about EAS Build generating app icons is correct but it only applies to Expo managed projects (the ones without **android/** and **ios/** directories). If you want to set icons for a bare workflow project, you should do that manually (with Xcode).

Is there a way to set the ios app icons without Xcode in windows pc for react native bare workflow?

**Comment by thisisadithk** [comment]
Run `expo prebuild --clean`. For me, it gave some errors installing pod files. If that's the case, then you need to manually resolve the issues there and run `pod install` in ios/PodFile. Once the pod files are successfully installed, run “expo prebuild”. After this take a build either through `./gradlew assembleRelease` or `eas build` and new build should have the updated app icon as well as splash screen.

**Comment by Dofamen** [comment]
Is there any way to set the ios app icons without Xcode on windows computer for react native bare workflow + expo?
