### ISSUE TITLE
EAS Build, Apple 403 detected - Access forbidden on Linking bundle identifier 

### ISSUE THREAD

**Issue by martink635** [expo/eas-cli#880]
### Summary

We did a successful build 2 days ago without any issues. From today on it seems we are getting 

```Network Timeout: 'AccessForbiddenError', 'Apple 403 detected - Access forbidden'. Retrying after 3 seconds (remaining: 3)```

on the `Linking bundle identifier` step.

This happens while running the `eas build --profile preview --platform ios` command.

Nothing was changed in the AppstoreConnect user settings, I still have access to everything (am an admin), so not sure what is going on or how to proceed with a build.

If you need more information let me know or if you could point me in the right direction.

### Managed or bare?

managed

### Environment

```
  EAS CLI 0.42.4 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.5.0/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: ^43.0.0 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 4.13.0
    Project workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

1. Run the `eas build --profile preview --platform ios` from the project
2. Watch it fail while trying to `Linking bundle identifier`

**Comment by chrisscott** [comment]
Seeing the same thing. `expo build:ios` returns the same error at the same spot. I've tried deleting the session cookie and the keychain password to start the login from scratch but it didn't help.

**Comment by martink635** [comment]
@chrisscott Make sure to accept the latest TOS on the Apple developer page, this was the issue in our case…

**Comment by dwinpaez** [comment]
I looked at my profile in https://developer.apple.com/ and that I accepted the changes. it worked for me.

**Comment by ChabaJosa** [comment]
Just accept the new terms and agreements on your app store connect or developer account and it will work just fine.

**Comment by navuyi** [comment]
Is there a way to find the agreement in order to accept it? There is no information on that on my Apple developer account.

**Comment by navuyi** [comment]
I am using Apple developer account which is part of a University package (or sth like that). All ToS agreements seem to be updated and I am still receiving mentioned error. Any clues?

**Comment by abanoubMaher96** [comment]
just open the developer account from any browser and agree for the new  terms

**Comment by Joao010** [comment]
> No new terms are visible when opening developer account. I am an admin now.

same thing

**Comment by navuyi** [comment]
I am using university/educational program. It is not possible to release apps in AppStore using that program. Can it be that it is also not possible to use EAS to create an ipa archive?

**Comment by navuyi** [comment]
I found out that only Account Holder can accept any legal agreements. Admin and developer cannot do that. Still there is the question if building apps is possible with University/educational program.

**Comment by Joao010** [comment]
> I found out that only Account Holder can accept any legal agreements. Admin and developer cannot do that. Still there is the question if building apps is possible with University/educational program.

I managed to resolve this issue after reporting this bug on the apple dev forum, and the apple support guy asked me to try again and it worked man_shrugging. Apparently it was some bug in their system and not with the expo itself, but thanks anyway.

Link: https://developer.apple.com/forums/

**Comment by mohamed-tebani** [comment]
> 
It's work 💯

**Comment by mohamed-tebani** [comment]
> @chrisscott Make sure to accept the latest TOS on the Apple developer page, this was the issue in our case…

It's work ! 💯

**Comment by saravanan-vjd** [comment]
> I found out that only Account Holder can accept any legal agreements. Admin and developer cannot do that. Still there is the question if building apps is possible with University/educational program.

Same for me. Let me know once you solved.

**Comment by mbordia-eightfold** [comment]
Hi !! 
Did anyone solved this issue ? I have already accepted the terms.

**Comment by NomanGul** [comment]
new link to accept apple terms of service: https://appstoreconnect.apple.com/agree_to_terms

**Comment by iramnavarrete** [comment]
I fixed this issue modifying user's permission in Admin account, user must have those permissions: 
![image](https://user-images.githubusercontent.com/32463351/212736259-690c5eeb-7c51-40d0-b6f7-e3e9efd548c1.png)
Especifically  "Acceso al certificado de distribución gestionado en la nube"

**Comment by noxterr** [comment]
Trying to accept terms for me is not a solution as accessing to [this](https://appstoreconnect.apple.com/agree_to_terms) page (https://appstoreconnect.apple.com/agree_to_terms) auto redirects me to the app control panel, implicitly stating that I have agreed on all ToS

**Comment by AEP20** [comment]
> https://appstoreconnect.apple.com/agree_to_terms

same, do you have any update ?

**Comment by MarchewkaMatthew** [comment]
Hi, is there anyone else facing this problem recently? Can I verify if TOS (Terms of Service) is accepted in my organization if I'm not an Account Holder?

**Comment by awesomedan93** [comment]
> Hi, is there anyone else facing this problem recently? Can I verify if TOS (Terms of Service) is accepted in my organization if I'm not an Account Holder?
> 
> EDIT: In my case, I had to ask for more permissions for my account: <img alt="MicrosoftTeams-image (13)" width="387" src="https://private-user-images.githubusercontent.com/56259093/261524855-3538e08e-fe05-48fd-b34b-a6f75d0e5264.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTk4ODEsIm5iZiI6MTcwNzMxOTU4MSwicGF0aCI6Ii81NjI1OTA5My8yNjE1MjQ4NTUtMzUzOGUwOGUtZmUwNS00OGZkLWIzNGItYTZmNzVkMGU1MjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE1MjYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMTFmY2IyNDU2ZDY2ZDYwNmU5NzI2NGU3YzJkMTBlMTY0OWViZTAzN2Q5OGJmZjMwZTQ1YzM0MzE3NWFjNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m3CasfDKSqI5-rfFWOGr0oReSZsfXUrVr2shbrHr5ZA"> In order to be able to enter this URL: https://developer.apple.com/account/resources/identifiers/bundleId/add

I have same question.
Did you find anything?

**Comment by zegenerative** [comment]
> > Hi, is there anyone else facing this problem recently? Can I verify if TOS (Terms of Service) is accepted in my organization if I'm not an Account Holder?
> > EDIT: In my case, I had to ask for more permissions for my account: <img alt="MicrosoftTeams-image (13)" width="387" src="https://private-user-images.githubusercontent.com/56259093/261524855-3538e08e-fe05-48fd-b34b-a6f75d0e5264.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMTk4ODEsIm5iZiI6MTcwNzMxOTU4MSwicGF0aCI6Ii81NjI1OTA5My8yNjE1MjQ4NTUtMzUzOGUwOGUtZmUwNS00OGZkLWIzNGItYTZmNzVkMGU1MjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE1MjYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMTFmY2IyNDU2ZDY2ZDYwNmU5NzI2NGU3YzJkMTBlMTY0OWViZTAzN2Q5OGJmZjMwZTQ1YzM0MzE3NWFjNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m3CasfDKSqI5-rfFWOGr0oReSZsfXUrVr2shbrHr5ZA"> In order to be able to enter this URL: https://developer.apple.com/account/resources/identifiers/bundleId/add
> 
> I have same question. When I access https://appstoreconnect.apple.com/agree_to_terms I am just redirected to homepage https://appstoreconnect.apple.com and I am not an account holder Did you find anything?

Same issue here and cannot find where to agree, also being redirected. This url https://developer.apple.com/account/resources/identifiers/bundleId/add results in the same error though. 

![Screenshot 2024-07-24 at 12 17 11](https://github.com/user-attachments/assets/5dc1cce0-67f9-4166-88f2-02c983faed98)

**Comment by atmanmax** [comment]
I am currently facing same issue even with App Manager role

upd: Build works with Admin role

**Comment by beedell-roke** [comment]
Due to [`facebook/react-native/issues/32931#issuecomment-2692279464`](https://github.com/facebook/react-native/issues/32931#issuecomment-2692279464), [^4] I'm forced to test on Darwin. Due to [`software-mansion/react-native-reanimated/issues/8432#issuecomment-3997465617`](https://github.com/software-mansion/react-native-reanimated/issues/8432#issuecomment-3997465617), I'd been attempting to generate a new IPA. [^1] Due to [`issues/1324#issuecomment-1232940722`](https://github.com/expo/eas-cli/issues/1324#issuecomment-1232940722), I need a new certificate, [^3] but encountered this problem:

[^4]: [`stackoverflow.com/revisions/79115607/2`](https://stackoverflow.com/revisions/79115607/2#content:~:text=%2E/gradlew%20assembleRelease:%20to%20create%20%2Eapk%2E)

[^3]: [`stackoverflow.com/revisions/19604713/1`](https://stackoverflow.com/revisions/19604713/1#content:~:text=The%20%2Ep12%20contains%20both%20the%20private%20and%20the%20public%20key)

<blockquote>

~~~Markdown
✔ Generate a new Apple Distribution Certificate? … yes
✖ Failed to create Apple distribution certificate
Failed to set up credentials.
Apple 403 detected - Access forbidden.
This request is forbidden for security reasons - You are not allowed to perform this operation.  Please check with one of your Team Admins, or, if you need further assistance, please contact Apple Developer Program Support. https://developer.apple.com/support
    Error: build command failed.
~~~

</blockquote>

[^1]: [`stackoverflow.com/revisions/55483190/1`](https://stackoverflow.com/revisions/55483190/1#content:~:text=Unless%20you%20have%20the%20private,they%20can%27t%20do%20rogue%20submissions%2E%29)

I've accepted all TOSs. Consequently, it might be because my Apple Developer Account is “pending”, due to incomplete enrolment, despite being a member of an organisation. [^2] I've asked, in Case 102836074621, and <del>I'll report back when it has been responded to.</del>

[^2]: [`reddit.com/r/iOSProgramming/comments/zkdgru/comment/o8l28dx`](https://www.reddit.com/r/iOSProgramming/comments/zkdgru/comment/o8l28dx/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
