### ISSUE TITLE
CombinedError: [GraphQL] "value" must contain less than or equal to 100 items

### ISSUE THREAD

**Issue by xD3CODER** [expo/eas-cli#883]
### Summary

When I try to create an update with eas udpdate command, if I have more than 100 assets, the upload fails due to a graphql error:

### Managed or bare?

bare

### Environment

  EAS CLI 0.42.4 environment info:
    System:
      OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
      Shell: 5.8 - /usr/bin/zsh
    Binaries:
      Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
      npm: 8.3.0 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: ^44.0.3 => 44.0.3 
      react: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.42.4
      expo-cli: 5.0.3
    Project workflow: generic

### Error output

```
✔ Built bundle!
✖ Failed to upload assets
    CombinedError: [GraphQL] "value" must contain less than or equal to 100 items
```

### Reproducible demo or steps to reproduce from a blank project

Create a project which produce more than 100 assets and run

`eas update -p android  --message=test`

**Comment by jkhales** [comment]
Hi @xD3CODER,  the 100 asset limit is intentional during our preview phase. Is this for a production app, or are you just testing out limits?

**Comment by xD3CODER** [comment]
> Hi @xD3CODER, the 100 asset limit is intentional during our preview phase. Is this for a production app, or are you just testing out limits?

Hi @jkhales 
Ok I didn't find anything about this in the doc or the "known issues" so I thought it wasn't intentional
It was just to test the functionality on an ongoing project, not in production

**Comment by jkhales** [comment]
> Hi @jkhales Ok I didn't find anything about this in the doc or the "known issues" so I thought it wasn't intentional It was just to test the functionality on an ongoing project, not in production

Thanks for reporting it, I'll look into adding it to the documentation!
