### ISSUE TITLE
`eas device:create` doesn't save device name

### ISSUE THREAD

**Issue by kbrandwijk** [expo/eas-cli#886]
### Summary

All registered devices have name 'Unknown'

### Managed or bare?

N/A

### Environment

```
EAS CLI 0.43.0 environment info:
    System:
      OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
      Shell: 5.0.17 - /bin/bash
    Binaries:
      Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v12.22.1/bin/yarn
      npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
    Utilities:
      Git: 2.25.1 - /usr/bin/git
    npmPackages:
      expo: ~44.0.0 => 44.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.43.0
      expo-cli: 5.0.3
    Project workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

- Register a device
- List devices

**Comment by dsokal** [comment]
Can you please elaborate? Are you registering the device by scanning the QR code and then installing the profile on your iPhone? If so, unfortunately, we can't read the device name. This is a well-known issue with Apple and we can't do too much with it.

**Comment by kbrandwijk** [comment]
Yes, I'm using the 'web flow'. Alternatively, if it can't be read (weird), would it be an idea to allow the user to set a name using the CLI (maybe directly when entering a UDID manually, and afterwards when someone uses the web flow)? I find myself looking at a list of UDID's xxxxx-xxxx (iPhone), which doesn't help much. It would also help when looking at the list of devices on the development portal, as they all appear like this:
![image](https://user-images.githubusercontent.com/852069/148110495-5357e7a0-8dfb-46a5-be56-02aee2ecbb58.png).

**Comment by chakafasano88** [comment]
I am having the same issue. I need my entire team's devices registered but it is difficult to know who is signed when I have no history of names.

**Comment by mgouault** [comment]
I am also encountering this issue, when adding a device with `eas device:create`(in our case it's iPhones) it does not seem to register any "name".
When using `eas device:list` it displays among the informations `Name             Unknown`.
Then when building for internal distribution `Select devices for the ad hoc build` it displays the devices by their "UDID" and "Class", which is not enough information to know which device belongs to who.
