### ISSUE TITLE
Enable passing in template for the `prebuild` command for eas builds

### ISSUE THREAD

**Issue by kbrandwijk** [expo/eas-cli#887]
`expo prebuild` allows a custom template. You can subsequently build this with `eas build` without issues. Therefore, it would be useful for managed workflow projects, to be able to specify the template directly in eas.json, instead of having to prebuild locally.

**Comment by byCedric** [comment]
It would be awesome if we can find something where we can add other parameters as well, like those `--skip-dependency-update` flags for edge cases.

**Comment by kbrandwijk** [comment]
Thanks for the scope creep ;) Kidding aside, if it makes sense to expose other `expo prebuild` command line options through env vars, let me know which ones.

I'm still debating whether a `prebuild` key under the eas.json build profile with a property for each command line option wouldn't be more straightforward too, but I'm starting out with env vars.

```json
{
   "prebuild" : {
       "template": "https://....",
       "skipDependencyUpdates: [ "....", "...."],
       "....": ....
   }
}
```

**Comment by wkozyra95** [comment]
Passing those values via envs is a better approach for now.

Adding anything to eas.json would require api changes, plus it would be a lot harder to deprecate it in the future, if we use envs it's relatively easy to deprecate and we don't need to change anything on the backend. We talked about supporting a generic way to fully customize any build steps, but it's not sth we are planing to work on in a near future

**Comment by EvanBacon** [comment]
@wkozyra95 On the contrary, env variables in an unversioned CLI (for now) don't have many mechanisms for safely deprecating. 
Given the points you raised, I would think that the env variable approach should be fine, but it very likely would be deprecated in the future. 

Since 'prebuild' is an entire step in a EAS Build, one would imagine that it should be modified directly.

**Comment by brentvatne** [comment]
@EvanBacon - you can detect if the env var is set and warn.

> Since 'prebuild' is an entire step in a EAS Build, one would imagine that it should be modified directly.

this is where we want to go at some point (every step should be completely customizable, or you should be able to define your own build steps entirely) but we're not prioritizing that yet

**Comment by brentvatne** [comment]
me @EvanBacon and @kbrandwijk discussed this on slack and i think a good compromise between `prebuild: { options }` and env vars is `prebuildCommand`, similar to `gradleCommand`. we'd pass in the platform to it by default.

**Comment by mackuba** [comment]
Hey, does this setting allow you to point it to a template with a customized `Podfile` for situations where you want to add/change something in the Podfile but still use managed mode? We have a native module which uses a private cocoapod as a dependency and you can't specify the git URL in the `.podspec`, only in the `Podfile`, so I was looking for a way to add a custom `pod 'xxx', git: ...` line to the `ios/Podfile`, and so far the only suggested ways I found was to either switch to bare mode, or modify the Podfile using regexps… Is this a better solution?

**Comment by kbrandwijk** [comment]
The recommended way is to work with config plugins, and not to fork and modify the template for a specific package, but the short answer is: yes, if you modify the template and pre-add that like to the Podfile, that should allow you to achieve the same result.

**Comment by mackuba** [comment]
Ok, thanks - and as for config plugins, it's mentioned here https://docs.expo.dev/guides/config-plugins/#modifying-the-ios-podfile that:

> The Podfile is a ruby file (application code), which means you cannot safely modify it from Expo config plugins, and should opt towards another approach, like Expo Autolinking hooks (citation needed).

However, the only other mention of "autolinking hooks" I can find anywhere is in this PR https://github.com/react-native-mapbox-gl/maps/pull/1388, where it's mentioned as something better that will be available in the future - are those hooks implemented now? Or is the only way to modify the Podfile with config plugins to use regexps, like it's currently done in that PR in mapbox-gl (`mergeContents`)?

**Comment by brentvatne** [comment]
@mackuba - we don't have these cocoapods autolinking hooks built in yet -- these would allow you to do things like hook into the `post_install` and `post_integrate` cocoapods hooks in a cleaner way. for now you'll need to do something like in the mapbox-gl plugin

**Comment by mackuba** [comment]
@brentvatne ok, thanks for info, we'll try to do it this way
