### ISSUE TITLE
Provide QR codes with EAS Updates

### ISSUE THREAD

**Issue by cemo** [expo/eas-cli#898]
Currently EAS updates are lacking generating QR codes and makes impossible to test them with dev clients.  

Please provide QR codes as EAS build command. I would like to simply open QR with my dev client as before.

**Comment by dsokal** [comment]
Could you please elaborate what's your use case? You can run `expo start` from any commit you need and you'll see a QR code which you can scan.

**Comment by cemo** [comment]
`eas build `command creates necessary QR codes. `eas update` is not creating. This is not now impossible to load a new channel with new branch.

Please see this thread:

https://twitter.com/CemoKoc/status/1479200155823976458

**Comment by kennethlynne** [comment]
I thought following this guide https://github.com/jonsamp/test-expo-dev-client-eas-update or using this serverless function could solve it, but I am met with a black screen on boot in the development client. 

`https://us-central1-exponentjs.cloudfunctions.net/generateQRCode/development-client?appScheme=<scheme>&url=https://exp.host/@<user>/<project>/index.exp?release-channel=<channel>`

**Comment by cemo** [comment]
I can confirm that that documented approach is working.

**Comment by kbrandwijk** [comment]
So, here's the issue: in the development client, you open a `channel` (that's also what's in the URL), but when running `eas update`, you publish to a _branch_. As you are free to link any channel to any branch, at the time of update, you can't simply show a QR code that points to a channel... It might be useful to have another CLI command to open a channel in the dev client (and by 'open', I mean: 'show the QR'), but as part of `eas update`, it doesn't seem possible.

**Comment by kennethlynne** [comment]
This worked well for us:
- Deploy to a branch on merges with GitHub actions for example `eas update --branch staging-1.x.x --message "v1.3.37"` + `eas channel:edit staging-1.x.x --branch staging-1.x.x` ("1.x.x" is to indicate that OTA updates are compatible with any matching major version)
- Generate a manifest URL, for example: `https://u.expo.dev/<eas-project-id>?channel-name=1.x.x` (project id found under the project overview on the Expo website)
- Note: This URL can now be loaded into your development client 
- Generate a deep link URL, for example: `exp+<expo-slug>://expo-development-client/?url=${{ MANIFEST_URL }}` (Expo slug is found in your app.json, manifest URL is from the previous step
- Use deep link from previous step to generate a QR code using for example api.qrserver:
`http://api.qrserver.com/v1/create-qr-code/?color=000000&bgcolor=FFFFFF&data=<deeplink>&qzone=1&margin=0&size=500x500&ecc=L'`

**Comment by cemo** [comment]
@kbrandwijk is this resolved?

**Comment by cemo** [comment]
@kbrandwijk would you please elaborate on this? If it is possible to show a url why it is not possible to display a QR for it?

**Comment by kbrandwijk** [comment]
I already explained in my initial reply. You publish to a _branch_, and in the app you open a _channel_. The approach that was shared above to generate a URL depends on this detail:
>  `eas channel:edit <channel-name> --branch <branch-name>` we use branch names that match channel
Without that, there's no way to know what channel you want to open if you run `eas update` to publish an update to a branch.

**Comment by cemo** [comment]
@kbrandwijk So there might a command to display a QR based on channel?
