### ISSUE TITLE
EAS Build Only Failing for profiles with `developmentClient: true`

### ISSUE THREAD

**Issue by Maker-Mark** [expo/eas-cli#899]
### Build/Submit details page URL

https://expo.dev/accounts/markcodelet/projects/codelet-app/builds/28299482-9dc1-4a7d-b669-b1c7176aaaf8

### Summary

I'm having a hard time making a development client for my app using EAS. The app builds fine for internal distribution and production, there just seems to be an issue when building the development client.

**Update**:
I ran the build without `expo-dev-client` and the `react-native-safe-area-contex`  and the build succeeded but the dev client downloaded would just crash.
Then I re-installed each actual dependency, and now it WORKS. This makes no sense, I ran in multiple times, with the  --clear-cache flag, so I have no idea what it was that was making this broken. I'd still like to leave this open in case there's an underlying bug. Here to helo.

### Managed or bare?

Managed

### Environment

  Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 11.6.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
      Watchman: 2021.11.08.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7486908
      Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.15 
      expo: ^44.0.0 => 44.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.43.0
    Expo Workflow: managed

### Error output

The output is best seen in context in the build URL. In short, it's happening in the "fastlane" section of the build where the app and there are a few warnings when it comes to linking expo dev client

### Reproducible demo or steps to reproduce from a blank project

I cannot reproduce this, other managed projects I have been making a dev build fine and I can't reproduce it on a bare project.

**Comment by dsokal** [comment]
The failure is not related to expo-dev-client.

The root cause can be found in the logs you provided.
```
Build failed: Fastlane build failed with unknown error. Please refer to the "Run fastlane" and "Xcode Logs" phases.
Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.
```

See how this message suggests that you should look at the Xcode Logs phase. I checked those logs and the actual error is really obvious. I'll leave looking for it to you (just for educational purposes).

**Comment by Maker-Mark** [comment]
> The failure is not related to expo-dev-client.
> 
> The root cause can be found in the logs you provided.
> 
> ```
> Build failed: Fastlane build failed with unknown error. Please refer to the "Run fastlane" and "Xcode Logs" phases.
> Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.
> ```
> 
> See how this message suggests that you should look at the Xcode Logs phase. I checked those logs and the actual error is really obvious. I'll leave looking for it to you (just for educational purposes).

Oh my god, you're kidding. I feel so smart 🙃. I was confused, I didn't think to download that stage logs since it failed in "Fast lane", I thought it was referring to the xcode logs in that section, not the "Xcode logs" phase. I actually thought it didn't get there due to the GUI showing success or failure. Is there a better way to highlight that next time for other users?
<img width="266" alt="Screen Shot 2022-01-11 at 11 51 12 AM" src="https://user-images.githubusercontent.com/40143016/148986025-f588964f-9d53-4fc8-ae6c-2d74b546ab1e.png">

I'm still confused why my issue was fixed when I just removed some packages and added them back. I already had the env variables defined. Generally, when they were not defined it showed the error in the "Fastlane" phase with the error that now I'm only seeing it in the phase below, that I assumed didn't run and have output.

Thanks for pointing this out.

**Comment by jamonholmgren** [comment]
For some reason I totally missed the Xcode logs section, since it was _below_ the message, and also didn't have a red :x: on it. Perhaps this could be more obvious?

<img width="381" alt="image" src="https://user-images.githubusercontent.com/1479215/163836728-340c9557-9c9c-4227-b2c5-874c079e4355.png">

**Comment by erquhart** [comment]
Yep, Xcode Logs containing errors, having no status symbol, and being after the Fail build step definitely was a clear signal that there was nothing to see there. Just that red X would have made all the difference.

**Comment by Maker-Mark** [comment]
> For some reason I totally missed the Xcode logs section, since it was _below_ the message, and also didn't have a red ❌ on it. Perhaps this could be more obvious?
> 
> <img alt="image" width="381" src="https://user-images.githubusercontent.com/1479215/163836728-340c9557-9c9c-4227-b2c5-874c079e4355.png">

Hey Jamon, good to see you around (huge RNR podcast fan :) Glad this issue was not one that just stumped me.
Can we get an issue to update the Xcode Logs error to be more obvious? This easily ate up many hours of my day digging into logs.

**Comment by paul-ridgway** [comment]
Agreed, tripped me up too

**Comment by Maker-Mark** [comment]
> Agreed, tripped me up too

Glad others are finding this. @dsokal Can we get an update if this can be communicated better? Thanks!

**Comment by CorinneKelly** [comment]
@Maker-Mark Where did you go to see that portal in your screenshot with all the steps and logs?

**Comment by paul-ridgway** [comment]
> @Maker-Mark Where did you go to see that portal in your screenshot with all the steps and logs?

 @CorinneKelly It's a bit unintuitive but it's the last pane on the page which stays collapsed by default

**Comment by CorinneKelly** [comment]
> > @Maker-Mark Where did you go to see that portal in your screenshot with all the steps and logs?
> 
> @CorinneKelly It's a bit unintuitive but on a given app build, it's the last pane on the page which stays collapsed by default

@paul-ridgway I'm not sure I understand your response. To clarify, I was asking where is the page with the "panes" you're referring to? Is it somewhere in the expo dashboard? Is there a web url that prints out that I'm not seeing? When I run an eas build I don't see those sections in the build details on my expo dashboard. I've tried running both `eas build -p ios` both with and without the `--local` flag.

**Comment by paul-ridgway** [comment]
@CorinneKelly EAS build should give you a link to monitor progress - it's that page eg:
![image](https://user-images.githubusercontent.com/1295064/170313740-066f4fa3-91ba-46ac-aeb3-b4db7e02e76d.png)

**Comment by dvirben** [comment]
I tried finding the probem in the logs file, couldn't. Any help will be welcomed
