### ISSUE TITLE
Allow uploading git-ignored files to EAS

### ISSUE THREAD

**Issue by dsokal** [expo/eas-cli#900]
It sometimes makes sense to upload git-ignored files to EAS. There should be a way to override .gitignore file rules.

See https://github.com/expo/eas-cli/issues/228#issuecomment-1006837799 for context.

**Comment by DrKylstein** [comment]
For some setups, it seems you can use a negated ('!' before it) pattern in .easignore to do this. In my case I have individual files that are specifically ignored and only a single .gitignore, I don't know if this would work with ignored directories or multiple .gitignore files. Hopefully this helps somebody!

**Comment by diegoconcha** [comment]
It would be awesome if you all could add an `.easincludes` file instead or in addition to the `.easignore` file discussed [here](https://github.com/expo/eas-cli/issues/228#issuecomment-1008717383). We only want to include the `aws-exports.js` instead of now having to have two ignore files we need to keep up-to-date.

**Comment by caioedut** [comment]
I need to include ignored google-services.json

**Comment by ShepSims** [comment]
Has anyone figured out how to get past the aws-exports and google-services.json needing to be gitignored?

adding the following to .easignore did not fix the eas:build issues for us
!aws-exports.js
!google-services.json

**Comment by VictorioMolina** [comment]
@ShepSims have u tried encoding the files with bash64, storing them as eas secrets, and running a package.json script (hook) for restoring the respective files?

I am about to handle this situation in a few days, and I feel that updating my eas secrets everytime the sensitive .gitignored files change is annoying…

**Comment by bombillazo** [comment]
Please please EAS maintainers! This feature is very valuable to streamline uploading files we already have in out repo but do not want to commit nor duplicate the ignore files!

**Comment by Jonak-Adipta-Kalita** [comment]
Please the maintainers of the repo, fix this issue.

**Comment by anadal-fundaciobit** [comment]
I too need fix this issue !!!!

**Comment by hbriese** [comment]
Adding the negation to `.easignore` worked for 
```
!google-services.secret.json
```

This works because my `.gitignore` looks like
```
**/*.secret.*
```

Had I ignored the file specifically then this would not work

**Comment by joaquinbian** [comment]
Hello, is there a way of including `.easignore` in github actions? I am using aws-amplify as well and my workflow fails because aws-exports is not found, I keep it ignore in `.gitignore ` file

**Comment by hanamurayuki** [comment]
After putting `.easignore` on the `root directory` of git repository, build starts working without error.
I haven't written `aws-exports.js` on the `.easignore`, but build works successfully.
So, I understand `.easignore` overrides all content of `.gitignore`.

**Comment by andy-HM** [comment]
I am running into the same thing.  @hanamurayuki did you have the `aws-exports.js` committed before you tried this?  

I have tried using `.easignore` and simply not including `aws-exports.js`.  I have also tried explicit using `!aws-exports.js` in the `.easignore` with no luck.

**Comment by JavanPoirier** [comment]
> After putting `.easignore` on the `root directory` of git repository, build starts working without error. I haven't written `!aws-exports.js` on the `.easignore` file, but build works successfully. So, I understand `.easignore` overrides all contents of `.gitignore`.

Thanks @hanamurayuki, placing in my monorepo root did the trick

`
├── apps
│   ├── expo
│   │   ├── .easignore <--- Does not work
│   ├── next
├── packages
│   ├── api
│   ├── app
│   │   ├── amplifyconfiguration.json
│   │   ├── .gitignore.json <-- includes amplifyconfiguration.json
│   ├── db
└── .easignore <--- Works (amplifyconfiguration.json not included)

My issue with git ignored files was a pain to sort out due to a few layers of masquerading issues.
1. Dev builds appear to include git ignored files, no issue with this file missing. 
2. Because I was doing EAS builds locally I didn't fully clue into to concept of "uploading to EAS". 
3. Tried to find a way to ensure assets were being included in EAS builds.
4. Went down a rabbit whole trying to figure out if metro was excluding assets in non-dev builds.

**Comment by MauriceArikoglu** [comment]
Can confirm this

> Adding the negation to `.easignore` worked for
> 
> ```
> !google-services.secret.json
> ```
> 
> This works because my `.gitignore` looks like
> 
> ```
> **/*.secret.*
> ```
> 
> Had I ignored the file specifically then this would not work

and this


> > After putting `.easignore` on the `root directory` of git repository, build starts working without error. I haven't written `!aws-exports.js` on the `.easignore` file, but build works successfully. So, I understand `.easignore` overrides all contents of `.gitignore`.
> 
> Thanks [@hanamurayuki](https://github.com/hanamurayuki), placing in my monorepo root did the trick
> 
> ` ├── apps │ ├── expo │ │ ├── .easignore <--- Does not work │ ├── next ├── packages │ ├── api │ ├── app │ │ ├── amplifyconfiguration.json │ │ ├── .gitignore.json <-- includes amplifyconfiguration.json │ ├── db └── .easignore <--- Works (amplifyconfiguration.json not included in git)
> 
> My issue with git ignored files was a pain to sort out due to a few layers of masquerading issues.
> 
>     1. Dev builds appear to include git ignored files, no issue with this file missing.
> 
>     2. Because I was doing EAS builds locally I didn't fully clue into to concept of "uploading to EAS".
> 
>     3. Tried to find a way to ensure assets were being included in EAS builds.
> 
>     4. Went down a rabbit whole trying to figure out if metro was excluding assets in non-dev builds.

to help.

We ended up placing the .easignore in the root, where it successfully overrode .gitignore

**Comment by Uanela** [comment]
> > After putting `.easignore` on the `root directory` of git repository, build starts working without error. I haven't written `!aws-exports.js` on the `.easignore` file, but build works successfully. So, I understand `.easignore` overrides all contents of `.gitignore`.
> 
> Thanks [@hanamurayuki](https://github.com/hanamurayuki), placing in my monorepo root did the trick
> 
> ` ├── apps │ ├── expo │ │ ├── .easignore <--- Does not work │ ├── next ├── packages │ ├── api │ ├── app │ │ ├── amplifyconfiguration.json │ │ ├── .gitignore.json <-- includes amplifyconfiguration.json │ ├── db └── .easignore <--- Works (amplifyconfiguration.json not included in git)
> 
> My issue with git ignored files was a pain to sort out due to a few layers of masquerading issues.
> 
> 1. Dev builds appear to include git ignored files, no issue with this file missing.
> 2. Because I was doing EAS builds locally I didn't fully clue into to concept of "uploading to EAS".
> 3. Tried to find a way to ensure assets were being included in EAS builds.
> 4. Went down a rabbit whole trying to figure out if metro was excluding assets in non-dev builds.

Yes on monorepo this gotta be in the root.
