### ISSUE TITLE
cannot specify npm version via eas.json

### ISSUE THREAD

**Issue by salzhrani** [expo/eas-cli#905]
### Summary

the [documentation](https://docs.expo.dev/build/eas-json/#configuring-your-build-tools) states that npm version can be configured via `eas.json` via `build.production.npm` but when `npm` is added to `build.production` I get the following error
```
Error: eas.json is not valid [ValidationError: "build.production.npm" is not allowed]
```
I had to specify a newer version of node to get the version of npm that I wanted.

### Managed or bare?

bare

### Environment

EAS CLI 0.44.1 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.0 - /usr/local/bin/npm
    Utilities:
      Git: 2.30.1 - /usr/bin/git
    npmGlobalPackages:
      eas-cli: 0.44.1
      expo-cli: 5.0.3
    Project workflow: generic

### Error output

Error: eas.json is not valid [ValidationError: "build.production.npm" is not allowed]

### Reproducible demo or steps to reproduce from a blank project

```json
{
  "build": {
    "production": {
      "releaseChannel": "production",
      "node": "16.13.0",
      "npm": "8.1.0"
    },
}
```

**Comment by dsokal** [comment]
Hi!
Thanks for pointing this out. This is a "bug" in docs rather than in EAS CLI. Currently, we don't support specifying a custom npm version. See https://docs.expo.dev/build-reference/eas-json/#options-common-to-both-platforms At the moment, if you want a newer npm version you should either bump the node version or use a pre-install hook to install the desired npm version - https://docs.expo.dev/build-reference/how-tos/#eas-build-specific-npm-hooks 

I'm leaving this issue open but changing the label to "enhancement".

**Comment by n0mer** [comment]
@dsokal is it possible to specify jdk version?

I'm getting similar error during "eas build --profile development --platform android": 

[stderr] Build file '/root/workingdir/build/android/app/build.gradle' line: 249
[stderr] * What went wrong:
[stderr] A problem occurred evaluating project ':app'.
[stderr] > java.lang.UnsupportedClassVersionError: com/google/firebase/perf/plugin/FirebasePerfPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[stderr] * Try:

**Comment by dsokal** [comment]
@n0mer FWIW you can choose between JDK 8 and 11 - https://docs.expo.dev/build-reference/infrastructure/

**Comment by n0mer** [comment]
@dsokal setting `latest` helped! Thank you

```
Creating new worker instance
Connecting to the worker
Sending job to worker
Using image "ubuntu-20.04-jdk-11-ndk-r21e" based on "ubuntu:focal-20210921"
Installed software:
- NDK 21.4.7075529
- Node.js 14.18.1
- Yarn 1.22.10
- Npm 6.14.8
- Java 11
```
