### ISSUE TITLE
Eas build failing after updating Apple certificates

### ISSUE THREAD

**Issue by HristoEftimov** [expo/eas-cli#909]
### Summary

Earlier I was able to build ios applications based on `expo builds` and `eas build`. Today I had to update my expired Apple certificates. I have updated them using `expo credentials:manager` and successfully created a build with `expo build` with the new certificates. Unfortunately, on `eas build` this is not possible anymore.

All credentials in the Expo Dashboard and `eas credentials` are valid and the correct ones.

When I run `eas build` it requires Apple account login. The first time the error was `✖ Failed to register bundle identifier com.appname.com`, the second time is `✖ Failed to fetch Apple distribution certificates Error: Apple 403 detected - Access forbidden.`. Why it's trying to fetch them from the Apple account? 

### Managed or bare?

managed

### Environment

```
  EAS CLI 0.44.1 environment info:
    System:
      OS: macOS 11.6
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.18.1 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 6.14.15 - /usr/local/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: 44.0.4 => 44.0.4 
      expo-cli: 5.0.3 => 5.0.3 
      expo-updates: 0.11.3 => 0.11.3 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.42.4
    Project workflow: managed
 ```

### Error output

`✖ Failed to fetch Apple distribution certificates`

### Reproducible demo or steps to reproduce from a blank project

```
{
  "cli": {
    "version": ">= 0.42.4"
  },
  "build": {
    "DEV": {
      "developmentClient": false,
      "distribution": "internal",
      "releaseChannel": "dev",
      "ios": {
        "simulator": false
      },
      "android": {
        "buildType": "app-bundle"
      },
    },
  }
  ```

**Comment by dsokal** [comment]
> The first time the error was ✖ Failed to register bundle identifier com.appname.com

Are you sure you didn't change the bundle identifier in app.json? Were there any other errors?

> the second time is ✖ Failed to fetch Apple distribution certificates Error: Apple 403 detected - Access forbidden.. Why it's trying to fetch them from the Apple account?

We fetch the certificates from your Apple account in order to check if the cert you're using is valid. That is, it's not expired.
It looks like it's either a transient error on the Apple side or you actually passed the wrong credentials.

If you're sure the credentials on EAS servers are now correct, you can try to answer "No" to the question "Do you want to sign in with Apple". With this answer, EAS CLI will not contact Apple servers.

**Comment by HristoEftimov** [comment]
@dsokal Thanks for the answer.

>Are you sure you didn't change the bundle identifier in app.json? Were there any other errors?

Yes, the bundle indefinite is fine. An to be honest it doesn't happen anymore.

> We fetch the certificates from your Apple account in order to check if the cert you're using is valid. That is, it's not expired.
It looks like it's either a transient error on the Apple side or you actually passed the wrong credentials.

My account has developer permissions and cannot fetch the certificates. 

>if you're sure the credentials on EAS servers are now correct, you can try to answer "No" to the question "Do you want to sign in with Apple". With this answer, EAS CLI will not contact Apple servers.

Yes, I am sure that the credentials are correct. I can see them on the Web dashboard. If I press "No", it ask me again because "No problem! 👌 If you select an action that requires those credentials we will ask you again about it."

Before renewing certificates it was fine and didn't fetch them from the Apple account. How can I avoid that?

**Comment by HristoEftimov** [comment]
```
eas build
✔ Select platform › iOS
✔ The "production" profile is missing in eas.json. Pick another profile: › dev
✔ Linked to project @project/project-name (​https://expo.dev/accounts/12313/projects/project-name​)
✔ Using remote iOS credentials (Expo server)

If you provide your Apple account credentials we will be able to generate all necessary build credentials and fully validate them.
This is optional, but without Apple account access you will need to provide all the values manually and we can only run minimal validation on them.
✔ Do you want to log in to your Apple account? … no
No problem! 👌 If you select an action that requires those credentials we will ask you again about it.

› Log in to your Apple Developer account to continue
✔ Apple ID: … email@gmail.com
› Restoring session /Users/username/.app-store/auth/email@gmail.com/cookie
› Session expired Local session
› Using password for email@gmail.com from your local Keychain
  Learn more: https://docs.expo.dev/distribution/security#keychain
✔ Logged in New session
✔ Select a Team › TeamName (TeamId)
✔ Select a Provider › ProviderName (ProviderId)
✔ Switched to provider: ProviderName (ProviderId)
✖ Failed to fetch Apple distribution certificates
Failed to set up credentials.
    Error: Apple 403 detected - Access forbidden.
    This request is forbidden for security reasons - You currently don't have access to this membership resource. Contact your team's Account Holder, TeamName App Store, or an Admin.
```

**Comment by HristoEftimov** [comment]
@dsokal, thanks for the support again!

I have just re-uploaded my credentials and now it works fine. Seems that something went wrong the first time, even the credentials were valid on the `eas credentials` output, I noticed that download credentials wasn't available and after re-uploading everything works fine.
