### ISSUE TITLE
Android .apk builds are failing

### ISSUE THREAD

**Issue by rafmrs** [expo/eas-cli#914]
### Build/Submit details page URL

https://expo.dev/accounts/intutor/projects/my-kid/builds/dcc1ef8b-36d8-4525-ba5c-baf26b2b86e8

### Summary

Seems like same problem as 13th of january still ocurring. JCenter seems to be down

![image](https://user-images.githubusercontent.com/44644902/149788023-e6d819b1-7bc2-48ea-9281-4a7a282aad05.png)

### Managed or bare?

Managed

### Environment

  EAS CLI 0.44.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: ^44.0.4 => 44.0.4 
      expo-dev-client: ~0.8.0 => 0.8.0 
      expo-updates: ~0.11.4 => 0.11.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.44.1
      expo-cli: 5.0.3
    Project workflow: managed

### Reproducible demo or steps to reproduce from a blank project

Running eas build for android as apk

**Comment by frederikocmr** [comment]
Same problem is happening here.

**Comment by rafmrs** [comment]
This seems to be fixed, thanks to whomever fixed it :D

**Comment by dsokal** [comment]
See https://github.com/expo/eas-cli/issues/916#issuecomment-1015233740
