### ISSUE TITLE
EAS build EPERM

### ISSUE THREAD

**Issue by htrappmaier** [expo/eas-cli#917]
### Build/Submit details page URL

https://expo.dev/accounts/htrappmaier/projects/flipflapp/builds/ec7f7ab8-1cb0-46c5-a8a5-b107f991cc69

### Summary

created a eas build for internal distribution with sdk 0.37 (both IOS & android) (see above [IOS] in details page URL), switched to 0.44.1 and run into the error shown in 'error output' (push notification - EPERM)
reason for switching to 0.44.1: IOS build ok but failed for android with error same like: https://github.com/expo/eas-cli/issues/914

### Managed or bare?

managed

### Environment

EAS CLI 0.44.1 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 7.15.0 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.33.0.
    npmPackages:
      expo: ^44.0.0 => 44.0.5
      expo-updates: ~0.11.4 => 0.11.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Project workflow: managed

### Error output

IOS: Push Notifications setup for <project>: <bundle/package>
    Error: EPERM: operation not permitted, rmdir
    'C:\Users\herma\AppData\Local\Temp\eas-cli-nodejs\069269de-045c-473b-b49c-913f2c182952-shallow-clone\.expo'
    Code: EPERM
- Compressing project files
ANDROID: Using Keystore from configuration: Build Credentials <credential> (default)
    Error: EPERM: operation not permitted, rmdir
    'C:\Users\herma\AppData\Local\Temp\eas-cli-nodejs\a00a7cbc-40bf-4e35-8200-604c4d8f0a1e-shallow-clone\.expo'
    Code: EPERM
- Compressing project files

### Reproducible demo or steps to reproduce from a blank project

sorry

**Comment by dsokal** [comment]
Hey, 
I think there are two issues that you encounter:
- First is related to the fact that jCenter (external Maven repository) was down. This caused your Android build to fail. See https://github.com/expo/eas-cli/issues/916#issuecomment-1015233740
- Second error is related to the permission issue on Windows. @wkozyra95 do you know what could be causing this?

**Comment by htrappmaier** [comment]
additional:
did everything I found to be sure that it's not a matter of user permission: NO ITS NOT!

**Comment by htrappmaier** [comment]
switched back to eas-cli v0.31.0 - it works! Oh man. Anyway, would like to use the latest version - thx 4 help.

**Comment by htrappmaier** [comment]
It turned out that either to accept a dirty git or the eas-cli version in the eas.json was the reason for the error.

**Comment by j-t-dev** [comment]
In the hopes it might help someone else as well. Thanks @htrappmaier 

I also had the same problem, after reinstalling every thing except windows itself I switched back to cli version 0.31.0 and deleted eas.json.
This prompted a dirty git message, committed it and everything worked fine.
Changed back to the @latest version (0.45.0) and got prompted:
```
eas-cli@>=0.34.0 no longer requires that you commit changes to Git before starting a build. Learn more: https://expo.fyi/eas-vcs-workflow
If you want to continue using the Git integration, you can opt in with cli.requireCommit in eas.json or with the following prompt.

√ Select your preferred Git integration » Require changes to be committed in Git (old default)
√ Updated eas.json
√ Can we commit these changes to git for you? » Yes
√ Commit message: ... Set cli.requireCommit to true in eas.json
√ Committed changes.
```

Opted for the not dirty route and everything went fine.

**Comment by wkozyra95** [comment]
forum post for context https://forums.expo.dev/t/eas-0-44-1-internal-build-error-eperm/60930/6

@j-t-dev This is works because enabling `requireCommit` is using a different packaging method, also you don't need to downgrade and upgrade, you can just add `cli: { requireCommit: true } ` in your eas.json
