### ISSUE TITLE
Unable to edit channel to update branch

### ISSUE THREAD

**Issue by kennethlynne** [expo/eas-cli#926]
### Summary

```
➜ : eas channel:edit              
✔ Linked to project @x/x (​https://expo.dev/accounts/x/projects/x​)
✔ Please enter the name of the channel to edit: … development
✔ What branch should it change to? … dev
    TypeError: Cannot read properties of null (reading 'id')
```

### Managed or bare?

managed

### Environment

EAS CLI 0.45.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
      Yarn: 1.22.4 - ~/.yarn/bin/yarn
      npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: 44.0.3 => 44.0.3 
      expo-dev-client: 0.7.2 => 0.7.2 
      expo-updates: 0.11.3 => 0.11.3 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.5 => 0.17.5 
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Project workflow: managed

### Error output

TypeError: Cannot read properties of null (reading 'id')

### Reproducible demo or steps to reproduce from a blank project

```
eas channel:create development
eas channel:edit

# try to change branch
```

**Comment by jkhales** [comment]
Hi @kennethlynne, thanks for writing in about this.

Would you mind confirming that you can repro this on a fresh project?

I can't seem to repro it:
<img width="1131" alt="Screen Shot 2022-01-21 at 10 22 30 AM" src="https://user-images.githubusercontent.com/1220444/150552740-207b479c-661f-4b3b-9969-6ca7bc573384.png">

**Comment by jkhales** [comment]
Hi @kennethlynne thanks for reporting this.

It seems like you are trying to point the channel at a branch that does not exist. I will put up a PR to make an informative error message, but in the meantime you can look to see what branches are available with `eas branch:list`
