### ISSUE TITLE
Android build fails after updating packages to expo suggested versions 

### ISSUE THREAD

**Issue by TomasSestak** [expo/eas-cli#927]
### Build/Submit details page URL

https://expo.dev/accounts/yolk/projects/orbi-app/builds/05136261-7824-4a4f-b044-4f8773911e3b

### Summary

Hello,

thank for your awesome work, my eas build is failing with the new packages, when I revert it works just fine (https://expo.dev/accounts/yolk/projects/orbi-app/builds/d6e5b50a-e382-4f69-aea5-32912884f390)

-		"expo-constants": "~13.0.0",
+		"expo-constants": "~13.0.1",

-		"expo-file-system": "~13.1.0",
+		"expo-file-system": "~13.2.1",

-		"expo-updates": "~0.11.4",
+		"expo-updates": "~0.11.5",

### Managed or bare?

Bare

### Environment

  EAS CLI 0.45.1 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
      npm: 8.1.4 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: ^44.0.5 => 44.0.5 
      expo-dev-client: ~0.8.0 => 0.8.0 
      expo-updates: ~0.11.5 => 0.11.5 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1
    Project workflow: generic

### Reproducible demo or steps to reproduce from a blank project

.

**Comment by wkozyra95** [comment]
you are using packages that require different versions of kotlin which is not supported, either:
- update all expo packages with `expo install`
- set globally one version of kotlin in the  build gradle `project.ext.kotlinVersion = "1.6.10"`

**Comment by TomasSestak** [comment]
It was because of expo-file-system, after your comment and i ran expo install and it dowgraded it so there mustve been some change and then build was OK. Thanks.
