### ISSUE TITLE
App build is failing on monorepo setup

### ISSUE THREAD

**Issue by nnieto** [expo/eas-cli#931]
### Build/Submit details page URL

https://expo.dev/accounts/yenbekbay/projects/alka-tabs/builds/72297e37-e108-459c-b9b7-9a45fdff156d

### Summary

I'm trying to build the app for both platforms but I get the same error in all of them, tried to `expo run:ios` and `expo run:android` and the build still fails, also tried to run the eas build process locally and got the same result as in the cloud, the dependencies are well installed because it detects that is a monorepo and runs the `yarn install` command from the root folder.

I saw that is trying like compile a typescript file on the bundling process and the unexpected token error is thrown.

Thanks in advance for your help!

### Managed or bare?

Managed

### Environment

Expo CLI 5.0.3 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
      Yarn: 1.18.0 - ~/.nvm/versions/node/v16.10.0/bin/yarn
      npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
      Watchman: 2021.12.13.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
      Android SDK:
        API Levels: 23, 26, 27, 28, 29, 30, 31
        Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
        System Images: android-31 | Google APIs ARM 64 v8a
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7621141
      Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
    npmPackages:
      expo: 44.0.5 => 44.0.5 
      react-native: 0.64.3 => 0.64.3 
    npmGlobalPackages:
      eas-cli: 0.45.0
      expo-cli: 5.0.3
    Expo Workflow: managed

### Error output

> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
Welcome to Metro!
Fast - Scalable - Integrated
[stderr] error ../../@universal/util/sorted-collections.ts: Unexpected token: name (readonly) in file ../../@universal/util/sorted-collections.ts at 168:18.
Error: Unexpected token: name (readonly) in file ../../@universal/util/sorted-collections.ts at 168:18
    at /root/workingdir/build/node_modules/metro-transform-worker/src/index.js:279:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/root/workingdir/build/node_modules/metro-transform-worker/src/index.js:146:24)
    at _next (/root/workingdir/build/node_modules/metro-transform-worker/src/index.js:168:9)
    at /root/workingdir/build/node_modules/metro-transform-worker/src/index.js:175:7
    at new Promise (<anonymous>)
    at /root/workingdir/build/node_modules/metro-transform-worker/src/index.js:164:12
    at minifyCode (/root/workingdir/build/node_modules/metro-transform-worker/src/index.js:289:17)
    at Object.<anonymous> (/root/workingdir/build/node_modules/metro-transform-worker/src/index.js:569:40)
info Run CLI with --verbose flag for more details.
> Task :app:bundleReleaseJsAndAssets FAILED
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:bundleReleaseJsAndAssets'.
[stderr] > Process 'command 'node'' finished with non-zero exit value 1
[stderr] * Try:
[stderr] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[stderr] * Get more help at https://help.gradle.org
[stderr] BUILD FAILED in 5m 41s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
1 actionable task: 1 executed
Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.

### Reproducible demo or steps to reproduce from a blank project

I have a very large monorepo, I followed the steps on this repo https://github.com/byCedric/eas-monorepo-example, I'm not sure how to put a reproducible demo right now. I'll try to do it ASAP.

**Comment by wkozyra95** [comment]
check this guide https://docs.expo.dev/guides/monorepos/

when you are importing sth from other package it should be `@universal/util/sorted-collections` and not `../../@universal/util/sorted-collections`. (I'm guessing that `@universal/util` is your package in monorepo)

**Comment by nnieto** [comment]
@wkozyra95 Thanks for your response, we checked and linked the missing packages.
