### ISSUE TITLE
Build throws incorrect warning when deps not installed locally

### ISSUE THREAD

**Issue by kbrandwijk** [expo/eas-cli#935]
### Summary

If I clone a repo, but don't install the dependencies, when I try to run `eas build`, it warns me:

```
✖ EAS Build does not officially support building managed project with Expo SDK < 41. Do you want to proceed? … yes
```

### Managed or bare?

managed

### Environment

Latest eas-cli

### Reproducible demo or steps to reproduce from a blank project

- Clone a repo
- Run a build

**Comment by dsokal** [comment]
I think we could check if `node_modules` exists and if it doesn't display a prompt asking if the user wants to run `npm install`/`yarn install` for them. We need to make sure it works in monorepos.

**Comment by kbrandwijk** [comment]
@dsokal For this specific check, would checking for the `expo` dependency version number in package.json not be easier? After all, the build works perfectly fine without being 'forced' to install my dependencies. I wouldn't want to create that overhead/delay just for the sake of that validation.

**Comment by dsokal** [comment]
If there's a reliable way of determining what version of `expo` would be installed then I'm okay with that. Keep in mind that `*` is a valid version in `package.json` :) Also, people don't need to have a lock file.

**Comment by kbrandwijk** [comment]
> If there's a reliable way of determining what version of `expo` would be installed then I'm okay with that. Keep in mind that `*` is a valid version in `package.json` :) Also, people don't need to have a lock file. I'm afraid the implementation would become really complicated.

Theoretically, you are right. However, for this specific SDK < 41 warning let's not overcomplicate things. This is one that I'd be happy to just make a best guess on based on what's in package.json. `*` means latest version, so that wouldn't be an issue, lockfile can't resolve to a different major version either, we're really only talking about those cases where the `expo` dependency in `package.json` says something old. That check would be 99.999% accurate, and still much better than a `yarn install` being the only way to stop the warning.

**Comment by dsokal** [comment]
Sounds good.
