### ISSUE TITLE
android crash on camera launch

### ISSUE THREAD

**Issue by htrappmaier** [expo/eas-cli#936]
### Build/Submit details page URL

https://expo.dev/accounts/htrappmaier/projects/flipflapp/builds/af7e969a-662c-4e9b-990f-3ee82b3b129a

### Summary

App crashes only with (internal) android build (not with expo, not with standalone internal ios build)
Permission request before launching the comp with the camera 
   => const { status } = await Camera.requestCameraPermissionsAsync(); resp.
   => const { status } = await Camera.requestMicrophonePermissionsAsync();
         if (status == 'granted') navigation.navigate(' .....

Also tried it within useEffect of the comp - no difference

App.json (extract)
   ...
    "android": {
      "googleServicesFile": "./google-services.json",
      "adaptiveIcon": {
        "foregroundImage": "./src/assets/<name>",
        "backgroundColor": "#FFFFFF"
      },
      "package": <name>,
      "versionCode": 12,
      "softwareKeyboardLayoutMode": "pan",
      "permissions": ["CAMERA", "RECORD_AUDIO", "NOTIFICATION", "WRITE_SETTINGS", "VIBRATE", "READ_PHONE_STATE",
        "READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE", "ACCESS_FINE_LOCATION", "ACCESS_BACKGROUND_LOCATION"],
      "useNextNotificationsApi": true      
    },
  ...
Also tried it without "permissions" at all - no difference.

### Managed or bare?

managed

### Environment

EAS CLI 0.45.1 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.33.0.
    npmPackages:
      expo: ^44.0.0 => 44.0.5
      expo-updates: ~0.11.4 => 0.11.4
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Project workflow: managed

  Expo CLI 5.0.3 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
      Watchman: 20200730.120504.0 - C:\Users\herma\AppData\Local\watchman\watchman.EXE
    IDEs:
      Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7621141
    npmPackages:
      @expo/metro-config: ^0.2.8 => 0.2.8
      expo: ^44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Error output

sentry result:
##### NullPointerException

Attempt to invoke interface method 'expo.modules.interfaces.barcodescanner.BarCodeScannerInterface expo.modules.interfaces.barcodescanner.BarCodeScannerProviderInterface.createBarCodeDetectorWithContext(android.content.Context)' on a null object reference

Important to notice: I do NOT use the BarCodeScanner

**Comment by wkozyra95** [comment]
> App crashes only with (internal) android build (not with expo, not with standalone internal ios build)

- whether it's an internal build or not it should not affect the build process, more important here is if it's release or debug(dev client) build (from logs I see it's release)
- `expo build` is using specific prebuild native code, eas is using exactly what's in your package.json and lockfile, make sure you have a compatible version of expo packages installed (using `expo install` instead of `npm/yarn` to add packages)
- you can check this troubleshooting guide https://docs.expo.dev/build-reference/troubleshooting/

It does not look like eas specific problem, if you are using the correct versions of the packages and this is still happening, please open an issue in https://github.com/expo/expo and provide a reproducible example.

**Comment by htrappmaier** [comment]
The app doesn't crash using expo build and additionally only crashes on android.
Installing expo-barcodescanner and expo-facedetector solved the problem.  (and yes, I always use expo install). As mentioned above, the app doesn't use the barcode scanner and the face detector. Nevertheless, you may be right, that it's a expo and not an eas issue (even it only appears with eas build)
