### ISSUE TITLE
eas submit -p ios - Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by norenz92** [expo/eas-cli#945]
### Summary

When running `eas submit -p ios` I get the following

`✔ Linked to project [HIDDEN] (​https://expo.dev/accounts/[HIDDEN]​)

Ensuring your app exists on App Store Connect. This step can be skipped by providing ascAppId in the submit profile. Learn more: https://expo.fyi/asc-app-id

› Log in to your Apple Developer account to continue
√ Apple ID: ... [HIDDEN]
› Restoring session C:\Users\norenz\.app-store\auth\[HIDDEN]\cookie
√ Select a Team » [HIDDEN]
› Provider [HIDDEN] ([HIDDEN])
√ Logged in Local session

Cannot read property 'attributes' of undefined
    Error: Submission failed`

This might be due to me changing apple id email at Apple site? Same account, just changed email to sign in with.
`eas build --platform ios` works fine.

### Managed or bare?

Managed

### Environment

`EAS CLI 0.46.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.22.0.
    npmPackages:
      expo: ^43.0.0 => 43.0.5
      expo-updates: ~0.10.15 => 0.10.15
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Project workflow: managed`

### Reproducible demo or steps to reproduce from a blank project

Not sure

**Comment by norenz92** [comment]
Running `eas submit -p ios --latest --verbose` seems to solve the problem

**Comment by EvanBacon** [comment]
Ok, perhaps some weird transient error with the Apple API.

**Comment by sebastianrueckerai** [comment]
I have the same issue 

> Cannot read properties of undefined (reading 'attributes')
> Submission failed

Only for me `eas submit -p ios --latest --verbose` does not solve it!

**Comment by SamuelWallisBauer** [comment]
Ditto

**Comment by sebastianrueckerai** [comment]
For me this was solved by logging in via apiKey. This needed to be enabled on apple connect and then ascApiKeyPath, ascApiKeyIssuerId and ascApiKeyId needed to be added to eas.json.

**Comment by Shashank-Ganta** [comment]
ditto
