### ISSUE TITLE
Firebase Authentication deeplink works when built with expo but not with eas

### ISSUE THREAD

**Issue by pdandradeb** [expo/eas-cli#947]
### Build/Submit details page URL

https://expo.dev/accounts/appjusto/projects/appjusto-deeplink

### Summary

I'm using Firebase Authentication with passwordless email provider but the App can't fetch the deeplink when it's built with `eas`.

Expected: after clicking on the link sent by Firebase the app should open and show the deeplink regardless if it was built with `expo` or ` eas`.

What's actually happening: the flow only works when building it with `expo build`.

### Managed or bare?

managed

### Environment

  EAS CLI 0.45.1 environment info:
    System:
      OS: macOS 11.5.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.17.2 - ~/.nvm/versions/node/v14.17.2/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.2/bin/yarn
      npm: 6.14.13 - ~/.nvm/versions/node/v14.17.2/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: ~44.0.0 => 44.0.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    npmGlobalPackages:
      eas-cli: 0.45.1
      expo-cli: 5.0.3
    Project workflow: managed

### Reproducible demo or steps to reproduce from a blank project

The code is minimal. Basically I'm doing three things:

- configuring the `intentFilters`
- authenticating with `sendSignInLinkToEmail`
- showing the deeplink with `Linking.useURL()`

I've created a project for this app on Firebase and I'm more than happy to share the apiKey and the rest of configuration to make it easier to reproduce the issue.

### Repo

https://github.com/appjusto/appjusto-deeplink/

### Instructions

1. clone repo
2. create a `firebase.ts` file on the root and add:

```
export const firebaseConfig = {
  apiKey: "",
  authDomain: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: ""
};
```

3. expo publish
4. yarn expo-build
5. yarn eas-build

Compare the versions.

I've also added the AndroidManifest.xml from both versions [here](https://github.com/appjusto/appjusto-deeplink/tree/main/assets/manifests)

**Comment by ilyatsykunov** [comment]
I am experiencing the same issue. It was first reported in August 2021 here https://github.com/expo/eas-cli/issues/558 , almost a year ago. Is there really no solution to it still?

**Comment by pdandradeb** [comment]
hei @ilyatsykunov, I don't think so. It's pretty clear to me that the output of `eas build` is not the same of `expo build` and that's pretty much broke the e-mail authentication flow with deeplink. As `expo build` will be dismissed by the end of the year, I've just moved to Phone Authentication to avoid the problem altogether.

**Comment by ilyatsykunov** [comment]
@pdandradeb Did you have to strip all deep link functionality from your app then? This workaround https://github.com/expo/expo-cli/issues/4180 seems to have helped many people, but I am still unable to get my firebase dynamic links to direct to a specific page in the app.

**Comment by pdandradeb** [comment]
No, the other deeplinks are working correctly. In fact that was not the only problem we faced with this deeplink. People using other browsers than Chrome (Firefox) simply can't complete the login flow. I'd recommend to move awai from e-mail authentication if that's an option for you.

**Comment by aberezhk** [comment]
@ilyatsykunov , were you able to find a fix for this issue? I have the same problem with firebase dynamic links and eas build. At the same time "normal" (aka com.myapp://abc?param=value) deep links seem to work with eas as before with expo build.
