### ISSUE TITLE
Cannot set properties of undefined (setting 'DevelopmentTeam')

### ISSUE THREAD

**Issue by KROSF** [expo/eas-cli#948]
### Build/Submit details page URL

https://expo.dev/accounts/krosf/projects/ownda/builds/f09f1603-5eab-45ce-9891-bccdb3a91e6c

### Summary

I not able to build [variants](https://docs.expo.dev/build-reference/variants/) off the app, on a bare workflow, the android flow works great but ios

I know the app does not contain bugs and was working before adding the variant flow

### Managed or bare?

bare

### Environment

  EAS CLI 0.46.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.2 - /usr/local/bin/node
      Yarn: 1.22.17 - /usr/local/bin/yarn
      npm: 8.1.2 - /usr/local/bin/npm
    Utilities:
      Git: 2.35.0 - /usr/local/bin/git
    npmPackages:
      expo: 44.0.5 => 44.0.5 
      react: 17.0.2 => 17.0.2 
      react-native: 0.67.1 => 0.67.1
    Project workflow: generic

### Error output

![image](https://user-images.githubusercontent.com/24454660/151616829-9a36d289-bbc3-41bc-a5f3-222845dfda33.png)

### Reproducible demo or steps to reproduce from a blank project

https://github.com/muchobien/ownda-app/tree/feat/eas-variants

**Comment by wkozyra95** [comment]
attributes field in PBXProject has a bit different structure than we expect, can you try adding bellow changes in you pbxproj file?

If your main project is different than the reproducible example you linked then those ids will be different, but you can find them few lines below in the PBXProj definition.

```diff
diff --git a/ios/ownda.xcodeproj/project.pbxproj b/ios/ownda.xcodeproj/project.pbxproj
index aed96a3..20bbb3b 100644
--- a/ios/ownda.xcodeproj/project.pbxproj
+++ b/ios/ownda.xcodeproj/project.pbxproj
@@ -263,6 +263,8 @@
                                        13B07F861A680F5B00A75B9A = {
                                                LastSwiftMigration = 1120;
                                        };
+                                       4906934427A461BA0056D776 = {};
+                                       4906935827A466920056D776 = {};
                                };
                        };
                        buildConfigurationList = 83CBB9FA1A601CBA00E9B192 /* Build configuration list for PBXProject "ownda" */;
```

**Comment by KROSF** [comment]
@wkozyra95 it works great

**Comment by wkozyra95** [comment]
this looks like the same issue(hard to say for sure without pbxproj file), the same workaround as I suggested above will work, but ids will be different(it will be obvious after you find `PBXProject` section in pbxproj file)

PR linked above was not deployed yet(after it is that workaround should not be necessary)

**Comment by evenSosaAkido** [comment]
Thanks @wkozyra95 , found them.. just in case someone else sees this.. the ids can be found a few lines below where the proposed change is pointing. in the `targets` key

**Comment by miwialex** [comment]
it looks like this issue is closed, but I just ran into this issue with my build here. https://expo.dev/accounts/nurse-disrupted/projects/nurse-disrupted-kiosk/builds/270f06f8-ef4a-48b9-8be6-f7d534140e42. would this still be the same issue?

**Comment by wkozyra95** [comment]
@miwialex we didn't update that part for a while, so fix was never deployed, if you are hitting the same issue it should work now

**Comment by miwialex** [comment]
@wkozyra95 awesome, thanks for the update!
