### ISSUE TITLE
Build failing on INSTALL_PODS step

### ISSUE THREAD

**Issue by whatnottodo** [expo/eas-cli#950]
### Summary

while building iOS app locally build fails at INSTALL_PODS with output

I know this is probably an environmental error but I'm really having a rough time moving past it. 
eas local build seems to be using an outdated version of pods; the version I expect it to use is from /Users/user/.rbenv/shims/pod: 1.11.2. 

I'd be utterly grateful to anyone that could lend help.

### Managed or bare?

Managed

### Environment

  EAS CLI 0.46.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
      npm: 7.18.1 - ~/.nvm/versions/node/v14.15.4/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.15 
      expo: ^44.0.0 => 44.0.4 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.46.0
      expo-cli: 5.0.3
    Project workflow: managed

### Error output

**[INSTALL_PODS] Using Expo modules
[INSTALL_PODS] Auto-linking React Native modules for target `app`: RNCAsyncStorage, RNGestureHandler, RNReanimated, and RNSVG
[INSTALL_PODS] 
[INSTALL_PODS] [!] Invalid `Podfile` file: undefined method `post_integrate' for #<Pod::Podfile:0x00007f9b26111340>
[INSTALL_PODS] Did you mean?  post_install.
[INSTALL_PODS] 
[INSTALL_PODS]  #  from /private/var/folders/6q/g_t0qbk94wl6bxqjswtqdhfm0000gn/T/eas-build-local-nodejs/8a5fc9fe-1474-4d34-a9c0-b58161ecca55/build/frontend/ios/Podfile:41
[INSTALL_PODS]  #  -------------------------------------------
[INSTALL_PODS]  #  
[INSTALL_PODS]  >    post_integrate do |installer|
[INSTALL_PODS]  #      begin
[INSTALL_PODS]  #  -------------------------------------------
[INSTALL_PODS] 
Error: pod exited with non-zero code: 1**

### Reproducible demo or steps to reproduce from a blank project

eas build --platform ios --local

**Comment by artalat** [comment]
Running into this issue myself, how did you solve it?

**Comment by terrierscript** [comment]
Is this issue resolved? I got same error.

**Comment by whatnottodo** [comment]
@terrierscript For me this was an issue with nvm, worked around by disableing nvm and installing node with brew

**Comment by terrierscript** [comment]
I try update `sudo gem update cocoapod` and this error resolved.
(I feel eas-cli is very hard and need more documentation like pre-required gem version.)

**Comment by gallivangames** [comment]
i tried that but i get `error installing cocoapods-core: ERROR: Failed to build gem native extension`
