### ISSUE TITLE
Gateway timeout when uploading credentials

### ISSUE THREAD

**Issue by phatmann** [expo/eas-cli#951]
When I try to upload iOS credentials to EAS using eas credentials, I get this error:

```
[Network] Gateway Time-out
```

When I use `eas build` to make an ad hoc iOS build, I get the same error right after the profile is updated; i.e. the build is failing trying to upload the profile. This prevents me from making a build using remote credentials.

When I try to upload credentials using the Credentials web page, I get a “Load failed” error, which I am guessing is the same issue.

This has been happening for at least a week, so this is not an intermittent failure.

### Do you understand that any feature requests opened in this repository will be closed?

Yes

**Comment by wkozyra95** [comment]
We have a global request timeout on our server set to about 9 seconds, so if uploading takes longer we can't really do much about it, it looks like it's bottlenecked by your internet connection.

I don't expect it to be different, but did you try to upload credentials via website?

**Comment by phatmann** [comment]
It all works now. 

Tony
