### ISSUE TITLE
Android sets release channel to default if releaseChannel has a dot in the value.

### ISSUE THREAD

**Issue by GollyJer** [expo/eas-cli#955]
### Summary

When the release channel has a dot in the name Android builds do not use it and instead set the channel to `default`.

### Managed or bare?

eas build

### Environment

npmPackages:
      expo: ^44.0.0 => 44.0.5
      expo-dev-client: ~0.8.2 => 0.8.2
      expo-updates: ~0.11.5 => 0.11.5
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Project workflow: managed

### Reproducible demo or steps to reproduce from a blank project

This is when building via `eas build` and pushing OTA updates via `expo publish`.

To test is pretty easy. 
Create a build with the release channel set to `1.0`. 
It will not take OTAs published to release channel `1.0`. But, push an OTA to `default` and it will be picked up.

Create a build with release channel set to `1_0`. 
It will take OTAs published to release channel `1_0`.

The behavior was not this way when we were using expo-cli for builds and, I _think_ things were working for a while in eas-cli. But now there is definitely an issue.

note: iOS builds work as expected.

**Comment by brentvatne** [comment]
@GollyJer - to be totally clear, you are using `expo publish` ("Classic updates") and not EAS Update, right?

**Comment by GollyJer** [comment]
@brentvatne Yes. That is correct. 
But, to be more direct. `expo publish` is **not** the problem.

### `eas build` choking on the dot in the `releaseChannel` name is the issue.

**Comment by GollyJer** [comment]
PS - The way I discovered the issue was to pull in this and display it on a screen in the builds.

`import { releaseChannel } from 'expo-updates';`

**Comment by jkhales** [comment]
Thanks for reporting this @GollyJer! I'll take a look!

**Comment by wkozyra95** [comment]
@GollyJer it should work now

**Comment by GollyJer** [comment]
💪
