### ISSUE TITLE
Force npm instead of yarn during prebuild phase of eas build?

### ISSUE THREAD

**Issue by Joshuapwilley** [expo/eas-cli#957]
Is there a way to force the prebuild stage of `eas build` to use the "--npm" option to apply this workaround?

Without "--npm":
![image](https://user-images.githubusercontent.com/20932326/152423461-34baa17b-a83f-4996-99e6-3b020a3ead0f.png)

With "--npm":
![image](https://user-images.githubusercontent.com/20932326/152424005-cda68342-dad0-425d-9edd-c1d19bb750ef.png)

I realize I run `expo prebuild` in these examples but I think it illustrates the issue cleanly.

My actual issue is this (I want to be able to pass --npm here, I guess?):
`eas build --profile my-profile -p android --local --clear-cache`
![image](https://user-images.githubusercontent.com/20932326/152424395-717c9555-3c49-45eb-a441-13b07ea91c78.png)

I fully admit that I may be missing something here so if I am, please point me in the direction of it!

**Comment by Joshuapwilley** [comment]
Disregard!
You are able to do this via `eas.json`.

For example:

```
{
  "build": {
    "base-local": {
      "node": "12.22.5",
      "developmentClient": true,
      "prebuildCommand": "prebuild --npm",
      ...
    }
  }
}
```

**Comment by cristobalmackenzie** [comment]
Hi @Joshuapwilley , ran into the same issue today. May I ask where you found this documented? Thanks!

**Comment by EmePin** [comment]
isn't there a way for eas build to run npm i --force? or npm config set legacy-peer-deps true or npm install --save --legacy-peer-deps?

**Comment by osamwelian3** [comment]
@EmePin Did you find a way with customizing the npm command? Am stuck and that is exactly what I need to do

**Comment by VolkerLieber** [comment]
From https://stackoverflow.com/questions/73933728/how-to-tell-expo-to-install-npm-dependencies-with-legacy-peerdeps-option#answer-74268002

1. Create a .npmrc file in the project root and add `force=true` or `legacy-peer-deps=true`
2. In package.json, add ` "eas-build-pre-install": "npm config set legacy-peer-deps true"` to `scripts`

**Comment by izakdvlpr** [comment]
> [@EmePin](https://github.com/EmePin) [@osamwelian3](https://github.com/osamwelian3) From [stackoverflow.com/questions/73933728/how-to-tell-expo-to-install-npm-dependencies-with-legacy-peerdeps-option#answer-74268002](https://stackoverflow.com/questions/73933728/how-to-tell-expo-to-install-npm-dependencies-with-legacy-peerdeps-option#answer-74268002)
> 
> 1. Create a .npmrc file in the project root and add `force=true` or `legacy-peer-deps=true`
> 2. In package.json, add ` "eas-build-pre-install": "npm config set legacy-peer-deps true"` to `scripts`

Thanks, it worked here.
