### ISSUE TITLE
iOS build fails when changing app entry

### ISSUE THREAD

**Issue by heidgert** [expo/eas-cli#960]
### Build/Submit details page URL

https://expo.dev/accounts/heidgert/projects/eas-issue/builds/e5f75e64-f91f-43cf-80b5-b5a936782ed2

### Summary

When changing the main entry to a javascript file in the root folder (AppEntry.js) the build fails for iOS (works on Android).

Complete repo here:

https://github.com/heidgert/eas-issue

### Managed or bare?

Managed

### Environment

 EAS CLI 0.46.0 environment info:
    System:
      OS: Windows 10 10.0.19044
    Binaries:
      Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
    Utilities:
      Git: 2.28.0.
    npmPackages:
      expo: ~44.0.0 => 44.0.6
      expo-dev-client: ~0.8.3 => 0.8.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Project workflow: managed

### Error output

iOS build failed:
Fastlane build failed with unknown error. Please refer to the "Run fastlane" and "Xcode Logs" phases.
Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.

### Reproducible demo or steps to reproduce from a blank project

`expo init`
`expo install expo-dev-client`
`eas build:configure`

Create new file: AppEntry.js

```
import registerRootComponent from "expo/build/launch/registerRootComponent";

import App from "../../App";

registerRootComponent(App);
```

Edit package.json and set main to "AppEntry.js"

`eas build --profile development --platform ios`

**Comment by kbrandwijk** [comment]
Currently, customizing the app entry for EAS like this is not supported yet. More info here in the migration docs: https://docs.expo.dev/build-reference/migrating/#custom--main--entry-point-in
