### ISSUE TITLE
eas build -p ios fails with 

### ISSUE THREAD

**Issue by woltob** [expo/eas-cli#965]
### Summary

I receive this error in my build pipeline. Using the command eas build -p ios. I can provide the build details page if necessary.

### Managed or bare?

managed

### Environment

eas diagnostics

  EAS CLI 0.47.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.10.0 - /usr/local/bin/node
      Yarn: 1.22.17 - ~/.npm-global/bin/yarn
      npm: 7.24.0 - /usr/local/bin/npm
    Utilities:
      Git: 2.34.1 - /usr/local/bin/git
    npmPackages:
      @expo/webpack-config: ~0.16.2 => 0.16.16 
      expo: ^44.0.6 => 44.0.6 
      expo-dev-client: ~0.8.4 => 0.8.4 
      expo-updates: ~0.11.6 => 0.11.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.0.3
    Project workflow: generic

### Error output

I receive this error which is quite cryptic. Can anyone point me to a solution?

```
▸ ** ARCHIVE FAILED **

▸ The following build commands failed:

▸ 	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/MY-APP-NAME-gfpiycnwdqyjfaaiwqvnkfdyemxa/Build/Intermediates.noindex/ArchiveIntermediates/MY-APP-NAME/IntermediateBuildFilesPath/MY-APP-NAME.build/Release-iphoneos/MY-APP-NAME.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'MY-APP-NAME' from project 'MY-APP-NAME')

▸ (1 failure)

** ARCHIVE FAILED **

The following build commands failed:

	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/expo/Library/Developer/Xcode/DerivedData/MY-APP-NAME-gfpiycnwdqyjfaaiwqvnkfdyemxa/Build/Intermediates.noindex/ArchiveIntermediates/MY-APP-NAME/IntermediateBuildFilesPath/MY-APP-NAME.build/Release-iphoneos/MY-APP-NAME.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'MY-APP-NAME' from project 'MY-APP-NAME')

(1 failure)

Exit status: 65

+-------------+-------------------------+

|           Build environment           |

+-------------+-------------------------+

| xcode_path  | /Applications/Xcode.app |

| gym_version | 2.185.1                 |

| sdk         | iPhoneOS15.0.sdk        |

+-------------+-------------------------+

Looks like fastlane ran into a build/archive error with your project

It's hard to tell what's causing the error, so we wrote some guides on how

to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/

Before submitting an issue on GitHub, please follow the guide above and make

sure your project is set up correctly.

fastlane uses `xcodebuild` commands to generate your binary, you can see the

the full commands printed out in yellow in the above log.

Make sure to inspect the output above, as usually you'll find more error information there

[stderr] [!] Error building the application - see the log above

Error: Fastlane build failed with unknown error. Please refer to the "Run fastlane" and "Xcode Logs" phases.
Fastlane errors in most cases are not printed at the end of the output, so you may not find any useful information in the last lines of output when looking for an error message.
```

### Reproducible demo or steps to reproduce from a blank project

Will provide if no quick solution an be found.

**Comment by wkozyra95** [comment]
check xcode logs in the last section on the build page

`PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images` suggest that there is an error when building js bundle

**Comment by 610consulting** [comment]
This very problem occurs for me as well with the exact phrasing in the error description. Not really clear what goes wrong

**Comment by wkozyra95** [comment]
@610consulting check my answer above
