### ISSUE TITLE
Can not find file with path set to eas.json

### ISSUE THREAD

**Issue by imhazige** [expo/eas-cli#969]
### Summary

I use bash to create the file develop-google-services.json underneath the project root folder and set the env to "APP_ANDROID_FCM_JSON_PATH": "./develop-google-services.json",  but the expo eas build throw error.

### Managed or bare?

managed

### Environment

- Config syncing
✖ Config sync failed
[stderr] [04:51:24] [android.dangerous]: withAndroidDangerousBaseMod: Cannot copy google-services.json from /home/expo/workingdir/build/develop-google-services.json to /home/expo/workingdir/build/android/app/google-services.json. Please make sure the source and destination paths exist.

Is there any problem to this way.

## eas.json

```json
{
"cli": {
"version": ">= 0.47.0"
},
"build": {
"develop": {
"distribution": "store",
"releaseChannel": "develop_android_1.0.0_2",
"env": {
"UNIVERSAL_LINK_HOST": "webapp.dev.[REDACTED].com",
"APP_VERSION": "1.0.0",
"APP_BUILD_NUMBER": "2",
"APP_NAME": "FMClarity DEVELOP",
"APP_SLUG": "[REDACTED]_develop",
"APP_IOS_BUNDLE_ID": "com.[REDACTED].develop",
"APP_ANDROID_PACKAGE": "com.[REDACTED].develop",
"APP_ANDROID_FCM_JSON_PATH": "./develop-google-services.json",
"APP_API_BASEURL": "https://api.dev.[redacted].com/",
"BUGSNAG_API_KEY": "[REDACTED]",
"APP_DEBUG_APP_JSON": "true",
"RELEASE_CHANNEL": "develop_android_1.0.0_2",
"MY_BUILD_PROFILE": "develop"
}
}
},
"submit": {
"production": {}
}
}
```

android part on app.json

```json
android: {
    package: 'com.[REDACTED].develop',
    googleServicesFile: './develop-google-services.json',
    versionCode: 1000002,
    useNextNotificationsApi: true,
    permissions: [
      'CAMERA',
      'READ_EXTERNAL_STORAGE',
      'WRITE_EXTERNAL_STORAGE',
      'RECEIVE_BOOT_COMPLETED'
    ],
    intentFilters: [ [Object] ]
  },
```

### Reproducible demo or steps to reproduce from a blank project

- Config syncing
✖ Config sync failed
[stderr] [04:51:24] [android.dangerous]: withAndroidDangerousBaseMod: Cannot copy google-services.json from /home/expo/workingdir/build/develop-google-services.json to /home/expo/workingdir/build/android/app/google-services.json. Please make sure the source and destination paths exist.

**Comment by kbrandwijk** [comment]
Are you running the EAS build locally, or on the server? And can you share the script you use to create the file?

**Comment by imhazige** [comment]
Hey, @kbrandwijk 

I am running on bitrise, so it  on server.

**Comment by imhazige** [comment]
OK, nvm, it is the .gitignore, the android will be affect by it.

After remove it, it works. Thanks.

**Comment by bryanltobing** [comment]
> Are you running the EAS build locally, or on the server? And can you share the script you use to create the file?

Hi @kbrandwijk , I bump into this issue today. I run EAS build locally via `--local` flag

I wanted to build android `apk` via local EAS build using this command

```bash
eas build -p android --profile preview --local
```

but i got this issue

```
[stderr] [04:51:24] [android.dangerous]: withAndroidDangerousBaseMod: Cannot copy google-services.json from /home/expo/workingdir/build/develop-google-services.json to /home/expo/workingdir/build/android/app/google-services.json. Please make sure the source and destination paths exist.
```

any idea why that's happen?
