### ISSUE TITLE
AppStoreConnect url uses wrong `ascAppId` when using multiple profiles

### ISSUE THREAD

**Issue by IjzerenHein** [expo/eas-cli#975]
### Build/Submit details page URL

https://expo.dev/accounts/onairevents/projects/onair_mobile/submissions/918d9216-915c-473c-8c01-4ba07c4e5f4a

### Summary

I've succesfully used `eas build --platform=ios --profile=development` to build a project. After that I've used `eas submit --platform ios` to submit it to the app-store. The submission was succesful, however the `https://appstoreconnect.apple.com...` URL displayed here was wrong. It displayed the `ascAppId` from the *production* profile, rather than from the *development* profile which I had build.

### Managed or bare?

bare

### Environment

```
EAS CLI 0.47.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.0 - ~/.volta/tools/image/node/16.13.0/bin/node
      Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
      npm: 8.1.0 - ~/.volta/tools/image/node/16.13.0/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: ^43.0.0 => 43.0.2
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.2 => 0.64.2
      react-native-web: 0.17.1 => 0.17.1
» ios: paths-project-pbxproj: Found multiple project.pbxproj file paths, using "ios/OnAir.xcodeproj/project.pbxproj". Ignored paths: ["submodules/onair_frontend-mobile-theoplayer/ios/RNTheoPlayer/RNTheoPlayer.xcodeproj/project.pbxproj"]
    Project workflow: generic
```

### Error output

```
✔ Submitted your app to Apple App Store Connect!

Your binary has been successfully uploaded to App Store Connect!
- It is now being processed by Apple - you will receive an e-mail when the processing finishes.
- It usually takes about 5-10 minutes depending on how busy Apple servers are.
- When it’s done, you can see your build here: https://appstoreconnect.apple.com/apps/1594595623/appstore/ios
```

URL `https://appstoreconnect.apple.com/apps/1594595623/appstore/ios` is incorrect, should have been `https://appstoreconnect.apple.com/apps/1605573078/appstore/ios`

### Reproducible demo or steps to reproduce from a blank project

- Create `eas.json` with multiple profiles and multiple iOS `ascAppId` fields
- `eas build --platform ios --profile=development`
- `eas submit --platform ios`

*eas.json*
```
{
    "cli": {
        "version": ">= 0.46.0"
    },
    "build": {
        "development": {
            "releaseChannel": "development",
            "distribution": "store",
            "ios": {
                "buildConfiguration": "Release",
                "scheme": "OnAir"
            }
        },
        "staging": {
            "releaseChannel": "staging",
            "distribution": "store",
            "ios": {
                "buildConfiguration": "Release - Staging",
                "scheme": "STAGING - OnAir"
            }
        },
        "production": {
            "releaseChannel": "production",
            "distribution": "store",
            "ios": {
                "buildConfiguration": "Release - Production",
                "scheme": "PROD - OnAir"
            }
        }
    },
    "submit": {
        "development": {
            "ios": {
                "appleId": "...",
                "ascAppId": "1605573078",
                "appleTeamId": "..."
            }
        },
        "staging": {
            "ios": {
                "appleId": "...",
                "ascAppId": "1605573355",
                "appleTeamId": "..."
            }
        },
        "production": {
            "ios": {
                "appleId": "...",
                "ascAppId": "1594595623",
                "appleTeamId": "..."
            }
        }
    }
}
```

**Comment by wkozyra95** [comment]
When you run `eas submit --platform ios` it's using production profile, so `1594595623` is correct. If you check submit logs you can see the line "Ready to upload new build to TestFlight (App: 1594595623)".

Based on your description I'm assuming that submit affected app `1605573078`, is that correct?
I'm not sure why it works, but it's possible that the transporter is ignoring the id that we are passing and is uploading based on bundle identifier read from ipa.

**Comment by IjzerenHein** [comment]
Still looks like a bug to me (but totally not critical). Do you need any more information from me?

**Comment by wkozyra95** [comment]
> Still looks like a bug to me 

This behavior is intentional (maybe with the exception that submit should fail, but we don't really have control over that) and help output for submitting command is clear about it.

```
--profile=<value>         Name of the submit profile from eas.json. Defaults to "production" if defined in eas.json.
```

If you have any ideas on how we could make it clear that the profile needs to be passed, I'm open to suggestions, but we are not planning to change this behavior.
