### ISSUE TITLE
[linux] eas build asks to login to apple every time

### ISSUE THREAD

**Issue by OneOfOne** [expo/eas-cli#981]
### Summary

Trying to move build system from expo build to eas build and it asks to login to apple and select the team every time.

Is there a way to pass the team id like with expo build?

### Managed or bare?

managed

### Environment

```
  EAS CLI 0.47.0 environment info:
    System:
      OS: Linux 5.16 Arch Linux
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 17.5.0 - /bin/node
      Yarn: 1.22.15 - /bin/yarn
      npm: 8.5.0 - /bin/npm
    Utilities:
      Git: 2.35.1 - /bin/git
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      expo-dev-client: ^0.8.4 => 0.8.4 
      expo-updates: ~0.11.6 => 0.11.6 
      react: ^17.0.1 => 17.0.2 
      react-dom: ^17.0.1 => 17.0.2 
      react-native: ^0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1
    Project workflow: managed
```

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by wkozyra95** [comment]
if you already have credentials configured you can skip this and all other prompts by running with flag `--non-interactive`

**Comment by robertherber** [comment]
> if you already have credentials configured you can skip this and all other prompts by running with flag `--non-interactive`

I use non-interactive for CI builds - but would also like a way to configure those parameters through config files/environment variables. 

Especially when experimenting with expo plugins/native libs it's frustrating to have to retype the same things that seldom changes every time (dev team, devices, push notifications) - and non-interactive doesn't cut it for those cases since it often requires updates to certificates etc.

**Comment by michaek** [comment]
I would like to second the request to more closely mirror the behavior of `expo build`, which accepted a `--team-id` argument. The documentation suggests that this is also not configurable by using a profile, as appleTeamId is available for [submit](https://docs.expo.dev/submit/eas-json/) configuration, but not for [build](https://docs.expo.dev/build/eas-json/).
