### ISSUE TITLE
EAS not accepting npm fontawesome 

### ISSUE THREAD

**Issue by tb42** [expo/eas-cli#983]
### Build/Submit details page URL

https://expo.dev/accounts/thomasb123/projects/Temple/builds/963f6688-278b-45fe-8cd5-db803422b8bf

### Summary

I’m encountering a build error with eas for iOS. It’s firing a 401 unauthorized error for an npm fontawesome package. I’ve followed the fontawesome .npmrc guidelines ([here](https://fontawesome.com/docs/web/setup/packages#configure-access)) and eas does not like it.

### Managed or bare?

managed

### Environment

  EAS CLI 0.47.0 environment info:
    System:
      OS: macOS 12.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.13.1 - /usr/local/bin/node
      npm: 8.1.2 - /usr/local/bin/npm
    Utilities:
      Git: 2.32.0 - /usr/bin/git
    npmPackages:
      expo: ^44.0.0 => 44.0.6 
      react: ^17.0.2 => 17.0.2 
      react-dom: ^17.0.2 => 17.0.2 
      react-native: ^0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.0.3
    Project workflow: managed

### Error output

![image](https://user-images.githubusercontent.com/16248244/155030941-0d5bfb6a-feeb-4e5d-93c1-17d813c1214b.png)

### Reproducible demo or steps to reproduce from a blank project

Running eas iOS build after installing fontawesome-reactNative with npm

**Comment by wkozyra95** [comment]
https://docs.expo.dev/build-reference/private-npm-packages/

You need to pass that token to eas builder, I don't see you passing it anywhere

**Comment by tb42** [comment]
Okay, what's the proper syntax for the expo secret? I've tried multiple variations and it's still firing a build error.  
In the expo doc link you provided it shows that the output will be 
```
"//registry.npmjs.org/:_authToken=**${NPM_TOKEN}**
registry=https://registry.npmjs.org/"
```
Setting the Expo secret with the full npm registry provided from the FontAwesome docs, see below, does not work, neither does putting just my api token. What's the correct syntax?

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken={Token}
```

**Comment by wkozyra95** [comment]
> In the expo doc link you provided it shows that the output will be

no, config snippet you added in your comment is neither in eas docs nor in fontawesome you linked to

IT should be just like it's in both docs
```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
```
where FONTAWESOME_NPM_AUTH_TOKEN is name of the env variable (in eas case it's name of the secret)

**Comment by wkozyra95** [comment]
> The expo docs you linked to says it automatically creates an npmrc file via eas secrets. Are you saying that's not the case and I need to create the npmrc file manually and then link the token via eas secrets?

from the docs : "However, this only happens when you don't already have an .npmrc in your project's root directory."
if you have your own npmrc eas will not create it

automatically created npmrc is configured for private packages in npm registry, you want to use different registry no the one from npm

**Comment by tb42** [comment]
Ok that seems to have resolved that issue, but now another one has popped up. Please advise on how to resolve the issue below:

```
Running yarn in the root dir of your repository 

yarn install v1.22.17

[1/4] Resolving packages...

[2/4] Fetching packages...

[stderr] error An unexpected error occurred: "Commit hash required".

info If you think this is a bug, please open a bug report with the information provided in "/Users/expo/workingdir/build/yarn-error.log".

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

yarn exited with non-zero code: 1
```

**Comment by tb42** [comment]
@wkozyra95
