### ISSUE TITLE
expo url:apk returning wrong url when using eas build command

### ISSUE THREAD

**Issue by juaal12** [expo/eas-cli#988]
### Summary

So time ago we changed expo build to the new released eas build (expo-cli to eas-cli). On our project we run the following command:  `eas build --profile preview --platform android --non-interactive`. Build finishes properly and we get our package *.apk on expo.dev. We can download it and it works fine in our android devices.

We use TeamCity CI for automating some tasks so after executing  `eas build --profile preview --platform android --non-interactive` we execute `expo url:apk` for downloading the package on our system. This command is always returning an url which responds with 403 forbidden. Concerning this issue we have noticed this:

- EAS Build Package: When on expo.dev we download the package we have this url => https://turtle-v2-artifacts.s3.amazonaws.com/android/.../*.apk
- EXPO Build Package: When on expo.dev we download the package we have this url => https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/../*.apk

Using `expo url:apk` we are expecting to get EAS Build Package download url but we are not getting it. Instead of this url we are getting EXPO Build Package download url. So this is making our CI to fail.

Is there any way to get EAS Build Package download url?

### Managed or bare?

Managed

### Environment

expo: "43.0.3",
eas-cli: "0.42.4",
expo-cli: "5.2.0"

### Reproducible demo or steps to reproduce from a blank project

Run following commands:

- eas build --profile preview --platform android --non-interactive
- expo url:apk

Try to open generated url. You will get an error.

**Comment by wkozyra95** [comment]
expo-cli was used to interact with old build service, eas-cli is interacting with `EAS Build`. Those cli tools are not interchangeable, if you are using `EAS Build` you need to use eas-cli for everything build related and `expo-cli` only for local development e.g. `expo start` (and OTA updates if you are using them)

You are getting 403 because it's probably showing up URL to apk that was built with `expo build:android` and it expired(artifacts are stored for 30 days)

**Comment by juaal12** [comment]
@wkozyra95 Yeah, you are right, my bad. I am sorry.

But how could I be able to get my package url? I've been reading the docs and I cannot find the proper command for doing it. Could you help me with this?

**Comment by wkozyra95** [comment]
```
eas build:list --json --limit=1 --platform=android | jq '.[0].artifacts.buildUrl'
```

**Comment by rajasekhar1404** [comment]
> ```
> eas build:list --json --limit=1 --platform=android | jq '.[0].artifacts.buildUrl'
> ```
this worked for me, also if you want to extract the url without double quotations use -r, 
OUTPUT=$(eas build:list --json --limit=1 --non-interactive | jq -r '.[0].artifacts.buildUrl')
