### ISSUE TITLE
Doesn't track the app.json (versionCode and version)

### ISSUE THREAD

**Issue by nihil-pro** [expo/eas-cli#989]
### Build/Submit details page URL

https://expo.dev/accounts/nihil_pro/projects/avtodokaApp/builds/f6682a6f-c847-4c21-af85-c953fda343e3

### Summary

Eas build doesn't track the app.json (versionCode and version)

### Managed or bare?

Managed

### Environment

EAS CLI 0.47.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.9.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.24.0 - /usr/local/bin/npm
    Utilities:
      Git: 2.26.2 - /usr/local/bin/git
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.0.3
    Project workflow: generic

### Reproducible demo or steps to reproduce from a blank project

So,  i changed the js Engine, because of Intl. I took hermes for android. Eas is required for Hermes. I installed it.
Then i changed the version and android version Number in app.json
Then ran easy build -p android. I saw old version in expo build:
<img width="1162" alt="Screenshot 2022-02-25 at 21 58 33" src="https://user-images.githubusercontent.com/39807476/155772500-18ed87c4-e850-45c5-90e4-000b2b0502c2.png">
but logs showed correct version: 
<img width="609" alt="Screenshot 2022-02-25 at 22 01 22" src="https://user-images.githubusercontent.com/39807476/155772694-c78116f8-7844-4f31-b845-f5c73181039f.png">
and i tried to deploy it to play market but get an error 
<img width="647" alt="Screenshot 2022-02-25 at 22 05 46" src="https://user-images.githubusercontent.com/39807476/155773261-0cfe199e-a6fe-46a0-bc38-5754afd8628c.png">

**Comment by kbrandwijk** [comment]
Your diagnostics show `Project workflow: generic`, which means that you have an `android` and `ios` folder in your project. In that case, you are responsible for making the changes to the native files yourself.

If you have not made any manual changes to any files in those native folders at all, you can also opt to delete them to go back to managed mode, after which all your changes to app.json will be automatically applied again.

**Comment by nihil-pro** [comment]
Understood, thanks. 
I created the app with expo init, and those directories was created automatically after first build. I feel something can broke if I’ll remove them

**Comment by wodin** [comment]
@nihil-pro I suspect you used `expo run:android` or `expo run:ios`. This has the side effect of adding the native code to your app.
If you manually make changes to the files under `android` and `ios` then Expo can no longer manage things like the version number updates for you automatically.
There are three ways to proceed:
1. Continue manually updating these native files like a normal React Native app; or
2. Keep the native code, but use `expo prebuild --clean` to regenerate them if you make changes to `app.json`; or
3. Delete the native code. When you use `eas build`, the native code will be generated (using `expo prebuild`) on the build servers

So if you do not need to make your own changes to the native code, I would personally go with option 3.

**Comment by Darmolar** [comment]
> @nihil-pro I suspect you used `expo run: android` or `expo run:ios`. This has the side effect of adding the native code to your app. If you manually make changes to the files under `android` and `ios` then Expo can no longer manage things like the version number updates for you automatically. There are three ways to proceed:
> 
> 1. Continue manually updating these native files like a normal React Native app; or
> 2. Keep the native code, but use `expo prebuild --clean` to regenerate them if you make changes to `app.json`; or
> 3. Delete the native code and let Expo manage it for you when you run `eas build`. If the native code does not exist in your project when you run `eas build`, it will be generated (using `expo prebuild`) on the build servers. If you want more details on how the Expo build servers work, see [Android build process](https://docs.expo.dev/build-reference/android-builds/) and [iOS build process](https://docs.expo.dev/build-reference/ios-builds/)
> 
> So if you do not need to make your own changes to the native code, I would personally go with option 3. I would also avoid using `expo run` for building the app unless I was trying to debug some build errors. I would instead use `eas build` or `eas build --local` to build the app or dev client, because `eas build` does not have the side effect of adding native code to your project.

Thanks very much, you just saved from 3 days issue I have

**Comment by suyashvash** [comment]
> Your diagnostics show `Project workflow: generic`, which means that you have an `android` and `ios` folder in your project. In that case, you are responsible for making the changes to the native files yourself.
> 
> If you have not made any manual changes to any files in those native folders at all, you can also opt to delete them to go back to managed mode, after which all your changes to app.json will be automatically applied again.

Thanks man! I deleted the ios folder (only ) and now it is updating based on app.json.

**Comment by seferdemirci** [comment]
@suyashvash if you have custom configurations in the /ios or /android folder, such as AppClip, StoreKit.storekit or PrivacyInfo,xcprivacy, do not include "--clean" in your "expo prebuild" command. The comments above do not mention this, but I learned it through bitter experience.
