### ISSUE TITLE
Problem with dependencies of installed packages 

### ISSUE THREAD

**Issue by nihil-pro** [expo/eas-cli#990]
### Build/Submit details page URL

https://expo.dev/accounts/nihil_pro/projects/avtodokaApp/builds/36ffd9f5-3e3c-4b0b-9dea-80fc3ecbad6c

### Summary

When i build with eas build, i get a lot of errors like this: 
`Error: Unable to resolve module react-native-svg from /home/expo/workingdir/build/node_modules/react-native-chart-kit/dist/AbstractChart.js: react-native-svg could not be found within the project or in these directories:`

It is a good behaviour? I think isn't. If i installed a dependency with npm, i expect that dependencies of this dependency would be also installed.

### Managed or bare?

Bare

### Environment

```
EAS CLI 0.47.0 environment info:
    System:
      OS: macOS 12.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.9.1 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 7.24.0 - /usr/local/bin/npm
    Utilities:
      Git: 2.26.2 - /usr/local/bin/git
    npmPackages:
      expo: ~44.0.0 => 44.0.6 
      expo-updates: ~0.11.6 => 0.11.6 
      react: 17.0.1 => 17.0.1 
      react-dom: 17.0.1 => 17.0.1 
      react-native: 0.64.3 => 0.64.3 
      react-native-web: 0.17.1 => 0.17.1 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.0.3
    Project workflow: generic
```

### Error output

1)
```
Error: Unable to resolve module react-native-svg from /home/expo/workingdir/build/node_modules/react-native-chart-kit/dist/AbstractChart.js: react-native-svg could not be found within the project or in these directories:
  node_modules/react-native-chart-kit/node_modules
  node_modules
If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
  31 | };
  32 | import React, { Component } from "react";
> 33 | import { Defs, Line, LinearGradient, Stop, Text } from "react-native-svg";
```

2)
```
Error: Unable to resolve module @react-native-community/segmented-control from /home/expo/workingdir/build/node_modules/@ant-design/react-native/lib/segmented-control/segmented.ios.js: @react-native-community/segmented-control could not be found within the project or in these directories:
  node_modules/@ant-design/react-native/node_modules
  node_modules
```
etc

### Reproducible demo or steps to reproduce from a blank project

eas build -p android

**Comment by kbrandwijk** [comment]
`react-native-chart-kit` defines `react-native-svg` as a peerDependency. It also literally mentions in the installation instructions that you need to install it yourself https://github.com/indiespirit/react-native-chart-kit#import-components. This has nothing to do with EAS, or Expo in general.
