### ISSUE TITLE
What does --skip-project-configuration use for? Document need enhancement!

### ISSUE THREAD

**Issue by imhazige** [expo/eas-cli#994]
### Do you understand that any feature requests opened in this repository will be closed?

Yes

==============

Does it mean will not create eas.json?
In my project, I will create it by a script, so I want to know if I need turn this option on.

**Comment by wkozyra95** [comment]
In the past it was used to block eas-cli from making changes to the native code, currently, it does not do anything and it should be removed.

> In my project, I will create it by a script, so I want to know if I need turn this option on.

`eas build` creates eas.json only if it does not exist, so it doesn't matter whether you have eas.json in repo or creating on the fly.
