### ISSUE TITLE
EAS: Apple Developer account needed while it should be optional

### ISSUE THREAD

**Issue by iboxgithub** [expo/eas-cli#997]
### Do you understand that any discussions or questions opened as issues in the core Expo repository will be closed?

Yes

**Comment by iboxgithub** [comment]
UPDATE: I get that to have local build this needs to be followed: [eas-update/getting-started/](https://docs.expo.dev/eas-update/getting-started/)
then: eas build --platform ios --local --profile development

I just think the CLI message here should be more explicit, it should detect when a non-local build is attempted, and in this case not display "`Do you want to log in to your Apple account?`" but "`You are attempting an online build, an Apple account is necessary, please type your credentials below (if you only want to build locally please follow these instructions: link)`"

**Comment by wkozyra95** [comment]
> I just think the CLI message here should be more explicit, it should detect when a non-local build is attempted, and in this case not display "Do you want to log in to your Apple account?" but "You are attempting an online build, an Apple account is necessary, please type your credentials below (if you only want to build locally please follow these instructions: link)"

local or non-local builds have no impact on this requirement of having and apple account, when you build a release build you should be prompted if you want to provide those values manually, but for internal distribution, you need to log in because we need to generate new provisioning profile with all your registered devices.

I agree those messages should be clarified.

**Comment by iboxgithub** [comment]
> > I just think the CLI message here should be more explicit, it should detect when a non-local build is attempted, and in this case not display "Do you want to log in to your Apple account?" but "You are attempting an online build, an Apple account is necessary, please type your credentials below (if you only want to build locally please follow these instructions: link)"
> 
> local or non-local builds have no impact on this requirement of having and apple account, when you build a release build you should be prompted if you want to provide those values manually, but for internal distribution, you need to log in because we need to generate new provisioning profile with all your registered devices.
> 
> I agree those messages should be clarified.

aligned, should I close this thread or do you recommend keeping it open until the messages are updated?

**Comment by wkozyra95** [comment]
let's keep it open

**Comment by adem-usta** [comment]
Hi all !

I am currently trying to build an iOS app and try it with Expo Go, but I can't build it without having an apple developer account with a paid plan.. 

My understanding of expo was: I make an app with react-native, I use Expo to let it build for me for all the platforms and test them with Expo Go, and then if I want to publish the apps on stores, in this case I need developer account with a paid plan (for iOS for example).

PS: I work on a linux machine, if that matters ...

Am I wrong ? I have exactly the same problem as @iboxgithub , so I decided to write about my problem here ..

**Comment by iboxgithub** [comment]
@adem-usta if you read the thread you will see I shared the proper commands to use.

**Comment by adem-usta** [comment]
Yes, I read the thread and that does not work: --local cannot work for me as I am on a linux machine.

But my question is: do I need an apple account with a paid plan to let expo build an app for me ? Even if I do not need to publish it (at the moment) on the app store ?

If yes, this is clearly a blocking situation for me ...

**Comment by wkozyra95** [comment]
@adem-usta You don't need to login to apple in eas-cli, but you need to have paid apple account to build anything other than simulator build. To build on EAS you have 2 options, either login to apple or provide all the credentials manually, the only exception is an internal distribution build where you have to login in to apple in eas-cli.

> My understanding of expo was: I make an app with react-native, I use Expo to let it build for me for all the platforms and test them with Expo Go,

You can test your apps on Expo Go without apple account, but to build the production ipa or custom developer client you need to have it.

**Comment by adem-usta** [comment]
I came to the same conclusion.. I can’t build my app and test it with expo go if I don’t have an apple developer account. The only way to test my app on iOS is to start the development server locally, have my smartphone on the same network and scan the qrcode given .. 

This is clearly a blocking situation. Why do we need an apple developer account if we do not submit anything to the apple servers ? Is it mandatory for building an app on iOS ?

**Comment by wkozyra95** [comment]
> I can’t build my app and test it with expo go

You don't need to build your app to test it with expo go, just run `expo start` and scan qr code

> Why do we need an apple developer account if we do not submit anything to the apple servers ? Is it mandatory for building an app on iOS ?

Apple does not allow sideloading, to install app on a physical iPhone it needs to be signed with distribution certificate that can be generated only if you have paid apple account. With a free apple account, you can build app signed with developer certificates, but you need to build it from xcode(we do not support it in eas because it would require rebuilds every time because developer certificates have a short expiration time)

**Comment by adem-usta** [comment]
What if I want my clients to test the app with Expo Go without having a paid account ? With your explanation, I guess that I cannot. Or, I start the expo server and give access to it via a tunnel or something.

Thank you @wkozyra95 for your clear answers !

**Comment by wkozyra95** [comment]
you can run `expo publish` and send your client URL to the project `https://expo.dev/@account_name/slug`
https://docs.expo.dev/guides/sharing-preview-releases/#expo-go

You will need to invite them to your expo team/organisation, if you have multiple clients and don't want all of them to have access to all apps you will need create separate organisations for different clients/apps

**Comment by crystalball808** [comment]
Hello there. I have a similar problem with Apple Developer account needed even if I choose not to log in.
eas-cli version: 2.6.0
command: `eas build -p ios --profile production`

**Comment by jmammri** [comment]
@wkozyra95 This is what I did, previously, but now SDK 44 is deprecated and from 45 on, the 'classic' way with `expo publish` isn't working anymore. 
So I'm forced to work with the newer 'eas'-stuff, that makes it impossible to let my clients (with iphones) test my app, when I'm not paying for the apple development account, right?

So is there any way around this without paying for the apple dev-account or having my clients in the same network as my PC, like it used to be with `expo publish`?

**Comment by nmateo** [comment]
Same problem here.
Please allow build without developer ID...

**Comment by randyzhao** [comment]
Why is this issue closed?

**Comment by AbhayAysola** [comment]
> So is there any way around this without paying for the apple dev-account or having my clients in the same network as my PC, like it used to be with `expo publish`?

Same question here, hope this gets resolved

**Comment by TheGithubJoshua** [comment]
> Yes, I read the thread and that does not work: --local cannot work for me as I am on a linux machine.
> 
> But my question is: do I need an apple account with a paid plan to let expo build an app for me ? Even if I do not need to publish it (at the moment) on the app store ?
> 
> If yes, this is clearly a blocking situation for me ...

Use darling it can run xcode commandline tools and other commandline programs on linux

**Comment by rodrimarchese** [comment]
I figure to solve the issue using this in the eas.json, and running:
`eas build -p ios --profile preview` to build
<img width="408" alt="image" src="https://github.com/expo/eas-cli/assets/32769860/24cc1a61-fb1c-4ee7-879d-980fcf0cfb20">

**Comment by lukexrout** [comment]
why isn't the ability there when building using eas and just get the built ios code? i.e. compilation into swift or objective c.

**Comment by fo-fo** [comment]
The documentation for this use case is not good at all, and took me a while to figure it out, but if you want to distribute your app for testing with Expo Go, you can simply use `eas update`, for example: `eas update --branch preview --message 'my new version'`

This command will build the JS bundle locally and it will host it at Expo's servers. You can find the link / QR code under "Updates" by logging into https://expo.dev with your Expo account.

It's not required to use `eas build` before `eas update`.

**Comment by nico-gao** [comment]
@fo-fo 

This is what I did as well. I also wanted to put the preview qrcodes of the eas updates on a website to share with people. But so far I couldn't find a way to generate those qrcodes for the most recent update, other than doing it manually. It seems like a build is required to generate qrcodes with their endpoint (https://docs.expo.dev/develop/development-builds/development-workflows/), and to do that an apple developer account is required.

**Comment by nico-gao** [comment]
> The documentation for this use case is not good at all, and took me a while to figure it out, but if you want to distribute your app for testing with Expo Go, you can simply use `eas update`, for example: `eas update --branch preview --message 'my new version'`
> 
> This command will build the JS bundle locally and it will host it at Expo's servers. You can find the link / QR code under "Updates" by logging into https://expo.dev with your Expo account.
> 
> It's not required to use `eas build` before `eas update`.

This is what I did as well. I also wanted to put the preview qrcodes of the eas updates on a website to share with people. But so far I couldn't find a way to generate those qrcodes for the most recent update, other than doing it manually. It seems like a build is required to generate qrcodes with their endpoint (https://docs.expo.dev/develop/development-builds/development-workflows/), and to do that an apple developer account is required.

**Comment by SmartDevSource** [comment]
> I figure to solve the issue using this in the eas.json, and running: `eas build -p ios --profile preview` to build <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/32769860/248084009-24cc1a61-fb1c-4ee7-879d-980fcf0cfb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NjM3MTAsIm5iZiI6MTcwOTQ2MzQxMCwicGF0aCI6Ii8zMjc2OTg2MC8yNDgwODQwMDktMjRjYzFhNjEtZmIxYy00ZWU3LTg3OWQtOTgwZmNmMGNmYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDEwNTY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YmM4NzkyY2JiNjNlZDZlODNmZWU1Y2M0NTVjMWZjM2VmYzM5OWE0Y2RjMmZkZGY4NzhlZjk5ZjRjNDhhNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sm6Bj5HaX7ps8mKRgcSKx-KALzLxatttO7S1oj3ucXc">

You're the best !

**Comment by vedmant** [comment]
React Native can be run on user iOs device without paid account [click](https://sugandsingh5566.medium.com/connecting-a-real-ios-device-to-xcode-for-react-native-development-a-step-by-step-guide-c0e3817a1893) . Why then expo build cannot be run? For example for my purpose I need to test background location tracking, and this is not working with Expo Go only with development build.

**Comment by axhatem** [comment]
> I figure to solve the issue using this in the eas.json, and running: `eas build -p ios --profile preview` to build <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/32769860/248084009-24cc1a61-fb1c-4ee7-879d-980fcf0cfb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMzUwMzgsIm5iZiI6MTcxMTIzNDczOCwicGF0aCI6Ii8zMjc2OTg2MC8yNDgwODQwMDktMjRjYzFhNjEtZmIxYy00ZWU3LTg3OWQtOTgwZmNmMGNmYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDIyNTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMDNhNzRmZjA2OTdiZTVmZjZiOTAxNWExNDYxYTBmNzRlM2IyZjFkNGU0MDY2YmUyYjdiNjBmYTMzNzcyMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dtm1Uz844sYSpAP6MXvkFwAX5i0HlQy8_b0oNdz0yHA">

Thanks, finally this was what I was looking for and I think many other people too.

**Comment by yhmyhm0910** [comment]
> I figure to solve the issue using this in the eas.json, and running: `eas build -p ios --profile preview` to build <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/32769860/248084009-24cc1a61-fb1c-4ee7-879d-980fcf0cfb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NzQ3NDksIm5iZiI6MTcxNTU3NDQ0OSwicGF0aCI6Ii8zMjc2OTg2MC8yNDgwODQwMDktMjRjYzFhNjEtZmIxYy00ZWU3LTg3OWQtOTgwZmNmMGNmYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA0MjcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTUyZWRlYTcwMDgwMTA3ZjU0NDhlZDNmNjM1ZmU5N2I0N2QxYzc4M2JjMDkzZTAxYzczMzEyYTM1MDdlNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hujYPRD_v3pAQP10W9mZL4mPLjN3NfMc4M1xyiYRRI0">

I do not have an Apple developer account and now trying to run my app on my own iPhone with this solution. It can be built successfully but after scanning the QR code, my iPhone will show "Unable to Install (app name) Please try again later."

**Comment by yhmyhm0910** [comment]
> > I figure to solve the issue using this in the eas.json, and running: `eas build -p ios --profile preview` to build <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/32769860/248084009-24cc1a61-fb1c-4ee7-879d-980fcf0cfb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NzQ3NDksIm5iZiI6MTcxNTU3NDQ0OSwicGF0aCI6Ii8zMjc2OTg2MC8yNDgwODQwMDktMjRjYzFhNjEtZmIxYy00ZWU3LTg3OWQtOTgwZmNmMGNmYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA0MjcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTUyZWRlYTcwMDgwMTA3ZjU0NDhlZDNmNjM1ZmU5N2I0N2QxYzc4M2JjMDkzZTAxYzczMzEyYTM1MDdlNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hujYPRD_v3pAQP10W9mZL4mPLjN3NfMc4M1xyiYRRI0">
> 
> I do not have an Apple developer account and now trying to run my app on my own iPhone with this solution. It can be built successfully but after scanning the QR code, my iPhone will show "Unable to Install (app name) Please try again later."

Only able to run my app inside Expo Go app with `eas update`. The app will be run locally inside Expo Go app. But not like an actual app on Homescreen.

**Comment by mgfouad** [comment]
> I figure to solve the issue using this in the eas.json, and running: `eas build -p ios --profile preview` to build <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/32769860/248084009-24cc1a61-fb1c-4ee7-879d-980fcf0cfb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MjkyODEsIm5iZiI6MTcyMzkyODk4MSwicGF0aCI6Ii8zMjc2OTg2MC8yNDgwODQwMDktMjRjYzFhNjEtZmIxYy00ZWU3LTg3OWQtOTgwZmNmMGNmYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDIxMDk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiN2ZkMTAyNzUxOWFmNWJlYmQ5MzI5NDhlODEyYzYwYzRkODNlODQwZDQ0MzFhZmY3MjM2ZDRhN2YzYjgwMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yvfJiS1Btpl0gf5BIDHtSKBikZCoO7mvcVJQ7qtxAaA">

you saved my life +1

**Comment by darul75** [comment]
> I figure to solve the issue using this in the eas.json, and running: `eas build -p ios --profile preview` to build <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/32769860/248084009-24cc1a61-fb1c-4ee7-879d-980fcf0cfb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjM5OTksIm5iZiI6MTcyNjEyMzY5OSwicGF0aCI6Ii8zMjc2OTg2MC8yNDgwODQwMDktMjRjYzFhNjEtZmIxYy00ZWU3LTg3OWQtOTgwZmNmMGNmYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA2NDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZTkzM2I3Njc0ZDc2ZGU3YmIzN2FhNzkyMzQyNGZhYzQ5ZGZjMmIxOTk3OTA4Yzg4OTIwNDZjNWU2OGE3YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gn6TFBaBwc7u8mleIqHQFQ2lpqxvbtJR80AG3tNfQEA">

also added `--local` and it worked like a charm

**Comment by progjonner77** [comment]
> I figure to solve the issue using this in the eas.json, and running: `eas build -p ios --profile preview` to build <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/32769860/248084009-24cc1a61-fb1c-4ee7-879d-980fcf0cfb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3MDE1MjcsIm5iZiI6MTcyOTcwMTIyNywicGF0aCI6Ii8zMjc2OTg2MC8yNDgwODQwMDktMjRjYzFhNjEtZmIxYy00ZWU3LTg3OWQtOTgwZmNmMGNmYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDE2MzM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNmJlNzQzMWFjYzJhYWRlZmRlYTNjYjMxNjY5YjFjYWNiMjA0MzJmYWU4NWQ4NGFkZjYxMjU4NDVjMGRhMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ttccAMCWhNdOkeoBaPdFlXFD_3dfUTIHxeevLHO-y4w">

You are still saving people thanks

**Comment by TerryChan** [comment]
> I figure to solve the issue using this in the eas.json, and running: `eas build -p ios --profile preview` to build <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/32769860/248084009-24cc1a61-fb1c-4ee7-879d-980fcf0cfb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MzY1MjksIm5iZiI6MTczMjUzNjIyOSwicGF0aCI6Ii8zMjc2OTg2MC8yNDgwODQwMDktMjRjYzFhNjEtZmIxYy00ZWU3LTg3OWQtOTgwZmNmMGNmYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDEyMDM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MjY4OWNhMGJlOTUwZGNhMTkwMjBmMGE0ZmZjNzAwODI0NjQ3MTkxMTYxNmYyZGViMTYyMzM3NWIwMzY4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IjdyoA9a2gaRaUrNSIF_aKDlvMp9T5xwnJYcyvwURIc">

But this generated .app package, not .ipa package that can install and run on real iPhone device. How to generate .ipa package with Apple Developer account that not paid?

**Comment by hypackel** [comment]
> > I figure to solve the issue using this in the eas.json, and running: `eas build -p ios --profile preview` to build <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/32769860/248084009-24cc1a61-fb1c-4ee7-879d-980fcf0cfb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MzY1MjksIm5iZiI6MTczMjUzNjIyOSwicGF0aCI6Ii8zMjc2OTg2MC8yNDgwODQwMDktMjRjYzFhNjEtZmIxYy00ZWU3LTg3OWQtOTgwZmNmMGNmYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDEyMDM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MjY4OWNhMGJlOTUwZGNhMTkwMjBmMGE0ZmZjNzAwODI0NjQ3MTkxMTYxNmYyZGViMTYyMzM3NWIwMzY4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IjdyoA9a2gaRaUrNSIF_aKDlvMp9T5xwnJYcyvwURIc">
> 
> But this generated .app package, not .ipa package that can install and run on real iPhone device. How to generate .ipa package with Apple Developer account that not paid?

you can create a new folder called `Payload` and put the .app there. then compress it into a zip and rename to an ipa.

**Comment by kubijo** [comment]
> > > I figure to solve the issue using this in the eas.json, and running: `eas build -p ios --profile preview` to build <img alt="image" width="408" src="https://private-user-images.githubusercontent.com/32769860/248084009-24cc1a61-fb1c-4ee7-879d-980fcf0cfb20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MzY1MjksIm5iZiI6MTczMjUzNjIyOSwicGF0aCI6Ii8zMjc2OTg2MC8yNDgwODQwMDktMjRjYzFhNjEtZmIxYy00ZWU3LTg3OWQtOTgwZmNmMGNmYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDEyMDM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MjY4OWNhMGJlOTUwZGNhMTkwMjBmMGE0ZmZjNzAwODI0NjQ3MTkxMTYxNmYyZGViMTYyMzM3NWIwMzY4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IjdyoA9a2gaRaUrNSIF_aKDlvMp9T5xwnJYcyvwURIc">
> > 
> > But this generated .app package, not .ipa package that can install and run on real iPhone device. How to generate .ipa package with Apple Developer account that not paid?
> 
> you can create a new folder called `Payload` and put the .app there. then compress it into a zip and rename to an ipa.

Can you please post the content of the file as text? The image is no longer loading, so the help is now useless.

**Comment by ibrust** [comment]
For the ignoramuses commenting - this is not an expo policy, it is an apple policy. You're complaining to the wrong people here.
