### ISSUE TITLE
EAS Update does not publish any new Expo Updates

### ISSUE THREAD

**Issue by y471n** [expo/eas-cli#998]
### Summary

I'm using EAS for configuring updates. The update isn't working. I tried the `eas update` command and got the result as well:

✔ Linked to project @team/something
✔ Please enter an update message. … test
✔ Built bundle!
✔ Uploaded assets!
✔ Published!
Then, running `eas update:list` also, shows the list and all the group IDs. But on opening/closing the Android app, no updates are detected.

### Managed or bare?

Bare

### Environment

expo-env-info 1.0.2 environment info:
    System:
      OS: macOS 12.2.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
      Yarn: 1.22.15 - ~/.nvm/versions/node/v16.9.1/bin/yarn
      npm: 7.24.2 - ~/.nvm/versions/node/v16.9.1/bin/npm
      Watchman: 2022.01.03.00 - /opt/homebrew/bin/watchman
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~44.0.2 => 44.0.6
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: ^0.17.1 => 0.17.5
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.2.0
    Expo Workflow: bare

### Reproducible demo or steps to reproduce from a blank project

NA

**Comment by byanes** [comment]
I am having the exact same issue. I posted it on the discord channel but no replies do far. Any ideas?

**Comment by y471n** [comment]
I guess, for managed workflow, you can try `expo publish`.

**Comment by shoes22** [comment]
If `eas update:list` is showing the published update and the client-side has been configured correctly, it is likely you are running into the same issue I filed a bug report about here: https://github.com/expo/eas-cli/issues/999

**Comment by byanes** [comment]
> I guess, for managed workflow, you can try `expo publish`.

Yes, that works for me, but I would still like to be able to update the app via `eas update`.

> If `eas update:list` is showing the published update and the client-side has been configured correctly, it is likely you are running into the same issue I filed a bug report about here: #999

For the client side, I run `eas update:configure`, which adds the `runtimeVersion` (set to `policy: "sdkVersion"`) and `updates.url` properties to my app.json. I also modified the eas.json file to include `channels` instead of `releaseChannels`. 

Running `eas update:list` shows that the update is published. It also looks like the update it's in the right branch, which is linked to the right channel. I don't think I am missing anything from the docs, so I might be running into the same issue you reported. 


<img width="1211" alt="Screen Shot 2022-03-03 at 11 20 46 AM" src="https://user-images.githubusercontent.com/7077269/156621212-0f06ea72-4552-4b00-8323-3c2c099f78ba.png">

**Comment by shoes22** [comment]
> If `eas update:list` is showing the published update and the client-side has been configured correctly, it is likely you are running into the same issue I filed a bug report about here: #999

@byanes @y471n 
Yesterday the Expo team deployed a server-side fix which resolved the issue I described above. Did it fix for you both too?

**Comment by byanes** [comment]
@shoes22 I actually just saw your message on discord, thanks for the heads up. Unfortunately It didn't fix it for me. 

Could you explain how did you print the results of `Updates.fetchUpdateAsync()` to the native device logs and how did you access them? Are you using sentry or something like that? I'm struggling to debug this.

**Comment by shoes22** [comment]
@byanes I used another library for that, react-native-native-log, https://www.npmjs.com/package/react-native-native-log . You can access your device logs through Flipper, logcat on Android, or through the Console on the Mac with any connected iOS device. (including simulators)

**Comment by byanes** [comment]
Thanks again @shoes22. I was able to debug the issue with the library you mentioned. My problem was that I was using version `44.0.0` of the Expo sdk, but the minimum required for eas update to work is `44.0.1`. So if anyone is having this issue, make sure you reference at least the minimum required version in the `sdkVersion` field of your app.json.

**Comment by wkozyra95** [comment]
@byanes eas update requires `44.0.1` expo package, field `sdkVersion` in app.json is not necessary but if it's set it should be set to `sdkVersion.0.0`, setting it to sth else most likely won't break anything but minor and patch versions are ignored in that field eitherway

**Comment by wkozyra95** [comment]
It looks like a server-side fix resolved that issue, if you are still experiencing this problem, please reopen the issue or create a new one.

**Comment by byanes** [comment]
Thanks for the clarification @wkozyra95. Unfortunately, the server-side fix didn't resolve my issue. if I remove `sdkVersion: 44.0.1` from my app.json the eas updates don't work, but setting it throws warnings in the console when running in Expo Go in ios and doesn't even let me run on android.

My package.json is pointing to `"expo": "^44.0.1",`,  but when I do an `eas build` without setting the `sdkVersion` in app.json the build shows up in the expo ui with runtime version `exposdk:44.0.0`.

<img width="577" alt="Screen Shot 2022-03-07 at 4 33 20 PM" src="https://user-images.githubusercontent.com/7077269/157065367-bb8d8c58-e8b2-4862-92b7-b547e956eead.png">

On the other hand, manually setting the `sdkVersion` to `44.0.1` shows runtime version `exposdk:44.0.1` in the build and eas updates work. Do you have any idea of why this would be the case?

**Comment by y471n** [comment]
Didn't work for me yet. The differences between my approaches are:
1. I'm using npm instead of yarn
2. I'm using `releaseChannels` instead of `channels` now because I can't the documentation again for using `releaseChannel`. And the build process was throwing issues for `channel`.
3. Instead of using `sdkVersion` I'm hardcoding runtime-version.

I see the build in `eas update:list` with all details of branch, groupId etc.

Any hints on what should I change?

**Comment by y471n** [comment]
Didn't work for me yet. The differences between my approaches are:
1. I'm using `npm` instead of `yarn`
2. I'm using `releaseChannels` instead of channels now because I can't the documentation again for using `releaseChannel`. And the build process was throwing issues for `channel`.
3. Instead of using `sdkVersion` I'm hardcoding runtime-version. I see the `eas update:list` with all details of branch, groupId etc.

I've the `sdkVersion` set to `44.0.2` on `app.json`.

Any hints on what should I change?
