### ISSUE TITLE
EAS Update uploads facing Cloudflare Access Denied Restriction

### ISSUE THREAD

**Issue by shoes22** [expo/eas-cli#999]
### Build/Submit details page URL

https://expo.dev/accounts/podopolo/projects/podopolo/updates/e2896f41-d8b3-4f84-bf7f-8229bef7d9e3

### Summary

I switched from the classic Expo Updates to EAS Update in our project, and it was working for a few days. The app detects the published update on update check, but it fails when trying to download the jsbundle, returning a Cloudflare Access Denied 1020 error. The messages are provided below.

### Managed or bare?

Bare

### Environment

  expo-env-info 1.0.2 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 16.10.0 - /usr/bin/node
      npm: 7.24.0 - /usr/bin/npm
    npmPackages:
      expo: >=44.0.0-0 <45.0.0 => 44.0.6 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.66.3 => 0.66.3 
      react-native-web: 0.17.5 => 0.17.5 
    npmGlobalPackages:
      eas-cli: 0.47.0
      expo-cli: 5.2.0
    Expo Workflow: bare

### Error output

Fetch Error:

```
error loading asset e46d5f70416941eb6286fa04f819ad29: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Access denied | assets.eascdn.net used Cloudflare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" type="text/css" media="screen,projection" />
```

iOS App Error:

`{"code":"ERR_UPDATES_FETCH","message":"Failed to download new update","domain":"EXUpdatesAppLoader","userInfo":{"NSLocalizedDescription":"Failed to load all assets"},"nativeStackIOS":["0   podopolo                            0x0000000102c13f33 RCTJSErrorFromCodeMessageAndNSError + 85","1   podopolo                            0x0000000102be36df __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.103 + 97","2   podopolo                            0x00000001029fcef8 __29-[EXUpdatesAppLoader _finish]_block_invoke_2 + 173","3   libdispatch.dylib                   0x0000000118af8876 _dispatch_call_block_and_release + 12","4   libdispatch.dylib                   0x0000000118af9a56 _dispatch_client_callout + 8","5   libdispatch.dylib                   0x0000000118b0008b _dispatch_lane_serial_drain + 718","6   libdispatch.dylib                   0x0000000118b00c31 _dispatch_lane_invoke + 400","7   libdispatch.dylib                   0x0000000118b0b6de _dispatch_workloop_worker_thread + 772","8`

Android App Error: 

`Failed to download asset with key 12fd2564711adafbc706aab38c4640aa
java.lang.Exception: Network request failed: error code: 1020
	at expo.modules.updates.loader.FileDownloader$downloadFileToPath$1.onResponse(FileDownloader.kt:67)
	at expo.modules.updates.loader.FileDownloader$downloadData$1.onResponse(FileDownloader.kt:351)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)`

### Reproducible demo or steps to reproduce from a blank project

Publish an update using EAS Update and try to download the update, the update fails with the error message above. Issue exists on both iOS and Android

**Comment by vlad-x** [comment]
Having the same problem with a managed app. All previous updates worked fine.

**Comment by ide** [comment]
This issue has been resolved as of 10 minutes or so ago. The root cause was that a credential shared between the EAS Update server and the CDN were encoded differently. This caused apps not to get valid asset download URLs.

The impact on production apps is that they wouldn't have been able to get new updates and would have loaded their last successfully downloaded update. We designed the expo-updates library this way since connections can fail for all sorts of reasons like unreliable internet in a subway tunnel or whenever a device has 0-1 bars of signal in general, or in this case when the global CDN doesn't serve an asset. Obviously high availability is better and enterprise SLAs for EAS Update will be a feature when the service comes out of preview so that the main source of network failures will be mobile internet connections and not EAS.

**Comment by aidankinzett** [comment]
hi, I am facing this same issue trying to load assets in our expo app. One of the URLs its trying to hit gave me this error:

```
I got an error when visiting assets.eascdn.net/FwJkAbrRNahBGX1KXnTAgiiwyzENu3D7DeEzCwmInyo?project=d83ee014-4714-4008-bbc0-ac1e7d7a62a3.

Error code: 1020
Ray ID: 7abb126beafa4874
Country: AU
Data center: bne01
IP: 2403:580c:7b:0:6d2e:ae0:e875:393e
Timestamp: 2023-03-22 02:40:47 UTC
```
